### ISSUE TITLE
implicitly_wait(30) generate a bug

### ISSUE THREAD

**Issue by jneb92jneb92** [mozilla/geckodriver#1003]
## System
* Version: geckodriver version : --> 0.16.1
* Platform: Linux 4.4.0-96-generic #119-Ubuntu SMP x86_64 x86_64 x86_64 GNU/Linux
* Firefox: 56.0
* Selenium: 3.4.3

## Testcase

No HTML code needed for this bug

## Stacktrace

the very first call on "self.driver = webdriver.Firefox()
        self.driver.implicitly_wait(30)" generate a bug.

======================================================================
ERROR: test_remote (__main__.Remote)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "sl-quickbooks.py", line 14, in setUp
    self.driver.implicitly_wait(30)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 767, in implicitly_wait
    'implicit': int(float(time_to_wait) * 1000)})
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 297, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
WebDriverException: Message: timeouts

**Comment by andreastt** [comment]
This has been fixed in more recent versions. Please try again with geckodriver 0.19.0.

**Comment by andreastt** [comment]
FWIW I’m happy to re-open if using 0.19.0 does not fix your problem.

**Comment by kirean** [comment]
Was on geckodriver 0.16.0 and encountered this. Works fine with 0.19.1 for me.
