### ISSUE TITLE
browser.manage.window.resize_to causes UnknownError with the message "setWindowRect"

### ISSUE THREAD

**Issue by mltsy** [mozilla/geckodriver#1004]
## System
* Version: 0.19.0
* Platform: Ubuntu 16.04
* Firefox: 56
* Selenium: Ruby gem selenium-webdriver 3.6.0

## Testcase

I don't think any HTML is necessary, just, from a minitest-capybara feature test case, I call `page.driver.browser.manage.window.resize_to(1024,768)` and I get a `Selenium::WebDriver::Error::UnknownError` with the message: `setWindowRect`

## Stacktrace
This is the ruby backtrace of the exception object:
```
/my_project/vendor/bundle/ruby/2.4.0/gems/selenium-webdriver-3.6.0/lib/selenium/webdriver/remote/response.rb:71:in `assert_ok'
/my_project/vendor/bundle/ruby/2.4.0/gems/selenium-webdriver-3.6.0/lib/selenium/webdriver/remote/response.rb:34:in `initialize'
/my_project/vendor/bundle/ruby/2.4.0/gems/selenium-webdriver-3.6.0/lib/selenium/webdriver/remote/http/common.rb:83:in `new'
/my_project/vendor/bundle/ruby/2.4.0/gems/selenium-webdriver-3.6.0/lib/selenium/webdriver/remote/http/common.rb:83:in `create_response'
/my_project/vendor/bundle/ruby/2.4.0/gems/selenium-webdriver-3.6.0/lib/selenium/webdriver/remote/http/default.rb:106:in `request'
/my_project/vendor/bundle/ruby/2.4.0/gems/selenium-webdriver-3.6.0/lib/selenium/webdriver/remote/http/common.rb:61:in `call'
/my_project/vendor/bundle/ruby/2.4.0/gems/selenium-webdriver-3.6.0/lib/selenium/webdriver/remote/bridge.rb:170:in `execute'
/my_project/vendor/bundle/ruby/2.4.0/gems/selenium-webdriver-3.6.0/lib/selenium/webdriver/remote/w3c/bridge.rb:537:in `execute'
/my_project/vendor/bundle/ruby/2.4.0/gems/selenium-webdriver-3.6.0/lib/selenium/webdriver/remote/w3c/bridge.rb:209:in `set_window_rect'
/my_project/vendor/bundle/ruby/2.4.0/gems/selenium-webdriver-3.6.0/lib/selenium/webdriver/remote/w3c/bridge.rb:170:in `resize_window'
/my_project/vendor/bundle/ruby/2.4.0/gems/selenium-webdriver-3.6.0/lib/selenium/webdriver/common/window.rb:123:in `resize_to'
/my_project/test/features/signup_form_test.rb:97:in `block (4 levels) in <class:SignupFormTest>'
```

And I'm not sure where this stack trace comes from, but it's in the output when I output the ruby backtrace, oddly:
```
webdriver::error::WebDriverError::new::h1643cda523229127
   3:           0x445b2b - geckodriver::marionette::MarionetteSession::response::hb2d7d32d0087420d
   4:           0x443814 - <geckodriver::marionette::MarionetteHandler as webdriver::server::WebDriverHandler<geckodriver::marionette::GeckoExtensionRoute>>::handle_command::hec53c2ea4656249d
   5:           0x434924 - webdriver::server::start::{{closure}}::he5e71944552dea53
   6:           0x405f87 - std::panicking::try::do_call::h061d4025362f1291
   7:           0x5b567a - panic_unwind::__rust_maybe_catch_panic
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-musl-linux/build/src/libpanic_unwind/lib.rs:98
   8:           0x416fd7 - <F as alloc::boxed::FnBox<A>>::call_box::hf93806550e6c682e
   9:           0x5ade94 - alloc::boxed::{{impl}}::call_once<(),()>
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-musl-linux/build/src/liballoc/boxed.rs:624
                         - std::sys_common::thread::start_thread
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-musl-linux/build/src/libstd/sys_common/thread.rs:21
                         - std::sys::imp::thread::{{impl}}::new::thread_start
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-musl-linux/build/src/libstd/sys/unix/thread.rs:84
```

## Trace-level log

I was unable to get it to output a trace level log anywhere I could find...

**Comment by andreastt** [comment]
You didn’t actually include the error message string or a trace-level log, so it’s hard to tell what’s causing this.

**Comment by mltsy** [comment]
Yeah, I'm a little confounded as to how to get an error message that goes deeper than Selenium... (The error message I gave was obviously from Selenium and not very helpful).  There are so many layers!

What would be the simplest way to manually interact with geckodriver to get an error message out of it?  I've tried adding a `desired_capabilities` to my capybara-selenium configuration that includes `{"moz:firefoxOptions": {log: {level: trace}}}`, but couldn't see or find any additional output (I don't know where it was supposed to go...).

If anyone can tell me how to create an instance of selenium in Ruby that will output geckodriver errors somewhere I can find them, that would be great! ;)

**Comment by andreastt** [comment]
The simplest way is to start the geckodriver process with the `-vv` flag. Alternatively you pass a `moz:firefoxOptions` configuration capability that looks like this:

    {`moz:firefoxOptions`: {"log": {"level": "trace"}}}`

Since you’re using the Selenium Ruby client, you may also us the [`Options`](https://seleniumhq.github.io/selenium/docs/api/rb/Selenium/WebDriver/Firefox/Options.html) helper for generating this:

    opts = Selenium::WebDriver::Firefox::Options.new(log_level: :trace)
    driver = Selenium::WebDriver.for :firefox, options: opts

I’m not sure if the Ruby client inherits the geckodriver output by default, so if it doesn’t I think it will if you enable debug mode in your Ruby interpreter, either by passing `ruby -v` or setting the `DEBUG=1` output variable.

**Comment by mltsy** [comment]
Hmm... I'm just getting the same error that I posted above, basically.  This is what I'm doing and the results:
```ruby
$ bundle exec irb -W --verbose
2.4.1 :002 > require 'selenium-webdriver'
 => true 
2.4.1 :003 > opts = Selenium::WebDriver::Firefox::Options.new(log_level: :trace)
 => #<Selenium::WebDriver::Firefox::Options:0x00000002934a20 @args=[], @binary=nil, @profile=nil, @log_level=:trace, @prefs={}, @options={}> 
2.4.1 :004 > driver = Selenium::WebDriver.for :firefox, options: opts
# [Several "method redefined" warnings]
=> #<Selenium::WebDriver::Firefox::Marionette::Driver:0xae79cc38d355016 browser=:firefox>
# [Firefox window open now]
2.4.1 :005 > driver.manage.window.resize_to(1024,768)
Selenium::WebDriver::Error::UnknownError: setWindowRect
	from stack backtrace:
	from    0:           0x4f99ad - backtrace::backtrace::trace::h45ace4059cd74233
	from    1:           0x4f9e92 - backtrace::capture::Backtrace::new::hb5a725a088a2a2fc
	from    2:           0x434469 - webdriver::error::WebDriverError::new::h1643cda523229127
	from    3:           0x445b2b - geckodriver::marionette::MarionetteSession::response::hb2d7d32d0087420d
	from    4:           0x443814 - <geckodriver::marionette::MarionetteHandler as webdriver::server::WebDriverHandler<geckodriver::marionette::GeckoExtensionRoute>>::handle_command::hec53c2ea4656249d
	from    5:           0x434924 - webdriver::server::start::{{closure}}::he5e71944552dea53
	from    6:           0x405f87 - std::panicking::try::do_call::h061d4025362f1291
	from    7:           0x5b567a - panic_unwind::__rust_maybe_catch_panic
	from                         at /buildslave/rust-buildbot/slave/stable-dist-rustc-musl-linux/build/src/libpanic_unwind/lib.rs:98
	from    8:           0x416fd7 - <F as alloc::boxed::FnBox<A>>::call_box::hf93806550e6c682e
	from    9:           0x5ade94 - alloc::boxed::{{impl}}::call_once<(),()>
	from                         at /buildslave/rust-buildbot/slave/stable-dist-rustc-musl-linux/build/src/liballoc/boxed.rs:624
	from                          - std::sys_common::thread::start_thread
	from                         at /buildslave/rust-buildbot/slave/stable-dist-rustc-musl-linux/build/src/libstd/sys_common/thread.rs:21
	from                          - std::sys::imp::thread::{{impl}}::new::thread_start
... 15 levels...
	from /home/jmarty/.rvm/gems/ruby-2.4.1/gems/bundler-1.15.4/lib/bundler/cli/exec.rb:74:in `kernel_load'
	from /home/jmarty/.rvm/gems/ruby-2.4.1/gems/bundler-1.15.4/lib/bundler/cli/exec.rb:27:in `run'
	from /home/jmarty/.rvm/gems/ruby-2.4.1/gems/bundler-1.15.4/lib/bundler/cli.rb:362:in `exec'
	from /home/jmarty/.rvm/gems/ruby-2.4.1/gems/bundler-1.15.4/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	from /home/jmarty/.rvm/gems/ruby-2.4.1/gems/bundler-1.15.4/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
	from /home/jmarty/.rvm/gems/ruby-2.4.1/gems/bundler-1.15.4/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
	from /home/jmarty/.rvm/gems/ruby-2.4.1/gems/bundler-1.15.4/lib/bundler/cli.rb:22:in `dispatch'
	from /home/jmarty/.rvm/gems/ruby-2.4.1/gems/bundler-1.15.4/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
	from /home/jmarty/.rvm/gems/ruby-2.4.1/gems/bundler-1.15.4/lib/bundler/cli.rb:13:in `start'
	from /home/jmarty/.rvm/gems/ruby-2.4.1/gems/bundler-1.15.4/exe/bundle:30:in `block in <top (required)>'
	from /home/jmarty/.rvm/gems/ruby-2.4.1/gems/bundler-1.15.4/lib/bundler/friendly_errors.rb:121:in `with_friendly_errors'
	from /home/jmarty/.rvm/gems/ruby-2.4.1/gems/bundler-1.15.4/exe/bundle:22:in `<top (required)>'
	from /home/jmarty/.rvm/gems/ruby-2.4.1/bin/bundle:22:in `load'
	from /home/jmarty/.rvm/gems/ruby-2.4.1/bin/bundle:22:in `<main>'
	from /home/jmarty/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `eval'
	from /home/jmarty/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `<main>'
```

I'm not sure if there's a way to expand that `... 15 levels...` abbreviation, or whether it would be helpful... ?  Is there another log output I'm missing here?

**Comment by andreastt** [comment]
You’re looking for the geckodriver processs output, not the stacktrace.

**Comment by mltsy** [comment]
Ah!  `irb -d` is debug mode (when you said ruby -v, which is actually the version info flag, I figured you must have meant verbose, but -d must be what you meant!)  I got this additional output:

```
2017-10-09 14:19:49 INFO Selenium -> POST session/432ea2b6-1bf0-48ec-ab1d-b7543744237d/window/rect
2017-10-09 14:19:49 INFO Selenium    >>> http://127.0.0.1:4444/session/432ea2b6-1bf0-48ec-ab1d-b7543744237d/window/rect | {"x":null,"y":null,"width":1024,"height":768}
2017-10-09 14:19:49 DEBUG Selenium      > {"Accept"=>"application/json", "Content-Type"=>"application/json; charset=utf-8", "Content-Length"=>"45"}
1507576789577	webdriver::server	DEBUG	→ POST /session/432ea2b6-1bf0-48ec-ab1d-b7543744237d/window/rect {"x":null,"y":null,"width":1024,"height":768}
1507576789577	geckodriver::marionette	TRACE	→ 67:[0,2,"setWindowRect",{"height":768,"width":1024,"x":null,"y":null}]
1507576789579	Marionette	TRACE	conn0 -> [0,2,"setWindowRect",{"height":768,"width":1024,"x":null,"y":null}]
1507576789581	Marionette	TRACE	conn0 <- [1,2,{"error":"unknown command","message":"setWindowRect","stacktrace":"WebDriverError@chrome://marionette/content/error.js:200:5\nUnknownCommandError@chrome://marionette/content/error.js:444:5\nDispatcher.prototype.execute/req<@chrome://marionette/content/dispatcher.js:121:13\nTaskImpl_run@resource://gre/modules/Task.jsm:319:42\nTaskImpl@resource://gre/modules/Task.jsm:277:3\ncreateAsyncFunction/asyncFunction@resource://gre/modules/Task.jsm:252:14\nTask_spawn@resource://gre/modules/Task.jsm:166:12\nDispatcher.prototype.execute@chrome://marionette/content/dispatcher.js:118:13\nDispatcher.prototype.onPacket@chrome://marionette/content/dispatcher.js:89:5\nDebuggerTransport.prototype._onJSONObjectReady/<@chrome://marionette/content/server.js -> resource://devtools/shared/transport/transport.js:483:11\nexports.makeInfallible/<@resource://gre/modules/commonjs/toolkit/loader.js -> resource://devtools/shared/ThreadSafeDevToolsUtils.js:101:14\nexports.makeInfallible/<@resource://gre/modules/commonjs/toolkit/loader.js -> resource://devtools/shared/ThreadSafeDevToolsUtils.js:101:14\n"},null]
1507576789581	geckodriver::marionette	TRACE	← [1,2,{"error":"unknown command","message":"setWindowRect","stacktrace":"WebDriverError@chrome://marionette/content/error.js:200:5\nUnknownCommandError@chrome://marionette/content/error.js:444:5\nDispatcher.prototype.execute/req<@chrome://marionette/content/dispatcher.js:121:13\nTaskImpl_run@resource://gre/modules/Task.jsm:319:42\nTaskImpl@resource://gre/modules/Task.jsm:277:3\ncreateAsyncFunction/asyncFunction@resource://gre/modules/Task.jsm:252:14\nTask_spawn@resource://gre/modules/Task.jsm:166:12\nDispatcher.prototype.execute@chrome://marionette/content/dispatcher.js:118:13\nDispatcher.prototype.onPacket@chrome://marionette/content/dispatcher.js:89:5\nDebuggerTransport.prototype._onJSONObjectReady/<@chrome://marionette/content/server.js -> resource://devtools/shared/transport/transport.js:483:11\nexports.makeInfallible/<@resource://gre/modules/commonjs/toolkit/loader.js -> resource://devtools/shared/ThreadSafeDevToolsUtils.js:101:14\nexports.makeInfallible/<@resource://gre/modules/commonjs/toolkit/loader.js -> resource://devtools/shared/ThreadSafeDevToolsUtils.js:101:14\n"},null]
1507576789582	webdriver::server	DEBUG	← 404 Not Found {"value":{"error":"unknown error","message":"setWindowRect","stacktrace":"stack backtrace:\n   0:           0x4f99ad - backtrace::backtrace::trace::h45ace4059cd74233\n   1:           0x4f9e92 - backtrace::capture::Backtrace::new::hb5a725a088a2a2fc\n   2:           0x434469 - webdriver::error::WebDriverError::new::h1643cda523229127\n   3:           0x445b2b - geckodriver::marionette::MarionetteSession::response::hb2d7d32d0087420d\n   4:           0x443814 - <geckodriver::marionette::MarionetteHandler as webdriver::server::WebDriverHandler<geckodriver::marionette::GeckoExtensionRoute>>::handle_command::hec53c2ea4656249d\n   5:           0x434924 - webdriver::server::start::{{closure}}::he5e71944552dea53\n   6:           0x405f87 - std::panicking::try::do_call::h061d4025362f1291\n   7:           0x5b567a - panic_unwind::__rust_maybe_catch_panic\n                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-musl-linux/build/src/libpanic_unwind/lib.rs:98\n   8:           0x416fd7 - <F as alloc::boxed::FnBox<A>>::call_box::hf93806550e6c682e\n   9:           0x5ade94 - alloc::boxed::{{impl}}::call_once<(),()>\n                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-musl-linux/build/src/liballoc/boxed.rs:624\n                         - std::sys_common::thread::start_thread\n                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-musl-linux/build/src/libstd/sys_common/thread.rs:21\n                         - std::sys::imp::thread::{{impl}}::new::thread_start\n                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-musl-linux/build/src/libstd/sys/unix/thread.rs:84"}}
2017-10-09 14:19:49 INFO Selenium <- {"value":{"error":"unknown error","message":"setWindowRect","stacktrace":"stack backtrace:\n   0:           0x4f99ad - backtrace::backtrace::trace::h45ace4059cd74233\n   1:           0x4f9e92 - backtrace::capture::Backtrace::new::hb5a725a088a2a2fc\n   2:           0x434469 - webdriver::error::WebDriverError::new::h1643cda523229127\n   3:           0x445b2b - geckodriver::marionette::MarionetteSession::response::hb2d7d32d0087420d\n   4:           0x443814 - <geckodriver::marionette::MarionetteHandler as webdriver::server::WebDriverHandler<geckodriver::marionette::GeckoExtensionRoute>>::handle_command::hec53c2ea4656249d\n   5:           0x434924 - webdriver::server::start::{{closure}}::he5e71944552dea53\n   6:           0x405f87 - std::panicking::try::do_call::h061d4025362f1291\n   7:           0x5b567a - panic_unwind::__rust_maybe_catch_panic\n                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-musl-linux/build/src/libpanic_unwind/lib.rs:98\n   8:           0x416fd7 - <F as alloc::boxed::FnBox<A>>::call_box::hf93806550e6c682e\n   9:           0x5ade94 - alloc::boxed::{{impl}}::call_once<(),()>\n                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-musl-linux/build/src/liballoc/boxed.rs:624\n                         - std::sys_common::thread::start_thread\n                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-musl-linux/build/src/libstd/sys_common/thread.rs:21\n                         - std::sys::imp::thread::{{impl}}::new::thread_start\n                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-musl-linux/build/src/libstd/sys/unix/thread.rs:84"}}
Exception `Selenium::WebDriver::Error::UnknownError' at /home/jmarty/Projects/satorix-website/vendor/bundle/ruby/2.4.0/gems/selenium-webdriver-3.6.0/lib/selenium/webdriver/remote/response.rb:72 - setWindowRect
```

**Comment by andreastt** [comment]
Judging by https://github.com/SeleniumHQ/selenium/blob/master/rb/lib/selenium/webdriver/common/service.rb#L93 you need to set `Selenium::WebDriver.logger.level = :debug`.

**Comment by andreastt** [comment]
Sorry about `-v` misleading you. It’s been several years since I’ve done any Ruby. The log you attached is exactly what we’re looking for!

You say that you use Firefox 56, but that should have the `setWindowRect` command. Can you confirm that the returned capabilities from starting a new session show a `browserVersion` of `56`?

**Comment by andreastt** [comment]
It also does not look to me that you’re using geckodriver 0.19.0, because it should not have ← and → as symbols for log, so please also confirm that you’re using the correctly geckodriver version.

**Comment by mltsy** [comment]
Oh!  Indeed.  I guess my dev environment is different from the testing environment I originally inspected when filing the issue.  Let me see if I get the same results in that env... (and fix my dev env!)

**Comment by mltsy** [comment]
Hmm... I've updated geckodriver, but even though my system version of firefox is 56, selenium/geckodriver is starting Firefox 52, which I must have installed at some alternate location... any way to easily find out where that is installed so I can update/remove it?

**Comment by mltsy** [comment]
Ah, nevermind - I see it's listed with in the capabilities object as the `binary` attribute

**Comment by andreastt** [comment]
On Linux, geckodriver searches the system path. You can see which directories are included in the search this way:

    % echo $PATH
    /home/ato/bin:/home/ato/bin:/usr/local/bin:/usr/bin:/bin:/usr/games:/usr/local/plan9/bin:/home/ato/.cargo/bin:/home/ato/bin:/home/ato/.mozbuild/version-control-tools/git/commands:/home/ato/src/moz-git-tools:/usr/local/plan9/bin:/home/ato/.cargo/bin:/home/ato/bin:/home/ato/.mozbuild/version-control-tools/git/commands:/home/ato/src/moz-git-tools

To find the locations of Firefox, in the order it chooses you can use whereis(1):

    % whereis firefox
    firefox: /usr/bin/firefox /usr/local/firefox

**Comment by mltsy** [comment]
Okay, so for some reason it was using `/usr/local/bin/firefox2` (I don't know what that is - probably a sign I shot myself in the foot with a time-traveling bullet from the past, on a previous attempt to hobble together a working Firefox test environment), and after deleting that, it does indeed work fine in development!  Thank you!

I guess the error that's happening now in CI is actually not the same error (I assumed it was, because it was failing in the same place), but I think it's maybe due to xvfb having too small of a frame buffer to resize the window large enough to work or something like that.  If I find anything else I'll open a new ticket.

At least now I know how to get a geckodriver trace level log from selenium in IRB! ;)

**Comment by andreastt** [comment]
Happy to hear it is solved!

You might want to consider passing the `-headless` argument (in `moz:firefoxOptions`) instead of using xvfb. It is considerably more reliable because a plain X session does not by default have a window manager.

**Comment by andreastt** [comment]
(Note: `-headless` only works with Firefox 57 and greater.)

**Comment by andreastt** [comment]
Sorry, I meant >= 55 on Linux, and >= 56 on Windows/Mac for `-headless`. See https://developer.mozilla.org/en-US/Firefox/Headless_mode.

**Comment by mltsy** [comment]
Holy :hankey:, that actually worked! Thanks for the tip :smiley: :fireworks: :+1:

**Comment by whimboo** [comment]
Please note that when using headless your test will not use real key/mouse events. If you rely on those you will have to keep your tests (or a subset) running non-headless. You can always define the dimensions of the virtual framebuffers used by xvfb.

**Comment by andreastt** [comment]
The input events will be “as real” as those using xvfb, the difference being that the underlying code supporting `nsIWindowUtils` will not call out to the widget layer (it will call a dummy, but stateful widget layer).

Headless mode also supports setting window dimensions through the `MOZ_HEADLESS_WIDTH` and `MOZ_HEADLESS_HEIGHT` output variables.
