### ISSUE TITLE
Unable to set folderList - parse exception

### ISSUE THREAD

**Issue by shogus** [mozilla/geckodriver#1005]
## System
* Version: 19 & 18
* Platform: Ubuntu xenial 4.9.49-moby
* Firefox: 54 & 55
* Selenium: 3.5
* node v6.10.2
* protractor 5.1.1
* webdriver-manager 12.0.6

## Testcase

In protractor js config:

let firefox = require("selenium-webdriver/firefox");
let profile = new firefox.Profile();
profile.setPreference("browser.download.folderList", 2);

exports.config = {
  allScriptsTimeout: 30000,
  SELENIUM_PROMISE_MANAGER: false,
  getPageTimeout: 20000,
  capabilities: {
    browserName: "firefox",
    acceptInsecureCerts: true,
    firefoxOptions: {
      prefs: [{ "dom.file.createInChild": true }],
      log: { level: "trace" }
    },
    firefox_profile: profile
  },

  seleniumServerJar: "../selenium-server-standalone-3.5.0.jar",
  localSeleniumStandaloneOpts: {
    jvmArgs: ["-Dwebdriver.gecko.driver=../geckodriver-v0.19.0"]
  },
  framework: "custom",
  frameworkPath: require.resolve("protractor-cucumber-framework"),
...

setting profile.setPreference("browser.download.folderList", 2); generates error:
Could not convert pref value to string, boolean, or integer

setting profile.setPreference("browser.download.folderList", "2") doesn't work :( - value 2 is ignored

This issue prevents from creating automated tests capable of downloading files.

Same configuration and settings work nicely on Windows 10

## Stacktrace

Build info: version: '3.5.0', revision: '8def36e068', time: '2017-08-10T23:00:22.093Z'
System info: host: '4a1d1bc39db3', ip: '172.17.0.2', os.name: 'Linux', os.arch: 'amd64', os.version: '4.9.49-moby', java.version: '1.8.0_131'
Driver info: driver.version: unknown
remote stacktrace: stack backtrace:
   0:           0x4f388c - backtrace::backtrace::trace::h736111741fa0878e
   1:           0x4f38c2 - backtrace::capture::Backtrace::new::h63b8a5c0787510c9
   2:           0x442c61 - webdriver::error::WebDriverError::new::hc4fe6a1ced4e57dd
   3:           0x44715b - geckodriver::marionette::MarionetteHandler::create_connection::hf8b6061dba65cdd0
   4:           0x42ac91 - <webdriver::server::Dispatcher<T, U>>::run::hba9181b5aacf8f04
   5:           0x402c59 - std::sys_common::backtrace::__rust_begin_short_backtrace::h19de262639927233
   6:           0x40c065 - std::panicking::try::do_call::h6c1659fc4d01af51
   7:           0x5e38ec - panic_unwind::__rust_maybe_catch_panic
                        at /checkout/src/libpanic_unwind/lib.rs:98
   8:           0x420d32 - <F as alloc::boxed::FnBox<A>>::call_box::h953e5f59694972c5
   9:           0x5dc00b - alloc::boxed::{{impl}}::call_once<(),()>
                        at /checkout/src/liballoc/boxed.rs:661
                         - std::sys_common::thread::start_thread
                        at /checkout/src/libstd/sys_common/thread.rs:21
                         - std::sys::imp::thread::{{impl}}::new::thread_start
                        at /checkout/src/libstd/sys/unix/thread.rs:84
[15:36:24] E/launcher - Error: WebDriverError: Could not convert pref value to string, boolean, or integer
Build info: version: '3.5.0', revision: '8def36e068', time: '2017-08-10T23:00:22.093Z'
System info: host: '4a1d1bc39db3', ip: '172.17.0.2', os.name: 'Linux', os.arch: 'amd64', os.version: '4.9.49-moby', java.version: '1.8.0_131'
Driver info: driver.version: unknown
remote stacktrace: stack backtrace:
   0:           0x4f388c - backtrace::backtrace::trace::h736111741fa0878e
   1:           0x4f38c2 - backtrace::capture::Backtrace::new::h63b8a5c0787510c9
   2:           0x442c61 - webdriver::error::WebDriverError::new::hc4fe6a1ced4e57dd
   3:           0x44715b - geckodriver::marionette::MarionetteHandler::create_connection::hf8b6061dba65cdd0
   4:           0x42ac91 - <webdriver::server::Dispatcher<T, U>>::run::hba9181b5aacf8f04
   5:           0x402c59 - std::sys_common::backtrace::__rust_begin_short_backtrace::h19de262639927233
   6:           0x40c065 - std::panicking::try::do_call::h6c1659fc4d01af51
   7:           0x5e38ec - panic_unwind::__rust_maybe_catch_panic
                        at /checkout/src/libpanic_unwind/lib.rs:98
   8:           0x420d32 - <F as alloc::boxed::FnBox<A>>::call_box::h953e5f59694972c5
   9:           0x5dc00b - alloc::boxed::{{impl}}::call_once<(),()>
                        at /checkout/src/liballoc/boxed.rs:661
                         - std::sys_common::thread::start_thread
                        at /checkout/src/libstd/sys_common/thread.rs:21
                         - std::sys::imp::thread::{{impl}}::new::thread_start
                        at /checkout/src/libstd/sys/unix/thread.rs:84
    at WebDriverError (/tests/node_modules/selenium-webdriver/lib/error.js:27:5)
    at Object.checkLegacyResponse (/tests/node_modules/selenium-webdriver/lib/error.js:505:15)
    at parseHttpResponse (/tests/node_modules/selenium-webdriver/lib/http.js:509:13)
    at doSend.then.response (/tests/node_modules/selenium-webdriver/lib/http.js:440:13)
    at process._tickCallback (internal/process/next_tick.js:109:7)
[15:36:24] E/launcher - Process exited with error code 100

**Comment by shogus** [comment]
duplicate : https://github.com/mozilla/geckodriver/issues/837 sorry
