### ISSUE TITLE
Problem with driver.quit() - HTTP Status: '404' -> incorrect JSON status mapping for 'unknown error' (500 expected)

### ISSUE THREAD

**Issue by KeReS1** [mozilla/geckodriver#1009]
Hello, 
I have a problem with sellenium driver for Firefox. I get error on the driver.quit();  in @After -> method afterEveryTest() 

Error:
HTTP Status: '404' -> incorrect JSON status mapping for 'unknown error' (500 expected)
Full error below.

## System
* Geko version: 0.19 (64)
* Platform: Windows 10 (64)
* Firefox: 52.4.0 (64)
* Selenium: 3.6.0

## Testcase

This is how I invoke FireFox Driver, its little longer cause I need headers for my tests. I wrote function that invoke driver and it start firefox.

@Before
startFF();

< StartFF() >
System.setProperty("webdriver.gecko.driver", "C:\\Selenium\\geckodriver-v0.18.0-win64\\geckodriver.exe");
        final String addOnPath = "C:\\Selenium\\header.xpi";
        File addOnFile = new File(addOnPath);
        FirefoxProfile profile = new FirefoxProfile();
        profile.addExtension(addOnFile);
        profile.setPreference("modifyheaders.headers.count", 1);
        ...
(alot of headers)
        ...
 FirefoxOptions options = new FirefoxOptions();
         options.setProfile(profile);
      options.addTo(DesiredCapabilities.firefox());
         driver = new FirefoxDriver(options);
         profile.setPreference("some.preference", true);
          PageFactory.initElements(driver, this);
          return driver;

@Test
< DRIVER WORKS DURRING TEST >

@After
    public void afterEveryTest() throws InterruptedException  {
         driver.quit(); <--- I get error here
{

## Stacktrace

paź 10, 2017 1:38:20 PM org.openqa.selenium.remote.ErrorCodes toStatus
INFO: HTTP Status: '404' -> incorrect JSON status mapping for 'unknown error' (500 expected)

org.openqa.selenium.WebDriverException: quit
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: host: 'PC426', ip: '172.30.0.133', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_144'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{moz:profile=C:\Users\keres\AppData\Local\Temp\rust_mozprofile.7uCjtAGmXUTK, rotatable=false, timeouts={implicit=0, page load=300000, script=30000}, pageLoadStrategy=normal, platform=XP, specificationLevel=0, moz:accessibilityChecks=false, acceptInsecureCerts=false, browserVersion=52.4.0, platformVersion=10.0, moz:processID=6188, browserName=firefox, javascriptEnabled=true, platformName=XP}]
Session ID: 35a6fdb8-d546-4e88-a955-76a0a2d82cce

	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:185)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:120)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:49)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:164)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:82)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:646)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:703)
	at org.openqa.selenium.remote.RemoteWebDriver.quit(RemoteWebDriver.java:542)
	at ProjectTesty.afterEveryTest(ProjectTesty.java:69)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:33)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)

**Comment by andreastt** [comment]
Firefox 52 isn’t supported by geckodriver. Consider using Firefox Nightly as suggested in the README.
