### ISSUE TITLE
Process gets stuck when `maximize_window()` is invoked using Xvfb

### ISSUE THREAD

**Issue by migonzalvar** [mozilla/geckodriver#1014]
## System
* Version: 0.19.0
* Platform: Linux 4.13.4-200.fc26.x86_64
* Firefox: 56.0 (64-bit)
* Selenium: 3.6.0 (python)

## Testcase

```python
# main.py
from selenium import webdriver
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

capabilities = DesiredCapabilities.FIREFOX.copy()
capabilities["moz:firefoxOptions"] = {
    "log": {
        "level": "trace",
    },
}

driver = webdriver.Firefox(capabilities=capabilities)
driver.maximize_window()
driver.get('https://google.com/')
driver.close()
```
This works just right.

But, when I run this code with `xvfb-run`, the process get stucks on `maximize_window()` step.

## Stacktrace

This stack trace is obtained when I kill geckodriver process after a while.

```
$ xvfb-run python main.py
Traceback (most recent call last):                                                                                                                                                                                 
  File "main.py", line 12, in <module>                                                                                                                                                                             
    driver.maximize_window()                                                                                                                                                                                       
  File "selenium-playground/.venv/lib64/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 640, in maximize_window                                      
    self.execute(command, {"windowHandle": "current"})                                                                                                                                                             
  File "selenium-playground/.venv/lib64/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 306, in execute                                              
    response = self.command_executor.execute(driver_command, params)                                                                                                                                               
  File "selenium-playground/.venv/lib64/python3.5/site-packages/selenium/webdriver/remote/remote_connection.py", line 464, in execute                                      
    return self._request(command_info[0], url, body=data)                                                                                                                                                          
  File "selenium-playground/.venv/lib64/python3.5/site-packages/selenium/webdriver/remote/remote_connection.py", line 488, in _request                                     
    resp = self._conn.getresponse()
  File "/usr/lib64/python3.5/http/client.py", line 1198, in getresponse
    response.begin()
  File "/usr/lib64/python3.5/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/usr/lib64/python3.5/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response
```

## Trace-level log

```
1507807930644	geckodriver	INFO	geckodriver 0.19.0
1507807930647	geckodriver	INFO	Listening on 127.0.0.1:43223
1507807931846	mozrunner::runner	INFO	Running command: "/usr/bin/firefox" "-marionette" "-profile" "/tmp/rust_mozprofile.xprKACa2B1PA"
1507807931847	geckodriver::marionette	TRACE	  connection attempt 0/600
1507807931947	geckodriver::marionette	TRACE	  connection attempt 1/600
1507807932048	geckodriver::marionette	TRACE	  connection attempt 2/600
1507807932070	addons.xpi	WARN	Error parsing extensions state: [Exception... "Component returned failure code: 0x80520012 (NS_ERROR_FILE_NOT_FOUND) [amIAddonManagerStartup.readStartupData]"  nsresult: "0x80520012 (NS_ERROR_FILE_NOT_FOUND)"  location: "JS frame :: resource://gre/modules/addons/XPIProvider.jsm :: loadExtensionState :: line 1554"  data: no] Stack trace: loadExtensionState()@resource://gre/modules/addons/XPIProvider.jsm:1554 < getInstallState()@resource://gre/modules/addons/XPIProvider.jsm:1589 < checkForChanges()@resource://gre/modules/addons/XPIProvider.jsm:3122 < startup()@resource://gre/modules/addons/XPIProvider.jsm:2188 < callProvider()@resource://gre/modules/AddonManager.jsm:269 < _startProvider()@resource://gre/modules/AddonManager.jsm:739 < startup()@resource://gre/modules/AddonManager.jsm:906 < startup()@resource://gre/modules/AddonManager.jsm:3090 < observe()@jar:file:///usr/lib64/firefox/omni.ja!/components/addonManager.js:65
1507807932148	geckodriver::marionette	TRACE	  connection attempt 3/600
1507807932248	geckodriver::marionette	TRACE	  connection attempt 4/600
1507807932314	Marionette	DEBUG	Received observer notification "profile-after-change"
1507807932349	geckodriver::marionette	TRACE	  connection attempt 5/600
1507807932354	Marionette	DEBUG	Received observer notification "command-line-startup"
1507807932354	Marionette	INFO	Enabled via --marionette
1507807932449	geckodriver::marionette	TRACE	  connection attempt 6/600
1507807932550	geckodriver::marionette	TRACE	  connection attempt 7/600
1507807932650	geckodriver::marionette	TRACE	  connection attempt 8/600
1507807932750	geckodriver::marionette	TRACE	  connection attempt 9/600
1507807932851	geckodriver::marionette	TRACE	  connection attempt 10/600
1507807932951	geckodriver::marionette	TRACE	  connection attempt 11/600
1507807933051	geckodriver::marionette	TRACE	  connection attempt 12/600
1507807933152	geckodriver::marionette	TRACE	  connection attempt 13/600
1507807933252	geckodriver::marionette	TRACE	  connection attempt 14/600
1507807933266	Marionette	DEBUG	Received observer notification "sessionstore-windows-restored"
1507807933353	geckodriver::marionette	TRACE	  connection attempt 15/600
1507807933453	geckodriver::marionette	TRACE	  connection attempt 16/600
1507807933497	Marionette	DEBUG	Setting recommended pref toolkit.cosmeticAnimations.enabled to false
1507807933498	Marionette	DEBUG	Setting recommended pref datareporting.policy.dataSubmissionPolicyAccepted to false
1507807933499	Marionette	INFO	Listening on port 46741
1507807933553	geckodriver::marionette	DEBUG	Connected to Marionette on localhost:46741
1507807933565	Marionette	DEBUG	Accepted connection 0 from 127.0.0.1:38216
1507807933565	geckodriver::marionette	TRACE	<- {"applicationType":"gecko","marionetteProtocol":3}
1507807933566	geckodriver::marionette	TRACE	-> 163:[0,1,"newSession",{"acceptInsecureCerts":true,"browserName":"firefox","capabilities":{"desiredCapabilities":{"acceptInsecureCerts":true,"browserName":"firefox"}}}]
1507807933567	Marionette	TRACE	0 -> [0,1,"newSession",{"acceptInsecureCerts":true,"browserName":"firefox","capabilities":{"desiredCapabilities":{"acceptInsecureCerts":true,"browserName":"firefox"}}}]
1507807933570	Marionette	CONFIG	Matched capabilities: {"browserName":"firefox","browserVersion":"56.0","platformName":"linux","platformVersion":"4.13.4-200.fc26.x86_64","pageLoadStrategy":"normal","acceptInsecureCerts":true,"timeouts":{"implicit":0,"pageLoad":300000,"script":30000},"rotatable":false,"specificationLevel":0,"moz:processID":20343,"moz:profile":"/tmp/rust_mozprofile.xprKACa2B1PA","moz:accessibilityChecks":false,"moz:headless":false}
1507807933570	Marionette	WARN	TLS certificate errors will be ignored for this session
1507807933617	Marionette	DEBUG	Register listener.js for window 2147483649
1507807933639	Marionette	TRACE	0 <- [1,1,null,{"sessionId":"3fefda09-ca84-44e8-b48a-070817d92a1b","capabilities":{"browserName":"firefox","browserVersion":"56.0","platformName":"linux","platformVersion":"4.13.4-200.fc26.x86_64","pageLoadStrategy":"normal","acceptInsecureCerts":true,"timeouts":{"implicit":0,"pageLoad":300000,"script":30000},"rotatable":false,"specificationLevel":0,"moz:processID":20343,"moz:profile":"/tmp/rust_mozprofile.xprKACa2B1PA","moz:accessibilityChecks":false,"moz:headless":false}}]
1507807933640	geckodriver::marionette	TRACE	<- [1,1,null,{"sessionId":"3fefda09-ca84-44e8-b48a-070817d92a1b","capabilities":{"browserName":"firefox","browserVersion":"56.0","platformName":"linux","platformVersion":"4.13.4-200.fc26.x86_64","pageLoadStrategy":"normal","acceptInsecureCerts":true,"timeouts":{"implicit":0,"pageLoad":300000,"script":30000},"rotatable":false,"specificationLevel":0,"moz:processID":20343,"moz:profile":"/tmp/rust_mozprofile.xprKACa2B1PA","moz:accessibilityChecks":false,"moz:headless":false}}]
1507807933640	webdriver::server	DEBUG	<- 200 OK {"value": {"sessionId":"3fefda09-ca84-44e8-b48a-070817d92a1b","capabilities":{"acceptInsecureCerts":true,"browserName":"firefox","browserVersion":"56.0","moz:accessibilityChecks":false,"moz:headless":false,"moz:processID":20343,"moz:profile":"/tmp/rust_mozprofile.xprKACa2B1PA","pageLoadStrategy":"normal","platformName":"linux","platformVersion":"4.13.4-200.fc26.x86_64","rotatable":false,"specificationLevel":0,"timeouts":{"implicit":0,"pageLoad":300000,"script":30000}}}}
1507807933641	webdriver::server	DEBUG	-> POST /session/3fefda09-ca84-44e8-b48a-070817d92a1b/window/maximize {"windowHandle": "current", "sessionId": "3fefda09-ca84-44e8-b48a-070817d92a1b"}
1507807933641	geckodriver::marionette	TRACE	-> 25:[0,2,"maximizeWindow",{}]
1507807933646	Marionette	TRACE	0 -> [0,2,"maximizeWindow",{}]
1507808038126	Marionette	DEBUG	Closed connection 0
Gdk-Message: firefox: Fatal IO error 11 (Resource temporarily unavailable) on X server :99.

Gdk-Message: /usr/lib64/firefox/firefox: Fatal IO error 11 (Resource temporarily unavailable) on X server :99.
```

**Comment by whimboo** [comment]
@andreastt I don't have xvfb available locally. Would you mind to have a quick look at this issue and why `maximizeWindow` causes an error in Firefox? Thanks.

**Comment by andreastt** [comment]
Maximize Window probably won’t work in xvfb because it doesn’t have a window manager: maximisation isn’t a concept in X when you don’t have a window manager, so I would say this is expected behaviour.

If however you run a lightweight window on the virtual X display, this problem should disappear. It is also possible to use Firefox in headless mode, which achieves the same effect but without a WM.
