### ISSUE TITLE
Unable to find a matching set of capabilities - Java/Win 10-32/3.6/0.19/56.0

### ISSUE THREAD

**Issue by rashaverak** [mozilla/geckodriver#1028]
## System
* Version: 0.19 - v32
* Platform: Windows 10
* Firefox: 56
* Selenium: 3.6

Java client

## Testcase

direct request to localhost:4444/session

{"capabilities": {"alwaysMatch": {"acceptInsecureCerts": true, "browserName":"firefox",
"moz:firefoxOptions":{"args":[], "log":{"level":"trace"}, "binary":"valid path to binary", "profile":"valid profile"}}}}

Result of testing: "binary" cause this issue.

## Stacktrace

When called with java client

1508826976983	geckodriver	INFO	geckodriver 0.19.0 (f0b5f3476d8b05a3bacebb06056ff933e26a17fa 2017-09-16)
1508826976992	geckodriver	INFO	Listening on 127.0.0.1:37776
org.openqa.selenium.SessionNotCreatedException: Unable to find a matching set of capabilities
Build info: version: '3.6.0', revision: '6fbf3ec767', time: '2017-09-27T16:15:40.131Z'
System info: host: '', ip: '', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_131'
Driver info: driver.version: AbstractSeleniumDriver
remote stacktrace: stack backtrace:
   0:   0x47d2a4 - <no info>
   1:   0x45d174 - <no info>
   2:   0x427701 - <no info>
   3:   0x42ac5a - <no info>
   4:   0x45ff5e - <no info>
   5:   0x45581f - <no info>
   6:   0x4437a6 - <no info>
   7:   0x443aa6 - <no info>
   8:   0x6de879 - <no info>
   9:   0x4439e9 - <no info>
  10:   0x44385b - <no info>
  11:   0x4575c8 - <no info>
  12:   0x6da071 - <no info>
  13: 0x74f38744 - BaseThreadInitThunk
  14: 0x776a582d - RtlGetAppContainerNamedObjectPath
	at newInstance0(NativeConstructorAccessorImpl.java:-2)
	at newInstance(NativeConstructorAccessorImpl.java:62)
	at newInstance(DelegatingConstructorAccessorImpl.java:45)
	at newInstance(Constructor.java:423)
	at lambda$new$0(W3CHandshakeResponse.java:57)
	at lambda$getResponseFunction$2(W3CHandshakeResponse.java:104)
	at lambda$createSession$24(ProtocolHandshake.java:359)
	at accept(ReferencePipeline.java:193)
	at tryAdvance(Spliterators.java:958)
	at forEachWithCancel(ReferencePipeline.java:126)
	at copyIntoWithCancel(AbstractPipeline.java:498)
	at copyInto(AbstractPipeline.java:485)
	at wrapAndCopyInto(AbstractPipeline.java:471)
	at evaluateSequential(FindOps.java:152)
	at evaluate(AbstractPipeline.java:234)
	at findFirst(ReferencePipeline.java:464)
	at createSession(ProtocolHandshake.java:362)
	at createSession(ProtocolHandshake.java:136)
	at execute(HttpCommandExecutor.java:142)
	at execute(DriverCommandExecutor.java:83)
	at execute(RemoteWebDriver.java:586)
	at startSession(RemoteWebDriver.java:217)
	at <init>(RemoteWebDriver.java:140)
	at <init>(FirefoxDriver.java:120)
	at <init>(ForwardingFirefoxDriver.java:17)
	at createDriver(FirefoxDriver.java:64)
	at createDriver(FirefoxDriver.java:22)
	at forward(AbstractSeleniumDriver.java:400)
	at handleForward(EmulatorThread.java:52)
	at processAction(EmulatorThread.java:35)
	at consumeItem(AbstractThread.java:21)
	at consumeItem(AbstractThread.java:7)
	at run(AbstractQueueThread.java:42)

## Trace-level log

1508752193486 webdriver::server DEBUG <- 500 Internal Server Error {"value":{"error":"session not created","message":"Unable to find a matching set of capabilities","stacktrace":"stack backtrace:\n 0: 0x47d2a4 - \n 1: 0x45d174 - \n 2: 0x427701 - \n 3: 0x42ac5a - \n 4: 0x45ff5e - \n 5: 0x45581f - \n 6: 0x4437a6 - \n 7: 0x443aa6 - \n 8: 0x6de879 - \n 9: 0x4439e9 - \n 10: 0x44385b - \n 11: 0x4575c8 - \n 12: 0x6da071 - \n 13: 0x74f38744 - BaseThreadInitThunk\n 14: 0x776a582d - RtlGetAppContainerNamedObjectPath"}}

**Comment by rashaverak** [comment]
Works fine with selenium-server-standalone-3.5.0.jar

**Comment by rashaverak** [comment]
Could my issue be connected to the fact I am trying to use FirefoxPortable ?

**Comment by andreastt** [comment]
FirefoxPortable isn’t supported.

**Comment by nbnds** [comment]
@rashaverak the note that FirefoxPortable is not supported is not quite right. It works if you set the path correctly to the actual firefox.exe 
https://github.com/SeleniumHQ/selenium/issues/5006
working - [...] PortableApps\\FirefoxPortable\\App\\Firefox64\\firefox.exe
not working - [...] PortableApps\\FirefoxPortable\\FirefoxPortable.exe

**Comment by whimboo** [comment]
Right, I do not see why we are not supporting FirefoxPortable. It's just a non-installable package, and is fully identical to Firefox.

Can you really attach a trace log here? See https://firefox-source-docs.mozilla.org/testing/geckodriver/geckodriver/TraceLogs.html in how to get one.
