### ISSUE TITLE
Throwing error while running the simple code; Geckodriver 0.19.1 and selenium 3.6;Eclipse oxyzen ;Firefox driver 47.0;

### ISSUE THREAD

**Issue by darshanddd7** [mozilla/geckodriver#1040]
## Mac
* Version: 0.19.1
* Platform: mcos Sierra
* Firefox: 47.0
* Selenium: 3.6

## This is the issue..

```
1509707074809	geckodriver	INFO	geckodriver 0.19.1
1509707074822	geckodriver	INFO	Listening on 127.0.0.1:9477
Exception in thread "main" org.openqa.selenium.SessionNotCreatedException: Unable to find a matching set of capabilities
Build info: version: '3.6.0', revision: '6fbf3ec767', time: '2017-09-27T16:15:40.131Z'
System info: host: 'Darshans-MacBook-Air.local', ip: 'fe80:0:0:0:410:539:c982:328d%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.12.6', java.version: '9.0.1'
Driver info: driver.version: FirefoxDriver
remote stacktrace: stack backtrace:
   0:        0x10405749e - backtrace::backtrace::trace::h3ab5720c483fe461
   1:        0x1040574dc - backtrace::capture::Backtrace::new::h096accf58447e0d5
   2:        0x103f903e5 - webdriver::error::WebDriverError::new::hb28209cec8791fc2
   3:        0x103f915c5 - geckodriver::marionette::MarionetteHandler::create_connection::h59a68c8dfef48e54
   4:        0x103f76d3c - _$LT$webdriver..server..Dispatcher$LT$T$C$$u20$U$GT$$GT$::run::h5a26ba0bb4fdb139
   5:        0x103f4f0c5 - std::sys_common::backtrace::__rust_begin_short_backtrace::h3f868f7a1a12bdcc
   6:        0x103f59d2d - std::panicking::try::do_call::hfce1ad2a948c3632
   7:        0x104103a5c - __rust_maybe_catch_panic
   8:        0x103f6ceb5 - _$LT$F$u20$as$u20$alloc..boxed..FnBox$LT$A$GT$$GT$::call_box::h651dedb755194a8c
   9:        0x1040ffc4b - std::sys::imp::thread::Thread::new::thread_start::h48c72bb09587cbc3
  10:     0x7fffca1bc93a - _pthread_body
  11:     0x7fffca1bc886 - _pthread_start
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:488)
	at org.openqa.selenium.remote.W3CHandshakeResponse.lambda$new$0(W3CHandshakeResponse.java:57)
	at org.openqa.selenium.remote.W3CHandshakeResponse.lambda$getResponseFunction$2(W3CHandshakeResponse.java:104)
	at org.openqa.selenium.remote.ProtocolHandshake.lambda$createSession$24(ProtocolHandshake.java:359)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:958)
	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:127)
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:502)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:488)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:476)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:362)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:136)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:142)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:586)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:217)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:140)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:120)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:106)
	at com.testing.automation.MyFirefoxTest1.main(MyFirefoxTest1.java:33)
```

**Comment by curtisy1** [comment]
@darshanddd7 Can you please post the code snippet of how you start WebDriver with the Capabilities as well?

Thanks.

**Comment by andreastt** [comment]
Could you please attach a [trace-level log] from geckodriver? Read more about reporting actionable bugs in our [contribution guidelines].

[trace-level log]: https://searchfox.org/mozilla-central/source/testing/geckodriver/doc/TraceLogs.md
[contribution guidelines]: https://searchfox.org/mozilla-central/source/testing/geckodriver/CONTRIBUTING.md#reporting-bugs

**Comment by andreastt** [comment]
Ah, I see you’re using Firefox 47. Firefox 47 isn’t supported, please try again with Firefox Nightly.
