### ISSUE TITLE
send_keys() fails to fill the text field

### ISSUE THREAD

**Issue by cikakosta** [mozilla/geckodriver#1081]
## System
* Version: 0.19.1
* Platform: macOS
* Firefox: v52 and above
* Selenium: 3.5.1 - 3.7.0

Using PyCharm with tests written in python.

## Testcase
```
from selenium import webdriver
from selenium.webdriver.common.by import By

class FillTheAddress():

def test(self):
    baseUrl = "https://www.bonfire.com/stbw-loon-design/buy/"
    driver = webdriver.Firefox()
    # driver.maximize_window()
    driver.get(baseUrl)
    driver.implicitly_wait(10)
    driver.find_element_by_xpath("//select[@name='prod0size']/option[text()='M']").click()
    driver.find_element_by_xpath("//button[@class='sw-BtnDefault sw-BtnDefault-success sw-BtnWide']").click()
    driver.find_element(By.XPATH, "//input[@name='name']").send_keys("Mitar Mitra Mitar")
    driver.find_element(By.XPATH, "//input[@id='co-shippingaddress']").send_keys("Hello Hello Street")
ff = FillTheAddress()
ff.test()
```

Here is HTML

```
<h3 ng-show="vm.orderSummary.donationOnly" class="ng-hide">Billing address</h3><h3 ng-hide="vm.orderSummary.donationOnly" class="">Shipping information</h3><div class="sw-Form_Group"><label class="sw-Form_Label" for="co-fullname">Full name</label><input focus-me="" id="co-fullname" name="name" class="sw-Form sw-Form_Input ng-pristine ng-empty ng-invalid ng-invalid-required ng-valid-pattern ng-touched" ng-class="{'sw-Form_Input-error': form.name.$invalid &amp;&amp; ((form.name.$touched &amp;&amp; form.name.$dirty) || form.$submitted)}" ng-model="vm.name" placeholder="Your first and last name" autocomplete="off" ng-model-options="{ allowInvalid: true }" ng-pattern="/^([^0-9`~,<>;:&quot;\/\[\]\|\{}()=_+?*&amp;^%$#@! ]{2,}[ ]?){2,}$/" ng-blur="vm.saveAddress()" ui-validate="{required:'!!$value &amp;&amp; $value.indexOf(\' \') > 0 &amp;&amp; $value.length > 5'}" uib-tooltip-html="'<span>Please enter your first and last name</span>'" tooltip-trigger="none" tooltip-is-open="form.name.$invalid &amp;&amp; ((form.name.$touched &amp;&amp; form.name.$dirty) || form.$submitted)" style="" type="text"></div><!----><div class="row" ng-if="!vm.orderSummary.donationOnly"><div class="col-xs-12 col-sm-12 col-md-9"><div class="sw-Form_Group"><label for="co-shippingaddress" class="sw-Form_Label">Street address</label><input id="co-shippingaddress" name="shpStreet" class="sw-Form sw-Form_Input ng-pristine ng-empty ng-invalid ng-invalid-required ng-valid-maxlength ng-touched" ng-class="{'sw-Form_Input-error': form.shpStreet.$invalid &amp;&amp; (form.shpStreet.$dirty || form.$submitted)}" placeholder="123 Example Street" autocomplete="off" maxlength="50" ng-model="vm.shippingAddress.street" required="" ng-blur="vm.saveAddress()" uib-tooltip-html="'<span>Please enter your street address</span>'" tooltip-trigger="none" tooltip-is-open="form.shpStreet.$invalid &amp;&amp; (form.shpStreet.$dirty || form.$submitted)" style="" hidden="" type="text"></div></div><div class="col-xs-12 col-sm-12 col-md-3"><div class="sw-Form_Group"><label for="co-shippmentapt" class="sw-Form_Label">Apt/Suite</label><input id="co-shippmentapt" class="sw-Form sw-Form_Input ng-pristine ng-untouched ng-valid ng-empty ng-valid-maxlength" placeholder="Apt/Suite" autocomplete="off" maxlength="50" ng-model="vm.shippingAddress.apt" ng-blur="vm.saveAddress()" type="text"></div></div></div><!----><!----><div class="row" ng-if="!vm.orderSummary.donationOnly"><div class="col-xs-12 col-sm-12 col-md-5"><div class="sw-Form_Group"><label for="co-shippmentcity" class="sw-Form_Label">City</label><input id="co-shippmentcity" name="shpCity" class="sw-Form sw-Form_Input ng-pristine ng-untouched ng-empty ng-invalid ng-invalid-required" ng-class="{'sw-Form_Input-error': form.shpCity.$invalid &amp;&amp; (form.shpCity.$dirty || form.$submitted)}" placeholder="City" autocomplete="off" ng-model="vm.shippingAddress.city" required="" ng-blur="vm.saveAddress()" uib-tooltip-html="'<span>Please enter your city</span>'" tooltip-trigger="none" tooltip-is-open="form.shpCity.$invalid &amp;&amp; (form.shpCity.$dirty || form.$submitted)" type="text"></div></div><div class="col-xs-12 col-sm-12 col-md-7"><div class="row"><div class="col-xs-7 col-sm-7 col-md-7"><!----><!----><div class="sw-Form_Group" ng-if="vm.shippingAddress.country.usa" style=""><label class="sw-Form_Label" for="co-shippmentusastate">State</label><div style="height:0px" uib-tooltip-html="'<span>Please select your state</span>'" tooltip-trigger="none" tooltip-is-open="form.shpUsState.$invalid &amp;&amp; (form.shpUsState.$dirty || form.$submitted)"></div><select name="shpUsState" id="co-shippmentusastate" class="sw-Form sw-Form_Select ng-pristine ng-untouched ng-empty ng-invalid ng-invalid-required" autocomplete="off" ng-model="vm.shippingAddress.usState" ng-change="vm.saveAddress()" ng-options="state as state.name for state in vm.usStates" ui-validate="{required:'vm.validateState(true, vm.shippingAddress.country, $value)'}"><option value="" selected="selected">Select state</option><option label="Alabama" value="object:188">Alabama</option><option label="Alaska" value="object:189">Alaska</option><option label="Arizona" value="object:190">Arizona</option><option label="Arkansas" value="object:191">Arkansas</option><option label="California" value="object:192">California</option><option label="Colorado" value="object:193">Colorado</option><option label="Connecticut" value="object:194">Connecticut</option><option label="Delaware" value="object:195">Delaware</option><option label="District of Columbia" value="object:196">District of Columbia</option><option label="Florida" value="object:197">Florida</option><option label="Georgia" value="object:198">Georgia</option><option label="Hawaii" value="object:199">Hawaii</option><option label="Idaho" value="object:200">Idaho</option><option label="Illinois" value="object:201">Illinois</option><option label="Indiana" value="object:202">Indiana</option><option label="Iowa" value="object:203">Iowa</option><option label="Kansas" value="object:204">Kansas</option><option label="Kentucky" value="object:205">Kentucky</option><option label="Louisiana" value="object:206">Louisiana</option><option label="Maine" value="object:207">Maine</option><option label="Maryland" value="object:208">Maryland</option><option label="Massachusetts" value="object:209">Massachusetts</option><option label="Michigan" value="object:210">Michigan</option><option label="Minnesota" value="object:211">Minnesota</option><option label="Mississippi" value="object:212">Mississippi</option><option label="Missouri" value="object:213">Missouri</option><option label="Montana" value="object:214">Montana</option><option label="Nebraska" value="object:215">Nebraska</option><option label="Nevada" value="object:216">Nevada</option><option label="New Hampshire" value="object:217">New Hampshire</option><option label="New Jersey" value="object:218">New Jersey</option><option label="New Mexico" value="object:219">New Mexico</option><option label="New York" value="object:220">New York</option><option label="North Carolina" value="object:221">North Carolina</option><option label="North Dakota" value="object:222">North Dakota</option><option label="Ohio" value="object:223">Ohio</option><option label="Oklahoma" value="object:224">Oklahoma</option><option label="Oregon" value="object:225">Oregon</option><option label="Pennsylvania" value="object:226">Pennsylvania</option><option label="Rhode Island" value="object:227">Rhode Island</option><option label="South Carolina" value="object:228">South Carolina</option><option label="South Dakota" value="object:229">South Dakota</option><option label="Tennessee" value="object:230">Tennessee</option><option label="Texas" value="object:231">Texas</option><option label="Utah" value="object:232">Utah</option><option label="Vermont" value="object:233">Vermont</option><option label="Virginia" value="object:234">Virginia</option><option label="Washington" value="object:235">Washington</option><option label="West Virginia" value="object:236">West Virginia</option><option label="Wisconsin" value="object:237">Wisconsin</option><option label="Wyoming" value="object:238">Wyoming</option></select></div><!----></div><div class="col-xs-5 col-sm-5 col-md-5"><div class="sw-Form_Group"><label for="co-shippmentzip" class="sw-Form_Label">Zip code</label><input id="co-shippmentzip" name="shpZip" class="sw-Form sw-Form_Input ng-pristine ng-untouched ng-empty ng-valid-us-format ng-invalid ng-invalid-required" ng-class="{'sw-Form_Input-error': form.shpZip.$error.required &amp;&amp; (form.shpZip.$dirty || form.$submitted) || form.shpZip.$error.usFormat &amp;&amp; ((form.shpZip.$touched &amp;&amp; form.shpZip.$dirty) || (form.shpZip.$touched || form.$submitted))}" placeholder="Zip code" autocomplete="off" ng-model="vm.shippingAddress.zip" ng-model-options="{ allowInvalid: true }" required="" ng-blur="vm.saveAddress()" ui-validate="{usFormat:'vm.validateZipCodeFormat(vm.shippingAddress.country, $value)'}" uib-tooltip-template="'zipShpMessages.html'" tooltip-trigger="none" tooltip-is-open="form.shpZip.$error.required &amp;&amp; (form.shpZip.$dirty || form.$submitted) || form.shpZip.$error.usFormat &amp;&amp; ((form.shpZip.$touched &amp;&amp; form.shpZip.$dirty) || (form.shpZip.$touched || form.$submitted))" type="text"></div></div></div></div></div><!----><!----><div class="row" ng-if="!vm.orderSummary.donationOnly"><div class="col-xs-12 col-sm-12 col-md-9"><div class="sw-Form_Group"><label class="sw-Form_Label" for="co-shoppmentcountry">Country</label><select name="shpCountry" id="co-shoppmentcountry" class="sw-Form sw-Form_Select block-on-update-order-summary ng-pristine ng-untouched ng-not-empty ng-valid ng-valid-required" required="" autocomplete="off" ng-model="vm.shippingAddress.country" ng-change="vm.saveAddress()" ng-options="country as country.name for country in vm.countries" style=""><option label="United States of America" value="object:240" selected="selected">United States of America</option><option label="Afghanistan" value="object:241">Afghanistan</option><option label="Aland Islands" value="object:242">Aland Islands</option><option label="Albania" value="object:243">Albania</option><option label="Algeria" value="object:244">Algeria</option><option label="American Samoa" value="object:245">American Samoa</option><option label="Andorra" value="object:246">Andorra</option><option label="Angola" value="object:247">Angola</option><option label="Anguilla" value="object:248">Anguilla</option><option label="Antigua and Barbuda" value="object:249">Antigua and Barbuda</option><option label="Argentina" value="object:250">Argentina</option><option label="Armenia" value="object:251">Armenia</option><option label="Aruba" value="object:252">Aruba</option><option label="Australia" value="object:253">Australia</option><option label="Austria" value="object:254">Austria</option><option label="Azerbaijan" value="object:255">Azerbaijan</option><option label="Bahamas" value="object:256">Bahamas</option><option label="Bahrain" value="object:257">Bahrain</option><option label="Bangladesh" value="object:258">Bangladesh</option><option label="Barbados" value="object:259">Barbados</option><option label="Belarus" value="object:260">Belarus</option><option label="Belgium" value="object:261">Belgium</option><option label="Belize" value="object:262">Belize</option><option label="Benin" value="object:263">Benin</option><option label="Bermuda" value="object:264">Bermuda</option><option label="Bhutan" value="object:265">Bhutan</option><option label="Bolivia" value="object:266">Bolivia</option><option label="Bosnia and Herzegovina" value="object:267">Bosnia and Herzegovina</option><option label="Botswana" value="object:268">Botswana</option><option label="Brazil" value="object:269">Brazil</option><option label="Brunei Darussalam" value="object:270">Brunei Darussalam</option><option label="Bulgaria" value="object:271">Bulgaria</option><option label="Burkina Faso" value="object:272">Burkina Faso</option><option label="Burundi" value="object:273">Burundi</option><option label="Cambodia" value="object:274">Cambodia</option><option label="Cameroon" value="object:275">Cameroon</option><option label="Canada" value="object:276">Canada</option><option label="Cape Verde" value="object:277">Cape Verde</option><option label="Cayman Islands" value="object:278">Cayman Islands</option><option label="Central African Republic" value="object:279">Central African Republic</option><option label="Chad" value="object:280">Chad</option><option label="Chile" value="object:281">Chile</option><option label="China" value="object:282">China</option><option label="Christmas Island" value="object:283">Christmas Island</option><option label="Cocos (Keeling) Islands" value="object:284">Cocos (Keeling) Islands</option><option label="Colombia" value="object:285">Colombia</option><option label="Comoros" value="object:286">Comoros</option><option label="Congo" value="object:287">Congo</option><option label="Cook Islands" value="object:288">Cook Islands</option><option label="Costa Rica" value="object:289">Costa Rica</option><option label="Cote D'Ivoire (Ivory Coast)" value="object:290">Cote D'Ivoire (Ivory Coast)</option><option label="Croatia (Hrvatska)" value="object:291">Croatia (Hrvatska)</option><option label="Cuba" value="object:292">Cuba</option><option label="Cyprus" value="object:293">Cyprus</option><option label="Czech Republic" value="object:294">Czech Republic</option><option label="Democratic Republic of the Congo" value="object:295">Democratic Republic of the Congo</option><option label="Denmark" value="object:296">Denmark</option><option label="Djibouti" value="object:297">Djibouti</option><option label="Dominica" value="object:298">Dominica</option><option label="Dominican Republic" value="object:299">Dominican Republic</option><option label="East Timor" value="object:300">East Timor</option><option label="Ecuador" value="object:301">Ecuador</option><option label="Egypt" value="object:302">Egypt</option><option label="El Salvador" value="object:303">El Salvador</option><option label="Equatorial Guinea" value="object:304">Equatorial Guinea</option><option label="Eritrea" value="object:305">Eritrea</option><option label="Estonia" value="object:306">Estonia</option><option label="Ethiopia" value="object:307">Ethiopia</option><option label="Falkland Islands (Malvinas)" value="object:308">Falkland Islands (Malvinas)</option><option label="Faroe Islands" value="object:309">Faroe Islands</option><option label="Federated States of Micronesia" value="object:310">Federated States of Micronesia</option><option label="Fiji" value="object:311">Fiji</option><option label="Finland" value="object:312">Finland</option><option label="France" value="object:313">France</option><option label="French Guiana" value="object:314">French Guiana</option><option label="French Polynesia" value="object:315">French Polynesia</option><option label="Gabon" value="object:316">Gabon</option><option label="Gambia" value="object:317">Gambia</option><option label="Georgia" value="object:318">Georgia</option><option label="Germany" value="object:319">Germany</option><option label="Ghana" value="object:320">Ghana</option><option label="Gibraltar" value="object:321">Gibraltar</option><option label="Great Britain (UK)" value="object:322">Great Britain (UK)</option><option label="Greece" value="object:323">Greece</option><option label="Greenland" value="object:324">Greenland</option><option label="Grenada" value="object:325">Grenada</option><option label="Guadeloupe" value="object:326">Guadeloupe</option><option label="Guam" value="object:327">Guam</option><option label="Guatemala" value="object:328">Guatemala</option><option label="Guinea" value="object:329">Guinea</option><option label="Guinea-Bissau" value="object:330">Guinea-Bissau</option><option label="Guyana" value="object:331">Guyana</option><option label="Haiti" value="object:332">Haiti</option><option label="Honduras" value="object:333">Honduras</option><option label="Hong Kong" value="object:334">Hong Kong</option><option label="Hungary" value="object:335">Hungary</option><option label="Iceland" value="object:336">Iceland</option><option label="India" value="object:337">India</option><option label="Indonesia" value="object:338">Indonesia</option><option label="Iran" value="object:339">Iran</option><option label="Iraq" value="object:340">Iraq</option><option label="Ireland" value="object:341">Ireland</option><option label="Israel" value="object:342">Israel</option><option label="Italy" value="object:343">Italy</option><option label="Jamaica" value="object:344">Jamaica</option><option label="Japan" value="object:345">Japan</option><option label="Jordan" value="object:346">Jordan</option><option label="Kazakhstan" value="object:347">Kazakhstan</option><option label="Kenya" value="object:348">Kenya</option><option label="Kiribati" value="object:349">Kiribati</option><option label="Korea (North)" value="object:350">Korea (North)</option><option label="Korea (South)" value="object:351">Korea (South)</option><option label="Kuwait" value="object:352">Kuwait</option><option label="Kyrgyzstan" value="object:353">Kyrgyzstan</option><option label="Laos" value="object:354">Laos</option><option label="Latvia" value="object:355">Latvia</option><option label="Lebanon" value="object:356">Lebanon</option><option label="Lesotho" value="object:357">Lesotho</option><option label="Liberia" value="object:358">Liberia</option><option label="Libya" value="object:359">Libya</option><option label="Liechtenstein" value="object:360">Liechtenstein</option><option label="Lithuania" value="object:361">Lithuania</option><option label="Luxembourg" value="object:362">Luxembourg</option><option label="Macao" value="object:363">Macao</option><option label="Macedonia" value="object:364">Macedonia</option><option label="Madagascar" value="object:365">Madagascar</option><option label="Malawi" value="object:366">Malawi</option><option label="Malaysia" value="object:367">Malaysia</option><option label="Maldives" value="object:368">Maldives</option><option label="Mali" value="object:369">Mali</option><option label="Malta" value="object:370">Malta</option><option label="Marshall Islands" value="object:371">Marshall Islands</option><option label="Martinique" value="object:372">Martinique</option><option label="Mauritania" value="object:373">Mauritania</option><option label="Mauritius" value="object:374">Mauritius</option><option label="Mayotte" value="object:375">Mayotte</option><option label="Mexico" value="object:376">Mexico</option><option label="Moldova" value="object:377">Moldova</option><option label="Monaco" value="object:378">Monaco</option><option label="Mongolia" value="object:379">Mongolia</option><option label="Montserrat" value="object:380">Montserrat</option><option label="Morocco" value="object:381">Morocco</option><option label="Mozambique" value="object:382">Mozambique</option><option label="Myanmar" value="object:383">Myanmar</option><option label="Namibia" value="object:384">Namibia</option><option label="Nauru" value="object:385">Nauru</option><option label="Nepal" value="object:386">Nepal</option><option label="Netherlands" value="object:387">Netherlands</option><option label="Netherlands Antilles" value="object:388">Netherlands Antilles</option><option label="New Caledonia" value="object:389">New Caledonia</option><option label="New Zealand (Aotearoa)" value="object:390">New Zealand (Aotearoa)</option><option label="Nicaragua" value="object:391">Nicaragua</option><option label="Niger" value="object:392">Niger</option><option label="Nigeria" value="object:393">Nigeria</option><option label="Niue" value="object:394">Niue</option><option label="Norfolk Island" value="object:395">Norfolk Island</option><option label="Northern Mariana Islands" value="object:396">Northern Mariana Islands</option><option label="Norway" value="object:397">Norway</option><option label="Oman" value="object:398">Oman</option><option label="Pakistan" value="object:399">Pakistan</option><option label="Palau" value="object:400">Palau</option><option label="Panama" value="object:401">Panama</option><option label="Papua New Guinea" value="object:402">Papua New Guinea</option><option label="Paraguay" value="object:403">Paraguay</option><option label="Peru" value="object:404">Peru</option><option label="Philippines" value="object:405">Philippines</option><option label="Pitcairn" value="object:406">Pitcairn</option><option label="Poland" value="object:407">Poland</option><option label="Portugal" value="object:408">Portugal</option><option label="Puerto Rico" value="object:409">Puerto Rico</option><option label="Qatar" value="object:410">Qatar</option><option label="Reunion" value="object:411">Reunion</option><option label="Romania" value="object:412">Romania</option><option label="Russian Federation" value="object:413">Russian Federation</option><option label="Rwanda" value="object:414">Rwanda</option><option label="Saint Helena" value="object:415">Saint Helena</option><option label="Saint Kitts and Nevis" value="object:416">Saint Kitts and Nevis</option><option label="Saint Lucia" value="object:417">Saint Lucia</option><option label="Saint Martin" value="object:418">Saint Martin</option><option label="Saint Pierre and Miquelon" value="object:419">Saint Pierre and Miquelon</option><option label="Saint Vincent and the Grenadines" value="object:420">Saint Vincent and the Grenadines</option><option label="Samoa" value="object:421">Samoa</option><option label="San Marino" value="object:422">San Marino</option><option label="Sao Tome and Principe" value="object:423">Sao Tome and Principe</option><option label="Saudi Arabia" value="object:424">Saudi Arabia</option><option label="Senegal" value="object:425">Senegal</option><option label="Serbia" value="object:426">Serbia</option><option label="Seychelles" value="object:427">Seychelles</option><option label="S. Georgia and S. Sandwich Islands" value="object:428">S. Georgia and S. Sandwich Islands</option><option label="Sierra Leone" value="object:429">Sierra Leone</option><option label="Singapore" value="object:430">Singapore</option><option label="Slovakia" value="object:431">Slovakia</option><option label="Slovenia" value="object:432">Slovenia</option><option label="Solomon Islands" value="object:433">Solomon Islands</option><option label="Somalia" value="object:434">Somalia</option><option label="South Africa" value="object:435">South Africa</option><option label="Spain" value="object:436">Spain</option><option label="Sri Lanka" value="object:437">Sri Lanka</option><option label="Sudan" value="object:438">Sudan</option><option label="Suriname" value="object:439">Suriname</option><option label="Svalbard and Jan Mayen" value="object:440">Svalbard and Jan Mayen</option><option label="Swaziland" value="object:441">Swaziland</option><option label="Sweden" value="object:442">Sweden</option><option label="Switzerland" value="object:443">Switzerland</option><option label="Syria" value="object:444">Syria</option><option label="Taiwan" value="object:445">Taiwan</option><option label="Tajikistan" value="object:446">Tajikistan</option><option label="Tanzania" value="object:447">Tanzania</option><option label="Thailand" value="object:448">Thailand</option><option label="Timor-Leste" value="object:449">Timor-Leste</option><option label="Togo" value="object:450">Togo</option><option label="Tokelau" value="object:451">Tokelau</option><option label="Tonga" value="object:452">Tonga</option><option label="Trinidad and Tobago" value="object:453">Trinidad and Tobago</option><option label="Tunisia" value="object:454">Tunisia</option><option label="Turkey" value="object:455">Turkey</option><option label="Turkmenistan" value="object:456">Turkmenistan</option><option label="Turks and Caicos Islands" value="object:457">Turks and Caicos Islands</option><option label="Tuvalu" value="object:458">Tuvalu</option><option label="Uganda" value="object:459">Uganda</option><option label="Ukraine" value="object:460">Ukraine</option><option label="United Arab Emirates" value="object:461">United Arab Emirates</option><option label="United Kingdom" value="object:462">United Kingdom</option><option label="United States Minor Outlying Islands" value="object:463">United States Minor Outlying Islands</option><option label="United States of America" value="object:464">United States of America</option><option label="Uruguay" value="object:465">Uruguay</option><option label="Uzbekistan" value="object:466">Uzbekistan</option><option label="Vanuatu" value="object:467">Vanuatu</option><option label="Vatican City State (Holy See)" value="object:468">Vatican City State (Holy See)</option><option label="Venezuela" value="object:469">Venezuela</option><option label="Viet Nam" value="object:470">Viet Nam</option><option label="Virgin Islands (British)" value="object:471">Virgin Islands (British)</option><option label="Virgin Islands (U.S.)" value="object:472">Virgin Islands (U.S.)</option><option label="Wallis and Futuna" value="object:473">Wallis and Futuna</option><option label="Yemen" value="object:474">Yemen</option><option label="Zambia" value="object:475">Zambia</option><option label="Zimbabwe" value="object:476">Zimbabwe</option></select></div></div></div><!----><!----><!----><div ng-if="!vm.hideEmail"><div class="sw-Form_Group"><label for="co-email" class="sw-Form_Label">Email address</label><input id="co-email" name="email" class="sw-Form sw-Form_Input ng-pristine ng-untouched ng-empty ng-invalid ng-invalid-required ng-valid-email" ng-class="{'sw-Form_Input-error': form.email.$error.required &amp;&amp; (form.email.$dirty || form.$submitted)}" ng-model="vm.email" placeholder="email@example.com" autocomplete="off" required="" uib-tooltip-html="'<span>Please enter your email</span>'" tooltip-trigger="none" tooltip-is-open="form.email.$error.required &amp;&amp; (form.email.$dirty || form.$submitted)" type="email"></div></div><!----><!----><div class="sw-Form_Checkbox" ng-if="!vm.orderSummary.donationOnly"><div class="checkbox-cnt"><div class="checkbox-layer ng-not-empty ng-valid checked" ng-class="{'checked': isChecked, 'checkbox-layer-disabled': disabled}" ng-click="toggle()" ng-model="vm.billingAddressIsSame" disabled="disabled"></div></div><p class="sw-Form_CheckboxLabel" ng-click="vm.billingAddressIsSame = (vm.preferencesDisabled) ? vm.billingAddressIsSame : !vm.billingAddressIsSame">Billing address is same as shipping</p></div><!---->
```

## Trace-level log

I have problem with filling the address data. Only for street field driver is failing to send data. For all others, chrome, opera and Safari, same code is working perfectly. Im using it with Python, tried to find element by id, css, xpath, no difference.
PyCharm, Python - pytest, Selenium, geckodriver 0.19.1, tried also with 0.18.x and 0.19, it was the same.

**Comment by whimboo** [comment]
Can you please attach a trace level log as requested? That would give way more information for us to act on. Thanks.

**Comment by cikakosta** [comment]
Im not so experienced, so Im pasting traceback. If I missed something, please ask.

```
Traceback (most recent call last):
  File "/Users/jjbonfire/PycharmProjects/FirstDevbonfire/tests/try/DropdownSelect.py", line 20, in <module>
    ff.test()
  File "/Users/jjbonfire/PycharmProjects/FirstDevbonfire/tests/try/DropdownSelect.py", line 17, in test
    driver.find_element(By.XPATH, "//input[@id='co-shippingaddress']").send_keys("Hello Hello Street")
  File "/Users/jjbonfire/PycharmProjects/FirstDevbonfire/lib/python3.6/site-packages/selenium/webdriver/remote/webelement.py", line 352, in send_keys
    'value': keys_to_typing(value)})
  File "/Users/jjbonfire/PycharmProjects/FirstDevbonfire/lib/python3.6/site-packages/selenium/webdriver/remote/webelement.py", line 501, in _execute
    return self._parent.execute(command, params)
  File "/Users/jjbonfire/PycharmProjects/FirstDevbonfire/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 308, in execute
    self.error_handler.check_response(response)
  File "/Users/jjbonfire/PycharmProjects/FirstDevbonfire/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementNotInteractableException: Message: Element is not visible
```

Thanks

**Comment by whimboo** [comment]
@cikakosta please see https://firefox-source-docs.mozilla.org/testing/geckodriver/geckodriver/TraceLogs.html in how to get a trace level log. Once you have it please add it as attachment. Thanks.

**Comment by cikakosta** [comment]
Hey @whimboo Thanks for your patience :)

Im now pasting a new code and attaching file as requested.

```
from selenium import webdriver
from selenium.webdriver.firefox.options import Options
opts = Options()
opts.log.level = "trace"
from selenium.webdriver.common.by import By

class FillTheAddress():

    def test(self):
        baseUrl = "https://www.bonfire.com/stbw-loon-design/buy/"
        driver = webdriver.Firefox(firefox_options=opts)
        # driver.maximize_window()
        driver.get(baseUrl)
        driver.implicitly_wait(10)
        driver.find_element_by_xpath("//select[@name='prod0size']/option[text()='M']").click()
        driver.find_element_by_xpath("//button[@class='sw-BtnDefault sw-BtnDefault-success sw-BtnWide']").click()
        driver.find_element(By.XPATH, "//input[@name='name']").send_keys("Mitar Mitra Mitar")
        driver.find_element(By.XPATH, "//input[@id='co-shippingaddress']").send_keys("Hello Hello Street")

ff = FillTheAddress()
ff.test()
```


[geckodriver.log](https://github.com/mozilla/geckodriver/files/1517162/geckodriver.log)

**Comment by whimboo** [comment]
Can you please test again with a recent Firefox 58 beta, or Firefox Nightly version? Those contain better intractability checks, and it should hopefully work.

You can find those builds at https://www.mozilla.org/en-US/firefox/channel/desktop/

**Comment by cikakosta** [comment]
I just tried 58 beta and it appears that this is working properly. However, there other issues with clicking but this will be documented in another ticket.

Thank you @whimboo :)

**Comment by whimboo** [comment]
Thank you for checking! Marking this issue as worksforme then.
