### ISSUE TITLE
selenium + geckodriver + nodejs start browser   but get  error "firefox.exe: other os error"

### ISSUE THREAD

**Issue by wenJanus** [mozilla/geckodriver#1083]
## System
* Version:  v0.19.1
* Platform: windows7
* Firefox: 57.0.1
* Selenium: selenium-webdriver@3.5.0

## Testcase
http://

var webdriver = require('selenium-webdriver'),
    By = webdriver.By,
    until = webdriver.until;
    promise = webdriver.promise;

var firefox = require('selenium-webdriver/firefox');
// promise.USE_PROMISE_MANAGER = false;
var binary = new firefox.Binary('C:/Program Files/Mozilla Firefox/firefox.exe');
binary.addArguments("-headless");

var driver = new webdriver.Builder()
    .forBrowser('firefox')
    .setFirefoxOptions(new firefox.Options().setBinary(binary))
    .build();

driver.get('https://www.google.com');

## Stacktrace

SessionNotCreatedError: Failed to start browser C:/Program Files/Mozilla Firefox/firefox.exe: other os error
    at WebDriverError (C:\Users\ewenzye\workspace\headless-examples\node_modules\selenium-webdriver\lib\error.js:27:5)
    at SessionNotCreatedError (C:\Users\ewenzye\workspace\headless-examples\node_modules\selenium-webdriver\lib\error.js:222:5)
    at Object.throwDecodedError (C:\Users\ewenzye\workspace\headless-examples\node_modules\selenium-webdriver\lib\error.js:497:15)
    at parseHttpResponse (C:\Users\ewenzye\workspace\headless-examples\node_modules\selenium-webdriver\lib\http.js:519:13)
    at doSend.then.response (C:\Users\ewenzye\workspace\headless-examples\node_modules\selenium-webdriver\lib\http.js:441:30)
    at process._tickCallback (internal/process/next_tick.js:109:7)
From: Task: WebDriver.createSession()
    at Function.createSession (C:\Users\ewenzye\workspace\headless-examples\node_modules\selenium-webdriver\lib\webdriver.js:769:24)
    at Function.createSession (C:\Users\ewenzye\workspace\headless-examples\node_modules\selenium-webdriver\firefox\index.js:571:41)
    at createDriver (C:\Users\ewenzye\workspace\headless-examples\node_modules\selenium-webdriver\index.js:170:33)
    at Builder.build (C:\Users\ewenzye\workspace\headless-examples\node_modules\selenium-webdriver\index.js:645:16)
    at Object.<anonymous> (C:\Users\ewenzye\workspace\headless-examples\selenium-test.js:14:6)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

**Comment by wenJanus** [comment]
1512028542455   webdriver::server       DEBUG   -> POST /session {"desiredCapabilities":{"browserName":"firefox","moz:firefoxOptions":{"binary":"C:/Program Files/Mozilla Firefox/firefox.exe","args":["--headless"]}}}
1512028542504   mozrunner::runner       INFO    Running command: "C:/Program Files/Mozilla Firefox/firefox.exe" "-marionette" "--headless" "-profile" "C:\\Users\\ewenzye\\AppData\\Local\\Temp\\rust_mozprofile.YIfDs1qjrzD7"
1512028542572   webdriver::server       DEBUG   <- 500 Internal Server Error {"value":{"error":"session not created","message":"Failed to start browser C:/Program Files/Mozilla Firefox/firefox.exe: other os error","stacktrace":"stack backtrace:\n   0:           0x4821c4 - <no info>\n   1:           0x482933 - <no info>\n   2:           0x445159 - <no info>\n   3:           0x44cbd2 - <no info>\n   4:
      0x43026a - <no info>\n   5:           0x40ba4e - <no info>\n   6:           0x4119b9 - <no info>\n   7:           0x6d2c89 - <no info>\n   8:           0x426006 - <no info>\n   9:           0x6cd490 - <no info>\n  10:         0x773459cd - BaseThreadInitThunk"}}

**Comment by whimboo** [comment]
Please add that information to your already filed issue #940. Duping this one now.
