### ISSUE TITLE
Firefox can not be controlled by geckodriver: connection refused

### ISSUE THREAD

**Issue by StegSchreck** [mozilla/geckodriver#1085]
## System
* Version: geckodriver 0.19.1
* Platform: CentOS 7.4.1708
* Firefox: 52.5.0 
* Selenium: python selenium==3.4.3

## Code
```
    def _init_browser(self):
        capabilities = DesiredCapabilities.FIREFOX.copy()
        capabilities["moz:firefoxOptions"] = {
            "log": {
                "level": "trace",
            },
        }

        options = Options()
        options.log.level = 'trace'

        profile = FirefoxProfile()
        profile.set_preference("browser.download.folderList", 2)
        profile.set_preference("browser.download.manager.showWhenStarting", False)
        profile.set_preference("browser.download.dir", EXPORTS_FOLDER)
        profile.set_preference("browser.helperApps.neverAsk.saveToDisk", "text/csv, application/zip")
        profile.set_preference("browser.helperApps.alwaysAsk.force", False)
        profile.set_preference("devtools.jsonview.enabled", False)
        profile.set_preference("media.volume_scale", "0.0")

        # https://github.com/mozilla/geckodriver/issues/858#issuecomment-322512336
        profile.set_preference("dom.file.createInChild", True)

        self.browser = Firefox(firefox_profile=profile, capabilities=capabilities, firefox_options=options)

        # http://stackoverflow.com/questions/42754877/cant-upload-file-using-selenium-with-python-post-post-session-b90ee4c1-ef51-4  # pylint: disable=line-too-long
        self.browser._is_remote = False  # pylint: disable=protected-access
```
Capabilities and options were only added in order to have a TRACE log.

## Stacktrace
Firefox is started, but the commands are not executed, after a while, this stacktrace appears:

```
Traceback (most recent call last):
  File "transfer_ratings.py", line 149, in <module>
    main()
  File "transfer_ratings.py", line 65, in main
    execute(args)
  File "transfer_ratings.py", line 110, in execute
    parser = get_parser_from_arg(args.source)(args)
  File "/home/developer/repos/RatS/RatS/movielens/movielens_ratings_parser.py", line 13, in __init__
    super(MovielensRatingsParser, self).__init__(Movielens(args), args)
  File "/home/developer/repos/RatS/RatS/movielens/movielens_site.py", line 11, in __init__
    super(Movielens, self).__init__(args)
  File "/home/developer/repos/RatS/RatS/base/base_site.py", line 33, in __init__
    self._init_browser()
  File "/home/developer/repos/RatS/RatS/base/base_site.py", line 78, in _init_browser
    self.browser = Firefox(firefox_profile=profile, capabilities=capabilities, firefox_options=options)
  File "/home/developer/virtual_env/RatS/lib64/python3.4/site-packages/selenium/webdriver/firefox/webdriver.py", line 152, in __init__
    keep_alive=True)
  File "/home/developer/virtual_env/RatS/lib64/python3.4/site-packages/selenium/webdriver/remote/webdriver.py", line 98, in __init__
    self.start_session(desired_capabilities, browser_profile)
  File "/home/developer/virtual_env/RatS/lib64/python3.4/site-packages/selenium/webdriver/remote/webdriver.py", line 188, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/home/developer/virtual_env/RatS/lib64/python3.4/site-packages/selenium/webdriver/remote/webdriver.py", line 256, in execute
    self.error_handler.check_response(response)
  File "/home/developer/virtual_env/RatS/lib64/python3.4/site-packages/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: connection refused

```

## Trace-level log
[geckodriver.log](https://github.com/mozilla/geckodriver/files/1518187/geckodriver.log)

I tried to update Firefox and geckodriver, but it didn't help. Could anyone please give me a hint, what my problem is?

**Comment by StegSchreck** [comment]
After installing Firefox 57.0.1 manually (as it isn't in the yum repository unfortunately), it worked. Thanks!
