### ISSUE TITLE
Process unexpectedly closed with status: 1

### ISSUE THREAD

**Issue by PascalGit1** [mozilla/geckodriver#1091]
## System
* Version: 19.0
* Platform: Linux server
* Firefox: Nightly 
* Selenium: 3.8.1
'
I'm running my cucumber tests from a linux machine using jenkins.
Every few tests they will fail randomly with the Process unexpectedly closed with status: 1 error

## Trace-level log

I just added all the logs from a failed case that had this error:

```

1512470895022	geckodriver	INFO	geckodriver 0.19.0
1512470895028	geckodriver	INFO	Listening on 127.0.0.1:15094
1512470895278	mozrunner::runner	INFO	Running command: "/opt/firefox/firefox" "-marionette" "-profile" "/tmp/rust_mozprofile.cwX6A51p8KAU"
1512470895315	geckodriver::marionette	TRACE	  connection attempt 0/600
Error: cannot open display: :95
1512470895419	webdriver::server	DEBUG	<- 500 Internal Server Error {"value":{"error":"unknown error","message":"Process unexpectedly closed with status: 1","stacktrace":"stack backtrace:\n   0:           0x4f388c - backtrace::backtrace::trace::h736111741fa0878e\n   
1:           0x4f38c2 - backtrace::capture::Backtrace::new::h63b8a5c0787510c9\n   
2:           0x442d88 - webdriver::error::WebDriverError::new::hea6d4dbf778b2b24\n   
3:           0x44a8c3 - geckodriver::marionette::MarionetteHandler::create_connection::hf8b6061dba65cdd0\n   
4:           0x42ac91 - <webdriver::server::Dispatcher<T, U>>::run::hba9181b5aacf8f04\n   
5:           0x402c59 - std::sys_common::backtrace::__rust_begin_short_backtrace::h19de262639927233\n   
6:           0x40c065 - std::panicking::try::do_call::h6c1659fc4d01af51\n   
7:           0x5e38ec - panic_unwind::__rust_maybe_catch_panic\n                        at /checkout/src/libpanic_unwind/lib.rs:98\n   
8:           0x420d32 - <F as alloc::boxed::FnBox<A>>::call_box::h953e5f59694972c5\n   
9:           0x5dc00b - alloc::boxed::{{impl}}::call_once<(),()>\n                        at /checkout/src/liballoc/boxed.rs:661\n                         - std::sys_common::thread::start_thread\n                        at /checkout/src/libstd/sys_common/thread.rs:21\n                         - std::sys::imp::thread::{{impl}}::new::thread_start\n                        at /checkout/src/libstd/sys/unix/thread.rs:84"}}
Failure in before hook:EsizeCucumberTest.setupTest()
Message: org.openqa.selenium.WebDriverException: Process unexpectedly closed with status: 1
Build info: version: '3.8.1', revision: '6e95a6684b', time: '2017-12-01T18:33:54.468Z'
System info: host: 'ehgd-bld-l04.esizedc.com', ip: '10.3.162.21', os.name: 'Linux', os.arch: 'amd64', os.version: '3.10.0-693.2.2.el7.x86_64', java.version: '1.8.0_144'
Driver info: driver.version: FirefoxDriver
remote stacktrace: stack backtrace:
   0:           0x4f388c - backtrace::backtrace::trace::h736111741fa0878e
   1:           0x4f38c2 - backtrace::capture::Backtrace::new::h63b8a5c0787510c9
   2:           0x442d88 - webdriver::error::WebDriverError::new::hea6d4dbf778b2b24
   3:           0x44a8c3 - geckodriver::marionette::MarionetteHandler::create_connection::hf8b6061dba65cdd0
   4:           0x42ac91 - <webdriver::server::Dispatcher<T, U>>::run::hba9181b5aacf8f04
   5:           0x402c59 - std::sys_common::backtrace::__rust_begin_short_backtrace::h19de262639927233
   6:           0x40c065 - std::panicking::try::do_call::h6c1659fc4d01af51
   7:           0x5e38ec - panic_unwind::__rust_maybe_catch_panic
                        at /checkout/src/libpanic_unwind/lib.rs:98
   8:           0x420d32 - <F as alloc::boxed::FnBox<A>>::call_box::h953e5f59694972c5
   9:           0x5dc00b - alloc::boxed::{{impl}}::call_once<(),()>
                        at /checkout/src/liballoc/boxed.rs:661
                         - std::sys_common::thread::start_thread
                        at /checkout/src/libstd/sys_common/thread.rs:21
                         - std::sys::imp::thread::{{impl}}::new::thread_start
                        at /checkout/src/libstd/sys/unix/thread.rs:84
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.W3CHandshakeResponse.lambda$new$0(W3CHandshakeResponse.java:57)
	at org.openqa.selenium.remote.W3CHandshakeResponse.lambda$getResponseFunction$2(W3CHandshakeResponse.java:104)
	at org.openqa.selenium.remote.ProtocolHandshake.lambda$createSession$0(ProtocolHandshake.java:123)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:958)
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:464)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:126)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:73)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:142)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:601)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:219)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:142)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:120)
	at nl.esize.cucumber.helper.LinuxDriverHelper.getDriver(LinuxDriverHelper.java:52)
	at nl.esize.cucumber.helper.DriverHelper.setUp(DriverHelper.java:29)
	at nl.esize.cucumber.EsizeCucumberTest.setupTest(EsizeCucumberTest.java:36)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at cucumber.runtime.Utils$1.call(Utils.java:40)
	at cucumber.runtime.Timeout.timeout(Timeout.java:16)
	at cucumber.runtime.Utils.invoke(Utils.java:34)
	at cucumber.runtime.java.JavaHookDefinition.execute(JavaHookDefinition.java:60)
	at cucumber.runtime.Runtime.runHookIfTagsMatch(Runtime.java:224)
	at cucumber.runtime.Runtime.runHooks(Runtime.java:212)
	at cucumber.runtime.Runtime.runBeforeHooks(Runtime.java:202)
	at cucumber.runtime.model.CucumberScenario.run(CucumberScenario.java:40)
	at cucumber.runtime.junit.ExecutionUnitRunner.run(ExecutionUnitRunner.java:102)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at cucumber.runtime.junit.ExamplesRunner.run(ExamplesRunner.java:59)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at cucumber.runtime.junit.ScenarioOutlineRunner.run(ScenarioOutlineRunner.java:53)
	at cucumber.runtime.junit.FeatureRunner.runChild(FeatureRunner.java:63)
	at cucumber.runtime.junit.FeatureRunner.runChild(FeatureRunner.java:18)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at cucumber.runtime.junit.FeatureRunner.run(FeatureRunner.java:70)
	at cucumber.api.junit.Cucumber.runChild(Cucumber.java:95)
	at cucumber.api.junit.Cucumber.runChild(Cucumber.java:38)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at cucumber.api.junit.Cucumber.run(Cucumber.java:100)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:367)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:274)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:161)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)

```

**Comment by andreastt** [comment]
`Error: cannot open display: :95` would indicate that Firefox fails to open on that X display. Make sure you set the `DISPLAY` output variable properly for the process.

In any case, not a geckodriver issue.

**Comment by PascalGit1** [comment]
I'm not sure what else to set for the display, its weird that it works some of the tests but fails randomly.
It also works fine on other browsers.

How i set the display:
![display](https://user-images.githubusercontent.com/22746723/33607563-dafc1d04-d9c1-11e7-94e4-a7e6e92f075e.png)

**Comment by whimboo** [comment]
Your screenshot shows a display :96, while the log has :95. Why the difference?

**Comment by PascalGit1** [comment]
this screenshot was made after the test on 95, i changed it because 95 was in use at the time.

**Comment by whimboo** [comment]
Ok, so as you have said it sometimes fails but not all the time. I have seen a similar thing on issue #1020, which this issue might be a dupe of. But first please provide a [trace log](https://firefox-source-docs.mozilla.org/testing/geckodriver/geckodriver/TraceLogs.html) which shows that it works for one test, but then fails for the next one. I would really appreciate that. Thanks.

**Comment by PascalGit1** [comment]
same test run directly after the failed one i showed earlier that succeeded:

```
1512479715142	geckodriver::marionette	TRACE	<- [1,15,null,{"value":true}]
1512479715142	webdriver::server	DEBUG	<- 200 OK {"value":true}
1512479715159	webdriver::server	DEBUG	-> GET /session/245544be-1dd0-4aa9-8481-41c0a9a95632/element/5b6c983a-9a0f-4421-8fd4-109201aa0ffe/enabled 
1512479715159	geckodriver::marionette	TRACE	-> 71:[0,16,"isElementEnabled",{"id":"5b6c983a-9a0f-4421-8fd4-109201aa0ffe"}]
1512479715223	geckodriver::marionette	TRACE	<- [1,16,null,{"value":true}]
1512479715226	webdriver::server	DEBUG	<- 200 OK {"value":true}
1512479715230	webdriver::server	DEBUG	-> POST /session/245544be-1dd0-4aa9-8481-41c0a9a95632/element {"value":"#form\\-header\\-search\\:search\\-general_input","using":"css selector"}
1512479715230	geckodriver::marionette	TRACE	-> 104:[0,17,"findElement",{"using":"css selector","value":"#form\\-header\\-search\\:search\\-general_input"}]
1512479715236	geckodriver::marionette	TRACE	<- [1,17,null,{"value":{"element-6066-11e4-a52e-4f735466cecf":"5b6c983a-9a0f-4421-8fd4-109201aa0ffe","ELEMENT":"5b6c983a-9a0f-4421-8fd4-109201aa0ffe"}}]
1512479715236	webdriver::server	DEBUG	<- 200 OK {"value":{"element-6066-11e4-a52e-4f735466cecf":"5b6c983a-9a0f-4421-8fd4-109201aa0ffe"}}
1512479715463	webdriver::server	DEBUG	-> DELETE /session/245544be-1dd0-4aa9-8481-41c0a9a95632 
1512479715466	geckodriver::marionette	TRACE	-> 38:[0,18,"quit",{"flags":["eForceQuit"]}]
1512479715468	Marionette	TRACE	0 -> [0,18,"quit",{"flags":["eForceQuit"]}]
1512479715468	Marionette	DEBUG	New connections will no longer be accepted
1512479715537	Marionette	TRACE	0 <- [1,18,null,{"cause":"shutdown"}]
1512479715576	geckodriver::marionette	TRACE	<- [1,18,null,{"cause":"shutdown"}]
1512479715576	webdriver::server	DEBUG	Deleting session
1512479715576	geckodriver::marionette	DEBUG	Stopping browser process
[Child 17354, Chrome_ChildThread] WARNING: pipe error (3): Connection reset by peer: file /builds/worker/workspace/build/src/ipc/chromium/src/chrome/common/ipc_channel_posix.cc, line 353
1512479715611	webdriver::server	DEBUG	<- 200 OK {"value": {}}
```

**Comment by whimboo** [comment]
I think we have to clarify... Are you running only a single test, and running it fails sometimes? Or do you have a set of tests which get run, and randomly the connection to Firefox fails in the middle of such a run.

**Comment by PascalGit1** [comment]
sorry if i wasn't clear its a set of tests and the connection fails in the middle of such a run at random

**Comment by whimboo** [comment]
Ok, so lets continue the investigation on issue #1020 then. Marking this issue as a dupe.
