### ISSUE TITLE
cannot create driver when running in Windows scheduled task

### ISSUE THREAD

**Issue by 4nt01ne** [mozilla/geckodriver#1095]
## System
* Version: 0.19.1
* Platform: Windows Server 2012 (offline accessed via remote desktop)
* Firefox: 57.0.2 (64-bit)
* Selenium: 3.8.1

## Testcase

Using java driver:

```
System.setProperty("webdriver.gecko.driver", geckDriverExecutable.toString());
FirefoxOptions options = new FirefoxOptions()
    .setBinary(new FirefoxBinary())
    .setAcceptInsecureCerts(Boolean.TRUE);
GeckoDriverService geckoDriverService = new GeckoDriverService.Builder()
    .usingDriverExecutable(new File("D:\\Applications\\simple-test\\geckodriver.exe"))
    .build();
FirefoxDriver driver = new FirefoxDriver(geckoDriverService, options);**

```

Stacktrace is produced when the driver is instantiated (last line of snippet.
However, the geckodriver is started and Firefox too.
After some time it hits the code (not shown here) to stop the GeckoDriverService and stops.

It is only failing when runned via a scheduled task (run when user not logged in and with highest privilege)

Please provide guidance to achieve execution in scheduled task.

## Stacktrace

org.openqa.selenium.WebDriverException: connection reset
Build info: version: '3.8.1', revision: '6e95a6684b', time: '2017-12-01T18:33:54.468Z'
System info: host: 'AP6061', ip: '10.48.160.118', os.name: 'Windows Server 2012', os.arch: 'amd64', os.version: '6.2', java.version: '1.8.0_144'
Driver info: driver.version: FirefoxDriver
remote stacktrace: stack backtrace:
   0:           0x47e934 - <no info>
   1:           0x47f0a3 - <no info>
   2:           0x476b0a - <no info>
   3:           0x477440 - <no info>
   4:           0x4490d8 - <no info>
   5:           0x42a890 - <no info>
   6:           0x406f5e - <no info>
   7:           0x40cfc9 - <no info>
   8:           0x6bef19 - <no info>
   9:           0x420756 - <no info>
  10:           0x6b96e0 - <no info>
  11:      0x7f975471842 - BaseThreadInitThunk
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.W3CHandshakeResponse.lambda$new$0(W3CHandshakeResponse.java:57)
	at org.openqa.selenium.remote.W3CHandshakeResponse.lambda$getResponseFunction$2(W3CHandshakeResponse.java:104)
	at org.openqa.selenium.remote.ProtocolHandshake.lambda$createSession$0(ProtocolHandshake.java:123)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:958)
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:464)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:126)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:73)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:142)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:601)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:219)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:142)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:132)
	at com.bics.smart.skpis.FirefoxWebpageTest.openDriver(FirefoxWebpageTest.java:108)
	at com.bics.smart.skpis.FirefoxWebpageTest.main(FirefoxWebpageTest.java:55)

## Trace-level 
[firefox.log](https://github.com/mozilla/geckodriver/files/1543342/firefox.log)

**Comment by andreastt** [comment]
Could you please attach a [trace-level log] from geckodriver? Read more about reporting actionable bugs in our [contribution guidelines].

[trace-level log]: https://searchfox.org/mozilla-central/source/testing/geckodriver/doc/TraceLogs.md
[contribution guidelines]: https://searchfox.org/mozilla-central/source/testing/geckodriver/CONTRIBUTING.md#reporting-bugs

**Comment by 4nt01ne** [comment]
trace level logs [firefox.log](https://github.com/mozilla/geckodriver/files/1543803/firefox.log)

**Comment by 4nt01ne** [comment]
can somebody give an insight please.
FYI I had the same issue when using Selenium 3.5.3 and Firefox 55.0.1 but I don't have the logs anymore. If needed I could reproduce it.
I switched to newer versions to try the headless capability

**Comment by andreastt** [comment]
Those are not trace-level logs, but to me it looks like Firefox is crashing on startup. I don’t believe that is a geckodriver bug.

**Comment by ftalo** [comment]
I have exactly the same problem described by 4nt01ne.

As he suggested the exact same task it is only failing when run via a scheduled task (run when user not logged in and with highest privilege) while it is perfectly working when executed once logged on the Windows machine. 

I was running the scheduled task on the same type of Windows machine: Windows Server 2012 64 bit.

It is sounds to me as a too big coincidence

**Comment by whimboo** [comment]
This is a startup crash of Firefox, and might be related to issue #466. Please try to run your tests by setting the preference "security.sandbox.content.level" to 4. Does that help? If not please try again with a Nightly build of Firefox which you can find here: https://www.mozilla.org/en-US/firefox/channel/desktop/#nightly

**Comment by 4nt01ne** [comment]
it is indeed related to Firefox. We never managed to have it running as a Windows service.
We then switched to a scheduled task with preference "security.sandbox.content.level" set to 4.
This is working fine on our Windows Server 2012 with Firefox 57.0.2 and Geckodriver 0.19
