### ISSUE TITLE
StaleElementReferenceError on unreferenced iframes

### ISSUE THREAD

**Issue by matthewbyrne** [mozilla/geckodriver#1098]
## System
* Version: 0.19.0
* Platform: Ubuntu 14.04
* Firefox: FF 58.0b9
* Selenium: 3.8.0 (watir 6.10)

## Testcase

Unreferenced iframes are throwing a StaleElementReferenceError in my code. I never reference `iframe-name` (see stack trace below), yet it throws the exception.
The line of code it actually fails on is this:
`@browser.div(:id => 'search').wait_until(&:present?)`
Which makes no sense to me.

## Stacktrace

```
Selenium::WebDriver::Error::StaleElementReferenceError: Exception The element reference of <iframe id="iframe-name"> is stale; either the element is no longer attached to the DOM, it is not in the current frame context, or the document has been refreshed
  Stack Trace:
  stack backtrace:
     0:           0x4f388c - backtrace::backtrace::trace::h736111741fa0878e
     1:           0x4f38c2 - backtrace::capture::Backtrace::new::h63b8a5c0787510c9
     2:           0x442d88 - webdriver::error::WebDriverError::new::hea6d4dbf778b2b24
     3:           0x44cecc - geckodriver::marionette::MarionetteSession::response::h98d048d51a7ee2ba
     4:           0x42c729 - <webdriver::server::Dispatcher<T, U>>::run::hba9181b5aacf8f04
     5:           0x402c59 - std::sys_common::backtrace::__rust_begin_short_backtrace::h19de262639927233
     6:           0x40c065 - std::panicking::try::do_call::h6c1659fc4d01af51
     7:           0x5e38ec - panic_unwind::__rust_maybe_catch_panic
                          at /checkout/src/libpanic_unwind/lib.rs:98
     8:           0x420d32 - <F as alloc::boxed::FnBox<A>>::call_box::h953e5f59694972c5
     9:           0x5dc00b - alloc::boxed::{{impl}}::call_once<(),()>
                          at /checkout/src/liballoc/boxed.rs:661
                           - std::sys_common::thread::start_thread
                          at /checkout/src/libstd/sys_common/thread.rs:21
                           - std::sys::imp::thread::{{impl}}::new::thread_start
                          at /checkout/src/libstd/sys/unix/thread.rs:84
  /usr/local/lib/ruby/gems/2.3.0/gems/selenium-webdriver-3.8.0/lib/selenium/webdriver/remote/response.rb:69:in `assert_ok'
  /usr/local/lib/ruby/gems/2.3.0/gems/selenium-webdriver-3.8.0/lib/selenium/webdriver/remote/response.rb:32:in `initialize'
  /usr/local/lib/ruby/gems/2.3.0/gems/selenium-webdriver-3.8.0/lib/selenium/webdriver/remote/http/common.rb:81:in `new'
  /usr/local/lib/ruby/gems/2.3.0/gems/selenium-webdriver-3.8.0/lib/selenium/webdriver/remote/http/common.rb:81:in `create_response'
  /usr/local/lib/ruby/gems/2.3.0/gems/selenium-webdriver-3.8.0/lib/selenium/webdriver/remote/http/default.rb:104:in `request'
  /usr/local/lib/ruby/gems/2.3.0/gems/selenium-webdriver-3.8.0/lib/selenium/webdriver/remote/http/common.rb:59:in `call'
  /usr/local/lib/ruby/gems/2.3.0/gems/selenium-webdriver-3.8.0/lib/selenium/webdriver/remote/bridge.rb:164:in `execute'
  /usr/local/lib/ruby/gems/2.3.0/gems/selenium-webdriver-3.8.0/lib/selenium/webdriver/remote/w3c/bridge.rb:535:in `execute'
  /usr/local/lib/ruby/gems/2.3.0/gems/selenium-webdriver-3.8.0/lib/selenium/webdriver/remote/w3c/bridge.rb:441:in `element_tag_name'
  /usr/local/lib/ruby/gems/2.3.0/gems/selenium-webdriver-3.8.0/lib/selenium/webdriver/common/element.rb:86:in `tag_name'
  /usr/local/lib/ruby/gems/2.3.0/gems/watir-6.10.0/lib/watir/locators/element/validator.rb:7:in `validate'
  /usr/local/lib/ruby/gems/2.3.0/gems/watir-6.10.0/lib/watir/locators/element/locator.rb:164:in `block in filter_elements_by_locator'
  /usr/local/lib/ruby/gems/2.3.0/gems/watir-6.10.0/lib/watir/locators/element/locator.rb:164:in `select!'
  /usr/local/lib/ruby/gems/2.3.0/gems/watir-6.10.0/lib/watir/locators/element/locator.rb:164:in `filter_elements_by_locator'
  /usr/local/lib/ruby/gems/2.3.0/gems/watir-6.10.0/lib/watir/locators/element/locator.rb:61:in `block in using_selenium'
  /usr/local/lib/ruby/gems/2.3.0/gems/watir-6.10.0/lib/watir/locators/element/locator.rb:56:in `each'
  /usr/local/lib/ruby/gems/2.3.0/gems/watir-6.10.0/lib/watir/locators/element/locator.rb:56:in `using_selenium'
  /usr/local/lib/ruby/gems/2.3.0/gems/watir-6.10.0/lib/watir/locators/element/locator.rb:46:in `locate_all'
  /usr/local/lib/ruby/gems/2.3.0/gems/watir-6.10.0/lib/watir/element_collection.rb:130:in `elements'
  /usr/local/lib/ruby/gems/2.3.0/gems/watir-6.10.0/lib/watir/element_collection.rb:70:in `to_a'
  /usr/local/lib/ruby/gems/2.3.0/gems/watir-6.10.0/lib/watir/element_collection.rb:29:in `each'
  /usr/local/lib/ruby/gems/2.3.0/gems/watir-6.10.0/lib/watir/elements/element.rb:660:in `count'
  /usr/local/lib/ruby/gems/2.3.0/gems/watir-6.10.0/lib/watir/elements/element.rb:660:in `rescue in element_call'
  /usr/local/lib/ruby/gems/2.3.0/gems/watir-6.10.0/lib/watir/elements/element.rb:679:in `element_call'
  /usr/local/lib/ruby/gems/2.3.0/gems/watir-6.10.0/lib/watir/elements/element.rb:403:in `visible?'
  /usr/local/lib/ruby/gems/2.3.0/gems/watir-6.10.0/lib/watir/elements/element.rb:426:in `present?'
  /usr/local/lib/ruby/gems/2.3.0/gems/watir-6.10.0/lib/watir/wait.rb:46:in `block in until'
  /usr/local/lib/ruby/gems/2.3.0/gems/watir-6.10.0/lib/watir/wait.rb:89:in `block in run_with_timer'
  /usr/local/lib/ruby/gems/2.3.0/gems/watir-6.10.0/lib/watir/wait/timer.rb:20:in `block in wait'
  /usr/local/lib/ruby/gems/2.3.0/gems/watir-6.10.0/lib/watir/wait/timer.rb:19:in `loop'
  /usr/local/lib/ruby/gems/2.3.0/gems/watir-6.10.0/lib/watir/wait/timer.rb:19:in `wait'
  /usr/local/lib/ruby/gems/2.3.0/gems/watir-6.10.0/lib/watir/wait.rb:88:in `run_with_timer'
  /usr/local/lib/ruby/gems/2.3.0/gems/watir-6.10.0/lib/watir/wait.rb:45:in `until'
  /usr/local/lib/ruby/gems/2.3.0/gems/watir-6.10.0/lib/watir/wait.rb:125:in `wait_until'
  /usr/local/lib/ruby/gems/2.3.0/gems/watir-6.10.0/lib/watir/wait.rb:173:in `wait_until_present'

```

**Comment by andreastt** [comment]
Unable to reproduce.

Could you please attach a [trace-level log] from geckodriver? Read more about reporting actionable bugs in our [contribution guidelines].

[trace-level log]: https://searchfox.org/mozilla-central/source/testing/geckodriver/doc/TraceLogs.md
[contribution guidelines]: https://searchfox.org/mozilla-central/source/testing/geckodriver/CONTRIBUTING.md#reporting-bugs
