### ISSUE TITLE
geckodriver hangs on running with Xvfb

### ISSUE THREAD

**Issue by jiteshk23** [mozilla/geckodriver#1101]
## System
* Version: 0.19.1
* Platform: Linux
* Firefox: 52.5.1
* Selenium: python bindings v3.8.0

## Testcase
- I am trying to run the below script (using Xvfb for headless mode).
```
#! /bin/env bash
Xvfb :99 -screen 0 1024x768x24 +extension RANDR -nolisten inet6 &
export DISPLAY=:99
python scrapping.py
```
- Running fine on my local machine (same system configuration as mentioned above, only firefox 57 instead of 52.5.1)
- Gives error on a remote machine (system configuration mentioned above) on which I am running the script after doing ssh. 

## Stacktrace
The script hangs when I run it.

I get below stacktrace if I press CTRL+C
```
Traceback (most recent call last):
  File "scrapping.py", line 162, in <module>
    with FirefoxDriver(profile, capabilities) as driver:
  File "/apps/nor/env-trader6-norgrp/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "scrapping.py", line 20, in FirefoxDriver
    driver = webdriver.Firefox(firefox_profile=profile, capabilities=capabilities)
  File "/apps/nor/env-trader6-norgrp/lib/python2.7/site-packages/selenium/webdriver/firefox/webdriver.py", line 158, in __init__
    keep_alive=True)
  File "/apps/nor/env-trader6-norgrp/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 154, in __init__
    self.start_session(desired_capabilities, browser_profile)
  File "/apps/nor/env-trader6-norgrp/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 243, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/apps/nor/env-trader6-norgrp/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 309, in execute
    response = self.command_executor.execute(driver_command, params)
  File "/apps/nor/env-trader6-norgrp/lib/python2.7/site-packages/selenium/webdriver/remote/remote_connection.py", line 460, in execute
    return self._request(command_info[0], url, body=data)
  File "/apps/nor/env-trader6-norgrp/lib/python2.7/site-packages/selenium/webdriver/remote/remote_connection.py", line 484, in _request
    resp = self._conn.getresponse()
  File "/apps/nor/env-trader6-norgrp/lib/python2.7/httplib.py", line 1045, in getresponse
    response.begin()
  File "/apps/nor/env-trader6-norgrp/lib/python2.7/httplib.py", line 409, in begin
    version, status, reason = self._read_status()
  File "/apps/nor/env-trader6-norgrp/lib/python2.7/httplib.py", line 365, in _read_status
    line = self.fp.readline(_MAXLINE + 1)
  File "/apps/nor/env-trader6-norgrp/lib/python2.7/socket.py", line 476, in readline
    data = self._sock.recv(self._rbufsize)
KeyboardInterrupt
```

If I wait long enough, it sort of times out and gives connnection refused message.
```
Traceback (most recent call last):
  File "scrapping.py", line 162, in <module>
    with FirefoxDriver(profile, capabilities) as driver:
  File "/apps/nor/env-trader6-norgrp/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "scrapping.py", line 20, in FirefoxDriver
    driver = webdriver.Firefox(firefox_profile=profile, capabilities=capabilities)
  File "/apps/nor/env-trader6-norgrp/lib/python2.7/site-packages/selenium/webdriver/firefox/webdriver.py", line 158, in __init__
    keep_alive=True)
  File "/apps/nor/env-trader6-norgrp/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 154, in __init__
    self.start_session(desired_capabilities, browser_profile)
  File "/apps/nor/env-trader6-norgrp/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 243, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/apps/nor/env-trader6-norgrp/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 311, in execute
    self.error_handler.check_response(response)
  File "/apps/nor/env-trader6-norgrp/lib/python2.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 237, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: connection refused
```

## Trace-level log
[output.log](https://github.com/mozilla/geckodriver/files/1555300/output.log)

The log says 
```
...
Xlib:  extension "RANDR" missing on display ":99".
...
```

Google searches suggested adding the +extension option to the Xvfb command, but it didn't help.

Also, checked the availability of the package on the system.
```
$ xdpyinfo | grep "number of extensions"  -A 25

number of extensions:    28
    BIG-REQUESTS
    Composite
    DAMAGE
    DOUBLE-BUFFER
    DPMS
    DRI2
    GLX
    Generic Event Extension
    MIT-SCREEN-SAVER
    MIT-SHM
    Present
    **** RANDR ****
    RECORD
    RENDER
    SECURITY
    SGI-GLX
    SHAPE
    SYNC
    X-Resource
    XC-MISC
    XFIXES
    XFree86-DGA
    XFree86-VidModeExtension
    XINERAMA
    XInputExtension

```

**Comment by andreastt** [comment]
Firefox 52 isn’t supported by geckodriver. Overall this sounds like a configuration problem of the remote machine. You didn’t attach a trace-level log, but also I couldn’t spot anything fishy in it.
