### ISSUE TITLE
Unable to click on Radio button - Headless mode

### ISSUE THREAD

**Issue by shreyanshp** [mozilla/geckodriver#1144]
## System
* Version: 0.19.1
* Platform:  Linux 16.04 Server and Linux 17.04 Desktop
* Firefox: 57.0.4
* Selenium: 3.0.7

## Testcase

https://www.w3schools.com/html/tryit.asp?filename=tryhtml_radio
Tried Clicking on radio button, but could not

![radio](https://user-images.githubusercontent.com/21307950/35394102-cdf0270e-020c-11e8-8b4a-d2a2ddd7a21c.png)

I use cucumber and selenium, so you can use basic code for Clicking using attribute "value" as "male" or "female" or "other"

## Stacktrace

Running Feature child (scenario)...
Begin scenario run...
Scenario completed...0
Running Feature child (scenario)...
Begin scenario run...
Used Environment - FF
Case - FF
1516891513355	geckodriver	INFO	geckodriver 0.19.1
1516891513359	geckodriver	INFO	Listening on 127.0.0.1:24472
1516891513595	mozrunner::runner	INFO	Running command: "/opt/Firefox-57/firefox/firefox-bin" "-marionette" "-headless" "-profile" "/tmp/rust_mozprofile.yPClTfH8Jdzc"
*** You are running in headless mode.
1516891513902	Marionette	INFO	Enabled via --marionette
1516891514726	Marionette	INFO	Listening on port 35589
1516891514803	Marionette	WARN	TLS certificate errors will be ignored for this session
1516891514850	Marionette	DEBUG	Register listener.js for window 2147483649
Jan 25, 2018 8:15:14 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: W3C
1516891516958	Marionette	DEBUG	Received DOM event "beforeunload" for "about:blank"
1516891517184	Marionette	DEBUG	Received DOM event "pagehide" for "about:blank"
1516891517185	Marionette	DEBUG	Received DOM event "unload" for "about:blank"
1516891517725	Marionette	DEBUG	Received DOM event "DOMContentLoaded" for "https://www.w3schools.com/html/tryit.asp?filename=tryhtml_radio"
1516891518978	Marionette	DEBUG	Received DOM event "pageshow" for "https://www.w3schools.com/html/tryit.asp?filename=tryhtml_radio"
https://www.w3schools.com/html/tryit.asp?filename=tryhtml_radio
[Child 32678, Chrome_ChildThread] WARNING: pipe error (3): Connection reset by peer: file /builds/worker/workspace/build/src/ipc/chromium/src/chrome/common/ipc_channel_posix.cc, line 353
Initiating retry...
Current class is: com.github.mkolisnyk.cucumber.runner.ExtendedExecutionUnitRunner
Scenario completed...1

Failed scenarios:
gecko.feature:6 # Scenario: User is able to clone iteration and delete iteration

2 Scenarios (1 failed, 1 passed)
4 Steps (1 failed, 3 passed)
0m28.913s

org.openqa.selenium.TimeoutException: Expected condition failed: waiting for com.TrialRun.StepDefinitions.StepDefinitionBase$2@16afbd92 (tried for 20 second(s) with 1 SECONDS interval)
	at org.openqa.selenium.support.ui.FluentWait.timeoutException(FluentWait.java:263)
	at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:231)
	at com.TrialRun.StepDefinitions.StepDefinitionBase.fluentWait(StepDefinitionBase.java:1148)
	at com.TrialRun.StepDefinitions.StepDefinitionBase.clicks_on_having_as(StepDefinitionBase.java:272)
	at ✽.And Clicks on "male", having "value" as "male"(gecko.feature:10)
Caused by: org.openqa.selenium.NoSuchElementException: Unable to locate element: //*[@value = 'male']
For documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.html
Build info: version: '3.7.1', revision: '8a0099a', time: '2017-11-06T21:01:39.354Z'
System info: host: 'shreyansh-asus', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '4.8.0-59-generic', java.version: '1.8.0_131'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities {acceptInsecureCerts: true, browserName: firefox, browserVersion: 57.0.4, javascriptEnabled: true, moz:accessibilityChecks: false, moz:headless: true, moz:processID: 32635, moz:profile: /tmp/rust_mozprofile.yPClTf..., moz:webdriverClick: false, pageLoadStrategy: normal, platform: LINUX, platformName: LINUX, platformVersion: 4.8.0-59-generic, rotatable: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}}
Session ID: defc6dd3-7505-4be2-a071-551bbddfb90d
*** Element info: {Using=xpath, value=//*[@value = 'male']}
	at sun.reflect.GeneratedConstructorAccessor13.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:187)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:122)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:49)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:164)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:600)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:370)
	at org.openqa.selenium.remote.RemoteWebDriver.findElementByXPath(RemoteWebDriver.java:472)
	at org.openqa.selenium.By$ByXPath.findElement(By.java:361)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:362)
	at com.TrialRun.StepDefinitions.StepDefinitionBase$2.apply(StepDefinitionBase.java:1150)
	at com.TrialRun.StepDefinitions.StepDefinitionBase$2.apply(StepDefinitionBase.java:1)
	at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:208)
	at com.TrialRun.StepDefinitions.StepDefinitionBase.fluentWait(StepDefinitionBase.java:1148)
	at com.TrialRun.StepDefinitions.StepDefinitionBase.clicks_on_having_as(StepDefinitionBase.java:272)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at cucumber.runtime.Utils$1.call(Utils.java:40)
	at cucumber.runtime.Timeout.timeout(Timeout.java:16)
	at cucumber.runtime.Utils.invoke(Utils.java:34)
	at cucumber.runtime.java.JavaStepDefinition.execute(JavaStepDefinition.java:38)
	at cucumber.runtime.StepDefinitionMatch.runStep(StepDefinitionMatch.java:37)
	at cucumber.runtime.ExtendedRuntime.runStep(ExtendedRuntime.java:319)
	at cucumber.runtime.model.StepContainer.runStep(StepContainer.java:44)
	at cucumber.runtime.model.StepContainer.runSteps(StepContainer.java:39)
	at cucumber.runtime.model.CucumberScenario.run(CucumberScenario.java:44)
	at com.github.mkolisnyk.cucumber.runner.ExtendedExecutionUnitRunner.run(ExtendedExecutionUnitRunner.java:32)
	at com.github.mkolisnyk.cucumber.runner.ExtendedFeatureRunner.runChild(ExtendedFeatureRunner.java:99)
	at com.github.mkolisnyk.cucumber.runner.ExtendedFeatureRunner.runChild(ExtendedFeatureRunner.java:24)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at cucumber.runtime.junit.FeatureRunner.run(FeatureRunner.java:70)
	at com.github.mkolisnyk.cucumber.runner.ExtendedCucumber.runChild(ExtendedCucumber.java:108)
	at com.github.mkolisnyk.cucumber.runner.ExtendedCucumber.runChild(ExtendedCucumber.java:32)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at com.github.mkolisnyk.cucumber.runner.ExtendedCucumber.run(ExtendedCucumber.java:148)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)

-->

####

If you need more information let me know

I am sensing this may be Firefox issue, but let me know if this is not geckodriver issue as I can click on non headless mode

**Comment by whimboo** [comment]
Sadly the above log is not a trace log as requested, so I cannot say much about what could have gone wrong. But I assume that you missed to switch into the `iFrame` before trying to retrieve the element. As such the `NoSuchElementError` is getting thrown because it's not part of the top-level browsing context, but the embedded frame.

**Comment by shreyanshp** [comment]
@whimboo ohh, apologies as this is my first time raising an issue here, the above url/html (https://www.w3schools.com/html/tryit.asp?filename=tryhtml_radio ) was an example I used to share the issue as the issue is generic for all radio inputs/buttons

To clarify again, I can click the radio button in normal mode using geckodriver-selenium on Firefox 57.0.4, but I am unable to click the same element with the same code in headless mode, screenshot is from headless mode where you can see that the radio button looks distorted

Let me know if you need anything more or how to get it

**Comment by AutomatedTester** [comment]
This is covered by tests in our infrastructure and there is none of the requested info so closing
