### ISSUE TITLE
Gecko webdriver throws InvalidArgumentException (is not an array) when noProxy setting specified

### ISSUE THREAD

**Issue by shankarkc** [mozilla/geckodriver#1164]
## System
* Version: 
0.19.1
* Platform: 
Linux and Windows(Hvent tested on MAC)
* Firefox: 
57.0.4
* Selenium: 
3.8.1

## Testcase
Refer attached zip. Update the java file with grid URL, http_proxy,https_proxy and no_proxy details
(..\testNGSelenium\src\test\java\com\javacodegeeks\testng\selenium\TestNGSeleniumSimpleSearchExample.java)
[testNGSelenium.zip](https://github.com/mozilla/geckodriver/files/1701806/testNGSelenium.zip)
It has 2 tests. One shows its passing on chrome browser and another shows it fails on firefox

## Stacktrace

Refer the log here in zip file
[emailable-report.zip](https://github.com/mozilla/geckodriver/files/1701798/emailable-report.zip)
```
Caused by: org.openqa.selenium.InvalidArgumentException: &quot;localhost,  127.0.0.1, 10.0.2.15, *.lab1.MyCompany.com&quot; is not an array
Build info: version: &apos;3.8.1&apos;, revision: &apos;6e95a6684b&apos;, time: &apos;2017-12-01T19:05:32.194Z&apos;
System info: host: &apos;573c6d3fa472&apos;, ip: &apos;10.0.9.36&apos;, os.name: &apos;Linux&apos;, os.arch: &apos;amd64&apos;, os.version: &apos;4.2.0-27-generic&apos;, java.version: &apos;1.8.0_151&apos;
Driver info: driver.version: unknown
remote stacktrace: stack backtrace:
   0:           0x4edb3c - backtrace::backtrace::trace::hc4bd56a2f176de7e
   1:           0x4edb72 - backtrace::capture::Backtrace::new::he3b2a15d39027c46
   2:           0x4e9586 - webdriver::error::WebDriverError::new::hee9ff9dd0a444441
   3:           0x4dd8b6 - webdriver::capabilities::SpecNewSessionParameters::validate_proxy::h3387fbc10633c5eb
   4:           0x436c1a - &lt;&amp;&apos;a mut I as core::iter::iterator::Iterator&gt;::next::hbb01b33ace84bf9d
   5:           0x4414c5 - geckodriver::marionette::MarionetteHandler::create_connection::hf0532ddb9e159684
   6:           0x428570 - &lt;webdriver::server::Dispatcher&lt;T, U&gt;&gt;::run::h2119c674d7b88193
   7:           0x4029b9 - std::sys_common::backtrace::__rust_begin_short_backtrace::h21d98a9ff86d4c25
   8:           0x40be65 - std::panicking::try::do_call::h5cff0c9b18cfdbba
   9:           0x5e6a6c - panic_unwind::__rust_maybe_catch_panic
                        at /checkout/src/libpanic_unwind/lib.rs:99
  10:           0x41eb22 - &lt;F as alloc::boxed::FnBox&lt;A&gt;&gt;::call_box::h413eb1d9d9f1c473
  11:           0x5df13b - alloc::boxed::{{impl}}::call_once&lt;(),()&gt;
                        at /checkout/src/liballoc/boxed.rs:692
                         - std::sys_common::thread::start_thread
                        at /checkout/src/libstd/sys_common/thread.rs:21
                         - std::sys::imp::thread::{{impl}}::new::thread_start
                        at /checkout/src/libstd/sys/unix/thread.rs:84
Build info: version: &apos;3.8.1&apos;, revision: &apos;6e95a6684b&apos;, time: &apos;2017-12-01T18:33:54.468Z&apos;
System info: host: &apos;INLN50949132A&apos;, ip: &apos;10.138.169.153&apos;, os.name: &apos;Windows 10&apos;, os.arch: &apos;amd64&apos;, os.version: &apos;10.0&apos;, java.version: &apos;1.8.0_112&apos;
Driver info: driver.version: unknown
	at org.openqa.selenium.remote.W3CHandshakeResponse.lambda$new$0(W3CHandshakeResponse.java:57)
	at org.openqa.selenium.remote.W3CHandshakeResponse.lambda$getResponseFunction$2(W3CHandshakeResponse.java:104)
	at org.openqa.selenium.remote.ProtocolHandshake.lambda$createSession$0(ProtocolHandshake.java:123)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:958)
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:464)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:126)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:73)
	at org.openqa.selenium.remote.server.ServicedSession$Factory.apply(ServicedSession.java:232)
	at org.openqa.selenium.remote.server.ActiveSessionFactory.lambda$apply$11(ActiveSessionFactory.java:167)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.stream.ReferencePipeline$11$1.accept(ReferencePipeline.java:373)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:958)
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:464)
	at org.openqa.selenium.remote.server.ActiveSessionFactory.apply(ActiveSessionFactory.java:170)
	at org.openqa.selenium.remote.server.NewSessionPipeline.lambda$null$1(NewSessionPipeline.java:44)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Collections$2.tryAdvance(Collections.java:4717)
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:464)
	at org.openqa.selenium.remote.server.NewSessionPipeline.lambda$createNewSession$2(NewSessionPipeline.java:47)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.stream.DistinctOps$1$2.accept(DistinctOps.java:175)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.stream.Streams$StreamBuilderImpl.tryAdvance(Streams.java:405)
	at java.util.stream.Streams$ConcatSpliterator.tryAdvance(Streams.java:728)
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:464)
	at org.openqa.selenium.remote.server.NewSessionPipeline.createNewSession(NewSessionPipeline.java:50)
	at org.openqa.selenium.remote.server.commandhandler.BeginSession.execute(BeginSession.java:77)
	at org.openqa.selenium.remote.server.WebDriverServlet.lambda$handle$0(WebDriverServlet.java:240)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
... Removed 42 stack frames
```

## Trace-level log

Info

**Comment by andreastt** [comment]
Would it be possible for you to show the raw capabilities object you are passing to geckodriver?

Could you also please attach a [trace-level log] from geckodriver? Read more about reporting actionable bugs in our [contribution guidelines].

[trace-level log]: https://searchfox.org/mozilla-central/source/testing/geckodriver/doc/TraceLogs.md
[contribution guidelines]: https://searchfox.org/mozilla-central/source/testing/geckodriver/CONTRIBUTING.md#reporting-bugs

**Comment by shankarkc** [comment]
Here is the code for the proxy object.
```
prox = new Proxy();
prox.setProxyType(ProxyType.MANUAL);
prox.setHttpProxy(testParameter.getHttp_proxy());
prox.setSslProxy(testParameter.getHttps_proxy());
prox.setNoProxy(testParameter.getHttp_noproxy());
```
I will post the trace log tomorrow. I have attached maven project  zip file that you can refer... Using that you can reproduce the issue. Basically no_proxy is comma separated string.

**Comment by shankarkc** [comment]
Example values
```
    <parameter name="http_proxy" value="proxy.mycompany.corp:8080" />
    <parameter name="https_proxy" value="proxy.mycompany.corp:8080" />
    <parameter name="http_noproxy" value="localhost, *.mycompany.corp, *.mycompany.com, *.mycompany.biz,, 127.0.0.1, 10.0.2.15, *.lab1.mycompany.com" />

```

**Comment by whimboo** [comment]
NO_PROXY needs to be a list of strings, and not a string.

Also see https://github.com/SeleniumHQ/selenium/issues/5004.

**Comment by shankarkc** [comment]
@whimboo... But proxy object does not take string array as its input. It just takes a string. In that case how can one pass multiple strings? Here is the class definition
https://seleniumhq.github.io/selenium/docs/api/java/org/openqa/selenium/Proxy.html

**Comment by shankarkc** [comment]
Here is the source code of set method
```
public Proxy setNoProxy(String noProxy) {
    verifyProxyTypeCompatibility(ProxyType.MANUAL);
    this.proxyType = ProxyType.MANUAL;
    this.noProxy = noProxy;
    return this;
  }
```
How can I pass list of strings to this method? How csv values work fine on chrome browser and fail on Firefox?

**Comment by whimboo** [comment]
Please see the link in my last comment. This is a Selenium issue.
