### ISSUE TITLE
Cannot launch with existing profile: Unable to read profile preferences file

### ISSUE THREAD

**Issue by brnbs** [mozilla/geckodriver#1169]
## System
* Version: 0.19.1 (also tried with 0.18)
* Platform: Windows 10 64-bit
* Firefox: 59.0a1 
* Selenium: C# with NuGet package 3.9.0

## Testcase

When trying to start a new instance of Firefox with an existing profile the geckodriver gives an error and the Firefox browser not started at all. The exact same profile is working good when loaded manually to firefox using the `firefox.exe -profile "/path/to/profile"` command. If I dont specify any profile directory to the FirefoxProfile constructor, the browser is starting normally with a fresh profile.

Code used to launch browser:
```
var options = new FirefoxOptions
{
    Proxy = new Proxy
    {
        IsAutoDetect = false,
        Kind = ProxyKind.Manual,
        HttpProxy = $"...",
        SslProxy = $"..."
    },
    LogLevel = FirefoxDriverLogLevel.Trace, // Debugging
    Profile = new FirefoxProfile("/path/to/profile/folder", false) // Also tried with deleteSourceOnClean=true parameter
};

options.SetPreference("app.update.service.enabled", false);
options.SetPreference("browser.search.countryCode", "en");
options.SetPreference("browser.search.region", "en");

_driver = FirefoxDriverService.CreateDefaultService("path/to/geckodriver");
_driver.HideCommandPromptWindow = false;
_driver.FirefoxBinaryPath = "/path/to/firefox.exe";

WebDriver = new EventFiringWebDriver(new FirefoxDriver(_driver, options, TimeSpan.FromSeconds(30)));
WebDriver.Navigating += BrowserNavigatedEvent;

WebDriver.Navigate().GoToUrl(DefaultStartpageUrl);
```

## Stacktrace

```
at OpenQA.Selenium.Remote.RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse)
at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
at OpenQA.Selenium.Remote.RemoteWebDriver.StartSession(ICapabilities desiredCapabilities)
at OpenQA.Selenium.Remote.RemoteWebDriver..ctor(ICommandExecutor commandExecutor, ICapabilities desiredCapabilities)
at OpenQA.Selenium.Firefox.FirefoxDriver..ctor(FirefoxDriverService service, FirefoxOptions options, TimeSpan commandTimeout)
...
```

## Trace-level log

```
1518170889403   geckodriver     INFO    geckodriver 0.19.1 (0000000000000000000000000000000000000000 2017-10-31)
1518170889408   geckodriver     INFO    Listening on 127.0.0.1:51203
1518170891453   webdriver::server       DEBUG   <- 500 Internal Server Error {"value":{"error":"session not created","message":"Failed to set preferences: Unable to read profile preferences file","stacktrace":"stack backtrace:\n   0:   0x46c297 - <no info>\n   1:   0x43e857 - <no info>\n   2:   0x4225f2 - <no info>\n   3:   0x406389 - <no info>\n   4:   0x40cc97 - <no info>\n   5:   0x657a89 - <no info>\n   6:   0x4185b6 - <no info>\n   7:   0x6535a1 - <no info>\n   8: 0x76038654 - BaseThreadInitThunk\n   9: 0x77de4a77 - RtlGetAppContainerNamedObjectPath"}}
```

**Comment by whimboo** [comment]
I don't know what C# is doing behind the scenes here, but you have to use the `args` under FirefoxOptions to specify an existing profile folder. See https://github.com/mozilla/geckodriver/#mozfirefoxoptions.

Also your log is not a trace log, because it misses the command line as used by geckodriver to start Firefox.

**Comment by brnbs** [comment]
Thanks for the reply. I tried to use the args to specify a profile to Firefox, but when I use that way the C# binding cannot modify the profile, so it cannot set any preference, cannot set the correct marionette port for communication and the connection between the driver and the browser gets a timeout. I believe the C# binding always creates a copy of the given profile directory into the user's temp directory and pass that folder to Firefox. The only workaround I have found is to delete the user.js file from the profile I want to load and pass the profile directory to the C# binding.

Im not sure what else should I do to get a trace log? I know that the command line used to launch the Firefox is missing, because Firefox is not started at all. This is the full output I got from the driver.

**Comment by whimboo** [comment]
Yes, note issue #1058 for custom profiles and geckodriver. I can't say anything for the C# binding, sorry.

If the command line or any geckodriver output is not shown I would suspect that the binding aborts or doesn't even send anything to geckodriver.

**Comment by AutomatedTester** [comment]
@brnbs what happens if you set the preferences using the `Profile` object instead of using `Options`. I suspect that using a mix of `Profile` and `Option` would result in undefined behavior because it is more designed for either or usage

**Comment by revathi-sadanand** [comment]
Hello everyone.
I am using selenium standalone server 3.11.0 , firefox nightly 60 and gecko driver 0.20. when i try to start geckdriver with the customized profile it starts FF browse and points to the blank page.
I tried creating profile as default

**Comment by andreastt** [comment]
@revathi-sadanand Please don’t hijack existing issues. File a new one instead.

**Comment by andreastt** [comment]
Closing for inactivity. No response from original filer.

**Comment by javierlopez111** [comment]
The link above is way old.  Very misleading.

**Comment by whimboo** [comment]
Which link? It's all up-to-date. So not sure what you are referring to.

**Comment by javierlopez111** [comment]
My bad.  I thought I was updating another page.

**Comment by javierlopez111** [comment]
However, I have tried to use an existing profile with the following,
Selenium standalone 3.10
geckodriver 20
Windows 10
FF 58

Selenium-java code is as follows,

 String profileDir = "C:/Users/jlopez/AppData/Roaming/Mozilla/Firefox/Profiles/ddtkw80l.profile5902";
 FirefoxProfile ffprofile = new FirefoxProfile();

FirefoxOptions options = new FirefoxOptions();
options.setBinary("C:\\Program Files\\Mozilla Firefox\\firefox.exe");
options.addArguments("-profile", profileDir);

System.setProperty("webdriver.gecko.driver","C:\\selenium\\drivers\\geckodriver.exe");

capabilities = DesiredCapabilities.firefox();
 capabilities.setCapability("moz:firefoxOptions", options);

driver = new RemoteWebDriver(new URL("http://" + hubHost + ":4567/wd/hub"), capabilities);

What am I doing wrong??

**Comment by whimboo** [comment]
@javierlopez111 can you please move your problem to a new issue? Thanks.
