### ISSUE TITLE
Firefox - Selenium - Cannot find firefox binary in PATH. 

### ISSUE THREAD

**Issue by stephanierl88** [mozilla/geckodriver#1190]
* Version: geckodriver-v0.19.1-win64
* Platform: Windows 10
* Firefox: 58.0.2 (32-bit)
* Selenium: selenium-java-3.9.1

**I am receiving an error message when trying to execute the following code:**
package test_suite_1;

import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;

public class test_case_2 {

	public static void main(String[] args) {
		// TODO Auto-generated method stub
		System.setProperty("webdriver.firefox.marionette", "C:\\Working Directory\\geckodriver.exe");
		WebDriver driver=new FirefoxDriver();
		driver.get("http://google.com");
		System.out.println(driver.getTitle()); 
	}

}

**Error Message Received:**
Exception in thread "main" org.openqa.selenium.WebDriverException: Cannot find firefox binary in PATH. Make sure firefox is installed. OS appears to be: WIN10
Build info: version: '3.9.1', revision: '63f7b50', time: '2018-02-07T22:42:22.379Z'
System info: host: 'DESKTOP-58HI2JA', ip: '10.0.0.41', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '9.0.4'
Driver info: driver.version: FirefoxDriver
	at org.openqa.selenium.firefox.FirefoxBinary.<init>(FirefoxBinary.java:116)
	at java.base/java.util.Optional.orElseGet(Unknown Source)
	at org.openqa.selenium.firefox.FirefoxOptions.getBinary(FirefoxOptions.java:218)
	at org.openqa.selenium.firefox.FirefoxDriver.toExecutor(FirefoxDriver.java:151)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:120)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:98)
	at test_suite_1.test_case_2.main(test_case_2.java:11)

**Comment by AutomatedTester** [comment]
Is your Firefox in the default locations? Have you tried adding Firefox path to your `PATH` environment variable?

**Comment by andreastt** [comment]
What is firefox-sdk? That doesn’t sound like a stock Firefox installation.

**Comment by stephanierl88** [comment]
The issue has been fixed, I uninstalled and reinstalled Firefox and it now works.

**Comment by iishita** [comment]
Hi, my eclipse is also throwing the same error message, how can i fix it.
I'm using:
windows 7
selenium 2.53.1
firefox 45.0.1

![issueinselenium](https://user-images.githubusercontent.com/37995171/38185112-30acb362-366a-11e8-9844-ee24df764147.png)

**Comment by andreastt** [comment]
You need to put Firefox on your system path, or provide geckodriver with a `--binary` argument.
