### ISSUE TITLE
Wrong event order for Ctrl-Right-Click

### ISSUE THREAD

**Issue by codingphil** [mozilla/geckodriver#1201]
## System

* Version: 0.19.1
* Platform: Windows 10.0.16299.248
* Firefox: 58.0.2 (64-bit) (also tested with Nightly 60.0a1 (2018-03-05) (64-bit))
* Selenium: 3.10.0

## Testcase
The following JUnit 4 test fails because the event order of the mouse events triggered by a Ctrl-Right-Click is "wrong".
The event order for Chrome, Edge is *mousemove, mousedown, mouseup, contextmenu*.
Also when Ctrl-Right-Click manually (without selenium) the events have this order.
With Selenium/Geckodriver the event order is not as expected:
*mousemove, mousedown, contextmenu, mouseup*

```java
  @Test
  public void testCtrlRightClick() {
    String url = "http://www.not-w3c-test.org/webdriver/tests/actions/support/test_actions_wdspec.html";
    driver.navigate().to(url);
    WebElement clickTarget = driver.findElementById("outer");
    
    new Actions(driver).moveToElement(clickTarget).keyDown(Keys.CONTROL).contextClick().keyUp(Keys.CONTROL).perform();

    List<String> events = (List<String>) driver.executeScript("return allEvents.events.map(function(e) { return e.type; })");
    assertNotNull(events);
    assertTrue(events.size() == 4);
    
    assertEquals("mousemove", events.get(0));
    assertEquals("mousedown", events.get(1));
    assertEquals("mouseup", events.get(2)); // FAILS in Firefox (succeeds in Chrome and Edge)
    assertEquals("contextmenu", events.get(3));
  }
```

The used HTML page attached:
[test_actions_wdspec.html.zip](https://github.com/mozilla/geckodriver/files/1784871/test_actions_wdspec.html.zip)

## Stacktrace

```java
org.junit.ComparisonFailure: expected:<[mouseup]> but was:<[contextmenu]>
	at org.junit.Assert.assertEquals(Assert.java:115)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at CtrlRightClickTests.testCtrlRightClick(CtrlRightClickTests.java:54)
```

## Trace-level log
[geckodriver.log](https://github.com/mozilla/geckodriver/files/1784875/geckodriver.log)

**Comment by andreastt** [comment]
Thanks for the bug report! I’ve filed https://bugzilla.mozilla.org/show_bug.cgi?id=1443482.

**Comment by Herst** [comment]
AFAIK, the order is OS specific, so there is not wrong by itself, just not representing the OS in question.

**Comment by codingphil** [comment]
In my opinion the events triggered during a webdriver test should be as similar to the way it works without selenium as possible.
As I mentioned in the original issue description, if you right click manually without selenium the event order is different.
