### ISSUE TITLE
Failed to decode response from marionette in Selenium WebDriver 

### ISSUE THREAD

**Issue by deepidua** [mozilla/geckodriver#1209]
## System

* Version:   gecko Version is 0.19
* Platform:  Windows 
* Firefox:  Firefox 58
* Selenium:  3.9.1

## Stacktrace

I am getting below exception: 

org.openqa.selenium.WebDriverException: Failed to decode response from marionette
Build info: version: '3.9.1', revision: '63f7b50', time: '2018-02-07T22:25:02.294Z'

Full Stack Trace:
```
Driver info: org.openqa.selenium.remote.RemoteWebDriver
Capabilities {acceptInsecureCerts: false, browserName: firefox, browserVersion: 58.0.1, javascriptEnabled: true, moz:accessibilityChecks: false, moz:headless: false, moz:processID: 103, moz:profile: /tmp/rust_mozprofile.Ago8cF..., moz:webdriverClick: true, pageLoadStrategy: normal, platform: LINUX, platformName: LINUX, platformVersion: 3.10.0-327.36.3.el7.x86_64, rotatable: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}}
Session ID: 2620c991-3171-4528-ba04-933a43620451
at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:187)
at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:122)
at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:49)
at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:160)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:601)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:658)
at org.openqa.selenium.remote.RemoteWebDriver.getScreenshotAs(RemoteWebDriver.java:343)
at utils.CommonUtilities.getscreenshot(CommonUtilities.java:867)
at stepDefinition.Test_Steps.user_Create(Test_Steps.java:386)
```
Line At 386 : commonutil.getscreenshot(driver, "mari"); // from this I am taking screenshot. This method is working in previous step but failed in this step.

I am using latest firfox version and latest selenium 3.9.

**Comment by andreastt** [comment]
Could you please attach a [trace-level log] from geckodriver? Read more about reporting actionable bugs in our [contribution guidelines].

[trace-level log]: https://searchfox.org/mozilla-central/source/testing/geckodriver/doc/TraceLogs.md
[contribution guidelines]: https://searchfox.org/mozilla-central/source/testing/geckodriver/CONTRIBUTING.md#reporting-bugs

**Comment by deepidua** [comment]
I have enabled gecko trace log using this code 

	capabilities.setCapability(FirefoxDriver.PROFILE, profile);
		capabilities.setPlatform(Platform.LINUX);
		capabilities.setCapability("marionette", false);
		capabilities.setBrowserName("firefox");
		capabilities.setCapability("auth","xyx"); // auth token required to access SeleniumBox

		
		FirefoxOptions options = new FirefoxOptions();
		options.setLogLevel(FirefoxDriverLogLevel.TRACE);
		capabilities.setCapability("moz:firefoxOptions", options);
		capabilities.setCapability(FirefoxDriver.MARIONETTE, false);

org.openqa.selenium.WebDriverException: Failed to decode response from marionette
Build info: version: '3.9.1', revision: '63f7b50', time: '2018-02-07T22:25:02.294Z'
System info: host: 'xxx', ip: 'xxx', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_162'
Driver info: org.openqa.selenium.remote.RemoteWebDriver
Capabilities {acceptInsecureCerts: true, browserName: firefox, browserVersion: 58.0.1, javascriptEnabled: true, moz:accessibilityChecks: false, moz:headless: false, moz:processID: 103, moz:profile: /tmp/rust_mozprofile.Q7iwOu..., moz:webdriverClick: true, pageLoadStrategy: normal, platform: LINUX, platformName: LINUX, platformVersion: 3.10.0-327.36.3.el7.x86_64, rotatable: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}}
Session ID: d553f55b-11b3-47f4-82ce-023d1bfb7b53
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:187)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:122)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:49)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:160)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:601)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:658)
	at org.openqa.selenium.remote.RemoteWebDriver.getCurrentUrl(RemoteWebDriver.java:335)
	at stepDefinition.Test_Steps.user_Actions(Test_Steps.java:367)
	at ?.And User clicks on All Actions(xxx/TC03-7_CreateRelease.feature:118)

**Comment by deepidua** [comment]
Actually  I am running this on remote machine.
driver = new RemoteWebDriver(new URL("https://seleniumbox.xyzcom/wd/hub"), capabilities);

May be that is why not able to see the gecko trace logs.

Please help in this case.

**Comment by whimboo** [comment]
Check the CWD on the remote machine from where the code gets executed from. There should be a geckodriver.log file. Otherwise Selenium forwards the stdout output somewhere else, which you will have to figure out yourself.

**Comment by andreastt** [comment]
Closing for inactivity. Happy to re-open once reproducible steps or a trace log has been added.

**Comment by salvada** [comment]
I am trying to find a solution for the same problem. Did you someone find a solution? 
I am using firefox 60 selenium 3.9.1 geckodriver 0.20.1 and fluentlenium 3.5.2

**Comment by whimboo** [comment]
Sorry, but "me too" comments are pretty useless for us. If you want to see progress make sure to provide the requested trace level log.

**Comment by salvada** [comment]
08:46:04.472 INFO [RemoteSession$Factory.lambda$performHandshake$0] - Started new session 3047780e-66fb-473f-9caf-3a821032474b (org.openqa.selenium.firefox.GeckoDriverService)
[Parent 6610, Gecko_IOThread] WARNING: pipe error (48): Connection reset by peer: file /builds/worker/workspace/build/src/ipc/chromium/src/chrome/common/ipc_channel_posix.cc, line 353
[Parent 6610, Gecko_IOThread] WARNING: pipe error (49): Connection reset by peer: file /builds/worker/workspace/build/src/ipc/chromium/src/chrome/common/ipc_channel_posix.cc, line 353
[Parent 6610, Gecko_IOThread] WARNING: pipe error: Broken pipe: file /builds/worker/workspace/build/src/ipc/chromium/src/chrome/common/ipc_channel_posix.cc, line 709
###!!! [Parent][MessageChannel] Error: (msgtype=0x15007F,name=PBrowser::Msg_Destroy) Channel error: cannot send/recv
###!!! [Parent][MessageChannel] Error: (msgtype=0x470002,name=PHttpBackgroundChannel::Msg_OnTransportAndData) Channel error: cannot send/recv
###!!! [Parent][MessageChannel] Error: (msgtype=0x470002,name=PHttpBackgroundChannel::Msg_OnTransportAndData) Channel error: cannot send/recv
A content process crashed and MOZ_CRASHREPORTER_SHUTDOWN is set, shutting down


This is the docker log get back from the selenium grid node for firefox. I hope that is enough.

**Comment by whimboo** [comment]
@salvada now that you said docker you might be affected by https://github.com/mozilla/geckodriver/issues/285. Please check.

**Comment by ChetanKolhe** [comment]
Getting the same issue. 
please find the traceback of gecodriver.log

[Parent 29748, Gecko_IOThread] WARNING: pipe error (72): Connection reset by peer: file /build/firefox-4VfQCB/firefox-63.0+build2/ipc/chromium/src/chrome/common/ipc_channel_posix.cc, line 356
1542284518001	mozrunner::runner	INFO	Running command: "/usr/bin/firefox" "-marionette" "--headless" "-foreground" "-no-remote" "-profile" "/tmp/rust_mozprofile.9VBLIWgkIc5w"
*** You are running in headless mode.
1542284520262	Marionette	INFO	Listening on port 36369
1542284520314	Marionette	WARN	TLS certificate errors will be ignored for this session
console.error: BroadcastService: 
  receivedBroadcastMessage: handler for
  remote-settings/monitor_changes
  threw error:
  Message: Error: Polling for changes failed: NetworkError when attempting to fetch resource..
  Stack:
    remoteSettingsFunction/remoteSettings.pollChanges@resource://services-settings/remote-settings.js:721:13

JavaScript error: https://192.168.33.18:8443/upgrade.htm, line 185: TypeError: document.getElementById(...) is null
JavaScript error: https://192.168.33.18:8443/upgrade.htm, line 198: TypeError: document.getElementById(...) is null
JavaScript error: https://192.168.33.18:8443/upgrade.htm, line 198: TypeError: document.getElementById(...) is null
JavaScript error: https://192.168.33.18:8443/upgrade.htm, line 198: TypeError: document.getElementById(...) is null
JavaScript error: https://192.168.33.18:8443/upgrade.htm, line 198: TypeError: document.getElementById(...) is null
JavaScript error: https://192.168.33.18:8443/systemUpgrade.htm, line 1: ReferenceError: handleChange is not defined
JavaScript error: https://192.168.33.18:8443/systemUpgrade.htm, line 1: ReferenceError: handleOk is not defined
1542285772893	mozrunner::runner	INFO	Running command: "/usr/bin/firefox" "-marionette" "--headless" "-foreground" "-no-remote" "-profile" "/tmp/rust_mozprofile.6qKhMtzOxxha"
*** You are running in headless mode.
1542285774823	Marionette	INFO	Listening on port 37111
1542285774902	Marionette	WARN	TLS certificate errors will be ignored for this session
console.error: BroadcastService: 
  receivedBroadcastMessage: handler for
  remote-settings/monitor_changes
  threw error:
  Message: Error: Polling for changes failed: NetworkError when attempting to fetch resource..
  Stack:
    remoteSettingsFunction/remoteSettings.pollChanges@resource://services-settings/remote-settings.js:721:13


(/usr/lib/firefox/firefox:30545): dconf-WARNING **: 12:44:16.631: Unable to open /var/lib/snapd/desktop/dconf/profile/user: Permission denied
1542285863829	Marionette	INFO	Stopped listening on port 37111
[Parent 30434, Gecko_IOThread] WARNING: pipe error (64): Connection reset by peer: file /build/firefox-4VfQCB/firefox-63.0+build2/ipc/chromium/src/chrome/common/ipc_channel_posix.cc, line 356

**Comment by whimboo** [comment]
@ChetanKolhe why do you think that? Nothing in the log shows anything related. Instead it seems like there is a network error, and because of that the server socket from Marionette gets closed.
