### ISSUE TITLE
phpunit-selenium keys() function is not working with geckodriver

### ISSUE THREAD

**Issue by K-Deep** [mozilla/geckodriver#1217]
## System

OS: Win 10 ( 32 Bit )
Selenium Version: 3.8.1, geckodriver-v0.20.0, Java1.8.0_162
Browser: FireFox 59.0
Language Package : phpunit-selenium

Other Versions For That Same Issue Is occurring  : 

1. Selenium 3.4.0 + Firefox 49 + geckodriverv0.13.0,  geckodriverv0.14.0, geckodriverv0.15.0
2. Selenium 3.4.0 + Firefox 52 + geckodriverv0.13.0,  geckodriverv0.14.0, geckodriverv0.15.0
3. Selenium 3.8.1 + Firefox 52 + geckodriverv0.16.0,  geckodriverv0.18.0, geckodriverv0.19.0, geckodriverv0.20.0
4. Selenium 3.8.1 + Firefox 56 + geckodriverv0.16.0,  geckodriverv0.18.0, geckodriverv0.19.0, geckodriverv0.20.0
5. Selenium 3.8.1 + Firefox 58 + geckodriverv0.16.0,  geckodriverv0.18.0, geckodriverv0.19.0, geckodriverv0.20.0

For below version where gecko drivers was not required it was working fine.

1. Selenium 2.53 + Firefox 48

## Testcase

Expected Behavior - keys() function should work to enter keys or special keys
Actual Behavior - The script failed with below exceptions

## Stacktrace

org.openqa.selenium.UnsupportedCommandException: sendKeysToActiveElement
Build info: version: '3.8.1', revision: '6e95a6684b', time: '2017-12-01T19:05:32.194Z'
System info: host: 'XXXXXXX', ip: 'XXXXXXX', os.name: 'Windows 10', os.arch: 'x86', os.version: '10.0', java.version: '1.8.0_162'
Driver info: driver.version: RemoteWebDriver
        at org.openqa.selenium.remote.http.AbstractHttpCommandCodec.encode(AbstractHttpCommandCodec.java:219)
        at org.openqa.selenium.remote.http.AbstractHttpCommandCodec.encode(AbstractHttpCommandCodec.java:118)
        at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
        at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
        at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:601)
        at org.openqa.selenium.remote.RemoteExecuteMethod.execute(RemoteExecuteMethod.java:35)
        at org.openqa.selenium.remote.RemoteKeyboard.sendKeys(RemoteKeyboard.java:38)
        at org.openqa.selenium.support.events.internal.EventFiringKeyboard.sendKeys(EventFiringKeyboard.java:41)
        at org.openqa.selenium.remote.server.handler.interactions.SendKeyToActiveElement.call(SendKeyToActiveElement.java:56)
        at org.openqa.selenium.remote.server.handler.interactions.SendKeyToActiveElement.call(SendKeyToActiveElement.java:31)
        at org.openqa.selenium.remote.server.handler.WebDriverHandler.handle(WebDriverHandler.java:41)
        at org.openqa.selenium.remote.server.rest.ResultConfig.handle(ResultConfig.java:112)
        at org.openqa.selenium.remote.server.JsonHttpCommandHandler.handleRequest(JsonHttpCommandHandler.java:191)
        at org.openqa.selenium.remote.server.DriverServlet.lambda$handleRequest$0(DriverServlet.java:261)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

## Trace-level log

PHPUnit_Extensions_Selenium2TestCase_WebDriverException: sendKeysToActiveElement
Build info: version: '3.8.1', revision: '6e95a6684b', time: '2017-12-01T19:05:32.194Z'
System info: host: 'XXXXXXX', ip: 'XXXXXXXX', os.name: 'Windows 10', os.arch: 'x86', os.version: '10.0', java.version: '1.8.0_162'
Driver info: driver.version: RemoteWebDriver

**Comment by whimboo** [comment]
It's not clear to me what this `keys` function should be. Please clarify if this is something specific to your binding in use. Also attaching a [trace log](https://firefox-source-docs.mozilla.org/testing/geckodriver/geckodriver/TraceLogs.html) would help.

**Comment by AutomatedTester** [comment]
@K-Deep This is an issue with the php client you are using, please raise a bug there.
