### ISSUE TITLE
send_keys doesn't work in Firefox

### ISSUE THREAD

**Issue by altezza072** [mozilla/geckodriver#1226]
## System

* Version: latest geckodriver 0.20
* Platform: Windows 10 x64
* Firefox: any Firefox later than 52.0
* Selenium: 3.11.0

i try to using my test in firefox+selenium, in all version of browser, later than 52.0 i received a error. send_keys doesn't work.

Traceback (most recent call last):
  File "mail.py", line 132, in <module>
   mail.send_keys(item)
  File "C:\Users\###\AppData\Local\Programs\Python\Python36-32\lib\site-packages\selenium\webdriver\remote\webelement.py", line 479, in send_keys
    'value': keys_to_typing(value)})
  File "C:\Users\###\AppData\Local\Programs\Python\Python36-32\lib\site-packages\selenium\webdriver\remote\webelement.py", line 628, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\###\AppData\Local\Programs\Python\Python36-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 312, in execute
    self.error_handler.check_response(response)
  File "C:\Users\###\AppData\Local\Programs\Python\Python36-32\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.InvalidArgumentException: Message: Expected [object Undefined] undefined to be a string

**Comment by Ant0nyJM** [comment]
post the code

**Comment by altezza072** [comment]
My code is work on Firefox 52 or earlier,problem in selenium,or geckodriver

**Comment by andreastt** [comment]
Firefox 52 is not supported.

**Comment by altezza072** [comment]
I try to use 53,54,55,56,57,58

**Comment by whimboo** [comment]
This is the same issue as #1229 which I marked invalid due to an outdated release of geckodriver.
