### ISSUE TITLE
 Process unexpectedly closed with status 1 (raspberry pi 3 headless setup)

### ISSUE THREAD

**Issue by jms37** [mozilla/geckodriver#1255]
## System

* Version: geckodriver 0.20.1
* Platform:  Raspberry Pi3 (Linux raspi1 4.14.31-v7)
* Firefox: Mozilla Firefox 52.7.3
* Selenium: 3.11.0

## Testcase
from selenium import webdriver
from selenium.webdriver.firefox.options import Options
options = Options()
options.add_argument("--headless")
driver = webdriver.Firefox(firefox_options=options)
print("Firefox Headless Browser Invoked")
driver.get('http://google.com/')
driver.quit()

## Stacktrace
python3 test.py
Traceback (most recent call last):
  File "test.py", line 10, in <module>
    driver = webdriver.Firefox(firefox_options=options)
  File "/usr/local/lib/python3.6/site-packages/selenium/webdriver/firefox/webdriver.py", line 162, in __init__
    keep_alive=True)
  File "/usr/local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 154, in __init__
    self.start_session(desired_capabilities, browser_profile)
  File "/usr/local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 243, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 312, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: Process unexpectedly closed with status 1

## Trace-level log
cat geckodriver.log
1523858307980	geckodriver	INFO	geckodriver 0.20.1
1523858308048	geckodriver	INFO	Listening on 127.0.0.1:37061
1523858342680	geckodriver	INFO	geckodriver 0.20.1
1523858342744	geckodriver	INFO	Listening on 127.0.0.1:45795
1523858353302	geckodriver	INFO	geckodriver 0.20.1
1523858353335	geckodriver	INFO	Listening on 127.0.0.1:57205
1523858364211	geckodriver	INFO	geckodriver 0.20.1
1523858364244	geckodriver	INFO	Listening on 127.0.0.1:46967
1523858551046	geckodriver	INFO	geckodriver 0.20.1
1523858551079	geckodriver	INFO	Listening on 127.0.0.1:53085
1523858687931	geckodriver	INFO	geckodriver 0.20.1
1523858687985	geckodriver	INFO	Listening on 127.0.0.1:54739
1523858689282	mozrunner::runner	INFO	Running command: "/usr/bin/firefox" "-marionette" "-profile" "/tmp/rust_mozprofile.z1P29aujXxIp"

(firefox-esr:1392): Gtk-WARNING **: Locale not supported by C library.
	Using the fallback 'C' locale.
Error: GDK_BACKEND does not match available displays
1523859854508	geckodriver	INFO	geckodriver 0.20.1
1523859854572	geckodriver	INFO	Listening on 127.0.0.1:34023
1523859855673	mozrunner::runner	INFO	Running command: "/usr/bin/firefox" "-marionette" "-profile" "/tmp/rust_mozprofile.CQg0TFrlQ858"

(firefox-esr:1432): Gtk-WARNING **: Locale not supported by C library.
	Using the fallback 'C' locale.
Error: GDK_BACKEND does not match available displays
1523859949691	geckodriver	INFO	geckodriver 0.20.1
1523859949724	geckodriver	INFO	Listening on 127.0.0.1:45581
1523860249578	geckodriver	INFO	geckodriver 0.20.1
1523860249611	geckodriver	INFO	Listening on 127.0.0.1:39159
1523860250777	mozrunner::runner	INFO	Running command: "/usr/bin/firefox" "-marionette" "-profile" "/tmp/rust_mozprofile.gfWhFNLlZ8sr"

(firefox-esr:1473): Gtk-WARNING **: Locale not supported by C library.
	Using the fallback 'C' locale.
Error: GDK_BACKEND does not match available displays
1523861926914	geckodriver	INFO	geckodriver 0.20.1
1523861926947	geckodriver	INFO	Listening on 127.0.0.1:54221
1523861928120	mozrunner::runner	INFO	Running command: "/usr/bin/firefox" "-marionette" "-headless" "-profile" "/tmp/rust_mozprofile.RjpkH6VM9EjG"

(firefox-esr:1528): Gtk-WARNING **: Locale not supported by C library.
	Using the fallback 'C' locale.
Error: GDK_BACKEND does not match available displays
1523861957042	geckodriver	INFO	geckodriver 0.20.1
1523861957075	geckodriver	INFO	Listening on 127.0.0.1:36375
1523861958235	mozrunner::runner	INFO	Running command: "/usr/bin/firefox" "-marionette" "-headless" "-profile" "/tmp/rust_mozprofile.eema2sUFZMNf"

(firefox-esr:1546): Gtk-WARNING **: Locale not supported by C library.
	Using the fallback 'C' locale.
Error: GDK_BACKEND does not match available displays
1523862095588	geckodriver	INFO	geckodriver 0.20.1
1523862095639	geckodriver	INFO	Listening on 127.0.0.1:32861
1523862096795	mozrunner::runner	INFO	Running command: "/usr/bin/firefox" "-marionette" "--headless" "-profile" "/tmp/rust_mozprofile.BTw97sZmDzBT"

(firefox-esr:1568): Gtk-WARNING **: Locale not supported by C library.
	Using the fallback 'C' locale.
Error: GDK_BACKEND does not match available displays
1523862252205	geckodriver	INFO	geckodriver 0.20.1
1523862252238	geckodriver	INFO	Listening on 127.0.0.1:55259
1523862253391	mozrunner::runner	INFO	Running command: "/usr/bin/firefox" "-marionette" "--headless" "-profile" "/tmp/rust_mozprofile.JQumQ2nhmmpC"

(firefox-esr:1587): Gtk-WARNING **: Locale not supported by C library.
	Using the fallback 'C' locale.
Error: GDK_BACKEND does not match available displays
1523862261590	geckodriver	INFO	geckodriver 0.20.1
1523862261623	geckodriver	INFO	Listening on 127.0.0.1:56661
1523862262774	mozrunner::runner	INFO	Running command: "/usr/bin/firefox" "-marionette" "--headless" "-profile" "/tmp/rust_mozprofile.JSYJ0z8e5z4k"

(firefox-esr:1605): Gtk-WARNING **: Locale not supported by C library.
	Using the fallback 'C' locale.
Error: GDK_BACKEND does not match available displays
1523862500898	geckodriver	INFO	geckodriver 0.20.1
1523862500931	geckodriver	INFO	Listening on 127.0.0.1:39051
1523862502094	mozrunner::runner	INFO	Running command: "/usr/bin/firefox" "-marionette" "-headless" "-profile" "/tmp/rust_mozprofile.C0GlqZh0bNCA"

(firefox-esr:1634): Gtk-WARNING **: Locale not supported by C library.
	Using the fallback 'C' locale.
Error: GDK_BACKEND does not match available displays
1523862510946	geckodriver	INFO	geckodriver 0.20.1
1523862510980	geckodriver	INFO	Listening on 127.0.0.1:50225
1523862512136	mozrunner::runner	INFO	Running command: "/usr/bin/firefox" "-marionette" "-headless" "-profile" "/tmp/rust_mozprofile.687TaEGVHP0c"

(firefox-esr:1652): Gtk-WARNING **: Locale not supported by C library.
	Using the fallback 'C' locale.
Error: GDK_BACKEND does not match available displays
1523862909549	geckodriver	INFO	geckodriver 0.20.1
1523862909582	geckodriver	INFO	Listening on 127.0.0.1:47335
1523862910743	mozrunner::runner	INFO	Running command: "/usr/bin/firefox" "-marionette" "-profile" "/tmp/rust_mozprofile.775cqGTDgtT1"

(firefox-esr:1687): Gtk-WARNING **: Locale not supported by C library.
	Using the fallback 'C' locale.
Error: GDK_BACKEND does not match available displays
1523863102909	geckodriver	INFO	geckodriver 0.20.1
1523863102942	geckodriver	INFO	Listening on 127.0.0.1:48539
1523863104087	mozrunner::runner	INFO	Running command: "/usr/bin/firefox" "-marionette" "-profile" "/tmp/rust_mozprofile.oRMt4eyELOLe"

(firefox-esr:1722): Gtk-WARNING **: Locale not supported by C library.
	Using the fallback 'C' locale.
Error: GDK_BACKEND does not match available displays
1523863112950	geckodriver	INFO	geckodriver 0.20.1
1523863112983	geckodriver	INFO	Listening on 127.0.0.1:53569
1523863114135	mozrunner::runner	INFO	Running command: "/usr/bin/firefox" "-marionette" "-profile" "/tmp/rust_mozprofile.ev0Nc2qs4zno"

(firefox-esr:1740): Gtk-WARNING **: Locale not supported by C library.
	Using the fallback 'C' locale.
Error: GDK_BACKEND does not match available displays
1523863276918	geckodriver	INFO	geckodriver 0.20.1
1523863276951	geckodriver	INFO	Listening on 127.0.0.1:55033
1523863278117	mozrunner::runner	INFO	Running command: "/usr/bin/firefox" "-marionette" "-profile" "/tmp/rust_mozprofile.2iAfwlsZb7Nj"

(firefox-esr:1762): Gtk-WARNING **: Locale not supported by C library.
	Using the fallback 'C' locale.
Error: GDK_BACKEND does not match available displays
1523863521715	geckodriver	INFO	geckodriver 0.20.1
1523863521748	geckodriver	INFO	Listening on 127.0.0.1:33339
1523863522882	mozrunner::runner	INFO	Running command: "/usr/bin/firefox" "-marionette" "--headless" "-profile" "/tmp/rust_mozprofile.k6YoiBGCk0Q5"

(firefox-esr:1784): Gtk-WARNING **: Locale not supported by C library.
	Using the fallback 'C' locale.
Error: GDK_BACKEND does not match available displays
1523863530595	geckodriver	INFO	geckodriver 0.20.1
1523863530628	geckodriver	INFO	Listening on 127.0.0.1:55807
1523863531776	mozrunner::runner	INFO	Running command: "/usr/bin/firefox" "-marionette" "--headless" "-profile" "/tmp/rust_mozprofile.R19BNxCv1jwB"

(firefox-esr:1802): Gtk-WARNING **: Locale not supported by C library.
	Using the fallback 'C' locale.
Error: GDK_BACKEND does not match available displays
1523864490763	geckodriver	INFO	geckodriver 0.20.1
1523864490797	geckodriver	INFO	Listening on 127.0.0.1:48037
1523864491950	mozrunner::runner	INFO	Running command: "/usr/bin/firefox" "-marionette" "--headless" "-profile" "/tmp/rust_mozprofile.1uTsAEWY6NYZ"

(firefox-esr:1840): Gtk-WARNING **: Locale not supported by C library.
	Using the fallback 'C' locale.
Error: GDK_BACKEND does not match available displays
1523865279908	geckodriver	INFO	geckodriver 0.20.1
1523865279941	geckodriver	INFO	Listening on 127.0.0.1:34905
1523865281119	mozrunner::runner	INFO	Running command: "/usr/bin/firefox" "-marionette" "--headless" "-profile" "/tmp/rust_mozprofile.07Y3tXxUzE3q"

(firefox-esr:1869): Gtk-WARNING **: Locale not supported by C library.
	Using the fallback 'C' locale.
Error: GDK_BACKEND does not match available displays

**Comment by whimboo** [comment]
Two problems here... First, geckodriver 0.20.1 doesn't work with Firefox 52ESR; therefore see the release notes. Second, there is a display error as shown in the log:

> Error: GDK_BACKEND does not match available displays

This means you have to fix that outside of Selenium and geckodriver.
