### ISSUE TITLE
linux centos6.8 geckodriver0.15 firefox52 start selenium jar failed

### ISSUE THREAD

**Issue by jijiangchengweidashenderen** [mozilla/geckodriver#1256]
[crawler]15:05:55 096  INFO (.MyProxySelector:88) - proxys is:[DIRECT]
1523862355096   geckodriver     INFO    Listening on 127.0.0.1:11397
[crawler]15:05:55 267  INFO (.MyProxySelector:55) - uri is:http://localhost:11397/, host is:localhost
[crawler]15:05:55 267  INFO (.MyProxySelector:88) - proxys is:[DIRECT]
[crawler]15:05:55 274  INFO (MyProxySelector:55) - uri is:socket://localhost:11397, host is:localhost
[crawler]15:05:55 274  INFO (.MyProxySelector:88) - proxys is:[DIRECT]
1523862355336   mozprofile::profile     INFO    Using profile path /tmp/rust_mozprofile.NIT0usz3vpJ2
1523862355339   geckodriver::marionette INFO    Starting browser /usr/bin/firefox with args []
1523862355340   geckodriver::marionette INFO    Connecting to Marionette on localhost:34156
Exception in thread "main" org.openqa.selenium.WebDriverException: connection refused
Build info: version: '3.11.0', revision: 'e59cfb3', time: '2018-03-11T20:26:55.152Z'
System info: host: 'minionD6-63', ip: '192.168.60.63', os.name: 'Linux', os.arch: 'amd64', os.version: '2.6.32-042stab126.2', java.version: '1.8.0_65'
Driver info: driver.version: FirefoxDriver
remote stacktrace: stack backtrace:
   0:           0x4d3f8d - backtrace::backtrace::trace::h0d01da48b5a2a3d1
   1:           0x4d4452 - backtrace::capture::Backtrace::new::h90c05c8c72e0f6cd
   2:           0x4349d2 - geckodriver::marionette::MarionetteHandler::create_connection::he7a110f15ba82f44
   3:           0x438298 - <geckodriver::marionette::MarionetteHandler as webdriver::server::WebDriverHandler<geckodriver::marionette::GeckoExtensionRoute>>::handle_command::h4749945b9e0ef997
   4:           0x4056e4 - std::panicking::try::do_call::h901d1278794bfce4
   5:           0x58226a - panic_unwind::__rust_maybe_catch_panic
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-musl-linux/build/src/libpanic_unwind/lib.rs:98
   6:           0x418c04 - <F as alloc::boxed::FnBox<A>>::call_box::hacb8995bcbac970c
   7:           0x57aa74 - alloc::boxed::{{impl}}::call_once<(),()>
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-musl-linux/build/src/liballoc/boxed.rs:615
                         - std::sys_common::thread::start_thread
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-musl-linux/build/src/libstd/sys_common/thread.rs:21
                         - std::sys::imp::thread::{{impl}}::new::thread_start
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-musl-linux/build/src/libstd/sys/unix/thread.rs:84
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
        at org.openqa.selenium.remote.W3CHandshakeResponse.lambda$new$0(W3CHandshakeResponse.java:57)
        at org.openqa.selenium.remote.W3CHandshakeResponse.lambda$getResponseFunction$2(W3CHandshakeResponse.java:104)
        at org.openqa.selenium.remote.ProtocolHandshake.lambda$createSession$0(ProtocolHandshake.java:123)
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
        at java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:958)
        at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
        at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
        at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:464)
        at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:126)
        at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:73)
        at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:136)
        at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
        at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:545)
        at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:209)
        at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:132)
        at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:120)
        at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:98)
        at com.ximalaya.crawler.node.parse.impl.YouTubeParser4Playlist.initPage(YouTubeParser4Playlist.java:192)
        at com.ximalaya.crawler.node.parse.impl.YouTubeParser4Playlist.main(YouTubeParser4Playlist.java:261)
15:06 root@minionD6-63 webdriver $

**Comment by andreastt** [comment]
geckodriver 0.15 is very old adn Firefox 52 is not supported.

**Comment by jijiangchengweidashenderen** [comment]
but i start them on a linux machine.and another one failed

**Comment by jijiangchengweidashenderen** [comment]
@andreastt I had a machine start success, but another one failed.why?

**Comment by whimboo** [comment]
Without a trace log there is nothing we can tell you. Find help in how to create one here: https://firefox-source-docs.mozilla.org/testing/geckodriver/geckodriver/TraceLogs.html.
