### ISSUE TITLE
NS_ERROR_UNKNOWN_PROTOCOL

### ISSUE THREAD

**Issue by arya6000** [mozilla/geckodriver#1271]
## System

* Version: v0.20.1
* Platform: Linux Mint 18
* Firefox: 60.0 (64-bit)
* Selenium: 3.12.0

This is about a page which returns the following content 

`<script type="text/javascript">window.location.href="fbconnect:\/\/success#state..........`

as soon as the page loads, Firefox will try to load fbconnect:\/\/success#state..... , I do understand that Firefox does not support the fbconnect protocol, but I did add the fbconnect protocol to it with the following line

`profile.setPreference("network.protocol-handler.expose.fbconnect", false);`

I want to get the content of the page before Firefox tries to load the fbconnect protocol. Is there anyway to achieve this?
 

## Testcase

```

	volatile WebDriver driver = null;
	volatile String USER_AGENT = "Mozilla/5.0 (Linux; Android 7.0; Moto G (4) Build/NPJS25.93-14.7-5; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/66.0.3359.158 Mobile Safari/537.36";

	public void loginToFacebook() {
		try {
			if (OSValidator.isUnix()) {
				System.setProperty("webdriver.gecko.driver", "geckodriver");
			} else if (OSValidator.isWindows()) {
				System.setProperty("webdriver.gecko.driver", "geckodriver.exe");
			}
			//System.setProperty(FirefoxDriver.SystemProperty.DRIVER_USE_MARIONETTE, "true");
			//System.setProperty(FirefoxDriver.SystemProperty.BROWSER_LOGFILE, "/dev/null");

			FirefoxProfile profile = new FirefoxProfile();
			profile.setPreference("network.protocol-handler.expose.fbconnect", false);
			profile.setPreference("media.peerconnection.enabled", false);
			profile.setPreference("general.useragent.override", USER_AGENT);


			FirefoxOptions options = new FirefoxOptions();
			options.setHeadless(false);
			options.setProfile(profile);
			driver = new FirefoxDriver(options);

			driver.get(
					"https://m.facebook.com/v3.0/dialog/oauth?client_id=464891386855067&e2e=%7B%22init%22%3A1526253341806%7D&sdk=android-4.33.0&scope=user_birthday%2Cuser_friends%2Cemail%2Cuser_likes%2Cuser_photos&state=%7B%220_auth_logger_id%22%3A%2221137766-f789-4813-89b8-bcfa1253047e%22%2C%223_method%22%3A%22web_view%22%7D&default_audience=friends&redirect_uri=fbconnect%3A%2F%2Fsuccess&auth_type=rerequest&display=touch&response_type=token%2Csigned_request&return_scopes=true");

			driver.findElement(By.xpath("//*[@id=\"m_login_email\"]")).sendKeys("AudreyRice7485@outlook.com");
			driver.findElement(By.xpath("//*[@id=\"m_login_password\"]")).sendKeys("AudreyRice7485@outlook.com");

			driver.findElement(By.xpath("//*[@id=\"u_0_5\"]")).click();

			Thread.sleep(5000);
                        //exception happens when button is pressed on the next line
			driver.findElement(By.xpath("//*[@id=\"u_0_3\"]")).click();
			System.out.println(driver.getPageSource());
			Thread.sleep(20000);
		} catch (Exception e) {
			e.printStackTrace();
		} finally {
			if (driver != null) {
				driver.quit();
			}
		}
	}

```

## Stacktrace

```
org.openqa.selenium.WebDriverException: Reached error page: about:neterror?e=unknownProtocolFound&u=fbconnect%3A//success%23state%3D%257B%25220_auth_logger_id%2522%253A%252221137766-f789-4813-89b8-bcfa1253047e%2522%252C%25223_method%2522%253A%2522web_view%2522%257D%26granted_scopes%3Duser_birthday%252Cuser_likes%252Cuser_photos%252Cuser_friends%252Cemail%252Cpublic_profile%26denied_scopes%3D%26signed_request%3DP_GWLTpWb3GfD2R4bcFAVv7WJejY82CbnvsVBkoNzBw.eyJhbGdvcml0aG0iOiJITUFDLVNIQTI1NiIsImNvZGUiOiJBUUJGWDB0UU1MTzdrUXBwaUVxVENKS0VvUWxvSzB5TE9rNGxkWTlyS0pxd2IxQ0VFY2FFR3ZvWWxLN29HZDBMZzEzeVRTeGdjZGRNU0w3bno1ZjV4N3JfZ19VNkx0QllSZ1JkclVUUUpQcDQ1NXU4UDd1NWFLajltQ2JvUXBmNl94SHhvWGxJN3NSbjdkOXViNTh2cUlRS2lxSUZLSTNIemtyeE9XLVNGSk5MSk1hX1BpZE1EVjNQakxMNTAwSzd0dk9zYlhWZ0E1eE5rQUp5eFVJOS1ER0tQVUx1dVpNaUNxOHYtaElseWxCZEhnczhfQmdWOVZybWtManlyWVhidklxMzFLd1NhQmFiS3ZYb1plaUtQUEY1blhGMy1DbTExRG1CMkhDcW1ld2NtSGsxX2l1SnVwakpNVXVaOWlWNFBEdmwwTzdTQnJYNU12TENrSExsTFJGZTZBRGp5YXRpWEVpMkx0a0g2R014MWciLCJpc3N1ZWRfYXQiOjE1MjYzNDIwMDQsInVzZXJfaWQiOiIxMzI2ODAxNzA5MjE1OTgifQ%26access_token%3DEAAGm0PX4ZCpsBAEASsOzOZAS564tGHSdqW1uY1exEL5eZAgKtJIvAb325PYZAiGvPVjAGymUjLsiEtcdy3yZA2A2sIn9l7KkJhmjbH7XZB4PKNkYPQP02ZBs3FCjFPASzSgkLfYchEEelTwJmyLCh3jt99LXRbdpa0SyhtZCa3dnGjChsnOokdhKMWWZB41iKEh10hzrH8r32yAZDZD%26expires_in%3D6223000&c=UTF-8&f=regular&d=Firefox%20doesn%E2%80%99t%20know%20how%20to%20open%20this%20address%2C%20because%20one%20of%20the%20following%20protocols%20%28fbconnect%29%20isn%E2%80%99t%20associated%20with%20any%20program%20or%20is%20not%20allowed%20in%20this%20context.
Build info: version: '3.12.0', revision: '7c6e0b3', time: '2018-05-08T14:04:26.12Z'
System info: host: 'GE70', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '4.13.0-41-generic', java.version: '10.0.1'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities {acceptInsecureCerts: true, browserName: firefox, browserVersion: 60.0, javascriptEnabled: true, moz:accessibilityChecks: false, moz:headless: false, moz:processID: 11346, moz:profile: /tmp/rust_mozprofile.hzl30s..., moz:useNonSpecCompliantPointerOrigin: false, moz:webdriverClick: true, pageLoadStrategy: normal, platform: LINUX, platformName: LINUX, platformVersion: 4.13.0-41-generic, rotatable: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}}
Session ID: 25d81a25-ab25-4da8-9444-122bd97d3589
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:488)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:187)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:122)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:49)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:543)
	at org.openqa.selenium.remote.RemoteWebElement.execute(RemoteWebElement.java:276)
	at org.openqa.selenium.remote.RemoteWebElement.click(RemoteWebElement.java:83)
```

## Trace-level log

```
JavaScript error: https://m.facebook.com/v3.0/dialog/oauth/confirm, line 1: NS_ERROR_UNKNOWN_PROTOCOL: 
org.openqa.selenium.WebDriverException: Reached error page: about:neterror?e=unknownProtocolFound&u=fbconnect%3A//success%23state%3D%257B%25220_auth_logger_id%2522%253A%252221137766-f789-4813-89b8-bcfa1253047e%2522%252C%25223_method%2522%253A%2522web_view%2522%257D%26granted_scopes%3Duser_birthday%252Cuser_likes%252Cuser_photos%252Cuser_friends%252Cemail%252Cpublic_profile%26denied_scopes%3D%26signed_request%3De8RTRd0lXjdA5Pn5UOslNHInS9tYHRSXFRaBxYyi6KA.eyJhbGdvcml0aG0iOiJITUFDLVNIQTI1NiIsImNvZGUiOiJBUUNvQnV2WnNlTXpjTGFZcTU3OEoxcmdxTDZIMFd4UlRiU3VzRFljb19LcnRrbXRKUU1DV2hEckZMRHcxZVVTdi1oWGFJNlVUTm1WSWNsc3NRaGxGZ3BsY1RmaXU3UHVjRS1VMldEREV1UGM5UnFZT3J1N1dqZ0hzRzd0em83QWpzNDlxVS1hVGpsYjhWOWE1SDA2S3hWRlYxazMzbWQ3b2tDU2FnNGc5RHRWeTJGeXlMbjJtbFJaRFJ5d2tOdUJzXzg3Z0cyRjRnME10dllCQVJvY2F6cUVlOTkxOEo5cHI5N094aGlDQ1BTMkhLRi02cjhFb1EyblFscHJFdFNZOHE4TVcyS1h0TmR0SGlncUk3WE9xM20wQVJJV0ZlUGwyZ3VHX2d0YWl5cDdNVndHNXhmRUVkRndEa3poendrTnN1TGZ5RVBPWTY0LVR3czg4SXZYMmJHWUNSSjFtNFRrMzRmd2RGQ0hBYzl4Y0EiLCJpc3N1ZWRfYXQiOjE1MjYzNDIxMDIsInVzZXJfaWQiOiIxMzI2ODAxNzA5MjE1OTgifQ%26access_token%3DEAAGm0PX4ZCpsBADSthQ6dhAcFZBZBVVEcZADVtPF9Bk8dKZCbJ4dyuTWOuU468ZAlEAumhEW71YubCatyTvORO2NZBjx9E72NbWoIEtuMx0NZCrK3dolNalXwTBlBZA63f88fHxNjuMh57COCmrgPh8AorNsr1ZBwG9ZCA6ZB4joWpwe6f2EBPycPBLHC5RgLzdwNEaty14wZBdcsJwZDZD%26expires_in%3D6222902&c=UTF-8&f=regular&d=Firefox%20doesn%E2%80%99t%20know%20how%20to%20open%20this%20address%2C%20because%20one%20of%20the%20following%20protocols%20%28fbconnect%29%20isn%E2%80%99t%20associated%20with%20any%20program%20or%20is%20not%20allowed%20in%20this%20context.
Build info: version: '3.12.0', revision: '7c6e0b3', time: '2018-05-08T14:04:26.12Z'
System info: host: 'GE70', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '4.13.0-41-generic', java.version: '10.0.1'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities {acceptInsecureCerts: true, browserName: firefox, browserVersion: 60.0, javascriptEnabled: true, moz:accessibilityChecks: false, moz:headless: false, moz:processID: 11716, moz:profile: /tmp/rust_mozprofile.vTxTG9..., moz:useNonSpecCompliantPointerOrigin: false, moz:webdriverClick: true, pageLoadStrategy: normal, platform: LINUX, platformName: LINUX, platformVersion: 4.13.0-41-generic, rotatable: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}}
Session ID: 5611cc08-c9f4-4b8c-8d71-ab78eed25e1a

```

**Comment by whimboo** [comment]
You may not have setup your system correctly. Please see http://kb.mozillazine.org/Register_protocol#Linux. Also as far as I can see it will still need user interaction to accept the new protocol. This is something you might not be able to do with Selenium. So your question seems to be mainly a Firefox one but not geckodriver one.

In regards of earlier intercepting a page load you can set page load strategies: https://w3c.github.io/webdriver/#dfn-table-of-page-load-strategies. So `eager` might be helpful here.

As long as it's not clear that there is a problem with geckodriver I will close this issue.
