### ISSUE TITLE
JavaScript error: resource://gre/modules/XPCOMUtils.jsm, line 187: TypeError: undefined has no properties

### ISSUE THREAD

**Issue by Haski-server** [mozilla/geckodriver#1275]
## System

* Version: geckodriver-v0.20.1-arm7hf
* Platform: Linux orangepizero 4.14.18-sunxi #24 SMP Fri Feb 9 16:24:32 CET 2018 armv7l GNU/Linux
* Firefox: Mozilla Firefox 60.0.1
* Selenium: Python 3.5 selenium 3.12.0

### Console
```
>>> from pyvirtualdisplay import Display
>>> from selenium import webdriver
>>> display = Display(visible=0, size=(800, 600))
>>> display.start()
<Display cmd_param=['Xvfb', '-br', '-nolisten', 'tcp', '-screen', '0', '800x600x24', ':1017'] cmd=['Xvfb', '-br', '-nolisten', 'tcp', '-screen', '0', '800x600x24', ':1017'] oserror=None return_code=None stdout="None" stderr="None" timeout_happened=False>
>>> browser = webdriver.Firefox()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/firefox/webdriver.py", line 170, in __init__
    keep_alive=True)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 156, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 245, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 314, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: Process unexpectedly closed with status 11
```
### geckodriver.log
```
1526629162711	geckodriver	INFO	geckodriver 0.20.1
1526629162754	geckodriver	INFO	Listening on 127.0.0.1:56627
1526629163788	mozrunner::runner	INFO	Running command: "/usr/bin/firefox" "-marionette" "-profile" "/tmp/rust_mozprofile.roct3sdPvLRu"
JavaScript error: resource://gre/modules/XPCOMUtils.jsm, line 187: TypeError: undefined has no properties
JavaScript error: resource://gre/modules/XPCOMUtils.jsm, line 187: TypeError: undefined has no properties
JavaScript error: resource://gre/modules/XPCOMUtils.jsm, line 187: TypeError: undefined has no properties
JavaScript error: resource://gre/modules/XPCOMUtils.jsm, line 187: TypeError: undefined has no properties
JavaScript error: resource://gre/modules/XPCOMUtils.jsm, line 187: TypeError: undefined has no properties
JavaScript error: resource://gre/modules/XPCOMUtils.jsm, line 187: TypeError: undefined has no properties
JavaScript error: resource://gre/modules/XPCOMUtils.jsm, line 187: TypeError: undefined has no properties
ExceptionHandler::GenerateDump cloned child ExceptionHandler::WaitForContinueSignal waiting for continue signal...
8015
```
## Start with Xfce
```
>>> from selenium import webdriver
>>> browser = webdriver.Firefox()
```

### Console
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/firefox/webdriver.py", line 170, in __init__
    keep_alive=True)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 156, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 245, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 314, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: Process unexpectedly closed with status 11
```
### geckodriver.log
```
1526629241571	geckodriver	INFO	geckodriver 0.20.1
1526629241625	geckodriver	INFO	Listening on 127.0.0.1:38789
1526629242643	mozrunner::runner	INFO	Running command: "/usr/bin/firefox" "-marionette" "-profile" "/tmp/rust_mozprofile.nr6BYR94HI30"
JavaScript error: resource://gre/modules/XPCOMUtils.jsm, line 187: TypeError: undefined has no properties
JavaScript error: resource://gre/modules/XPCOMUtils.jsm, line 187: TypeError: undefined has no properties
JavaScript error: resource://gre/modules/XPCOMUtils.jsm, line 187: TypeError: undefined has no properties
JavaScript error: resource://gre/modules/XPCOMUtils.jsm, line 187: TypeError: undefined has no properties
JavaScript error: resource://gre/modules/XPCOMUtils.jsm, line 187: TypeError: undefined has no properties
JavaScript error: resource://gre/modules/XPCOMUtils.jsm, line 187: TypeError: undefined has no properties
JavaScript error: resource://gre/modules/XPCOMUtils.jsm, line 187: TypeError: undefined has no properties
ExceptionHandler::GenerateDump cloned child ExceptionHandler::WaitForContinueSignal waiting for continue signal...
8135
ExceptionHandler::SendContinueSignalToChild sent continue signal to child
```

**Comment by andreastt** [comment]
It looks to me like your Firefox crashes. Have you checked about:crashes? Can you start it manually on the machine?

**Comment by whimboo** [comment]
This is a very internal error which should basically not happen, so I wonder what's special to your system. As I can see this is an ARM platform, do you have more details for us? Also where did you download Firefox 60.0.1 for ARM from? 

> It looks to me like your Firefox crashes. Have you checked about:crashes? Can you start it manually on the machine?

Under automation the crash report will not appear in `about:crashes`. Only if Firefox also crashes when started manually, this will be an option. If that is not the case I would suggest you to go through the following step and upload the crash data files: https://dxr.mozilla.org/mozilla-central/source/testing/geckodriver/doc/CrashReports.md

**Comment by leftcoastryan** [comment]
I am having the same issue with this setup:

```
Raspberry Pi 3, Model B
Broadcom BCM2837 64bit CPU

Raspbian GNU/Linux 8.0 (jessie)

Python 2.7.9 and 3.4.2 (both cause the error)
Selenium 3.12.0
Firefox 60.0.1
Geckodriver 0.20.1
Java 1.8.0_171-b11
```

I attempted to run the CrashReports.md script, but get this error:

```
Traceback (most recent call last):
  File "crash_test.py", line 5, in <module>
    profile = tempfile.mkdtemp(".selenium")
NameError: name 'tempfile' is not defined
```

I'm new to the software, so I am not able to quickly fix this undefined variable issue.

Thanks

**Comment by leftcoastryan** [comment]
Potential answer [here](https://raspberrypi.stackexchange.com/questions/75463/firefox-57-on-a-raspberry-pi/75490):

> Due to an unresolved issue since Firefox 55, the newer Firefox versions (latest is now Firefox 58) do not work on standard Raspbian or Ubuntu MATE. This issue continues up to the present. I myself have tried out each new version on Ubuntu MATE.
> 
> On standard Raspbian, the best you can do for now is to stay with Firefox ESR, as it will still get security updates. The latest RPi compatible ESR version is currently Firefox 52.5.2 ESR.

Though, I'm seeing the latest version available from the Raspbian repositories (i.e., not the Firefox repositories) is 52.7.3.

**Comment by whimboo** [comment]
@leftcoastryan please add `import tempfile` at the beginning of the script. I missed that, and will fix it soon. Please let me know about the results.

**Comment by whimboo** [comment]
Btw. when following the forums for RPi and Ubuntu Mate I found https://bugzilla.mozilla.org/show_bug.cgi?id=1391802. There are listed workarounds and people got it working. Please have a look and let us know.

Given that this is not a geckodriver or Marionette issue I'm closing the issue now. We can still continue to discuss here.
