### ISSUE TITLE
gecko driver does not load page properly - cannot read name property

### ISSUE THREAD

**Issue by inthegarage** [mozilla/geckodriver#128]
I have now got the selenium driver working with gecko and eveything is picked up as it should be.
This is running in Windows 10 and selenium is running as administrator.

When I start my protractor script the following error is thrown from the console:

```
09:57:37.315 INFO - Executing: [get: data:text/html,<html></html>])
1467277057321   Marionette      TRACE   conn0 -> [0,48,"get",{"url":"data:text/html,<html></html>"}]
1467277057442   Marionette      TRACE   conn0 <- [1,48,null,{}]
09:57:37.444 INFO - Done: [get: data:text/html,<html></html>]
09:57:37.456 INFO - Executing: [execute script: window.name = "NG_DEFER_BOOTSTRAP!" + window.name;window.location.replace("http://localhost:9001/#/search");, []])
1467277057467   Marionette      TRACE   conn0 -> [0,49,"executeScript",{"args":[],"newSandbox":false,"script":"window.name = \"NG_DEFER_BOOTSTRAP!\" + window.name;window.location.replace(\"http://localhost:9001/#/search\");","scriptTimeout":null,"specialPowers":false}]
1467277057471   Marionette      TRACE   conn0 <- [1,49,{"error":"javascript error","message":"Error: Permission denied to access property \"name\"","stacktrace":"execute_script\ninline javascript, line 0\nsrc: \"var __marionetteFunc = function(){window.name = \"NG_DEFER_BOOTSTRAP!\" + window.name;window.location.replace(\"http://localhost:9001/#/search\");};__marionetteFunc.apply(null, __marionetteParams);\"\nStack:\n__marionetteFunc@dummy file:0:35\n@dummy file:0:149\n"},nul
09:57:37.678 WARN - Exception thrown
org.openqa.selenium.WebDriverException: Error: Permission denied to access property "name" (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 10 milliseconds
Build info: version: '2.53.0', revision: '35ae25b', time: '2016-03-15 17:00:58'
System info: host: 'PS-E7450', ip: '192.168.2.63', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_74'
Driver info: org.openqa.selenium.firefox.MarionetteDriver
Capabilities [{rotatable=false, raisesAccessibilityExceptions=false, marionette=true, count=1, webdriver.gecko.driver=/tools/gecko, appBuildId=20160623154057, version=47.0.1, platform=XP, proxy={}, command_id=1, specificationLevel=0, acceptSslCerts=false, browserVersion=47.0.1, platformVersion=10.0, XULappId={ec8030f7-c20a-464f-9b0e-13a3a9e97384}, browserName=Firefox, takesScreenshot=true, takesElementScreenshot=true, platformName=Windows_NT, device=desktop}]
Session ID: 3581dc95-c899-4d58-92cf-a8172078f721
        at sun.reflect.GeneratedConstructorAccessor9.newInstance(Unknown Source)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:206)
        at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:158)
        at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:678)
        at org.openqa.selenium.remote.RemoteWebDriver.executeScript(RemoteWebDriver.java:575)
        at sun.reflect.GeneratedMethodAccessor13.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.openqa.selenium.support.events.EventFiringWebDriver$2.invoke(EventFiringWebDriver.java:103)
        at com.sun.proxy.$Proxy1.executeScript(Unknown Source)
        at org.openqa.selenium.support.events.EventFiringWebDriver.executeScript(EventFiringWebDriver.java:217)
        at org.openqa.selenium.remote.server.handler.ExecuteScript.call(ExecuteScript.java:56)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at org.openqa.selenium.remote.server.DefaultSession$1.run(DefaultSession.java:176)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
09:57:37.772 WARN - Exception: Error: Permission denied to access property "name" (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 10 milliseconds
Build info: version: '2.53.0', revision: '35ae25b', time: '2016-03-15 17:00:58'
System info: host: 'PS-E7450', ip: '192.168.2.63', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_74'
Driver info: org.openqa.selenium.firefox.MarionetteDriver
Capabilities [{rotatable=false, raisesAccessibilityExceptions=false, marionette=true, count=1, webdriver.gecko.driver=/tools/gecko, appBuildId=20160623154057, version=47.0.1, platform=XP, proxy={}, command_id=1, specificationLevel=0, acceptSslCerts=false, browserVersion=47.0.1, platformVersion=10.0, XULappId={ec8030f7-c20a-464f-9b0e-13a3a9e97384}, browserName=Firefox, takesScreenshot=true, takesElementScreenshot=true, platformName=Windows_NT, device=desktop}]
Session ID: 3581dc95-c899-4d58-92cf-a8172078f721
09:57:37.870 INFO - Executing: [delete session: 96e16188-f8b6-4c7e-b091-aa12764c6859])
1467277057878   Marionette      TRACE   conn0 -> [0,50,"quitApplication",{"flags":["eForceQuit"]}]
1467277057879   Marionette      TRACE   conn0 <- [1,50,null,{}]
09:57:38.429 INFO - Done: [delete session: 96e16188-f8b6-4c7e-b091-aa12764c6859]
```

My 1st page does load - partially, but then the page (subsequent tests) are not displayed.
What can be done to help Marionette get the window.name? Please advise what sort of information you need to investigate this.

Many thanks.

**Comment by andreastt** [comment]
Firefox 47 is missing a few important Marionette features, such as the ability to retrieve properties from the `window` object. You should run this again with [Nightly](https://nightly.mozilla.org/). I believe this problem is resolved by [bug 1123506](https://bugzilla.mozilla.org/show_bug.cgi?id=1123506), which is available in Firefox 48 and later.

**Comment by inthegarage** [comment]
I will try that, many thanks.

**Comment by inthegarage** [comment]
Yes that has worked. Looks like FF 47 is a bit of island and should be avoided when using protractor/selenium. 
Thanks for the quick turn around on these issues, much appreaciated.

**Comment by sandeepjain1987** [comment]
I see a similar issue on FF 49 as well. Is this fix available only in Nightly builds ?

**Comment by andreastt** [comment]
@sandeepjain1987 See my comment made on 30 June.

**Comment by vijaysp77** [comment]
Even I am still able to see that issue with following configuration
FF 49
Protractor 0.6 as well as 0.8
Selenium 3.0
it shows error as Error occurred with message : Error in Login Document was unloaded during execution (UnexpectedJavaScriptError)
