### ISSUE TITLE
Message: timeouts when trying to set implicit_wait

### ISSUE THREAD

**Issue by OranShuster** [mozilla/geckodriver#1282]
## System

* Version: 0.20.1
* Platform: Linux debian 8.10
* Firefox: firefox-esr 60.0.1 (64-bit)
* Selenium: 3.12.0 for python

## Testcase

`        
driver = webdriver.Firefox()
driver.implicitly_wait(5)
`

## Stacktrace
```
Traceback (most recent call last):
  File "/home/oran/ParKam/devel/parkam_www/smoke_tests/lib/web_test_case.py", line 32, in setUp
    self.driver.implicitly_wait(5)
  File "/usr/local/lib/python3.4/dist-packages/selenium/webdriver/remote/webdriver.py", line 892, in implicitly_wait
    'implicit': int(float(time_to_wait) * 1000)})
  File "/usr/local/lib/python3.4/dist-packages/selenium/webdriver/remote/webdriver.py", line 314, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.4/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: timeouts
```
## Trace-level log

```
1526967609114	webdriver::server	DEBUG	-> POST /session/2cfca206-5f4f-41c2-a90e-80d4090d5929/timeouts {"implicit": 5000}
1526967609117	geckodriver::marionette	TRACE	-> 34:[0,2,"timeouts",{"implicit":5000}]
1526967609140	Marionette	TRACE	0 -> [0,2,"timeouts",{"implicit":5000}]
1526967609141	Marionette	TRACE	0 <- [1,2,{"error":"unknown command","message":"timeouts","stacktrace":"WebDriverError@chrome://marionette/content/error.js:178:5\ ... et@chrome://marionette/content/server.js:241:8\n_onJSONObjectReady/<@chrome://marionette/content/transport.js:500:9\n"},null]
1526967609141	geckodriver::marionette	TRACE	<- [1,2,{"error":"unknown command","message":"timeouts","stacktrace":"WebDriverError@chrome://marionette/content/error.js:178:5\nUnknownCommandError@chrome://marionette/content/error.js:518:5\ndespatch@chrome://marionette/content/server.js:286:13\nexecute@chrome://marionette/content/server.js:267:11\nonPacket/<@chrome://marionette/content/server.js:242:15\nonPacket@chrome://marionette/content/server.js:241:8\n_onJSONObjectReady/<@chrome://marionette/content/transport.js:500:9\n"},null]
1526967609143	webdriver::server	DEBUG	<- 404 Not Found {"value":{"error":"unknown error","message":"timeouts","stacktrace":"stack backtrace:\n   0:           0x57af6d - backtrace::backtrace::trace::h59229d13f6a8837d\n   1:           0x57b0c2 - backtrace::capture::Backtrace::new::h23089c033eded8f0\n   2:           0x4472fc - webdriver::error::WebDriverError::new::h0b226f62ff19e120\n   3:           0x455bb8 - geckodriver::marionette::MarionetteSession::response::hcd41032e9ef5a928\n   4:           0x46ace4 - geckodriver::marionette::MarionetteConnection::send_command::hd7b113ec7d281909\n   5:           0x426e5f - <webdriver::server::Dispatcher<T, U>>::run::h62323eaff3e71b8c\n   6:           0x40935c - std::panicking::try::do_call::hb7e6ff6d130a72cf\n   7:           0x5de23a - panic_unwind::__rust_maybe_catch_panic\n                        at /checkout/src/libpanic_unwind/lib.rs:98\n   8:           0x41c003 - <F as alloc::boxed::FnBox<A>>::call_box::hd6ceeda495c4fa0e\n   9:           0x5d68d4 - alloc::boxed::{{impl}}::call_once<(),()>\n                        at /checkout/src/liballoc/boxed.rs:650\n                         - std::sys_common::thread::start_thread\n                        at /checkout/src/libstd/sys_common/thread.rs:21\n                         - std::sys::imp::thread::{{impl}}::new::thread_start\n                        at /checkout/src/libstd/sys/unix/thread.rs:84"}}
1526967609241	Marionette	DEBUG	Closed connection 0
```

Used to run my tests with ff-esr 52, gecko 0.17 and selenium 3.11 and everything worked fine
since i wanted to use headless mode (that does not work in ff52 as far as i can tell) i upgraded everything to what i wrote above. since then i cannot set implicit wait without getting the error. 
this was also tested with selenium 3.11 and with the same result

**Comment by OranShuster** [comment]
actually it was an old version of geckodriver. Still not sure how that happened (i actually went through my zsh history to make sure i moved and overwrote the 0.17 version)

**Comment by whimboo** [comment]
I see. It makes sense. Thanks.
