### ISSUE TITLE
Unable to parse new session - sends back a value as key and sessionId and capabilities are values

### ISSUE THREAD

**Issue by suryavir** [mozilla/geckodriver#1327]
## System

* Version: gecko v 21
* Platform: RHEL 6.9
* Firefox: Firefox 60 
* Selenium: 3.13.0
* Protractor : 5.3.0 

## Testcase

1. We are running our protractor test on Jenkins in the jenkins CI Box. We have an xvfb plugin which runs first and then we have our protractor test run which runs through maven. The protractor conf is such that it has directConnect as true. 

We get an error of unable to parse new session back

## Stacktrace

$ tsc && cross-env TEST_ENV=int protractor dist/out-tsc/e2e/protractor.conf.js
[20:44:37] I/direct - Using FirefoxDriver directly...
[20:44:37] I/launcher - Running 1 instances of WebDriver
[20:44:39] E/launcher - Unable to parse new session response: {"value": {"sessionId":"37c2a0ba-9531-45d6-9c8e-56d2693a5900","capabilities":{"acceptInsecureCerts":false,"browserName":"firefox","browserVersion":"60.1.0","moz:accessibilityChecks":false,"moz:headless":false,"moz:processID":6258,"moz:profile":"/tmp/rust_mozprofile.F1xaGQ8IGsbc","moz:useNonSpecCompliantPointerOrigin":false,"moz:webdriverClick":true,"pageLoadStrategy":"normal","platformName":"linux","platformVersion":"2.6.32-696.16.1.el6.x86_64","rotatable":false,"timeouts":{"implicit":0,"pageLoad":300000,"script":30000}}}}
[20:44:39] E/launcher - WebDriverError: Unable to parse new session response: {"value": {"sessionId":"37c2a0ba-9531-45d6-9c8e-56d2693a5900","capabilities":{"acceptInsecureCerts":false,"browserName":"firefox","browserVersion":"60.1.0","moz:accessibilityChecks":false,"moz:headless":false,"moz:processID":6258,"moz:profile":"/tmp/rust_mozprofile.F1xaGQ8IGsbc","moz:useNonSpecCompliantPointerOrigin":false,"moz:webdriverClick":true,"pageLoadStrategy":"normal","platformName":"linux","platformVersion":"2.6.32-696.16.1.el6.x86_64","rotatable":false,"timeouts":{"implicit":0,"pageLoad":300000,"script":30000}}}}
    at WebDriverError (/export1/local_rdt/im-jenkins/jenkins_home/jobs/im-gui2-e2e-tests/workspace/node_modules/selenium-webdriver/lib/error.js:27:5)
    at client_.send.then.response (/export1/local_rdt/im-jenkins/jenkins_home/jobs/im-gui2-e2e-tests/workspace/node_modules/selenium-webdriver/http/index.js:477:17)
    at ManagedPromise.invokeCallback_ (/export1/local_rdt/im-jenkins/jenkins_home/jobs/im-gui2-e2e-tests/workspace/node_modules/selenium-webdriver/lib/promise.js:1379:14)
    at TaskQueue.execute_ (/export1/local_rdt/im-jenkins/jenkins_home/jobs/im-gui2-e2e-tests/workspace/node_modules/selenium-webdriver/lib/promise.js:2913:14)
    at TaskQueue.executeNext_ (/export1/local_rdt/im-jenkins/jenkins_home/jobs/im-gui2-e2e-tests/workspace/node_modules/selenium-webdriver/lib/promise.js:2896:21)
    at asyncRun (/export1/local_rdt/im-jenkins/jenkins_home/jobs/im-gui2-e2e-tests/workspace/node_modules/selenium-webdriver/lib/promise.js:2820:25)
    at /export1/local_rdt/im-jenkins/jenkins_home/jobs/im-gui2-e2e-tests/workspace/node_modules/selenium-webdriver/lib/promise.js:639:7
    at process._tickCallback (internal/process/next_tick.js:103:7)
From: Task: WebDriver.createSession()
    at Function.createSession (/export1/local_rdt/im-jenkins/jenkins_home/jobs/im-gui2-e2e-tests/workspace/node_modules/selenium-webdriver/lib/webdriver.js:329:24)
    at Driver (/export1/local_rdt/im-jenkins/jenkins_home/jobs/im-gui2-e2e-tests/workspace/node_modules/selenium-webdriver/firefox/index.js:386:38)
    at Direct.getNewDriver (/export1/local_rdt/im-jenkins/jenkins_home/jobs/im-gui2-e2e-tests/workspace/node_modules/protractor/built/driverProviders/direct.js:74:26)
    at Runner.createBrowser (/export1/local_rdt/im-jenkins/jenkins_home/jobs/im-gui2-e2e-tests/workspace/node_modules/protractor/built/runner.js:197:43)
    at /export1/local_rdt/im-jenkins/jenkins_home/jobs/im-gui2-e2e-tests/workspace/node_modules/protractor/built/runner.js:276:30
    at _fulfilled (/export1/local_rdt/im-jenkins/jenkins_home/jobs/im-gui2-e2e-tests/workspace/node_modules/protractor/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/export1/local_rdt/im-jenkins/jenkins_home/jobs/im-gui2-e2e-tests/workspace/node_modules/protractor/node_modules/q/q.js:863:30)
    at Promise.promise.promiseDispatch (/export1/local_rdt/im-jenkins/jenkins_home/jobs/im-gui2-e2e-tests/workspace/node_modules/protractor/node_modules/q/q.js:796:13)
    at /export1/local_rdt/im-jenkins/jenkins_home/jobs/im-gui2-e2e-tests/workspace/node_modules/protractor/node_modules/q/q.js:556:49
    at runSingle (/export1/local_rdt/im-jenkins/jenkins_home/jobs/im-gui2-e2e-tests/workspace/node_modules/protractor/node_modules/q/q.js:137:13)

Any thoughts on this? I read all the other issues related to this and it felt like the latest gecko driver has fixed this issue but issue is prevalent in gecko v21.0 as well.

**Comment by andreastt** [comment]
I suspect the issue here is that Protractor does not support the W3C WebDriver protocol. I would file an upstream bug against the client.
