### ISSUE TITLE
The browser appears to have exited before we could connect. 

### ISSUE THREAD

**Issue by alirezastack** [mozilla/geckodriver#1334]
## Meta:
OS: Debian GNU/Linux 9
Selenium Version:  3.13.0
Browser:  Firefox

## Browser Version:  
60.1.0 (linux 64bit)

## Expected Behavior:
Run Firefox from Selenium

## Actual Behavior:

```
Traceback (most recent call last):
  File "selen.py", line 8, in <module>
    driver = webdriver.Firefox(firefox_binary=binary, capabilities=capabilities)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/webdriver.py", line 187, in __init__
    self.binary, timeout)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/extension_connection.py", line 52, in __init__
    self.binary.launch_browser(self.profile, timeout=timeout)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/firefox_binary.py", line 73, in launch_browser
    self._wait_until_connectable(timeout=timeout)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/firefox_binary.py", line 104, in _wait_until_connectable
    "The browser appears to have exited "
selenium.common.exceptions.WebDriverException: Message: The browser appears to have exited before we could connect. If you specified a log_file in the FirefoxBinary constructor, check it for details.
```

## Steps to reproduce -
Install latest version of below packages:
Selenium: 3.13.0
Firefox: 60.1.0-esr
geckodriver: 0.21.0
debian: 9

The python code:

```
from selenium import webdriver
from selenium.webdriver.firefox.firefox_binary import FirefoxBinary

binary = FirefoxBinary('/root/firefox/firefox-bin')
driver = webdriver.Firefox(firefox_binary=binary)

driver.get('http://seleniumhq.org/')

print driver.title

driver.quit()
```

Returns error below:

`selenium.common.exceptions.WebDriverException: Message: Process unexpectedly closed with status 255`

And the code below:

```
from selenium import webdriver
from selenium.webdriver.firefox.firefox_binary import FirefoxBinary

capabilities = webdriver.DesiredCapabilities().FIREFOX
capabilities["marionette"] = False

binary = FirefoxBinary('/root/firefox/firefox-bin')
driver = webdriver.Firefox(firefox_binary=binary, capabilities=capabilities)

driver.get('http://seleniumhq.org/')

print driver.title

driver.quit()
```

Returns error below:

```
Traceback (most recent call last):
  File "selen.py", line 8, in <module>
    driver = webdriver.Firefox(firefox_binary=binary, capabilities=capabilities)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/webdriver.py", line 187, in __init__
    self.binary, timeout)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/extension_connection.py", line 52, in __init__
    self.binary.launch_browser(self.profile, timeout=timeout)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/firefox_binary.py", line 73, in launch_browser
    self._wait_until_connectable(timeout=timeout)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/firefox_binary.py", line 104, in _wait_until_connectable
    "The browser appears to have exited "
selenium.common.exceptions.WebDriverException: Message: The browser appears to have exited before we could connect. If you specified a log_file in the FirefoxBinary constructor, check it for details.
```
I even ran this code with `headless` option, it didn't work either and gave the above error.

What is the issue? how should I solve this problem? Is this because of version mismatch between packages?

This issue has been asked on `Selenium` before: [Selenium](https://github.com/SeleniumHQ/selenium/issues/6194#issuecomment-407053313)

**Comment by alirezastack** [comment]
I have tried to provide the `Selenium` with `geckodriver` path:

```
            options = Options()
            options.add_argument("--headless")
            options.add_argument("--window-size=1920,1080")

            logging.info("Instantiating firefox driver...")
            self.driver = webdriver.Firefox(executable_path='/usr/bin/geckodriver', options=options)  # type:Firefox
            self.driver.implicitly_wait(3)
```

**Comment by andreastt** [comment]
Could you please attach a [trace-level log] from geckodriver? Read more about reporting actionable bugs in our [contribution guidelines].

[trace-level log]: https://searchfox.org/mozilla-central/source/testing/geckodriver/doc/TraceLogs.md
[contribution guidelines]: https://searchfox.org/mozilla-central/source/testing/geckodriver/CONTRIBUTING.md#reporting-bugs

**Comment by alirezastack** [comment]
@andreastt thank you for the link. I have set the log level of `geckodriver` as mentioned in the link a new file created with the name of `geckodriver.log`. All the logs that appear in the log file is:

```
1532355142660   geckodriver     INFO    geckodriver 0.18.0
1532355142672   geckodriver     INFO    Listening on 127.0.0.1:59477
1532355205313   geckodriver     INFO    geckodriver 0.18.0
1532355205326   geckodriver     INFO    Listening on 127.0.0.1:55009
```

And getting error of:

`SessionNotCreatedException: Message: Unable to find a matching set of capabilities`
