### ISSUE TITLE
Driver connection lost midway through test script

### ISSUE THREAD

**Issue by ranjitiyer** [mozilla/geckodriver#1339]
## System

* Version: 0.21.0
* Platform: MacOS Darwin Kernel Version 16.7.0
* Firefox: 61.0.1 (64-bit)
* Selenium: selenium==3.13.0 

## Testcase
Here's my script (imports elided)

```
 # Options
options=Options()
options.headless = True
 
# Profile
profile = webdriver.FirefoxProfile()
profile.accept_untrusted_certs = True
 
caps = webdriver.DesiredCapabilities.FIREFOX
caps["marionette"] = True
binary = FirefoxBinary(r'/Applications/Firefox.app/Contents/MacOS/firefox',log_file=open('/var/lib/jupyter/home/firefox.log', 'w'))
 
driver = webdriver.Firefox(firefox_binary=binary,options=options,firefox_profile=profile,capabilities=caps)
driver.set_page_load_timeout(60)
driver.get('https://localhost:9443/hub/login')
 
# login
try:
        username = driver.find_element_by_id('username_input')
        password = driver.find_element_by_id('password_input')
        submit = driver.find_element_by_id('login_submit')
        username.send_keys(<user>)
        password.send_keys(****)
        submit.click()
except Exception as e: 
        print(driver.page_source)
        sys.exit(1)
 
# Create Python 3 Notebook
try:
    new_group = driver.find_element_by_id('new-buttons')
    new_group.click()
 
    python3_nb = driver.find_element_by_css_selector('a[title="Create a new notebook with Python 3"]')
    python3_nb.click()
except Exception as e:
    print(driver.page_source)
    sys.exit(1)
 
# Switch to new tab
driver.switch_to_window(driver.window_handles[1])
 
# wait until notebook panel is visible
wait = WebDriverWait(driver, 30)
try:
    wait.until(EC.presence_of_element_located((By.CSS_SELECTOR, 'textarea')))
 
    # Execute some Python code
    textarea = driver.find_element_by_css_selector('textarea')
    textarea.send_keys("import os")
    textarea.send_keys(Keys.RETURN)
    textarea.send_keys("os.getenv('HOME')")
    run = driver.find_element_by_css_selector('span.toolbar-btn-label')
    run.click()
 
    sleep(5)

    # grab output
    output=driver.find_element_by_class_name('output_subarea')
    assert output.text == '\'/home/jovyan\''
    print("Done")
finally:
    driver.quit()
```

I'm consistently encountering a Connection reset error on line ```output=driver.find_element_by_class_name('output_subarea')```, towards the end of the program. All interactions before this line are working fine and as expected.

## Stacktrace

```
07:34 PM ~/work/temp/selenium-python/firefox $ python test_python3_firefox.py
Traceback (most recent call last):
  File "test_python3_firefox.py", line 75, in <module>
    output=driver.find_element_by_class_name('output_subarea')
  File "/Users/ranjiti/miniconda3/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 563, in find_element_by_class_name
    return self.find_element(by=By.CLASS_NAME, value=name)
  File "/Users/ranjiti/miniconda3/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 966, in find_element
    'value': value})['value']
  File "/Users/ranjiti/miniconda3/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 318, in execute
    response = self.command_executor.execute(driver_command, params)
  File "/Users/ranjiti/miniconda3/lib/python3.6/site-packages/selenium/webdriver/remote/remote_connection.py", line 472, in execute
    return self._request(command_info[0], url, body=data)
  File "/Users/ranjiti/miniconda3/lib/python3.6/site-packages/selenium/webdriver/remote/remote_connection.py", line 496, in _request
    resp = self._conn.getresponse()
  File "/Users/ranjiti/miniconda3/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/Users/ranjiti/miniconda3/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/Users/ranjiti/miniconda3/lib/python3.6/http/client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/Users/ranjiti/miniconda3/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 54] Connection reset by peer
```

## Trace-level log
[Link](https://pastebin.com/HK3S6mae)

Thanks for your help :)

**Comment by whimboo** [comment]
It's your `sleep(5)` call here which will cause a disconnect due to issue #1304. Marking as dupe.

Note, never use sleep but instead actively query for the element, and wait until it is available.
