### ISSUE TITLE
Click on div not executed if only partially scrolled into view

### ISSUE THREAD

**Issue by mfugmann** [mozilla/geckodriver#1346]
## System

* Version: 0.21.0
* Platform: Windows 10
* Firefox: 60.1.0esr (64 bit)
* Selenium: 3.13.0

## Description

Clicking a div does not work, if only a small part of it is scrolled into viewport. 
(If the div is completely scrolled out of the viewport, it will be scrolled into view automatically, so everything is fine then.)

## Testcase
```
<html>
<head>
    <title>selenium example</title>
</head>
<body>
<div id="spacer">&nbsp;</div>
<div id="dummy" style="width: 20px; height: 20px; background-color: red;" onclick="alert('clicked');"></div>
<script type="application/javascript">
document.getElementById('spacer').style.height = (window.innerHeight - 9) + 'px';
</script>
</body>
</html>
```

### Java-Code:
```
System.setProperty("webdriver.gecko.driver", "C:\\seleniumdriver\\geckodriver\\geckodriver-v0.21.0.exe");
FirefoxOptions options = new FirefoxOptions();
options.setBinary("C:\\Program Files\\Mozilla Firefox 60 esr\\firefox.exe");
WebDriver driver = new FirefoxDriver(options);
driver.navigate().to("http://127.0.0.1/user/seleniumExample.html");

// click not executed, if only a minmal area of it is scrolled into viewport
driver.findElement(By.id("dummy")).click();
driver.switchTo().alert().accept();
```

## Stacktrace

```
Exception in thread "main" org.openqa.selenium.NoAlertPresentException: No modal dialog is currently open
Build info: version: '3.13.0', revision: '2f0d292', time: '2018-06-25T15:24:21.231Z'
System info: host: 'xxx', ip: '127.0.0.1', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_172'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities {acceptInsecureCerts: true, browserName: firefox, browserVersion: 60.1.0, javascriptEnabled: true, moz:accessibilityChecks: false, moz:headless: false, moz:processID: 13628, moz:profile: C:\Users\myUser\AppData\L..., moz:useNonSpecCompliantPointerOrigin: false, moz:webdriverClick: true, pageLoadStrategy: normal, platform: XP, platformName: XP, platformVersion: 10.0, rotatable: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}}
Session ID: 10eb0865-4a12-4e1c-9717-9bea0b11c321
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:187)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:122)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:49)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:548)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:605)
	at org.openqa.selenium.remote.RemoteWebDriver$RemoteTargetLocator.alert(RemoteWebDriver.java:928)
	at de.interexa.selenium.ScrollTest.main(ScrollTest.java:25)
```

## Trace-level log
```
1533727084215	geckodriver	INFO	geckodriver 0.21.0
1533727084229	geckodriver	INFO	Listening on 127.0.0.1:12585
1533727084943	mozrunner::runner	INFO	Running command: "C:/Program Files/Mozilla Firefox 60 esr/firefox.exe" "-marionette" "-foreground" "-no-remote" "-profile" "C:\\Users\\myUser\\AppData\\Local\\Temp\\rust_mozprofile.HZQ3pUfUymzU"
1533727084945	geckodriver::marionette	DEBUG	Waiting 60s to connect to browser on 127.0.0.1:55579
1533727085800	Marionette	DEBUG	Received observer notification profile-after-change
Unable to read VR Path Registry from C:\Users\myUser\AppData\Local\openvr\openvrpaths.vrpath
1533727085952	Marionette	DEBUG	Received observer notification command-line-startup
1533727085953	Marionette	DEBUG	Received observer notification nsPref:changed
Unable to read VR Path Registry from C:\Users\myUser\AppData\Local\openvr\openvrpaths.vrpath
Unable to read VR Path Registry from C:\Users\myUser\AppData\Local\openvr\openvrpaths.vrpath
Unable to read VR Path Registry from C:\Users\myUser\AppData\Local\openvr\openvrpaths.vrpath
1533727087221	Marionette	DEBUG	Received observer notification sessionstore-windows-restored
1533727087341	Marionette	DEBUG	Setting recommended pref apz.content_response_timeout to 60000
1533727087342	Marionette	DEBUG	Setting recommended pref browser.download.panel.shown to true
1533727087342	Marionette	DEBUG	Setting recommended pref browser.EULA.override to true
1533727087343	Marionette	DEBUG	Setting recommended pref browser.offline to false
1533727087343	Marionette	DEBUG	Setting recommended pref browser.pagethumbnails.capturing_disabled to true
1533727087343	Marionette	DEBUG	Setting recommended pref browser.search.update to false
1533727087343	Marionette	DEBUG	Setting recommended pref toolkit.cosmeticAnimations.enabled to false
1533727087344	Marionette	DEBUG	Setting recommended pref browser.tabs.disableBackgroundZombification to false
1533727087344	Marionette	DEBUG	Setting recommended pref browser.tabs.warnOnCloseOtherTabs to false
1533727087345	Marionette	DEBUG	Setting recommended pref browser.tabs.warnOnOpen to false
1533727087345	Marionette	DEBUG	Setting recommended pref browser.usedOnWindows10.introURL to 
1533727087345	Marionette	DEBUG	Setting recommended pref browser.urlbar.suggest.searches to false
1533727087345	Marionette	DEBUG	Setting recommended pref browser.urlbar.userMadeSearchSuggestionsChoice to true
1533727087346	Marionette	DEBUG	Setting recommended pref datareporting.policy.dataSubmissionPolicyAccepted to false
1533727087346	Marionette	DEBUG	Setting recommended pref dom.disable_open_during_load to false
1533727087346	Marionette	DEBUG	Setting recommended pref dom.file.createInChild to true
1533727087347	Marionette	DEBUG	Setting recommended pref dom.max_chrome_script_run_time to 0
1533727087347	Marionette	DEBUG	Setting recommended pref dom.max_script_run_time to 0
1533727087347	Marionette	DEBUG	Setting recommended pref extensions.getAddons.cache.enabled to false
1533727087347	Marionette	DEBUG	Setting recommended pref extensions.shield-recipe-client.api_url to 
1533727087347	Marionette	DEBUG	Setting recommended pref extensions.webservice.discoverURL to http://%(server)s/dummy/discoveryURL
1533727087347	Marionette	DEBUG	Setting recommended pref network.http.prompt-temp-redirect to false
1533727087347	Marionette	DEBUG	Setting recommended pref network.http.speculative-parallel-limit to 0
1533727087347	Marionette	DEBUG	Setting recommended pref security.fileuri.strict_origin_policy to false
1533727087348	Marionette	DEBUG	Setting recommended pref security.notification_enable_delay to 0
1533727087348	Marionette	DEBUG	Setting recommended pref signon.autofillForms to false
1533727087348	Marionette	DEBUG	Setting recommended pref signon.rememberSignons to false
1533727087401	Marionette	DEBUG	New connections are accepted
1533727087401	Marionette	INFO	Listening on port 55579
1533727087649	geckodriver::marionette	DEBUG	Connected to Marionette on 127.0.0.1:55579
1533727087651	Marionette	DEBUG	Accepted connection 0 from 127.0.0.1:55589
Unable to read VR Path Registry from C:\Users\myUser\AppData\Local\openvr\openvrpaths.vrpath
1533727087660	Marionette	TRACE	0 -> [0,1,"WebDriver:NewSession",{"acceptInsecureCerts":true,"browserName":"firefox","capabilities":{"desiredCapabilities":{"acceptInsecureCerts":true,"browserName":"firefox"}}}]
1533727087660	Marionette	WARN	TLS certificate errors will be ignored for this session
1533727087694	Marionette	DEBUG	Register listener.js for window 4294967297
1533727087701	Marionette	TRACE	0 <- [1,1,null,{"sessionId":"10eb0865-4a12-4e1c-9717-9bea0b11c321","capabilities":{"browserName":"firefox","browserVersion":"60.1. ... AppData\\Local\\Temp\\rust_mozprofile.HZQ3pUfUymzU","moz:useNonSpecCompliantPointerOrigin":false,"moz:webdriverClick":true}}]
1533727087704	webdriver::server	DEBUG	<- 200 OK {"value": {"sessionId":"10eb0865-4a12-4e1c-9717-9bea0b11c321","capabilities":{"acceptInsecureCerts":true,"browserName":"firefox","browserVersion":"60.1.0","moz:accessibilityChecks":false,"moz:headless":false,"moz:processID":13628,"moz:profile":"C:\\Users\\myUser\\AppData\\Local\\Temp\\rust_mozprofile.HZQ3pUfUymzU","moz:useNonSpecCompliantPointerOrigin":false,"moz:webdriverClick":true,"pageLoadStrategy":"normal","platformName":"windows_nt","platformVersion":"10.0","rotatable":false,"timeouts":{"implicit":0,"pageLoad":300000,"script":30000}}}}
Aug 08, 2018 1:18:07 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFORMATION: Detected dialect: W3C
1533727087758	webdriver::server	DEBUG	-> POST /session/10eb0865-4a12-4e1c-9717-9bea0b11c321/url {
  "url": "http:\u002f\u002f127.0.0.1\u002fuser\u002fseleniumExample.html"
}
1533727087762	Marionette	TRACE	0 -> [0,2,"WebDriver:Navigate",{"url":"http://127.0.0.1/user/seleniumExample.html"}]
1533727087771	Marionette	DEBUG	Received DOM event beforeunload for about:blank
1533727087801	Marionette	DEBUG	Received DOM event pagehide for about:blank
1533727087811	Marionette	DEBUG	Received DOM event DOMContentLoaded for http://127.0.0.1/user/seleniumExample.html
1533727087846	Marionette	DEBUG	Received DOM event pageshow for http://127.0.0.1/user/seleniumExample.html
1533727087852	Marionette	TRACE	0 <- [1,2,null,{}]
1533727087875	webdriver::server	DEBUG	<- 200 OK {"value": null}
1533727087894	webdriver::server	DEBUG	-> POST /session/10eb0865-4a12-4e1c-9717-9bea0b11c321/element {
  "value": "#dummy",
  "using": "css selector"
}
1533727087901	Marionette	TRACE	0 -> [0,3,"WebDriver:FindElement",{"using":"css selector","value":"#dummy"}]
1533727087905	Marionette	TRACE	0 <- [1,3,null,{"value":{"element-6066-11e4-a52e-4f735466cecf":"57e1951d-a264-410b-8404-a6e40e9080a5","ELEMENT":"57e1951d-a264-410b-8404-a6e40e9080a5"}}]
1533727087905	webdriver::server	DEBUG	<- 200 OK {"value":{"element-6066-11e4-a52e-4f735466cecf":"57e1951d-a264-410b-8404-a6e40e9080a5"}}
1533727087914	webdriver::server	DEBUG	-> POST /session/10eb0865-4a12-4e1c-9717-9bea0b11c321/element/57e1951d-a264-410b-8404-a6e40e9080a5/click {
  "id": "57e1951d-a264-410b-8404-a6e40e9080a5"
}
1533727087920	Marionette	TRACE	0 -> [0,4,"WebDriver:ElementClick",{"id":"57e1951d-a264-410b-8404-a6e40e9080a5"}]
1533727088655	Marionette	DEBUG	Canceled page load listener because no navigation has been detected
1533727088657	Marionette	TRACE	0 <- [1,4,null,{}]
1533727088657	webdriver::server	DEBUG	<- 200 OK {"value": null}
1533727088663	webdriver::server	DEBUG	-> GET /session/10eb0865-4a12-4e1c-9717-9bea0b11c321/alert/text 
1533727088665	Marionette	TRACE	0 -> [0,5,"WebDriver:GetAlertText",{}]
1533727088666	Marionette	TRACE	0 <- [1,5,{"error":"no such alert","message":"No modal dialog is currently open","stacktrace":"WebDriverError@chrome://marionette/ ... et@chrome://marionette/content/server.js:241:8\n_onJSONObjectReady/<@chrome://marionette/content/transport.js:500:9\n"},null]
1533727088667	webdriver::server	DEBUG	<- 404 Not Found {"value":{"error":"no such alert","message":"No modal dialog is currently open","stacktrace":"WebDriverError@chrome://marionette/content/error.js:178:5\nNoSuchAlertError@chrome://marionette/content/error.js:423:5\nGeckoDriver.prototype._checkIfAlertIsPresent@chrome://marionette/content/driver.js:3197:11\nGeckoDriver.prototype.getTextFromDialog@chrome://marionette/content/driver.js:3160:3\ndespatch@chrome://marionette/content/server.js:293:20\nexecute@chrome://marionette/content/server.js:267:11\nonPacket/<@chrome://marionette/content/server.js:242:15\nonPacket@chrome://marionette/content/server.js:241:8\n_onJSONObjectReady/<@chrome://marionette/content/transport.js:500:9\n"}}
```

**Comment by whimboo** [comment]
@mfugmann can you please attach a log which shows the problem? The above one shows a successful `click` command.

**Comment by mfugmann** [comment]
@whimboo 
Unfortunately the logfile belongs to the same run.
The click just seems to be executed but isn't. If the div is slightly scrolled up or down, the click is either executed directly or the div is scrolled into view and the click is executed afterwards.
If only some pixels of the divs upper part are scrolled into viewport the click  seems to be executed but onclick is not triggered.

**Comment by whimboo** [comment]
Ok, I can reproduce and filed https://bugzilla.mozilla.org/show_bug.cgi?id=1493115.
