### ISSUE TITLE
Cannot pause for fractions of seconds

### ISSUE THREAD

**Issue by Herst** [mozilla/geckodriver#1355]
Unlike with `chromedriver` I cannot use fractional seconds for `ActionChains.pause()` in Selenium for Python and I'm told that "_Parameter 'duration' was not a positive integer_".

---

## System

* Version: 0.21.0
* Platform: Linux
* Firefox: 61
* Selenium: 3.14

## Testcase

~~~py
from selenium.webdriver import Firefox
from selenium.webdriver.common.action_chains import ActionChains
import time
import base64

driver = Firefox()
u = base64.b64encode(b"""<!DOCTYPE html>
    <input type="button">
    <script>
        var start;
        b=document.querySelector("input");
        b.addEventListener("mousedown", function () {start = performance.now()});
        b.addEventListener("mouseup", function () {b.value = performance.now() - start});
    </script>
""")
driver.get((b"data:text/html;base64," + u).decode())
btn = driver.find_element_by_css_selector("input")
ActionChains(driver) \
    .click_and_hold(btn) \
    .pause(0.5) \
    .release(btn) \
    .perform()
print(driver.page_source)
driver.quit()
~~~

## Stacktrace

~~~
Traceback (most recent call last):                                                                                                            
  File "test.py", line 21, in <module>                                                                                                        
    .release(btn) \                                                                                                                           
  File "/lib/python3.6/site-packages/selenium/webdriver/common/action_chains.py", line 80, in perfor
    self.w3c_actions.perform()
  File "/lib/python3.6/site-packages/selenium/webdriver/common/actions/action_builder.py", line 76, 
    self.driver.execute(Command.W3C_ACTIONS, enc)
  File "/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 320, in execute
    self.error_handler.check_response(response)
  File "/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.InvalidArgumentException: Message: Parameter 'duration' was not a positive integer
~~~

## Trace-level log

~~~
1534438214970	geckodriver	INFO	geckodriver 0.21.0
1534438214973	geckodriver	INFO	Listening on 127.0.0.1:50999
1534438215980	mozrunner::runner	INFO	Running command: "/usr/bin/firefox" "-marionette" "-headless" "-foreground" "-no-remote" "-profile" "/tmp/rust_mozprofile.EUbgzg13bdwp"
*** You are running in headless mode.
1534438221933	Marionette	INFO	Listening on port 38189
1534438221996	Marionette	WARN	TLS certificate errors will be ignored for this session
[Parent 27623, Gecko_IOThread] WARNING: pipe error (54): Connection reset by peer: file /home/abuild/rpmbuild/BUILD/firefox-61.0.2/ipc/chromium/src/chrome/common/ipc_channel_posix.cc, line 353
*** UTM:SVC TimerManager:registerTimer called after profile-before-change notification. Ignoring timer registration for id: telemetry_modules_ping
1534438241868	geckodriver	INFO	geckodriver 0.21.0
1534438241871	geckodriver	INFO	Listening on 127.0.0.1:38825
1534438242882	mozrunner::runner	INFO	Running command: "/usr/bin/firefox" "-marionette" "-foreground" "-no-remote" "-profile" "/tmp/rust_mozprofile.yUZO1MSVoAMv"
1534438249045	Marionette	INFO	Listening on port 37875
1534438249095	Marionette	WARN	TLS certificate errors will be ignored for this session
[Parent 27885, Gecko_IOThread] WARNING: pipe error (51): Connection reset by peer: file /home/abuild/rpmbuild/BUILD/firefox-61.0.2/ipc/chromium/src/chrome/common/ipc_channel_posix.cc, line 353
*** UTM:SVC TimerManager:registerTimer called after profile-before-change notification. Ignoring timer registration for id: telemetry_modules_ping
1534438539106	geckodriver	INFO	geckodriver 0.21.0
1534438539110	geckodriver	INFO	Listening on 127.0.0.1:54539
1534438540115	mozrunner::runner	INFO	Running command: "/usr/bin/firefox" "-marionette" "-foreground" "-no-remote" "-profile" "/tmp/rust_mozprofile.miPJsrQJJK1A"
1534438547042	Marionette	INFO	Listening on port 43681
1534438547136	Marionette	WARN	TLS certificate errors will be ignored for this session
[Parent 28997, Gecko_IOThread] WARNING: pipe error (58): Connection reset by peer: file /home/abuild/rpmbuild/BUILD/firefox-61.0.2/ipc/chromium/src/chrome/common/ipc_channel_posix.cc, line 353
*** UTM:SVC TimerManager:registerTimer called after profile-before-change notification. Ignoring timer registration for id: telemetry_modules_ping
1534438563754	geckodriver	INFO	geckodriver 0.21.0
1534438563759	geckodriver	INFO	Listening on 127.0.0.1:42749
1534438564761	mozrunner::runner	INFO	Running command: "/usr/bin/firefox" "-marionette" "-foreground" "-no-remote" "-profile" "/tmp/rust_mozprofile.VgUc1wyHgNa2"
1534438571816	Marionette	INFO	Listening on port 46499
1534438571874	Marionette	WARN	TLS certificate errors will be ignored for this session
[Parent 29266, Gecko_IOThread] WARNING: pipe error (51): Connection reset by peer: file /home/abuild/rpmbuild/BUILD/firefox-61.0.2/ipc/chromium/src/chrome/common/ipc_channel_posix.cc, line 353
*** UTM:SVC TimerManager:registerTimer called after profile-before-change notification. Ignoring timer registration for id: telemetry_modules_ping
1534438635815	geckodriver	INFO	geckodriver 0.21.0
1534438635818	geckodriver	INFO	Listening on 127.0.0.1:37937
1534438636824	mozrunner::runner	INFO	Running command: "/usr/bin/firefox" "-marionette" "-foreground" "-no-remote" "-profile" "/tmp/rust_mozprofile.A3tRUs5flZp6"
1534438643250	Marionette	INFO	Listening on port 42399
1534438643337	Marionette	WARN	TLS certificate errors will be ignored for this session
[Parent 29729, Gecko_IOThread] WARNING: pipe error (51): Connection reset by peer: file /home/abuild/rpmbuild/BUILD/firefox-61.0.2/ipc/chromium/src/chrome/common/ipc_channel_posix.cc, line 353
1534438766053	geckodriver	INFO	geckodriver 0.21.0
1534438766056	geckodriver	INFO	Listening on 127.0.0.1:53989
1534438767059	mozrunner::runner	INFO	Running command: "/usr/bin/firefox" "-marionette" "-foreground" "-no-remote" "-profile" "/tmp/rust_mozprofile.MXZOtWVWSqU5"
1534438773128	Marionette	INFO	Listening on port 46181
1534438773178	Marionette	WARN	TLS certificate errors will be ignored for this session
[Parent 30155, Gecko_IOThread] WARNING: pipe error (51): Connection reset by peer: file /home/abuild/rpmbuild/BUILD/firefox-61.0.2/ipc/chromium/src/chrome/common/ipc_channel_posix.cc, line 353
*** UTM:SVC TimerManager:registerTimer called after profile-before-change notification. Ignoring timer registration for id: telemetry_modules_ping
1534438782706	geckodriver	INFO	geckodriver 0.21.0
1534438782710	geckodriver	INFO	Listening on 127.0.0.1:43973
1534438783720	mozrunner::runner	INFO	Running command: "/usr/bin/firefox" "-marionette" "-foreground" "-no-remote" "-profile" "/tmp/rust_mozprofile.Dg9xxyUgZ4lK"
1534438789869	Marionette	INFO	Listening on port 44035
1534438789949	Marionette	WARN	TLS certificate errors will be ignored for this session
[Parent 30414, Gecko_IOThread] WARNING: pipe error (51): Connection reset by peer: file /home/abuild/rpmbuild/BUILD/firefox-61.0.2/ipc/chromium/src/chrome/common/ipc_channel_posix.cc, line 353
*** UTM:SVC TimerManager:registerTimer called after profile-before-change notification. Ignoring timer registration for id: telemetry_modules_ping
1534438855329	geckodriver	INFO	geckodriver 0.21.0
1534438855332	geckodriver	INFO	Listening on 127.0.0.1:50825
1534438856335	mozrunner::runner	INFO	Running command: "/usr/bin/firefox" "-marionette" "-foreground" "-no-remote" "-profile" "/tmp/rust_mozprofile.TAv8UM5xJ9o0"
1534438862496	Marionette	INFO	Listening on port 33363
1534438862553	Marionette	WARN	TLS certificate errors will be ignored for this session
[Parent 30774, Gecko_IOThread] WARNING: pipe error (51): Connection reset by peer: file /home/abuild/rpmbuild/BUILD/firefox-61.0.2/ipc/chromium/src/chrome/common/ipc_channel_posix.cc, line 353
*** UTM:SVC TimerManager:registerTimer called after profile-before-change notification. Ignoring timer registration for id: telemetry_modules_ping
1534438969242	geckodriver	INFO	geckodriver 0.21.0
1534438969244	geckodriver	INFO	Listening on 127.0.0.1:38819
1534438970254	mozrunner::runner	INFO	Running command: "/usr/bin/firefox" "-marionette" "-foreground" "-no-remote" "-profile" "/tmp/rust_mozprofile.fIRuM91De7ze"
1534438976501	Marionette	INFO	Listening on port 41751
1534438976573	Marionette	WARN	TLS certificate errors will be ignored for this session
1534439076547	geckodriver	INFO	geckodriver 0.21.0
1534439076549	geckodriver	INFO	Listening on 127.0.0.1:51857
1534439077557	mozrunner::runner	INFO	Running command: "/usr/bin/firefox" "-marionette" "-foreground" "-no-remote" "-profile" "/tmp/rust_mozprofile.UdmFKdYq5jIj"
1534439083607	Marionette	INFO	Listening on port 40763
1534439083672	Marionette	WARN	TLS certificate errors will be ignored for this session
[Parent 31544, Gecko_IOThread] WARNING: pipe error (67): Connection reset by peer: file /home/abuild/rpmbuild/BUILD/firefox-61.0.2/ipc/chromium/src/chrome/common/ipc_channel_posix.cc, line 353
1534439639403	geckodriver	INFO	geckodriver 0.21.0
1534439639407	geckodriver	INFO	Listening on 127.0.0.1:41655
1534439640418	mozrunner::runner	INFO	Running command: "/usr/bin/firefox" "-marionette" "-foreground" "-no-remote" "-profile" "/tmp/rust_mozprofile.o1sbuDgdIxPo"
1534439646483	Marionette	INFO	Listening on port 32809
1534439646563	Marionette	WARN	TLS certificate errors will be ignored for this session
[Parent 32256, Gecko_IOThread] WARNING: pipe error (57): Connection reset by peer: file /home/abuild/rpmbuild/BUILD/firefox-61.0.2/ipc/chromium/src/chrome/common/ipc_channel_posix.cc, line 353
*** UTM:SVC TimerManager:registerTimer called after profile-before-change notification. Ignoring timer registration for id: telemetry_modules_ping
[Parent 31196, Gecko_IOThread] WARNING: pipe error (51): Connection reset by peer: file /home/abuild/rpmbuild/BUILD/firefox-61.0.2/ipc/chromium/src/chrome/common/ipc_channel_posix.cc, line 353
1534439766362	geckodriver	INFO	geckodriver 0.21.0
1534439766365	geckodriver	INFO	Listening on 127.0.0.1:53457
1534439767368	mozrunner::runner	INFO	Running command: "/usr/bin/firefox" "-marionette" "-foreground" "-no-remote" "-profile" "/tmp/rust_mozprofile.Ul6349aEG7Gr"
1534439773538	Marionette	INFO	Listening on port 40067
1534439773587	Marionette	WARN	TLS certificate errors will be ignored for this session
[Parent 32650, Gecko_IOThread] WARNING: pipe error (51): Connection reset by peer: file /home/abuild/rpmbuild/BUILD/firefox-61.0.2/ipc/chromium/src/chrome/common/ipc_channel_posix.cc, line 353
*** UTM:SVC TimerManager:registerTimer called after profile-before-change notification. Ignoring timer registration for id: telemetry_modules_ping
1534440096572	geckodriver	INFO	geckodriver 0.21.0
1534440096575	geckodriver	INFO	Listening on 127.0.0.1:48425
1534440097585	mozrunner::runner	INFO	Running command: "/usr/bin/firefox" "-marionette" "-foreground" "-no-remote" "-profile" "/tmp/rust_mozprofile.HVXleBv8dDkZ"
1534440103656	Marionette	INFO	Listening on port 45921
1534440103701	Marionette	WARN	TLS certificate errors will be ignored for this session
[Parent 687, Gecko_IOThread] WARNING: pipe error (70): Connection reset by peer: file /home/abuild/rpmbuild/BUILD/firefox-61.0.2/ipc/chromium/src/chrome/common/ipc_channel_posix.cc, line 353
*** UTM:SVC TimerManager:registerTimer called after profile-before-change notification. Ignoring timer registration for id: telemetry_modules_ping
1534440127875	geckodriver	INFO	geckodriver 0.21.0
1534440127878	geckodriver	INFO	Listening on 127.0.0.1:49863
1534440128886	mozrunner::runner	INFO	Running command: "/usr/bin/firefox" "-marionette" "-foreground" "-no-remote" "-profile" "/tmp/rust_mozprofile.lqrAIDu2ykzc"
1534440135101	Marionette	INFO	Listening on port 44605
1534440135204	Marionette	WARN	TLS certificate errors will be ignored for this session
[Parent 1002, Gecko_IOThread] WARNING: pipe error (57): Connection reset by peer: file /home/abuild/rpmbuild/BUILD/firefox-61.0.2/ipc/chromium/src/chrome/common/ipc_channel_posix.cc, line 353
*** UTM:SVC TimerManager:registerTimer called after profile-before-change notification. Ignoring timer registration for id: telemetry_modules_ping
1534440150288	geckodriver	INFO	geckodriver 0.21.0
1534440150292	geckodriver	INFO	Listening on 127.0.0.1:56139
1534440151302	mozrunner::runner	INFO	Running command: "/usr/bin/firefox" "-marionette" "-foreground" "-no-remote" "-profile" "/tmp/rust_mozprofile.pnDQICaDqrKV"
1534440157553	Marionette	INFO	Listening on port 36075
1534440157616	Marionette	WARN	TLS certificate errors will be ignored for this session
[Parent 1327, Gecko_IOThread] WARNING: pipe error (57): Connection reset by peer: file /home/abuild/rpmbuild/BUILD/firefox-61.0.2/ipc/chromium/src/chrome/common/ipc_channel_posix.cc, line 353
*** UTM:SVC TimerManager:registerTimer called after profile-before-change notification. Ignoring timer registration for id: telemetry_modules_ping
1534440193555	geckodriver	INFO	geckodriver 0.21.0
1534440193558	geckodriver	INFO	Listening on 127.0.0.1:55875
1534440194570	mozrunner::runner	INFO	Running command: "/usr/bin/firefox" "-marionette" "-foreground" "-no-remote" "-profile" "/tmp/rust_mozprofile.OHMDe2Y6b7bE"
1534440200775	Marionette	INFO	Listening on port 45495
1534440200783	Marionette	WARN	TLS certificate errors will be ignored for this session
[Parent 1617, Gecko_IOThread] WARNING: pipe error (51): Connection reset by peer: file /home/abuild/rpmbuild/BUILD/firefox-61.0.2/ipc/chromium/src/chrome/common/ipc_channel_posix.cc, line 353
*** UTM:SVC TimerManager:registerTimer called after profile-before-change notification. Ignoring timer registration for id: telemetry_modules_ping
1534440550255	geckodriver	INFO	geckodriver 0.21.0
1534440550258	geckodriver	INFO	Listening on 127.0.0.1:48425
1534440551262	mozrunner::runner	INFO	Running command: "/usr/bin/firefox" "-marionette" "-foreground" "-no-remote" "-profile" "/tmp/rust_mozprofile.c7Z4WxxbC5Jh"
1534440557536	Marionette	INFO	Listening on port 34675
1534440557592	Marionette	WARN	TLS certificate errors will be ignored for this session
[Parent 2952, Gecko_IOThread] WARNING: pipe error (62): Connection reset by peer: file /home/abuild/rpmbuild/BUILD/firefox-61.0.2/ipc/chromium/src/chrome/common/ipc_channel_posix.cc, line 353
*** UTM:SVC TimerManager:registerTimer called after profile-before-change notification. Ignoring timer registration for id: telemetry_modules_ping
1534440572956	geckodriver	INFO	geckodriver 0.21.0
1534440572959	geckodriver	INFO	Listening on 127.0.0.1:45599
1534440573968	mozrunner::runner	INFO	Running command: "/usr/bin/firefox" "-marionette" "-foreground" "-no-remote" "-profile" "/tmp/rust_mozprofile.tiHo0DmUOfhQ"
1534440580095	Marionette	INFO	Listening on port 42637
1534440580193	Marionette	WARN	TLS certificate errors will be ignored for this session
[Parent 3339, Gecko_IOThread] WARNING: pipe error (60): Connection reset by peer: file /home/abuild/rpmbuild/BUILD/firefox-61.0.2/ipc/chromium/src/chrome/common/ipc_channel_posix.cc, line 353
*** UTM:SVC TimerManager:registerTimer called after profile-before-change notification. Ignoring timer registration for id: telemetry_modules_ping
1534440625384	geckodriver	INFO	geckodriver 0.21.0
1534440625387	geckodriver	INFO	Listening on 127.0.0.1:46487
1534440626396	mozrunner::runner	INFO	Running command: "/usr/bin/firefox" "-marionette" "-foreground" "-no-remote" "-profile" "/tmp/rust_mozprofile.M828MoLbaR7r"
1534440632493	Marionette	INFO	Listening on port 43239
1534440632521	Marionette	WARN	TLS certificate errors will be ignored for this session
[Parent 3699, Gecko_IOThread] WARNING: pipe error (60): Connection reset by peer: file /home/abuild/rpmbuild/BUILD/firefox-61.0.2/ipc/chromium/src/chrome/common/ipc_channel_posix.cc, line 353
*** UTM:SVC TimerManager:registerTimer called after profile-before-change notification. Ignoring timer registration for id: telemetry_modules_ping
1534440699173	geckodriver	INFO	geckodriver 0.21.0
1534440699176	geckodriver	INFO	Listening on 127.0.0.1:57061
1534440700189	mozrunner::runner	INFO	Running command: "/usr/bin/firefox" "-marionette" "-foreground" "-no-remote" "-profile" "/tmp/rust_mozprofile.Pef8re678X1H"
1534440706433	Marionette	INFO	Listening on port 35943
1534440706525	Marionette	WARN	TLS certificate errors will be ignored for this session
[Parent 4038, Gecko_IOThread] WARNING: pipe error (60): Connection reset by peer: file /home/abuild/rpmbuild/BUILD/firefox-61.0.2/ipc/chromium/src/chrome/common/ipc_channel_posix.cc, line 353
*** UTM:SVC TimerManager:registerTimer called after profile-before-change notification. Ignoring timer registration for id: telemetry_modules_ping
1534440919291	geckodriver	INFO	geckodriver 0.21.0
1534440919294	geckodriver	INFO	Listening on 127.0.0.1:49637
1534440920306	mozrunner::runner	INFO	Running command: "/usr/bin/firefox" "-marionette" "-foreground" "-no-remote" "-profile" "/tmp/rust_mozprofile.e8nJjI2OGTPI"
1534440920308	geckodriver::marionette	DEBUG	Waiting 60s to connect to browser on 127.0.0.1:45093
1534440925613	Marionette	DEBUG	Received observer notification profile-after-change
1534440925661	Marionette	DEBUG	Received observer notification command-line-startup
1534440925661	Marionette	DEBUG	Received observer notification nsPref:changed
1534440926294	Marionette	DEBUG	Received observer notification sessionstore-windows-restored
1534440926384	Marionette	DEBUG	Setting recommended pref apz.content_response_timeout to 60000
1534440926384	Marionette	DEBUG	Setting recommended pref browser.download.panel.shown to true
1534440926384	Marionette	DEBUG	Setting recommended pref browser.pagethumbnails.capturing_disabled to true
1534440926384	Marionette	DEBUG	Setting recommended pref browser.search.update to false
1534440926384	Marionette	DEBUG	Setting recommended pref toolkit.cosmeticAnimations.enabled to false
1534440926384	Marionette	DEBUG	Setting recommended pref browser.tabs.disableBackgroundZombification to false
1534440926385	Marionette	DEBUG	Setting recommended pref browser.tabs.warnOnCloseOtherTabs to false
1534440926385	Marionette	DEBUG	Setting recommended pref browser.tabs.warnOnOpen to false
1534440926385	Marionette	DEBUG	Setting recommended pref browser.usedOnWindows10.introURL to 
1534440926385	Marionette	DEBUG	Setting recommended pref browser.urlbar.suggest.searches to false
1534440926385	Marionette	DEBUG	Setting recommended pref datareporting.policy.dataSubmissionPolicyAccepted to false
1534440926385	Marionette	DEBUG	Setting recommended pref dom.disable_beforeunload to true
1534440926386	Marionette	DEBUG	Setting recommended pref dom.disable_open_during_load to false
1534440926386	Marionette	DEBUG	Setting recommended pref dom.file.createInChild to true
1534440926386	Marionette	DEBUG	Setting recommended pref dom.max_chrome_script_run_time to 0
1534440926386	Marionette	DEBUG	Setting recommended pref dom.max_script_run_time to 0
1534440926386	Marionette	DEBUG	Setting recommended pref extensions.getAddons.cache.enabled to false
1534440926386	Marionette	DEBUG	Setting recommended pref extensions.webservice.discoverURL to http://%(server)s/dummy/discoveryURL
1534440926386	Marionette	DEBUG	Setting recommended pref network.http.prompt-temp-redirect to false
1534440926386	Marionette	DEBUG	Setting recommended pref network.http.speculative-parallel-limit to 0
1534440926386	Marionette	DEBUG	Setting recommended pref security.fileuri.strict_origin_policy to false
1534440926386	Marionette	DEBUG	Setting recommended pref security.notification_enable_delay to 0
1534440926386	Marionette	DEBUG	Setting recommended pref signon.autofillForms to false
1534440926386	Marionette	DEBUG	Setting recommended pref signon.rememberSignons to false
1534440926419	Marionette	DEBUG	New connections are accepted
1534440926419	Marionette	INFO	Listening on port 45093
1534440926517	geckodriver::marionette	DEBUG	Connected to Marionette on 127.0.0.1:45093
1534440926523	Marionette	DEBUG	Accepted connection 0 from 127.0.0.1:59968
1534440926525	Marionette	TRACE	0 -> [0,1,"WebDriver:NewSession",{"acceptInsecureCerts":true,"browserName":"firefox","capabilities":{"desiredCapabilities":{"acceptInsecureCerts":true,"browserName":"firefox"}}}]
1534440926526	Marionette	WARN	TLS certificate errors will be ignored for this session
1534440926551	Marionette	DEBUG	Register listener.js for window 2147483649
1534440926555	Marionette	TRACE	0 <- [1,1,null,{"sessionId":"ddda84af-7dda-4063-8971-aeba63184a81","capabilities":{"browserName":"firefox","browserVersion":"61.0. ... 8,"moz:profile":"/tmp/rust_mozprofile.e8nJjI2OGTPI","moz:useNonSpecCompliantPointerOrigin":false,"moz:webdriverClick":true}}]
1534440926556	webdriver::server	DEBUG	<- 200 OK {"value": {"sessionId":"ddda84af-7dda-4063-8971-aeba63184a81","capabilities":{"acceptInsecureCerts":true,"browserName":"firefox","browserVersion":"61.0.2","moz:accessibilityChecks":false,"moz:headless":false,"moz:processID":4748,"moz:profile":"/tmp/rust_mozprofile.e8nJjI2OGTPI","moz:useNonSpecCompliantPointerOrigin":false,"moz:webdriverClick":true,"pageLoadStrategy":"normal","platformName":"linux","platformVersion":"4.17.13-1-default","rotatable":false,"timeouts":{"implicit":0,"pageLoad":300000,"script":30000}}}}
1534440926557	webdriver::server	DEBUG	-> POST /session/ddda84af-7dda-4063-8971-aeba63184a81/url {"url": "data:text/html;base64,PCFET0NUWVBFIGh0bWw+CiAgICA8aW5wdXQgdHlwZT0iYnV0dG9uIj4KICAgIDxzY3JpcHQ+CiAgICAgICAgdmFyIHN0YXJ0OwogICAgICAgIGI9ZG9jdW1lbnQucXVlcnlTZWxlY3RvcigiaW5wdXQiKTsKICAgICAgICBiLmFkZEV2ZW50TGlzdGVuZXIoIm1vdXNlZG93biIsIGZ1bmN0aW9uICgpIHtzdGFydCA9IHBlcmZvcm1hbmNlLm5vdygpfSk7CiAgICAgICAgYi5hZGRFdmVudExpc3RlbmVyKCJtb3VzZXVwIiwgZnVuY3Rpb24gKCkge2IudmFsdWUgPSBwZXJmb3JtYW5jZS5ub3coKSAtIHN0YXJ0fSk7CiAgICA8L3NjcmlwdD4K"}
1534440926557	Marionette	TRACE	0 -> [0,2,"WebDriver:Navigate",{"url":"data:text/html;base64,PCFET0NUWVBFIGh0bWw+CiAgICA8aW5wdXQgdHlwZT0iYnV0dG9uIj4KICAgIDxzY3Jpc ... RFdmVudExpc3RlbmVyKCJtb3VzZXVwIiwgZnVuY3Rpb24gKCkge2IudmFsdWUgPSBwZXJmb3JtYW5jZS5ub3coKSAtIHN0YXJ0fSk7CiAgICA8L3NjcmlwdD4K"}]
1534440926561	Marionette	DEBUG	Received DOM event beforeunload for about:blank
1534440926563	Marionette	DEBUG	Received DOM event pagehide for about:blank
1534440926567	Marionette	DEBUG	Received DOM event DOMContentLoaded for data:text/html;base64,PCFET0NUWVBFIGh0bWw+CiAgICA8aW5wdXQgdHlwZT0iYnV0dG9uIj4KICAgIDxzY3JpcHQ+CiAgICAgICAgdmFyIHN0YXJ0OwogICA ... hZGRFdmVudExpc3RlbmVyKCJtb3VzZXVwIiwgZnVuY3Rpb24gKCkge2IudmFsdWUgPSBwZXJmb3JtYW5jZS5ub3coKSAtIHN0YXJ0fSk7CiAgICA8L3NjcmlwdD4K
1534440926598	Marionette	DEBUG	Received DOM event pageshow for data:text/html;base64,PCFET0NUWVBFIGh0bWw+CiAgICA8aW5wdXQgdHlwZT0iYnV0dG9uIj4KICAgIDxzY3JpcHQ+CiAgICAgICAgdmFyIHN0YXJ0OwogICA ... hZGRFdmVudExpc3RlbmVyKCJtb3VzZXVwIiwgZnVuY3Rpb24gKCkge2IudmFsdWUgPSBwZXJmb3JtYW5jZS5ub3coKSAtIHN0YXJ0fSk7CiAgICA8L3NjcmlwdD4K
1534440926604	Marionette	TRACE	0 <- [1,2,null,{}]
1534440926607	webdriver::server	DEBUG	<- 200 OK {"value": null}
1534440926608	webdriver::server	DEBUG	-> POST /session/ddda84af-7dda-4063-8971-aeba63184a81/element {"using": "css selector", "value": "input"}
1534440926610	Marionette	TRACE	0 -> [0,3,"WebDriver:FindElement",{"using":"css selector","value":"input"}]
1534440926619	Marionette	TRACE	0 <- [1,3,null,{"value":{"element-6066-11e4-a52e-4f735466cecf":"3c74849c-bb36-4489-b36a-3a42903866b6","ELEMENT":"3c74849c-bb36-4489-b36a-3a42903866b6"}}]
1534440926630	webdriver::server	DEBUG	<- 200 OK {"value":{"element-6066-11e4-a52e-4f735466cecf":"3c74849c-bb36-4489-b36a-3a42903866b6"}}
1534440926631	webdriver::server	DEBUG	-> POST /session/ddda84af-7dda-4063-8971-aeba63184a81/actions {"actions": [{"type": "pointer", "parameters": {"pointerType": "mouse"}, "id": "mouse", "actions": [{"type": "pointerMove", "duration": 250, "x": 0, "y": 0, "origin": {"element-6066-11e4-a52e-4f735466cecf": "3c74849c-bb36-4489-b36a-3a42903866b6"}}, {"type": "pointerDown", "duration": 0, "button": 0}, {"type": "pause", "duration": 500.0}, {"type": "pointerMove", "duration": 250, "x": 0, "y": 0, "origin": {"element-6066-11e4-a52e-4f735466cecf": "3c74849c-bb36-4489-b36a-3a42903866b6"}}, {"type": "pointerUp", "duration": 0, "button": 0}]}, {"type": "key", "id": "key", "actions": [{"type": "pause", "duration": 0}, {"type": "pause", "duration": 0}, {"type": "pause", "duration": 500.0}, {"type": "pause", "duration": 0}, {"type": "pause", "duration": 0}]}]}
1534440926631	webdriver::server	DEBUG	<- 400 Bad Request {"value":{"error":"invalid argument","message":"Parameter 'duration' was not a positive integer","stacktrace":""}}
1534440926644	Marionette	DEBUG	Closed connection 0
~~~

**Comment by andreastt** [comment]
The WebDriver standard does not allow the pause action to be specified in floating point. This is actually a bug in the Selenium client you’re using, which is passing `{"type": "pause", "duration": 500.0}`, which should be an integer.

See https://w3c.github.io/webdriver/#dfn-computing-the-tick-duration for more details.

An argument can also be made for the fact that chromedriver doesn’t respect the specification by allowing floating point input. I’ve filed https://bugzilla.mozilla.org/show_bug.cgi?id=1484157 to write a conformance test for this.
