### ISSUE TITLE
Unable to locate element by link text for application/xhtml+xml

### ISSUE THREAD

**Issue by jleyba** [mozilla/geckodriver#137]
Using Firefox 47.0.1 and geckodriver 0.8.0

```py
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from selenium.webdriver.firefox.webdriver import WebDriver

capabilities = DesiredCapabilities.FIREFOX.copy()
capabilities['marionette'] = True

driver = WebDriver(capabilities=capabilities)
driver.get('''
data:application/xhtml+xml,<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
  <head>
    <title>
      Title
    </title>
  </head>
  <body>
    <p>
     <a href="/foo">Foo</a>
    </p>
  </body>
</html>
''')

try:
  driver.find_element_by_link_text('Foo')
finally:
  driver.quit()
```

This fails with:

```
Traceback (most recent call last):
  File "xhtml.py", line 25, in <module>
    driver.find_element_by_link_text('Foo')
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 317, in find_element_by_link_text
    return self.find_element(by=By.LINK_TEXT, value=link_text)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 752, in find_element
    'value': value})['value']
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: Foo
```

The test passes if you change the data URL's mime-type to `text/html`

**Comment by andreastt** [comment]
Filed [bug 1283999](https://bugzilla.mozilla.org/show_bug.cgi?id=1283999) to track this.

**Comment by andreastt** [comment]
I’ve patched this now. The core of the problem was that we were using `node.getElementsByTagName("A")`. Upper-case "`A`" only matches link elements in HTML documents. By using a lower-case "`a`" we can also match those in XHTML documents.

**Comment by andreastt** [comment]
This has now landed in central.
