### ISSUE TITLE
my selenium cucumber doesn't able to open the browser  

### ISSUE THREAD

**Issue by Purushottam10** [mozilla/geckodriver#1374]
## runner class 
@RunWith(Cucumber.class)
@Cucumber.Options(features="features",glue= {"stepDefinatin"})
public class TestRunner {
	//glue= {"stepDefinatin"}
	
}

##feature File 
Feature: Test Facebook somke scenario

  Scenario: Test login with valid credentials 
  Given Open firefox and start application 
  When I enter valid username and valid password 
  Then user should be able to login successfuly 

## Testcase
public class SmokeTest {
	

	WebDriver driver;
	
	@Given("^Open firefox and start application$")
	public void Open_firefox_and_start_application() throws Throwable  {
	   driver=new FirefoxDriver();
	   driver.manage().window().maximize();
	   driver.get("http://www.facebook.com");
	}

	@When("^I enter valid username and valid password$")
	public void I_enter_valid_username_and_valid_password() throws Throwable {
	   driver.findElement(By.id("email")).sendKeys("purushott");
	   driver.findElement(By.id("pass")).sendKeys("12345");
	}

	@Then("^user should be able to login successfuly$")
	public void user_should_be_able_to_login_successfuly() throws Throwable {
		 driver.findElement(By.id("loginbutton")).click();
		 }
}

## Stacktrace

java.lang.IllegalStateException: The path to the driver executable must be set by the webdriver.gecko.driver system property; for more information, see https://github.com/mozilla/geckodriver. The latest version can be downloaded from https://github.com/mozilla/geckodriver/releases
	at com.google.common.base.Preconditions.checkState(Preconditions.java:847)
	at org.openqa.selenium.remote.service.DriverService.findExecutable(DriverService.java:125)
	at org.openqa.selenium.firefox.GeckoDriverService.access$100(GeckoDriverService.java:43)
	at org.openqa.selenium.firefox.GeckoDriverService$Builder.findDefaultExecutable(GeckoDriverService.java:168)
	at org.openqa.selenium.remote.service.DriverService$Builder.build(DriverService.java:346)
	at org.openqa.selenium.firefox.FirefoxDriver.toExecutor(FirefoxDriver.java:168)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:125)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:103)
	at stepDefinatin.SmokeTest.Open_firefox_and_start_application(SmokeTest.java:18)
	at ?.Given Open firefox and start application(myapplication.feature:4)

**Comment by whimboo** [comment]
As the stacktrace from Selenium tells you the `geckodriver` binary cannot be found. So set it via the `webdriver.gecko.driver` system property, or put it into the PATH.
