### ISSUE TITLE
this error show my pc

### ISSUE THREAD

**Issue by arunkumar143199** [mozilla/geckodriver#1377]
package arun;

import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;

public class arun {

	public static void main(String[] args) {
		// TODO Auto-generated method stub
		
		System.setProperty("Webdriver.gecko.Driver", "C:\\Users\\ARUNKUMAR\\Downloads\\geckodriver.exe");
		WebDriver driver=new FirefoxDriver();
		
		
		driver.get("http:\\wwww.facebook.com");

	}

}

--------------------------------------------show error ---------------------------------------------------

Exception in thread "main" java.lang.IllegalStateException: The path to the driver executable must be set by the webdriver.gecko.driver system property; for more information, see https://github.com/mozilla/geckodriver. The latest version can be downloaded from https://github.com/mozilla/geckodriver/releases
	at com.google.common.base.Preconditions.checkState(Preconditions.java:847)
	at org.openqa.selenium.remote.service.DriverService.findExecutable(DriverService.java:125)
	at org.openqa.selenium.firefox.GeckoDriverService.access$100(GeckoDriverService.java:43)
	at org.openqa.selenium.firefox.GeckoDriverService$Builder.findDefaultExecutable(GeckoDriverService.java:166)
	at org.openqa.selenium.remote.service.DriverService$Builder.build(DriverService.java:346)
	at org.openqa.selenium.firefox.FirefoxDriver.toExecutor(FirefoxDriver.java:168)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:125)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:103)
	at arun.arun.main(arun.java:12)

**Comment by thc202** [comment]
The key of the system property should be all lower case.
