### ISSUE TITLE
With unhandledPromptBehavior=ignore 2 alerts following a button click cannot be closed any more

### ISSUE THREAD

**Issue by codingphil** [mozilla/geckodriver#1379]
## System

* Version: 0.22.0
* Platform: Windows 10 1803 (Redstone 4)
* Firefox: 63.0b6 (64-bit) and 64.0a1 (2018-09-18) (64-bit)
* Selenium: 3.13.0

## Testcase

The issue https://github.com/mozilla/geckodriver/issues/617 is fixed in Firefox 63 (and the nightly build of course).

If you set the capability `unhandledPromptBehavior` to `ignore` and a button click triggers 2 alerts (the second one is displayed after the first one was closed), `switchTo().alert()` after accepting the 1st alert raises an `NoAlertPresentException` which is not expected.

JUnit 4 test:
```java
@Test
public void testDoubleAlert() {
  driver.navigate().to("http://localhost:8080/DoubleAlert.html");
  WebElement button = driver.findElementById("jsDialogsAlert");
  button.click();
  driver.switchTo().alert().accept();
  // Thread.sleep(....) here does not solve the issue
  driver.switchTo().alert().accept(); // NoAlertPresentException thrown (not expected)
  assertEquals("2nd alert accepted", driver.findElementById("alertResult").getText());
}
```

## Stacktrace
```java
org.openqa.selenium.NoAlertPresentException: 
Build info: version: '3.13.0', revision: '2f0d292', time: '2018-06-25T15:24:21.231Z'
System info: host: 'LNZ-PHILIPL2', ip: '10.71.34.1', os.name: 'Windows 10', os.arch: 'x86', os.version: '10.0', java.version: '1.8.0_151'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities {acceptInsecureCerts: true, browserName: firefox, browserVersion: 63.0, javascriptEnabled: true, moz:accessibilityChecks: false, moz:geckodriverVersion: 0.22.0, moz:headless: false, moz:processID: 10788, moz:profile: C:\Users\philipl\AppData\Lo..., moz:useNonSpecCompliantPointerOrigin: false, moz:webdriverClick: true, pageLoadStrategy: normal, platform: WINDOWS, platformName: WINDOWS, platformVersion: 10.0, rotatable: false, setWindowRect: true, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: ignore}
Session ID: d440b7b6-1bbd-4ca2-9a00-4d1f133b2419
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:187)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:122)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:49)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:548)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:605)
	at org.openqa.selenium.remote.RemoteWebDriver$RemoteTargetLocator.alert(RemoteWebDriver.java:928)
	at AlertTests.testDoubleAlert(AlertTests.java:502)
```

## Trace-level log
[geckodriver-log.txt](https://github.com/mozilla/geckodriver/files/2393077/geckodriver-log.txt)

**Comment by whimboo** [comment]
This is blocked by landing the patch on https://bugzilla.mozilla.org/show_bug.cgi?id=1487358 which I cannot do at the moment due to other platform blockers. See the dependency list on that mentioned bug.
