### ISSUE TITLE
Driver.executeAsyncScript causes throwDecodedError in 0.22.0

### ISSUE THREAD

**Issue by soulgalore** [mozilla/geckodriver#1380]
## System

* Version: 0.22.0
* Platform: Mac OS X 10.13.6 (and the same on Ubuntu 16/18)
* Firefox: 62.0
* Selenium: NodeJS 3.6.0

## Testcase

Switching from Geckodriver 0.21.0 -> 0.22.0 makes running Driver.executeAsyncScript to fail. That makes it impossible to upgrade to 0.22.0 in [Browsertime](https://github.com/sitespeedio/browsertime). I didn't see anything in the changelog related to that but I guess I could have missed it. Maybe Selenium need an update?

```
git clone git@github.com:sitespeedio/browsertime.git
cd browsertime
nano package.json - > change "soprano-saxophone": "0.21.0" to  "0.22.0"
npm install
bin/browsertime.js https://en.wikipedia.org/wiki/Barack_Obama  -n 1 -b firefox
```

## Stacktrace

```
[2018-09-19 10:42:04] ERROR: Could not get the HAR from Firefox JavascriptError: ReferenceError: HAR is not defined at Object.throwDecodedError (/usr/src/app/node_modules/selenium-webdriver/lib/error.js:514:15) at parseHttpResponse (/usr/src/app/node_modules/selenium-webdriver/lib/http.js:519:13) at doSend.then.response (/usr/src/app/node_modules/selenium-webdriver/lib/http.js:441:30) at <anonymous> at process._tickCallback (internal/process/next_tick.js:188:7) From: Task: WebDriver.executeScript() at Driver.schedule (/usr/src/app/node_modules/selenium-webdriver/lib/webdriver.js:807:17) at Driver.executeAsyncScript (/usr/src/app/node_modules/selenium-webdriver/lib/webdriver.js:891:17) at SeleniumRunner.runAsyncScript (/usr/src/app/lib/core/seleniumRunner.js:268:26) at FirefoxDelegate.onStopIteration (/usr/src/app/lib/firefox/webdriver/firefoxDelegate.js:70:40) at <anonymous> at process._tickCallback (internal/process/next_tick.js:188:7)
```

## Trace-level log
There's no way to easy get the trace from Geckodriver in the NodeJS version of Selenium right, but I can try get it if there's a way?

**Comment by whimboo** [comment]
Nothing in that stack looks geckodriver or Marionette related. So you really want to try to get a trace log. Get an inspiration in how to request it via https://firefox-source-docs.mozilla.org/testing/geckodriver/geckodriver/TraceLogs.html.

Also which JS code do you make use of in the call to `executeAsyncScrip()`?

**Comment by soulgalore** [comment]
Cool, let me try it out after the weekend. We use the async to get data from [HAR Export trigger](https://github.com/devtools-html/har-export-trigger)  https://github.com/sitespeedio/browsertime/blob/master/lib/firefox/webdriver/firefoxDelegate.js#L38-L55

**Comment by soulgalore** [comment]
I was wrong. The problem is that the plugin https://github.com/devtools-html/har-export-trigger doesn't get installed when I switched to 0.22.0. I'll close this bug for now and then open a new one if I can't find a matching bug report.

**Comment by whimboo** [comment]
So you are saying it works with geckodriver 0.21.0? How did you install it?

**Comment by soulgalore** [comment]
Through Selenium. It works now again in 0.23.0. Thanks.

**Comment by whimboo** [comment]
Perfect! And thanks for getting back.
