### ISSUE TITLE
org.openqa.selenium.WebDriverException TypeError: el is undefined

### ISSUE THREAD

**Issue by tporeba** [mozilla/geckodriver#1407]
After migrating from selenium 2 to selenium 3 + geckodriver I had to modify my code that handles page reloads. So I first wait for html element to become stale and then detect if new page was fully reloaded. 

```
// before clicking button that cause reload 
WebElement page = driver.findElement(By.tagName("html");

// action that causes the reload 
// ...

// waiting for reload
WebDriverWait waitForStaleness = new WebDriverWait(driver, timeoutInSeconds);
waitForStaleness.until(ExpectedConditions.or(ExpectedConditions.alertIsPresent(),ExpectedConditions.stalenessOf(page)));
 if (isAlertPresent()) {
    String alertText = getAlert().getText();
    getAlert().dismiss();
    Assert.fail("Unexpected alert when waiting for page to be reloaded, alertText=" + alertText);
} else {
    waitForPageLoaded();
    checkForJavaScriptErrors();
}
```

It generally works, but sometimes checking for staleness fails with following error:
> Error: org.openqa.selenium.WebDriverException: TypeError: el is undefined

The problem is rare, it happened on 2 runs out of ~3000 executions. For now I have no reproducible html test case and probably it will be hard to get one as the problem looks like some kind of a race condition to me. Still I will enable trace logging to get a geckodriver trace next time it happens.

## System

* Version: 0.22.0
* Platform: client on Linux/CentOS connecting to selenium docker grid 3.14.0-francium
* Firefox: 62.0.3 (selenium/node-firefox:3.14.0-francium)
* Selenium: 3.14.0 (Java Client)

## Stacktrace

> Error: org.openqa.selenium.WebDriverException: TypeError: el is undefined
Build info: version: '3.14.0', revision: 'aacccce0', time: '2018-08-02T20:19:58.91Z'
System info: host: 'host', ip: '10.10.12.101', os.name: 'Linux', os.arch: 'amd64', os.version: '2.6.32-431.3.1.el6.x86_64', java.version: '1.8.0_121'
Driver info: org.openqa.selenium.remote.RemoteWebDriver
Capabilities {acceptInsecureCerts: true, browserName: firefox, browserVersion: 62.0.3, javascriptEnabled: true, moz:accessibilityChecks: false, moz:geckodriverVersion: 0.22.0, moz:headless: false, moz:processID: 5308, moz:profile: /tmp/rust_mozprofile.laVEKQ..., moz:useNonSpecCompliantPointerOrigin: false, moz:webdriverClick: true, pageLoadStrategy: normal, platform: LINUX, platformName: LINUX, platformVersion: 3.10.0-327.4.5.el7.x86_64, rotatable: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, webdriver.remote.sessionid: fd93b7bf-e98e-4111-ba11-4c7...}
Session ID: fd93b7bf-e98e-4111-ba11-4c725cf3a750
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:187)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:122)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:49)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:548)
	at org.openqa.selenium.remote.RemoteWebElement.execute(RemoteWebElement.java:276)
	at org.openqa.selenium.remote.RemoteWebElement.isEnabled(RemoteWebElement.java:150)
	at org.openqa.selenium.support.ui.ExpectedConditions$24.apply(ExpectedConditions.java:716)
	at org.openqa.selenium.support.ui.ExpectedConditions$24.apply(ExpectedConditions.java:711)
	at org.openqa.selenium.support.ui.ExpectedConditions$47.apply(ExpectedConditions.java:1427)
	at org.openqa.selenium.support.ui.ExpectedConditions$47.apply(ExpectedConditions.java:1421)
	at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:260)

**Comment by andreastt** [comment]
Does it reproduce in Firefox Nightly?

**Comment by whimboo** [comment]
Could you please attach a [trace-level log] from geckodriver? Read more about reporting actionable bugs in our [contribution guidelines].

[trace-level log]: https://firefox-source-docs.mozilla.org/testing/geckodriver/geckodriver/TraceLogs.html
[contribution guidelines]: https://firefox-source-docs.mozilla.org/testing/geckodriver/geckodriver/Bugs.html

**Comment by tporeba** [comment]
Sorry, but I don't have trace-level log yet. I cannot also check if this happens on Firefox Nightly as I don't have a reproducible scenario myself on my current configuration. I tried extracting the part of my tests which previously thrown this error and executing it in a loop with trace-logging enabled. But I couldn't reproduce it even though the loop went on for a few hours.

I will enable the trace logging on my grid environment and wait for next random occurrence. 

Yes, I understand that without this detailed data it will be impossible to proceed with this issue.
