### ISSUE TITLE
OSError: [Errno 8] Exec format error on Ubuntu power platform

### ISSUE THREAD

**Issue by yahliu** [mozilla/geckodriver#1410]
## System

* Version: 0.21.0
* Platform: Ubuntu 16.04 ppc64le
* Firefox: Mozilla Firefox 63.0
* Selenium: 3.13.0

## Testcase
```
opts = FirefoxOptions()
opts.add_argument("--headless")
browser = webdriver.Firefox(firefox_options=opts)
```

## Stacktrace

Traceback (most recent call last): File "./suites/testui/script/logon.py", line 4, in <module> import common_fun File "/root/yrrrrhliu/icp-sanity-bats/suites/testui/script/common_fun.py", line 11, in <module> browser = webdriver.Firefox(firefox_options=opts) File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/webdriver.py", line 160, in __init__ self.service.start() File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/common/service.py", line 76, in start stdin=PIPE) File "/usr/lib/python2.7/subprocess.py", line 711, in __init__ errread, errwrite) File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child raise child_exception OSError: [Errno 8] Exec format error

when run  geckodriver directly, still report the error:
```
# geckodriver --version
-bash: /usr/bin/geckodriver: cannot execute binary file: Exec format error
```
but this case on Ubuntu 16.04 x86_64 platform run passed. 
```
# geckodriver --version
geckodriver 0.21.0

The source code of this program is available from
testing/geckodriver in https://hg.mozilla.org/mozilla-central.

This program is subject to the terms of the Mozilla Public License 2.0.
You can obtain a copy of the license at https://mozilla.org/MPL/2.0/.
```

**Comment by whimboo** [comment]
First, this is an old version of geckodriver. Meanwhile there is version 0.23.0 available. So please download that one. Also make sure that you pick the right build for your platform. There are two releases for Linux, one for 32bit systems and another one for 64bit. You most likely downloaded the wrong version.

**Comment by yahliu** [comment]
I tried new latest version 0.23.0, still report the same error. I found the geckodriver is `x86-64` after run `file geckodriver` , my platform is `ppc64le`. 
```
# tar zxvf geckodriver-v0.23.0-linux64.tar.gz
geckodriver
# file geckodriver
geckodriver: ELF 64-bit LSB executable, x86-64, version 1 (GNU/Linux), statically linked, BuildID[sha1]=b200fb865fa1ecd1372067b4bd1030303d93a28a, not stripped
```

**Comment by andreastt** [comment]
I’m sorry, we don’t provide executables for POWER8 or ppc64le systems, but you can probably self-service one through building geckodriver yourself.

If you have a checkout of mozilla-central, follow the instructions here: https://firefox-source-docs.mozilla.org/testing/geckodriver/geckodriver/Building.html
