### ISSUE TITLE
Switching between windows throws InvalidArgumentException (missing handle)

### ISSUE THREAD

**Issue by cmcgs** [mozilla/geckodriver#1424]
## System

* Version: 0.20.1
* Platform: Observed on all these: Windows 7/8.1/10, MacOS Yosemite/El Capitan/Mavericks
* Firefox: 63, 64 beta
* Selenium: Python Selenium 3.14.0

## Testcase

Given I am viewing a page
When I click on a link
Then the link opens in a new tab
```
context.browser.switch_to_window(context.browser.window_handles[-1])
assert_that(context.browser.current_url, equal_to(link_value))
# switch back to the original tab
context.browser.switch_to_window(context.browser.window_handles[0])
```
This error is being observed when running it through BrowserStack. It opens the link as a new window rather than a new tab and though it has and can print the value of the window handle, it can't switch between them.
Locally, I find that it opens in a new tab and is able to switch over fine. 

## Stacktrace
_Link has been redacted_
```
Then a new tab is opened containing the link "https://foo/bar"        # features/steps/common.py:104
      Traceback (most recent call last):
        File "/usr/local/lib/python3.7/site-packages/behave/model.py", line 1329, in run
          match.run(runner.context)
        File "/usr/local/lib/python3.7/site-packages/behave/matchers.py", line 98, in run
          self.func(context, *args, **kwargs)
        File "/features/steps/common.py", line 110, in new_tab
          context.browser.switch_to_window(context.browser.window_handles[-1])
        File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 782, in switch_to_window
          self._switch_to.window(window_name)
        File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/switch_to.py", line 115, in window
          self._driver.execute(Command.SWITCH_TO_WINDOW, data)
        File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
          self.error_handler.check_response(response)
        File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
          raise exception_class(message, screen, stacktrace)
      selenium.common.exceptions.InvalidArgumentException: Message: Missing 'handle' parameter
      Build info: version: '3.14.0', revision: 'aacccce0', time: '2018-08-02T20:13:22.693Z'
      System info: host: 'mac-207-254-75-36.browserstack.com', ip: 'fe80:0:0:0:426c:8fff:fe39:ed5f%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.9.5', java.version: '1.8.0_51'
      Driver info: driver.version: unknown
      Stacktrace:

      
      Captured stdout:
      ['4294967297', '4294967302']
```
Stacktrace itself is empty

## Trace-level log

```
07:58:12.737 DEBUG [WebDriverServlet.lambda$handle$3] - Handler thread for session 25ad47c1-e7be-3645-b169-868b0dad53d9 (firefox): Executing GET on /session/25ad47c1-e7be-3645-b169-868b0dad53d9/window_handles (handler: ServicedSession)
07:58:12.742 DEBUG [W3CHttpResponseCodec.decode] - Decoding response. Response code was: 200 and content: {"value":["4294967297","4294967302"]}
07:58:12.788 DEBUG [WebDriverServlet.handle] - Found handler: 25ad47c1-e7be-3645-b169-868b0dad53d9 (org.openqa.selenium.firefox.GeckoDriverService)
07:58:12.788 DEBUG [WebDriverServlet.lambda$handle$3] - Handler thread for session 25ad47c1-e7be-3645-b169-868b0dad53d9 (firefox): Executing GET on /session/25ad47c1-e7be-3645-b169-868b0dad53d9/window_handles (handler: ServicedSession)
07:58:12.792 DEBUG [W3CHttpResponseCodec.decode] - Decoding response. Response code was: 200 and content: {"value":["4294967297","4294967302"]}
07:58:12.837 DEBUG [WebDriverServlet.handle] - Found handler: 25ad47c1-e7be-3645-b169-868b0dad53d9 (org.openqa.selenium.firefox.GeckoDriverService)
07:58:12.837 DEBUG [WebDriverServlet.lambda$handle$3] - Handler thread for session 25ad47c1-e7be-3645-b169-868b0dad53d9 (firefox): Executing POST on /session/25ad47c1-e7be-3645-b169-868b0dad53d9/window (handler: ServicedSession)
07:58:12.843 DEBUG [W3CHttpResponseCodec.decode] - Decoding response. Response code was: 400 and content: {"value":{"error":"invalid argument","message":"Missing 'handle' parameter","stacktrace":""}}
```

I don't think this is related to geckodriver/issues/204 or geckodriver/issues/1370

**Comment by cmcgs** [comment]
@whimboo I have endeavoured to produce these logs by enabling the following:
```
"FirefoxOptions": {
    "log": {
      "level": "trace"
    }
  }
```

As I am experiencing this issue through BrowserStack it is difficult to get the logs I want. I have attached all the Selenium logs if that helps at all? [selenium_logs.txt](https://github.com/mozilla/geckodriver/files/2586279/selenium_logs.txt)

If not, I would appreciate any tips on how to get the data I need out of BrowserStack!

**Comment by whimboo** [comment]
Sadly it misses all the relevant trace log entries from Marionette. Can you ask the folks at browserstack in how to get those logs? It's nothing I can help you with.

Also this doesn't reproduce when you run the tests locally?

**Comment by cmcgs** [comment]
@whimboo That's typical  😂  I shall message them and hopefully get back to you soon.

Locally I have had no luck replicating it. I thought perhaps it was due to the fact my Firefox is configured to open links in new tabs rather than windows but turning that feature off hasn't helped me replicate it.

**Comment by whimboo** [comment]
Ok.

Just some thoughts... most likely `click` returns too early, and the content browser of the new tab hasn't been successfully registered yet. The webdriver spec doesn't say that we should wait for a new tab/window to be available. The only thing which should be done is to wait for post navigation steps. But those are not related here. 

So your best bet here might be to poll the `window_handles` until the new handle is listed.

Also I think that this is all what we should do here. @andreastt, if you think differently please reopen.

**Comment by whimboo** [comment]
Note that I would still be interested in the trace log given that the `InvalidArgumentException` is strange. Why is no `handle` specified?
