### ISSUE TITLE
Occasional stale element reference error.

### ISSUE THREAD

**Issue by tamaroth** [mozilla/geckodriver#1433]
## System

* Version: 0.23
* Platform: Linux, Ubuntu 18.04
* Firefox: 63.0
* Selenium: 3.14.1, Python 3.7

## Testcase

We were unable to reproduce this. From time to time it simply appears in our tests and we're clueless as to why it might happen.

What the test does is simply requests through driver an API endpoint (via `self.driver.get(url)`) and finally receive the text of the element (via `self.driver.find_element_by_id('json').text`). At which point we receive the following error:

## Stacktrace
```
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/my-app/tests/web/api/public/info_tests.py", line 19, in test_returns_information_in_result
    result = self.get_page_source_as_json()
  File "/my-app/tests/web/__init__.py", line 157, in get_page_source_as_json
    return json.loads(self._driver.find_element_by_id('json').text)
  File "/my-app/virtualenv/lib/python3.7/site-packages/selenium/webdriver/remote/webelement.py", line 76, in text
    return self._execute(Command.GET_ELEMENT_TEXT)['value']
  File "/my-app/virtualenv/lib/python3.7/site-packages/selenium/webdriver/remote/webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "/my-app/virtualenv/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/my-app/virtualenv/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.StaleElementReferenceException: Message: The element reference of <div id="json"> is stale; either the element is no longer attached to the DOM, it is not in the current frame context, or the document has been refreshed

-------------------- >> begin captured logging << --------------------
selenium.webdriver.remote.remote_connection: DEBUG: POST http://127.0.0.1:51741/session {"capabilities": {"firstMatch": [{}], "alwaysMatch": {"browserName": "firefox", "acceptInsecureCerts": true, "moz:firefoxOptions": {"binary": "/my-app/tools/firefox/firefox", "profile": "UEsDBBQAAAAIAGV6dU0+3NKsfgMAAM0MAAAHAAAAdXNlci5qc6VWTW/UMBC98ytQTyCx1rbABU6lFAkJUcSq4mg59mTjrmMbe7zp/nvGyaYsbb6AWz7e89hvZt44RQjcByhfnBXBNfTGlKtZo61yDVOp9gysKAyos1fPMSR4+f5ZesoxAiGEZE/ApTBxBG2hQVGwFAzhzkThEr4rjLC7sym8F1tYtn5EETB5lhmEXE+jKlfDEblgL49Z3O3p5FoBqyM6266it9YFGFmAPqkb+6MVOJ6vmbYY3O33L9Phc1Jqcc9lFSgwjzJoj5wU56jrHPT1epiwDBnAu4BcGMPvIod7CR61s3Ew6XdiL7plmetgLFau+Wyv6NEZGCRZwMaFHZOCKHtY5XjCrAiw13ImrxFkChoPTMa+HEeAj5PTgJFZr9lSm2IyoZTO5xQzizRQqECHC1zIrCBPlNsUERSXEHBYzRNSjClHfCBp+gBhhtXpwa3IsnLYgx0JJLxnySvqVCYSumEFT0CLWk3p6I04gLo+X2++OqRcEuHNCNg11jihqDAtaRzasvlRgd1k9bXdTse6vv1yyfp2m7SjFvmadVmYsy5td1THYKnsycS6JF/MYcmSOo8cB7uyJPxIpfagAEJlZQBB0k4/6RDxkrSQI230YEOihPaZVFtoiqeMWphGhKV2CiLI6lgWc1BTxuRzc/f2PuajEGO2DiSnJBXayi/J27gMIlYzUSowhskK5O4jlCIZ/ND9mabRDImMjm1v7JVxceYoJ+gbyvgwmBQRnXdmVSsQBqvunS1ytgl+8rlVrv+R3Ucvc0F9T3+/feO22/xRdp7+F/vwzmh5YPnjJhW1bvP8v/xv7cfL3w09tAzs0TkTGTmEC8eNT15f8ugjB2sNtG1rRXPGbnlWfjhG9gjbFm5roh878kYSO7vu+XoUXhgnd0ZHnK6IE0Zb4Feu9mTthTZ5AFq9rdAcZqlLLPwp3JJ/l4fb0UY6GfxTqvajvnP51dEHVzRiMcXhlXtKhUjXtkrH6rDKvz3NxJUBu8VsCRdv3/5J65emqUX5MMY1vDhw1XnC4N48WYzHmLub104Js/DmUWoD9MRc0NQWvKvRfJmawUcMWiJ/TBsKlW+NlqywhrqAsGlfR+TKZb7TyI6y9eP0WMqDB+8pCIYiYDiwTor25Bdz2EmRnsID3LXjbHAn916T7VO2WD4y1QS5PzF+Jh3GIvymNJWmMLmLBhi/AFBLAQIUAxQAAAAIAGV6dU0+3NKsfgMAAM0MAAAHAAAAAAAAAAAAAACkgQAAAAB1c2VyLmpzUEsFBgAAAAABAAEANQAAAKMDAAAAAA==", "args": ["-headless"], "log": {"level": "trace"}}}}, "desiredCapabilities": {"browserName": "firefox", "acceptInsecureCerts": true, "marionette": true, "moz:firefoxOptions": {"binary": "/my-app/tools/firefox/firefox", "profile": "UEsDBBQAAAAIAGV6dU0+3NKsfgMAAM0MAAAHAAAAdXNlci5qc6VWTW/UMBC98ytQTyCx1rbABU6lFAkJUcSq4mg59mTjrmMbe7zp/nvGyaYsbb6AWz7e89hvZt44RQjcByhfnBXBNfTGlKtZo61yDVOp9gysKAyos1fPMSR4+f5ZesoxAiGEZE/ApTBxBG2hQVGwFAzhzkThEr4rjLC7sym8F1tYtn5EETB5lhmEXE+jKlfDEblgL49Z3O3p5FoBqyM6266it9YFGFmAPqkb+6MVOJ6vmbYY3O33L9Phc1Jqcc9lFSgwjzJoj5wU56jrHPT1epiwDBnAu4BcGMPvIod7CR61s3Ew6XdiL7plmetgLFau+Wyv6NEZGCRZwMaFHZOCKHtY5XjCrAiw13ImrxFkChoPTMa+HEeAj5PTgJFZr9lSm2IyoZTO5xQzizRQqECHC1zIrCBPlNsUERSXEHBYzRNSjClHfCBp+gBhhtXpwa3IsnLYgx0JJLxnySvqVCYSumEFT0CLWk3p6I04gLo+X2++OqRcEuHNCNg11jihqDAtaRzasvlRgd1k9bXdTse6vv1yyfp2m7SjFvmadVmYsy5td1THYKnsycS6JF/MYcmSOo8cB7uyJPxIpfagAEJlZQBB0k4/6RDxkrSQI230YEOihPaZVFtoiqeMWphGhKV2CiLI6lgWc1BTxuRzc/f2PuajEGO2DiSnJBXayi/J27gMIlYzUSowhskK5O4jlCIZ/ND9mabRDImMjm1v7JVxceYoJ+gbyvgwmBQRnXdmVSsQBqvunS1ytgl+8rlVrv+R3Ucvc0F9T3+/feO22/xRdp7+F/vwzmh5YPnjJhW1bvP8v/xv7cfL3w09tAzs0TkTGTmEC8eNT15f8ugjB2sNtG1rRXPGbnlWfjhG9gjbFm5roh878kYSO7vu+XoUXhgnd0ZHnK6IE0Zb4Feu9mTthTZ5AFq9rdAcZqlLLPwp3JJ/l4fb0UY6GfxTqvajvnP51dEHVzRiMcXhlXtKhUjXtkrH6rDKvz3NxJUBu8VsCRdv3/5J65emqUX5MMY1vDhw1XnC4N48WYzHmLub104Js/DmUWoD9MRc0NQWvKvRfJmawUcMWiJ/TBsKlW+NlqywhrqAsGlfR+TKZb7TyI6y9eP0WMqDB+8pCIYiYDiwTor25Bdz2EmRnsID3LXjbHAn916T7VO2WD4y1QS5PzF+Jh3GIvymNJWmMLmLBhi/AFBLAQIUAxQAAAAIAGV6dU0+3NKsfgMAAM0MAAAHAAAAAAAAAAAAAACkgQAAAAB1c2VyLmpzUEsFBgAAAAABAAEANQAAAKMDAAAAAA==", "args": ["-headless"], "log": {"level": "trace"}}}}
urllib3.connectionpool: DEBUG: Starting new HTTP connection (1): 127.0.0.1:51741
urllib3.connectionpool: DEBUG: http://127.0.0.1:51741 "POST /session HTTP/1.1" 200 617
selenium.webdriver.remote.remote_connection: DEBUG: Finished Request
selenium.webdriver.remote.remote_connection: DEBUG: POST http://127.0.0.1:51741/session/58de7449-2f90-4a7c-beb0-e22d27cfac88/url {"url": "http://localhost:8081/api/5bf56960a0b2752f21d18187/"}
urllib3.connectionpool: DEBUG: http://127.0.0.1:51741 "POST /session/58de7449-2f90-4a7c-beb0-e22d27cfac88/url HTTP/1.1" 200 14
selenium.webdriver.remote.remote_connection: DEBUG: Finished Request
selenium.webdriver.remote.remote_connection: DEBUG: POST http://127.0.0.1:51741/session/58de7449-2f90-4a7c-beb0-e22d27cfac88/element {"using": "css selector", "value": "[id=\"json\"]"}
urllib3.connectionpool: DEBUG: http://127.0.0.1:51741 "POST /session/58de7449-2f90-4a7c-beb0-e22d27cfac88/element HTTP/1.1" 200 88
selenium.webdriver.remote.remote_connection: DEBUG: Finished Request
selenium.webdriver.remote.remote_connection: DEBUG: GET http://127.0.0.1:51741/session/58de7449-2f90-4a7c-beb0-e22d27cfac88/element/80ac8dfe-8dfb-47e0-9ea8-0c5374335941/text {"id": "80ac8dfe-8dfb-47e0-9ea8-0c5374335941"}
urllib3.connectionpool: DEBUG: http://127.0.0.1:51741 "GET /session/58de7449-2f90-4a7c-beb0-e22d27cfac88/element/80ac8dfe-8dfb-47e0-9ea8-0c5374335941/text HTTP/1.1" 404 624
selenium.webdriver.remote.remote_connection: DEBUG: Finished Request
--------------------- >> end captured logging << ---------------------
```
## Trace-level log

```
1542809952162	Marionette	INFO	Listening on port 40399
1542809952162	Marionette	DEBUG	Remote service is active
1542809952262	geckodriver::marionette	DEBUG	Connection established on 127.0.0.1:40399. Waiting for Marionette handshake
1542809952264	Marionette	DEBUG	Accepted connection 0 from 127.0.0.1:49464
1542809952265	geckodriver::marionette	DEBUG	Connected to Marionette
1542809952266	Marionette	TRACE	0 -> [0,1,"WebDriver:NewSession",{"acceptInsecureCerts":true,"browserName":"firefox"}]
1542809952266	Marionette	WARN	TLS certificate errors will be ignored for this session
1542809952300	Marionette	DEBUG	[4294967297] Frame script loaded
1542809952300	Marionette	DEBUG	[4294967297] Frame script registered
1542809952303	Marionette	TRACE	0 <- [1,1,null,{"sessionId":"58de7449-2f90-4a7c-beb0-e22d27cfac88","capabilities":{"browserName":"firefox","browserVersion":"63.0" ... 4,"moz:profile":"/tmp/rust_mozprofile.7fpwDCZhmVg4","moz:useNonSpecCompliantPointerOrigin":false,"moz:webdriverClick":true}}]
1542809952304	webdriver::server	DEBUG	<- 200 OK {"value":{"sessionId":"58de7449-2f90-4a7c-beb0-e22d27cfac88","capabilities":{"acceptInsecureCerts":true,"browserName":"firefox","browserVersion":"63.0","moz:accessibilityChecks":false,"moz:geckodriverVersion":"0.23.0","moz:headless":true,"moz:processID":12094,"moz:profile":"/tmp/rust_mozprofile.7fpwDCZhmVg4","moz:useNonSpecCompliantPointerOrigin":false,"moz:webdriverClick":true,"pageLoadStrategy":"normal","platformName":"linux","platformVersion":"4.15.0-39-generic","rotatable":false,"setWindowRect":true,"timeouts":{"implicit":0,"pageLoad":300000,"script":30000},"unhandledPromptBehavior":"dismiss and notify"}}}
1542809952590	webdriver::server	DEBUG	-> POST /session/58de7449-2f90-4a7c-beb0-e22d27cfac88/url {"url": "http://localhost:8081/api/clusters/5bf56960a0b2752f21d18187/"}
1542809952592	Marionette	TRACE	0 -> [0,2,"WebDriver:Navigate",{"url":"http://localhost:8081/api/clusters/5bf56960a0b2752f21d18187/"}]
1542809952621	Marionette	DEBUG	[4294967297] Received DOM event beforeunload for about:blank
1542809952653	Marionette	DEBUG	[4294967297] Received DOM event pagehide for about:blank
1542809952681	Marionette	DEBUG	[4294967297] Received DOM event DOMContentLoaded for http://localhost:8081/api/clusters/5bf56960a0b2752f21d18187/
1542809952690	Marionette	DEBUG	[4294967297] Received DOM event pageshow for http://localhost:8081/api/clusters/5bf56960a0b2752f21d18187/
1542809952693	Marionette	TRACE	0 <- [1,2,null,{"value":null}]
1542809952695	webdriver::server	DEBUG	<- 200 OK {"value":null}
1542809952697	webdriver::server	DEBUG	-> POST /session/58de7449-2f90-4a7c-beb0-e22d27cfac88/element {"using": "css selector", "value": "[id=\"json\"]"}
1542809952698	Marionette	TRACE	0 -> [0,3,"WebDriver:FindElement",{"using":"css selector","value":"[id=\"json\"]"}]
1542809952759	Marionette	TRACE	0 <- [1,3,null,{"value":{"element-6066-11e4-a52e-4f735466cecf":"80ac8dfe-8dfb-47e0-9ea8-0c5374335941"}}]
1542809952760	webdriver::server	DEBUG	<- 200 OK {"value":{"element-6066-11e4-a52e-4f735466cecf":"80ac8dfe-8dfb-47e0-9ea8-0c5374335941"}}
1542809952761	webdriver::server	DEBUG	-> GET /session/58de7449-2f90-4a7c-beb0-e22d27cfac88/element/80ac8dfe-8dfb-47e0-9ea8-0c5374335941/text 
1542809952762	Marionette	TRACE	0 -> [0,4,"WebDriver:GetElementText",{"id":"80ac8dfe-8dfb-47e0-9ea8-0c5374335941"}]
1542809952817	Marionette	TRACE	0 <- [1,4,{"error":"stale element reference","message":"The element reference of <div id=\"json\"> is stale; either the element is ... ch/</req<@chrome://marionette/content/listener.js:478:20\ndispatch/<@chrome://marionette/content/listener.js:477:15\n"},null]
1542809952818	webdriver::server	DEBUG	<- 404 Not Found {"value":{"error":"stale element reference","message":"The element reference of <div id=\"json\"> is stale; either the element is no longer attached to the DOM, it is not in the current frame context, or the document has been refreshed","stacktrace":"WebDriverError@chrome://marionette/content/error.js:178:5\nStaleElementReferenceError@chrome://marionette/content/error.js:437:5\nget@chrome://marionette/content/element.js:240:13\nevaluate.fromJSON@chrome://marionette/content/evaluate.js:189:18\ndispatch/</req<@chrome://marionette/content/listener.js:478:20\ndispatch/<@chrome://marionette/content/listener.js:477:15\n"}}
```

If more information is required, please don't hesitate to ask.

**Comment by whimboo** [comment]
Does the page http://localhost:8081/api/clusters/ make use of Javascript, and maybe removes the requested element from the DOM? 

Also to further investigate a minimized HTML testcase would be necessary.

**Comment by tamaroth** [comment]
The page itself is pure text, with content-type set to `application/json`. It seems that the default JSON viewer of Firefox is adding some JS and presenting the text in HTML form. 

I think this will be the cause of this.

**Comment by tamaroth** [comment]
Yes, this seems to be a problem. Adding `profile.set_preference('devtools.jsonview.enabled', False)` disabled the JSON viewer and returned instead a static HTML, which then was not prone to changes to DOM from JavaScript.
