### ISSUE TITLE
GeckoDriver v0.23.0 is unable to initiate a new session through FirefoxPortable

### ISSUE THREAD

**Issue by Debanjan-B** [mozilla/geckodriver#1443]
#Meta: GeckoDriver v0.23.0 is unable to initiate a new session through FirefoxPortable 63.0.3

## System

* Version: GeckoDriver v0.23.0
* Platform: Windows 8.1
* Firefox: FirefoxPortable_63.0.3_English.paf.exe (**63.0.3** from _About Mozilla Firefox_) (installed at `C:\\FirefoxPortable\\FirefoxPortable.exe`)
* Selenium: v3.14.0

## Testcase

- Code Block 1:

```
package demo;

import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.firefox.FirefoxDriverLogLevel;
import org.openqa.selenium.firefox.FirefoxOptions;
import org.openqa.selenium.remote.DesiredCapabilities;

public class A_Firefox_Portable {

	public static void main(String[] args) {

		System.setProperty("webdriver.gecko.driver", "C:/Utility/BrowserDrivers/geckodriver.exe");
		FirefoxOptions options = new FirefoxOptions();
		options.setBinary("C:\\FirefoxPortable\\FirefoxPortable.exe");
		options.setLogLevel(FirefoxDriverLogLevel.TRACE);
		WebDriver driver =  new FirefoxDriver(options);
		driver.get("https://stackoverflow.com");
		System.out.println("Page Title is : "+driver.getTitle());
		driver.quit();
	}
}
```
- Browser Snapshot:

FirefoxPortable
![firefoxportable](https://user-images.githubusercontent.com/26503213/49091366-b2d9f200-f285-11e8-8aad-1ae850c85ed6.png)

## Stacktrace

```
Exception in thread "main" org.openqa.selenium.SessionNotCreatedException: Unable to find a matching set of capabilities
Build info: version: '3.14.0', revision: 'aacccce0', time: '2018-08-02T20:13:22.693Z'
System info: host: 'ATECHM-03', ip: '192.168.1.6', os.name: 'Windows 8', os.arch: 'amd64', os.version: '6.2', java.version: '1.8.0_172'
Driver info: driver.version: FirefoxDriver
remote stacktrace: 
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at org.openqa.selenium.remote.W3CHandshakeResponse.lambda$new$0(W3CHandshakeResponse.java:57)
	at org.openqa.selenium.remote.W3CHandshakeResponse.lambda$getResponseFunction$2(W3CHandshakeResponse.java:104)
	at org.openqa.selenium.remote.ProtocolHandshake.lambda$createSession$0(ProtocolHandshake.java:122)
	at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
	at java.util.Spliterators$ArraySpliterator.tryAdvance(Unknown Source)
	at java.util.stream.ReferencePipeline.forEachWithCancel(Unknown Source)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(Unknown Source)
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.util.stream.FindOps$FindOp.evaluateSequential(Unknown Source)
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.util.stream.ReferencePipeline.findFirst(Unknown Source)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:125)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:73)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:136)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:548)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:212)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:130)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:125)
	at demo.A_Firefox_Portable.main(A_Firefox_Portable.java:17)
```

## Trace-level log: NA

--------------------------------

Followed the article [Using Portable Firefox 46 with WebDriver](http://seleniumsimplified.com/post/2016-06-15-using-portable-firefox-46-with-webdriver/) and have set `"marionatte"` to `false`:

- Code Block 2:

```
package demo;

import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.firefox.FirefoxDriverLogLevel;
import org.openqa.selenium.firefox.FirefoxOptions;
import org.openqa.selenium.remote.DesiredCapabilities;

public class A_Firefox_Portable {

	public static void main(String[] args) {

		System.setProperty("webdriver.gecko.driver", "C:/Utility/BrowserDrivers/geckodriver.exe");
		FirefoxOptions options = new FirefoxOptions();
		options.setBinary("C:\\FirefoxPortable\\FirefoxPortable.exe");
		options.setLogLevel(FirefoxDriverLogLevel.TRACE);
		DesiredCapabilities dc = DesiredCapabilities.firefox();
		dc.setCapability("marionatte", false);
		options.merge(dc);
		WebDriver driver =  new FirefoxDriver(options);
		driver.get("https://stackoverflow.com");
		System.out.println("Page Title is : "+driver.getTitle());
		driver.quit();
	}
}
```

- Browser Snapshot:

FirefoxPortable_marionatte_false
![firefoxportable_marionatte_false](https://user-images.githubusercontent.com/26503213/49092267-a5be0280-f287-11e8-90c8-9279822cbebe.png)

## Stacktrace

```
Nov 27, 2018 9:05:10 PM org.openqa.selenium.remote.DesiredCapabilities firefox
INFO: Using `new FirefoxOptions()` is preferred to `DesiredCapabilities.firefox()`
Exception in thread "main" org.openqa.selenium.SessionNotCreatedException: Unable to find a matching set of capabilities
Build info: version: '3.14.0', revision: 'aacccce0', time: '2018-08-02T20:13:22.693Z'
System info: host: 'ATECHM-03', ip: '192.168.1.6', os.name: 'Windows 8', os.arch: 'amd64', os.version: '6.2', java.version: '1.8.0_172'
Driver info: driver.version: FirefoxDriver
remote stacktrace: 
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at org.openqa.selenium.remote.W3CHandshakeResponse.lambda$new$0(W3CHandshakeResponse.java:57)
	at org.openqa.selenium.remote.W3CHandshakeResponse.lambda$getResponseFunction$2(W3CHandshakeResponse.java:104)
	at org.openqa.selenium.remote.ProtocolHandshake.lambda$createSession$0(ProtocolHandshake.java:122)
	at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
	at java.util.Spliterators$ArraySpliterator.tryAdvance(Unknown Source)
	at java.util.stream.ReferencePipeline.forEachWithCancel(Unknown Source)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(Unknown Source)
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.util.stream.FindOps$FindOp.evaluateSequential(Unknown Source)
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.util.stream.ReferencePipeline.findFirst(Unknown Source)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:125)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:73)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:136)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:548)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:212)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:130)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:125)
	at demo.A_Firefox_Portable.main(A_Firefox_Portable.java:20)
```

## Trace-level log: NA

**Comment by andreastt** [comment]
I’m afraid Firefox Portable is not supported by geckodriver.

**Comment by whimboo** [comment]
Note that you cannot disable Marionette when using geckodriver. That's the only mode which will work. Marionette disabled means you want to use the old and no longer running Firefox Driver.

What kind of splash screen is it what Firefox portable is showing here? Does it block the application startup?

**Comment by Debanjan-B** [comment]
@whimboo Thanks for looking in this issue. This was my first attempt with **Firefox Portable** thats too after a successful _test execution_ with **GoogleChromePortable**. 

Not sure about the splash screen, though `options.setLogLevel(FirefoxDriverLogLevel.TRACE);` nothing significant was observed.

Untill now, to deal with Firefox versions <47.x, we have been following the approach to **`setCapability("marionatte", false);`** and it worked. See [this](https://stackoverflow.com/questions/49789963/org-openqa-selenium-sessionnotcreatedexception-unable-to-find-a-matching-set-of/49791342#49791342) and [this](https://stackoverflow.com/questions/47782650/selenium-common-exceptions-sessionnotcreatedexception-message-unable-to-find-a/47785513#47785513) discussion.

**Comment by whimboo** [comment]
> Not sure about the splash screen, though `options.setLogLevel(FirefoxDriverLogLevel.TRACE);` nothing significant was observed.

If the splash screen (or what this is) is blocking Firefox from fully starting up, then Marionette will not be enabled. I cannot test it myself, but please try yourself to assist and closing it. If Firefox portable comes fully up, does Marionette work? It definitely should.

> Untill now, to deal with Firefox versions <47.x, we have been following the approach to **`setCapability("marionatte", false);`** and it worked

Yes, but then you are using the old Firefox Driver, and not geckodriver. With geckodriver you must have Marionette enabled.

**Comment by bennyvw** [comment]
I managed to get this working (in Python):

`import sys
from time import sleep

from selenium import webdriver
from selenium.webdriver.firefox.firefox_binary import FirefoxBinary

firefox_path = '/ws/apps/PortableApps/PortableApps/FirefoxPortable/App/Firefox64/firefox.exe'
gecko_path = '/python27/geckodriver.exe'

profile = webdriver.FirefoxProfile()
binary = FirefoxBinary(firefox_path, log_file=sys.stdout)

try:
   driver = webdriver.Firefox(executable_path=gecko_path, firefox_binary=binary)
   driver.get("http://stackoverflow.com")
except Exception as e:
   print(e)
finally:
   	sleep(2)
   	driver.quit()`
