### ISSUE TITLE
`Tried to run command without establishing a connection` after failing in headless mode

### ISSUE THREAD

**Issue by KroArtem** [mozilla/geckodriver#1462]
## System

* Version: moz:geckodriverVersion":"0.23.0"
* Platform: macOS High Sierra 10.13.6
* Firefox: "browserVersion":"64.0"
* Selenium: 3.141.59

## Testcase

I'm launching a testcase which opens menu in our application and then tries to open another submenu, which opens standard file dialog. However, the test fails even before file dialog is opened.

Note that this test seem to be working ok if not in headless mode.

## Stacktrace

```
org.openqa.selenium.NoSuchSessionException: Tried to run command without establishing a connection
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'spb-krosheninn', ip: 'ipHere', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.13.6', java.version: '1.8.0_152'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities {acceptInsecureCerts: true, browserName: firefox, browserVersion: 64.0, javascriptEnabled: true, moz:accessibilityChecks: false, moz:geckodriverVersion: 0.23.0, moz:headless: true, moz:processID: 92624, moz:profile: /tmp/rust_mozprofile.wLViYf..., moz:shutdownTimeout: 60000, moz:useNonSpecCompliantPointerOrigin: false, moz:webdriverClick: false, pageLoadStrategy: normal, platform: MAC, platformName: MAC, platformVersion: 17.7.0, rotatable: false, setWindowRect: true, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify}
Session ID: a5f636b7-9e90-0248-ab30-99676f222bd3
*** Element info: {Using=xpath, value=//ws-folder-header}

	at sun.reflect.GeneratedConstructorAccessor50.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:187)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:122)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:49)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:323)
	at org.openqa.selenium.remote.RemoteWebDriver.findElementByXPath(RemoteWebDriver.java:428)
	at org.openqa.selenium.By$ByXPath.findElement(By.java:353)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:315)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at io.qameta.htmlelements.handler.WebBlockMethodHandler.safeInvokeTargetMethod(WebBlockMethodHandler.java:111)
	at io.qameta.htmlelements.handler.WebBlockMethodHandler.lambda$invoke$0(WebBlockMethodHandler.java:61)
	at io.qameta.htmlelements.statement.RetryStatement.lambda$apply$1(RetryStatement.java:60)
	at io.qameta.htmlelements.statement.ListenerStatement.lambda$apply$3(ListenerStatement.java:37)
	at io.qameta.htmlelements.handler.WebBlockMethodHandler.invoke(WebBlockMethodHandler.java:72)
	at com.sun.proxy.$Proxy92.findElement(Unknown Source)
	at io.qameta.htmlelements.annotation.FindBy$Extension.lambda$handle$1(FindBy.java:56)
	at io.qameta.htmlelements.handler.WebBlockMethodHandler.safeInvokeTargetMethod(WebBlockMethodHandler.java:107)
	at io.qameta.htmlelements.handler.WebBlockMethodHandler.lambda$invoke$0(WebBlockMethodHandler.java:61)
	at io.qameta.htmlelements.statement.RetryStatement.lambda$apply$1(RetryStatement.java:60)
	at io.qameta.htmlelements.statement.ListenerStatement.lambda$apply$3(ListenerStatement.java:37)
	at io.qameta.htmlelements.handler.WebBlockMethodHandler.invoke(WebBlockMethodHandler.java:72)
	at com.sun.proxy.$Proxy93.findElement(Unknown Source)
	at io.qameta.htmlelements.annotation.FindBy$Extension.lambda$handle$1(FindBy.java:56)
	at io.qameta.htmlelements.handler.WebBlockMethodHandler.safeInvokeTargetMethod(WebBlockMethodHandler.java:107)
	at io.qameta.htmlelements.handler.WebBlockMethodHandler.lambda$invoke$0(WebBlockMethodHandler.java:61)
	at io.qameta.htmlelements.statement.RetryStatement.lambda$apply$1(RetryStatement.java:60)
	at io.qameta.htmlelements.statement.ListenerStatement.lambda$apply$3(ListenerStatement.java:37)
	at io.qameta.htmlelements.handler.WebBlockMethodHandler.invoke(WebBlockMethodHandler.java:72)
	at com.sun.proxy.$Proxy95.findElement(Unknown Source)
	at io.qameta.htmlelements.annotation.FindBy$Extension.lambda$handle$1(FindBy.java:56)
	at io.qameta.htmlelements.handler.WebBlockMethodHandler.safeInvokeTargetMethod(WebBlockMethodHandler.java:107)
	at io.qameta.htmlelements.handler.WebBlockMethodHandler.lambda$invoke$0(WebBlockMethodHandler.java:61)
	at io.qameta.htmlelements.statement.RetryStatement.lambda$apply$1(RetryStatement.java:60)
	at io.qameta.htmlelements.statement.ListenerStatement.lambda$apply$3(ListenerStatement.java:37)
	at io.qameta.htmlelements.handler.WebBlockMethodHandler.invoke(WebBlockMethodHandler.java:72)
	at com.sun.proxy.$Proxy87.click(Unknown Source)
```

## Trace-level log

[trace_log.txt](https://github.com/mozilla/geckodriver/files/2727983/trace_log.txt)

**Comment by andreastt** [comment]
It might look like the browser crashed on clicking the submit button.
WDYT @whimboo?

It would be nice if we could detect and handle crashes in Firefox
more gracefully in geckodriver. E.g. when we can’t decode the
message, check if the browser has crashed.

**Comment by whimboo** [comment]
Yes, it looks like that there is an IPC error which triggered a crash of the Firefox parent process. If that happens all the time, please check https://firefox-source-docs.mozilla.org/testing/geckodriver/geckodriver/CrashReports.html and if you can please provide us details of the crash. I would appreciate that. Thanks.

**Comment by KroArtem** [comment]
@whimboo , I've tried to do the same way as it's described on the page, the test failed but the are no files in minidump directory (though a lot of other files were created in profile directory)
```
.
..
.DS_Store
.parentlock
OfflineCache
addonStartup.json.lz4
addons.json
blocklist.xml
bookmarkbackups
cache2
compatibility.ini
containers.json
content-prefs.sqlite
cookies.sqlite
cookies.sqlite-wal
crashes
datareporting
extensions
extensions.json
favicons.sqlite
favicons.sqlite-wal
gmp
handlers.json
key3.db
key4.db
minidumps
permissions.sqlite
pkcs11.txt
places.sqlite
places.sqlite-wal
pluginreg.dat
prefs.js
results.txt
safebrowsing
saved-telemetry-pings
search.json.mozlz4
sessionCheckpoints.json
sessionstore-backups
startupCache
storage
storage.sqlite
thumbnails
times.json
webappsstore.sqlite
webappsstore.sqlite-wal

**Comment by KroArtem** [comment]
The only thing I didn't do was setting marionnete port

**Comment by whimboo** [comment]
When you are using a custom profile you will have to set the Marionette port. Otherwise geckodriver won't be able to create a connection with Marionette, and no tests should be running.

I assume when you check the geckodriver log with the custom profile the IPC error doesn't happen and Firefox doesn't just quit?

**Comment by KroArtem** [comment]
Right now I have the following error in log (firefox doesn't launch) :
```
1547019195986	mozrunner::runner	INFO	Running command: "/Applications/Firefox.app/Contents/MacOS/firefox-bin" "-marionette" "-profile" "/Users/artem.username/ourRepoHere/../test_utils/src/main/resources/profile" "-marionette-port" "2828" "--headless" "-foreground" "-no-remote"
1547019196018	geckodriver::marionette	DEBUG	Waiting 60s to connect to browser on 127.0.0.1:58172
*** You are running in headless mode.
1547019256106	mozrunner::runner	DEBUG	Killing process 31030
1547019256157	webdriver::server	DEBUG	<- 500 Internal Server Error {"value":{"error":"unknown error","message":"connection refused","stacktrace":""}}

```

Here is the code to set standard `FirefoxOptions` for our project. I've added `-profile` argument with path to an existing directory and added `--marionette-port` argument but it doesn't seem to be working.
```
static FirefoxOptions getDefaultFirefoxOptions() {
        return new FirefoxOptions()
                .setLegacy(false)
                .addArguments("-profile")
                .addArguments(FIREFOX_PROFILE_PATH)
                .addArguments("--marionette-port")
                .addArguments("2828")
                .addArguments("--headless")
                .addPreference("devtools.selfxss.count", 100) //this helps to use console and evaluate xpath, e.g. $x(".//xpath")
                .setLogLevel(TRACE);
    }
```

**Comment by whimboo** [comment]
Yes, marionette port is not an argument for the Firefox executable but for the driver. If it really cannot be set in Java, maybe the workaround from https://github.com/mozilla/geckodriver/issues/1058#issuecomment-409287559 might help by creating a wrapper script around geckodriver.

**Comment by KroArtem** [comment]
I'll try to run it anyway in a few days.

**Comment by whimboo** [comment]
Closing due to inactivity.
