### ISSUE TITLE
Connection refused error

### ISSUE THREAD

**Issue by cooperfrench95** [mozilla/geckodriver#1486]
## System

* Version: 0.24.0
* Platform: Ubuntu 18.04
* Firefox: 64
* Selenium: python, 3.141.0

## Description

I have been completely unable to fix this issue. There seems to be basically no information in the logs. I have xvfb installed and all that, I have tried playing around with DISPLAY variables etc.

I am doing this while SSH'd into the server so perhaps because I'm ssh'd in the driver is lacking permissions or something?

## Error
```
Traceback (most recent call last):
  File "parseNewArticles.py", line 41, in <module>
    driver = webdriver.Firefox(options=opt)
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/firefox/webdriver.py", line 174, in __init__
    keep_alive=True)
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: connection refused


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "parseNewArticles.py", line 146, in <module>
    driver.quit()
NameError: name 'driver' is not defined
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 63, in apport_excepthook
    from apport.fileutils import likely_packaged, get_recent_crashes
  File "/usr/lib/python3/dist-packages/apport/__init__.py", line 5, in <module>
    from apport.report import Report
  File "/usr/lib/python3/dist-packages/apport/report.py", line 30, in <module>
    import apport.fileutils
  File "/usr/lib/python3/dist-packages/apport/fileutils.py", line 23, in <module>
    from apport.packaging_impl import impl as packaging
  File "/usr/lib/python3/dist-packages/apport/packaging_impl.py", line 24, in <module>
    import apt
  File "/usr/lib/python3/dist-packages/apt/__init__.py", line 23, in <module>
    import apt_pkg
ModuleNotFoundError: No module named 'apt_pkg'

Original exception was:
Traceback (most recent call last):
  File "parseNewArticles.py", line 41, in <module>
    driver = webdriver.Firefox(options=opt)
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/firefox/webdriver.py", line 174, in __init__
    keep_alive=True)
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: connection refused

```

## Stacktrace
```
1548886753458   mozrunner::runner       INFO    Running command: "/usr/bin/firefox" "-marionette" "-headless" "-foreground" "-no-remote" "-profile" "/tmp/rust_mozprofile.3tGSdWKJTz72"
1548886753488   geckodriver::marionette DEBUG   Waiting 60s to connect to browser on 127.0.0.1:46823
*** You are running in headless mode.
1548886813614   mozrunner::runner       DEBUG   Killing process 26750
1548886813651   webdriver::server       DEBUG   <- 500 Internal Server Error {"value":{"error":"unknown error","message":"connection refused","stacktrace":""}}

```

## Python file

```
import json
import time
from pyvirtualdisplay import Display
from selenium import webdriver
from bs4 import BeautifulSoup
import datetime
import dateutil.parser
from selenium.webdriver.support.ui import WebDriverWait
import requests

try:
    display = Display(visible=0, size=(1024, 768)) 
    display.start() 
    opt = webdriver.FirefoxOptions()
    opt.headless = True
    opt.log.level = 'trace'
    driver = webdriver.Firefox(options=opt) # Breaks here with 'connection refused' on firefox when on server, no idea why. Seems unfixable.
    driver.get('https://www.example.com/')

    count = 0

    articles = set()


    for i in range(10): 
        
        driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")
        WebDriverWait(driver, 10).until(lambda d: d.execute_script('return document.readyState') == 'complete')

    images = driver.find_elements_by_class_name("lazyimage")
    for image in images:
        driver.execute_script("arguments[0].scrollIntoView();", image)
        time.sleep(1)
        print('Making sure images are loaded properly...')
        
    soup = BeautifulSoup(driver.page_source, features="html5lib")
    current_articles = soup.find_all('div', class_='full-item')
    for item in current_articles:
        articles.add(item)

    articles_to_remove = []
    itemDateDict = {}
    for item in articles:
        for child in item.descendants:
            if child.name == 'div':
                if 'data-publish-date' in child.attrs:
                    item_date = dateutil.parser.parse(child.attrs['data-publish-date'], ignoretz=True).date()
                    if item_date < datetime.date(2018, 7, 25):
                        articles_to_remove.append(item)
                    else:
                        itemDateDict[item] = item_date


    for item in articles_to_remove:
        articles.remove(item)

    articles_not_to_remove = []
    for item in articles:
        for child in item.descendants:
            try:
                if child.name == "span":
                    if 'byline-name' in child.attrs['class']:
                        if 'example' in child.string:
                            articles_not_to_remove.append(item)
            except:
                continue

    articles_to_remove = []

    for item in articles:
        if item not in articles_not_to_remove:
            articles_to_remove.append(item)

    for item in articles_to_remove:
        articles.remove(item)

    articles = list(articles)

    articles.sort(key=lambda item: itemDateDict[item], reverse=True)



    output_data = []
    baseURL = "https://www.example.com"
    count = 0

    for item in articles:
        output_data_add = {'img': {}, 'id': count}
        output_data_add['date'] = itemDateDict[item].isoformat()
        for child in item.descendants:
            if child.name == 'a' and "full-item-title" in child.attrs['class']:
                output_data_add['title'] = child.string.lstrip('\n\t').rstrip('\n')
                output_data_add['link'] = baseURL + child.attrs['href']
            elif child.name == 'img' and "lazyloaded" in child.attrs['class']:
                output_data_add['img']['alt'] = child.attrs['alt']
                output_data_add['img']['src'] = child.attrs['src']
        if output_data_add['img'] == None or output_data_add['title'] == None or output_data_add['link'] == None:
            raise IOError
        output_data.append(output_data_add)
        count += 1

    display.stop()
    driver.quit()

    with open('example.json', 'w') as f:
        json.dump(output_data, f, ensure_ascii=False, indent=4)

    url = "https://localhost:3444/blogposts"

    for item in output_data:
        newData = {}
        newData['name'] = item['name']
        newData['data'] = item['data']
        newData['data']['author'] = "5c30c9d3f00f49089043ccd5"
        print(newData, type(newData))
        response = requests.post(url, json=json.dumps(newData, indent=4, ensure_ascii=False), verify=False)
        print(response)


    print("成功")
except:
    driver.quit()
```

**Comment by cooperfrench95** [comment]
To add to this, I am now getting a slightly more detailed set of logs in geckodriver.log after rebooting:

```
1548888874026   mozrunner::runner       INFO    Running command: "/usr/bin/firefox" "-marionette" "-headless" "-foreground" "-no-remote" "-profile" "/tmp/rust_mozprofile.2KeCJBlFF2aS"
1548888874030   geckodriver::marionette DEBUG   Waiting 60s to connect to browser on 127.0.0.1:37603
*** You are running in headless mode.
1548888875623   addons.webextension.screenshots@mozilla.org     WARN    Loading extension 'screenshots@mozilla.org': Reading manifest: Invalid host permission: resource://pdf.js/
1548888875627   addons.webextension.screenshots@mozilla.org     WARN    Loading extension 'screenshots@mozilla.org': Reading manifest: Invalid host permission: about:reader*
1548888875911   Marionette      DEBUG   Received observer notification profile-after-change
1548888876018   Marionette      DEBUG   Received observer notification command-line-startup
1548888876020   Marionette      DEBUG   Received observer notification nsPref:changed
1548888876022   Marionette      DEBUG   Init aborted (running=false, enabled=true, finalUIStartup=false)
1548888876281   Marionette      DEBUG   Received observer notification toplevel-window-ready
1548888931142   Marionette      DEBUG   Received observer notification sessionstore-windows-restored
1548888931157   Marionette      DEBUG   Waiting for delayed startup...
1548888934130   mozrunner::runner       DEBUG   Killing process 2207
1548888934167   webdriver::server       DEBUG   <- 500 Internal Server Error {"value":{"error":"unknown error","message":"connection refused","stacktrace":""}}

```

**Comment by whimboo** [comment]
So you are running in headless mode. Does it also happen when not running headless? I assume the GTK libaries are installed on that machine? If not see https://bugzilla.mozilla.org/show_bug.cgi?id=1372998 for problems running Firefox headless.

**Comment by cooperfrench95** [comment]
@whimboo this does happen when not running headless as well. I ended up concluding that the machine was probably just running out of RAM because there's only 512mb of it and 80% is already being chewed up by other processes. Is that a possible cause of this?

**Comment by whimboo** [comment]
This could happen. Maybe try to close as many other processes as possible. Also does Firefox work when you start it manually, and browse around?

**Comment by cooperfrench95** [comment]
It appears to work when opened manually, yes. It seems that the lack of RAM must have been the problem.

**Comment by whimboo** [comment]
Thanks. If you can reproduce it again on a machine with more memory installed please reopen the issue, and we can continue to investigate the problem.
