### ISSUE TITLE
Unable to find a matching set of capabilities when running webdriver.Firefox()

### ISSUE THREAD

**Issue by afriestad** [mozilla/geckodriver#1488]
I am having the same trouble as @nischt mentioned in https://github.com/mozilla/geckodriver/issues/832#issuecomment-439602113 on MacOS Sierra (10.12.6) with FirefoxDeveloperEdition (aurora channel, currently 65.0b10 64 bit), geckodriver 0.23.0 (which is the version on homebrew) and Selenium 3.141.0

It doesn't matter if I simply write:

```python
from selenium import webdriver
driver = webdriver.Firefox()
```

or if I explicitly state the firefox executable path:

```python
from selenium import webdriver
driver = webdriver.Firefox(firefox_binary="/Applications/FirefoxDeveloperEdition.app")
```

Either way I get the following error:

```
Traceback (most recent call last):
  File "/path/to/file.py", line 40, in <module>
    driver = webdriver.Firefox(firefox_binary="/Applications/FirefoxDeveloperEdition.app")
  File "/path/to/lib/python3.7/site-packages/selenium/webdriver/firefox/webdriver.py", line 174, in __init__
    keep_alive=True)
  File "/path/to/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/path/to/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/path/to/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/path/to/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: Unable to find a matching set of capabilities
```

Thought I would make this a new issue since it's only tangentially related to #832, in that I don't understand a thing of the exception message 😓 

EDIT: I ran a trace with the provided option flag, which indeed did produce a geckodriver.log file. However, the file is completely empty.

**Comment by andreastt** [comment]
We need a [trace-level log] from geckodriver to saying anything useful. There’s probably a Selenium client reason this doesn’t work, as 65 + 0.23.0 is a supported combination.

geckodriver writes its log to stdout, but I don’t know what the client you are using is doing with it. Paging the maintainer @AutomatedTester.

[trace-level log]: https://firefox-source-docs.mozilla.org/testing/geckodriver/geckodriver/TraceLogs.html

**Comment by andreastt** [comment]
By client, I mean the Selenium Python client.

It’s documented in the link I gave earlier how to crank up the logging verbosity:
https://firefox-source-docs.mozilla.org/testing/geckodriver/geckodriver/TraceLogs.html#python

**Comment by afriestad** [comment]
Again, I copied that exact trace code and it gave me an empty file.

trace.py
```python
from selenium.webdriver import Firefox
from selenium.webdriver.firefox.options import Options

opts = Options()
opts.log.level = "trace"
driver = Firefox(options=opts)
```

Running it from the terminal:

```bash
(env) lemonous@ARCNET:src$ python trace.py 
Traceback (most recent call last):
  File "trace.py", line 6, in <module>
    driver = Firefox(options=opts)
  File "/env/lib/python3.7/site-packages/selenium/webdriver/firefox/webdriver.py", line 174, in __init__
    keep_alive=True)
  File "/env/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/env/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/env/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/env/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: Unable to find a matching set of capabilities

(env) lemonous@ARCNET:src$ cat geckodriver.log 
(env) lemonous@ARCNET:src$

**Comment by andreastt** [comment]
That the Selenium Python client isn’t able to emit logs isn’t a geckodriver problem. When you have the time you should dig into where it’s hiding the logs and report the bug to Selenium.

**Comment by afriestad** [comment]
Ah, I see what you mean. I tried following the tip from https://github.com/SeleniumHQ/selenium/issues/2078#issuecomment-218320864, but did not get anything out of that. `firefox_output` is created, but also empty, and `firefox_console` doesn't get created (which makes sense, assuming the binary and thus the console never gets initialized).

I tried running `geckodriver -vv`, but only got this back:

```bash
(env) lemonous@ARCNET:src$ geckodriver -vv
1549030179567	webdriver::httpapi	DEBUG	Creating routes
1549030179578	geckodriver	DEBUG	Listening on 127.0.0.1:4444
```

and this had no effect on running `trace.py`. Is there any way I can debug this with geckodriver directly, and not through Selenium?  This is also one of the key points noted by the commenter in https://github.com/mozilla/geckodriver/issues/832#issuecomment-439602113. See also your own answer to that, https://github.com/mozilla/geckodriver/issues/832#issuecomment-439603592, which is the reason why I opened this issue.

**Comment by andreastt** [comment]
I just tried replicating the problem from scratch, and I can see the trace-level output in geckodriver.log after executing the script:

```
% virtualenv _trace
New python executable in /Users/ato/_trace/bin/python
Installing setuptools, pip, wheel...done.
% source _trace/bin/activate
(_trace) % pip install selenium
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
Collecting selenium
  Downloading https://files.pythonhosted.org/packages/80/d6/4294f0b4bce4de0abf13e17190289f9d0613b0a44e5dd6a7f5ca98459853/selenium-3.141.0-py2.py3-none-any.whl (904kB)
    100% |████████████████████████████████| 911kB 5.3MB/s 
Collecting urllib3 (from selenium)
  Downloading https://files.pythonhosted.org/packages/62/00/ee1d7de624db8ba7090d1226aebefab96a2c71cd5cfa7629d6ad3f61b79e/urllib3-1.24.1-py2.py3-none-any.whl (118kB)
    100% |████████████████████████████████| 122kB 9.1MB/s 
Installing collected packages: urllib3, selenium
Successfully installed selenium-3.141.0 urllib3-1.24.1
(_trace) % curl -L https://github.com/mozilla/geckodriver/releases/download/v0.24.0/geckodriver-v0.24.0-macos.tar.gz | tar xz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   622    0   622    0     0   1892      0 --:--:-- --:--:-- --:--:--  1896
100 2050k  100 2050k    0     0  1210k      0  0:00:01  0:00:01 --:--:-- 1582k
(_trace) % cat >trace.py <<EOF
> from selenium.webdriver import Firefox
> from selenium.webdriver.firefox.options import Options
> 
> opts = Options()
> opts.log.level = "trace"
> driver = Firefox(options=opts)
> 
> EOF
(_trace) % python trace.py 
(_trace) % PATH=$(pwd):$PATH python trace.py 
(_trace) % cat geckodriver.log 
1549031247032	mozrunner::runner	INFO	Running command: "/Applications/Firefox.app/Contents/MacOS/firefox-bin" "-marionette" "-foreground" "-no-remote" "-profile" "/var/folders/3z/3yj7t8sx7_55xscc7v57h6p40000gn/T/rust_mozprofile.eK9bKiRqYgvN"
1549031247044	geckodriver::marionette	DEBUG	Waiting 60s to connect to browser on 127.0.0.1:64963
1549031247688	addons.webextension.screenshots@mozilla.org	WARN	Loading extension 'screenshots@mozilla.org': Reading manifest: Invalid extension permission: mozillaAddons
1549031247688	addons.webextension.screenshots@mozilla.org	WARN	Loading extension 'screenshots@mozilla.org': Reading manifest: Invalid extension permission: resource://pdf.js/
1549031247689	addons.webextension.screenshots@mozilla.org	WARN	Loading extension 'screenshots@mozilla.org': Reading manifest: Invalid extension permission: about:reader*
1549031247817	Marionette	TRACE	Received observer notification profile-after-change
1549031247944	Marionette	TRACE	Received observer notification command-line-startup
1549031247944	Marionette	TRACE	Received observer notification nsPref:changed
1549031247944	Marionette	DEBUG	Init aborted (running=false, enabled=true, finalUIStartup=false)
1549031248196	Marionette	TRACE	Received observer notification toplevel-window-ready
1549031249218	Marionette	TRACE	Received observer notification sessionstore-windows-restored
1549031249218	Marionette	TRACE	Waiting until startup recorder finished recording startup scripts...
1549031249423	Marionette	TRACE	All scripts recorded.
1549031249424	Marionette	DEBUG	Setting recommended pref apz.content_response_timeout to 60000
1549031249424	Marionette	DEBUG	Setting recommended pref browser.contentblocking.introCount to 99
1549031249424	Marionette	DEBUG	Setting recommended pref browser.download.panel.shown to true
1549031249424	Marionette	DEBUG	Setting recommended pref browser.newtabpage.enabled to false
1549031249425	Marionette	DEBUG	Setting recommended pref browser.pagethumbnails.capturing_disabled to true
1549031249426	Marionette	DEBUG	Setting recommended pref browser.search.update to false
1549031249426	Marionette	DEBUG	Setting recommended pref browser.tabs.disableBackgroundZombification to false
1549031249426	Marionette	DEBUG	Setting recommended pref browser.tabs.warnOnCloseOtherTabs to false
1549031249427	Marionette	DEBUG	Setting recommended pref browser.tabs.warnOnOpen to false
1549031249427	Marionette	DEBUG	Setting recommended pref browser.usedOnWindows10.introURL to 
1549031249427	Marionette	DEBUG	Setting recommended pref browser.urlbar.suggest.searches to false
1549031249428	Marionette	DEBUG	Setting recommended pref datareporting.policy.dataSubmissionPolicyAccepted to false
1549031249428	Marionette	DEBUG	Setting recommended pref dom.disable_beforeunload to true
1549031249429	Marionette	DEBUG	Setting recommended pref dom.disable_open_during_load to false
1549031249429	Marionette	DEBUG	Setting recommended pref dom.file.createInChild to true
1549031249429	Marionette	DEBUG	Setting recommended pref dom.max_chrome_script_run_time to 0
1549031249429	Marionette	DEBUG	Setting recommended pref dom.max_script_run_time to 0
1549031249430	Marionette	DEBUG	Setting recommended pref extensions.getAddons.cache.enabled to false
1549031249430	Marionette	DEBUG	Setting recommended pref extensions.webservice.discoverURL to http://%(server)s/dummy/discoveryURL
1549031249430	Marionette	DEBUG	Setting recommended pref network.http.prompt-temp-redirect to false
1549031249430	Marionette	DEBUG	Setting recommended pref network.http.speculative-parallel-limit to 0
1549031249430	Marionette	DEBUG	Setting recommended pref security.fileuri.strict_origin_policy to false
1549031249430	Marionette	DEBUG	Setting recommended pref security.notification_enable_delay to 0
1549031249431	Marionette	DEBUG	Setting recommended pref signon.autofillForms to false
1549031249431	Marionette	DEBUG	Setting recommended pref signon.rememberSignons to false
1549031249431	Marionette	DEBUG	Setting recommended pref toolkit.cosmeticAnimations.enabled to false
1549031249476	Marionette	INFO	Listening on port 64963
1549031249476	Marionette	DEBUG	Remote service is active
1549031249476	geckodriver::marionette	DEBUG	Connection established on 127.0.0.1:64963. Waiting for Marionette handshake
1549031249479	Marionette	DEBUG	Accepted connection 0 from 127.0.0.1:64991
1549031249480	geckodriver::marionette	DEBUG	Connected to Marionette
1549031249482	Marionette	DEBUG	0 -> [0,1,"WebDriver:NewSession",{"acceptInsecureCerts":true,"browserName":"firefox"}]
1549031249482	Marionette	WARN	TLS certificate errors will be ignored for this session
1549031249527	Marionette	TRACE	[4294967297] Frame script loaded
1549031249527	Marionette	TRACE	[4294967297] Frame script registered
1549031249533	Marionette	DEBUG	0 <- [1,1,null,{"sessionId":"a5d33fe0-0f1d-5c4d-9f22-2d4ff2d4e2a6","capabilities":{"browserName":"firefox","browserVersion":"67.0a ... ozprofile.eK9bKiRqYgvN","moz:shutdownTimeout":60000,"moz:useNonSpecCompliantPointerOrigin":false,"moz:webdriverClick":true}}]
1549031249534	webdriver::server	DEBUG	<- 200 OK {"value":{"sessionId":"a5d33fe0-0f1d-5c4d-9f22-2d4ff2d4e2a6","capabilities":{"acceptInsecureCerts":true,"browserName":"firefox","browserVersion":"67.0a1","moz:accessibilityChecks":false,"moz:geckodriverVersion":"0.24.0","moz:headless":false,"moz:processID":70325,"moz:profile":"/var/folders/3z/3yj7t8sx7_55xscc7v57h6p40000gn/T/rust_mozprofile.eK9bKiRqYgvN","moz:shutdownTimeout":60000,"moz:useNonSpecCompliantPointerOrigin":false,"moz:webdriverClick":true,"pageLoadStrategy":"normal","platformName":"mac","platformVersion":"18.2.0","rotatable":false,"setWindowRect":true,"strictFileInteractability":false,"timeouts":{"implicit":0,"pageLoad":300000,"script":30000},"unhandledPromptBehavior":"dismiss and notify"}}}
```

**Comment by afriestad** [comment]
I found the problem, using your help :)

It was indeed a newbie problem: Selenium on MacOS does not parse FirefoxDeveloperEdition.app as a Mac app automatically, and I had to point to the binary file `/Applications/FirefoxDeveloperEdition.app/Contents/MacOS/firefox-bin` instead. The exception went away, and the browser now runs. Thank you very much! I might take this resolution on as a feature suggestion for Selenium in the future.

**Comment by andreastt** [comment]
Oh right, I should’ve spotted that earlier. Glad you solved it!

What the path needs to be on macOS is sort of implicitly documented on https://developer.mozilla.org/en-US/docs/Web/WebDriver/Capabilities/firefoxOptions#binary and on https://firefox-source-docs.mozilla.org/testing/geckodriver/geckodriver/Capabilities.html, but we could make that clearer.

I wonder if we could improve the check in geckodriver to detect that the `binary` value is not an executable. I’ve filed https://bugzilla.mozilla.org/show_bug.cgi?id=1524584 about this.
