### ISSUE TITLE
Not opening Web Url selenium java.

### ISSUE THREAD

**Issue by ssilistre** [mozilla/geckodriver#1498]
## System

* Version: 
* Platform: Win10
* Firefox: 65 Latest Verson
* Selenium: 3.141.59 Standalone

## Testcase

Open URL

## Trace-level log

[RemoteTestNG] detected TestNG version 6.8.0
[TestNG] Running:
  C:\Users\internssilistre\AppData\Local\Temp\testng-eclipse-889479386\testng-customsuite.xml

1549628466454	mozrunner::runner	INFO	Running command: "C:\\Program Files (x86)\\Mozilla Firefox\\firefox.exe" "-marionette" "-foreground" "-no-remote" "-profile" "C:\\Users\\INTERN~1\\AppData\\Local\\Temp\\rust_mozprofile.sSz0XTU77jYe"
Unable to read VR Path Registry from C:\Users\internssilistre\AppData\Local\openvr\openvrpaths.vrpath
1549628468270	Marionette	INFO	Enabled via --marionette
Unable to read VR Path Registry from C:\Users\internssilistre\AppData\Local\openvr\openvrpaths.vrpath
Unable to read VR Path Registry from C:\Users\internssilistre\AppData\Local\openvr\openvrpaths.vrpath
[Child 15628, Chrome_ChildThread] WARNING: pipe error: 109: file z:/build/build/src/ipc/chromium/src/chrome/common/ipc_channel_win.cc, line 346
[Child 15628, Chrome_ChildThread] WARNING1549628471380	Marionette	INFO	Listening on port 54894
1549628471729	Marionette	WARN	TLS certificate errors will be ignored for this session
Unable to read VR Path Registry from C:\Users\internssilistre\AppData\Local\openvr\openvrpaths.vrpath
Unable to read VR Path Registry from C:\Users\internssilistre\AppData\Local\openvr\openvrpaths.vrpath
1549628472690	Marionette	DEBUG	Register listener.js for window 4294967297
Şub 08, 2019 3:21:12 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: W3C
1549628472810	Marionette	DEBUG	Received DOM event "beforeunload" for "about:blank"
1549628493839	Marionette	DEBUG	Received DOM event "beforeunload" for "about:blank"
1549628493841	Marionette	DEBUG	Received DOM event "pagehide" for "about:blank"
1549628493841	Marionette	DEBUG	Received DOM event "unload" for "about:blank"
1549628493886	Marionette	DEBUG	Received DOM event "DOMContentLoaded" for "about:neterror?e=netTimeout&u=http%3A//demo.guru99.com/selenium/guru99home/&c=UTF-8&f=regular&d=The%20server%20at%20demo.guru99.com%20is%20taking%20too%20long%20to%20respond."
FAILED CONFIGURATION: @BeforeMethod setUpMethod(public void scripts.Demo2.DemoTest() throws java.lang.Exception)
org.openqa.selenium.WebDriverException: Reached error page: about:neterror?e=netTimeout&u=http%3A//demo.guru99.com/selenium/guru99home/&c=UTF-8&f=regular&d=The%20server%20at%20demo.guru99.com%20is%20taking%20too%20long%20to%20respond.
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:48'
System info: host: 'GMLSESILISTRE', ip: '172.24.76.66', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_191'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities {acceptInsecureCerts: true, browserName: firefox, browserVersion: 57.0, javascriptEnabled: true, moz:accessibilityChecks: false, moz:geckodriverVersion: 0.24.0, moz:headless: false, moz:processID: 17660, moz:profile: C:\Users\internssilistre\Ap..., moz:webdriverClick: false, pageLoadStrategy: normal, platform: XP, platformName: XP, platformVersion: 10.0, rotatable: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}}
Session ID: 6bf3bffd-39f0-4fb6-8130-ef77bf96b58f
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:187)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:122)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:49)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
	at org.openqa.selenium.remote.RemoteWebDriver.get(RemoteWebDriver.java:277)
	at scripts.Demo2.setUpMethod(Demo2.java:49)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:543)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:212)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:631)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:883)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1208)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:754)
	at org.testng.TestRunner.run(TestRunner.java:614)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:335)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:330)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:292)
	at org.testng.SuiteRunner.run(SuiteRunner.java:241)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1169)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1094)
	at org.testng.TestNG.run(TestNG.java:1006)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)

SKIPPED CONFIGURATION: @AfterMethod tearDownMethod
SKIPPED CONFIGURATION: @AfterMethod tearDownClass
SKIPPED: DemoTest

===============================================
    Default test
    Tests run: 1, Failures: 0, Skips: 1
    Configuration Failures: 1, Skips: 2
===============================================

===============================================
Default suite
Total tests run: 1, Failures: 0, Skips: 1
Configuration Failures: 1, Skips: 2
===============================================

[TestNG] Time taken by org.testng.reporters.EmailableReporter@79698539: 23 ms
[TestNG] Time taken by org.testng.reporters.XMLReporter@7a5d012c: 25 ms
[TestNG] Time taken by [TestListenerAdapter] Passed:0 Failed:0 Skipped:0]: 65 ms
[TestNG] Time taken by org.testng.reporters.JUnitReportReporter@dfd3711: 32 ms
[TestNG] Time taken by org.testng.reporters.SuiteHTMLReporter@1554909b: 161 ms

**Comment by whimboo** [comment]
When loading the web page a network timeout error occurred:

> 1549628493886 Marionette DEBUG Received DOM event "DOMContentLoaded" for "about:neterror?e=netTimeout&u=http%3A//demo.guru99.com/selenium/guru99home/&c=UTF-8&f=regular&d=The%20server%20at%20demo.guru99.com%20is%20taking%20too%20long%20to%20respond."

Does it happen for all pages? Is there a proxy in place? You didn't give that much data about the environment this test is running in.

**Comment by whimboo** [comment]
No reply from reporter. As such closing the issue.
