### ISSUE TITLE
Marionette Error: Error: Permission denied to access property [name]

### ISSUE THREAD

**Issue by vladikoff** [mozilla/geckodriver#15]
### STR

Load up the proxy and run the test project below:
```
git clone https://github.com/vladikoff/intern-quick-test.git -b m-reload
cd intern-quick-test 
npm i
npm test
```

(You can target custom firefox builds using this command example:
```
npm test firefoxBinary=/<path>/gecko-dev/obj-x86_64-apple-darwin14.4.0/dist/Nightly.app/Contents/MacOS/firefox-bin
```
)

### Actual

```
{"script":"location.reload();","args":[]}] Marionette Error: Error: Permission denied to access property "reload"
```

Full log:

```
× firefox on any platform - suite1 - testTrue (2.014s)
JavaScriptError: [POST http://localhost:4444/session/71f8589c-6dc0-8c44-bf54-2a8e144e8686/execute / {"script":"location.reload();","args":[]}] Marionette Error: Error: Permission denied to access property "reload"
  at ProxiedSession._post  <node_modules/intern/node_modules/leadfoot/Session.js:59:30>
  at ProxiedSession.Session.execute  <node_modules/intern/node_modules/leadfoot/Session.js:583:15>
  at Command.<anonymous>  <node_modules/intern/node_modules/leadfoot/Command.js:635:19>
  at <node_modules/intern/node_modules/dojo/Promise.ts:393:15>
  at Object.run [as _onImmediate]  <node_modules/intern/node_modules/dojo/Promise.ts:237:7>
  at processImmediate [as _immediateCallback]  <timers.js:354:15>
  at Command.target.(anonymous function) [as execute]  <node_modules/intern/node_modules/leadfoot/Command.js:610:11>
  at Test.registerSuite.testTrue [as test]  <testfunc1.js:12:10>
  at start.then.finally.self.timeElapsed  <node_modules/intern/lib/Test.js:211:24>
  at <node_modules/intern/node_modules/dojo/Promise.ts:393:15>
  at runCallbacks  <node_modules/intern/node_modules/dojo/Promise.ts:11:11>
  at <node_modules/intern/node_modules/dojo/Promise.ts:317:4>
  at Object.run [as _onImmediate]  <node_modules/intern/node_modules/dojo/Promise.ts:237:7>
  at processImmediate [as _immediateCallback]  <timers.js:354:15>
```

### Expected

.execute should reload the page. 

### Test Code

```javascript
 testTrue: function () {
      return this.remote // get remote browser
        .get(require.toUrl('http://mozilla.org')) // load a page into the browser
        .execute('location.reload();'); // use selenium execute to reload the page.
    }
```

( P.S. I know there is a Selenium refresh command but this error happens with any .execute command accessing window objects )

**Comment by jgraham** [comment]
This is a marionette issues. Specifically it's https://bugzilla.mozilla.org/show_bug.cgi?id=1123506 (please ignore the patch in that bug it's for an unrelated issue).

**Comment by vladikoff** [comment]
> This is a marionette issue. Specifically it's https://bugzilla.mozilla.org/show_bug.cgi?id=1123506 (please ignore the patch in that bug it's for an unrelated issue).

Ahhhhh, hopefully it won't be a lot of work to support that

**Comment by vladikoff** [comment]
https://github.com/mozilla/geckodriver/issues/79#issuecomment-225464823
