### ISSUE TITLE
Firefox is not launching on MAC book even when have set the path for the GeckoDriver 

### ISSUE THREAD

**Issue by AbasSunday** [mozilla/geckodriver#1510]
## System

* Version: 
* Platform: 
* Firefox: 
* Selenium: 

public class FirstSeleniumTest {
    WebDriver driver;
    //WebDriver driver1 = new FirefoxDriver();
    //This is opening the Url
    public void invokeWebApplication(){
            //driver = new ChromeDriver();
            driver = new FirefoxDriver();

            System.setProperty("webdriver.gecko.driver","/Users/abas/Downloads/geckodriver.exe");
            //System.setProperty("webdriver.firefox.marionette", "./geckodriver.exe");
            //driver.manage().deleteAllCookies();
            driver.get("https://accounts.spotify.com/en/login");
            String title = driver.getTitle();

            if (title.equals("spotify")){
                System.out.println("This is the correct title");
            }
            else {
                System.out.println("Its a wrong title");
            }
    }

    public static void main(String[] args) {

        FirstSeleniumTest d = new FirstSeleniumTest();
        d.invokeWebApplication();
    }
}

## Stacktrace
Exception in thread "main" java.lang.IllegalStateException: The path to the driver executable must be set by the webdriver.gecko.driver system property; for more information, see https://github.com/mozilla/geckodriver. The latest version can be downloaded from https://github.com/mozilla/geckodriver/releases
	at com.google.common.base.Preconditions.checkState(Preconditions.java:847)
	at org.openqa.selenium.remote.service.DriverService.findExecutable(DriverService.java:134)
	at org.openqa.selenium.firefox.GeckoDriverService.access$100(GeckoDriverService.java:44)
	at org.openqa.selenium.firefox.GeckoDriverService$Builder.findDefaultExecutable(GeckoDriverService.java:167)
	at org.openqa.selenium.remote.service.DriverService$Builder.build(DriverService.java:355)
	at org.openqa.selenium.firefox.FirefoxDriver.toExecutor(FirefoxDriver.java:190)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:147)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:125)
	at FirstSeleniumTest.invokeWebApplication(FirstSeleniumTest.java:13)
	at FirstSeleniumTest.main(FirstSeleniumTest.java:32)

**Comment by andreastt** [comment]
This error is thrown in the Selenium client, not in geckodriver.
