### ISSUE TITLE
Unable to set Window size

### ISSUE THREAD

**Issue by GARMBoshouwers** [mozilla/geckodriver#1528]
## System

* Version: geckodriver 0.24.0
* Platform: Windows 10
* Firefox: 66.0
* Selenium: 3.141.59
* Intern: 4.4.2

## Testcase

An HTML document is not needed.
Used Intern test case:

```
/* jshint browser: false, node: true, esnext: true */

const intern = require('intern').default;
const { registerSuite } = intern.getInterface('object');

registerSuite('test', {
	tests: {
		'test': function() {
			return this.remote
				.setWindowSize(400, 800)
			;
		},
	}
});
```

## Stacktrace

```
    UnknownCommand: [GET http://localhost:4444/wd/hub/session/6954a593-10a4-4052-9406-b671e625ccf8/window/rect] GET /session/6954a593-10a4-4052-9406-b671e625ccf8/window/rect
    Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:53'
    System info: host: 'MVGUITESTER', ip: '192.168.129.174', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_201'
    Driver info: driver.version: unknown
      at Server.get @ ..\..\..\packages\tools\intern-4.4.2-mv0\node_modules\src\Server.ts:353:16
      at runRequest @ ..\..\..\packages\tools\intern-4.4.2-mv0\node_modules\src\Session.ts:132:10
      at common_1.Task.cancelled @ ..\..\..\packages\tools\intern-4.4.2-mv0\node_modules\src\Session.ts:164:42
      at new e @ ..\..\..\packages\tools\intern-4.4.2-mv0\node_modules\@theintern\common\index.js:16:5076
      at InitializedProxiedSession.Session._delegateToServer @ ..\..\..\packages\tools\intern-4.4.2-mv0\node_modules\src\Session.ts:110:11
      at InitializedProxiedSession.Session.serverGet @ ..\..\..\packages\tools\intern-4.4.2-mv0\node_modules\src\Session.ts:170:16
      at InitializedProxiedSession.Session.getWindowRect @ ..\..\..\packages\tools\intern-4.4.2-mv0\node_modules\src\Session.ts:811:16
      at getWindowPosition_1 @ ..\..\..\packages\tools\intern-4.4.2-mv0\node_modules\src\Session.ts:918:13
      at InitializedProxiedSession.Session.getWindowPosition @ ..\..\..\packages\tools\intern-4.4.2-mv0\node_modules\src\Session.ts:923:15
      at setWindowSize_1 @ ..\..\..\packages\tools\intern-4.4.2-mv0\node_modules\src\Session.ts:708:13
      at Command._callSessionMethod @ ..\..\..\packages\tools\intern-4.4.2-mv0\node_modules\src\Command.ts:733:11
      at Command.setWindowSize @ ..\..\..\packages\tools\intern-4.4.2-mv0\node_modules\src\Command.ts:1030:34
      at Test.test @ tests\functional\test.js:26:6
      @ ..\..\..\packages\tools\intern-4.4.2-mv0\src\lib\Test.ts:263:51
      @ ..\..\..\packages\tools\intern-4.4.2-mv0\node_modules\@theintern\common\index.js:16:7182
      @ anonymous
      at process._tickCallback @ internal\process\next_tick.js:160:7
```

## Trace-level log

Selenium command line output including geckodriver trace log:
[selenium_out.txt](https://github.com/mozilla/geckodriver/files/2991913/selenium_out.txt)

**Comment by whimboo** [comment]
Nothing in the trace log shows that there was actually a command send to geckodriver for resizing the window. I would suggest to get help from the Selenium community responsible for the used binding.
