### ISSUE TITLE
Exception in thread "main" org.openqa.selenium.SessionNotCreatedException: Unable to create new remote session. 

### ISSUE THREAD

**Issue by TariShah1992** [mozilla/geckodriver#1539]
I am new in coding and trying to write my first project. keep getting following error message:
Exception in thread "main" org.openqa.selenium.SessionNotCreatedException: Unable to create new remote session.  I am using Firefox ver 66.0.2 and Eclipse ver 4.6.2.

package firefoxPractice;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;

public class NewFirefox {
                public static void openBrowser(String url){
		System.setProperty("webdriver.gecko.driver", "C:\\Drivers/geckodriver.exe");
		WebDriver driver = new FirefoxDriver();
                driver.get(url);	
	}       
         public static void main(String[] args) {
	openBrowser("http://www.google.com");

}

}

**Comment by TariShah1992** [comment]
Hi it me again( Tarishah), I am getting following exceptions,

Apr 06, 2019 4:13:20 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Attempting bi-dialect session, assuming Postel's Law holds true on the remote end
1554581601637	mozrunner::runner	INFO	Running command: "C:\\Program Files\\Mozilla Firefox\\firefox.exe" "-marionette" "-foreground" "-no-remote" "-profile" "C:\\Users\\FOURST~1\\AppData\\Local\\Temp\\rust_mozprofile.2tictSkFi2Lx"
1554581607838	addons.webextension.screenshots@mozilla.org	WARN	Loading extension 'screenshots@mozilla.org': Reading manifest: Invalid extension permission: mozillaAddons
1554581607840	addons.webextension.screenshots@mozilla.org	WARN	Loading extension 'screenshots@mozilla.org': Reading manifest: Invalid extension permission: resource://pdf.js/
1554581607840	addons.webextension.screenshots@mozilla.org	WARN	Loading extension 'screenshots@mozilla.org': Reading manifest: Invalid extension permission: about:reader*
[Child 7068, Chrome_ChildThread] WARNING: pipe error: 109: file z:/build/build/src/ipc/chromium/src/chrome/common/ipc_channel_win.cc, line 332
[Child 7068, Chrome_ChildThread] WARNING: pipe error: 109: file z:/build/build/src/ipc/chromium/src/chrome/common/ipc_channel_win.cc, line 332
[Parent 8884, Gecko_IOThread] WARNING: file z:/build/build/src/ipc/chromium/src/base/process_util_win.cc, line 166
1554581635956	Marionette	INFO	Listening on port 49832
Apr 06, 2019 4:13:58 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Falling back to original OSS JSON Wire Protocol.
1554581638176	webdriver::command	WARN	You are using deprecated legacy session negotiation patterns (desiredCapabilities/requiredCapabilities), see https://developer.mozilla.org/en-US/docs/Web/WebDriver/Capabilities#Legacy
Apr 06, 2019 4:13:58 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Falling back to straight W3C remote end connection
Exception in thread "main" org.openqa.selenium.SessionNotCreatedException: Unable to create new remote session. desired capabilities = Capabilities [{marionette=true, firefoxOptions=org.openqa.selenium.firefox.FirefoxOptions@57855c9a, browserName=firefox, moz:firefoxOptions=org.openqa.selenium.firefox.FirefoxOptions@57855c9a, version=, platform=ANY}], required capabilities = Capabilities [{}]
Build info: version: 'unknown', revision: '350cf60', time: '2016-10-13 10:43:56 -0700'
System info: host: 'Tarishah', ip: '192.168.0.17', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_201'
Driver info: driver.version: FirefoxDriver
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:91)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:141)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:82)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:601)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:241)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:128)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:259)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:247)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:242)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:238)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:127)
	at firefoxPractice.NewFirefox.openBrowser(NewFirefox.java:13)
	at firefoxPractice.NewFirefox.main(NewFirefox.java:23)

**Comment by andreastt** [comment]
I’m willing to bet `C:\Drivers/geckodriver.exe` is not a valid path on Windows. Try `C:\Drivers\geckodriver.exe`?
