### ISSUE TITLE
selenium and geckodriver inside of Windows Subsystem for Linux (WSL) crash something and other time no

### ISSUE THREAD

**Issue by antoinebou13** [mozilla/geckodriver#1570]
Hello,

## System

* Version: geckodriver 0.24.0 ( 2019-01-28)
* Platform: WSL ubuntu 18.04 window 10 
* Firefox: 67.0 (64-bit)
* Selenium:  3.141.0
* Xming and python3 

## Test Case

Everytime i try to run a basic selenium test i have to run multiple time the python script before the script work and run the geckodriver in xming (X server). Expected behavior is that the script start on first time with no error

I found that if a `sudo pkill -9 geckodriver` the script work with less retry

## Stacktrace
```
Traceback (most recent call last):
  File "test_suite_rk_roundtrip.py", line 43, in setUp
    self.browser = webdriver.Firefox()
  File "/home/antoine/.local/lib/python3.6/site-packages/selenium/webdriver/firefox/webdriver.py", line 174, in __init__
    keep_alive=True)
  File "/home/antoine/.local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/home/antoine/.local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/home/antoine/.local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/antoine/.local/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: Socket timeout reading Marionette handshake data: Resource temporarily unavailable (os error 11)
```

or

```
Traceback (most recent call last):
  File "test_suite_rk_roundtrip.py", line 43, in setUp
    self.browser = webdriver.Firefox()
  File "/home/antoine/.local/lib/python3.6/site-packages/selenium/webdriver/firefox/webdriver.py", line 174, in __init__
    keep_alive=True)
  File "/home/antoine/.local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/home/antoine/.local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/home/antoine/.local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/antoine/.local/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: invalid argument: can't kill an exited process
```

or

```
Traceback (most recent call last):
  File "test_suite_rk_roundtrip.py", line 43, in setUp
    self.browser = webdriver.Firefox()
  File "/home/antoine/.local/lib/python3.6/site-packages/selenium/webdriver/firefox/webdriver.py", line 174, in __init__
    keep_alive=True)
  File "/home/antoine/.local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/home/antoine/.local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/home/antoine/.local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/antoine/.local/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: Socket timeout reading Marionette handshake data: EOF reading marionette message
```

if you need something else ask me

Thank !

**Comment by whimboo** [comment]
Could you please attach a [trace-level log] from geckodriver? Read more about reporting actionable bugs in our [contribution guidelines].

[trace-level log]: https://firefox-source-docs.mozilla.org/testing/geckodriver/geckodriver/TraceLogs.html
[contribution guidelines]: https://firefox-source-docs.mozilla.org/testing/geckodriver/geckodriver/Bugs.html

**Comment by antoinebou13** [comment]
The trace level log and that contain the error and the last part it the working selenium script

https://pastebin.com/6K10pU8a

**Comment by whimboo** [comment]
That's clearly a crash of Firefox. Please check https://firefox-source-docs.mozilla.org/testing/geckodriver/CrashReports.html and see if you can identify the crash. If there are no minidump files around it would make it harder.

**Comment by whimboo** [comment]
No further reply from the reporter. Closing the issue as it may have been fixed meanwhile.
