### ISSUE TITLE
 org.openqa.selenium.SessionNotCreatedException: session not created exception

### ISSUE THREAD

**Issue by prashant-bhat** [mozilla/geckodriver#1572]
## Stacktrace
 
org.openqa.selenium.SessionNotCreatedException: session not created exception
      from unknown error: Runtime.executionContextCreated has invalid 'context': {"auxData":{"frameId":"6A7274FC4D79482BEA9678D51015E2FC","isDefault":true,"type":"default"},"id":1,"name":"","origin":"://"}
        (Session info: chrome=75.0.3770.80)
        (Driver info: chromedriver=2.20.353145 (343b531d31eeb933ec778dbcf7081628a1396067),platform=Windows NT 10.0 x86_64) (WARNING: The server did not provide any stacktrace information)
      Command duration or timeout: 13.31 seconds
      Build info: version: '3.5.1', revision: '9c21bb67ef', time: '2017-08-17T15:26:08.955Z'
      System info: host: 'DESKTOP-R8OAL20', ip: '192.168.1.17', os.name: 'Windows 8.1', os.arch: 'amd64', os.version: '6.3', java.version: '1.8.0_40'
      Driver info: driver.version: ChromeDriver
      	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
      	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
      	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
      	at java.lang.reflect.Constructor.newInstance(Unknown Source)
      	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:215)
      	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:167)
      	at org.openqa.selenium.remote.JsonWireProtocolResponse.lambda$new$0(JsonWireProtocolResponse.java:53)
      	at org.openqa.selenium.remote.JsonWireProtocolResponse$$Lambda$77/61426020.apply(Unknown Source)
      	at org.openqa.selenium.remote.JsonWireProtocolResponse.lambda$getResponseFunction$2(JsonWireProtocolResponse.java:91)
      	at org.openqa.selenium.remote.JsonWireProtocolResponse$$Lambda$79/1829460911.apply(Unknown Source)
      	at org.openqa.selenium.remote.ProtocolHandshake.lambda$createSession$24(ProtocolHandshake.java:360)
      	at org.openqa.selenium.remote.ProtocolHandshake$$Lambda$86/181078353.apply(Unknown Source)
      	at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
      	at java.util.Spliterators$ArraySpliterator.tryAdvance(Unknown Source)
      	at java.util.stream.ReferencePipeline.forEachWithCancel(Unknown Source)
      	at java.util.stream.AbstractPipeline.copyIntoWithCancel(Unknown Source)
      	at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
      	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
      	at java.util.stream.FindOps$FindOp.evaluateSequential(Unknown Source)
      	at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
      	at java.util.stream.ReferencePipeline.findFirst(Unknown Source)
      	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:363)
      	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:137)
      	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:142)
      	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:82)
      	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:641)
      	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:254)
      	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:236)
      	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:137)
      	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:178)
      	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:167)
      	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:124)
      	at stepDefination.PaymentGalaxy_Login.open_browser(PaymentGalaxy_Login.java:23)
      	at ✽.Given Open browser(PaymenGalaxy_Login.feature:5)

-->

**Comment by prashant-bhat** [comment]
Chrome browser opens and closing immediately.

**Comment by whimboo** [comment]
Could you please attach a [trace-level log] from geckodriver? Read more about reporting actionable bugs in our [contribution guidelines].

[trace-level log]: https://firefox-source-docs.mozilla.org/testing/geckodriver/geckodriver/TraceLogs.html
[contribution guidelines]: https://firefox-source-docs.mozilla.org/testing/geckodriver/geckodriver/Bugs.html

**Comment by KroArtem** [comment]
As far as I can see, this was an attempt to run new chrome (75) with old chromedriver (2.20) and some old Selenium, so I doubt this issue is relevant to Firefox/Geckodriver.

**Comment by whimboo** [comment]
You are right. Thanks for spotting that!

**Comment by prashant-bhat** [comment]
This community is wonderful.Thanks for the help.
