### ISSUE TITLE
Hangs after launching Firefox 52.0.2 ESR

### ISSUE THREAD

**Issue by davidfstr** [mozilla/geckodriver#1576]
## System

* Version: 0.24.0 (latest as of today)
* Platform: macOS 10.14.5 (latest as of today)
* Firefox: 52.0.2 (64-bit)
    * I believe this is a supported version of Firefox based on based on [this page](https://seleniumhq.github.io/docs/wd.html#firefox) which says geckodriver supports Firefox >= 48.
* Selenium: Python + 3.141.0

## Testcase

* [Download Firefox 52.0.2 ESR](https://ftp.mozilla.org/pub/firefox/releases/52.0.2esr/) and install it in its usual location. On macOS this means: /Applications/Firefox.app
* Open Firefox once manually once by right-clicking it, selecting Open from the dropdown, and selecting Open from the dialog that pops up. (This is necessary on macOS for opening unsigned applications.)
* Quit Firefox.
* Install [geckodriver](https://github.com/mozilla/geckodriver/releases) somewhere in your $PATH.
* Install Python 3.7 or some other 3.x version of Python.
* In a terminal type:

```
mkdir selenium-firefox-test; cd selenium-firefox-test
python3 -m venv venv
source venv/bin/activate
pip3 install selenium==3.141.0
python3 -c 'from selenium import webdriver; browser = webdriver.Firefox(); browser.quit()'
```

Firefox will launch, hang for 60 seconds, and then quit with the stacktrace below.

If you replace this version of Firefox with the latest version of Firefox, the browser launches and then quits immediately (without hanging) as expected.

## Stacktrace

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/davidf/tmp/selenium-firefox-test/venv/lib/python3.7/site-packages/selenium/webdriver/firefox/webdriver.py", line 174, in __init__
    keep_alive=True)
  File "/Users/davidf/tmp/selenium-firefox-test/venv/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/Users/davidf/tmp/selenium-firefox-test/venv/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/Users/davidf/tmp/selenium-firefox-test/venv/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/davidf/tmp/selenium-firefox-test/venv/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: connection refused
```

## Trace-level log

```
1561419111401	mozrunner::runner	INFO	Running command: "/Applications/Firefox.app/Contents/MacOS/firefox-bin" "-marionette" "-foreground" "-no-remote" "-profile" "/var/folders/vm/nd6nhd948xj4ds001s76srj80000gn/T/rust_mozprofile.2xdPBQn17604"
1561419111403	geckodriver::marionette	DEBUG	Waiting 60s to connect to browser on 127.0.0.1:61609
1561419112413	Marionette	INFO	Listening on port 2828
2019-06-24 16:31:54.104 plugin-container[49426:812840] *** CFMessagePort: bootstrap_register(): failed 1100 (0x44c) 'Permission denied', port = 0x862f, name = 'com.apple.tsm.portname'
See /usr/include/servers/bootstrap_defs.h for the error codes.
2019-06-24 16:31:54.135 plugin-container[49426:812849] +[NSXPCSharedListener endpointForReply:withListenerName:]: an error occurred while attempting to obtain endpoint for listener 'ClientCallsAuxiliary': Connection invalid
1561419171452	mozrunner::runner	DEBUG	Killing process 49420
[GFX1-]: Receive IPC close with reason=AbnormalShutdown
[Child 49426] ###!!! ABORT: Aborting on channel error.: file /builds/slave/m-esr52-m64-000000000000000000/build/src/ipc/glue/MessageChannel.cpp, line 2143
[Child 49426] ###!!! ABORT: Aborting on channel error.: file /builds/slave/m-esr52-m64-000000000000000000/build/src/ipc/glue/MessageChannel.cpp, line 2143
1561419171512	webdriver::server	DEBUG	<- 500 Internal Server Error {"value":{"error":"unknown error","message":"connection refused","stacktrace":""}}
```

**Comment by whimboo** [comment]
Note, that Firefox 52 should no longer used given that it is no longer supported. The current ESR release is 60.7.

Given the [support document](https://firefox-source-docs.mozilla.org/testing/geckodriver/Support.html) it is also not possible to run geckodriver 0.24.0 with that version of Firefox.

**Comment by davidfstr** [comment]
Thanks for the quick reply! The link to the support document is quite useful.
