### ISSUE TITLE
Session will not start

### ISSUE THREAD

**Issue by neurascenic** [mozilla/geckodriver#1578]
## System

* Version: v0.24.0
* Platform: macOS + 10.14.5
* Firefox: 67.04  and 68.0(Quantum/Beta)
* Selenium: 3.141.0

## Testcase

from selenium import webdriver
driver = webdriver.Firefox()
driver.get('https://github.com/')

## Stacktrace

selenium.common.exceptions.WebDriverException: Message: newSession

Traceback (most recent call last):
  File "/Users/MBProgasm/PycharmProjects/Shipping/ScratchSheet.py", line 7, in <module>
    driver = Firefox(options=opts)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/selenium/webdriver/firefox/webdriver.py", line 174, in __init__
    keep_alive=True)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 322, in execute
    self.error_handler.check_response(response)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: newSession

## Trace-level log
[geckodriver.log](https://github.com/mozilla/geckodriver/files/3353717/geckodriver.log)

**Comment by whimboo** [comment]
As the tracelog shows you aren't using geckodriver 0.24.0 but:

> 1511040556352	geckodriver	INFO	geckodriver 0.19.1

That version is not supported anymore.
