### ISSUE TITLE
Not able to identify Kendo controls using protractor for combobox

### ISSUE THREAD

**Issue by sukritikhosla** [mozilla/geckodriver#1593]
I am new to protractor and have doubt for using kendo control.
I am able to click on the combobox dropdown but unable to select the element from the list
  # HTML code
<p>
<label>Sub Material</label>
<span class="k-widget k-combobox k-header k-combobox-clearable" style="">
<span tabindex="-1" unselectable="on" class="k-dropdown-wrap k-state-default">
<input class="k-input" type="text" autocomplete="off" title="" role="combobox" aria-expanded="false" style="" tabindex="0" aria-disabled="false" aria-autocomplete="list" aria-owns="sub-material-combox_listbox" aria-busy="false" aria-activedescendant="9daedb54-28f6-4446-aa19-4778ef397773">
<span unselectable="on" class="k-icon k-clear-value k-i-close" title="clear" role="button" tabindex="-1"></span>
<span unselectable="on" class="k-select" aria-label="select" role="button" tabindex="-1" aria-controls="sub-material-combox_listbox">
<span class="k-icon k-i-arrow-60-down">
</span>
</span>
</span>
<select id="sub-material-combox" kendo-combo-box="" k-ng-model="create.subMaterial" k-filter="'contains'" k-options="create.subMaterialOp" k-value-primitive="true" data-role="combobox" aria-disabled="false" style="display: none;">
<option value="DIE">DIE</option>
<option value="JAN26_MATERIAL">JAN26_MATERIAL</option>
<option value="JAN31_MATERIAL">JAN31_MATERIAL</option>
<option value="SENSORS-LG">SENSORS-LG</option>
<option value="STRIPS">STRIPS</option>
<option value="TUBE">TUBE</option>
<option value="WAFER">WAFER</option></select></span> 
</p>

## Stacktrace
 WebDriverError: Element <select id="sub-material-combox"> is not reachable by keyboard
    Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:53'
    System info: host: 'SUKRITI', ip: '192.168.100.52', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_211'

    Driver info: driver.version: unknown
        at Object.checkLegacyResponse (C:\Users\Sukriti\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\error.js:546:15)
        at parseHttpResponse (C:\Users\Sukriti\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\http.js:509:13)
        at doSend.then.response (C:\Users\Sukriti\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\http.js:441:30)
        at process._tickCallback (internal/process/next_tick.js:68:7)
    From: Task: WebElement.sendKeys()
        at thenableWebDriverProxy.schedule (C:\Users\Sukriti\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\webdriver.js:807:17)
        at WebElement.schedule_ (C:\Users\Sukriti\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\webdriver.js:2010:25)
        at WebElement.sendKeys (C:\Users\Sukriti\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\webdriver.js:2174:19)
        at actionFn (C:\Users\Sukriti\AppData\Roaming\npm\node_modules\protractor\built\element.js:89:44)
        at Array.map (<anonymous>)
        at actionResults.getWebElements.then (C:\Users\Sukriti\AppData\Roaming\npm\node_modules\protractor\built\element.js:461:65)
        at ManagedPromise.invokeCallback_ (C:\Users\Sukriti\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:1376:14)        at TaskQueue.execute_ (C:\Users\Sukriti\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:3084:14)
        at TaskQueue.executeNext_ (C:\Users\Sukriti\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:3067:27)
        at asyncRun (C:\Users\Sukriti\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2927:27)Error
        at ElementArrayFinder.applyAction_ (C:\Users\Sukriti\AppData\Roaming\npm\node_modules\protractor\built\element.js:459:27)
        at ElementArrayFinder.(anonymous function).args [as sendKeys] (C:\Users\Sukriti\AppData\Roaming\npm\node_modules\protractor\built\element.js:91:29)
        at ElementFinder.(anonymous function).args [as sendKeys] (C:\Users\Sukriti\AppData\Roaming\npm\node_modules\protractor\built\element.js:831:22)
        at Util.createIdentifiedLot (C:\Users\Sukriti\Documents\Automation\Util.js:37:60)
        at UserContext.<anonymous> (C:\Users\Sukriti\Documents\Automation\Data_Collection.js:11:10)
        at C:\Users\Sukriti\AppData\Roaming\npm\node_modules\protractor\node_modules\jasminewd2\index.js:112:25
        at new ManagedPromise (C:\Users\Sukriti\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:1077:7)
        at ControlFlow.promise (C:\Users\Sukriti\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2505:12)
        at schedulerExecute (C:\Users\Sukriti\AppData\Roaming\npm\node_modules\protractor\node_modules\jasminewd2\index.js:95:18)
        at TaskQueue.execute_ (C:\Users\Sukriti\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:3084:14)
    From: Task: Run it("Collect data for Lot and Verify Load History && Default Values") in control flow
        at UserContext.<anonymous> (C:\Users\Sukriti\AppData\Roaming\npm\node_modules\protractor\node_modules\jasminewd2\index.js:94:19)
        at C:\Users\Sukriti\AppData\Roaming\npm\node_modules\protractor\node_modules\jasminewd2\index.js:64:48
        at ControlFlow.emit (C:\Users\Sukriti\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\events.js:62:21)
        at ControlFlow.shutdown_ (C:\Users\Sukriti\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2674:10)
        at shutdownTask_.MicroTask (C:\Users\Sukriti\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2599:53)
    From asynchronous test:
    Error
        at Suite.<anonymous> (C:\Users\Sukriti\Documents\Automation\Data_Collection.js:9:5)
        at Object.<anonymous> (C:\Users\Sukriti\Documents\Automation\Data_Collection.js:2:1)
        at Module._compile (internal/modules/cjs/loader.js:776:30)
        at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
        at Module.load (internal/modules/cjs/loader.js:653:32)
        at tryModuleLoad (internal/modules/cjs/loader.js:593:12)

Code:
var materialType=  element(by.xpath('//*[@id="dialogContent_popupContainer"]/div/div[1]/div[1]/div[2]/p[2]/span/span/span[2]/span'));
 browser.driver.sleep(1000);
materialType.click();
element(by.xpath('//*[@id="sub-material-combox"]')).sendKeys('JAN26_MATERIAL');
browser.driver.sleep(1000);

**Comment by whimboo** [comment]
If you need help with protractor you should ask the question in their support forum. This is the geckodriver repository, which has nothing to do with this client.
