### ISSUE TITLE
UnsupportedCommandException: POST /session/[sessionId]/log did not match a known command

### ISSUE THREAD

**Issue by BabyRoot** [mozilla/geckodriver#1596]
## System

* Version: 0.24.0
* Platform: Win 10
* Firefox: 68.0.1 64bit
* Selenium: 3.141.59

## Testcase
```
FirefoxOptions options = new FirefoxOptions();
options.setCapability("webdriver.gecko.driver", "geckodriver.exe");
        
LoggingPreferences logs = new LoggingPreferences(); 
logs.enable(LogType.DRIVER, Level.ALL); 
options.setCapability(CapabilityType.LOGGING_PREFS, logs);        
options.setLogLevel(FirefoxDriverLogLevel.TRACE);
        
WebDriver ddd = new FirefoxDriver(options);        
ddd.get("https://google.com");
System.out.println("BROWSER " + ddd.manage().logs().get(LogType.BROWSER).getAll());        
ddd.quit();
```

## Stacktrace
```
org.openqa.selenium.UnsupportedCommandException: POST /session/e2adff34-79c6-4209-8694-be5d89746f9b/log did not match a known command
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: xxxxxxxx', ip: '192.168.56.1', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_181'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities {acceptInsecureCerts: true, browserName: firefox, browserVersion: 68.0.1, javascriptEnabled: true, moz:accessibilityChecks: false, moz:buildID: 20190717172542, moz:geckodriverVersion: 0.24.0, moz:headless: false, moz:processID: 4136, moz:profile: C:\Users\user\AppData\Local..., moz:shutdownTimeout: 60000, moz:useNonSpecCompliantPointerOrigin: false, moz:webdriverClick: true, pageLoadStrategy: normal, platform: WINDOWS, platformName: WINDOWS, platformVersion: 10.0, rotatable: false, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify}
Session ID: e2adff34-79c6-4209-8694-be5d89746f9b
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:187)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:122)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:49)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
	at org.openqa.selenium.remote.RemoteExecuteMethod.execute(RemoteExecuteMethod.java:35)
	at org.openqa.selenium.remote.RemoteLogs.getRemoteEntries(RemoteLogs.java:81)
	at org.openqa.selenium.remote.RemoteLogs.get(RemoteLogs.java:77)
	at xxxxx.smoke.tests.SmokeTests.xxxxxxxxx(SmokeTests.java:11)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)	
```

## Trace-level log
[Trace-level log.txt](https://github.com/mozilla/geckodriver/files/3447217/Trace-level.log.txt)

**Comment by andreastt** [comment]
geckodriver implements the WebDriver standard, and it doesn’t define a logging API.
