### ISSUE TITLE
selenium.common.exceptions.WebDriverException: Message: The browser appears to have exited before we could connect

### ISSUE THREAD

**Issue by techhie** [mozilla/geckodriver#1599]
"The browser appears to have exited "
## System
* Version: 68.0.1
* Platform: Win 10
* Firefox: 68.0.1
* Selenium: 3.6.1

## Testcase
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

browser = "Firefox"
cap = DesiredCapabilities().FIREFOX
cap["marionette"] = False
driver = webdriver.Firefox(capabilities=cap,executable_path="C:\\pystuff\\geckodriver.exe")

## Stacktrace

Traceback (most recent call last):
  File "c:/pystuff/MA/PearsonTest.py", line 66, in <module>
    driver = webdriver.Firefox(capabilities=cap,executable_path="C:\\pystuff\\geckodriver.exe")
  File "C:\Python36-32\lib\site-packages\selenium\webdriver\firefox\webdriver.py", line 171, in __init__
    self.binary, timeout)
  File "C:\Python36-32\lib\site-packages\selenium\webdriver\firefox\extension_connection.py", line 52, in __init__
    self.binary.launch_browser(self.profile, timeout=timeout)
  File "C:\Python36-32\lib\site-packages\selenium\webdriver\firefox\firefox_binary.py", line 73, in launch_browser
    self._wait_until_connectable(timeout=timeout)
  File "C:\Python36-32\lib\site-packages\selenium\webdriver\firefox\firefox_binary.py", line 104, in _wait_until_connectable
    "The browser appears to have exited "
selenium.common.exceptions.WebDriverException: Message: The browser appears to have exited before we could connect. If you specified a log_file in the FirefoxBinary constructor, check it for details.

**Comment by whimboo** [comment]
Switching off Marionette doesn't work anymore. That was only required for the old FirefoxDriver, but that is no longer working with recent versions of Firefox. It means, you will always have to enable Marionette, and as such as best remove this line from your code - given that this happens by default.
