### ISSUE TITLE
Can't get Firefox headless in full screen

### ISSUE THREAD

**Issue by heitorsilva** [mozilla/geckodriver#1627]
## System

* Version: 0.25.0
* Platform: Debian 9.11 (of a custom Docker image made with node:lts-slim)
* Firefox: 69.0.2
* Selenium server version: 3.141.5
* CodeceptJS version: 2.3.2
* NodeJS version: 10.16.3
* WebDriverIO version: 5.14.3

## Stacktrace

```bash
Portal --
  ✖ login and logout works in 3091ms

-- FAILURES:

  1) Portal
       login and logout works:
     Element <input class="input-with-icon" name="email_address" type="email"> could not be scrolled into view

  Scenario Steps:

  - I.fillField("email_address", "dev+marvin@aklamio.com") at within (src/portals/basic_test.js:46:7)
  - I.click("//a[contains(@class,"header-container-link js-hide-register")]") at within (src/portals/basic_test.js:44:7)

  Run with --verbose flag to see NodeJS stacktrace

  FAIL  | 0 passed, 1 failed   // 13s
```

## Trace-level log

```bash
09:58:07.181 INFO [GridLauncherV3.parse] - Selenium server version: 3.141.5, revision: d54ebd709a
09:58:07.318 INFO [GridLauncherV3.lambda$buildLaunchers$3] - Launching a standalone Selenium Server on port 4444
2019-10-07 09:58:07.418:INFO::main: Logging initialized @568ms to org.seleniumhq.jetty9.util.log.StdErrLog
09:58:07.796 INFO [WebDriverServlet.<init>] - Initialising WebDriverServlet
09:58:07.915 INFO [SeleniumServer.boot] - Selenium Server is up and running on port 4444
Selenium started
09:58:25.885 INFO [ActiveSessionFactory.apply] - Capabilities are: {
  "browserName": "firefox",
  "moz:firefoxOptions": {
    "args": [
      "--headless",
      "--width=1920",
      "--height=1200"
    ]
  }
}
09:58:25.893 INFO [ActiveSessionFactory.lambda$apply$11] - Matched factory org.openqa.selenium.grid.session.remote.ServicedSession$Factory (provider: org.openqa.selenium.firefox.GeckoDriverService)
1570435106306	mozrunner::runner	INFO	Running command: "/usr/bin/firefox" "-marionette" "--headless" "--width=1920" "--height=1200" "-foreground" "-no-remote" "-profile" "/tmp/rust_mozprofile.nlLojniv374V"
*** You are running in headless mode.
1570435106823	addons.webextension.screenshots@mozilla.org	WARN	Loading extension 'screenshots@mozilla.org': Reading manifest: Invalid extension permission: mozillaAddons
1570435106824	addons.webextension.screenshots@mozilla.org	WARN	Loading extension 'screenshots@mozilla.org': Reading manifest: Invalid extension permission: telemetry
1570435106825	addons.webextension.screenshots@mozilla.org	WARN	Loading extension 'screenshots@mozilla.org': Reading manifest: Invalid extension permission: resource://pdf.js/
1570435106825	addons.webextension.screenshots@mozilla.org	WARN	Loading extension 'screenshots@mozilla.org': Reading manifest: Invalid extension permission: about:reader*
1570435108587	Marionette	INFO	Listening on port 45249
09:58:28.669 INFO [ProtocolHandshake.createSession] - Detected dialect: W3C
09:58:28.706 INFO [RemoteSession$Factory.lambda$performHandshake$0] - Started new session 946fc6dd-4c90-4d04-821f-dc0f1075177b (org.openqa.selenium.firefox.GeckoDriverService)
1570435113315	Marionette	INFO	Stopped listening on port 45249
09:58:35.801 INFO [ActiveSessions$1.onStop] - Removing session 946fc6dd-4c90-4d04-821f-dc0f1075177b (org.openqa.selenium.firefox.GeckoDriverService)
```

## What are you trying to achieve?

I want to run CodeceptJS with Webdriver, using Firefox, using the resolution of 1920x1200.

## What do you get instead?

Firefox always stays with a weird resolution. When I get the screen captures, the height is always small.

My tests are failing on Firefox because I can't get it to run on fullscreen.

## Other Details

I tried three configurations and all of them fail:

```json
{
  "helpers": {
    "WebDriver": {
      "url": "https://my-secret-domain.example.org",
      "browser": "firefox",
      "desiredCapabilities": {
        "moz:firefoxOptions": {
          "args": [
            "--headless",
            "--width=1920",
            "--height=1200"
          ]
        }
      },
      "windowSize": "maximize",
      "waitForTimeout": 5000,
      "smartWait": 5000,
      "restart": true
    }
  }
}
```

```json
{
  "helpers": {
    "WebDriver": {
      "url": "https://my-secret-domain.example.org",
      "browser": "firefox",
      "desiredCapabilities": {
        "moz:firefoxOptions": {
          "args": [
            "--headless",
            "--window-size=1920,1200"
          ]
        }
      },
      "windowSize": "maximize",
      "waitForTimeout": 5000,
      "smartWait": 5000,
      "restart": true
    }
  }
}
```

```json
{
  "helpers": {
    "WebDriver": {
      "url": "https://my-secret-domain.example.org",
      "browser": "firefox",
      "desiredCapabilities": {
        "moz:firefoxOptions": {
          "args": [
            "--headless"
          ]
        }
      },
      "windowSize": "1920x1200",
      "waitForTimeout": 5000,
      "smartWait": 5000,
      "restart": true
    }
  }
}
```

Here is a screenshot of what Firefox displays when the test fails:

![login_and_logout_works failed](https://user-images.githubusercontent.com/878699/66292462-a7634880-e8e4-11e9-99ac-44308fcdbdd7.png)

**Comment by andreastt** [comment]
We have https://bugzilla.mozilla.org/show_bug.cgi?id=1519777 on file to make fullscreening more reliable across platforms, but I don’t recall we have any problems specifically with headless mode. Do you know @whimboo?

If you happen to be using Xvfb instead of headless, you have to make sure to run a window manager that supports fullscreening within the X display for the WebDriver fullscreen command to work, but I don’t expect that is the problem here since you’re passing `--headless`.

**Comment by heitorsilva** [comment]
hey @andreastt!

thanks for the reply...

on the container I'm running, I don't have any window managers, and we only need the headless version of the browsers, so I would really love to understand why the resulting of my FF headless is always a small height viewport.

**Comment by whimboo** [comment]
Without a full [trace log](https://firefox-source-docs.mozilla.org/testing/geckodriver/TraceLogs.html) there is not much I can tell. Also a simplified HTML testcase would be fantastic. I cannot see how the page would look like, which element you are trying to screenshot, ...

**Comment by whimboo** [comment]
Please note that there are no `width` and `height` arguments for the Firefox binary. Also `-window-size` is only for the screenshot feature. If you really want to set a height and width of the browser window you will have to  use environment variables. See my comment at https://github.com/mozilla/geckodriver/issues/1354#issuecomment-479456411.

I assume  this is just a dupe of issue #1354.

**Comment by andreastt** [comment]
@whimboo Hm, I wonder if we should file a bug that `--window-size` should mirror `MOZ_HEADLESS_WIDTH`/`MOZ_HEADLESS_HEIGHT`. This seems like an unfortunate piece of design.

**Comment by whimboo** [comment]
Good idea. I filed https://bugzilla.mozilla.org/show_bug.cgi?id=1587489.
