### ISSUE TITLE
Failed to start up socket within 45000 milliseconds. Attempted to connect to the following addresses: 127.0.0.1:7055

### ISSUE THREAD

**Issue by HamzaShahidAli** [mozilla/geckodriver#1650]
## System

* Version: 0.26.0
* Platform: Windows 10
* Firefox: 70.0.1
* Selenium: selenium-dotnet-2.53.0 also use Updated version
[Script.txt](https://github.com/mozilla/geckodriver/files/3819501/Script.txt)

## Testcase

I want to run c# selenium script using  cmd, when i run this file using nunit3-console Firefox driver start new instance of Firefox but not redirect to URL, or execute further steps and then after some seconds it throws exception.
**Running commands**
- `csc /r:"nunit.framework.dll","WebDriver.dll","WebDriver.Support.dll","Selenium.WebDriverBackedSelenium.dll","ThoughtWorks.Selenium.Core.dll" /target:library /out:"UnTitiled.dll" "UnTitiled.cs"`

- `nunit3-console UnTitiled.dll `

## Stacktrace

1) Error : SeleniumTests.UnTitiled.UnTitiledTestCase
OpenQA.Selenium.WebDriverException : Failed to start up socket within 45000 milliseconds. Attempted to connect to the following addresses: 127.0.0.1:7055
   at OpenQA.Selenium.Firefox.FirefoxDriverServer.ConnectToBrowser(TimeSpan timeToWait) in c:\Projects\webdriver\dotnet\src\webdriver\Firefox\FirefoxDriverServer.cs:line 277
   at OpenQA.Selenium.Firefox.FirefoxDriverServer.Start() in c:\Projects\webdriver\dotnet\src\webdriver\Firefox\FirefoxDriverServer.cs:line 97
   at OpenQA.Selenium.Firefox.FirefoxDriverCommandExecutor.Execute(Command commandToExecute) in c:\Projects\webdriver\dotnet\src\webdriver\Firefox\FirefoxDriverCommandExecutor.cs:line 71
   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters) in c:\Projects\webdriver\dotnet\src\webdriver\Remote\RemoteWebDriver.cs:line 1060
   at OpenQA.Selenium.Remote.RemoteWebDriver.StartSession(ICapabilities desiredCapabilities) in c:\Projects\webdriver\dotnet\src\webdriver\Remote\RemoteWebDriver.cs:line 1038
   at OpenQA.Selenium.Remote.RemoteWebDriver..ctor(ICommandExecutor commandExecutor, ICapabilities desiredCapabilities) in c:\Projects\webdriver\dotnet\src\webdriver\Remote\RemoteWebDriver.cs:line 119
   at OpenQA.Selenium.Firefox.FirefoxDriver..ctor(FirefoxBinary binary, FirefoxProfile profile) in c:\Projects\webdriver\dotnet\src\webdriver\Firefox\FirefoxDriver.cs:line 140
   at SeleniumTests.UnTitiled.SetupTest()

**Comment by whimboo** [comment]
Given that you are on Windows, do you have the MSVC runtime installed? See our release notes and issue #1617.

**Comment by HamzaShahidAli** [comment]
Yes MSVC runtime  already installed on my system.

**Comment by whimboo** [comment]
Could you then please attach a [trace-level log] from geckodriver?

[trace-level log]: https://firefox-source-docs.mozilla.org/testing/geckodriver/TraceLogs.html

**Comment by HamzaShahidAli** [comment]
I used the latest dll files and this fixed my issue.
Download `selenium-dotnet-3.14.0` from the [Selenium official web](https://www.seleniumhq.org/download/) extract dll file from .nupkg files, used and run successfully on Firefox.
Thanks @whimboo (Y)
