### ISSUE TITLE
geckodriver 0.26.0 is not working in linux

### ISSUE THREAD

**Issue by Rishital** [mozilla/geckodriver#1685]
•	Version: geckodriver 0.26.0
•	Platform: Linux
•	Firefox: 60
Used protractor-cucumber-framework for Component tests(angular 8).
When I try to run Component tests I get below error.
 WebDriverError: Failed to decode response from marionette
       Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:53'
       System info: host: '5dad5ca24982', ip: '172.17.0.2', os.name: 'Linux', os.arch: 'amd64', os.version: '3.10.0-957.10.1.el7.x86_64', java.version: '1.8.0_222'
       Driver info: driver.version: unknown

Component tests are working when tried with geckodriver 0.20.0.

**Comment by whimboo** [comment]
Could you please attach a [trace-level log] from geckodriver? Read more about reporting actionable bugs in our [contribution guidelines].

[trace-level log]: https://firefox-source-docs.mozilla.org/testing/geckodriver/TraceLogs.html
[contribution guidelines]: https://firefox-source-docs.mozilla.org/testing/geckodriver/Bugs.html

**Comment by Rishital** [comment]
[31mWebDriverError: Failed to decode response from marionette[39m
       [31mBuild info: version: '3.141.59', revision: 'e8sdfad358', time: '2018-11-14T08:25:53'[39m
       [31mSystem info: host: '', ip: '', os.name: 'Linux', os.arch: 'amd64', os.version: '3.10.0-862.el7.x86_64', java.version: '1.8.0_222'[39m
       [31mDriver info: driver.version: unknown[39m[90m[39m
       [90m    at Object.checkLegacyResponse (/app/node_modules/selenium-webdriver/lib/error.js:546:15)[39m
       [90m    at parseHttpResponse (/app/node_modules/selenium-webdriver/lib/http.js:509:13[39m
       [90m    at /app/node_modules/selenium-webdriver/lib/http.js:441:30[39m
       [90m    at processTicksAndRejections (internal/process/task_queues.js:93:5)[39m
       [90mFrom: Task: WebDriver.navigate().to(data:text/html,<html></html>)[39m
       [90m    at thenableWebDriverProxy.schedule (/app/node_modules/selenium-webdriver/lib/webdriver.js:807:17)[39m
       [90m    at Navigation.to (/app/node_modules/selenium-webdriver/lib/webdriver.js:1133:25)[39m
       [90m    at thenableWebDriverProxy.get (/app/node_modules/selenium-webdriver/lib/webdriver.js:988:28)[39m
       [90m    at /app/node_modules/protractor/built/browser.js:675:32[39m
       [90m    at ManagedPromise.invokeCallback_ (/app/node_modules/selenium-webdriver/lib/promise.js:1376:14)[39m
       [90m    at TaskQueue.execute_ (/app/node_modules/selenium-webdriver/lib/promise.js:3084:14)[39m
       [90m    at TaskQueue.executeNext_ (/app/node_modules/selenium-webdriver/lib/promise.js:3067:27)[39m
       [90m    at /app/node_modules/selenium-webdriver/lib/promise.js:2927:27[39m
       [90m    at /app/node_modules/selenium-webdriver/lib/promise.js:668:7[39m
       [90m    at processTicksAndRejections (internal/process/task_queues.js:93:5)[39m
   [36m- Then Tools link should be visible[39m # [90me2e/src/steps/app.steps.ts:30[39m
   [32m After[39m # [90mnode_modules/protractor-cucumber-framework/lib/resultsCapturer.js:27[39m

**Comment by whimboo** [comment]
This is still not a trace level log.

**Comment by Rishital** [comment]
I got this error once I changed version from 20 to latest
