### ISSUE TITLE
Geckodrive does not work with Linux security sandbox called firejail

### ISSUE THREAD

**Issue by ddd7et** [mozilla/geckodriver#1692]
Geckodrive does not work with Linux security sandbox called firejail

``

    from selenium.webdriver.firefox.firefox_binary import FirefoxBinary
    from selenium.webdriver import Firefox

    firefox_binary = FirefoxBinary("firejail")
    firefox_binary.add_command_line_options("--profile=/etc/firejail/firefox.profile")
    firefox_binary.add_command_line_options("/usr/bin/geckodrive")
    driver = webdriver.Firefox(firefox_binary=firefox_binary)
``

## System

* Version: '0.26.0'
* Platform: Linux Mint 19 Tara
* Firefox:  73.0 (64-bit)
* Selenium: 3.141.0

## Stacktrace

Traceback (most recent call last):
File "/home/mn/AKernel/Program/start_browser.py", line 32, in
driver = webdriver.Firefox(firefox_binary=firefox_binary)
File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/firefox/webdriver.py", line 174, in init
keep_alive=True)
File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 157, in init
self.start_session(capabilities, browser_profile)
File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
response = self.execute(Command.NEW_SESSION, parameters)
File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
self.error_handler.check_response(response)
File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: Unable to find a matching set of capabilities

Process returned 1 (0x1) execution time : 1.343 s

## Trace-level log

Error: invalid -version command line option

**Comment by whimboo** [comment]
Note that firejail needs an argument when being called (`firejail firefox`), and I don't see how this would work with your code above, which doesn't adds that. What you would need is a wrapper script for Firefox which includes that command, and can be called via geckodriver.
