### ISSUE TITLE
Page loading timeout after upgading to Firefox 69.0.3

### ISSUE THREAD

**Issue by PiotrZgadzaj** [mozilla/geckodriver#1697]
## System

* Version: 0.23.0
* Platform: Linux, Ubuntu 4.15.0-46-generic
* Firefox: 69.0.3
* Selenium: 3.11.0

## Testcase
Hi All, 

I have a problem when upgrading my Selenium test configuration to newer firefox (from 65.0.2 to 69.0.3 or 72.0.1). I run Selenium tests on two types of environments:
- Local one with Ubuntu 16 in headless mode
- Remote one which uses Docker container and Ubuntu 16/18 in headless mode

I have additional configuration set up in firefox profile:

fp.setPreference("pdfjs.disabled", true);
fp.setPreference("browser.download.folderList", 2);
fp.setPreference("browser.download.manager.showWhenStarting", false);
fp.setPreference("browser.download.dir", getFirefoxDownloadDirectory());
fp.setPreference("browser.helperApps.neverAsk.saveToDisk", FF_AUTO_DOWNLOAD_CONTENT_TYPES);
fp.setPreference("browser.helperApps.alwaysAsk.force", false);
fp.setPreference("intl.accept_languages", getBrowserLanguage());
fp.setPreference("focusmanager.testmode", true);
fp.setPreference("plugins.load_appdir_plugins", true);
fp.setAcceptUntrustedCertificates(true);
fp.setPreference("security.enable_java", true);
fp.setPreference("plugin.state.java", 2);
fp.setPreference("dom.forms.number", false);
fp.setPreference("network.proxy.type", 0);
fp.setPreference("browser.tabs.remote.autostart", false);
fp.setPreference("browser.tabs.remote.autostart.2", false);
fp.setPreference("devtools.console.stdout.content", true);

The problem which i observe is, after Firefox upgrade, on remote environment most of tests are failing as the first POST/GET is not able to retrieve the html page. I did not observe such a problem on my local deployement

## Stacktrace

	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:187)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:122)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:49)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:545)
	at org.openqa.selenium.remote.RemoteWebDriver.get(RemoteWebDriver.java:273)
	at package.LoginHelper.setCookiesForCurrentDriver(LoginHelper.java:192)
	at package.LoginHelper.loginAs(LoginHelper.java:101)
	at package.BaseST.loginAs(BaseST.java:329)
	at package.GuiTestST.testMethod(GuiTestST.java:223)

## Trace-level log
[consoleText_anonymized.txt](https://github.com/mozilla/geckodriver/files/4274642/consoleText_anonymized.txt)

**Comment by whimboo** [comment]
The navigation happens to `http://localhost:7080/CONTEXT_ROOT/redirect_to_page.jsf?pageName=page1`. I assume this is a redirect via `http-equiv=refresh`?

**Comment by PiotrZgadzaj** [comment]
Nope. Server logic bound redirect_to_page.jsf, based on query parameter pageName evaluates target url and sends redirect back to browser

**Comment by whimboo** [comment]
So it sends a [HTTP 301 code](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/301) back in the response? I would also still be interested in a [trace log](https://firefox-source-docs.mozilla.org/testing/geckodriver/TraceLogs.html).

**Comment by PiotrZgadzaj** [comment]
I attached trace logs already: https://github.com/mozilla/geckodriver/files/4274642/consoleText_anonymized.txt

I will rerun the scenario and double check if it's 301 or 302

**Comment by whimboo** [comment]
@PiotrZgadzaj is that still a problem? If yes, which kind of redirect is it? Thanks.

**Comment by whimboo** [comment]
No further reply from reporter. Closing the issue.
