### ISSUE TITLE
Unexpected Error : Status code was: -1073741515

### ISSUE THREAD

**Issue by rajjaisur** [mozilla/geckodriver#1706]
Hello Devloper,
Receiving following error:
Service geckodriver unexpectedly exited. Status code was: -1073741515

* Version:  v0.26.0 
* Platform: Window
* Firefox: 74.0.1 (64-bit)
* Selenium: 3.141.0

Please find below traceback.
Traceback (most recent call last):
  File "C:/Users/Sony/PycharmProjects/python test1/Test.py", line 4, in <module>
    driver = webdriver.Firefox()
  File "C:\Users\Sony\PycharmProjects\python test1\venv\lib\site-packages\selenium\webdriver\firefox\webdriver.py", line 164, in __init__
    self.service.start()
  File "C:\Users\Sony\PycharmProjects\python test1\venv\lib\site-packages\selenium\webdriver\common\service.py", line 98, in start
    self.assert_process_still_running()
  File "C:\Users\Sony\PycharmProjects\python test1\venv\lib\site-packages\selenium\webdriver\common\service.py", line 111, in assert_process_still_running
    % (self.path, return_code)
selenium.common.exceptions.WebDriverException: Message: Service geckodriver unexpectedly exited. Status code was: -1073741515

**Comment by whimboo** [comment]
Could you please attach a [trace-level log] from geckodriver? Read more about reporting actionable bugs in our [contribution guidelines].

[trace-level log]: https://firefox-source-docs.mozilla.org/testing/geckodriver/TraceLogs.html
[contribution guidelines]: https://firefox-source-docs.mozilla.org/testing/geckodriver/Bugs.html
