### ISSUE TITLE
Even if this is not defined in WebDriver Spec, It is working completely fine with Latest Firefox (V67) and Geckodriver (V0.24).

### ISSUE THREAD

**Issue by juchen33** [mozilla/geckodriver#1711]
Even if this is not defined in WebDriver Spec, It is working completely fine with Latest Firefox (V67) and Geckodriver (V0.24). 

[Please find linked screenshot as proof. ](https://imgur.com/a/NQa9psp)

@blackgrouse  just need to write case as below

`IWebElement finalElement = (IWebElement)((IJavaScriptExecutor)_driver).ExecuteScript("return document.querySelector(\"shop-app\").shadowRoot.querySelector(\"shop-home\").shadowRoot.querySelector(\"div.item > shop-button\"));
`

You will get your element directly without even iterating

_Originally posted by @rudreshtrivedi in https://github.com/mozilla/geckodriver/issues/1428#issuecomment-501987292_

**Comment by juchen33** [comment]
It has been mentioned in the other closed issue that this issue may have been fixed since Firefox 67.
But It was reproduced with Firefox 68.7.0 ESR 

 org.openqa.selenium.JavascriptException: Cyclic object value
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:48'
System info: host:os.name: 'Windows Server 2016', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_151'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities {acceptInsecureCerts: true, browserName: firefox, browserVersion: 68.7.0, javascriptEnabled: true, moz:accessibilityChecks: false, moz:buildID: 20200403171148, moz:geckodriverVersion: 0.26.0, moz:headless: false, moz:processID: 14260, moz:profile: moz:shutdownTimeout: 60000, moz:useNonSpecCompliantPointerOrigin: false, moz:webdriverClick: true, pageLoadStrategy: normal, platform: WINDOWS, platformName: WINDOWS, platformVersion: 10.0, rotatable: false, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify}

**Comment by whimboo** [comment]
Could you please attach a [trace-level log] from geckodriver? Read more about reporting actionable bugs in our [contribution guidelines].

[trace-level log]: https://firefox-source-docs.mozilla.org/testing/geckodriver/TraceLogs.html
[contribution guidelines]: https://firefox-source-docs.mozilla.org/testing/geckodriver/Bugs.html

**Comment by juchen33** [comment]
Thank you for your response. This was my first time reporting issue. I
followed the Java example to enable the trace level log. And just updated
my post.
Could you review it, and let me know if any other information is needed.

Thank you again,

Julia

**Comment by juchen33** [comment]
> Could you please attach a [trace-level log](https://firefox-source-docs.mozilla.org/testing/geckodriver/TraceLogs.html) from geckodriver? Read more about reporting actionable bugs in our [contribution guidelines](https://firefox-source-docs.mozilla.org/testing/geckodriver/Bugs.html).

Trace Level Logs

1587018137805 webdriver::server DEBUG -> POST /session/fc2105f3-0b19-4f0c-8715-978cbf9ee5e4/execute/sync {
"script": "return arguments[0].shadowRoot",
"args": [
{
"ELEMENT": "2fe9af88-d3b0-450e-9277-4352a3ff21ff",
"element-6066-11e4-a52e-4f735466cecf": "2fe9af88-d3b0-450e-9277-4352a3ff21ff"
}
]
}
1587018137807 Marionette DEBUG 0 -> [0,713,"WebDriver:ExecuteScript",{"args":[{"ELEMENT":"2fe9af88-d3b0-450e-9277-4352a3ff21ff","element-6066-11e4-a52e-4f735466cecf":"2fe9af88-d3b0-450e-9277-4352a3ff21ff"}],"script":"return arguments[0].shadowRoot"}]
1587018137816 Marionette DEBUG 0 <- [1,713,{"error":"javascript error","message":"Cyclic object value","stacktrace":"WebDriverError@chrome://marionette/content/e ... esponse@chrome://marionette/content/listener.js:700:26\ndispatch/</<@chrome://marionette/content/listener.js:536:19\n"},null]
1587018137815 webdriver::server DEBUG <- 500 Internal Server Error {"value":{"error":"javascript error","message":"Cyclic object value","stacktrace":"WebDriverError@chrome://marionette/content/error.js:175:5\nJavaScriptError@chrome://marionette/content/error.js:354:5\nassert.acyclic@chrome://marionette/content/assert.js:61:11\nevaluate.toJSON@chrome://marionette/content/evaluate.js:301:12\nsendResponse@chrome://marionette/content/listener.js:700:26\ndispatch/</<@chrome://marionette/content/listener.js:536:19\n"}}

**Comment by whimboo** [comment]
Thanks. Now I noticed that there is already https://bugzilla.mozilla.org/show_bug.cgi?id=1489490 for specifically this problem.

Also the WebDriver spec needs to be updated. See: https://github.com/w3c/webdriver/issues/350

**Comment by juchen33** [comment]
As I referred the link, included in the my comment. That it has been tested
with FF67 by that comment author, the shadowRoot was returned without
issue. But I am testing against FF68 ESR, which fails.

**Comment by Baiskey** [comment]
On Firefox 75.0 (64-bit) the problem also occurs

**Comment by alagappan-annamalai** [comment]
Even on FF 76.0.1 (64-bit), getting the "cyclic object value" error while returning the shadowRoot element

**Comment by Trooper13** [comment]
I have same problem on FF 68.9.0 ESR. Anybody know that will be fixed in next Geckodriver realease version and when we can expect that?

**Comment by ZaiweiXiong** [comment]
reproduced the problem on Firefox 79.0 (64-bit) with geckodriver 0.27.0.

**Comment by whimboo** [comment]
Everyone please stop posting "me too" comments on this issue. As you can notice by https://github.com/mozilla/geckodriver/issues/1711#issuecomment-615065279 we are aware of this problem, which hasn't been fixed yet. Thanks.

**Comment by CAVAh** [comment]
Using "return arguments[0].shadowRoot.children" instead "return arguments[0].shadowRoot" on executeScript() works for me. Doesn't throw an error, may be will result a list of FirefoxWebElement, but you can select one of the list (in my case the last one).

**Comment by whimboo** [comment]
Please note that there is no need anymore to use script execution for retrieving the shadow root element given that all the recent Selenium bindings should actually support the [Get Element Shadow Root command](https://w3c.github.io/webdriver/#get-element-shadow-root) command and Firefox since version 96 and geckodriver 0.31.0.

I'll still try to get the failure for execute script in https://bugzilla.mozilla.org/show_bug.cgi?id=1764594.

**Comment by JohnA2** [comment]
> Please note that there is no need anymore to use script execution for retrieving the shadow root element given that all the recent Selenium bindings should actually support the [Get Element Shadow Root command](https://w3c.github.io/webdriver/#get-element-shadow-root) command and Firefox since version 96 and geckodriver 0.31.0.
> 

Unfortunately this new way doesn't work. The issue can be reproduced with the example from https://developer.mozilla.org/en-US/docs/Web/Web_Components/Using_shadow_DOM#working_through_a_simple_example using Firefox 102 + geckodriver 0.31.0 + Selenium 4.3.0. `arguments[0].shadowRoot.children` still works fine though.

The code to reproduce it:
```
FirefoxDriver driver = new FirefoxDriver();
driver.get("https://mdn.github.io/web-components-examples/popup-info-box-web-component/");
WebElement e = driver.findElement(By.tagName("popup-info"));
SearchContext sr = e.getShadowRoot();
sr.findElements(By.tagName("*"));
```

> 1658334476733	geckodriver	INFO	Listening on 127.0.0.1:50019
> 1658334477592	mozrunner::runner	INFO	Running command: "C:\\Program Files (x86)\\Mozilla Firefox\\firefox.exe" "--marionette" "--remote-debugging-port" "57377" "--remote-allow-hosts" "localhost" "--remote-allow-origins" "http://localhost:57377/" "-no-remote" "-profile" "C:\\Users\\...\\AppData\\Local\\Temp\\2\\rust_mozprofilepLg5wr"
> 1658334478110	Marionette	INFO	Marionette enabled
> 1658334478117	Marionette	INFO	Listening on port 55984
> WebDriver BiDi listening on ws://localhost:57377
> Read port: 55984
> 1658334478249	RemoteAgent	WARN	TLS certificate errors will be ignored for this session
> console.warn: SearchSettings: "get: No settings file exists, new profile?" (new NotFoundError("Could not open the file at C:\\Users\\...\\AppData\\Local\\Temp\\2\\rust_mozprofilepLg5wr\\search.json.mozlz4", (void 0)))
> DevTools listening on ws://localhost:57377/devtools/browser/855e1c00-0ba5-4ddf-b533-3cdaa6306f98
> Jul 20, 2022 12:28:06 PM org.openqa.selenium.remote.ProtocolHandshake createSession
> INFO: Detected upstream dialect: W3C
> Exception in thread "main" org.openqa.selenium.UnsupportedCommandException: HTTP method not allowed
> Command duration or timeout: 7 milliseconds
> Build info: version: '4.3.0', revision: 'a4995e2c09*'
> System info: host: '...', ip: '...', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '11.0.2'
> Driver info: org.openqa.selenium.firefox.FirefoxDriver
> Command: [c0697450-e035-4e9d-8ce1-5d6dc68304f4, findElementsFromShadowRoot {shadowId=86bc58c6-0544-461b-b9ce-d09470b743f6, using=tag name, value=*}]
> Capabilities {acceptInsecureCerts: true, browserName: firefox, browserVersion: 102.0, moz:accessibilityChecks: false, moz:buildID: 20220623063721, moz:debuggerAddress: localhost:57377, moz:geckodriverVersion: 0.31.0, moz:headless: false, moz:processID: 616, moz:profile: C:\Users\...\AppData\L..., moz:shutdownTimeout: 60000, moz:useNonSpecCompliantPointerOrigin: false, moz:webdriverClick: true, moz:windowless: false, pageLoadStrategy: normal, platformName: WINDOWS, platformVersion: 10.0, proxy: Proxy(), se:cdp: ws://localhost:57377/devtoo..., se:cdpVersion: 85.0, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify}
> Session ID: c0697450-e035-4e9d-8ce1-5d6dc68304f4
> 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
> 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
> 	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
> 	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
> 	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:217)
> 	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:169)
> 	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:604)
> 	at org.openqa.selenium.remote.ElementLocation$ElementFinder$2.findElements(ElementLocation.java:179)
> 	at org.openqa.selenium.remote.ElementLocation.findElements(ElementLocation.java:102)
> 	at org.openqa.selenium.remote.RemoteWebDriver.findElements(RemoteWebDriver.java:402)
> 	at org.openqa.selenium.remote.ShadowRoot.findElements(ShadowRoot.java:47)
> 	at test.Test.main(Test.java:14)
>

**Comment by paulmillar** [comment]
@whimboo, at least for the remote driver, the `shadow_root` property contains [an explicit check](https://github.com/SeleniumHQ/selenium/blob/trunk/py/selenium/webdriver/remote/webelement.py#L239) that rejects Firefox.

As far as I can see, something like:
```
shadow_root = driver.execute_script('return arguments[0].shadowRoot', shadow_host)
```
is the only way that works for all versions of Chrome.

The same approach *should* also work for Firefox, except for this issue.

**Comment by fenchu** [comment]
This is mostly fixed with geckodriver  0.33.0 and FF113.

instead of the script execution you can tat the shadow_root:
```
el = WebDriverWait(wd, 10).until(EC.presence_of_element_located((By.XPATH, "//*[@id='select-type-dispensation']")))
el = el.shadow_root.find_element(By.CSS_SELECTOR, "select.bp-select")
el.click()
```
you cant use XPATH in shadow_root, and there are some small bugs left.

**Comment by whimboo** [comment]
Oh right, I should have closed this issue as fixed.

Regarding the XPATH issue this is https://bugzilla.mozilla.org/show_bug.cgi?id=1822311 and there needs to be a discussion in the WG group how we want to handle the unsupported strategy - most likely to raise a specific error.
