### ISSUE TITLE
How to keep profile intact across launches?

### ISSUE THREAD

**Issue by pmeenan** [mozilla/geckodriver#1724]
Using the python client, is there a supported way to have the profile survive across instantiations? WebPageTest re-uses the same profile in a new browser launch for repeat view testing and nothing I've tried yet has worked.

Basic flow:

```Python
from selenium import webdriver
profile = webdriver.FirefoxProfile(custom_profile_directory)
driver = webdriver.Firefox(firefox_profile=profile)

# load a page

driver.quit()
```

Actual code is [here](https://github.com/WPO-Foundation/wptagent/blob/webdriver/internal/firefox.py#L140).

It looks like the close() interface explicitly nukes the profile directory. I've tried cloning the directory before quitting and using it as a template for the repeat view launch but maybe I'm holding it wrong. So far, nothing seems to retain the cache across launches.

**Comment by whimboo** [comment]
First, if not necessary don't use the `FirefoxProfile` class unless you do more than setting preferences (which should actually be done via the capabilities). 

Otherwise there is no way right now to keep the used profile. But I recently filed https://bugzilla.mozilla.org/show_bug.cgi?id=1613064 to get an export option implemented. Maybe we can get it into the next 0.27 release.

**Comment by pmeenan** [comment]
Is there any way to get an existing profile to work?

If I specify the profile path in the options args then Firefox starts but it looks like geckodriver doesn't connect to it (though the command-line looked the same, just with a different profile directory):

```json
        capabilities["moz:firefoxOptions"] = {
            "binary": "/path/to/firefox",
            "args": ["-profile", "/path/to/profile"],
            "prefs": {"xxx": "lots of prefs"},
            "log": {"level": "trace"},
        }
```

It hangs right after "starting a new connection..."

```
13:06:44.618 - POST http://127.0.0.1:38237/session {"capabilities": {"alwaysMatch": {"acceptInsecureCerts": true, "browserName": "firefox", "moz:firefoxOptions": {"binary": "/usr/lib/firefox/firefox", "args": ["-profile", "/home/pmeenan/wptagent/work/ubuntu/browser.200530_TxGP_345327fb3c1c7c68ec8745a526098b1d.1"], "log": {"level": "error"}, "env": {"MOZ_LOG_FILE": "/home/pmeenan/wptagent/work/ubuntu/200530_TxGP_345327fb3c1c7c68ec8745a526098b1d.1.0/moz.log", "MOZ_LOG": "timestamp,nsHttp:5,nsSocketTransport:5nsHostResolver:5,pipnss:5"}, "prefs": {"browser.aboutHomeSnippets.updateUrl": "", "dom.max_chrome_script_run_time": 0, "dom.push.serverURL": "", "services.sync.prefs.sync.privacy.trackingprotection.enabled": false, "javascript.options.showInConsole": true, "browser.bookmarks.added_static_root": true, "intl.charsetmenu.browser.cache": "UTF-8", "app.update.enabled": false, "datareporting.healthreport.service.enabled": false, "browser.fixup.typo.scheme": false, "extensions.abuseReport.enabled": false, "datareporting.policy.dataSubmissionPolicyResponseType": "accepted-info-bar-dismissed", "browser.newtabpage.enhanced": false, "privacy.trackingprotection.socialtracking.enabled": false, "security.certerrors.mitm.priming.endpoint": "", "extensions.blocklist.detailsURL": "", "extensions.blocklist.enabled": false, "datareporting.healthreport.uploadEnabled": false, "pageThumbs.enabled": false, "privacy.cpd.siteSettings": true, "extensions.shield-recipe-client.enabled": false, "geo.prompt.testing": true, "network.proxy.type": 0, "app.update.url": "", "devtools.sourcemap.locations.enabled": false, "security.warn_submit_insecure": false, "browser.places.importBookmarksHTML": false, "browser.newtabpage.activity-stream.feeds.snippets": false, "dom.performance.time_to_first_interactive.enabled": true, "browser.rights.3.shown": true, "extensions.shownSelectionUI": true, "toolkit.telemetry.rejected": true, "browser.safebrowsing.malware.enabled": false, "browser.startup.homepage_override.mstone": "ignore", "reader.parse-on-load.enabled": false, "browser.tabs.warnOnClose": false, "dom.performance.time_to_dom_content_flushed.enabled": true, "geo.prompt.testing.allow": true, "browser.contentblocking.enabled": false, "privacy.sanitize.migrateFx3Prefs": true, "pref.browser.homepage.disable_button.current_page": false, "security.certerrors.mitm.priming.enabled": false, "services.sync.prefs.sync.privacy.trackingprotection.pbmode.enabled": false, "browser.newtabpage.activity-stream.disableSnippets": true, "browser.newtabpage.enabled": false, "xpinstall.signatures.required": false, "browser.safebrowsing.provider.mozilla.gethashURL": "", "extensions.update.notifyUser": false, "privacy.sanitize.timeSpan": 0, "toolkit.telemetry.reportingpolicy.firstRun": false, "extensions.fxmonitor.enabled": false, "browser.cache.disk.capacity": 1048576, "extensions.pocket.enabled": false, "security.warn_leaving_secure": false, "privacy.trackingprotection.fingerprinting.enabled": false, "browser.cache.disk.smart_size_cached_value": 1048576, "services.settings.server": "", "dom.performance.time_to_non_blank_paint.enabled": true, "browser.newtabpage.directory.ping": "", "extensions.update.enabled": false, "security.warn_entering_weak": false, "browser.pagethumbnails.capturing_disabled": true, "browser.bookmarks.restore_default_bookmarks": false, "signon.management.page.breach-alerts.enabled": false, "services.sync.migrated": true, "browser.search.update": false, "devtools.chrome.enabled": true, "extensions.checkCompatibility": false, "browser.startup.page": 0, "signon.management.page.enabled": false, "browser.sessionstore.resume_from_crash": false, "privacy.trackingprotection.pbmode.enabled": false, "browser.startup.homepage": "about:blank", "extensions.autoDisableScopes": 14, "browser.uitour.enabled": false, "datareporting.healthreport.service.firstRun": false, "browser.safebrowsing.phishing.enabled": false, "browser.safebrowsing.remotelookups": false, "javascript.options.asyncstack": false, "toolkit.telemetry.enabled": false, "signon.rememberSignons": false, "browser.newtab.preload": false, "dom.webnotifications.enabled": false, "browser.messaging-system.whatsNewPanel.enabled": false, "datareporting.policy.dataSubmissionEnabled": false, "browser.contentblocking.report.monitor.enabled": false, "signon.generation.enabled": false, "browser.safebrowsing.enabled": false, "browser.selfsupport.url": "", "datareporting.policy.dataSubmissionPolicyAccepted": false, "network.cookie.prefsMigrated": true, "browser.contentblocking.report.lockwise.enabled": false, "extensions.blocklist.itemURL": "", "browser.safebrowsing.downloads.enabled": false, "browser.newtabpage.introShown": true, "devtools.debugger.remote-enabled": true, "media.gmp-gmpopenh264.autoupdate": false, "browser.safebrowsing.downloads.remote.enabled": false, "extensions.blocklist.url": "", "dom.ipc.plugins.flash.disable-protected-mode": true, "privacy.trackingprotection.cryptomining.enabled": false, "privacy.trackingprotection.annotate_channels": false, "services.sync.engine.bookmarks": false, "media.mediacapabilities.from-database": false, "browser.newtabpage.directory.source": "data:application/json,{}", "xpinstall.whitelist.add": "", "browser.messaging-system.fxatoolbarbadge.enabled": false, "browser.safebrowsing.provider.mozilla.updateURL": "", "dom.max_script_run_time": 0, "security.warn_viewing_mixed": false, "layers.acceleration.disabled": true, "browser.cache.disk.smart_size.first_run": false, "datareporting.healthreport.logging.consoleEnabled": false, "security.warn_entering_secure": false, "toolkit.telemetry.prompted": 2, "gfx.direct2d.disabled": true, "privacy.trackingprotection.enabled": false, "browser.shell.checkDefaultBrowser": false, "extensions.blocklist.update_enabled": false, "xpinstall.whitelist.add.36": "", "browser.selfsupport.enabled": false, "security.enable_java": false, "extensions.systemAddon.update.url": "", "network.captive-portal-service.enabled": false, "dom.performance.time_to_contentful_paint.enabled": true, "signon.management.page.breachAlertUrl": ""}}}, "firstMatch": [{}]}, "desiredCapabilities": {"acceptInsecureCerts": true, "browserName": "firefox", "moz:firefoxOptions": {"binary": "/usr/lib/firefox/firefox", "args": ["-profile", "/home/pmeenan/wptagent/work/ubuntu/browser.200530_TxGP_345327fb3c1c7c68ec8745a526098b1d.1"], "log": {"level": "error"}, "env": {"MOZ_LOG_FILE": "/home/pmeenan/wptagent/work/ubuntu/200530_TxGP_345327fb3c1c7c68ec8745a526098b1d.1.0/moz.log", "MOZ_LOG": "timestamp,nsHttp:5,nsSocketTransport:5nsHostResolver:5,pipnss:5"}, "prefs": {"browser.aboutHomeSnippets.updateUrl": "", "dom.max_chrome_script_run_time": 0, "dom.push.serverURL": "", "javascript.options.showInConsole": true, "browser.bookmarks.added_static_root": true, "intl.charsetmenu.browser.cache": "UTF-8", "app.update.enabled": false, "browser.safebrowsing.provider.mozilla.updateURL": "", "datareporting.healthreport.service.enabled": false, "browser.fixup.typo.scheme": false, "extensions.abuseReport.enabled": false, "browser.newtabpage.enhanced": false, "privacy.trackingprotection.socialtracking.enabled": false, "security.certerrors.mitm.priming.endpoint": "", "extensions.blocklist.detailsURL": "", "extensions.blocklist.enabled": false, "datareporting.healthreport.uploadEnabled": false, "browser.tabs.warnOnClose": false, "security.warn_viewing_mixed": false, "privacy.cpd.siteSettings": true, "extensions.shield-recipe-client.enabled": false, "geo.prompt.testing": true, "network.proxy.type": 0, "app.update.url": "", "signon.generation.enabled": false, "browser.places.importBookmarksHTML": false, "browser.newtabpage.activity-stream.feeds.snippets": false, "dom.performance.time_to_first_interactive.enabled": true, "browser.rights.3.shown": true, "extensions.shownSelectionUI": true, "toolkit.telemetry.rejected": true, "browser.safebrowsing.malware.enabled": false, "browser.startup.homepage_override.mstone": "ignore", "reader.parse-on-load.enabled": false, "pageThumbs.enabled": false, "dom.performance.time_to_dom_content_flushed.enabled": true, "geo.prompt.testing.allow": true, "browser.contentblocking.enabled": false, "browser.cache.disk.smart_size.first_run": false, "privacy.sanitize.migrateFx3Prefs": true, "pref.browser.homepage.disable_button.current_page": false, "security.certerrors.mitm.priming.enabled": false, "services.sync.prefs.sync.privacy.trackingprotection.pbmode.enabled": false, "browser.newtabpage.activity-stream.disableSnippets": true, "browser.newtabpage.enabled": false, "browser.safebrowsing.provider.mozilla.gethashURL": "", "extensions.update.notifyUser": false, "privacy.sanitize.timeSpan": 0, "toolkit.telemetry.reportingpolicy.firstRun": false, "dom.webnotifications.enabled": false, "browser.cache.disk.capacity": 1048576, "extensions.pocket.enabled": false, "security.warn_leaving_secure": false, "browser.messaging-system.fxatoolbarbadge.enabled": false, "browser.cache.disk.smart_size_cached_value": 1048576, "services.settings.server": "", "dom.performance.time_to_non_blank_paint.enabled": true, "browser.newtabpage.directory.ping": "", "extensions.update.enabled": false, "network.cookie.prefsMigrated": true, "browser.pagethumbnails.capturing_disabled": true, "browser.bookmarks.restore_default_bookmarks": false, "signon.management.page.breach-alerts.enabled": false, "services.sync.migrated": true, "browser.search.update": false, "devtools.chrome.enabled": true, "extensions.checkCompatibility": false, "browser.startup.page": 0, "privacy.trackingprotection.pbmode.enabled": false, "privacy.trackingprotection.fingerprinting.enabled": false, "browser.sessionstore.resume_from_crash": false, "signon.management.page.enabled": false, "browser.startup.homepage": "about:blank", "extensions.autoDisableScopes": 14, "browser.uitour.enabled": false, "datareporting.healthreport.service.firstRun": false, "browser.safebrowsing.phishing.enabled": false, "browser.safebrowsing.remotelookups": false, "javascript.options.asyncstack": false, "toolkit.telemetry.enabled": false, "signon.rememberSignons": false, "browser.newtab.preload": false, "extensions.fxmonitor.enabled": false, "browser.messaging-system.whatsNewPanel.enabled": false, "datareporting.policy.dataSubmissionEnabled": false, "browser.contentblocking.report.monitor.enabled": false, "devtools.sourcemap.locations.enabled": false, "browser.safebrowsing.enabled": false, "browser.selfsupport.url": "", "datareporting.policy.dataSubmissionPolicyAccepted": false, "security.warn_entering_weak": false, "browser.contentblocking.report.lockwise.enabled": false, "extensions.blocklist.itemURL": "", "browser.safebrowsing.downloads.enabled": false, "browser.newtabpage.introShown": true, "devtools.debugger.remote-enabled": true, "media.gmp-gmpopenh264.autoupdate": false, "browser.safebrowsing.downloads.remote.enabled": false, "extensions.blocklist.url": "", "dom.ipc.plugins.flash.disable-protected-mode": true, "privacy.trackingprotection.cryptomining.enabled": false, "privacy.trackingprotection.annotate_channels": false, "services.sync.engine.bookmarks": false, "media.mediacapabilities.from-database": false, "browser.newtabpage.directory.source": "data:application/json,{}", "xpinstall.whitelist.add": "", "services.sync.prefs.sync.privacy.trackingprotection.enabled": false, "datareporting.policy.dataSubmissionPolicyResponseType": "accepted-info-bar-dismissed", "dom.max_script_run_time": 0, "security.warn_submit_insecure": false, "layers.acceleration.disabled": true, "xpinstall.signatures.required": false, "datareporting.healthreport.logging.consoleEnabled": false, "security.warn_entering_secure": false, "toolkit.telemetry.prompted": 2, "gfx.direct2d.disabled": true, "privacy.trackingprotection.enabled": false, "browser.shell.checkDefaultBrowser": false, "extensions.blocklist.update_enabled": false, "xpinstall.whitelist.add.36": "", "browser.selfsupport.enabled": false, "security.enable_java": false, "extensions.systemAddon.update.url": "", "network.captive-portal-service.enabled": false, "dom.performance.time_to_contentful_paint.enabled": true, "signon.management.page.breachAlertUrl": ""}}, "marionette": true}}
13:06:44.619 - Starting new HTTP connection (1): 127.0.0.1:38237
13:07:44.676 - http://127.0.0.1:38237 "POST /session HTTP/1.1" 500 91
13:07:44.677 - Finished Request
13:07:44.678 - Error starting Firefox
Traceback (most recent call last):
  File "/home/pmeenan/wptagent/internal/firefox.py", line 178, in launch
    self.start_firefox(job, task)
  File "/home/pmeenan/wptagent/internal/firefox_webdriver.py", line 40, in start_firefox
    self.driver = webdriver.Firefox(desired_capabilities=capabilities)
  File "/home/pmeenan/.local/lib/python2.7/site-packages/selenium/webdriver/firefox/webdriver.py", line 174, in __init__
    keep_alive=True)
  File "/home/pmeenan/.local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/home/pmeenan/.local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/home/pmeenan/.local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/pmeenan/.local/lib/python2.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
TimeoutException: Message: Connection refused (os error 111)
```

If I pass the profile directory as a string, then it uses it as a template but creates a new temp profile that it deletes (though it does connect and work fine).

Here are the 2 different command-lines (from ps) that were actually used to launch the underlying Firefox instance (the second was with an explicit profile path):

```
/usr/lib/firefox/firefox -marionette -foreground -no-remote -profile /tmp/rust_mozprofile7bOS2G
/usr/lib/firefox/firefox -marionette -profile /home/pmeenan/wptagent/work/ubuntu/browser.200530_TxXS_fed222a60b9c4b4ced4697c400862af4.1 -foreground -no-remote
```

It feels like I'm missing something in my profile directory that webdriver needs and sets up when it creates one off of my template (though that's just a guess).

**Comment by pmeenan** [comment]
Also happy to upload a geckodriver trace if someone can let me know how to configure where it logs to or how to capture it. Changing the trace level in the options doesn't seem to do anything to the messages I get (which appear to be on the webdriver side).

**Comment by whimboo** [comment]
Yes, check issue #1058 for some guides. Especially you would have to tell geckodriver the Marionette port via `services_args`, and hard-code that in the profile via `marionette.port`.

**Comment by pmeenan** [comment]
That did it, works perfectly now, thank you!
