### ISSUE TITLE
[Docker] Timeout loading page - "Unable to autolaunch a dbus-daemon without a $DISPLAY for X11" 

### ISSUE THREAD

**Issue by mnakhaev** [mozilla/geckodriver#1727]
## System

* Version: geckodriver 0.26.0 (e9783a644016 2019-10-10 13:38 +0000)
* Platform: CentOS Linux release 7.6.1810
* Firefox: firefox.x86_64 68.8.0-1.el7.centos
* Selenium (Python): 3.141.0

## Testcase

Hi all,
I'm running a simple script with Selenium + Python from documentation inside of Docker container.

Here's the command for container deployment:
```
docker run -t -d -u 0:0 --net=host <centos_image> cat
```

Here's the script:
```
from selenium import webdriver
from selenium.webdriver import FirefoxOptions
from selenium.webdriver.common.keys import Keys

ff_options = webdriver.FirefoxOptions()
ff_options.add_argument("--headless")
driver = webdriver.Firefox(options=ff_options)
driver.set_page_load_timeout(10)
driver.get("http://www.python.org")
assert "Python" in driver.title
print("SUCCESS")
elem = driver.find_element_by_name("q")
elem.clear()
elem.send_keys("pycon")
elem.send_keys(Keys.RETURN)
assert "No results found." not in driver.page_source
print("SUCCESS")
driver.close()
```
But I started to receive a timeout errors not long ago.
I don't really understand what could be the root cause.

## Stacktrace

```
Traceback (most recent call last):
  File "chanda.py", line 13, in <module>
    driver.get("http://www.python.org")
  File "/usr/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/usr/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: Timeout loading page after 15000ms
```

## Trace-level log

```
Failed to open connection to "session" message bus: Unable to autolaunch a dbus-daemon without a $DISPLAY for X11
1590414245334   mozrunner::runner       INFO    Running command: "/usr/bin/firefox" "-marionette" "--headless" "-foreground" "-no-remote" "-profile" "/tmp/rust_mozprofileYlyf2a"
Failed to open connection to "session" message bus: Unable to autolaunch a dbus-daemon without a $DISPLAY for X11
Running without a11y support!
*** You are running in headless mode.
1590414246269   addons.webextension.screenshots@mozilla.org     WARN    Loading extension 'screenshots@mozilla.org': Reading manifest: Invalid extension permission: mozillaAddons
1590414246269   addons.webextension.screenshots@mozilla.org     WARN    Loading extension 'screenshots@mozilla.org': Reading manifest: Invalid extension permission: telemetry
1590414246269   addons.webextension.screenshots@mozilla.org     WARN    Loading extension 'screenshots@mozilla.org': Reading manifest: Invalid extension permission: resource://pdf.js/
1590414246270   addons.webextension.screenshots@mozilla.org     WARN    Loading extension 'screenshots@mozilla.org': Reading manifest: Invalid extension permission: about:reader*
JavaScript error: undefined, line 14: Error: An unexpected error occurred
JavaScript error: moz-extension://045d3afb-e559-40f1-8777-983a8b1fbba0/lib/picture_in_picture_overrides.js, line 15: Error: Incorrect argument types for pictureInPictureParent.setOverrides.
JavaScript error: resource:///modules/sessionstore/SessionStore.jsm, line 1325: uncaught exception: 2147746065
1590414249955   Marionette      INFO    Listening on port 39235
1590414249994   Marionette      WARN    TLS certificate errors will be ignored for this session
```

Could you please advice?

**Comment by whimboo** [comment]
Could you please attach a [trace-level log] from geckodriver? Read more about reporting actionable bugs in our [contribution guidelines].

[trace-level log]: https://firefox-source-docs.mozilla.org/testing/geckodriver/TraceLogs.html
[contribution guidelines]: https://firefox-source-docs.mozilla.org/testing/geckodriver/Bugs.html

**Comment by mnakhaev** [comment]
Here it is:
```
Failed to open connection to "session" message bus: Unable to autolaunch a dbus-daemon without a $DISPLAY for X11
1590477196587	mozrunner::runner	INFO	Running command: "/usr/bin/firefox" "-marionette" "--headless" "-foreground" "-no-remote" "-profile" "/tmp/rust_mozprofileRMFvVS"
1590477196589	geckodriver::marionette	DEBUG	Waiting 60s to connect to browser on 127.0.0.1:39077
Failed to open connection to "session" message bus: Unable to autolaunch a dbus-daemon without a $DISPLAY for X11
Running without a11y support!
*** You are running in headless mode.
1590477197492	addons.webextension.screenshots@mozilla.org	WARN	Loading extension 'screenshots@mozilla.org': Reading manifest: Invalid extension permission: mozillaAddons
1590477197492	addons.webextension.screenshots@mozilla.org	WARN	Loading extension 'screenshots@mozilla.org': Reading manifest: Invalid extension permission: telemetry
1590477197493	addons.webextension.screenshots@mozilla.org	WARN	Loading extension 'screenshots@mozilla.org': Reading manifest: Invalid extension permission: resource://pdf.js/
1590477197493	addons.webextension.screenshots@mozilla.org	WARN	Loading extension 'screenshots@mozilla.org': Reading manifest: Invalid extension permission: about:reader*
1590477197681	Marionette	TRACE	Received observer notification profile-after-change
1590477197730	Marionette	TRACE	Received observer notification command-line-startup
1590477197730	Marionette	TRACE	Received observer notification nsPref:changed
1590477197731	Marionette	DEBUG	Init aborted (running=false, enabled=true, finalUIStartup=false)
1590477197880	Marionette	TRACE	Received observer notification toplevel-window-ready
JavaScript error: undefined, line 14: Error: An unexpected error occurred
JavaScript error: moz-extension://f459b40a-c887-43c0-b8dd-7377fb01b68f/lib/picture_in_picture_overrides.js, line 15: Error: Incorrect argument types for pictureInPictureParent.setOverrides.
JavaScript error: resource:///modules/sessionstore/SessionStore.jsm, line 1325: uncaught exception: 2147746065
1590477200407	Marionette	TRACE	Received observer notification marionette-startup-requested
1590477200407	Marionette	TRACE	Waiting until startup recorder finished recording startup scripts...
1590477200418	Marionette	TRACE	All scripts recorded.
1590477200419	Marionette	DEBUG	Setting recommended pref apz.content_response_timeout to 60000
1590477200419	Marionette	DEBUG	Setting recommended pref browser.contentblocking.introCount to 99
1590477200420	Marionette	DEBUG	Setting recommended pref browser.download.panel.shown to true
1590477200420	Marionette	DEBUG	Setting recommended pref browser.newtabpage.enabled to false
1590477200421	Marionette	DEBUG	Setting recommended pref browser.pagethumbnails.capturing_disabled to true
1590477200421	Marionette	DEBUG	Setting recommended pref browser.search.update to false
1590477200422	Marionette	DEBUG	Setting recommended pref browser.tabs.disableBackgroundZombification to false
1590477200422	Marionette	DEBUG	Setting recommended pref browser.tabs.remote.separatePrivilegedContentProcess to false
1590477200422	Marionette	DEBUG	Setting recommended pref browser.tabs.unloadOnLowMemory to false
1590477200423	Marionette	DEBUG	Setting recommended pref browser.tabs.warnOnCloseOtherTabs to false
1590477200423	Marionette	DEBUG	Setting recommended pref browser.tabs.warnOnOpen to false
1590477200423	Marionette	DEBUG	Setting recommended pref browser.usedOnWindows10.introURL to 
1590477200423	Marionette	DEBUG	Setting recommended pref browser.urlbar.suggest.searches to false
1590477200424	Marionette	DEBUG	Setting recommended pref datareporting.policy.dataSubmissionPolicyAccepted to false
1590477200424	Marionette	DEBUG	Setting recommended pref dom.disable_beforeunload to true
1590477200424	Marionette	DEBUG	Setting recommended pref dom.disable_open_during_load to false
1590477200424	Marionette	DEBUG	Setting recommended pref dom.file.createInChild to true
1590477200425	Marionette	DEBUG	Setting recommended pref dom.max_chrome_script_run_time to 0
1590477200425	Marionette	DEBUG	Setting recommended pref dom.max_script_run_time to 0
1590477200426	Marionette	DEBUG	Setting recommended pref extensions.getAddons.cache.enabled to false
1590477200426	Marionette	DEBUG	Setting recommended pref extensions.webservice.discoverURL to http://%(server)s/dummy/discoveryURL
1590477200426	Marionette	DEBUG	Setting recommended pref network.http.prompt-temp-redirect to false
1590477200426	Marionette	DEBUG	Setting recommended pref network.http.speculative-parallel-limit to 0
1590477200426	Marionette	DEBUG	Setting recommended pref security.fileuri.strict_origin_policy to false
1590477200427	Marionette	DEBUG	Setting recommended pref security.notification_enable_delay to 0
1590477200427	Marionette	DEBUG	Setting recommended pref signon.autofillForms to false
1590477200427	Marionette	DEBUG	Setting recommended pref signon.rememberSignons to false
1590477200428	Marionette	DEBUG	Setting recommended pref toolkit.cosmeticAnimations.enabled to false
1590477200495	Marionette	INFO	Listening on port 39077
1590477200496	Marionette	DEBUG	Remote service is active
1590477200517	Marionette	DEBUG	Accepted connection 0 from 127.0.0.1:57818
1590477200519	geckodriver::marionette	DEBUG	Connection to Marionette established on 127.0.0.1:39077.
1590477200526	Marionette	DEBUG	0 -> [0,1,"WebDriver:NewSession",{"acceptInsecureCerts":true,"browserName":"firefox"}]
1590477200527	Marionette	WARN	TLS certificate errors will be ignored for this session
1590477200576	Marionette	TRACE	[4294967297] Frame script loaded
1590477200579	Marionette	TRACE	[4294967297] Frame script registered
1590477200588	Marionette	DEBUG	0 <- [1,1,null,{"sessionId":"c16c0c6f-c789-412b-b2be-784759342aa6","capabilities":{"browserName":"firefox","browserVersion":"68.8. ... /rust_mozprofileRMFvVS","moz:shutdownTimeout":60000,"moz:useNonSpecCompliantPointerOrigin":false,"moz:webdriverClick":true}}]
1590477200595	webdriver::server	DEBUG	<- 200 OK {"value":{"sessionId":"c16c0c6f-c789-412b-b2be-784759342aa6","capabilities":{"acceptInsecureCerts":true,"browserName":"firefox","browserVersion":"68.8.0","moz:accessibilityChecks":false,"moz:buildID":"20200507181246","moz:geckodriverVersion":"0.26.0","moz:headless":true,"moz:processID":5910,"moz:profile":"/tmp/rust_mozprofileRMFvVS","moz:shutdownTimeout":60000,"moz:useNonSpecCompliantPointerOrigin":false,"moz:webdriverClick":true,"pageLoadStrategy":"normal","platformName":"linux","platformVersion":"4.18.0-147.5.1.el8_1.x86_64","rotatable":false,"setWindowRect":true,"strictFileInteractability":false,"timeouts":{"implicit":0,"pageLoad":300000,"script":30000},"unhandledPromptBehavior":"dismiss and notify"}}}
1590477200599	webdriver::server	DEBUG	-> POST /session/c16c0c6f-c789-412b-b2be-784759342aa6/timeouts {"pageLoad": 10000}
1590477200603	Marionette	DEBUG	0 -> [0,2,"WebDriver:SetTimeouts",{"pageLoad":10000}]
1590477200604	Marionette	DEBUG	0 <- [1,2,null,{"value":null}]
1590477200611	webdriver::server	DEBUG	<- 200 OK {"value":null}
1590477200614	webdriver::server	DEBUG	-> POST /session/c16c0c6f-c789-412b-b2be-784759342aa6/url {"url": "http://www.python.org"}
1590477200645	Marionette	DEBUG	0 -> [0,3,"WebDriver:Navigate",{"url":"http://www.python.org"}]
1590477200732	Marionette	TRACE	[4294967297] Received DOM event beforeunload for about:blank
1590477220399	Marionette	DEBUG	0 <- [1,3,{"error":"timeout","message":"Timeout loading page after 10000ms","stacktrace":"WebDriverError@chrome://marionette/conte ... 5:5\nTimeoutError@chrome://marionette/content/error.js:444:5\nnotify@chrome://marionette/content/listener.js:371:11\n"},null]
1590477239492	webdriver::server	DEBUG	<- 500 Internal Server Error {"value":{"error":"timeout","message":"Timeout loading page after 10000ms","stacktrace":"WebDriverError@chrome://marionette/content/error.js:175:5\nTimeoutError@chrome://marionette/content/error.js:444:5\nnotify@chrome://marionette/content/listener.js:371:11\n"}}
```

**Comment by whimboo** [comment]
Thanks! The page you are requesting never gets loaded. I even don't see the `unload` event that should be listed in the log. There is only the `beforeunload` event visible. 

How does it look like in non-headless mode with the display environment variable specified? For me this looks like a problem with Firefox but not geckodriver.

**Comment by mnakhaev** [comment]
Thanks for your answer.

Sorry, but cannot check it in non-headless mode since I get another error when starting GUI applications:
```
process 1317: D-Bus library appears to be incorrectly set up; failed to read machine uuid: UUID file '/etc/machine-id' should contain a hex string of length 32, not length 0, with no other text
See the manual page for dbus-uuidgen to correct this issue.
  D-Bus not built with -rdynamic so unable to print a backtrace
1590509661714	mozrunner::runner	INFO	Running command: "/usr/bin/firefox" "-marionette" "-foreground" "-no-remote" "-profile" "/tmp/rust_mozprofileRXcyY4"
1590509661728	geckodriver::marionette	DEBUG	Waiting 60s to connect to browser on 127.0.0.1:35991
process 1334: D-Bus library appears to be incorrectly set up; failed to read machine uuid: UUID file '/etc/machine-id' should contain a hex string of length 32, not length 0, with no other text
See the manual page for dbus-uuidgen to correct this issue.
  D-Bus not built with -rdynamic so unable to print a backtrace
Running without a11y support!
No protocol specified
Error: cannot open display: :0
1590509662654	mozrunner::runner	DEBUG	Killing process 1326
1590509662655	webdriver::server	DEBUG	<- 500 Internal Server Error {"value":{"error":"unknown error","message":"invalid argument: can't kill an exited process","stacktrace":""}}
```

I didn't manage to find quick solution, will try more

**Comment by whimboo** [comment]
As I said you have to set the `DISPLAY=0:0` environment variable. The error `cannot open display: :0` describes it best.

**Comment by VictorJosso** [comment]
Hi, 

I'm experiencing the same issue. Here is the trace log : 
```
1594917369129	mozrunner::runner	INFO	Running command: "/usr/bin/firefox" "-marionette" "-headless" "-foreground" "-no-remote" "-profile" "/tmp/rust_mozprofileWWrRhX"
1594917369129	geckodriver::marionette	DEBUG	Waiting 60s to connect to browser on 127.0.0.1:39367
*** You are running in headless mode.
1594917369398	addons.webextension.screenshots@mozilla.org	WARN	Loading extension 'screenshots@mozilla.org': Reading manifest: Invalid extension permission: mozillaAddons
1594917369398	addons.webextension.screenshots@mozilla.org	WARN	Loading extension 'screenshots@mozilla.org': Reading manifest: Invalid extension permission: telemetry
1594917369398	addons.webextension.screenshots@mozilla.org	WARN	Loading extension 'screenshots@mozilla.org': Reading manifest: Invalid extension permission: resource://pdf.js/
1594917369398	addons.webextension.screenshots@mozilla.org	WARN	Loading extension 'screenshots@mozilla.org': Reading manifest: Invalid extension permission: about:reader*
1594917369468	Marionette	TRACE	Received observer notification profile-after-change
1594917369504	Marionette	TRACE	Received observer notification command-line-startup
1594917369504	Marionette	TRACE	Received observer notification nsPref:changed
1594917369504	Marionette	DEBUG	Init aborted (running=false, enabled=true, finalUIStartup=false)
1594917369549	Marionette	TRACE	Received observer notification toplevel-window-ready
JavaScript error: undefined, line 14: Error: An unexpected error occurred
JavaScript error: moz-extension://96f07e7d-d16f-49f0-b158-592881344515/lib/picture_in_picture_overrides.js, line 15: Error: Incorrect argument types for pictureInPictureParent.setOverrides.
JavaScript error: resource:///modules/sessionstore/SessionStore.jsm, line 1325: uncaught exception: 2147746065
1594917370356	Marionette	TRACE	Received observer notification marionette-startup-requested
1594917370356	Marionette	TRACE	Waiting until startup recorder finished recording startup scripts...
1594917370396	Marionette	TRACE	All scripts recorded.
1594917370396	Marionette	DEBUG	Setting recommended pref apz.content_response_timeout to 60000
1594917370396	Marionette	DEBUG	Setting recommended pref browser.contentblocking.introCount to 99
1594917370396	Marionette	DEBUG	Setting recommended pref browser.download.panel.shown to true
1594917370396	Marionette	DEBUG	Setting recommended pref browser.newtabpage.enabled to false
1594917370397	Marionette	DEBUG	Setting recommended pref browser.pagethumbnails.capturing_disabled to true
1594917370397	Marionette	DEBUG	Setting recommended pref browser.search.update to false
1594917370397	Marionette	DEBUG	Setting recommended pref browser.tabs.disableBackgroundZombification to false
1594917370397	Marionette	DEBUG	Setting recommended pref browser.tabs.remote.separatePrivilegedContentProcess to false
1594917370397	Marionette	DEBUG	Setting recommended pref browser.tabs.unloadOnLowMemory to false
1594917370397	Marionette	DEBUG	Setting recommended pref browser.tabs.warnOnCloseOtherTabs to false
1594917370397	Marionette	DEBUG	Setting recommended pref browser.tabs.warnOnOpen to false
1594917370397	Marionette	DEBUG	Setting recommended pref browser.usedOnWindows10.introURL to 
1594917370398	Marionette	DEBUG	Setting recommended pref browser.urlbar.suggest.searches to false
1594917370398	Marionette	DEBUG	Setting recommended pref datareporting.policy.dataSubmissionPolicyAccepted to false
1594917370398	Marionette	DEBUG	Setting recommended pref dom.disable_beforeunload to true
1594917370398	Marionette	DEBUG	Setting recommended pref dom.disable_open_during_load to false
1594917370398	Marionette	DEBUG	Setting recommended pref dom.file.createInChild to true
1594917370398	Marionette	DEBUG	Setting recommended pref dom.max_chrome_script_run_time to 0
1594917370398	Marionette	DEBUG	Setting recommended pref dom.max_script_run_time to 0
1594917370398	Marionette	DEBUG	Setting recommended pref extensions.getAddons.cache.enabled to false
1594917370398	Marionette	DEBUG	Setting recommended pref extensions.webservice.discoverURL to http://%(server)s/dummy/discoveryURL
1594917370398	Marionette	DEBUG	Setting recommended pref network.http.prompt-temp-redirect to false
1594917370399	Marionette	DEBUG	Setting recommended pref network.http.speculative-parallel-limit to 0
1594917370399	Marionette	DEBUG	Setting recommended pref security.fileuri.strict_origin_policy to false
1594917370399	Marionette	DEBUG	Setting recommended pref security.notification_enable_delay to 0
1594917370399	Marionette	DEBUG	Setting recommended pref signon.autofillForms to false
1594917370399	Marionette	DEBUG	Setting recommended pref signon.rememberSignons to false
1594917370399	Marionette	DEBUG	Setting recommended pref toolkit.cosmeticAnimations.enabled to false
1594917370428	Marionette	INFO	Listening on port 39367
1594917370428	Marionette	DEBUG	Remote service is active
1594917370432	Marionette	DEBUG	Accepted connection 0 from 127.0.0.1:56364
1594917370432	geckodriver::marionette	DEBUG	Connection to Marionette established on 127.0.0.1:39367.
1594917370435	Marionette	DEBUG	0 -> [0,1,"WebDriver:NewSession",{"acceptInsecureCerts":true,"browserName":"firefox"}]
1594917370435	Marionette	WARN	TLS certificate errors will be ignored for this session
1594917370454	Marionette	TRACE	[4294967297] Frame script loaded
1594917370455	Marionette	TRACE	[4294967297] Frame script registered
1594917370457	Marionette	DEBUG	0 <- [1,1,null,{"sessionId":"f5deaab2-49c0-47b9-9ee0-5407a94b8c4c","capabilities":{"browserName":"firefox","browserVersion":"68.10 ... /rust_mozprofileWWrRhX","moz:shutdownTimeout":60000,"moz:useNonSpecCompliantPointerOrigin":false,"moz:webdriverClick":true}}]
1594917370459	webdriver::server	DEBUG	<- 200 OK {"value":{"sessionId":"f5deaab2-49c0-47b9-9ee0-5407a94b8c4c","capabilities":{"acceptInsecureCerts":true,"browserName":"firefox","browserVersion":"68.10.0","moz:accessibilityChecks":false,"moz:buildID":"20200622191537","moz:geckodriverVersion":"0.26.0","moz:headless":true,"moz:processID":11987,"moz:profile":"/tmp/rust_mozprofileWWrRhX","moz:shutdownTimeout":60000,"moz:useNonSpecCompliantPointerOrigin":false,"moz:webdriverClick":true,"pageLoadStrategy":"normal","platformName":"linux","platformVersion":"5.4.0-0.bpo.4-amd64","rotatable":false,"setWindowRect":true,"strictFileInteractability":false,"timeouts":{"implicit":0,"pageLoad":300000,"script":30000},"unhandledPromptBehavior":"dismiss and notify"}}}
1594917407954	webdriver::server	DEBUG	-> POST /session/f5deaab2-49c0-47b9-9ee0-5407a94b8c4c/url {"url": "https://www.google.fr"}
1594917407957	Marionette	DEBUG	0 -> [0,2,"WebDriver:Navigate",{"url":"https://www.google.fr"}]
1594917407990	Marionette	TRACE	[4294967297] Received DOM event beforeunload for about:blank
1594917408229	Marionette	TRACE	[4294967297] Received DOM event pagehide for about:blank
1594917408280	Marionette	TRACE	[4294967297] Received DOM event DOMContentLoaded for https://www.google.fr/
Exiting due to channel error.
Exiting due to channel error.
[Child 12119, Chrome_ChildThread] WARNING: pipe error (3): Connection reset by peer: file /build/firefox-esr-L21rmf/firefox-esr-68.10.0esr/ipc/chromium/src/chrome/common/ipc_channel_posix.cc, line 358
Exiting due to channel error.
```

Here is the code I used : 
```python
from selenium.webdriver.firefox.options import Options
from selenium.common.exceptions import NoSuchElementException
from selenium.webdriver import Firefox

opts = Options()
opts.headless = True
opts.log.level = "trace"
search_browser = Firefox(options=opts)
search_browser.get("https://www.google.fr")
```
When I hit enter after the last line, the processor of my server becomes overloaded, and the Firefox instance is consuming more and more RAM. So I have to press `CTRL+C`. As @whimboo asked, I have tried to run Firefox in non-headless mode :

```python
from selenium.webdriver.firefox.options import Options
from selenium.common.exceptions import NoSuchElementException
from selenium.webdriver import Firefox
import os

os.environ["DISPLAY"] = "0:0"
opts = Options()
opts.log.level = "trace"
search_browser = Firefox()
```
but I got this error :
```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/downloader/venv/lib/python3.7/site-packages/selenium/webdriver/firefox/webdriver.py", line 174, in __init__
    keep_alive=True)
  File "/root/downloader/venv/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/root/downloader/venv/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/root/downloader/venv/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/root/downloader/venv/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: invalid argument: can't kill an exited process
```
with these logs:
```
1594918174332	mozrunner::runner	INFO	Running command: "/usr/bin/firefox" "-marionette" "-foreground" "-no-remote" "-profile" "/tmp/rust_mozprofileunFqfN"
1594918174333	geckodriver::marionette	DEBUG	Waiting 60s to connect to browser on 127.0.0.1:43145
Unable to init server: Type d’affichage Broadway non pris en charge : 0:0
Error: cannot open display: 0:0
1594918174433	mozrunner::runner	DEBUG	Killing process 23638
1594918174433	webdriver::server	DEBUG	<- 500 Internal Server Error {"value":{"error":"unknown error","message":"invalid argument: can't kill an exited process","stacktrace":""}}
```

I don't know what is going on, it was fully functional a few days ago...

**Comment by whimboo** [comment]
@VictorJosso your issue is different. There is nothing about `Unable to autolaunch a dbus-daemon` in your logs. Please file as a separate issue for investigation. I will hide your comment on this issue. Thanks.

**Comment by whimboo** [comment]
@mnakhaev can you please give an update? Otherwise we have to close this issue. Thanks.

**Comment by VictorJosso** [comment]
@whimboo Oh sorry, yes that is right... I was misled by the trace logs which are quite the same... Anyway my issue solved by itself...

**Comment by whimboo** [comment]
Thanks for letting me know.
