### ISSUE TITLE
selenium.common.exceptions.SessionNotCreatedException: Message: Unable to find a matching set of capabilities

### ISSUE THREAD

**Issue by aonoa** [mozilla/geckodriver#1731]
## System

* Version: v0.26.0/v0.25.0
* Platform: Ubuntu 20.04
* Firefox: 77.0.1 (64bit)
* Selenium: python3.8 selenium3.141.0

## Testcase

driver = webdriver.Chrome(r"/home/xxx/work/untitled/venv/Scripts/geckodriver")

## Stacktrace

Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/home/mini/work/untitled/main.py", line 113, in run
    driver = webdriver.Chrome("/home/mini/work/untitled/venv/Scripts/geckodriver")
  File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/chrome/webdriver.py", line 76, in __init__
    RemoteWebDriver.__init__(
  File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: Unable to find a matching set of capabilities

**Comment by whimboo** [comment]
You cannot use the Webdriver.Chrome with geckodriver. You will need the appropriate class for Firefox.

**Comment by aonoa** [comment]
I'm too careless. Thank you for your correction


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Henrik Skupin"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月9日(星期二) 晚上8:02
收件人:&nbsp;"mozilla/geckodriver"<geckodriver@noreply.github.com&gt;;
抄送： &nbsp;“ Vantablack” <1991849113@qq.com&gt;;“作者” <author@noreply.github.com&gt;;
主题： &nbsp;回复：[mozilla / geckodriver] selenium.common.exceptions.SessionNotCreatedException：消息：找不到匹配的功能集（＃1731）





 
您不能将Webdriver.Chrome与geckodriver一起使用。您将需要适当的Firefox类。
  
— 
您收到此消息是因为您创建了线程。
直接回复此电子邮件，在GitHub上查看，或取消订阅。
