### ISSUE TITLE
Gecko driver is not supporting & working with selenium java

### ISSUE THREAD

**Issue by prasadarun** [mozilla/geckodriver#1733]
## System

* Version: v0.25.0
* Platform: windows
* Firefox:  57 version 
* Selenium: 3.141.59

I am getting the following error while launching firefox 

Exception in thread "main" org.openqa.selenium.WebDriverException: Cannot find firefox binary in PATH. Make sure firefox is installed. OS appears to be: WIN10
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:48'
System info: host: 'LIN20002489', ip: '192.168.43.105', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_181'
Driver info: driver.version: FirefoxDriver
	at org.openqa.selenium.firefox.FirefoxBinary.<init>(FirefoxBinary.java:100)
	at java.util.Optional.orElseGet(Optional.java:267)
	at org.openqa.selenium.firefox.FirefoxOptions.getBinary(FirefoxOptions.java:216)
	at org.openqa.selenium.firefox.FirefoxDriver.toExecutor(FirefoxDriver.java:187)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:147)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:125)
	at verification.firefox.main(firefox.java:11)

Note: https://firefox-source-docs.mozilla.org/testing/geckodriver/Support.html 
With above reference link i tried with different version of gecko driver

**Comment by whimboo** [comment]
Please re-test with geckodriver 0.26 and a more recent version of Firefox. The 57 release is way outdated. Also in which path is Firefox installed, and which operating system do you have? Is it 32bit or 64bit?

**Comment by whimboo** [comment]
No reply from reporter. Closing the issue.
