### ISSUE TITLE
UPDATE: Error: argument --profile requires a path

### ISSUE THREAD

**Issue by rbed23** [mozilla/geckodriver#1738]
## System

* Version: 0.26.0 (e9783a644016 2019-10-10 13:38 +0000)
* Platform: Windows 10 WSL Ubuntu
* Firefox: 77.0.1 (64-bit)
* Selenium: 3.141.0

## Testcase
```
from time import sleep
from selenium import webdriver

def run_test():
    browser = webdriver.Firefox()
    broswer.get('www.instagram.com')
    sleep(2)
    broswer.close()

if __name__ == "__main__":
    run_test()
```

## Stacktrace

> 
> Traceback (most recent call last):
>   File "browser_test.py", line 18, in <module>
>     run_test()
>   File "browser_test.py", line 7, in run_test
>     browser = webdriver.Firefox()
>   File "/home/rbednar/.local/share/virtualenvs/insta-bot-TTjU9tlD/lib/python3.7/site-packages/selenium/webdriver/firefox/webdriver.py", line 174, in __init__
>     keep_alive=True)
>   File "/home/rbednar/.local/share/virtualenvs/insta-bot-TTjU9tlD/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
>     self.start_session(capabilities, browser_profile)
>   File "/home/rbednar/.local/share/virtualenvs/insta-bot-TTjU9tlD/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
>     response = self.execute(Command.NEW_SESSION, parameters)
>   File "/home/rbednar/.local/share/virtualenvs/insta-bot-TTjU9tlD/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
>     self.error_handler.check_response(response)
>   File "/home/rbednar/.local/share/virtualenvs/insta-bot-TTjU9tlD/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
>     raise exception_class(message, screen, stacktrace)
> selenium.common.exceptions.SessionNotCreatedException: Message: Unable to find a matching set of capabilities

## Trace-level log

```
userr@BenderInspiron:/mnt/c/Users/User/Desktop/cli-git-folder/insta-bot$ curl -d '{"capabilities": {"alwaysMatch": {"acceptInsecureCerts": true}}}' http://localhost:4444/session
{"value":{"error":"session not created","message":"Unable to find a matching set of capabilities","stacktrace":""}}
```

**Comment by rbed23** [comment]
UPDATE: fixed the desired capabilities list, but now having issues with setting the Profile

I **have** set the profile path using the FirefoxProfile object (as well as object.profile = '/path/to/profile') but I get the same error logs on each attempt, headless or otherwise.

Would love to know what I am doing wrong... thanks!

```
from time import sleep
#import tempfile

from selenium import webdriver
from selenium.webdriver.firefox.firefox_binary import FirefoxBinary
from selenium.webdriver import DesiredCapabilities
from selenium.webdriver import FirefoxOptions
from selenium.webdriver import FirefoxProfile

capabilities = DesiredCapabilities.FIREFOX.copy()
capabilities['browserName'] = 'firefox'
capabilities['acceptInsecureCerts'] = False
capabilities['marionette'] = True

binary =  FirefoxBinary('/mnt/c/Program Files/Mozilla Firefox/firefox.exe')
profile = FirefoxProfile('/mnt/c/Users/User/AppData/Roaming/Mozilla/Firefox/Profiles/random.selenium')
options = FirefoxOptions()

#profile = tempfile.mkdtemp('.selenium')
#print("*** Using profile: {}".format(profile))
def run_test():
    options.headless = True
    options.log.level = "trace"
    options.profile = profile
    options.binary = binary
    
    driver = webdriver.Firefox(
        options=options,
        capabilities=capabilities,
        executable_path="/usr/bin/geckodriver",
        service_args=["--marionette-port", "2828"])

    driver.get('www.selenium.com')
    sleep(5)
    driver.close()

if __name__ == "__main__":
    run_test()
```

geckdriver.log output
```
1593267483499	mozrunner::runner	INFO	Running command: "/mnt/c/Program Files/Mozilla Firefox/firefox.exe" "-marionette" "-headless" "-foreground" "-no-remote" "-profile" "/tmp/rust_mozprofilefQWr5E"
1593267483501	geckodriver::marionette	DEBUG	Waiting 60s to connect to browser on 127.0.0.1:58988
*** You are running in headless mode.
Error: argument --profile requires a path
1593267518812	mozrunner::runner	INFO	Running command: "/mnt/c/Program Files/Mozilla Firefox/firefox.exe" "-marionette" "-headless" "-foreground" "-no-remote" "-profile" "/tmp/rust_mozprofileM5BSJj"
1593267518816	geckodriver::marionette	DEBUG	Waiting 60s to connect to browser on 127.0.0.1:59924
*** You are running in headless mode.
Error: argument --profile requires a path
1593267578893	mozrunner::runner	DEBUG	Killing process 8559
1593267578894	webdriver::server	DEBUG	<- 500 Internal Server Error {"value":{"error":"timeout","message":"connection refused","stacktrace":""}}
1593268331229	mozrunner::runner	INFO	Running command: "/mnt/c/Program Files/Mozilla Firefox/firefox.exe" "-marionette" "-headless" "-foreground" "-no-remote" "-profile" "/tmp/rust_mozprofileBErRMS"
1593268331231	geckodriver::marionette	DEBUG	Waiting 60s to connect to browser on 127.0.0.1:2828
*** You are running in headless mode.
Error: argument --profile requires a path
1593268391232	mozrunner::runner	DEBUG	Killing process 8617
1593268391233	webdriver::server	DEBUG	<- 500 Internal Server Error {"value":{"error":"timeout","message":"connection refused","stacktrace":""}}
```

**Comment by rbed23** [comment]
and here is my FirefoxProfile object info, so Im confident that the Profile path supplied is correct(?):

```
*** Using profile: <selenium.webdriver.firefox.firefox_profile.FirefoxProfile object at 0x7fc2567fe710>
{
    "default_preferences": "{'browser.dom.window.dump.enabled': True, 'browser (<<<---truncated at 50 chars)",
    "extensionsDir": "/tmp/tmp8ig_d90g/webdriver-py-profilecopy/extensions",
    "profile_dir": "/tmp/tmp8ig_d90g/webdriver-py-profilecopy",
    "tempfolder": "/tmp/tmp8ig_d90g",
    "userPrefs": "/tmp/tmp8ig_d90g/webdriver-py-profilecopy/user.js"
}
```

**Comment by rbed23** [comment]
Was using the incorrect 'executable_path' file for my actual platform...

Geckodriver Version: 0.26.0 (e9783a644016 2019-10-10 13:38 +0000)
Platform: Windows 10 WSL Ubuntu
Firefox: 77.0.1 (64-bit)
Selenium: 3.141.0

I should have been using the .exe extension for my Windows machine

```
from time import sleep
from selenium import webdriver
from vars_handler import show_vars


def run_test():
    driver = webdriver.Firefox(
        executable_path="/usr/bin/geckodriver.exe"
        )
    show_vars(driver, 100)
    driver.get('https://www.test.com')
    sleep(5)
    driver.close()


if __name__ == "__main__":
    run_test()
```

Cleared all of my options + capabilities and it's now working correctly.
