### ISSUE TITLE
Problem to take a screenshot of a site with selenium and geckodriver

### ISSUE THREAD

**Issue by NotiScol** [mozilla/geckodriver#1749]
## System

* **Version:** geckodriver-v0.26.0-linux64
* **Platform:**  Linux debian 10
* **Firefox:** Mozilla Firefox 68.10.0esr
* **Selenium:** selenium Version: 3.141.0

## Testcase

Hi,
I am trying to run this script on my virtual machine(debian 10) and it works but when I run on my server(also debian 10)  the program does not stop and runs continuously. I am using the following script:

```
import sys
from selenium import webdriver

options = webdriver.FirefoxOptions()

options.headless = True
options.log.level = "trace"

driver = webdriver.Firefox(executable_path='/home/production/screenshot/driver/geckodriver',options=options)

driver.get("https://google.com/")

element = driver.find_element_by_tag_name('body')

png = element.screenshot_as_png

with open('img.png','wb') as file:
        file.write(png)

driver.quit()
```

## Stacktrace

When I stop the program, this is what python displays to me:

```
Traceback (most recent call last):
File "screen.py", line 11, in <module>
driver.get("https://google.com/")
File "/home/production/.local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
self.execute(Command.GET, {'url': url})
File "/home/production/.local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 319, in execute
response = self.command_executor.execute(driver_command, params)
File "/home/production/.local/lib/python2.7/site-packages/selenium/webdriver/remote/remote_connection.py", line 374, in execute
return self._request(command_info[0], url, body=data)
File "/home/production/.local/lib/python2.7/site-packages/selenium/webdriver/remote/remote_connection.py", line 397, in _request
resp = self._conn.request(method, url, body=body, headers=headers)
File "/usr/local/lib/python2.7/dist-packages/urllib3/request.py", line 80, in request
method, url, fields=fields, headers=headers, **urlopen_kw
File "/usr/local/lib/python2.7/dist-packages/urllib3/request.py", line 171, in request_encode_body
return self.urlopen(method, url, **extra_kw)
File "/usr/local/lib/python2.7/dist-packages/urllib3/poolmanager.py", line 336, in urlopen
response = conn.urlopen(method, u.request_uri, **kw)
File "/usr/local/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 677, in urlopen
chunked=chunked,
File "/usr/local/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 417, in _make_request
httplib_response = conn.getresponse(buffering=True)
File "/usr/lib/python2.7/httplib.py", line 1137, in getresponse
response.begin()
File "/usr/lib/python2.7/httplib.py", line 448, in begin
version, status, reason = self._read_status()
File "/usr/lib/python2.7/httplib.py", line 404, in _read_status
line = self.fp.readline(_MAXLINE + 1)
File "/usr/lib/python2.7/socket.py", line 480, in readline
data = self._sock.recv(self._rbufsize)
```

## Trace-level log
[geckodriver.log](https://github.com/mozilla/geckodriver/files/4977001/geckodriver.log)

Thank you !

**Comment by whimboo** [comment]
I can see a couple of `Connection reset by peer` entries in the trace log. That states that there are problems with the network connection. Are you running any firewall which might block local connections?

**Comment by NotiScol** [comment]
Thank you for your reply.
I haven't touched the firewall yet.
I have checked the rules and everything seems correct.
![iptables](https://user-images.githubusercontent.com/64222647/89918718-b00a6680-dbfa-11ea-9e6c-5d2584555121.PNG)

**Comment by whimboo** [comment]
Would you mind disabling it and trying again? Also please try to use the most recent Firefox 79 release for testing. Maybe it's a problem with Firefox 68 ESR.

**Comment by NotiScol** [comment]
Thank you it worked!
