### ISSUE TITLE
Unable to find a matching set of capabilities (gecko 0.27, FF 68, python selenium 3.141) 

### ISSUE THREAD

**Issue by DylannCordel** [mozilla/geckodriver#1761]
## System

* Version: 0.27 64bits
* Platform: Linux (Debian Buster)
* Firefox: 68.11.0esr (64 bits)
* Selenium: python selenium (via pip) 3.141.0

## Testcase

```python
from selenium import webdriver
webdriver.Firefox()
```

## Stacktrace

```
>>> from selenium import webdriver ; webdriver.Firefox()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "[...]python3.7/site-packages/selenium/webdriver/firefox/webdriver.py", line 174, in __init__
    keep_alive=True)
  File "[...]python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "[...]python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "[...]python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "[...]python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: Unable to find a matching set of capabilities
```

Tested with gecko v23 and v26 : it's ok. I dunno if I must report this issue here or in python-selenium but as there is a versions compatibility table here, maybe this table should be fixed by setting a minor Firefox version required ?

**Comment by thc202** [comment]
Looks like a duplicate of #1756, there's a geckodriver with the fix linked there.

**Comment by DylannCordel** [comment]
Seems you right @thc202 Sorry for the duplicate, I didn't find it with my keywords.
