### ISSUE TITLE
GeckoDriver does not run under IIS Processes for .Net

### ISSUE THREAD

**Issue by hightieryes** [mozilla/geckodriver#1767]
## System

* Version: 0.27.0
* Platform: Windows 10
* Firefox: 79.0
* Selenium: 3.141.0

## Testcase

        FirefoxDriverService service = FirefoxDriverService.CreateDefaultService(Environment.CurrentDirectory);
        service.FirefoxBinaryPath = @"C:\Program Files\Mozilla Firefox\firefox.exe";
        FirefoxDriver driver = new FirefoxDriver(service);

When trying to create a new GeckoDriver instance on an IIS worker thread (for instance, from a ASP.Net Core Web API project that's deployed to IIS), it results in the below error. This error does not occur in ChromeDriver. 

## Stacktrace

```
Exception: 
OpenQA.Selenium.WebDriverException: The HTTP request to the remote WebDriver server for URL http://localhost:51863/session timed out after 60 seconds.
 ---> System.Net.WebException: The operation has timed out.
   at System.Net.HttpWebRequest.GetResponse()
   at OpenQA.Selenium.Remote.HttpCommandExecutor.MakeHttpRequest(HttpRequestInfo requestInfo)
   --- End of inner exception stack trace ---
   at OpenQA.Selenium.Remote.HttpCommandExecutor.MakeHttpRequest(HttpRequestInfo requestInfo)
   at OpenQA.Selenium.Remote.HttpCommandExecutor.Execute(Command commandToExecute)
   at OpenQA.Selenium.Remote.DriverServiceCommandExecutor.Execute(Command commandToExecute)
   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary 2 parameters)
   at OpenQA.Selenium.Remote.RemoteWebDriver.StartSession(ICapabilities desiredCapabilities)
   at OpenQA.Selenium.Remote.RemoteWebDriver..ctor(ICommandExecutor commandExecutor, ICapabilities desiredCapabilities)
   at OpenQA.Selenium.Firefox.FirefoxDriver..ctor(FirefoxDriverService service, FirefoxOptions options, TimeSpan commandTimeout)
   at OpenQA.Selenium.Firefox.FirefoxDriver..ctor(FirefoxDriverService service, FirefoxOptions options)
   at WebApplication4.Controllers.TestController.InputMethod() in C:\Users\Administrator\source\repos\WebApplication4\WebApplication4\Controllers\TestController.cs:line 46
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Server.IIS.Core.IISHttpContextOfT`1.ProcessRequestAsync()
```

I also can't run the above code through Visual Studio when selecting "IIS Express" either. 

I receive the error message `

`"System.InvalidOperationException: 'Failed to start browser C:\Program Files\Mozilla Firefox\firefox.exe: The handle is invalid. (os error 6) (SessionNotCreated)".`

See this stackoverflow topic from all the way back in April where the issue was first publicly raised:
[https://stackoverflow.com/questions/61346662/selenium-with-geckodriver-dont-work-on-asp-net-core ](https://stackoverflow.com/questions/61346662/selenium-with-geckodriver-dont-work-on-asp-net-core)

Running through the console executable works just fine via Visual Studio.

This is a significant enough issue that's forcing people to use the ChromeDriver instead. 

Looking for some expert input here. Thanks guys.

EDIT:
After some investigation, I found that running in Visual Studio via IIS Express works with .NET Framework, but not with .NET Core. However, both .NET Core and .NET framework have the "The HTTP request to the remote WebDriver server for URL http://localhost:52443/session timed out after 60 seconds" error when the web application is deployed to IIS.

**Comment by ignacy130** [comment]
I'm experiencing the same issue on .NET 6 and 8 run via IIS Express. The issue didn't resolve itself overnight even when there was a restart :D

I get `"System.InvalidOperationException: 'Failed to start browser C:\Program Files\Mozilla Firefox\firefox.exe: The handle is invalid. (os error 6) (SessionNotCreated)".`

I can run geckodriver via test app and when running ASP .NET Core API as a project, not via IIS.

I can use edgedriver when running ASP .NET Core AP via IIS, just not geckodriver.
