### ISSUE TITLE
WebDriverException: Timed out waiting 45 seconds for Firefox to start

### ISSUE THREAD

**Issue by Dmilut** [mozilla/geckodriver#1778]
## System

    Version: 0.27.0
    Platform: Arch Linux 5.8.9-arch2-1
    Firefox: 80.0.1 (64-bit)
    Selenium: 3.141.59
    Java: openjdk-14.0.2

## Testcase
I'm trying to open a page in the browser but only a new window opens with a blank page.
Code is:
```
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.firefox.FirefoxDriverLogLevel;
import org.openqa.selenium.firefox.FirefoxOptions;

public class Test {

    public static void main(String[] args) {

        System.setProperty("webdriver.gecko.driver", "src/main/resources/geckodriver");
        FirefoxOptions options = new FirefoxOptions();
        options.setCapability("marionette", false);
        options.setLogLevel(FirefoxDriverLogLevel.TRACE);

        WebDriver driver = new FirefoxDriver(options);

        driver.get("http://google.com");

        driver.quit();

    }
}

```

## Stacktrace
Exception in thread "main" org.openqa.selenium.WebDriverException: Timed out waiting 45 seconds for Firefox to start.
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'arch', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '5.8.9-arch2-1', java.version: '14.0.2'
Driver info: driver.version: FirefoxDriver
	at org.openqa.selenium.firefox.XpiDriverService.waitUntilAvailable(XpiDriverService.java:247)
	at org.openqa.selenium.firefox.XpiDriverService.start(XpiDriverService.java:159)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:79)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:213)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:131)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:147)
	at Test.main(Test.java:15)
Caused by: org.openqa.selenium.net.UrlChecker$TimeoutException: Timed out waiting for [http://localhost:18496/hub/status] to be available after 45002 ms
	at org.openqa.selenium.net.UrlChecker.waitUntilAvailable(UrlChecker.java:100)
	at org.openqa.selenium.firefox.XpiDriverService.waitUntilAvailable(XpiDriverService.java:245)
	... 7 more
Caused by: java.util.concurrent.TimeoutException
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:204)
	at com.google.common.util.concurrent.SimpleTimeLimiter.callWithTimeout(SimpleTimeLimiter.java:156)
	at org.openqa.selenium.net.UrlChecker.waitUntilAvailable(UrlChecker.java:75)
	... 8 more

**Comment by whimboo** [comment]
Could you please attach a [trace-level log] from geckodriver? Read more about reporting actionable bugs in our [contribution guidelines].

[trace-level log]: https://firefox-source-docs.mozilla.org/testing/geckodriver/TraceLogs.html
[contribution guidelines]: https://firefox-source-docs.mozilla.org/testing/geckodriver/Bugs.html

**Comment by Dmilut** [comment]
Hello, I did it according to the guidelines for your link. I understand that this is not enough to fix the error, but I do not really understand how to help you. Please help me.

**Comment by whimboo** [comment]
No this is just a selenium stack trace but nothing from geckodriver. Please read the instructions carefully in how to provide a geckodriver trace log. Thanks.

**Comment by Dmilut** [comment]
Hello @whimboo,
As you can see in contribution guidelines we have only one way for providing trace log in java. This way is:

> Java
> 
> The Selenium Java client also comes with a org.openqa.selenium.firefox.FirefoxOptions helper for constructing the moz:firefoxOptions capabilities object:
> 
> FirefoxOptions options = new FirefoxOptions();
> options.setLogLevel(FirefoxDriverLogLevel.TRACE);
> WebDriver driver = new FirefoxDriver(options);
> 
> As with C#, the log output is helpfully propagated to stdout.

**Comment by whimboo** [comment]
Check for the geckodriver.log file in the current working dir.

**Comment by Dmilut** [comment]
Hello @whimboo ,
Naturally, I checked my entire working directory and did not find the log file there.
For the sake of cleanliness, I tried to do it with two IDEs - Intellij Idea and Eclipse and got the same result.
I have also posted the project code on github here [(https://github.com/Dmilut/selenium-webdriver)]
Is there any other way I can help with this proceeding?
Thank you for your time!

**Comment by whimboo** [comment]
Sorry, but please get this information from the Selenium community. They should know where log files are getting created. It's basically outside of our scope. Please report back once you have the information. Otherwise we cannot help and have to close the issue.
