### ISSUE TITLE
Message: Unable to find a matching set of capabilities

### ISSUE THREAD

**Issue by sorushsaghari** [mozilla/geckodriver#1785]
## System

* Version 0.27
* Platform: Linux 5.8.11-1-MANJARO #1  x86_64 GNU/Linux
* Firefox 81.0-2
* Selenium: 3.141.0

## Testcase
```
opts = Options()
opts.log.level = "trace"
browser = webdriver.Firefox(options=opts, executable_path='/usr/local/bin/geckodriver')
browser.get('google.com')
browser.quit()
```

## Stacktrace
Traceback (most recent call last):
  File "getHtml.py", line 11, in <module>
    browser = webdriver.Firefox()
  File "/home/sorush/workspace/python/zabbix/zabbix-templates/externalscripts/venv/lib/python3.8/site-packages/selenium/webdriver/firefox/webdriver.py", line 170, in __init__
    RemoteWebDriver.__init__(
  File "/home/sorush/workspace/python/zabbix/zabbix-templates/externalscripts/venv/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/home/sorush/workspace/python/zabbix/zabbix-templates/externalscripts/venv/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/home/sorush/workspace/python/zabbix/zabbix-templates/externalscripts/venv/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/sorush/workspace/python/zabbix/zabbix-templates/externalscripts/venv/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: Unable to find a matching set of capabilities

## Trace-level log

1602055462021	geckodriver	INFO	Listening on 127.0.0.1:33703

**Comment by thc202** [comment]
Most likely #1756.

**Comment by sorushsaghari** [comment]
> Most likely #1756.

but it is not fixed

**Comment by whimboo** [comment]
From reading the issue I agree with the dupe suspicion. But to verify could you please attach a [trace-level log] from geckodriver? Read more about reporting actionable bugs in our [contribution guidelines].

[trace-level log]: https://firefox-source-docs.mozilla.org/testing/geckodriver/TraceLogs.html
[contribution guidelines]: https://firefox-source-docs.mozilla.org/testing/geckodriver/Bugs.html

**Comment by sorushsaghari** [comment]
> From reading the issue I agree with the dupe suspicion. But to verify could you please attach a [trace-level log](https://firefox-source-docs.mozilla.org/testing/geckodriver/TraceLogs.html) from geckodriver? Read more about reporting actionable bugs in our [contribution guidelines](https://firefox-source-docs.mozilla.org/testing/geckodriver/Bugs.html).



> From reading the issue I agree with the dupe suspicion. But to verify could you please attach a [trace-level log](https://firefox-source-docs.mozilla.org/testing/geckodriver/TraceLogs.html) from geckodriver? Read more about reporting actionable bugs in our [contribution guidelines](https://firefox-source-docs.mozilla.org/testing/geckodriver/Bugs.html).

updated

**Comment by whimboo** [comment]
There should have been more in the trace log as only this line. But anyway, maybe it's better to check this comment https://github.com/mozilla/geckodriver/issues/1756#issuecomment-673576170, and that you test this signed nightly build of geckodriver.
