### ISSUE TITLE
.get times out through automatic proxy without explicit pause at launch

### ISSUE THREAD

**Issue by essandess** [mozilla/geckodriver#1797]
`.get` times out on through an automatic (PAC) proxy without using an explicit pause at launch.

I confirm this on multiple macOS systems though multiple different proxies.

In the MWE below, this issue is mitigated by adding the `time.sleep(5)` line right after the driver is configured and launched. But this line is a hack and should not be necessary.

When using a direct connection without the proxy PAC file, the issue is not observed, suggesting that this has something to do with loading and processing the `proxy.pac` file before issuing a `.get`.

## System

* Version: 0.27.0
* Platform: macOS 10.15
* Firefox: 82.0
* Selenium: 3.141.0

## Testcase

```python
#!/usr/bin/env python3
#coding: utf-8

import lxml.html, os, signal, socket, time, urllib.parse as uprs, warnings as warn
from selenium import webdriver
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.firefox.options import Options

if True:
    user_agent = 'Mozilla/5.0 (Windows NT 10.0; WOW64; Trident/7.0; rv:11.0) like Gecko'
else:
    user_agent = 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1 Safari/605.1.15'
timeout = 45
short_timeout = 15
long_timeout = 90
implicit_wait = 10
# Tor browser size on Linux
window_size = (1296,1018)

# configure and launch geckodriver
options = Options()
options.headless = True
options.add_argument(f'--width={window_size[0]}')
options.add_argument(f'--height={window_size[1]}')
options.add_argument(f'--window-size={window_size[0], window_size[1]}')
firefox_profile = webdriver.FirefoxProfile()
firefox_profile.set_preference("general.useragent.override", user_agent)
# https://stackoverflow.com/questions/44748741/how-to-stop-selenium-page-loading
firefox_profile.set_preference('webdriver.load.strategy', 'unstable')
# Block images: http://kb.mozillazine.org/Permissions.default.image, https://support.mozilla.org/en-US/questions/1276813
firefox_profile.set_preference("extensions.contentblocker.enabled", True)
firefox_profile.set_preference("permissions.default.image", 2)
# mute audio
firefox_profile.set_preference("media.volume_scale", "0.0")
# proxy settings
# Direct = 0, Manual = 1, PAC = 2, AUTODETECT = 4, SYSTEM = 5
firefox_profile.set_preference('network.proxy.type', 5)

driver = webdriver.Firefox(firefox_profile=firefox_profile, options=options)

# timeouts
if timeout is not None: driver.set_page_load_timeout(timeout)
if timeout is not None: driver.set_script_timeout(timeout)
if False:
    if implicit_wait is not None: driver.implicitly_wait(implicit_wait)

# wait for and check geckodriver
# undocumented reality: must wait until the geckodriver process and service respond

# check process existence
os.kill(driver.service.process.pid, signal.SIG_DFL.value)

# check service
service_url_parse = uprs.urlparse(driver.service.service_url)
for _ in range(10):
    try:
        s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
        s.settimeout(1)
        s.connect((service_url_parse.hostname, int(service_url_parse.port)))
        break
    except:
        time.sleep(1)
    finally:
        s.shutdown(socket.SHUT_RDWR)
        s.close()
else:
    warn.warn('geckodriver service unavailable.')

# increase this time if geckodriver error is selenium.common.exceptions.TimeoutException or 'Remote end closed connection without response'
if True:
    time.sleep(5)

# get a web page
if True:
    url = 'https://www.google.com/search?q=foobar'
elif True:
    url = 'https://www.duckduckgo.com/?q=foobar'
else:
    url = 'https://en.wikipedia.org/wiki/Rust_(programming_language)'

WebDriverWait(driver, short_timeout)
driver.get(url)
assert len(lxml.html.fromstring(driver.page_source).xpath("body")[0].getchildren()) > 0, \
    f"Empty body returned for link '{url}'."
# print the first three text lines
print('\n'.join(lxml.html.fromstring(driver.page_source).text_content().strip().split('\n')[:2]))

# quit geckodriver
driver.close()
driver.quit()
```

## Stacktrace

System 1:

```
Traceback (most recent call last):
  File "./gd_mwe.py", line 82, in <module>
    driver.get(url)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: Timeout loading page after 45000ms
```

System 2:

```
Traceback (most recent call last):
  File "./gd_mwe.py", line 82, in <module>
    driver.get(url)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: Reached error page: about:neterror?e=proxyConnectFailure&u=https%3A//www.google.com/search%3Fq%3Dfoobar&c=UTF-8&d=Firefox%20is%20configured%20to%20use%20a%20proxy%20server%20that%20is%20refusing%20connections.
```

**Comment by whimboo** [comment]
You aren't using the proxy capabilities as defined in the WebDriver spec:
https://w3c.github.io/webdriver/#proxy

Does it work using those?

Also make sure to attach a [trace-level log] from geckodriver.

[trace-level log]: https://firefox-source-docs.mozilla.org/testing/geckodriver/TraceLogs.html

**Comment by essandess** [comment]
I see the exact same issue using the following approaches, which I believe are equivalent to the code above.

Approach 1:
```python
from selenium.webdriver.common.proxy import Proxy

proxy = Proxy(dict(proxyType="system"))

driver = webdriver.Firefox(firefox_profile=firefox_profile, proxy=proxy, options=options)
```

Approach 2:
```python
proxy = Proxy(dict(proxyType="PAC", proxyAutoconfigUrl="http://localhost/proxy.pac"))

driver = webdriver.Firefox(firefox_profile=firefox_profile, proxy=proxy, options=options)
```

**Comment by whimboo** [comment]
Ok, so can you please check which delay is needed before you are no longer seeing the `about:neterror?e=proxyConnectFailure` failures? As best create a loop iterating over `driver.get` until it succeeds.

Is that proxy always running and accepting connections? See the failure message that is printed via the `about:neterror` page: `Firefox is configured to use a proxy server that is refusing connections`. As it looks like the proxy doesn't allow Firefox to connect. How does the script work with other drivers like chromedriver? Doesn't it see those problems?

**Comment by whimboo** [comment]
No further reply. Closing the issue.
