### ISSUE TITLE
Unable to load extension

### ISSUE THREAD

**Issue by rakeshsthakur** [mozilla/geckodriver#180]
Hey Guys, I have been trying load an extension from the file system like below. 

```
FirefoxProfile firefoxProfile = null;
// Extension is as a xpi file 
File extensionFile = new File(seleniumProperties.getExtensionFirefox());
firefoxProfile = new FirefoxProfile();
firefoxProfile.addExtension(extensionFile);
// path to gecko driver
String webDriverFirefox = seleniumProperties.getWebDriverFireFox();
System.setProperty("webdriver.gecko.driver", webDriverFirefox);
WebDriver driver = null;
driver = new FirefoxDriver(firefoxProfile);
```

This starts the browser but extension is not being loaded, I have looked through few other tickets that have same topic but could not figure this out. 

Firefox version is 48
selenium : 3.0.0-beta2
gecko: 0.10.0

**Comment by andreastt** [comment]
Can you provide the full log from geckodriver’s stdout when giving it the `-vv` flag? After you initialise a session, can you also take a look in the generated profile directory to see if the extension is there?

**Comment by jgraham** [comment]
My suspicion is that the problem here is that geckodriver only supports loading extensions by creating a profile containing the extension and sending it as a base64-encoded zip file in the `firefox_profile` capability.

**Comment by rakeshsthakur** [comment]
@andreastt Sorry, but where can I set -vv flag? Do I have to do that from firefox.exe -marionette, if yes then I only see marionette.force-local setting there, I opened the session and when it was running I looked into Mozilla/Firefox/profiles/ in %appdata% directory but I did not see any profile being created. If I was supposed to look for else where let me know.

Following @jgraham idea/suspicion I was able to load the extension via pre-created profile which already had the extension installed. While this is helpful, having a option to side load add-on makes the whole automation much more simpler and cleaner. Hope i'm missing something that is not allowing me to side load the add-on.

**Comment by andreastt** [comment]
Based on that it’s not clear to me how calling `firefoxProfile.addExtension(extensionFile)` is any different to pre-populating a profile and passing this in using the `firefox_profile` capability.

If we consider [_FirefoxProfile#installExtensions_](https://github.com/SeleniumHQ/selenium/blob/master/java/client/src/org/openqa/selenium/firefox/FirefoxProfile.java#L438) in the Java bindings, they are written to file from memory before the profile is written to disk, zipped, Base64 encoded, and sent across as the wire.

Is the Java binding using the wrong capability, or is it assuming you’re connecting to the legacy FirefoxDriver?

@rakeshsthakur Can you try setting the `marionette` capability to true or using the `webdriver.firefox.marionette` Java VM property?

**Comment by gentoo90** [comment]
Is your extension signed?
Because according to [MDN](https://wiki.mozilla.org/Add-ons/Extension_Signing):

> Firefox 48: (Pushed from Firefox 46). Release and Beta versions of Firefox for Desktop will not allow unsigned extensions to be installed, with no override.

So to install an unsigned extension you'll need to downgrade firefox or to use a [special build](https://wiki.mozilla.org/Add-ons/Extension_Signing#Unbranded_Builds) which allows that.

**Comment by rakeshsthakur** [comment]
@andreastt Setting 	`Webdriver.firefox.marionette` to true did not help, 
Modified code:
```
		FirefoxProfile firefoxProfile = null;
		// Extension is as a xpi file 
		File extensionFile = new File(seleniumProperties.getExtensionFirefox());
		firefoxProfile = new FirefoxProfile();
		firefoxProfile.addExtension(extensionFile);
		// path to gecko driver
		String webDriverFirefox = seleniumProperties.getWebDriverFireFox();
		System.setProperty("webdriver.gecko.driver", webDriverFirefox);
		System.setProperty("Webdriver.firefox.marionette", "true");
		WebDriver driver = null;
		driver = new FirefoxDriver(firefoxProfile);
```

@gentoo90 Yes extension is signed that is how i'm able to install it and load it using profile.

**Comment by vladikoff** [comment]
> System.setProperty("webdriver.gecko.driver", webDriverFirefox);

I don't think setting does anything per: 
https://github.com/mozilla/geckodriver/issues/177

**Comment by rakeshsthakur** [comment]
@vladikoff That is needed if you want to load the driver from any other location that is not added to your system path.

**Comment by vladikoff** [comment]
@rakeshsthakur i don't think it does anything in selenium 3.0.0 beta 2, see https://github.com/SeleniumHQ/selenium/issues/2600 . that was merged 12 days ago

**Comment by rakeshsthakur** [comment]
For me if I don't specify the path to the driver (removing or commenting out that line) I get this exception.
```
Exception in thread "main" java.lang.IllegalStateException: The path to the driver executable must be set by the webdriver.gecko.driver system property; for more information, see https://github.com/mozilla/geckodriver. The latest version can be downloaded from https://github.com/mozilla/geckodriver/releases
```

**Comment by phystem** [comment]
I also couldn't load the extension with the geckodriver

> Firefox 49.0.1
> Windows 7 32 bit
> geckodriver 0.11 32bit

Extension is a signed one only..
```
org.openqa.selenium.firefox.NotConnectedException: Unable to connect to host 127.0.0.1 on port 7055 after 45000 ms. Firefox console output:
tzfirefox version 4.1.7
1476269755615	addons.xpi	DEBUG	Registering manifest for C:\Program Files\Mozilla Firefox\browser\features\e10srollout@mozilla.org.xpi
1476269755616	addons.xpi	DEBUG	Calling bootstrap method startup on e10srollout@mozilla.org version 1.2
1476269755616	addons.xpi	DEBUG	Registering manifest for C:\Program Files\Mozilla Firefox\browser\features\firefox@getpocket.com.xpi
1476269755617	addons.xpi	DEBUG	Calling bootstrap method startup on firefox@getpocket.com version 1.0.4
1476269755618	addons.xpi	DEBUG	Registering manifest for C:\Program Files\Mozilla Firefox\browser\features\webcompat@mozilla.org.xpi
1476269755618	addons.xpi	DEBUG	Calling bootstrap method startup on webcompat@mozilla.org version 1.0
1476269755620	addons.manager	DEBUG	Registering shutdown blocker for XPIProvider
1476269755620	addons.manager	DEBUG	Provider finished startup: XPIProvider
1476269755620	addons.manager	DEBUG	Starting provider: LightweightThemeManager
1476269755620	addons.manager	DEBUG	Registering shutdown blocker for LightweightThemeManager
1476269755620	addons.manager	DEBUG	Provider finished startup: LightweightThemeManager
1476269755620	addons.manager	DEBUG	Starting provider: GMPProvider
1476269755628	addons.manager	DEBUG	Registering shutdown blocker for GMPProvider
1476269755629	addons.manager	DEBUG	Provider finished startup: GMPProvider
1476269755629	addons.manager	DEBUG	Starting provider: PluginProvider
1476269755629	addons.manager	DEBUG	Registering shutdown blocker for PluginProvider
1476269755631	addons.manager	DEBUG	Provider finished startup: PluginProvider
1476269755631	addons.manager	DEBUG	Completed startup sequence
[GFX1]: Potential driver version mismatch ignored due to missing DLLs 0.0.0.0 and 0.0.0.0
1476269757066	addons.manager	DEBUG	Starting provider: <unnamed-provider>
1476269757066	addons.manager	DEBUG	Registering shutdown blocker for <unnamed-provider>
1476269757066	addons.manager	DEBUG	Provider finished startup: <unnamed-provider>
Crash Annotation GraphicsCriticalError: |[0][GFX1]: [D3D9] Failed to create the device, code: 0x8876086c (t=9.64539) [GFX1]: [D3D9] Failed to create the device, code: 0x8876086c
Crash Annotation GraphicsCriticalError: |[0][GFX1]: [D3D9] Failed to create the device, code: 0x8876086c (t=9.64539) |[1][GFX1]: [D3D9] Could not Initialize the DeviceManagerD3D9 (t=9.64539) [GFX1]: [D3D9] Could not Initialize the DeviceManagerD3D9
1476269757365	DeferredSave.extensions.json	DEBUG	Write succeeded
1476269757365	addons.xpi-utils	DEBUG	XPI Database saved, setting schema version preference to 17
1476269757366	DeferredSave.extensions.json	DEBUG	Starting timer
1476269757467	DeferredSave.extensions.json	DEBUG	Starting write
1476269757478	addons.repository	DEBUG	No addons.json found.
1476269757479	DeferredSave.addons.json	DEBUG	Save changes
1476269757481	DeferredSave.addons.json	DEBUG	Starting timer
1476269757499	addons.manager	DEBUG	Starting provider: PreviousExperimentProvider
1476269757499	addons.manager	DEBUG	Registering shutdown blocker for PreviousExperimentProvider
1476269757500	addons.manager	DEBUG	Provider finished startup: PreviousExperimentProvider
1476269757513	DeferredSave.extensions.json	DEBUG	Write succeeded
1476269757535	DeferredSave.addons.json	DEBUG	Starting write
1476269757550	DeferredSave.addons.json	DEBUG	Write succeeded
Crash Annotation GraphicsCriticalError: |[0][GFX1]: [D3D9] Failed to create the device, code: 0x8876086c (t=9.64539) |[1][GFX1]: [D3D9] Could not Initialize the DeviceManagerD3D9 (t=9.64539) |[2][GFX1]: [D3D9] Failed to create the device, code: 0x8876086c (t=12.0393) [GFX1]: [D3D9] Failed to create the device, code: 0x8876086c
Crash Annotation GraphicsCriticalError: |[0][GFX1]: [D3D9] Failed to create the device, code: 0x8876086c (t=9.64539) |[1][GFX1]: [D3D9] Could not Initialize the DeviceManagerD3D9 (t=9.64539) |[2][GFX1]: [D3D9] Failed to create the device, code: 0x8876086c (t=12.0393) |[3][GFX1]: [D3D9] Could not Initialize the DeviceManagerD3D9 (t=12.0393) [GFX1]: [D3D9] Could not Initialize the DeviceManagerD3D9

	at org.openqa.selenium.firefox.internal.NewProfileExtensionConnection.start(NewProfileExtensionConnection.java:113)
	at org.openqa.selenium.firefox.FirefoxDriver.startClient(FirefoxDriver.java:271)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:119)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:216)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:211)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:128)
	at com.cognizant.drivers.WebDriverFactory.create(WebDriverFactory.java:145)
	at com.cognizant.drivers.WebDriverFactory.create(WebDriverFactory.java:134)
	at com.cognizant.drivers.WebDriverFactory.create(WebDriverFactory.java:126)
	at com.cognizant.drivers.SeleniumDriver.launchDriver(SeleniumDriver.java:60)
	at com.cognizant.core.Task.launchBrowser(Task.java:137)
	at com.cognizant.core.Task.runIteration(Task.java:101)
	at com.cognizant.core.Task.run(Task.java:80)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
|--| Failed to connect to binary FirefoxBinary(C:\Program Files\Mozilla Firefox\firefox.exe) on port 7055; process output follows: 
tzfirefox version 4.1.7
1476269755615	addons.xpi	DEBUG	Registering manifest for C:\Program Files\Mozilla Firefox\browser\features\e10srollout@mozilla.org.xpi
1476269755616	addons.xpi	DEBUG	Calling bootstrap method startup on e10srollout@mozilla.org version 1.2
1476269755616	addons.xpi	DEBUG	Registering manifest for C:\Program Files\Mozilla Firefox\browser\features\firefox@getpocket.com.xpi
1476269755617	addons.xpi	DEBUG	Calling bootstrap method startup on firefox@getpocket.com version 1.0.4
1476269755618	addons.xpi	DEBUG	Registering manifest for C:\Program Files\Mozilla Firefox\browser\features\webcompat@mozilla.org.xpi
1476269755618	addons.xpi	DEBUG	Calling bootstrap method startup on webcompat@mozilla.org version 1.0
1476269755620	addons.manager	DEBUG	Registering shutdown blocker for XPIProvider
1476269755620	addons.manager	DEBUG	Provider finished startup: XPIProvider
1476269755620	addons.manager	DEBUG	Starting provider: LightweightThemeManager
1476269755620	addons.manager	DEBUG	Registering shutdown blocker for LightweightThemeManager
1476269755620	addons.manager	DEBUG	Provider finished startup: LightweightThemeManager
1476269755620	addons.manager	DEBUG	Starting provider: GMPProvider
1476269755628	addons.manager	DEBUG	Registering shutdown blocker for GMPProvider
1476269755629	addons.manager	DEBUG	Provider finished startup: GMPProvider
1476269755629	addons.manager	DEBUG	Starting provider: PluginProvider
1476269755629	addons.manager	DEBUG	Registering shutdown blocker for PluginProvider
1476269755631	addons.manager	DEBUG	Provider finished startup: PluginProvider
1476269755631	addons.manager	DEBUG	Completed startup sequence
[GFX1]: Potential driver version mismatch ignored due to missing DLLs 0.0.0.0 and 0.0.0.0
1476269757066	addons.manager	DEBUG	Starting provider: <unnamed-provider>
1476269757066	addons.manager	DEBUG	Registering shutdown blocker for <unnamed-provider>
1476269757066	addons.manager	DEBUG	Provider finished startup: <unnamed-provider>
Crash Annotation GraphicsCriticalError: |[0][GFX1]: [D3D9] Failed to create the device, code: 0x8876086c (t=9.64539) [GFX1]: [D3D9] Failed to create the device, code: 0x8876086c
Crash Annotation GraphicsCriticalError: |[0][GFX1]: [D3D9] Failed to create the device, code: 0x8876086c (t=9.64539) |[1][GFX1]: [D3D9] Could not Initialize the DeviceManagerD3D9 (t=9.64539) [GFX1]: [D3D9] Could not Initialize the DeviceManagerD3D9
1476269757365	DeferredSave.extensions.json	DEBUG	Write succeeded
1476269757365	addons.xpi-utils	DEBUG	XPI Database saved, setting schema version preference to 17
1476269757366	DeferredSave.extensions.json	DEBUG	Starting timer
1476269757467	DeferredSave.extensions.json	DEBUG	Starting write
1476269757478	addons.repository	DEBUG	No addons.json found.
1476269757479	DeferredSave.addons.json	DEBUG	Save changes
1476269757481	DeferredSave.addons.json	DEBUG	Starting timer
1476269757499	addons.manager	DEBUG	Starting provider: PreviousExperimentProvider
1476269757499	addons.manager	DEBUG	Registering shutdown blocker for PreviousExperimentProvider
1476269757500	addons.manager	DEBUG	Provider finished startup: PreviousExperimentProvider
1476269757513	DeferredSave.extensions.json	DEBUG	Write succeeded
1476269757535	DeferredSave.addons.json	DEBUG	Starting write
1476269757550	DeferredSave.addons.json	DEBUG	Write succeeded
Crash Annotation GraphicsCriticalError: |[0][GFX1]: [D3D9] Failed to create the device, code: 0x8876086c (t=9.64539) |[1][GFX1]: [D3D9] Could not Initialize the DeviceManagerD3D9 (t=9.64539) |[2][GFX1]: [D3D9] Failed to create the device, code: 0x8876086c (t=12.0393) [GFX1]: [D3D9] Failed to create the device, code: 0x8876086c
Crash Annotation GraphicsCriticalError: |[0][GFX1]: [D3D9] Failed to create the device, code: 0x8876086c (t=9.64539) |[1][GFX1]: [D3D9] Could not Initialize the DeviceManagerD3D9 (t=9.64539) |[2][GFX1]: [D3D9] Failed to create the device, code: 0x8876086c (t=12.0393) |[3][GFX1]: [D3D9] Could not Initialize the DeviceManagerD3D9 (t=12.0393) [GFX1]: [D3D9] Could not Initialize the DeviceManagerD3D9

Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: host: 'PC327135', ip: '10.219.68.66', os.name: 'Windows 7', os.arch: 'x86', os.version: '6.1', java.version: '1.8.0_102'
Driver info: driver.version: SeleniumDriver

```

**Comment by andreastt** [comment]
For some time now we have had `moz:firefoxOptions`, which is documented in the README. Please try to use that to package your extensions. I’m going to close this for now, but please let me know if that’s wrong. Happy to reopen if new information has surfaced.
