### ISSUE TITLE
"this.curBrowser.messageManager is null" since Firefox 82

### ISSUE THREAD

**Issue by phoenix384** [mozilla/geckodriver#1812]
## System

* Version: 0.28
* Platform: Windows 10 / Ubuntu 20.04
* Firefox: 82 + 83
* Selenium: 3.141.59

## Testcase

When trying to find an element in a window that has closed, Firefox <82 threw a NoSuchWindowException.
Since v82 it is a WebDriverException "TypeError: this.curBrowser.messageManager is null".
The NoSuchWindowException was more understandable and could easily be handled if needed. The current error message looks like there might be something else wrong.

## Stacktrace

`org.openqa.selenium.WebDriverException: TypeError: this.curBrowser.messageManager is null
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:187)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:122)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:49)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:323)
	at org.openqa.selenium.remote.RemoteWebDriver.findElementByCssSelector(RemoteWebDriver.java:420)
	at org.openqa.selenium.By$ByCssSelector.findElement(By.java:431)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:315)`

**Comment by whimboo** [comment]
Can you please check with a recent Firefox 84 beta? That problem should no longer exist given that we rewrote most of the underlying code.

**Comment by phoenix384** [comment]
Checked with 84.0b4 and it works again.

**Comment by whimboo** [comment]
Thanks for the confirmation. I'm going to close this issue then.
