### ISSUE TITLE
Found argument '--marionette' which wasn't expected

### ISSUE THREAD

**Issue by HTransistor** [mozilla/geckodriver#1815]
## System

* Version: 
* Platform: 5.9.8-gentoo
* Firefox: www-client/firefox-83.0:0/83::gentoo with geckodriver flag
* Selenium: 

## Stacktrace

```
Traceback (most recent call last):
  File "/share/Documents/python_scripts/mobile-alerts-plot-private/selen.py", line 80, in <module>
    driver = Firefox(capabilities=caps, options=options)
  File "/usr/lib/python3.9/site-packages/selenium/webdriver/firefox/webdriver.py", line 190, in __init__
    executor = ExtensionConnection("127.0.0.1", self.profile,
  File "/usr/lib/python3.9/site-packages/selenium/webdriver/firefox/extension_connection.py", line 52, in __init__
    self.binary.launch_browser(self.profile, timeout=timeout)
  File "/usr/lib/python3.9/site-packages/selenium/webdriver/firefox/firefox_binary.py", line 73, in launch_browser
    self._wait_until_connectable(timeout=timeout)
  File "/usr/lib/python3.9/site-packages/selenium/webdriver/firefox/firefox_binary.py", line 103, in _wait_until_connectable
    raise WebDriverException(
selenium.common.exceptions.WebDriverException: Message: The browser appears to have exited before we could connect. If you specified a log_file in the FirefoxBinary constructor, check it for details.
```

## Trace-level log

```
1606901613879   geckodriver     INFO    Listening on 127.0.0.1:47711                                                
1606901613883   mozrunner::runner       INFO    Running command: "/usr/bin/geckodriver" "--marionette" "-           foreground" "-no-remote" "-profile" "/tmp/rust_mozprofiledIG0s8"                                                    
/usr/bin/geckodriver: error: Found argument '--marionette' which wasn't expected, or isn't valid in this context    
        Did you mean --marionette-host?                                                                             
                                                                                                                    
USAGE:                                                                                                              
    geckodriver --marionette-host <HOST>     
                                                               
                                                                                                                    
For more information try --help
```        

How do I unset the --marionette flag? Do I need to use the new --marionette-host flag?

**Comment by whimboo** [comment]
You are specifying the geckodriver binary path as Firefox binary. That's clearly not working.

**Comment by HTransistor** [comment]
Sorry!
I used the following to fix it:
```
options = webdriver.FirefoxOptions()                                                  
options.binary_location = "/usr/bin/firefox"
driver = Firefox(options=options) 
```
