### ISSUE TITLE
Errors with 57, 59 firefox when call implicitlyWait

### ISSUE THREAD

**Issue by rif88** [mozilla/geckodriver#1828]
## System

* Version: 
* Platform: Linux 3.10.0-862.3.2.el7.x86_64
* Firefox: 57, 59
* Selenium: 3.12.0

## Testcase

We call setTimeouts method in java application with variables
implicitlyWait = 30;
implicitlyWaitUnit = TimeUnit.MILLISECONDS
and get error for 57 and 59 version of firefox when timeouts.implicitlyWait() is called. But for 52 version of firefox we have no this error. 
Could you please explain why we have errors in our cases when we try use 57 or 59 version of firefox browser? And when we use 52 version of firefox browser we have no such error?

Code of this method:
`protected static WebDriver setTimeouts(WebDriver driver, Settings settings) { Timeouts timeouts = driver.manage().timeouts(); timeouts.implicitlyWait(settings.getImplicitlyWait(), settings.getImplicitlyWaitUnit()); try { timeouts.pageLoadTimeout(settings.getPageLoadTimeout(), settings.getPageLoadTimeoutUnit()); timeouts.setScriptTimeout(settings.getScriptTimeout(), settings.getScriptTimeoutUnit()); } catch (WebDriverException e) { String error = e.toString(); if (error.contains("setScriptTimeout")) { log.warn("setScriptTimeout has been failed. Default Script timeout remains. \n" + e); } else if (error.contains("pageLoadTimeout")) { log.warn("pageLoadTimeout has been failed. Default page load timeout remains. \n" + e); } } return driver; }`

## Stacktrace

`Caused by: org.openqa.selenium.WebDriverException: route not found (WARNING: The server did not provide any stacktrace information) Command duration or timeout: 0 milliseconds Build info: version: '3.12.0', revision: '7c6e0b3', time: '2018-05-08T14:04:26.12Z' System info: host: '...', ip: '...', os.name: 'Linux', os.arch: 'amd64', os.version: '3.10.0-862.3.2.el7.x86_64', java.version: '1.8.0_231' Driver info: org.openqa.selenium.remote.RemoteWebDriver Capabilities {capabilities: {acceptInsecureCerts: true, browserName: firefox, browserVersion: 59.0.1, moz:accessibilityChecks: false, moz:headless: false, moz:processID: 60, moz:profile: /tmp/rust_mozprofile.0WkUQ1..., moz:useNonSpecCompliantPointerOrigin: false, moz:webdriverClick: true, pageLoadStrategy: none, platformName: linux, platformVersion: 3.10.0-862.3.2.el7.x86_64, rotatable: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}}, javascriptEnabled: true, platform: ANY, platformName: ANY, sessionId: c7ef2437cf4e151630d75bd3419...} Session ID: null at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) at java.lang.reflect.Constructor.newInstance(Constructor.java:423) at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:214) at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:166) at org.openqa.selenium.remote.http.JsonHttpResponseCodec.reconstructValue(JsonHttpResponseCodec.java:40) at org.openqa.selenium.remote.http.AbstractHttpResponseCodec.decode(AbstractHttpResponseCodec.java:80) at com.netcracker.automation.wd.shell.browser.WDHttpCommandExecutor.execute(WDHttpCommandExecutor.java:82) at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:543) at org.openqa.selenium.remote.RemoteWebDriver$RemoteWebDriverOptions$RemoteTimeouts.implicitlyWait(RemoteWebDriver.java:771)`

## Trace-level log

We have no logs because firefox won't be up

**Comment by whimboo** [comment]
Firefox 59 isn't supported anymore since geckodriver 0.26.0 has been released a long time ago. If you can provide correct trace level logs for a recent Firefox 84 and geckodriver 0.28.0, I'm happy to help to investigate.

**Comment by rif88** [comment]
@whimboo hello. Could you please tell me: firefox 57 isn't supported too? Just for now do you support only 84 version?

**Comment by whimboo** [comment]
Firefox 57 is out of date for more than 3 years now! None of the users should use that version of Firefox anymore. 

Basically we only support the Firefox releases that are supported by the most recent geckodriver release. These versions can be found here:

https://firefox-source-docs.mozilla.org/testing/geckodriver/Support.html

**Comment by rif88** [comment]
By this link I see that for selenium ≥ 3.11 you should support min = 57 version of firefox.
![image](https://user-images.githubusercontent.com/44464331/104449598-43840100-55b8-11eb-8f99-20598e259405.png)

**Comment by whimboo** [comment]
No, we don't support anything below geckodriver 0.28.0. So if you want to see progress on this issue please provide the requested details with geckodriver 0.28.0 and Firefox 84, or even a Firefox Nightly. That is the place where development happens.

**Comment by rif88** [comment]
**System**
Version: geckodriver 0.28.0
Platform: Windows 10 Pro (x64)
Firefox: 84
Selenium: 3.12.0

**Stacktrace**
`Caused by: org.openqa.selenium.WebDriverException: Session [null] not available and is not among the last 1000 terminated sessions.
Active sessions are[ext. key 8eb408c2-102c-485f-ad14-8518478e8524]
Command duration or timeout: 0 milliseconds
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:214)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:166)
	at org.openqa.selenium.remote.http.JsonHttpResponseCodec.reconstructValue(JsonHttpResponseCodec.java:40)
	at org.openqa.selenium.remote.http.AbstractHttpResponseCodec.decode(AbstractHttpResponseCodec.java:80)
	at com.netcracker.automation.wd.shell.browser.WDHttpCommandExecutor.execute(WDHttpCommandExecutor.java:82)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:543)
	at org.openqa.selenium.remote.RemoteWebDriver$RemoteWebDriverOptions$RemoteTimeouts.implicitlyWait(RemoteWebDriver.java:771)
	...
	... 31 more
Caused by: org.openqa.selenium.WebDriverException: Session [null] not available and is not among the last 1000 terminated sessions.
Active sessions are[ext. key 8eb408c2-102c-485f-ad14-8518478e8524]
Build info: version: '3.12.0', revision: '7c6e0b3', time: '2018-05-08T14:04:26.12Z'
System info: host: '...', ip: '...', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_261'
Driver info: driver.version: unknown
	at org.openqa.grid.internal.ActiveTestSessions.getExistingSession(ActiveTestSessions.java:120)
	at org.openqa.grid.internal.DefaultGridRegistry.getExistingSession(DefaultGridRegistry.java:380)
	at org.openqa.grid.web.servlet.handler.RequestHandler.getSession(RequestHandler.java:241)
	at org.openqa.grid.web.servlet.handler.RequestHandler.process(RequestHandler.java:123)
	at org.openqa.grid.web.servlet.DriverServlet.process(DriverServlet.java:86)
	at org.openqa.grid.web.servlet.DriverServlet.doPost(DriverServlet.java:70)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.seleniumhq.jetty9.servlet.ServletHolder.handle(ServletHolder.java:860)
	at org.seleniumhq.jetty9.servlet.ServletHandler.doHandle(ServletHandler.java:535)
	at org.seleniumhq.jetty9.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.seleniumhq.jetty9.security.SecurityHandler.handle(SecurityHandler.java:548)
	at org.seleniumhq.jetty9.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:190)
	at org.seleniumhq.jetty9.server.session.SessionHandler.doHandle(SessionHandler.java:1595)
	at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:188)
	at org.seleniumhq.jetty9.server.handler.ContextHandler.doHandle(ContextHandler.java:1253)
	at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextScope(ScopedHandler.java:168)
	at org.seleniumhq.jetty9.servlet.ServletHandler.doScope(ServletHandler.java:473)
	at org.seleniumhq.jetty9.server.session.SessionHandler.doScope(SessionHandler.java:1564)
	at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextScope(ScopedHandler.java:166)
	at org.seleniumhq.jetty9.server.handler.ContextHandler.doScope(ContextHandler.java:1155)
	at org.seleniumhq.jetty9.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.seleniumhq.jetty9.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.seleniumhq.jetty9.server.Server.handle(Server.java:530)
	at org.seleniumhq.jetty9.server.HttpChannel.handle(HttpChannel.java:347)
	at org.seleniumhq.jetty9.server.HttpConnection.onFillable(HttpConnection.java:256)
	at org.seleniumhq.jetty9.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279)
	at org.seleniumhq.jetty9.io.FillInterest.fillable(FillInterest.java:102)
	at org.seleniumhq.jetty9.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)
	at org.seleniumhq.jetty9.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:247)
	at org.seleniumhq.jetty9.util.thread.strategy.EatWhatYouKill.produce(EatWhatYouKill.java:140)
	at org.seleniumhq.jetty9.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131)
	at org.seleniumhq.jetty9.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:382)
	at org.seleniumhq.jetty9.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:708)
	at org.seleniumhq.jetty9.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:626)
	... 1 more`

@whimboo could you please tell me where I can find trace level logs for browser?

**Comment by whimboo** [comment]
Oh, I thought I already provided that. Sorry, then. Here the details: https://firefox-source-docs.mozilla.org/testing/geckodriver/TraceLogs.html

When you have the logs, please don't paste it all in the comment but attach them as file. Thanks.
