### ISSUE TITLE
Setting the SOCKS version makes the session crash

### ISSUE THREAD

**Issue by cambiph** [mozilla/geckodriver#1833]
## System

* Version: 0.29.0
* Platform: Windows 10
* Firefox: 84.0.2 64-bit
* Selenium: 3.141.59

## Testcase

Setting the SOCKS proxy using the following code, crashes the session:

        Proxy proxy = new Proxy();
        proxy.setSocksProxy("localhost:6443");
        proxy.setSocksVersion(5);

        FirefoxOptions options = new FirefoxOptions();
        options.setCapability(CapabilityType.PROXY, proxy);

If you leave out the SocksVersion, the following error is displayed in the trace log:

```
{
    "error": "session not created",
    "message": "InvalidArgumentError: Expected \"socksVersion\" to be a positive integer, got  ... t@chrome:\/\/marionette\/content\/server.js:241:9\n_onJSONObjectReady\/<@chrome:\/\/marionette\/content\/transport.js:504:20\n"
}
```

## Stacktrace
```
Exception in thread "main" org.openqa.selenium.remote.UnreachableBrowserException: Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure.
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'CI00115928', ip: '192.168.1.239', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '15.0.1'
Driver info: driver.version: FirefoxDriver
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:573)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:213)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:131)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:147)
	at eu.ectl.dplt.test.FirefoxTest.main(FirefoxTest.java:40)
Caused by: java.lang.ClassCastException: class java.lang.Long cannot be cast to class java.lang.Integer (java.lang.Long and java.lang.Integer are in module java.base of loader 'bootstrap')
	at org.openqa.selenium.Proxy.<init>(Proxy.java:94)
	at org.openqa.selenium.remote.ProtocolHandshake$Result.lambda$static$0(ProtocolHandshake.java:151)
	at org.openqa.selenium.remote.ProtocolHandshake$Result.<init>(ProtocolHandshake.java:166)
	at org.openqa.selenium.remote.W3CHandshakeResponse.lambda$successHandler$1(W3CHandshakeResponse.java:107)
	at org.openqa.selenium.remote.HandshakeResponse.lambda$getResponseFunction$0(HandshakeResponse.java:30)
	at org.openqa.selenium.remote.ProtocolHandshake.lambda$createSession$0(ProtocolHandshake.java:126)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:958)
	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:127)
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:502)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:488)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:543)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:128)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:74)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:136)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
	... 4 more
```

## Trace-level log

[trace.txt](https://github.com/mozilla/geckodriver/files/5854962/trace.txt)

This seems to be related to:
https://github.com/mozilla/geckodriver/issues/669
https://github.com/mozilla/geckodriver/issues/764

**Comment by cambiph** [comment]
Still relevant in 0.30.0
