### ISSUE TITLE
Wait for element to become stale throws "NoSuchElementException"

### ISSUE THREAD

**Issue by jtnord** [mozilla/geckodriver#1839]
## System

* Version: 0.29.0
* Platform: Linux (container `selenium/standalone-firefox-debug:3.141.59`  (sha256:07eb3987eb30d371d6c010a2ff98045bc70988614bbdeab171aa23b18b2c145f) https://hub.docker.com/layers/selenium/standalone-firefox-debug/3.141.59/images/sha256-07eb3987eb30d371d6c010a2ff98045bc70988614bbdeab171aa23b18b2c145f?context=explore
* Firefox: 85.0
* Selenium: 3.141.59

## Testcase

```
        WebElement e = find(by.button("Save"));
        e.click();
        waitFor(e).until(CapybaraPortingLayerImpl::isStale);
```

which is in essence:
```
        WebElement e = find(by.button("Save"));
        e.click();
        while (true) {
                try {
                    // Calling any method forces a staleness check
                    e.isEnabled();
                   // not stale, wait some more 
                } catch (StaleElementReferenceException expected) {
                    // stale! now do some more
                    break;
                }
       }

```

## Stacktrace

```
[2021-02-02T12:14:52.517Z] [ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 86.846 s <<< FAILURE! - in io.jenkins.plugins.forensics.ForensicsPluginUiTest
[2021-02-02T12:14:52.517Z] [ERROR] io.jenkins.plugins.forensics.ForensicsPluginUiTest.shouldAggregateToolsIntoSingleResult  Time elapsed: 86.786 s  <<< ERROR!
[2021-02-02T12:14:52.517Z] org.openqa.selenium.NoSuchElementException: 
[2021-02-02T12:14:52.517Z] Web element reference not seen before: {"element-6066-11e4-a52e-4f735466cecf":"c26a4fc6-1eea-4b05-8dd1-e7559ba44373"}
[2021-02-02T12:14:52.517Z] For documentation on this error, please visit: https://www.seleniumhq.org/exceptions/no_such_element.html
[2021-02-02T12:14:52.517Z] Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
[2021-02-02T12:14:52.517Z] System info: host: 'ip-172-31-26-73', ip: '172.31.26.73', os.name: 'Linux', os.arch: 'amd64', os.version: '5.4.0-1029-aws', java.version: '1.8.0_242'
[2021-02-02T12:14:52.517Z] Driver info: org.openqa.selenium.remote.RemoteWebDriver
[2021-02-02T12:14:52.518Z] Capabilities {acceptInsecureCerts: true, browserName: firefox, browserVersion: 85.0, javascriptEnabled: true, moz:accessibilityChecks: false, moz:buildID: 20210118153634, moz:geckodriverVersion: 0.29.0, moz:headless: false, moz:processID: 72, moz:profile: /tmp/rust_mozprofileJDLt1o, moz:shutdownTimeout: 60000, moz:useNonSpecCompliantPointerOrigin: false, moz:webdriverClick: true, pageLoadStrategy: normal, platform: LINUX, platformName: LINUX, platformVersion: 5.4.0-1029-aws, rotatable: false, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webdriver.remote.sessionid: 4c05edf9-0ee7-4d17-bcec-ad8...}
[2021-02-02T12:14:52.518Z] Session ID: 4c05edf9-0ee7-4d17-bcec-ad8266806936
[2021-02-02T12:14:52.518Z] 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[2021-02-02T12:14:52.518Z] 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[2021-02-02T12:14:52.518Z] 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[2021-02-02T12:14:52.518Z] 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[2021-02-02T12:14:52.518Z] 	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:187)
[2021-02-02T12:14:52.518Z] 	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:122)
[2021-02-02T12:14:52.518Z] 	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:49)
[2021-02-02T12:14:52.518Z] 	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
[2021-02-02T12:14:52.518Z] 	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
[2021-02-02T12:14:52.518Z] 	at org.openqa.selenium.remote.RemoteWebElement.execute(RemoteWebElement.java:285)
[2021-02-02T12:14:52.518Z] 	at org.openqa.selenium.remote.RemoteWebElement.isEnabled(RemoteWebElement.java:156)
[2021-02-02T12:14:52.518Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2021-02-02T12:14:52.518Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2021-02-02T12:14:52.518Z] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2021-02-02T12:14:52.518Z] 	at java.lang.reflect.Method.invoke(Method.java:498)
[2021-02-02T12:14:52.518Z] 	at org.openqa.selenium.support.events.EventFiringWebDriver$EventFiringWebElement.lambda$new$0(EventFiringWebDriver.java:404)
[2021-02-02T12:14:52.518Z] 	at com.sun.proxy.$Proxy37.isEnabled(Unknown Source)
[2021-02-02T12:14:52.518Z] 	at org.openqa.selenium.support.events.EventFiringWebDriver$EventFiringWebElement.isEnabled(EventFiringWebDriver.java:457)
[2021-02-02T12:14:52.518Z] 	at org.jenkinsci.test.acceptance.po.CapybaraPortingLayerImpl.isStale(CapybaraPortingLayerImpl.java:343)
[2021-02-02T12:14:52.518Z] 	at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:249)
[2021-02-02T12:14:52.518Z] 	at org.jenkinsci.test.acceptance.po.ConfigurablePageObject.save(ConfigurablePageObject.java:133)
[2021-02-02T12:14:52.518Z] 	at io.jenkins.plugins.forensics.ForensicsPluginUiTest.createJob(ForensicsPluginUiTest.java:85)
[2021-02-02T12:14:52.518Z] 	at io.jenkins.plugins.forensics.ForensicsPluginUiTest.shouldAggregateToolsIntoSingleResult(ForensicsPluginUiTest.java:35)
[2021-02-02T12:14:52.518Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2021-02-02T12:14:52.518Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2021-02-02T12:14:52.518Z] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2021-02-02T12:14:52.518Z] 	at java.lang.reflect.Method.invoke(Method.java:498)
[2021-02-02T12:14:52.518Z] 	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
[2021-02-02T12:14:52.518Z] 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
[2021-02-02T12:14:52.518Z] 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
[2021-02-02T12:14:52.518Z] 	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
[2021-02-02T12:14:52.518Z] 	at org.jenkinsci.test.acceptance.junit.WithPlugins$RuleImpl$1.evaluate(WithPlugins.java:164)
[2021-02-02T12:14:52.518Z] 	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
[2021-02-02T12:14:52.518Z] 	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
[2021-02-02T12:14:52.518Z] 	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
[2021-02-02T12:14:52.518Z] 	at org.jenkinsci.test.acceptance.junit.JenkinsAcceptanceTestRule$1$2$1.evaluate(JenkinsAcceptanceTestRule.java:168)
[2021-02-02T12:14:52.518Z] 	at org.jenkinsci.test.acceptance.junit.FilterRule$1.evaluate(FilterRule.java:63)
[2021-02-02T12:14:52.518Z] 	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
[2021-02-02T12:14:52.518Z] 	at org.jenkinsci.test.acceptance.junit.JenkinsAcceptanceTestRule$1.evaluate(JenkinsAcceptanceTestRule.java:58)
[2021-02-02T12:14:52.518Z] 	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
[2021-02-02T12:14:52.518Z] 	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
[2021-02-02T12:14:52.518Z] 	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
[2021-02-02T12:14:52.518Z] 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
[2021-02-02T12:14:52.518Z] 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
[2021-02-02T12:14:52.518Z] 	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
[2021-02-02T12:14:52.518Z] 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
[2021-02-02T12:14:52.518Z] 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
[2021-02-02T12:14:52.518Z] 	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
[2021-02-02T12:14:52.518Z] 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
[2021-02-02T12:14:52.518Z] 	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
[2021-02-02T12:14:52.518Z] 	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
[2021-02-02T12:14:52.518Z] 	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
[2021-02-02T12:14:52.518Z] 	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
[2021-02-02T12:14:52.518Z] 	at org.junit.vintage.engine.execution.RunnerExecutor.execute(RunnerExecutor.java:43)
[2021-02-02T12:14:52.518Z] 	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
[2021-02-02T12:14:52.518Z] 	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
[2021-02-02T12:14:52.518Z] 	at java.util.Iterator.forEachRemaining(Iterator.java:116)
[2021-02-02T12:14:52.518Z] 	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
[2021-02-02T12:14:52.518Z] 	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
[2021-02-02T12:14:52.518Z] 	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
[2021-02-02T12:14:52.518Z] 	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
[2021-02-02T12:14:52.518Z] 	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
[2021-02-02T12:14:52.518Z] 	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
[2021-02-02T12:14:52.518Z] 	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:485)
[2021-02-02T12:14:52.518Z] 	at org.junit.vintage.engine.VintageTestEngine.executeAllChildren(VintageTestEngine.java:82)
[2021-02-02T12:14:52.518Z] 	at org.junit.vintage.engine.VintageTestEngine.execute(VintageTestEngine.java:73)
[2021-02-02T12:14:52.518Z] 	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:108)
[2021-02-02T12:14:52.518Z] 	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:88)
[2021-02-02T12:14:52.518Z] 	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:54)
[2021-02-02T12:14:52.518Z] 	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:67)
[2021-02-02T12:14:52.518Z] 	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:52)
[2021-02-02T12:14:52.518Z] 	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:96)
[2021-02-02T12:14:52.518Z] 	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:75)
[2021-02-02T12:14:52.518Z] 	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.execute(JUnitPlatformProvider.java:188)
[2021-02-02T12:14:52.518Z] 	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invokeAllTests(JUnitPlatformProvider.java:154)
[2021-02-02T12:14:52.518Z] 	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invoke(JUnitPlatformProvider.java:124)
[2021-02-02T12:14:52.518Z] 	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:428)
[2021-02-02T12:14:52.518Z] 	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
[2021-02-02T12:14:52.518Z] 	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:562)
[2021-02-02T12:14:52.518Z] 	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:548)

```

## Trace-level log

Full log below but the interesting bit I believe is the following where for some reason even though the URL has not changed the context is being reset. `Remoteness change detected. Set new top-level browsing context to 37`

```
[2021-02-02T12:14:52.510Z] 1612268076582	Marionette	DEBUG	0 -> [0,70,"WebDriver:ExecuteScript",{"args":[925,388,"yui-gen11-button"],"script":"// Visually navigate to the element in order t ... p (footer does not overlap)\n  return (footer[0].getBoundingClientRect().top >= sticker.getBoundingClientRect().bottom)\n}"}]
[2021-02-02T12:14:52.510Z] 1612268076585	Marionette	DEBUG	0 <- [1,70,null,{"value":true}]
[2021-02-02T12:14:52.510Z] 1612268076585	webdriver::server	DEBUG	<- 200 OK {"value":true}
[2021-02-02T12:14:52.510Z] 1612268076591	webdriver::server	DEBUG	-> POST /session/4c05edf9-0ee7-4d17-bcec-ad8266806936/element/c26a4fc6-1eea-4b05-8dd1-e7559ba44373/click {
[2021-02-02T12:14:52.510Z]   "id": "c26a4fc6-1eea-4b05-8dd1-e7559ba44373"
[2021-02-02T12:14:52.510Z] }
[2021-02-02T12:14:52.510Z] 1612268076592	Marionette	DEBUG	0 -> [0,71,"WebDriver:ElementClick",{"id":"c26a4fc6-1eea-4b05-8dd1-e7559ba44373"}]
[2021-02-02T12:14:52.510Z] 1612268076621	Marionette	TRACE	[35] MarionetteEvents actor created for window id 8589934593
[2021-02-02T12:14:52.510Z] 1612268076621	Marionette	TRACE	[8589934593] MarionetteEvents actor created for window id 8589934595
[2021-02-02T12:14:52.510Z] 1612268076622	Marionette	TRACE	Received event beforeunload for http://127.0.0.1:60596/job/tidy_broccoli/configure
[2021-02-02T12:14:52.510Z] 1612268076625	Marionette	TRACE	Received DOM event click for [object HTMLButtonElement]
[2021-02-02T12:14:52.510Z] 1612268077039	Marionette	TRACE	Remoteness change detected. Set new top-level browsing context to 37
[2021-02-02T12:14:52.510Z] 1612268077119	Marionette	TRACE	[37] Frame script loaded
[2021-02-02T12:14:52.510Z] 1612268077120	Marionette	ERROR	[37] No reply from Marionette:Register
[2021-02-02T12:14:52.510Z] 1612268077155	Marionette	TRACE	[37] MarionetteEvents actor created for window id 26
[2021-02-02T12:14:52.510Z] 1612268077158	Marionette	TRACE	Received event beforeunload for about:blank
[2021-02-02T12:14:52.510Z] 1612268077177	Marionette	TRACE	Received event pagehide for about:blank
[2021-02-02T12:14:52.510Z] 1612268077575	Marionette	TRACE	[37] MarionetteEvents actor created for window id 10737418241
[2021-02-02T12:14:52.510Z] 1612268077576	Marionette	TRACE	Received event DOMContentLoaded for http://127.0.0.1:60596/job/tidy_broccoli/
[2021-02-02T12:14:52.510Z] 1612268077636	Marionette	TRACE	Received event pageshow for http://127.0.0.1:60596/job/tidy_broccoli/
[2021-02-02T12:14:52.510Z] 1612268077636	Marionette	DEBUG	0 <- [1,71,null,{"value":null}]
[2021-02-02T12:14:52.510Z] 1612268077637	webdriver::server	DEBUG	<- 200 OK {"value":null}
[2021-02-02T12:14:52.510Z] 1612268077644	webdriver::server	DEBUG	-> GET /session/4c05edf9-0ee7-4d17-bcec-ad8266806936/element/c26a4fc6-1eea-4b05-8dd1-e7559ba44373/enabled 
[2021-02-02T12:14:52.510Z] 1612268077646	Marionette	DEBUG	0 -> [0,72,"WebDriver:IsElementEnabled",{"id":"c26a4fc6-1eea-4b05-8dd1-e7559ba44373"}]
[2021-02-02T12:14:52.510Z] 1612268077657	Marionette	TRACE	[37] MarionetteCommands actor created for window id 10737418241
[2021-02-02T12:14:52.510Z] 1612268077667	Marionette	DEBUG	0 <- [1,72,{"error":"no such element","message":"Web element reference not seen before: {\"element-6066-11e4-a52e-4f735466cecf\":\ ... tte/content/evaluate.js:253:29\nreceiveMessage@chrome://marionette/content/actors/MarionetteCommandsChild.jsm:89:29\n"},null]
[2021-02-02T12:14:52.510Z] 1612268077668	webdriver::server	DEBUG	<- 404 Not Found {"value":{"error":"no such element","message":"Web element reference not seen before: {\"element-6066-11e4-a52e-4f735466cecf\":\"c26a4fc6-1eea-4b05-8dd1-e7559ba44373\"}","stacktrace":"WebDriverError@chrome://marionette/content/error.js:181:5\nNoSuchElementError@chrome://marionette/content/error.js:393:5\nelement.resolveElement@chrome://marionette/content/element.js:821:11\nevaluate.fromJSON@chrome://marionette/content/evaluate.js:233:26\nevaluate.fromJSON@chrome://marionette/content/evaluate.js:253:29\nreceiveMessage@chrome://marionette/content/actors/MarionetteCommandsChild.jsm:89:29\n"}}
[2021-02-02T12:14:52.510Z] 1612268077697	webdriver::server	DEBUG	-> GET /session/4c05edf9-0ee7-4d17-bcec-ad8266806936/url 
```

full trace too big for here -> https://gist.github.com/jtnord/516bd617bceab385ff25eafa924580fe

see also #1826 
https://ci.jenkins.io/job/Plugins/job/git-forensics-plugin/job/PR-222/12/  
https://bugzilla.mozilla.org/show_bug.cgi?id=1684827#c36

The same code appears to work (although it may be a timing issue) with a lower version of the SUT.

The differences in the SUT that could trigger this as far as I can tell is the addition of the `Cross-Origin-Opener-Policy` header set to `same-origin` but the host domain and port are not changing here, and as I understand should not cause this issue in this case.

**Comment by jtnord** [comment]
I managed to reproduce this locally after wondering what was different between my system and the CI.

As I was launching using docker on windows I had told the test framework to use access the SUT via the docker interfaces IP address.

Changing to run geckodriver locally on windows and just using the default SUT address of `127.0.0.1` causes the issue, so it seems there is some strange handling if the URL is `127.0.0.1`.  (in neither case has the SUT been configured with a URL and all resources will be relative not absolute).

as far as "Frame script loaded"  this is funky...  there is a frame - but 
1) it has no source
2) the element we are using is not from that frame but from the top level dom page.

![image](https://user-images.githubusercontent.com/494726/106618572-8148c980-6567-11eb-9e45-06c858751d76.png)

**Comment by whimboo** [comment]
Thank you for the report. I filed it as https://bugzilla.mozilla.org/show_bug.cgi?id=1690308.

**Comment by whimboo** [comment]
This is now fixed in the most recent version of Firefox Nightly. I'm also going to request uplift to get it properly fixed for the upcoming 86 release.
