### ISSUE TITLE
NoSuchElementError when Switching Into Frame

### ISSUE THREAD

**Issue by titusfortner** [mozilla/geckodriver#1843]
## System
* Version: geckodriver 0.29.0 (cf6956a5ec8e 2021-01-14 10:31 +0200)
* Platform: Mac Catalina
* Firefox: 85.0.2 (64-bit)
* Selenium: 4.0.0.beta1

## Expectation
I'm expecting to get a `stale element reference` error returned, instead I get a `no such element`

## Testcase
$ irb
require 'selenium-webdriver'
driver = Selenium::WebDriver.for :firefox
driver.get 'https://the-internet.herokuapp.com/nested_frames'
frame = driver.find_element(tag_name: 'frame')
driver.switch_to.frame(frame)
frame.click

## Stacktrace

```
Traceback (most recent call last):
       16: from (irb):12
       15: from /Users/titusfortner/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/selenium-webdriver-4.0.0.beta1/lib/selenium/webdriver/common/element.rb:77:in `click'
       14: from /Users/titusfortner/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/selenium-webdriver-4.0.0.beta1/lib/selenium/webdriver/remote/bridge.rb:385:in `click_element'
       13: from /Users/titusfortner/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/selenium-webdriver-4.0.0.beta1/lib/selenium/webdriver/remote/bridge.rb:547:in `execute'
       12: from /Users/titusfortner/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/selenium-webdriver-4.0.0.beta1/lib/selenium/webdriver/remote/http/common.rb:64:in `call'
       11: from /Users/titusfortner/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/selenium-webdriver-4.0.0.beta1/lib/selenium/webdriver/remote/http/default.rb:110:in `request'
       10: from /Users/titusfortner/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/selenium-webdriver-4.0.0.beta1/lib/selenium/webdriver/remote/http/common.rb:88:in `create_response'
        9: from /Users/titusfortner/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/selenium-webdriver-4.0.0.beta1/lib/selenium/webdriver/remote/http/common.rb:88:in `new'
        8: from /Users/titusfortner/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/selenium-webdriver-4.0.0.beta1/lib/selenium/webdriver/remote/response.rb:35:in `initialize'
        7: from /Users/titusfortner/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/selenium-webdriver-4.0.0.beta1/lib/selenium/webdriver/remote/response.rb:56:in `assert_ok'
        6: from receiveMessage@chrome://marionette/content/actors/MarionetteCommandsChild.jsm:89:29
        5: from evaluate.fromJSON@chrome://marionette/content/evaluate.js:253:29
        4: from evaluate.fromJSON@chrome://marionette/content/evaluate.js:233:26
        3: from element.resolveElement@chrome://marionette/content/element.js:821:11
        2: from NoSuchElementError@chrome://marionette/content/error.js:393:5
        1: from WebDriverError@chrome://marionette/content/error.js:181:5
Selenium::WebDriver::Error::NoSuchElementError (Web element reference not seen before: {"element-6066-11e4-a52e-4f735466cecf":"fd3bad89-bfb6-284f-88df-9b1a7473e01f"})
```

## Trace-level log
```
irb(main):006:0> driver = Selenium::WebDriver.for :firefox
2021-02-15 18:05:25 INFO Selenium    >>> http://127.0.0.1:4444/session | {"capabilities":{"firstMatch":[{"browserName":"firefox"}]}}
2021-02-15 18:05:27 INFO Selenium <- {"value":{"sessionId":"ecd14b80-d2a5-a046-9def-3507d3a086ff","capabilities":{"acceptInsecureCerts":false,"browserName":"firefox","browserVersion":"85.0.2","moz:accessibilityChecks":false,"moz:buildID":"20210208133944","moz:geckodriverVersion":"0.29.0","moz:headless":false,"moz:processID":44041,"moz:profile":"/var/folders/fx/nlx77ccs72g808pr1994_xtw0000gn/T/rust_mozprofileCQj073","moz:shutdownTimeout":60000,"moz:useNonSpecCompliantPointerOrigin":false,"moz:webdriverClick":true,"pageLoadStrategy":"normal","platformName":"mac","platformVersion":"19.6.0","rotatable":false,"setWindowRect":true,"strictFileInteractability":false,"timeouts":{"implicit":0,"pageLoad":300000,"script":30000},"unhandledPromptBehavior":"dismiss and notify"}}}

irb(main):007:0> driver.get 'https://the-internet.herokuapp.com/nested_frames'
2021-02-15 18:05:34 INFO Selenium -> POST session/ecd14b80-d2a5-a046-9def-3507d3a086ff/url
2021-02-15 18:05:34 INFO Selenium    >>> http://127.0.0.1:4444/session/ecd14b80-d2a5-a046-9def-3507d3a086ff/url | {"url":"https://the-internet.herokuapp.com/nested_frames"}
2021-02-15 18:05:34 INFO Selenium <- {"value":null}
=> nil

irb(main):009:0> frame = driver.find_element(tag_name: 'frame')
2021-02-15 18:06:37 INFO Selenium -> POST session/ecd14b80-d2a5-a046-9def-3507d3a086ff/element
2021-02-15 18:06:37 INFO Selenium    >>> http://127.0.0.1:4444/session/ecd14b80-d2a5-a046-9def-3507d3a086ff/element | {"using":"css selector","value":"frame"}
2021-02-15 18:06:37 INFO Selenium <- {"value":{"element-6066-11e4-a52e-4f735466cecf":"fd3bad89-bfb6-284f-88df-9b1a7473e01f"}}

irb(main):011:0> driver.switch_to.frame(frame)
2021-02-15 18:07:27 INFO Selenium -> POST session/ecd14b80-d2a5-a046-9def-3507d3a086ff/frame
2021-02-15 18:07:27 INFO Selenium    >>> http://127.0.0.1:4444/session/ecd14b80-d2a5-a046-9def-3507d3a086ff/frame | {"id":{"element-6066-11e4-a52e-4f735466cecf":"fd3bad89-bfb6-284f-88df-9b1a7473e01f"}}
2021-02-15 18:07:27 INFO Selenium <- {"value":null}
=> nil

irb(main):012:0> frame.click
2021-02-15 18:07:47 INFO Selenium -> POST session/ecd14b80-d2a5-a046-9def-3507d3a086ff/element/fd3bad89-bfb6-284f-88df-9b1a7473e01f/click
2021-02-15 18:07:47 INFO Selenium <- {"value":{"error":"no such element","message":"Web element reference not seen before: {\"element-6066-11e4-a52e-4f735466cecf\":\"fd3bad89-bfb6-284f-88df-9b1a7473e01f\"}","stacktrace":"WebDriverError@chrome://marionette/content/error.js:181:5\nNoSuchElementError@chrome://marionette/content/error.js:393:5\nelement.resolveElement@chrome://marionette/content/element.js:821:11\nevaluate.fromJSON@chrome://marionette/content/evaluate.js:233:26\nevaluate.fromJSON@chrome://marionette/content/evaluate.js:253:29\nreceiveMessage@chrome://marionette/content/actors/MarionetteCommandsChild.jsm:89:29\n"}}
```

**Comment by whimboo** [comment]
You cannot get a `stale element reference` error for an element that is part of a different browsing context. This kind of error you would only get from the exact same browsing context.

This was a bug and a fix landed in https://bugzilla.mozilla.org/show_bug.cgi?id=1684827.

Other vendors will have to follow-up with fixes. CC'ing @JohnChen0, @burg, @shs96c.

**Comment by whimboo** [comment]
Actually also CC'ing @k7z45.

**Comment by k7z45** [comment]
Thanks! Created https://bugs.chromium.org/p/chromedriver/issues/detail?id=3742 to track this.

**Comment by k7z45** [comment]
Hi @whimboo 
After making the change, we found that some wpt tests are failing such as this [one](https://github.com/web-platform-tests/wpt/blob/master/webdriver/tests/element_click/stale.py). Complete list of failing tests is [here](https://chromium-review.googlesource.com/c/chromium/src/+/2702554).

Do you know if there is going to be changes in wpt tests to reflect this?

**Comment by whimboo** [comment]
@k7z45 the reference stale test for `click_element` is correct and should not start failing. In this case the browsing context is not changed, and as such `stale element reference` needs to be returned.

I assume that all the others are also somewhat related.

**Comment by k7z45** [comment]
Thanks, I will revert my change for now.
