### ISSUE TITLE
Connection refused (os error 111) - failed comm between geckodriver and firefox on Ubuntu Server as www-data

### ISSUE THREAD

**Issue by sdragnev** [mozilla/geckodriver#1851]
## System

* Version: 0.29.0
* Platform: Ubuntu Server 20.04.2
* Firefox: 86.0
* Selenium: 3.141.0 (python)

## Testcase

```python
opts = webdriver.FirefoxOptions()
opts.binary_location = "/usr/bin/firefox"
opts.headless = True
opts.log.level = "trace"

browser = webdriver.Firefox(options=opts, service_log_path="/tmp/geckodriver.log")
browser.get("https://google.com")
print("Started browser")
print("Waiting 10 sec...")
time.sleep(10)
browser.close()
browser.quit()
```

## Stacktrace

```
Traceback (most recent call last):
  File "/var/www/code/sel/test_webdriver.py", line 34, in <module>
    browser = webdriver.Firefox(options=opts, service_log_path="/tmp/geckodriver.log")
  File "/var/www/code/sel/venv/lib/python3.8/site-packages/selenium/webdriver/firefox/webdriver.py", line 170, in __init__
    RemoteWebDriver.__init__(
  File "/var/www/code/sel/venv/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/var/www/code/sel/venv/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/var/www/code/sel/venv/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/var/www/code/sel/venv/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: Connection refused (os error 111)
```

## Trace-level log

```
1614642270000   geckodriver     INFO    Listening on 127.0.0.1:59275
1614642271013   mozrunner::runner       INFO    Running command: "/usr/bin/firefox" "--marionette" "-headless" "-foreground" "-no-remote" "-profile" "/tmp/rust_mozprofileHkVl1f"
1614642271014   geckodriver::marionette DEBUG   Waiting 60s to connect to browser on 127.0.0.1:46209
*** You are running in headless mode.
[GFX1-]: glxtest: Unable to open a connection to the X server
[GFX1-]: glxtest: libEGL initialize failed
1614642331088   mozrunner::runner       DEBUG   Killing process 687416
1614642331097   webdriver::server       DEBUG   <- 500 Internal Server Error {"value":{"error":"timeout","message":"Connection refused (os error 111)","stacktrace":""}}
```

This is only an issue when running a selenium script as the webserver user **www-data** on Ubuntu server.
There is no errors in the journal. This is the process output during the script run:

```
www-data  690539  690537  0 19:12 pts/5    00:00:00 geckodriver --port 35557
www-data  690546  690539  6 19:12 pts/5    00:00:00 /usr/lib/firefox/firefox --marionette -headless -foreground -no-remote -profile /tmp/rust_mozprofileMpFydk
```
Both geckodriver and firefox appear to be running but I think something is wrong with the firefox instance.

This is what the processes look like when running the script as a regular user:

```
glenn     690960  690954  0 19:13 pts/1    00:00:00 geckodriver --port 60519
glenn     690969  690960 99 19:13 pts/1    00:00:07 /usr/lib/firefox/firefox --marionette -headless -foreground -no-remote -profile /tmp/rust_mozprofilejyIyJd
glenn     691028  690969 38 19:13 pts/1    00:00:01 /usr/lib/firefox/firefox -contentproc -childID 1 -isForBrowser -prefsLen 1 -prefMapSize 224737 -parentBuildID 20210222142601 -appdir /usr/lib/firefox/browser 690969 true tab
glenn     691055  690969 31 19:13 pts/1    00:00:00 /usr/lib/firefox/firefox -contentproc -childID 2 -isForBrowser -prefsLen 85 -prefMapSize 224737 -parentBuildID 20210222142601 -appdir /usr/lib/firefox/browser 690969 true tab
glenn     691163  690969 40 19:13 pts/1    00:00:00 /usr/lib/firefox/firefox -contentproc -childID 3 -isForBrowser -prefsLen 13466 -prefMapSize 224737 -parentBuildID 20210222142601 -appdir /usr/lib/firefox/browser 690969 true tab
```

This could be a firefox problem or it could it a ubuntu problem but I doubt ubuntu support would be very familiar and thus helpful with this. Maybe someone well-versed in the geckodriver-firefox communication can weigh in with ways to further troubleshoot this.
My hunch is that there is something limiting about firefox running as www-data but I see no errors or other notices in the logs which would suggest an issue.

Thanks!
Needless to say, It's been driving me bonkers.

**Comment by whimboo** [comment]
The problem here is not geckodriver but trying to start Firefox in headless mode:

```
*** You are running in headless mode.
[GFX1-]: glxtest: Unable to open a connection to the X server
[GFX1-]: glxtest: libEGL initialize failed
```

As you can see Firefox is not able to open a connection to the X server and as such dies. Does the same happen when you start Firefox directly with the `--headless` option? I most likely believe so. Given that it runs with `www-data` permissions it might not be allowed to use the X server.

**Comment by sdragnev** [comment]
Those errors are a red herring - they get thrown when running the script as a regular user as well, which goes through.
Here's an example trace from a process that works:

```
1614691251266   geckodriver     INFO    Listening on 127.0.0.1:43537
1614691252277   mozrunner::runner       INFO    Running command: "/usr/bin/firefox" "--marionette" "-headless" "-foreground" "-no-remote" "-profile" "/tmp/rust_mozprofileWli2zy"
1614691252278   geckodriver::marionette DEBUG   Waiting 60s to connect to browser on 127.0.0.1:35907
*** You are running in headless mode.
[GFX1-]: glxtest: Unable to open a connection to the X server
[GFX1-]: glxtest: libEGL initialize failed
1614691253028   Marionette      TRACE   Marionette enabled
1614691253111   Marionette      TRACE   Received observer notification toplevel-window-ready

(/usr/lib/firefox/firefox:755217): GLib-GObject-CRITICAL **: 08:20:54.115: g_object_set: assertion 'G_IS_OBJECT (object)' failed

(/usr/lib/firefox/firefox:755238): GLib-GObject-CRITICAL **: 08:20:54.399: g_object_set: assertion 'G_IS_OBJECT (object)' failed
console.warn: SearchSettings: "get: No settings file exists, new profile?" (new Error("", "(unknown module)"))
1614691256121   Marionette      TRACE   Received observer notification marionette-startup-requested
1614691256121   Marionette      TRACE   Waiting until startup recorder finished recording startup scripts...
1614691256238   Marionette      TRACE   All scripts recorded.
1614691256239   Marionette      DEBUG   Setting recommended pref apz.content_response_timeout to 60000
1614691256239   Marionette      DEBUG   Setting recommended pref browser.contentblocking.introCount to 99
(...)
1614691256253   Marionette      DEBUG   Setting recommended pref signon.rememberSignons to false
1614691256258   Marionette      INFO    Listening on port 35907
1614691256258   Marionette      DEBUG   Marionette is listening

(/usr/lib/firefox/firefox:755324): GLib-GObject-CRITICAL **: 08:20:56.274: g_object_set: assertion 'G_IS_OBJECT (object)' failed
1614691256343   Marionette      DEBUG   Accepted connection 0 from 127.0.0.1:40440
1614691256347   geckodriver::marionette DEBUG   Connection to Marionette established on 127.0.0.1:35907.
1614691256371   Marionette      DEBUG   0 -> [0,1,"WebDriver:NewSession",{"acceptInsecureCerts":true,"browserName":"firefox"}]
1614691256372   Marionette      WARN    TLS certificate errors will be ignored for this session
1614691256396   Marionette      DEBUG   0 <- [1,1,null,{"sessionId":"e197f696-62a6-4901-8438-ade925c174cd","capabilities":{"browserName":"firefox","browserVersion":"86.0" ... /rust_mozprofileWli2zy","moz:shutdownTimeout":60000,"moz:useNonSpecCompliantPointerOrigin":false,"moz:webdriverClick":true}}]
1614691256403   webdriver::server       DEBUG   <- 200 OK {"value":{"sessionId":"e197f696-62a6-4901-8438-ade925c174cd","capabilities":{"acceptInsecureCerts":true,"browserName":"firefox","browserVersion":"86.0","moz:accessibilityChecks":false,"moz:buildID":"20210222142601","moz:geckodriverVersion":"0.29.0","moz:headless":true,"moz:processID":755161,"moz:profile":"/tmp/rust_mozprofileWli2zy","moz:shutdownTimeout":60000,"moz:useNonSpecCompliantPointerOrigin":false,"moz:webdriverClick":true,"pageLoadStrategy":"normal","platformName":"linux","platformVersion":"5.4.0-66-generic","rotatable":false,"setWindowRect":true,"strictFileInteractability":false,"timeouts":{"implicit":0,"pageLoad":300000,"script":30000},"unhandledPromptBehavior":"dismiss and notify"}}}
1614691256408   webdriver::server       DEBUG   -> POST /session/e197f696-62a6-4901-8438-ade925c174cd/url {"url": "https://google.com"}
1614691256414   Marionette      DEBUG   0 -> [0,2,"WebDriver:Navigate",{"url":"https://google.com"}]
1614691256425   Marionette      TRACE   [15] MarionetteCommands actor created for window id 2147483649
1614691256435   Marionette      TRACE   [15] MarionetteEvents actor created for window id 2147483649
1614691256436   Marionette      TRACE   Received event beforeunload for about:blank
1614691256955   Marionette      TRACE   Received event pagehide for about:blank
1614691257487   Marionette      TRACE   [15] MarionetteEvents actor created for window id 2147483650
1614691257489   Marionette      TRACE   Received event DOMContentLoaded for https://www.google.com/
1614691257613   Marionette      TRACE   Received event pageshow for https://www.google.com/
1614691257614   Marionette      DEBUG   0 <- [1,2,null,{"value":null}]
1614691257625   webdriver::server       DEBUG   <- 200 OK {"value":null}
1614691267639   webdriver::server       DEBUG   -> DELETE /session/e197f696-62a6-4901-8438-ade925c174cd/window 
1614691267642   Marionette      DEBUG   0 -> [0,3,"WebDriver:CloseWindow",{}]
1614691267645   Marionette      DEBUG   0 <- [1,3,null,[]]
1614691267646   webdriver::server       DEBUG   Last window was closed, deleting session
1614691267646   webdriver::server       DEBUG   Deleting session
1614691267648   Marionette      DEBUG   0 -> [0,4,"Marionette:Quit",{"flags":["eForceQuit"]}]
1614691267650   Marionette      INFO    Stopped listening on port 35907
1614691267707   Marionette      TRACE   Received observer notification quit-application
1614691267714   Marionette      DEBUG   0 <- [1,4,null,{"cause":"shutdown"}]
1614691267762   Marionette      DEBUG   Closed connection 0
1614691268047   Marionette      TRACE   Received observer notification xpcom-will-shutdown
1614691268047   Marionette      DEBUG   Resetting recommended pref apz.content_response_timeout
(...)
1614691268056   Marionette      DEBUG   Resetting recommended pref signon.rememberSignons
1614691268057   Marionette      DEBUG   Marionette stopped listening
1614691268447   geckodriver::marionette DEBUG   Browser process stopped: exit code: 0
1614691268465   webdriver::server       DEBUG   <- 200 OK {"value":[]}
1614691268467   webdriver::server       DEBUG   -> DELETE /session/e197f696-62a6-4901-8438-ade925c174cd 
1614691268467   webdriver::server       DEBUG   <- 404 Not Found {"value":{"error":"invalid session id","message":"Tried to run command without establishing a connection","stacktrace":""}}
```

The user version throws additional errors (GLib-GObject-CRITICAL) which don't appear to bother it. I think those are thrown when child processes are created.

**Comment by sdragnev** [comment]
Issue was directory permissions... www-data's home dir is /var/www which it couldn't write to.
I had one error earlier about not being able to create /var/www/.cache which I rectified but apparently firefox was still quietly failing trying to create a .mozilla dir.

**Comment by whimboo** [comment]
Thanks for the info. Good to see it's now working for you.

**Comment by joshuakoh1** [comment]
@sdragnev How did you fix the permissions? I'm running the exact same software stack as you.

options = Options()
options.headless = True
driver = webdriver.Firefox(options=options, executable_path="./geckodriver")

```
1615570025855	geckodriver	INFO	Listening on 127.0.0.1:52455
1615570026867	mozrunner::runner	INFO	Running command: "/usr/bin/firefox" "--marionette" "-headless" "-foreground" "-no-remote" "-profile" "/tmp/rust_mozprofileaZD0TC"
*** You are running in headless mode.
[GFX1-]: glxtest: Unable to open a connection to the X server
[GFX1-]: glxtest: libEGL missing

(/usr/lib/firefox/firefox:16698): GLib-GObject-CRITICAL **: 17:27:08.332: g_object_set: assertion 'G_IS_OBJECT (object)' failed

(/usr/lib/firefox/firefox:16715): GLib-GObject-CRITICAL **: 17:27:08.676: g_object_set: assertion 'G_IS_OBJECT (object)' failed
console.warn: SearchSettings: "get: No settings file exists, new profile?" (new Error("", "(unknown module)"))
console.error: Region.jsm: "Error fetching region" (new Error("TIMEOUT", "resource://gre/modules/Region.jsm", 775))
console.error: Region.jsm: "Failed to fetch region" (new Error("TIMEOUT", "resource://gre/modules/Region.jsm", 422))

(/usr/lib/firefox/firefox:16796): GLib-GObject-CRITICAL **: 17:27:59.308: g_object_set: assertion 'G_IS_OBJECT (object)' failed
1615570079580	Marionette	INFO	Listening on port 33383
1615570079663	Marionette	WARN	TLS certificate errors will be ignored for this session
```
