### ISSUE TITLE
OSError: [Errno 8] Exec format error (geckodriver=0.29.1, firefox-esr=78.9.0, selenium=3.141.0(python))

### ISSUE THREAD

**Issue by xulu199705** [mozilla/geckodriver#1871]
The geckodriver+selenium+firefox is running on raspberry pi (raspios).  
Below is a test in Python3.  
Could anyone give a solution?

## python3 test

``` python
Python 3.7.3 (default, Jan 22 2021, 20:04:44)
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from selenium import webdriver
>>> browser = webdriver.Firefox(executable_path='/usr/bin/geckodriver')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/pi/.local/lib/python3.7/site-packages/selenium/webdriver/firefox/webdriver.py", line 164, in __init__
    self.service.start()
  File "/home/pi/.local/lib/python3.7/site-packages/selenium/webdriver/common/service.py", line 76, in start
    stdin=PIPE)
  File "/usr/lib/python3.7/subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.7/subprocess.py", line 1522, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 8] Exec format error: '/usr/bin/geckodriver'
```

## ENV info

**raspios-image used:** ```2021-03-04-raspios-buster-armhf-lite.img```

**OS info**
``` bash
Distributor ID: Raspbian
Description:    Raspbian GNU/Linux 10 (buster)
Release:        10
Codename:       buster
```

**geckodriver version:** ```geckodriver-v0.29.1-linux64```

**firefox version:** ```Mozilla Firefox 78.9.0esr```

**selenium version:** ```selenium   3.141.0```

**Comment by whimboo** [comment]
The Rasperry Pi has an ARM cpu and as such a x86-64 binary for Linux doesn't work. If you want to run geckodriver directly on the ARM device you will have to [build geckodriver on your own](https://firefox-source-docs.mozilla.org/testing/geckodriver/ARM.html).
