### ISSUE TITLE
Firefox not opening on remote server

### ISSUE THREAD

**Issue by aakwal** [mozilla/geckodriver#1909]
## System

* Version: geckodriver-v0.28.0-linux64
* Platform: Rhel 8.2
* Firefox: 68.6.0esr (64bit)
* Selenium: selenium-server-standalone-3.141.59.jar

## Testcase

    driver = webdriver.Remote(
        desired_capabilities=webdriver.DesiredCapabilities.FIREFOX,
        command_executor='http://ip:4444/wd/hub'

    )

## Trace-level log

<!--
See https://searchfox.org/mozilla-central/source/testing/geckodriver/doc/TraceLogs.md
for how to produce a trace-level log.

For trace logs with more than 20 lines please add its contents as attachment.

Error:
C:\Users\Administrator\AppData\Local\Programs\Python\Python39\python.exe C:/Users/Administrator/PycharmProject/Sum_Automation(Selenium_grid)/Main_Script.py
Im in node
Traceback (most recent call last):
  File "C:\Users\Administrator\PycharmProject\Sum_Automation(Selenium_grid)\Main_Script.py", line 7, in <module>
    s.open_browser()
  File "C:\Users\Administrator\PycharmProject\Sum_Automation(Selenium_grid)\sum_script.py", line 12, in open_browser
    driver = webdriver.Remote(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium-4.0.0b3-py3.9.egg\selenium\webdriver\remote\webdriver.py", line 217, in __init__
    self.start_session(capabilities, browser_profile)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium-4.0.0b3-py3.9.egg\selenium\webdriver\remote\webdriver.py", line 308, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium-4.0.0b3-py3.9.egg\selenium\webdriver\remote\webdriver.py", line 369, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium-4.0.0b3-py3.9.egg\selenium\webdriver\remote\errorhandler.py", line 236, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: Unable to create session from {
  "desiredCapabilities": {
    "browserName": "firefox",
    "server:CONFIG_UUID": "de22059c-d7ed-4685-81cd-58583ca7528b",
    "moz:debuggerAddress": true,
    "acceptInsecureCerts": true
  },
  "capabilities": {
    "firstMatch": [
      {
        "acceptInsecureCerts": true,
        "browserName": "firefox",
        "moz:debuggerAddress": true,
        "server:CONFIG_UUID": "de22059c-d7ed-4685-81cd-58583ca7528b"
      }
    ]
  }
}
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:53'
System info: host: 'localhost.localdomain', ip: '127.0.0.1', os.name: 'Linux', os.arch: 'amd64', os.version: '4.18.0-193.el8.x86_64', java.version: '1.8.0_242'
Driver info: driver.version: unknown
Stacktrace:
    at org.openqa.selenium.remote.server.NewSessionPipeline.lambda$null$4 (NewSessionPipeline.java:76)
    at java.util.Optional.orElseThrow (Optional.java:290)
    at org.openqa.selenium.remote.server.NewSessionPipeline.lambda$createNewSession$5 (NewSessionPipeline.java:75)
    at java.util.Optional.orElseGet (Optional.java:267)
    at org.openqa.selenium.remote.server.NewSessionPipeline.createNewSession (NewSessionPipeline.java:73)
    at org.openqa.selenium.remote.server.commandhandler.BeginSession.execute (BeginSession.java:65)
    at org.openqa.selenium.remote.server.WebDriverServlet.lambda$handle$0 (WebDriverServlet.java:235)
    at java.util.concurrent.Executors$RunnableAdapter.call (Executors.java:511)
    at java.util.concurrent.FutureTask.run (FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:624)
    at java.lang.Thread.run (Thread.java:748)

Process finished with exit code 1

**Comment by aakwal** [comment]
@whimboo Can you please help?

**Comment by whimboo** [comment]
Could you please attach a [trace-level log] from geckodriver? Read more about reporting actionable bugs in our [contribution guidelines]. Thanks!

[trace-level log]: https://firefox-source-docs.mozilla.org/testing/geckodriver/TraceLogs.html
[contribution guidelines]: https://firefox-source-docs.mozilla.org/testing/geckodriver/Bugs.html

**Comment by whimboo** [comment]
No reply from reporter. Closing the issue.
