### ISSUE TITLE
Selenium test fails because of Firefox autoupdate

### ISSUE THREAD

**Issue by JohnA2** [mozilla/geckodriver#1911]
Sometimes when I run a Selenium test, I see that Firefox updater starts instead of the browser and it makes the test fail. Is it possible to prevent autoupdate if the browser is started by geckodriver?

## System

* Version: 0.29.0
* Platform: Windows
* Firefox: 90
* Selenium: Java 4.0.0 beta 4

## Testcase

any

## Stacktrace

```
org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Response code 500. Message: Process unexpectedly closed with status 0
Build info: version: '4.0.0-beta-4', revision: '29f46d02dd'
System info: host: ..., ip: ..., os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_202'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Command: [null, newSession {capabilities=[Capabilities {acceptInsecureCerts: true, browserName: firefox, moz:debuggerAddress: true, moz:firefoxOptions: {}}], desiredCapabilities=Capabilities {acceptInsecureCerts: true, browserName: firefox, moz:debuggerAddress: true, moz:firefoxOptions: {}}}]
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:126)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:84)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:62)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:156)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.invokeExecute(DriverCommandExecutor.java:162)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:137)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:547)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:244)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:166)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:205)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:193)
	at <my code>
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:523)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:224)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:146)
	at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:166)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:105)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
```

**Comment by whimboo** [comment]
We turn off automatic updates for Firefox when it gets started via geckodriver. Maybe in such a situation Firefox as run with your normal daily profile might have already downloaded an update, and is waiting for a restart to apply that?

**Comment by JohnA2** [comment]
> 
> 
> Maybe in such a situation Firefox as run with your normal daily profile might have already downloaded an update, and is waiting for a restart to apply that?

Yes, probably that's what happened. At least today Firefox with my daily profile was already open when I started the test and it probably has downloaded the update by that time. In that case it's not such a big issue. I'll close this bug.

**Comment by whimboo** [comment]
It might actually be still worth filing a bug for Firefox in https://bugzilla.mozilla.org/enter_bug.cgi?product=Toolkit&component=Application%20Update. Maybe there is a way that it can be prevented, but the pref that controls that behavior is read after the profile selection, and as such might be too late.

**Comment by JohnA2** [comment]
My main concern was that it can happen on dedicated servers that we use for Selenium Grid. If it's only my local environment that can fail once in a while, it's not a big deal. So I would rather not fill a bug and not waste time of Firefox developers. It's better if they spend that time working on existing and more serious bugs, like https://bugzilla.mozilla.org/show_bug.cgi?id=1421766 :)
