### ISSUE TITLE
ERROR_SIGNEDSTATE_REQUIRED: The addon must be signed and isn't.

### ISSUE THREAD

**Issue by fregante** [mozilla/geckodriver#1912]
I've been trying to test a WebExtension with Selenium but I'm stuck on this issue. It seems that previous Mozilla examples required [long manual configuration](https://github.com/mozilla/example-addon-repo/blob/b45f244263252633b05282e1275004fc6ede5ffa/test/functional/utils.js#L66-L92) to allow unsigned extensions and 5 years ago a Mozillian [mentioned that that code would be part of geckodriver](https://github.com/mozilla/web-ext/issues/5#issuecomment-257522237).

Am I missing something or is that the only way to load extensions via GeckoDriver?

## System

* Version: 0.29.1
* Platform: macOS
* Firefox: 90.0.2
* Selenium: selenium-webdriver@4.0.0-beta.4 on npm 

## Testcase

Any extension, like https://github.com/mdn/webextensions-examples/tree/master/apply-css

```js
const webdriver = require("selenium-webdriver");

require("geckodriver");
async function init() {
  const builder = new webdriver.Builder();
  builder.withCapabilities({
    browser: "firefox",
    browserName: "firefox",
    browser_version: "latest",
    name: "firefox test",
  });

  const driver = await builder.build();
  await driver.installAddon('path/to/file.zip');
}
```

## Stacktrace

```
(node:84761) UnhandledPromiseRejectionWarning: WebDriverError: Failed to decode response from marionette
    at Object.throwDecodedError (./node_modules/selenium-webdriver/lib/error.js:517:15)
    at parseHttpResponse (./node_modules/selenium-webdriver/lib/http.js:642:13)
    at Executor.execute (./node_modules/selenium-webdriver/lib/http.js:568:28)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Driver.execute (./node_modules/selenium-webdriver/lib/webdriver.js:731:17)
    at async runInBrowser (./selenium/sample-build.js:153:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:84761) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:84761) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

## Trace-level log

I think this is a browser error more than a geckodriver error.

**Comment by whimboo** [comment]
Could you please attach a [trace-level log] from geckodriver? Read more about reporting actionable bugs in our [contribution guidelines].

[trace-level log]: https://firefox-source-docs.mozilla.org/testing/geckodriver/TraceLogs.html
[contribution guidelines]: https://firefox-source-docs.mozilla.org/testing/geckodriver/Bugs.html

**Comment by fregante** [comment]
I'm unable to produce the log for my node code. I added the argument manually and I see that `geckodriver` is being executed with the arguments `[ '-vv', '--port=64873' ]` but the output doesn't change.

**Comment by whimboo** [comment]
geckodriver logs to `stdout`. As such you would have to check what webdriver.js is actually doing here, and where it gets stored. Maybe check your current working directory for a possible `geckodriver.log` file.

**Comment by fregante** [comment]
I found a way: https://github.com/SeleniumHQ/selenium/issues/6219

<details>
<summary>Trace log</summary>

```
1627394007451geckodriverINFOListening on 127.0.0.1:4444
1627394010940webdriver::serverDEBUG-> POST /session {"desiredCapabilities":{"browser":"firefox","browserName":"firefox","browser_version":"latest","bstack:options":{"os":"Windows","osVersion":"10"},"name":"firefox test"},"capabilities":{"alwaysMatch":{"browserName":"firefox","bstack:options":{"os":"Windows","osVersion":"10"}}}}
1627394010944mozrunner::runnerINFORunning command: "/Applications/Firefox.app/Contents/MacOS/firefox-bin" "--marionette" "-foreground" "-no-remote" "-profile" "/var/folders/jx/zxcvz4sj195b3vf9l_7ycjsm0000gn/T/rust_mozprofileyQHGGh"
1627394010945geckodriver::marionetteDEBUGWaiting 60s to connect to browser on 127.0.0.1:51855
1627394011266MarionetteINFOMarionette enabled
1627394011349MarionetteTRACEReceived observer notification toplevel-window-ready
console.warn: SearchSettings: "get: No settings file exists, new profile?" (new NotFoundError("Could not open the file at /var/folders/jx/zxcvz4sj195b3vf9l_7ycjsm0000gn/T/rust_mozprofileyQHGGh/search.json.mozlz4", (void 0)))
console.error: BackgroundUpdate: 
  _reasonsToNotScheduleUpdates: Failed to check for Maintenance Service Registry Key: [Exception... "Component returned failure code: 0x80004001 (NS_ERROR_NOT_IMPLEMENTED) [nsIUpdateProcessor.getServiceRegKeyExists]"  nsresult: "0x80004001 (NS_ERROR_NOT_IMPLEMENTED)"  location: "JS frame :: resource://gre/modules/BackgroundUpdate.jsm :: _reasonsToNotScheduleUpdates :: line 243"  data: no]
1627394012751MarionetteTRACEReceived observer notification marionette-startup-requested
1627394012751MarionetteTRACEWaiting until startup recorder finished recording startup scripts…
1627394012757MarionetteTRACEAll scripts recorded.
1627394012757MarionetteDEBUGSetting recommended pref apz.content_response_timeout to 60000
1627394012758MarionetteDEBUGSetting recommended pref browser.contentblocking.introCount to 99
1627394012758MarionetteDEBUGSetting recommended pref browser.download.panel.shown to true
1627394012758MarionetteDEBUGSetting recommended pref browser.newtabpage.enabled to false
1627394012759MarionetteDEBUGSetting recommended pref browser.pagethumbnails.capturing_disabled to true
1627394012759MarionetteDEBUGSetting recommended pref browser.search.update to false
1627394012759MarionetteDEBUGSetting recommended pref browser.tabs.disableBackgroundZombification to false
1627394012759MarionetteDEBUGSetting recommended pref browser.tabs.remote.separatePrivilegedContentProcess to false
1627394012759MarionetteDEBUGSetting recommended pref browser.tabs.unloadOnLowMemory to false
1627394012759MarionetteDEBUGSetting recommended pref browser.tabs.warnOnCloseOtherTabs to false
1627394012759MarionetteDEBUGSetting recommended pref browser.tabs.warnOnOpen to false
1627394012759MarionetteDEBUGSetting recommended pref browser.toolbars.bookmarks.visibility to never
1627394012759MarionetteDEBUGSetting recommended pref browser.usedOnWindows10.introURL to 
1627394012759MarionetteDEBUGSetting recommended pref browser.urlbar.suggest.searches to false
1627394012760MarionetteDEBUGSetting recommended pref datareporting.policy.dataSubmissionPolicyAccepted to false
1627394012760MarionetteDEBUGSetting recommended pref dom.disable_beforeunload to true
1627394012760MarionetteDEBUGSetting recommended pref dom.disable_open_during_load to false
1627394012760MarionetteDEBUGSetting recommended pref dom.file.createInChild to true
1627394012760MarionetteDEBUGSetting recommended pref dom.max_chrome_script_run_time to 0
1627394012760MarionetteDEBUGSetting recommended pref dom.max_script_run_time to 0
1627394012761MarionetteDEBUGSetting recommended pref dom.push.connection.enabled to false
1627394012761MarionetteDEBUGSetting recommended pref extensions.getAddons.cache.enabled to false
1627394012761MarionetteDEBUGSetting recommended pref extensions.getAddons.discovery.api_url to data:, 
1627394012761MarionetteDEBUGSetting recommended pref network.http.prompt-temp-redirect to false
1627394012761MarionetteDEBUGSetting recommended pref privacy.trackingprotection.enabled to false
1627394012761MarionetteDEBUGSetting recommended pref security.fileuri.strict_origin_policy to false
1627394012761MarionetteDEBUGSetting recommended pref security.notification_enable_delay to 0
1627394012761MarionetteDEBUGSetting recommended pref signon.autofillForms to false
1627394012762MarionetteDEBUGSetting recommended pref signon.rememberSignons to false
1627394012766MarionetteINFOListening on port 51855
1627394012767MarionetteDEBUGMarionette is listening
1627394012805MarionetteDEBUGAccepted connection 0 from 127.0.0.1:51881
1627394012806geckodriver::marionetteDEBUGConnection to Marionette established on 127.0.0.1:51855.
1627394012809MarionetteDEBUG0 -> [0,1,"WebDriver:NewSession",{"browserName":"firefox","bstack:options":{"os":"Windows","osVersion":"10"}}]
1627394012816MarionetteDEBUG0 <- [1,1,null,{"sessionId":"eda59f4f-4dc1-ce4a-b04e-53155765937f","capabilities":{"browserName":"firefox","browserVersion":"90.0. ... nSpecCompliantPointerOrigin":false,"moz:webdriverClick":true,"bstack:options":{"os":"Windows","osVersion":"10"},"proxy":{}}}]
1627394012817webdriver::serverDEBUG<- 200 OK {"value":{"sessionId":"eda59f4f-4dc1-ce4a-b04e-53155765937f","capabilities":{"acceptInsecureCerts":false,"browserName":"firefox","browserVersion":"90.0.2","bstack:options":{"os":"Windows","osVersion":"10"},"moz:accessibilityChecks":false,"moz:buildID":"20210721174149","moz:geckodriverVersion":"0.29.1","moz:headless":false,"moz:processID":98209,"moz:profile":"/var/folders/jx/zxcvz4sj195b3vf9l_7ycjsm0000gn/T/rust_mozprofileyQHGGh","moz:shutdownTimeout":60000,"moz:useNonSpecCompliantPointerOrigin":false,"moz:webdriverClick":true,"pageLoadStrategy":"normal","platformName":"mac","platformVersion":"20.5.0","proxy":{},"setWindowRect":true,"strictFileInteractability":false,"timeouts":{"implicit":0,"pageLoad":300000,"script":30000},"unhandledPromptBehavior":"dismiss and notify"}}}
1627394018762webdriver::serverDEBUG-> POST /session/eda59f4f-4dc1-ce4a-b04e-53155765937f/moz/addon/install {"addon":"<CLIPPED BASE 64 ZIPFILE>","temporary":false}
1627394018859MarionetteDEBUG0 -> [0,2,"Addon:Install",{"path":"/var/folders/jx/zxcvz4sj195b3vf9l_7ycjsm0000gn/T/addon-30b673e2-008e-4fb5-af2a-6a1d2d14dfd5.xpi","temporary":false}]
1627394018888MarionetteDEBUG0 <- [1,2,{"error":"unknown error","message":"Could not install add-on: /var/folders/jx/zxcvz4sj195b3vf9l_7ycjsm0000gn/T/addon-30b ... :181:5\nUnknownError@chrome://marionette/content/error.js:488:5\ninstall@chrome://marionette/content/addon.js:86:13\n"},null]
1627394018888webdriver::serverDEBUG<- 500 Internal Server Error {"value":{"error":"unknown error","message":"Could not install add-on: /var/folders/jx/zxcvz4sj195b3vf9l_7ycjsm0000gn/T/addon-30b673e2-008e-4fb5-af2a-6a1d2d14dfd5.xpi: ERROR_SIGNEDSTATE_REQUIRED: The addon must be signed and isn't.","stacktrace":"WebDriverError@chrome://marionette/content/error.js:181:5\nUnknownError@chrome://marionette/content/error.js:488:5\ninstall@chrome://marionette/content/addon.js:86:13\n"}}
[GFX1-]: Receive IPC close with reason=AbnormalShutdown
[GFX1-]: Receive IPC close with reason=AbnormalShutdown
```

</details>

**Comment by fregante** [comment]
I noticed something in the log above:

> 1627394018762webdriver::serverDEBUG-> POST /session/eda59f4f-4dc1-ce4a-b04e-53155765937f/moz/addon/install {"addon":"<CLIPPED BASE 64 ZIPFILE>","temporary":false}


👉 `"temporary":false`

Firefox does not allow unsigned addons to be installed temporarily… but it does allow temporary installations!

The solution was:

```diff
-  await driver.installAddon('path/to/file.zip');
+  await driver.installAddon('path/to/file.zip', true);
```

Halleluja.

**Comment by whimboo** [comment]
Yes, indeed. When you have a look at the failure line as returned by geckodriver you can see `ERROR_SIGNEDSTATE_REQUIRED: The addon must be signed and isn't`. So it's great you found out that this extra argument is needed for this Selenium binding.

Nevertheless the error as reported by Selenium could be clearer to make failures like that more easily discoverable.
