### ISSUE TITLE
GeckoDriver is unable to execute AutoIT script

### ISSUE THREAD

**Issue by plaidshirtakos** [mozilla/geckodriver#1915]
## System

* Version: 0.29.1
* Platform: Windows 10
* Firefox: 91.0
* Selenium: 3.141.59

## Testcase

Browser is unable to wait for exe file to be executed. I use WebDriver with GeckoDriver 0.29.1. When I try to execute AutoIT script, I get following error:
    _JavaScript error: resource:///modules/Interactions.jsm, line 209: NS_ERROR_FAILURE: Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsIUserIdleService.removeIdleObserver] JavaScript error: chrome://remote/content/marionette/cert.js, line 55: NS_ERROR_NOT_AVAILABLE: Component returned failure code: 0x80040111 (NS_ERROR_NOT_AVAILABLE) [nsICertOverrideService.setDisableAllSecurityChecksAndLetAttackersInterceptMyData]

    org.openqa.selenium.NoSuchWindowException: Browsing context has been discarded_

Same code is working well with use of chromedriver:

```
        String autoITExecutable = "C:\\util\\filechooser.exe \"" + fileSource + "\"";
        try {
            Runtime.getRuntime().exec(autoITExecutable);
        } catch (IOException e) {
            e.printStackTrace();
        }
```

Code to check if input field is filled:
```
        wait.until(new ExpectedCondition<Boolean>() {
            public Boolean apply(WebDriver d) {
                WebElement el = d.findElement(By.xpath("//*[@id=\"file-path-a\"]"));
                String value = el.getAttribute("value");
                if(value.length() != 0 && !value.equals("0")) {
                    return true;
                }
                return false;
            }
        }
```

## Stacktrace

1629120252217	Marionette	INFO	Stopped listening on port 62881
JavaScript error: resource:///modules/Interactions.jsm, line 209: NS_ERROR_FAILURE: Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsIUserIdleService.removeIdleObserver]
JavaScript error: chrome://remote/content/marionette/cert.js, line 55: NS_ERROR_NOT_AVAILABLE: Component returned failure code: 0x80040111 (NS_ERROR_NOT_AVAILABLE) [nsICertOverrideService.setDisableAllSecurityChecksAndLetAttackersInterceptMyData]

org.openqa.selenium.NoSuchWindowException: Browsing context has been discarded
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'mypc', ip: '100.64.18.32', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '15.0.2'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities {acceptInsecureCerts: true, browserName: firefox, browserVersion: 91.0, javascriptEnabled: true, moz:accessibilityChecks: false, moz:buildID: 20210804193234, moz:geckodriverVersion: 0.29.1, moz:headless: false, moz:processID: 14452, moz:profile: C:\Users\kovacsako\AppData\..., moz:shutdownTimeout: 60000, moz:useNonSpecCompliantPointerOrigin: false, moz:webdriverClick: true, pageLoadStrategy: normal, platform: WINDOWS, platformName: WINDOWS, platformVersion: 10.0, proxy: Proxy(), setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify}
Session ID: 5735164b-d3d0-4eaf-b46c-9bbcecdf2f8e
*** Element info: {Using=xpath, value=//*[@id="file-path-a"]}

	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:187)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:122)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:49)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:323)
	at org.openqa.selenium.remote.RemoteWebDriver.findElementByXPath(RemoteWebDriver.java:428)
	at org.openqa.selenium.By$ByXPath.findElement(By.java:353)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:315)

**Comment by whimboo** [comment]
I'm not sure what you are trying to do here. Maybe you can give more details which executable calls geckodriver with which arguments? Also a full geckodriver [trace-level log] would be great to have.

[trace-level log]: https://firefox-source-docs.mozilla.org/testing/geckodriver/TraceLogs.html

**Comment by whimboo** [comment]
No reply from reporter. Closing the issue.
