### ISSUE TITLE
Groovy script fails to run in SoapUI open source version 5.6.0

### ISSUE THREAD

**Issue by dfcoffin** [mozilla/geckodriver#1917]
## System

* Version: geckodriver-v.0.29.1-linux64
* Platform: Ubuntu 20.04.2 LTS
* Firefox: 91.0 (64-bit) Mozilla Friefox for Ubuntu cononical -1.0
* Selenium: selenium-java-3.141.59

**Comment by dfcoffin** [comment]
Issue reported to SeleniumHQ/selenium as well

**Comment by whimboo** [comment]
Could you please attach a [trace-level log] from geckodriver? Read more about reporting actionable bugs in our [contribution guidelines].

[trace-level log]: https://firefox-source-docs.mozilla.org/testing/geckodriver/TraceLogs.html
[contribution guidelines]: https://firefox-source-docs.mozilla.org/testing/geckodriver/Bugs.html

**Comment by dfcoffin** [comment]
I have attempted to generate a trace-level log and have tried to use several of the documented methods, but am unable a generated log from the problem.  The closest I can come is the following dump trace:

Mon Sep 06 17:14:33 EDT 2021:ERROR:java.lang.NoSuchMethodError: com.google.common.base.Preconditions.checkState(ZLjava/lang/String;Ljava/lang/Object;)V
   java.lang.NoSuchMethodError: com.google.common.base.Preconditions.checkState(ZLjava/lang/String;Ljava/lang/Object;)V
   	at org.openqa.selenium.remote.service.DriverService.checkExecutable(DriverService.java:146)
   	at org.openqa.selenium.firefox.GeckoDriverService.access$000(GeckoDriverService.java:44)
   	at org.openqa.selenium.firefox.GeckoDriverService$Builder.usingFirefoxBinary(GeckoDriverService.java:160)
   	at org.openqa.selenium.firefox.FirefoxDriver.toExecutor(FirefoxDriver.java:187)
   	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:147)
   	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:125)
   	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
   	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
   	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
   	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
   	at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:83)
   	at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:105)
   	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:59)
   	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:238)
   	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:242)
   	at Script14.run(Script14.groovy:14)
   	at com.eviware.soapui.support.scripting.groovy.SoapUIGroovyScriptEngine.run(SoapUIGroovyScriptEngine.java:90)
   	at com.eviware.soapui.impl.wsdl.teststeps.WsdlGroovyScriptTestStep.run(WsdlGroovyScriptTestStep.java:141)
   	at com.eviware.soapui.impl.wsdl.panels.teststeps.GroovyScriptStepDesktopPanel$RunAction$1.run(GroovyScriptStepDesktopPanel.java:250)
   	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
   	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
   	at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by whimboo** [comment]
Thanks. That was helpful. Given the above log the failure comes from:

https://github.com/SeleniumHQ/selenium/blob/e82be7d3584062a0d16af8d562d387e3d4855aa1/java/client/src/org/openqa/selenium/remote/service/DriverService.java#L146-L147

Make sure that the geckodriver binary can be found, and if the path is correct you should better file an issue against the Selenium repository. This is not related to geckodriver itself. That explains why no trace log can be created.

**Comment by dfcoffin** [comment]
The statement you referenced is looking for geckodriver.exe, but the problem is with the Linux version which has no .exe suffix

**Comment by whimboo** [comment]
The `exe` name stands for `executable` and is the geckodriver file path as passed in to Selenium:

https://github.com/SeleniumHQ/selenium/blob/e82be7d3584062a0d16af8d562d387e3d4855aa1/java/client/src/org/openqa/selenium/remote/service/DriverService.java#L140-L141
