### ISSUE TITLE
[Idea] Flags or something else for marking Download completed

### ISSUE THREAD

**Issue by ThaiLe011094** [mozilla/geckodriver#1923]
## System

* Version: 0.29.1
* Platform: Windows 10/11 + Manjaro Linux 21.1.1 Kernel 5.13
* Firefox: 91.0
* Selenium: selenium/standalone-firefox:4.0.0-rc-1-prerelease-20210823 (docker version)

## Current:
No built-in flags to tell that download process completed or not
Status return no values

## Logs:
```Traceback (most recent call last):
  File "/home/thai/deliveree/prod-airflow/connectors/test_python.py", line 53, in <module>
    driver = webdriver.Remote(command_executor='http://localhost:4444/wd/hub', 
  File "/home/thai/deliveree/prod-airflow/venv/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/home/thai/deliveree/prod-airflow/venv/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/home/thai/deliveree/prod-airflow/venv/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/thai/deliveree/prod-airflow/venv/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 130, in check_response
    status = value["status"]
KeyError: 'status'
```

## Expect:
Flags telling downloading process has been error/disconnected/completed

## Comments:
  I'm sorry if it's a wrong place to put since I didn't find anywhere else to write those

**Comment by whimboo** [comment]
I'm not sure what this request is about. It looks like it's more of an issue with `prod-airflow`. What kind of download flag are you talking about? If you can give a clear description I'm happy to reopen the issue.
