### ISSUE TITLE
Could not start a new session. Response code 500.

### ISSUE THREAD

**Issue by mNarraMine** [mozilla/geckodriver#1960]
## System

* Version: 0.30.0
* Platform: Linux amd64, 5.10.47-linuxkit
* Firefox: 94.0
* Selenium: 4.0.0-beta-3
* Docker
* Java

I have a tests using Cucumber. Since 20 of October all my Firefox jobs in CI failing throwing TimeOutException. At first I thought that tests are failing because I am trying to perform get(); 50 times in a row in a new browser tab but then I turned those tests off and got the same result before test start. I was trying to upgrade/downgrade Firefox version, remove webdrivermanager and set up driver manually via property, run tests in docker remotely via CI and locally. The error 500 came up before any random test constantly. Can't provide no more information right now because message below is all what I have for the moment.
Does anyone met this too and maybe know workaround? Thanks

## Stacktrace

`org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Response code 500. Message: Connection refused (os error 111)`

**Comment by whimboo** [comment]
The information that you were able to give so far doesn't help that much in further investigation what's wrong. As such please provide us some [trace level logs](https://firefox-source-docs.mozilla.org/testing/geckodriver/TraceLogs.html) from geckodriver. Thanks.

**Comment by bande-here** [comment]
Hi @whimboo, I am also facing similar issue once the Firefox got upgraded to 94.0.2
here is the log trace, hope this helps.

**System info:
  GeckoDriver Version: 0.30.0
  Firefox: 94.0.2
  os.name: 'Mac OS X', 
  os.arch: 'x86_64', 
  os.version: '11.6.1', 
  java.version: '11.0.12'**


[0-0] 2021-11-24T11:15:55.662Z **ERROR webdriver: Request failed with status 500 due to session not created: Unable to create new service: GeckoDriverService**
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:53'
Driver info: driver.version: unknown
    at Object.getErrorFromResponseBody (/qad/node_modules/webdriver/build/utils.js:94:12)
    at WebDriverRequest._request (/qad/node_modules/webdriver/build/request.js:134:31)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Object.startWebDriverSession (/qad/node_modules/webdriver/build/utils.js:29:20)
    at async Function.newSession (/qad/node_modules/webdriver/build/index.js:35:45)
    at async Object.exports.remote (/qad/node_modules/webdriverio/build/index.js:53:22)
    at async Runner._startSession (/qad/node_modules/@wdio/runner/build/index.js:123:56)
    at async Runner._initSession (/qad/node_modules/@wdio/runner/build/index.js:103:25)
    at async Runner.run (/qad/node_modules/@wdio/runner/build/index.js:52:19)
2021-11-24T11:15:55.664Z ERROR @wdio/runner: Error: Failed to create session.

**Comment by whimboo** [comment]
Note that this is not a trace level log, but just the one from Selenium. That's not helpful. So please provide the logs from geckodriver itself. Thanks.

**Comment by whimboo** [comment]
Without trace logs there is nothing that we can help with. Once provided and it shows a valid issue I'm happy to reopen this issue.
