### ISSUE TITLE
Firefox could not load to a certain webpage: we're having trouble finding that site. we cannot connect to the server at login.microsoftonline.com. if that address is correct, here are three other things you can try:  try again later.  check your network connection. if you are connected but behind a firewall, check that firefox has permission to access the web.

### ISSUE THREAD

**Issue by RLCai** [mozilla/geckodriver#1967]
System

Version: geckodriver version 
Platform:  Windows 10
Firefox:  93.0,
Selenium: 4.0.0 

Testcase

    @BeforeTest
    @Throws(Exception::class)
    fun setup(browser: String) {
            val cap = DesiredCapabilities()
            val options = FirefoxOptions()
            val profile = FirefoxProfile()
            profile.setPreference("browser.download.dir", folder!!.absolutePath)
            profile.setPreference("browser.download.folderList", 2)
            profile.setPreference(
                "browser.helperApps.neverAsk.saveToDisk",
                "image/jpeg, application/pdf, application/octet-stream"  )
            profile.setPreference("browser.download.manager.showWhenStarting", false)
            profile.setPreference("pdfjs.disabled", true)

            options.setLogLevel(FirefoxDriverLogLevel.TRACE)
            options.profile = profile
            cap.setCapability(FirefoxOptions.FIREFOX_OPTIONS, options)

            driver = RemoteWebDriver(URL("http://localhost:4444/wd/hub"), cap);           
           driver.manage().deleteAllCookies()
           driver.manage().window().maximize()
     }
    @Test
    @Throws(WebDriverException::class)
    fun login() {
        driver.get(baseurl)
        sleep(2000)
        val element = driver.findElement(By.xpath("//label[contains(text(),'Sign in)]"))
        val executor = driver as JavascriptExecutor
        executor.executeScript("arguments[0].click();", element)
        WebDriverWait(driver, 60).until(ExpectedConditions.elementToBeClickable(By.id("logonIdentifier")))
    }

## Stacktrace

org.openqa.selenium.TimeoutException: Expected condition failed: waiting for element to be clickable: By.id: logonIdentifier (tried for 60 second(s) with 500 milliseconds interval)
Build info: version: '4.0.0', revision: '3a21814679'
System info: host: 'LAPTOP-N1F9KB4D', ip: '192.168.222.62', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '11.0.12'
Driver info: org.openqa.selenium.remote.RemoteWebDriver
Capabilities {acceptInsecureCerts: true, browserName: firefox, browserVersion: 93.0, javascriptEnabled: true, moz:accessibilityChecks: false, moz:buildID: 20210927210923, moz:debuggerAddress: localhost:44197, moz:geckodriverVersion: 0.30.0, moz:headless: false, moz:processID: 6964, moz:profile: /tmp/rust_mozprofileHcour7, moz:shutdownTimeout: 60000, moz:useNonSpecCompliantPointerOrigin: false, moz:webdriverClick: true, pageLoadStrategy: normal, platform: LINUX, platformName: LINUX, platformVersion: 5.10.16.3-microsoft-standar..., proxy: Proxy(), se:cdp: ws://localhost:4444/session..., se:cdpVersion: 85, se:vnc: ws://localhost:4444/session..., se:vncEnabled: true, se:vncLocalAddress: ws://172.20.0.3:7900, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify}
Session ID: 96d6462d-6524-46e0-a8e9-007b7f16c3da

	at org.openqa.selenium.support.ui.WebDriverWait.timeoutException(WebDriverWait.java:138)
	at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:231)
	at com.testui_sequence.UITest.login(UITest.kt:125)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at org.testng.TestRunner.privateRun(TestRunner.java:794)
	at org.testng.TestRunner.run(TestRunner.java:596)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
	at org.testng.SuiteRunner.run(SuiteRunner.java:276)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
	at org.testng.TestNG.runSuites(TestNG.java:1063)
	at org.testng.TestNG.run(TestNG.java:1031)
	at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
	at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)

on the webpage shows:
we're having trouble finding that site. we cannot connect to the server at login.microsoftonline.com. if that address is correct, here are three other things you can try: 
try again later. 
check your network connection.
if you are connected but behind a firewall, check that firefox has permission to access the web.

I use docker, version for selenium hub is selenium/hub:4.0.0-20211013 and for firefox is selenium/node-firefox:4.0.0-20211013.
The selenium test first loads to baseurl, after clicking the login button, it loads to another url login.microsoftonline.com.
The tests have been run for almost one months. At first, this setting and tests worked fine, and about a week ago the problem occured. Now it occurs nearly 90% when run the tests.
At first, I think it could be the problem of browser cookie, so after the driver being set up I added:
driver.manage().deleteAllCookies()
But it does not help. 
Could anyone knows how to solve it? Thanks a lot.

**Comment by RLCai** [comment]
System

* Version: 
* Platform: 
* Firefox: 
* Selenium: 

Testcase




## Stacktrace

<!--

org.openqa.selenium.TimeoutException: Expected condition failed: waiting for element to be clickable: By.id: logonIdentifier (tried for 60 second(s) with 500 milliseconds interval)
Build info: version: '4.0.0', revision: '3a21814679'
System info: host: 'LAPTOP-N1F9KB4D', ip: '192.168.222.62', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '11.0.12'
Driver info: org.openqa.selenium.remote.RemoteWebDriver
Capabilities {acceptInsecureCerts: true, browserName: firefox, browserVersion: 93.0, javascriptEnabled: true, moz:accessibilityChecks: false, moz:buildID: 20210927210923, moz:debuggerAddress: localhost:44197, moz:geckodriverVersion: 0.30.0, moz:headless: false, moz:processID: 6964, moz:profile: /tmp/rust_mozprofileHcour7, moz:shutdownTimeout: 60000, moz:useNonSpecCompliantPointerOrigin: false, moz:webdriverClick: true, pageLoadStrategy: normal, platform: LINUX, platformName: LINUX, platformVersion: 5.10.16.3-microsoft-standar..., proxy: Proxy(), se:cdp: ws://localhost:4444/session..., se:cdpVersion: 85, se:vnc: ws://localhost:4444/session..., se:vncEnabled: true, se:vncLocalAddress: ws://172.20.0.3:7900, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify}
Session ID: 96d6462d-6524-46e0-a8e9-007b7f16c3da

	at org.openqa.selenium.support.ui.WebDriverWait.timeoutException(WebDriverWait.java:138)
	at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:231)
	at com.testui_sequence.UITest.login(UITest.kt:125)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at org.testng.TestRunner.privateRun(TestRunner.java:794)
	at org.testng.TestRunner.run(TestRunner.java:596)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
	at org.testng.SuiteRunner.run(SuiteRunner.java:276)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
	at org.testng.TestNG.runSuites(TestNG.java:1063)
	at org.testng.TestNG.run(TestNG.java:1031)
	at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
	at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)

on the webpage shows:
we're having trouble finding that site. we cannot connect to the server at login.microsoftonline.com. if that address is correct, here are three other things you can try: 
try again later. 
check your network connection.
if you are connected but behind a firewall, check that firefox has permission to access the web.
->

I use docker, version for selenium hub is selenium/hub:4.0.0-20211013 and for firefox is selenium/node-firefox:4.0.0-20211013.
The selenium test first loads to baseurl, after clicking the login button, it loads to another url login.microsoftonline.com.
The tests have been run for almost one months. At first, this setting and tests worked fine, and about a week ago the problem occured. Now it occurs nearly 90% when run the tests.
At first, I think it could be the problem of browser cookie, so after the driver being set up I added:
driver.manage().deleteAllCookies()
But it does not help. 
Could anyone knows how to solve it? Thanks a lot.

**Comment by whimboo** [comment]
Could you please attach a [trace-level log] from geckodriver? Read more about reporting actionable bugs in our [contribution guidelines].

[trace-level log]: https://firefox-source-docs.mozilla.org/testing/geckodriver/TraceLogs.html
[contribution guidelines]: https://firefox-source-docs.mozilla.org/testing/geckodriver/Bugs.html

**Comment by RLCai** [comment]
> Could you please attach a [trace-level log](https://firefox-source-docs.mozilla.org/testing/geckodriver/TraceLogs.html) from geckodriver? Read more about reporting actionable bugs in our [contribution guidelines](https://firefox-source-docs.mozilla.org/testing/geckodriver/Bugs.html).

Hej, Thanks for your response. I have already added 'options.setLogLevel(FirefoxDriverLogLevel.TRACE)' in my codes, but I don't really know where I can get the logs. Is there a default path?

**Comment by whimboo** [comment]
geckodriver usually logs to the current working directory but it could be that the Selenium binding is intercepting that and stores it somewhere else. This is something you will have to check in the appropriate Selenium docs for your binding.

**Comment by RLCai** [comment]
> geckodriver usually logs to the current working directory but it could be that the Selenium binding is intercepting that and stores it somewhere else. This is something you will have to check in the appropriate Selenium docs for your binding.

Hi, I got a log here, could you have a look if it helps. The process of the test is:

1. load to https://theCompany.com, then click on the "loging" button
2. webpage load to login.microsoftonline.com, and the user type in account and password, and then a confirm button.
3. [webpage](url) load to the https://theCompany.com again.

The problem is with the second step. Errors are showed different: sometimes it is said "we're having trouble finding that site. we cannot connect to the server at login.microsoftonline.com. if that address is correct, here are three other things you can try: try again later. check your network connection. if you are conn
[trace-log.txt](https://github.com/mozilla/geckodriver/files/7649373/trace-log.txt)
ected but behind a firewall, check that firefox has permission to access the web." And sometimes it just stayed on the first step (I saw that via VNC viewer),could not load to login.microsoftonline.com, but the error is: could not find the element By.id("logonIdentifier") which should be on the second step(login.microsoftonline.com).

**Comment by whimboo** [comment]
The trace log misses the whole first part of the session. But it shows that there is a failure in retrieving the `#logonIdentifier` element. As such the test fails. I assume the initial page might dynamically add this button, so you will have to wait for the button to appear. Use implicit wait or poll for it. 

Nothing here indicates that this is an issue with geckodriver. As such closing the issue. But I'm happy to reopen if it turns out otherwise. Thanks.
