### ISSUE TITLE
Service geckodriver unexpectedly exited status code: -7

### ISSUE THREAD

**Issue by sejahui** [mozilla/geckodriver#1969]
## System

* Version: 0.30.0 ( Geckodriver ver. )
* platform: Ubuntu Linux( on android tablet Galaxy tab S7 by andronix)
* Firefox: 75.0
* Selenium: 4.1.0

## Testcase

 
Written in Python

import selenium
from selenium import webdriver
driver = webdriver.Firefox()
driver.get('https://firefox-source-docs.mozilla.org/testing/geckodriver/Support.html')
driver.close()

## Stacktrace

sejahui@localhost:~/projects$  env PYTHONIOENCODING=UTF-8 PYTHONUNBUFFERED=1 /usr/bin/python3 /home/sejahui/.vscode-oss/extensions/ms-python.python-2020.6.91350/pythonFiles/ptvsd_launcher.py --default --client --host localhost --port 42097 /home/sejahui/projects/stock_data_crawler_selenium 
Traceback (most recent call last):
  File "/home/sejahui/.vscode-oss/extensions/ms-python.python-2020.6.91350/pythonFiles/ptvsd_launcher.py", line 48, in <module>
    main(ptvsdArgs)
  File "/home/sejahui/.vscode-oss/extensions/ms-python.python-2020.6.91350/pythonFiles/lib/python/old_ptvsd/ptvsd/__main__.py", line 432, in main
    run()
  File "/home/sejahui/.vscode-oss/extensions/ms-python.python-2020.6.91350/pythonFiles/lib/python/old_ptvsd/ptvsd/__main__.py", line 316, in run_file
    runpy.run_path(target, run_name='__main__')
  File "/usr/lib/python3.8/runpy.py", line 265, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/usr/lib/python3.8/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/sejahui/projects/stock_data_crawler_selenium", line 3, in <module>
    driver = webdriver.Firefox()
  File "/home/sejahui/.local/lib/python3.8/site-packages/selenium/webdriver/firefox/webdriver.py", line 174, in __init__
    self.service.start()
  File "/home/sejahui/.local/lib/python3.8/site-packages/selenium/webdriver/common/service.py", line 98, in start
    self.assert_process_still_running()
  File "/home/sejahui/.local/lib/python3.8/site-packages/selenium/webdriver/common/service.py", line 110, in assert_process_still_running
    raise WebDriverException(
selenium.common.exceptions.WebDriverException: Message: Service geckodriver unexpectedly exited. Status code was: -7

## Trace-level log

File "/home/sejahui/.vscode-oss/extensions/ms-python.python-2020.6.91350/pythonFiles/ptvsd_launcher.py", line 48, in <module>
    main(ptvsdArgs)
  File "/home/sejahui/.vscode-oss/extensions/ms-python.python-2020.6.91350/pythonFiles/lib/python/old_ptvsd/ptvsd/__main__.py", line 432, in main
    run()
  File "/home/sejahui/.vscode-oss/extensions/ms-python.python-2020.6.91350/pythonFiles/lib/python/old_ptvsd/ptvsd/__main__.py", line 316, in run_file
    runpy.run_path(target, run_name='__main__')
  File "/usr/lib/python3.8/runpy.py", line 265, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/usr/lib/python3.8/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/sejahui/projects/stock_data_crawler_selenium", line 3, in <module>
    driver = webdriver.Firefox()
  File "/home/sejahui/.local/lib/python3.8/site-packages/selenium/webdriver/firefox/webdriver.py", line 174, in __init__
    self.service.start()
  File "/home/sejahui/.local/lib/python3.8/site-packages/selenium/webdriver/common/service.py", line 98, in start
    self.assert_process_still_running()
  File "/home/sejahui/.local/lib/python3.8/site-packages/selenium/webdriver/common/service.py", line 110, in assert_process_still_running
    raise WebDriverException(
selenium.common.exceptions.WebDriverException: Message: Service geckodriver unexpectedly exited. Status code was: -7

Messages for geckodriver helper: I really wanted to know what the heck is this error. I saw many similar ones, and did many different ways, but, eventually I had always came back to this error. Please help. I can't step further just because of this unknown error.

**Comment by whimboo** [comment]
Could you please attach a [trace-level log] from geckodriver? Read more about reporting actionable bugs in our [contribution guidelines].

[trace-level log]: https://firefox-source-docs.mozilla.org/testing/geckodriver/TraceLogs.html
[contribution guidelines]: https://firefox-source-docs.mozilla.org/testing/geckodriver/Bugs.html

**Comment by sejahui** [comment]
Yes, I read te instructions and I found geckodriver.log file. However,
geckodriver.log file was empty. I also tried to use the code which is in
instruction, but, I don't exactly know how to use it. Can you tell me more
detailed instructions how I apply your python code to my code for
geckodriver log? I am new at programming, so, everything is always new to
me.

2021년 12월 12일 (일) 오후 6:08, Henrik Skupin ***@***.***>님이 작성:

**Comment by whimboo** [comment]
Maybe there is a problem with Selenium. As such please start geckodriver yourself by running the following in the command line: `geckodriver -vv --binary %path_to_firefox%`. Once done use another terminal to [send HTTP requests directly to geckodriver by eg. using `curl`](https://firefox-source-docs.mozilla.org/testing/geckodriver/Usage.html#standalone). Trace logs can then be seen in the first terminal where geckodriver is running.

**Comment by sejahui** [comment]
Yes, I tried that code in terminal. But, it gave me "Bus error".

2021년 12월 13일 (월) 오후 4:24, Henrik Skupin ***@***.***>님이 작성:

**Comment by sejahui** [comment]
Yes, I tried that code in terminal. But, it gave me "Bus error".


2021년 12월 13일 (월) 오후 4:24, Henrik Skupin ***@***.***>님이 작성:

**Comment by whimboo** [comment]
Please add an attachment to this issue that includes all the output that you get.

**Comment by sejahui** [comment]
I mean, I couldn't get files what you need after I ran that code in
terminal. Because I got "Buss Error".

2021년 12월 13일 (월) 19:09, Henrik Skupin ***@***.***>님이 작성:

**Comment by whimboo** [comment]
Without getting any further information we won't be able to help. Sorry. Once you are able to get these I'm happy to reopen the issue. Thanks.

**Comment by Xehia** [comment]
Hi, i have the same issue, i get `bus error` when i try to open the executable.

**Comment by whimboo** [comment]
@Xehia this issue is closed. Please report your issue with log details over on issue #1970. Thanks.

**Comment by whimboo** [comment]
@Xehia actually please file a new issue. The other one is closed as well.
