### ISSUE TITLE
Unable to specify ::1 as host

### ISSUE THREAD

**Issue by gjakovaime** [mozilla/geckodriver#1972]
## System

* Version: 0.30.0
* Platform: Windows 10
* Firefox: N/A
* Selenium: Selenium.WebDriver 3.141.0

## Testcase
```
 private IWebDriver GetFirefoxBrowser(bool isHeadless)
        {
            FirefoxOptions firefoxOptions = new FirefoxOptions();
            firefoxOptions.SetPreference("security.insecure_field_warning.contextual.enabled", false);
            firefoxOptions.SetPreference("security.certerrors.permanentOverride", false);
            firefoxOptions.SetPreference("network.stricttransportsecurity.preloadlist", false);
            firefoxOptions.SetPreference("security.enterprise_roots.enabled", true);
            firefoxOptions.LogLevel = FirefoxDriverLogLevel.Trace;

            var firefoxConfig = new FirefoxConfig();
            new DriverManager().SetUpDriver(firefoxConfig, "0.30.0");
            FirefoxDriverService service = FirefoxDriverService.CreateDefaultService();
            service.Host = "::1";
            return new FirefoxDriver(service, firefoxOptions);
        }
```
## Stacktrace
Cannot start the driver service on http://localhost:62453/
   at OpenQA.Selenium.DriverService.Start()
   at OpenQA.Selenium.Remote.DriverServiceCommandExecutor.Execute(Command commandToExecute)
   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Remote.RemoteWebDriver.StartSession(ICapabilities desiredCapabilities)
   at OpenQA.Selenium.Remote.RemoteWebDriver..ctor(ICommandExecutor commandExecutor, ICapabilities desiredCapabilities)
   at OpenQA.Selenium.Firefox.FirefoxDriver..ctor(FirefoxDriverService service, FirefoxOptions options, TimeSpan commandTimeout)
   at OpenQA.Selenium.Firefox.FirefoxDriver..ctor(FirefoxDriverService service, FirefoxOptions options)
   at Common.BrowserSetup.BrowserFactory.GetFirefoxBrowser(Boolean isHeadless) in C:\ommited-path\BrowserSetup\BrowserFactory.cs:line 116
   at Common.BrowserSetup.BrowserFactory.GetWebDriver(BrowserType browser, TestContext testContext) in C:\ommited-path\Common\BrowserSetup\BrowserFactory.cs:line 36
   at Common.Tests.BaseTest.TestInit(String browserType) in C:\ommited-path\Common\Tests\BaseTest.cs:line 23
   at CAPS.WEB.UI.Automation.Test.Tests.ConnectingFamiliesTests.FillOutBecomeMentorForm_DirectsTo_ThankYouSubmissionConfirmation(String browserType) in C:\dev\ommited-path\WEB.UI.Automation.Tests\Tests.cs:line 47

## Trace-level log
========== Starting test run ==========
The active test run was aborted. Reason: Test host process crashed : thread 'webdriver server' panicked at 'Failed to parse server hostname as a host: InvalidDomainCharacter', /builds/worker/workspace/build/src/testing/webdriver/src/server.rs:270:42
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

The same test above with gecko version 0.29.1 runs successfully. It's only when I upgrade to 0.30.0 that I see the issue. I'm attempting to have a workaround for the issues reported [here](https://stackoverflow.com/questions/33078586/firefox-webdriver-is-extremely-slow) and [here](https://github.com/mozilla/geckodriver/issues/1496).

**Comment by whimboo** [comment]
Does it work when you use `[::1]` as host?

**Comment by whimboo** [comment]
Actually it's crashing! I tried myself and can reproduce. There is https://bugzilla.mozilla.org/show_bug.cgi?id=1747306 on file now.

Thanks a lot for reporting it!

**Comment by whimboo** [comment]
@gjakovaime we fixed it for the next geckodriver release. Would you have the chance to check the behavior with a Nightly build of geckodriver? If yes, you can find the CI generated builds [here](https://treeherder.mozilla.org/jobs?repo=mozilla-central&searchStr=gd-s&revision=1fa7169d33613187ad34302520976f3bc96fdd30&selectedTaskRun=MybvQ1_mQ-OBqZP2gnbNTQ.0). The artifact (geckodriver.tar.gz) you can find in the lower pane. Thanks a lot.

I'm already closing this issue but we will reopen if it's not fully fixed.
