### ISSUE TITLE
Process unexpectedly closed with status 1 - No crash logs created

### ISSUE THREAD

**Issue by andreacanton** [mozilla/geckodriver#1973]
## System

* Version: 95
* Platform: Ubuntu 21.10
* Firefox: 95.0.2 (64 bit)
* Selenium: 4.1.0

## Testcase

```python
import time
from selenium import webdriver
from webdriver_manager.firefox import GeckoDriverManager
from selenium.webdriver.firefox.service import Service

service = Service(executable_path=GeckoDriverManager().install())
browser = webdriver.Firefox(service=service)
time.sleep(10)
browser.get('http://selenium.dev/')
print(browser.title())
```

## Stacktrace

```
====== WebDriver manager ======
Current firefox version is 95.0
Get LATEST geckodriver version for 95.0 firefox
Driver [/home/andreacanton/.wdm/drivers/geckodriver/linux64/v0.30.0/geckodriver] found in cache
Traceback (most recent call last):
  File "/home/andreacanton/repos/super-secret-project/main.py", line 9, in <module>
    browser = webdriver.Firefox(service=service)
  File "/home/andreacanton/repos/super-secret-project/venv/lib/python3.9/site-packages/selenium/webdriver/firefox/webdriver.py", line 179, in __init__
    RemoteWebDriver.__init__(
  File "/home/andreacanton/repos/super-secret-project/venv/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 268, in __init__
    self.start_session(capabilities, browser_profile)
  File "/home/andreacanton/repos/super-secret-project/venv/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 359, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/home/andreacanton/repos/super-secret-project/venv/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 424, in execute
    self.error_handler.check_response(response)
  File "/home/andreacanton/repos/super-secret-project/venv/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: Process unexpectedly closed with status 1
```

## Trace-level log

```
1640535323715	geckodriver	INFO	Listening on 127.0.0.1:47537
1640535323718	mozrunner::runner	INFO	Running command: "/snap/bin/firefox" "--marionette" "--remote-debugging-port" "57509" "-no-remote" "-profile" "/tmp/rust_mozprofile1lh0Sr"
```

I also followed this guide https://firefox-source-docs.mozilla.org/testing/geckodriver/CrashReports.html
But no crash report were created.

**Comment by whimboo** [comment]
Thank you for the report. The above log that you added is not a trace log. As such please retry by following the steps from https://firefox-source-docs.mozilla.org/testing/geckodriver/TraceLogs.html. It should help to figure out why Firefox is closing. Thanks.

**Comment by whimboo** [comment]
We are happy to reopen when you can provide further details. Thanks.
