### ISSUE TITLE
Unable to start Gecko Driver Service on localhost

### ISSUE THREAD

**Issue by miksch123** [mozilla/geckodriver#1987]
## System

* Version: 0.30.0
* Platform: Windows 10 64 bit
* Firefox: 97
* Selenium: 3.141.0

## Testcase

On initiating a driver session the driver runs into a WebDriverException with the message "Cannot start the driver service on http://localhost:54128/"

FirefoxOptions used: 
public static FirefoxOptions FirefoxOption(string lang)
        {
            FirefoxOptions option = new FirefoxOptions();
            option.SetPreference("intl.accept_languages", lang);
            option.SetPreference("intl.locale.requested", lang);
            option.AcceptInsecureCertificates = true;
            return option;
        }
Driver creation method used:
public static IWebDriver GetFirefoxDriver(string lang)
        {
            FirefoxDriverService service = FirefoxDriverService.CreateDefaultService("./");
            service.Host = "::1";
            service.HideCommandPromptWindow = true;
            IWebDriver CommonWebDriver = new FirefoxDriver(service, Options.FirefoxOption(lang));
            return CommonWebDriver ;
        }

## Stacktrace

Exception has occurred: CLR/OpenQA.Selenium.WebDriverException
An exception of type 'OpenQA.Selenium.WebDriverException' occurred in WebDriver.dll but was not handled in user code: 'Cannot start the driver service on http://localhost:54128/'
   at OpenQA.Selenium.DriverService.Start()
   at OpenQA.Selenium.Remote.DriverServiceCommandExecutor.Execute(Command commandToExecute)
   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Remote.RemoteWebDriver.StartSession(ICapabilities desiredCapabilities)
   at OpenQA.Selenium.Remote.RemoteWebDriver..ctor(ICommandExecutor commandExecutor, ICapabilities desiredCapabilities)
   at OpenQA.Selenium.Firefox.FirefoxDriver..ctor(FirefoxDriverService service, FirefoxOptions options, TimeSpan commandTimeout)
   at OpenQA.Selenium.Firefox.FirefoxDriver..ctor(FirefoxDriverService service, FirefoxOptions options)

Comments: Geckodriver version 0.29.0 did not run into this type of issue. Replacing IPv6 Host Service option with IPv4 localhost (aka 127.0.0.1) creates a session, but the driver session inevitably runs into Timeout issues. I am running my automation in a dontet core 3.1 solution using C#.

**Comment by whimboo** [comment]
Duplicate of issue #1972.
