### ISSUE TITLE
WebDriver close() method not working properly

### ISSUE THREAD

**Issue by antodobrev** [mozilla/geckodriver#2016]
## System

* Version: 
* Platform: 
* Firefox: 
* Selenium: 

## Testcase

driver.close() method causes an Exception
org.openqa.selenium.NoSuchWindowException: Current window does not have a content browser

## Stacktrace

build	11-May-2022 14:38:33	Build info: version: '3.8.1', revision: '6e95a6684b', time: '2017-12-01T18:33:54.468Z'
build	11-May-2022 14:38:33	System info: host: 'regpay-sofia.synchr.net', ip: '192.168.20.117', os.name: 'Linux', os.arch: 'amd64', os.version: '3.10.0-1160.6.1.el7.x86_64', java.version: '1.8.0_272'
build	11-May-2022 14:38:33	Driver info: org.openqa.selenium.firefox.FirefoxDriver
build	11-May-2022 14:38:33	Capabilities {acceptInsecureCerts: true, browserName: firefox, browserVersion: 57.0, javascriptEnabled: true, moz:accessibilityChecks: false, moz:geckodriverVersion: 0.31.0, moz:headless: false, moz:processID: 32220, moz:profile: /tmp/rust_mozprofile1Ax3Iu, moz:webdriverClick: false, pageLoadStrategy: normal, platform: LINUX, platformName: LINUX, platformVersion: 3.10.0-1160.6.1.el7.x86_64, rotatable: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}}
build	11-May-2022 14:38:33	Session ID: b1cf844f-498e-48cb-9f8c-b7025e6b3397
build	11-May-2022 14:38:33		at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
build	11-May-2022 14:38:33		at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
build	11-May-2022 14:38:33		at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
build	11-May-2022 14:38:33		at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
build	11-May-2022 14:38:33		at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:187)
build	11-May-2022 14:38:33		at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:122)
build	11-May-2022 14:38:33		at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:49)
build	11-May-2022 14:38:33		at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:164)
build	11-May-2022 14:38:33		at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
build	11-May-2022 14:38:33		at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:601)
build	11-May-2022 14:38:33		at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:658)
build	11-May-2022 14:38:33		at org.openqa.selenium.remote.RemoteWebDriver.getWindowHandle(RemoteWebDriver.java:518)
build	11-May-2022 14:38:33		at org.openqa.selenium.remote.RemoteWebDriver$RemoteTargetLocator.window(RemoteWebDriver.java:962)

**Comment by whimboo** [comment]
Could you please attach a [trace-level log] from geckodriver? Read more about reporting actionable bugs in our [contribution guidelines].

[trace-level log]: https://firefox-source-docs.mozilla.org/testing/geckodriver/TraceLogs.html
[contribution guidelines]: https://firefox-source-docs.mozilla.org/testing/geckodriver/Bugs.html

**Comment by whimboo** [comment]
Also please upgrade Firefox. Version 69 isn't supported for a very long time and the recent release is Firefox 100.

**Comment by antodobrev** [comment]
> Could you please attach a [trace-level log](https://firefox-source-docs.mozilla.org/testing/geckodriver/TraceLogs.html) from geckodriver? Read more about reporting actionable bugs in our [contribution guidelines](https://firefox-source-docs.mozilla.org/testing/geckodriver/Bugs.html).

Here are the Trace level logs:

1652359058376	webdriver::server	DEBUG	-> DELETE /session/f5f2e01d-79b2-4b57-9ca0-b8bed0d25e8d/window 
1652359058394	webdriver::server	DEBUG	<- 200 OK {"value":["6442450978"]}
1652359066221	webdriver::server	DEBUG	-> GET /session/f5f2e01d-79b2-4b57-9ca0-b8bed0d25e8d/window/handles 
1652359066223	webdriver::server	DEBUG	<- 200 OK {"value":["6442450978"]}
1652359066240	webdriver::server	DEBUG	-> POST /session/f5f2e01d-79b2-4b57-9ca0-b8bed0d25e8d/window {
  "handle": "6442450978"
}
1652359066242	webdriver::server	DEBUG	<- 404 Not Found {"value":{"error":"no such window","message":"Unable to locate window: undefined","stacktrace":"WebDriverError@chrome://marionette/content/error.js:175:5\nNoSuchWindowError@chrome://marionette/content/error.js:409:5\nGeckoDriver.prototype.switchToWindow@chrome://marionette/content/driver.js:1577:11\ndespatch@chrome://marionette/content/server.js:305:40\nexecute@chrome://marionette/content/server.js:275:16\nonPacket/<@chrome://marionette/content/server.js:248:20\nonPacket@chrome://marionette/content/server.js:249:9\n_onJSONObjectReady/<@chrome://marionette/content/transport.js:503:20\n"}}
1652359066271	webdriver::server	DEBUG	-> GET /session/f5f2e01d-79b2-4b57-9ca0-b8bed0d25e8d/window 
1652359066273	webdriver::server	DEBUG	<- 404 Not Found {"value":{"error":"no such window","message":"Browsing context has been discarded","stacktrace":"WebDriverError@chrome://marionette/content/error.js:175:5\nNoSuchWindowError@chrome://marionette/content/error.js:409:5\nassert.that/<@chrome://marionette/content/assert.js:428:13\nassert.open@chrome://marionette/content/assert.js:183:72\nGeckoDriver.prototype.getWindowHandle@chrome://marionette/content/driver.js:1391:10\ndespatch@chrome://marionette/content/server.js:305:40\nexecute@chrome://marionette/content/server.js:275:16\nonPacket/<@chrome://marionette/content/server.js:248:20\nonPacket@chrome://marionette/content/server.js:249:9\n_onJSONObjectReady/<@chrome://marionette/content/transport.js:503:20\n"}}
org.openqa.selenium.NoSuchWindowException: Browsing context has been discarded
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'PC-ADOBREV', ip: '10.5.0.43', os.name: 'Windows 10', os.arch: 'x86', os.version: '10.0', java.version: '1.8.0_211'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities {acceptInsecureCerts: true, browserName: firefox, browserVersion: 69.0, javascriptEnabled: true, moz:accessibilityChecks: false, moz:buildID: 20190827005903, moz:geckodriverVersion: 0.31.0, moz:headless: false, moz:processID: 3248, moz:profile: C:\Users\Anton\AppData\Loca..., moz:shutdownTimeout: 60000, moz:useNonSpecCompliantPointerOrigin: false, moz:webdriverClick: true, pageLoadStrategy: normal, platform: WINDOWS, platformName: WINDOWS, platformVersion: 10.0, rotatable: false, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify}
Session ID: f5f2e01d-79b2-4b57-9ca0-b8bed0d25e8d
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:187)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:122)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:49)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:609)
	at org.openqa.selenium.remote.RemoteWebDriver.getWindowHandle(RemoteWebDriver.java:472)
	at org.openqa.selenium.remote.RemoteWebDriver$RemoteTargetLocator.window(RemoteWebDriver.java:907)

**Comment by whimboo** [comment]
@antodobrev I assume the trace log is still from Firefox 69? As mentioned this version isn't supported for quite some time and we won't make any changes. So please upgrade to the latest Firefox 100 release, and if still present create a new trace log as best some a couple more lines around the actual issue. Thanks.
