### ISSUE TITLE
I can't run this on Windows 10

### ISSUE THREAD

**Issue by tellts** [mozilla/geckodriver#2035]
Geckodriver 0.31.0
I downloaded the latest version of Firefox from mozilla.org today and installed it.
`from selenium import webdriver
import time

driver = webdriver.Edge(executable_path="C:\\webdriver\\geckodriver.exe")

time.sleep(5)
driver.quit()`
I ran this code in Visual studio code.

PS C:\parsing\bs\DynamicBS> & C:/Python310/python.exe c:/parsing/bs/DynamicBS/dbs1_3.py
c:\parsing\bs\DynamicBS\dbs1_3.py:4: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver = webdriver.Edge(executable_path="C:\\webdriver\\geckodriver.exe")
Traceback (most recent call last):
  File "c:\parsing\bs\DynamicBS\dbs1_3.py", line 4, in <module>
    driver = webdriver.Edge(executable_path="C:\\webdriver\\geckodriver.exe")
  File "C:\Python310\lib\site-packages\selenium\webdriver\edge\webdriver.py", line 61, in __init__
    super().__init__(DesiredCapabilities.EDGE['browserName'], "ms",
  File "C:\Python310\lib\site-packages\selenium\webdriver\chromium\webdriver.py", line 92, in __init__
    super().__init__(
  File "C:\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 276, in __init__
    self.start_session(capabilities, browser_profile)
  File "C:\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 369, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "C:\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 434, in execute
    self.error_handler.check_response(response)
  File "C:\Python310\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 243, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: Unable to find a matching set of capabilities

PS C:\parsing\bs\DynamicBS>

**Comment by tellts** [comment]
Firefox 103.0.2. I ask you to write a version of the browser with which the webdriver starts up and works fine.
