### ISSUE TITLE
Using switchTo().window(handle) gives `InvalidArgumentError: Missing 'handle' parameter`

### ISSUE THREAD

**Issue by Standard8** [mozilla/geckodriver#204]
I'm running selenium+geckodriver in javascript mode using Firefox 48 in e10s mode. Doing the following fails:

```javascript
driver.getWindowHandle()
  .then(currentHandle => driver.switchTo().window(currentHandle))
```
gives

```console
     InvalidArgumentError: Missing 'handle' parameter
      at WebDriverError (node_modules/selenium-webdriver/lib/error.js:27:10)
      at InvalidArgumentError (node_modules/selenium-webdriver/lib/error.js:64:10)
      at Object.throwDecodedError (node_modules/selenium-webdriver/lib/error.js:477:11)
      at parseHttpResponse (node_modules/selenium-webdriver/lib/http.js:386:15)
      at node_modules/selenium-webdriver/lib/http.js:328:11
  From: Task: WebDriver.switchTo().window(undefined)
      at Driver.schedule (node_modules/selenium-webdriver/lib/webdriver.js:414:17)
      at TargetLocator.window (node_modules/selenium-webdriver/lib/webdriver.js:1657:25)
      at test/functional/button_test.js:109:34
      at ManagedPromise.invokeCallback_ (node_modules/selenium-webdriver/lib/promise.js:1315:14)
      at TaskQueue.execute_ (node_modules/selenium-webdriver/lib/promise.js:2736:14)
      at TaskQueue.executeNext_ (node_modules/selenium-webdriver/lib/promise.js:2719:21)
      at node_modules/selenium-webdriver/lib/promise.js:2595:27
      at node_modules/selenium-webdriver/lib/promise.js:639:7
```

I'll attach more detailed geckodriver logs when I get them.

**Comment by Standard8** [comment]
Here's the geckodriver trace output:

```console
1472589097452	Marionette	TRACE	conn0 -> [0,4,"setContext",{"value":"chrome"}]
1472589097453	Marionette	TRACE	conn0 <- [1,4,null,{}]
1472589097465	Marionette	TRACE	conn0 -> [0,5,"findElements",{"using":"css selector","value":"*[id=\"action-button--example-addon-repo-mozilla-link\"]"}]
1472589097466	Marionette	TRACE	conn0 <- [1,5,null,[{"element-6066-11e4-a52e-4f735466cecf":"0c5c4564-a3ab-4a4a-b13a-5cfc4b6df47a","ELEMENT":"0c5c4564-a3ab-4a4a-b13a-5cfc4b6df47a"}]]
1472589097470	Marionette	TRACE	conn0 -> [0,6,"getElementAttribute",{"id":"0c5c4564-a3ab-4a4a-b13a-5cfc4b6df47a","name":"tooltiptext"}]
1472589097473	Marionette	TRACE	conn0 <- [1,6,null,{"value":"Visit Mozilla"}]
    ✓ should have a toolbar button (600ms)
1472589097485	Marionette	TRACE	conn0 -> [0,7,"setContext",{"value":"content"}]
1472589097485	Marionette	TRACE	conn0 <- [1,7,null,{}]
1472589097488	Marionette	TRACE	conn0 -> [0,8,"getCurrentUrl",{}]
1472589097489	Marionette	INFO	sendAsync d2114a2c-85b0-2142-98e4-97b95bd7be55
1472589097490	Marionette	TRACE	conn0 <- [1,8,null,{"value":"about:blank"}]
about:blank
    ✓ should get the current url
1472589097493	Marionette	TRACE	conn0 -> [0,9,"setContext",{"value":"content"}]
1472589097493	Marionette	TRACE	conn0 <- [1,9,null,{}]
1472589097496	Marionette	TRACE	conn0 -> [0,10,"get",{"url":"https://bugzilla.mozilla.org/"}]
1472589097496	Marionette	INFO	sendAsync d2114a2c-85b0-2142-98e4-97b95bd7be55
1472589097785	Marionette	INFO	sendAsync d2114a2c-85b0-2142-98e4-97b95bd7be55
1472589101049	Marionette	TRACE	conn0 <- [1,10,null,{}]
1472589101053	Marionette	TRACE	conn0 -> [0,11,"getCurrentUrl",{}]
1472589101054	Marionette	INFO	sendAsync d2114a2c-85b0-2142-98e4-97b95bd7be55
1472589101056	Marionette	TRACE	conn0 <- [1,11,null,{"value":"https://bugzilla.mozilla.org/"}]
    ✓ should navigate and get the current url (3566ms)
1472589101060	Marionette	TRACE	conn0 -> [0,12,"getWindowHandles",{}]
1472589101060	Marionette	TRACE	conn0 <- [1,12,null,["2147483649"]]
1472589101065	Marionette	TRACE	conn0 -> [0,13,"setContext",{"value":"chrome"}]
1472589101066	Marionette	TRACE	conn0 <- [1,13,null,{}]
1472589101068	Marionette	TRACE	conn0 -> [0,14,"findElements",{"using":"css selector","value":"*[id=\"action-button--example-addon-repo-mozilla-link\"]"}]
1472589101069	Marionette	TRACE	conn0 <- [1,14,null,[{"element-6066-11e4-a52e-4f735466cecf":"0c5c4564-a3ab-4a4a-b13a-5cfc4b6df47a","ELEMENT":"0c5c4564-a3ab-4a4a-b13a-5cfc4b6df47a"}]]
1472589101072	Marionette	TRACE	conn0 -> [0,15,"clickElement",{"id":"0c5c4564-a3ab-4a4a-b13a-5cfc4b6df47a"}]
1472589101077	Marionette	DEBUG	Element does not have an accessible object: id: action-button--example-addon-repo-mozilla-link, tagName: toolbarbutton, className: toolbarbutton-1 chromeclass-toolbar-additional badged-button
1472589101130	Marionette	TRACE	conn0 <- [1,15,null,{}]
1472589101155	Marionette	TRACE	conn0 -> [0,16,"getWindowHandles",{}]
1472589101156	Marionette	TRACE	conn0 <- [1,16,null,["2147483649","2147483654"]]
1472589101168	Marionette	TRACE	conn0 -> [0,17,"getWindowHandles",{}]
1472589101171	Marionette	TRACE	conn0 <- [1,17,null,["2147483649","2147483654"]]
1472589101174	Marionette	TRACE	conn0 -> [0,18,"getWindowHandle",{}]
1472589101174	Marionette	TRACE	conn0 <- [1,18,null,{"value":"2147483649"}]
2147483654
[ '2147483649', '2147483654' ]
1472589101181	Marionette	TRACE	conn0 -> [0,19,"setContext",{"value":"content"}]
1472589101181	Marionette	TRACE	conn0 <- [1,19,null,{}]
    1) should open a webpage when the button is clicked
```

**Comment by Standard8** [comment]
After some help from @andreastt, we isolated this to an issue in the selenium node.js driver. There's now a pull request on selenium to fix it: https://github.com/SeleniumHQ/selenium/pull/2718

**Comment by tonyaveniros** [comment]
I am getting this error for Firefox 51.0.1 (64-bit), but don't see a solution here as to how to work around it. Even after going to SeleniumHQ/selenium#2718, and copying the changes there i on my local copy of window-test.js resulted in:

```
InvalidArgumentError: Missing 'handle' parameter
    at WebDriverError (/Users/anthonybeck/Documents/COMPANY/AutomatedTestCases/node_testing/node_modules/selenium-webdriver/lib/error.js:27:5)
    at InvalidArgumentError (/Users/anthonybeck/Documents/COMPANY/AutomatedTestCases/node_testing/node_modules/selenium-webdriver/lib/error.js:64:5)
    at Object.throwDecodedError (/Users/anthonybeck/Documents/COMPANY/AutomatedTestCases/node_testing/node_modules/selenium-webdriver/lib/error.js:477:11)
    at parseHttpResponse (/Users/anthonybeck/Documents/COMPANY/AutomatedTestCases/node_testing/node_modules/selenium-webdriver/lib/http.js:386:15)
    at doSend.then.response (/Users/anthonybeck/Documents/COMPANY/AutomatedTestCases/node_testing/node_modules/selenium-webdriver/lib/http.js:328:11)
    at process._tickCallback (internal/process/next_tick.js:103:7)
From: Task: WebDriver.switchTo().window(2147483649)
    at Driver.schedule (/Users/anthonybeck/Documents/COMPANY/AutomatedTestCases/node_testing/node_modules/selenium-webdriver/lib/webdriver.js:414:17)
    at TargetLocator.window (/Users/anthonybeck/Documents/COMPANY/AutomatedTestCases/node_testing/node_modules/selenium-webdriver/lib/webdriver.js:1657:25)
    at /Users/anthonybeck/Documents/COMPANY/AutomatedTestCases/node_testing/BigIdeas_POM.js:1044:23
    at ManagedPromise.invokeCallback_ (/Users/anthonybeck/Documents/COMPANY/AutomatedTestCases/node_testing/node_modules/selenium-webdriver/lib/promise.js:1315:14)
    at TaskQueue.execute_ (/Users/anthonybeck/Documents/COMPANY/AutomatedTestCases/node_testing/node_modules/selenium-webdriver/lib/promise.js:2736:14)
    at TaskQueue.executeNext_ (/Users/anthonybeck/Documents/COMPANY/AutomatedTestCases/node_testing/node_modules/selenium-webdriver/lib/promise.js:2719:21)
    at asyncRun (/Users/anthonybeck/Documents/COMPANY/AutomatedTestCases/node_testing/node_modules/selenium-webdriver/lib/promise.js:2595:27)
    at /Users/anthonybeck/Documents/COMPANY/AutomatedTestCases/node_testing/node_modules/selenium-webdriver/lib/promise.js:639:7
    at process._tickCallback (internal/process/next_tick.js:103:7)
```

Any ideas about how I might work around this or when a fix might be available?

**Comment by thomas-lee** [comment]
It still happens on the `GECKODRIVER_VERSION=0.18.0` and `FIREFOX_VERSION=55.0.3`.

Any possible fix?

**Comment by whimboo** [comment]
@thomas-lee, first you are commenting on a closed issue and second without any trace level log, or testcase. There is nothing we can do for you at this stage. File a new issue with all the details provided, and we can see if that is a bug or not. Thanks.
