### ISSUE TITLE
Using switchTo().frame(handle) gives `NoSuchFrameError: frame id has unexpected type`

### ISSUE THREAD

**Issue by Standard8** [mozilla/geckodriver#205]
I'm running selenium+geckodriver in javascript mode using Firefox 48 in e10s mode. Doing the following fails:

```javascript
driver.getAllWindowHandles()
  .then(handles => driver.switchTo().frame(handles[0]))
```
gives

```console
     NoSuchFrameError: frame id has unexpected type
      at WebDriverError (node_modules/selenium-webdriver/lib/error.js:27:10)
      at NoSuchFrameError (node_modules/selenium-webdriver/lib/error.js:180:10)
      at Object.throwDecodedError (node_modules/selenium-webdriver/lib/error.js:477:11)
      at parseHttpResponse (node_modules/selenium-webdriver/lib/http.js:386:15)
      at node_modules/selenium-webdriver/lib/http.js:328:11
  From: Task: WebDriver.switchTo().frame(7)
      at Driver.schedule (node_modules/selenium-webdriver/lib/webdriver.js:414:17)
      at TargetLocator.frame (node_modules/selenium-webdriver/lib/webdriver.js:1637:25)
      at test/functional/button_test.js:109:34
      at ManagedPromise.invokeCallback_ (node_modules/selenium-webdriver/lib/promise.js:1315:14)
      at TaskQueue.execute_ (node_modules/selenium-webdriver/lib/promise.js:2736:14)
      at TaskQueue.executeNext_ (node_modules/selenium-webdriver/lib/promise.js:2719:21)
      at node_modules/selenium-webdriver/lib/promise.js:2595:27
      at node_modules/selenium-webdriver/lib/promise.js:639:7
```

I'll attach more detailed geckodriver logs when I get them.

**Comment by Standard8** [comment]
Here's the trace geckodriver output:

```console
1472588893895	Marionette	TRACE	conn0 -> [0,4,"setContext",{"value":"chrome"}]
1472588893896	Marionette	TRACE	conn0 <- [1,4,null,{}]
1472588893902	Marionette	TRACE	conn0 -> [0,5,"findElements",{"using":"css selector","value":"*[id=\"action-button--example-addon-repo-mozilla-link\"]"}]
1472588893904	Marionette	TRACE	conn0 <- [1,5,null,[{"element-6066-11e4-a52e-4f735466cecf":"2c3539c7-d67f-3648-a1ad-1ddcdb551726","ELEMENT":"2c3539c7-d67f-3648-a1ad-1ddcdb551726"}]]
1472588893909	Marionette	TRACE	conn0 -> [0,6,"getElementAttribute",{"id":"2c3539c7-d67f-3648-a1ad-1ddcdb551726","name":"tooltiptext"}]
1472588893912	Marionette	TRACE	conn0 <- [1,6,null,{"value":"Visit Mozilla"}]
    ✓ should have a toolbar button (590ms)
1472588893924	Marionette	TRACE	conn0 -> [0,7,"setContext",{"value":"content"}]
1472588893925	Marionette	TRACE	conn0 <- [1,7,null,{}]
1472588893929	Marionette	TRACE	conn0 -> [0,8,"getCurrentUrl",{}]
1472588893931	Marionette	INFO	sendAsync 4217d624-9a64-af4c-b6bb-f65f545a87af
1472588893932	Marionette	TRACE	conn0 <- [1,8,null,{"value":"about:blank"}]
about:blank
    ✓ should get the current url
1472588893935	Marionette	TRACE	conn0 -> [0,9,"setContext",{"value":"content"}]
1472588893936	Marionette	TRACE	conn0 <- [1,9,null,{}]
1472588893938	Marionette	TRACE	conn0 -> [0,10,"get",{"url":"https://bugzilla.mozilla.org/"}]
1472588893938	Marionette	INFO	sendAsync 4217d624-9a64-af4c-b6bb-f65f545a87af
1472588896783	Marionette	TRACE	conn0 <- [1,10,null,{}]
1472588896786	Marionette	TRACE	conn0 -> [0,11,"getCurrentUrl",{}]
1472588896787	Marionette	INFO	sendAsync 4217d624-9a64-af4c-b6bb-f65f545a87af
1472588896788	Marionette	TRACE	conn0 <- [1,11,null,{"value":"https://bugzilla.mozilla.org/"}]
    ✓ should navigate and get the current url (2857ms)
1472588896792	Marionette	TRACE	conn0 -> [0,12,"getWindowHandles",{}]
1472588896792	Marionette	TRACE	conn0 <- [1,12,null,["7"]]
1472588896796	Marionette	TRACE	conn0 -> [0,13,"setContext",{"value":"chrome"}]
1472588896796	Marionette	TRACE	conn0 <- [1,13,null,{}]
1472588896799	Marionette	TRACE	conn0 -> [0,14,"findElements",{"using":"css selector","value":"*[id=\"action-button--example-addon-repo-mozilla-link\"]"}]
1472588896800	Marionette	TRACE	conn0 <- [1,14,null,[{"element-6066-11e4-a52e-4f735466cecf":"2c3539c7-d67f-3648-a1ad-1ddcdb551726","ELEMENT":"2c3539c7-d67f-3648-a1ad-1ddcdb551726"}]]
1472588896803	Marionette	TRACE	conn0 -> [0,15,"clickElement",{"id":"2c3539c7-d67f-3648-a1ad-1ddcdb551726"}]
1472588896804	Marionette	DEBUG	Element does not have an accessible object: id: action-button--example-addon-repo-mozilla-link, tagName: toolbarbutton, className: toolbarbutton-1 chromeclass-toolbar-additional badged-button
1472588896857	Marionette	DEBUG	loaded listener.js
1472588896867	Marionette	TRACE	conn0 <- [1,15,null,{}]
1472588896903	Marionette	TRACE	conn0 -> [0,16,"getWindowHandles",{}]
1472588896904	Marionette	TRACE	conn0 <- [1,16,null,["7","18"]]
1472588896912	Marionette	TRACE	conn0 -> [0,17,"getWindowHandles",{}]
1472588896913	Marionette	TRACE	conn0 <- [1,17,null,["7","18"]]
1472588896916	Marionette	TRACE	conn0 -> [0,18,"getWindowHandle",{}]
1472588896916	Marionette	TRACE	conn0 <- [1,18,null,{"value":"7"}]
18
[ '7', '18' ]
1472588896921	Marionette	TRACE	conn0 -> [0,19,"setContext",{"value":"content"}]
1472588896921	Marionette	TRACE	conn0 <- [1,19,null,{}]
    1) should open a webpage when the button is clicked
```
(and then the failure message).

**Comment by twalpole** [comment]
You're calling `switchTo().frame`  but are passing window handles - you probably want `switchTo().window`

**Comment by Standard8** [comment]
> You're calling switchTo().frame but are passing window handles - you probably want switchTo().window

#204 is what happens when I try the `.window` variant. @andreastt asked me to file both of these so I did :-)

**Comment by Standard8** [comment]
Now that #204 is resolved, I think it is right that we don't want the .frame here. Therefore lets close this.
