### ISSUE TITLE
Firefox browser launch failing with latest geckodriver 0.32.0

### ISSUE THREAD

**Issue by kj101010** [mozilla/geckodriver#2065]
## System

* Version: 0.32.0
* Platform: Windows 10
* Firefox: 105.0.2
* Selenium: selenium webdriver- 4.6.0

## Testcase

Firefox browser launching failing with latest geckodriver 0.32.0. getting below issue:
Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure.

## Stacktrace

Exception in thread "main" org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure. 
Host info: host: 'DESKTOP-3TURH1E', ip: '10.8.160.79'
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:559)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:242)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:157)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:111)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:99)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:95)
	at new_sel_ver.sample_script.main(sample_script.java:13)
Caused by: org.openqa.selenium.WebDriverException: Driver server process died prematurely.
Build info: version: '4.6.0', revision: '79f1c02ae20'
System info: os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '17.0.1'
Driver info: driver.version: FirefoxDriver
	at org.openqa.selenium.remote.service.DriverService.start(DriverService.java:239)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:98)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:541)
	... 6 more

**Comment by whimboo** [comment]
Could you please attach a [trace-level log] from geckodriver? Read more about reporting actionable bugs in our [contribution guidelines].

[trace-level log]: https://firefox-source-docs.mozilla.org/testing/geckodriver/TraceLogs.html
[contribution guidelines]: https://firefox-source-docs.mozilla.org/testing/geckodriver/Bugs.html

**Comment by kj101010** [comment]
Tried to generate trace logs using below code :
FirefoxOptions option = new FirefoxOptions();
option.setLogLevel(FirefoxDriverLogLevel.TRACE);
WebDriver driver = new FirefoxDriver(option);

log:
Exception in thread "main" org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure. 
Host info: host: 'DESKTOP-3TURH1E', ip: '10.8.160.79'
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:559)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:242)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:157)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:111)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:99)
	at new_sel_ver.sample_script.main(sample_script.java:18)
Caused by: org.openqa.selenium.WebDriverException: Driver server process died prematurely.
Build info: version: '4.6.0', revision: '79f1c02ae20'
System info: os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '17.0.1'
Driver info: driver.version: FirefoxDriver
	at org.openqa.selenium.remote.service.DriverService.start(DriverService.java:239)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:98)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:541)
	... 5 more

**Comment by whimboo** [comment]
These are not trace logs. Please check a possible `geckodriver.log` file that Selenium should have been created.

**Comment by kj101010** [comment]
Not getting any logs with 0.32.0 version geckodriver

**Comment by kj101010** [comment]
Following are the logs with 0.31.0 version geckodriver and automation working fine with old geckodriver

1668697006174	geckodriver	INFO	Listening on 127.0.0.1:48600
1668697007153	geckodriver::capabilities	DEBUG	Trying to read firefox version from ini files
1668697007153	geckodriver::capabilities	DEBUG	Found version 108.0
1668697007157	mozrunner::runner	INFO	Running command: "C:\\Program Files\\Mozilla Firefox\\firefox.exe" "--marionette" "--remote-debugging-port" "10314" "--remote-allow-hosts" "localhost" "--remote-allow-origins" "http://127.0.0.1:10314/,http://localhost:10314/,http://[::1]:10314/" "-no-remote" "-profile" "C:\\Users\\NSMeter\\AppData\\Local\\Temp\\rust_mozprofilegWQwpr"
1668697007165	geckodriver::marionette	DEBUG	Waiting 60s to connect to browser on 127.0.0.1
1668697007165	geckodriver::browser	TRACE	Failed to open C:\Users\NSMeter\AppData\Local\Temp\rust_mozprofilegWQwpr\MarionetteActivePort
1668697007165	geckodriver::marionette	TRACE	Retrying in 100ms
1668697007290	geckodriver::browser	TRACE	Failed to open C:\Users\NSMeter\AppData\Local\Temp\rust_mozprofilegWQwpr\MarionetteActivePort
1668697007290	geckodriver::marionette	TRACE	Retrying in 100ms
1668697007422	geckodriver::browser	TRACE	Failed to open C:\Users\NSMeter\AppData\Local\Temp\rust_mozprofilegWQwpr\MarionetteActivePort
1668697007422	geckodriver::marionette	TRACE	Retrying in 100ms
1668697007523	geckodriver::browser	TRACE	Failed to open C:\Users\NSMeter\AppData\Local\Temp\rust_mozprofilegWQwpr\MarionetteActivePort
1668697007524	geckodriver::marionette	TRACE	Retrying in 100ms
1668697007635	geckodriver::browser	TRACE	Failed to open C:\Users\NSMeter\AppData\Local\Temp\rust_mozprofilegWQwpr\MarionetteActivePort
1668697007635	geckodriver::marionette	TRACE	Retrying in 100ms
1668697007740	geckodriver::browser	TRACE	Failed to open C:\Users\NSMeter\AppData\Local\Temp\rust_mozprofilegWQwpr\MarionetteActivePort
1668697007741	geckodriver::marionette	TRACE	Retrying in 100ms
1668697007851	geckodriver::browser	TRACE	Failed to open C:\Users\NSMeter\AppData\Local\Temp\rust_mozprofilegWQwpr\MarionetteActivePort
1668697007851	geckodriver::marionette	TRACE	Retrying in 100ms
1668697007966	geckodriver::browser	TRACE	Failed to open C:\Users\NSMeter\AppData\Local\Temp\rust_mozprofilegWQwpr\MarionetteActivePort
1668697007967	geckodriver::marionette	TRACE	Retrying in 100ms
1668697008088	geckodriver::browser	TRACE	Failed to open C:\Users\NSMeter\AppData\Local\Temp\rust_mozprofilegWQwpr\MarionetteActivePort
1668697008088	geckodriver::marionette	TRACE	Retrying in 100ms
1668697008224	geckodriver::browser	TRACE	Failed to open C:\Users\NSMeter\AppData\Local\Temp\rust_mozprofilegWQwpr\MarionetteActivePort
1668697008224	geckodriver::marionette	TRACE	Retrying in 100ms
1668697008324	RemoteAgent	DEBUG	WebDriver BiDi enabled
1668697008324	RemoteAgent	DEBUG	CDP enabled
1668697008325	Marionette	INFO	Marionette enabled
1668697008326	RemoteAgent	DEBUG	Setting recommended pref apz.content_response_timeout to 60000
1668697008326	RemoteAgent	DEBUG	Setting recommended pref browser.contentblocking.introCount to 99
1668697008326	RemoteAgent	DEBUG	Setting recommended pref browser.download.panel.shown to true
1668697008326	RemoteAgent	DEBUG	Setting recommended pref browser.newtabpage.enabled to false
1668697008326	RemoteAgent	DEBUG	Setting recommended pref browser.pagethumbnails.capturing_disabled to true
1668697008326	RemoteAgent	DEBUG	Setting recommended pref browser.search.update to false
1668697008326	RemoteAgent	DEBUG	Setting recommended pref browser.startup.couldRestoreSession.count to -1
1668697008327	RemoteAgent	DEBUG	Setting recommended pref browser.tabs.closeWindowWithLastTab to false
1668697008327	RemoteAgent	DEBUG	Setting recommended pref browser.tabs.disableBackgroundZombification to false
1668697008327	RemoteAgent	DEBUG	Setting recommended pref browser.tabs.unloadOnLowMemory to false
1668697008327	RemoteAgent	DEBUG	Setting recommended pref browser.tabs.warnOnClose to false
1668697008327	RemoteAgent	DEBUG	Setting recommended pref browser.tabs.warnOnCloseOtherTabs to false
1668697008327	RemoteAgent	DEBUG	Setting recommended pref browser.tabs.warnOnOpen to false
1668697008327	RemoteAgent	DEBUG	Setting recommended pref browser.toolbars.bookmarks.visibility to never
1668697008327	RemoteAgent	DEBUG	Setting recommended pref browser.usedOnWindows10.introURL to 
1668697008327	RemoteAgent	DEBUG	Setting recommended pref browser.urlbar.merino.endpointURL to 
1668697008338	geckodriver::browser	TRACE	Failed to open C:\Users\NSMeter\AppData\Local\Temp\rust_mozprofilegWQwpr\MarionetteActivePort
1668697008338	geckodriver::marionette	TRACE	Retrying in 100ms
1668697008339	RemoteAgent	DEBUG	Setting recommended pref browser.urlbar.suggest.searches to false
1668697008339	RemoteAgent	DEBUG	Setting recommended pref datareporting.policy.dataSubmissionPolicyAccepted to false
1668697008339	RemoteAgent	DEBUG	Setting recommended pref dom.disable_open_during_load to false
1668697008340	RemoteAgent	DEBUG	Setting recommended pref dom.file.createInChild to true
1668697008340	RemoteAgent	DEBUG	Setting recommended pref dom.max_chrome_script_run_time to 0
1668697008340	RemoteAgent	DEBUG	Setting recommended pref dom.max_script_run_time to 0
1668697008340	RemoteAgent	DEBUG	Setting recommended pref dom.push.connection.enabled to false
1668697008341	RemoteAgent	DEBUG	Setting recommended pref dom.successive_dialog_time_limit to 0
1668697008341	RemoteAgent	DEBUG	Setting recommended pref extensions.getAddons.cache.enabled to false
1668697008343	RemoteAgent	DEBUG	Setting recommended pref extensions.getAddons.discovery.api_url to data:, 
1668697008344	RemoteAgent	DEBUG	Setting recommended pref network.http.phishy-userpass-length to 255
1668697008344	RemoteAgent	DEBUG	Setting recommended pref network.http.prompt-temp-redirect to false
1668697008344	RemoteAgent	DEBUG	Setting recommended pref privacy.trackingprotection.enabled to false
1668697008344	RemoteAgent	DEBUG	Setting recommended pref security.fileuri.strict_origin_policy to false
1668697008345	RemoteAgent	DEBUG	Setting recommended pref security.notification_enable_delay to 0
1668697008345	RemoteAgent	DEBUG	Setting recommended pref signon.autofillForms to false
1668697008346	RemoteAgent	DEBUG	Setting recommended pref signon.rememberSignons to false
1668697008346	RemoteAgent	DEBUG	Setting recommended pref browser.topsites.contile.enabled to false
1668697008346	RemoteAgent	DEBUG	Setting recommended pref dom.disable_beforeunload to true
1668697008352	Marionette	TRACE	Received observer notification final-ui-startup
1668697008354	Marionette	INFO	Listening on port 58060
1668697008354	Marionette	DEBUG	Marionette is listening
1668697008354	RemoteAgent	TRACE	Received observer notification final-ui-startup
1668697008477	RemoteAgent	TRACE	Available local IP addresses: 127.0.0.1, [::1]
WebDriver BiDi listening on ws://127.0.0.1:10314
1668697008486	RemoteAgent	DEBUG	Setting recommended pref browser.contentblocking.features.standard to -tp,tpPrivate,cookieBehavior0,-cm,-fp
1668697008487	RemoteAgent	DEBUG	Setting recommended pref network.cookie.cookieBehavior to 0
1668697008487	CDP	DEBUG	Waiting for initial application window
Read port: 58060
1668697008809	Marionette	DEBUG	Accepted connection 0 from 127.0.0.1:58064
1668697008816	geckodriver::marionette	DEBUG	Connection to Marionette established on 127.0.0.1:58060.
1668697008868	Marionette	DEBUG	0 -> [0,1,"WebDriver:NewSession",{"acceptInsecureCerts":true,"browserName":"firefox"}]
1668697008871	RemoteAgent	WARN	TLS certificate errors will be ignored for this session
1668697008872	Marionette	DEBUG	Waiting for initial application window
console.warn: SearchSettings: "get: No settings file exists, new profile?" (new NotFoundError("Could not open the file at C:\\Users\\NSMeter\\AppData\\Local\\Temp\\rust_mozprofilegWQwpr\\search.json.mozlz4", (void 0)))
1668697010256	Marionette	TRACE	Received observer notification browser-idle-startup-tasks-finished
1668697010256	RemoteAgent	TRACE	Received observer notification browser-idle-startup-tasks-finished
1668697010263	RemoteAgent	TRACE	[9] ProgressListener Start: expectNavigation=false resolveWhenStarted=false unloadTimeout=200 waitForExplicitStart=false
1668697010263	RemoteAgent	TRACE	[9] ProgressListener Setting unload timer (200ms)
DevTools listening on ws://127.0.0.1:10314/devtools/browser/bedf2ebf-251a-4ca6-940f-d5387f5b0ff2
1668697010378	RemoteAgent	TRACE	[9] ProgressListener Check loading state: isStart=1 isStop=0
1668697010378	RemoteAgent	TRACE	[9] ProgressListener state=start: about:blank
1668697010378	RemoteAgent	TRACE	[9] ProgressListener Cleared the unload timer
1668697010505	RemoteAgent	TRACE	[9] ProgressListener Check loading state: isStart=0 isStop=16
1668697010505	RemoteAgent	TRACE	[9] ProgressListener state=stop: about:blank
1668697010505	RemoteAgent	TRACE	[9] ProgressListener Stop: has error=false
1668697010511	Marionette	DEBUG	0 <- [1,1,null,{"sessionId":"15ae77d0-f4fc-4415-8ce3-f8f2d2e40fe5","capabilities":{"browserName":"firefox","browserVersion":"108.0","platformName":"windows","acceptInsecureCerts":true,"pageLoadStrategy":"normal","setWindowRect":true,"timeouts":{"implicit":0,"pageLoad":300000,"script":30000},"strictFileInteractability":false,"unhandledPromptBehavior":"dismiss and notify","moz:accessibilityChecks":false,"moz:buildID":"20221115200658","moz:debuggerAddress":"127.0.0.1:10314","moz:headless":false,"moz:platformVersion":"10.0","moz:processID":22992,"moz:profile":"C:\\Users\\NSMeter\\AppData\\Local\\Temp\\rust_mozprofilegWQwpr","moz:shutdownTimeout":60000,"moz:useNonSpecCompliantPointerOrigin":false,"moz:webdriverClick":true,"moz:windowless":false,"proxy":{}}}]
1668697010514	webdriver::server	DEBUG	<- 200 OK {"value":{"sessionId":"15ae77d0-f4fc-4415-8ce3-f8f2d2e40fe5","capabilities":{"acceptInsecureCerts":true,"browserName":"firefox","browserVersion":"108.0","moz:accessibilityChecks":false,"moz:buildID":"20221115200658","moz:debuggerAddress":"127.0.0.1:10314","moz:geckodriverVersion":"0.31.0","moz:headless":false,"moz:platformVersion":"10.0","moz:processID":22992,"moz:profile":"C:\\Users\\NSMeter\\AppData\\Local\\Temp\\rust_mozprofilegWQwpr","moz:shutdownTimeout":60000,"moz:useNonSpecCompliantPointerOrigin":false,"moz:webdriverClick":true,"moz:windowless":false,"pageLoadStrategy":"normal","platformName":"windows","proxy":{},"setWindowRect":true,"strictFileInteractability":false,"timeouts":{"implicit":0,"pageLoad":300000,"script":30000},"unhandledPromptBehavior":"dismiss and notify"}}}
1668697010890	webdriver::server	DEBUG	-> POST /session/15ae77d0-f4fc-4415-8ce3-f8f2d2e40fe5/url {
  "url": "https:\u002f\u002fartoftesting.com"
}
1668697010891	Marionette	DEBUG	0 -> [0,2,"WebDriver:Navigate",{"url":"https://artoftesting.com"}]
1668697010899	Marionette	TRACE	[9] Received event beforeunload for about:blank
1668697012207	Marionette	TRACE	[9] Received event pagehide for about:blank
1668697013435	Marionette	TRACE	[9] Received event DOMContentLoaded for https://artoftesting.com/

**Comment by kj101010** [comment]
Yes combination of Firefox 108 and geckodriver 0.32.0 also failing and not getting any logs after execution. Only getting "Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure" exception.

**Comment by whimboo** [comment]
Could your issue be related to https://github.com/SeleniumHQ/selenium/issues/11231?

**Comment by nen4d** [comment]
I'm getting the same error, I'm using 4.6.0 Selenium, 107.0 Firefox version and 0.32.0 geckodriver

**Comment by kj101010** [comment]
> 

It's not working with older version of selenium manager too

**Comment by whimboo** [comment]
I tried with the Python bindings and it works all well for me. So it might be some issue with the Java bindings? I would suggest to file an issue against Selenium.

**Comment by kj101010** [comment]
I am getting issue with older versions of webdriver manager with latest 0.32.0 ver geckodriver. So is it a selenium issue?

**Comment by whimboo** [comment]
Well, could you try running your Selenium test without using webdriver manager? That would be the first step to figure out if it's related to this new tool.

**Comment by kj101010** [comment]
Tried without using webdriver manager also same issue I am getting. Also I am using virtual machine to execute these scripts so is it causing due to vm?

**Comment by whimboo** [comment]
Do you have a chance to test it manually outside of Selenium? The following page has some examples by using `curl` as client:

https://firefox-source-docs.mozilla.org/testing/geckodriver/Usage.html#standalone

**Comment by asantossa** [comment]
I'm also getting the same error. I'm using selenium 4.1.2 , 107.0 Firefox version and 0.32.0 geckodriver. Setting up the 0.31.0 geckodriver, it works

**Comment by whimboo** [comment]
@asantossa which platform are you on? Could you also check my last comment from above and test if you can create a session with geckodriver manually?

**Comment by sanj29** [comment]
@whimboo I am also getting the same issue with Selenium 4.6 and FF 108, below is the stack trace:
1672828149782	geckodriver	INFO	Listening on 127.0.0.1:25073
2023-01-04 16:00:00.695 ERROR [main           ] (SpringApplication.java:865)        : Application run failed
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'adminGroupManagerPage': Unsatisfied dependency expressed through field 'driver'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'firefoxDriver' defined in class path resource [tv/cadent/automation/config/driver/WebDriverConfig.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.openqa.selenium.WebDriver]: Factory method 'firefoxDriver' threw exception; nested exception is org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure. 
Host info: host: 'ndi-mb-308', ip: 'fe80:0:0:0:84:6996:270c:e2ff%en0'
Build info: version: '4.6.0', revision: '79f1c02ae20'
System info: os.name: 'Mac OS X', os.arch: 'aarch64', os.version: '12.6', java.version: '19'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Command: [null, newSession {capabilities=[Capabilities {acceptInsecureCerts: true, browserName: firefox, moz:debuggerAddress: true, moz:firefoxOptions: {args: [], prefs: {browser.download.viewableInternally.enabledTypes: , browser.helperApps.neverAsk.saveToDisk: application/pdf;text/plain;..., pdfjs.disabled: true, security.mixed_content.block_active_content: false}}}], desiredCapabilities=Capabilities {acceptInsecureCerts: true, browserName: firefox, moz:debuggerAddress: true, moz:firefoxOptions: {args: [], prefs: {browser.download.viewableInternally.enabledTypes: , browser.helperApps.neverAsk.saveToDisk: application/pdf;text/plain;..., pdfjs.disabled: true, security.mixed_content.block_active_content: false}}}}]
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.resolveFieldValue(AutowiredAnnotationBeanPostProcessor.java:659)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:639)
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:119)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessProperties(AutowiredAnnotationBeanPostProcessor.java:399)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1431)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:619)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:953)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:918)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:775)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:448)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:339)
	at org.springframework.boot.test.context.SpringBootContextLoader.loadContext(SpringBootContextLoader.java:136)
	at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContextInternal(DefaultCacheAwareContextLoaderDelegate.java:99)
	at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContext(DefaultCacheAwareContextLoaderDelegate.java:124)
	at org.springframework.test.context.support.DefaultTestContext.getApplicationContext(DefaultTestContext.java:124)
	at org.springframework.test.context.support.DependencyInjectionTestExecutionListener.injectDependencies(DependencyInjectionTestExecutionListener.java:118)
	at org.springframework.test.context.support.DependencyInjectionTestExecutionListener.prepareTestInstance(DependencyInjectionTestExecutionListener.java:83)
	at org.springframework.test.context.TestContextManager.prepareTestInstance(TestContextManager.java:248)
	at org.springframework.test.context.testng.AbstractTestNGSpringContextTests.springTestContextPrepareTestInstance(AbstractTestNGSpringContextTests.java:149)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
	at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:62)
	at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:385)
	at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:321)
	at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:176)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:122)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.testng.TestRunner.privateRun(TestRunner.java:794)
	at org.testng.TestRunner.run(TestRunner.java:596)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
	at org.testng.SuiteRunner.run(SuiteRunner.java:276)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
	at org.testng.TestNG.runSuites(TestNG.java:1063)
	at org.testng.TestNG.run(TestNG.java:1031)
	at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
	at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'firefoxDriver' defined in class path resource [tv/cadent/automation/config/driver/WebDriverConfig.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.openqa.selenium.WebDriver]: Factory method 'firefoxDriver' threw exception; nested exception is org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure. 
Host info: host: 'ndi-mb-308', ip: 'fe80:0:0:0:84:6996:270c:e2ff%en0'
Build info: version: '4.6.0', revision: '79f1c02ae20'
System info: os.name: 'Mac OS X', os.arch: 'aarch64', os.version: '12.6', java.version: '19'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Command: [null, newSession {capabilities=[Capabilities {acceptInsecureCerts: true, browserName: firefox, moz:debuggerAddress: true, moz:firefoxOptions: {args: [], prefs: {browser.download.viewableInternally.enabledTypes: , browser.helperApps.neverAsk.saveToDisk: application/pdf;text/plain;..., pdfjs.disabled: true, security.mixed_content.block_active_content: false}}}], desiredCapabilities=Capabilities {acceptInsecureCerts: true, browserName: firefox, moz:debuggerAddress: true, moz:firefoxOptions: {args: [], prefs: {browser.download.viewableInternally.enabledTypes: , browser.helperApps.neverAsk.saveToDisk: application/pdf;text/plain;..., pdfjs.disabled: true, security.mixed_content.block_active_content: false}}}}]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:658)

**Comment by whimboo** [comment]
Again we would need a [trace-level log] from geckodriver.

[trace-level log]: https://firefox-source-docs.mozilla.org/testing/geckodriver/TraceLogs.html
