### ISSUE TITLE
Executable needs to be in PATH

### ISSUE THREAD

**Issue by tang-butian** [mozilla/geckodriver#2067]
Version: geckodriver 0.27.0
Platform: Adnroid
Firefox:  fennec-68.9.0.multi.android-i386
Selenium: 3.11
The following error occurs when I run it on Android
`
EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'selenium.common.exceptions.WebDriverException'>
                                                   Error Contents: Message: 'geckodriver' executable needs to be in PATH. 
                                                   
                                                   Traceback (most recent call last):
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.selenium/lib/selenium/webdriver/common/service.py", line 73, in start
                                                       self.process = subprocess.Popen(cmd, env=self.env,
                                                     File "/data/user/0/org.xbmc.kodi/cache/apk/assets/python3.8/lib/python3.8/subprocess.py", line 854, in __init__
                                                       self._execute_child(args, executable, preexec_fn, close_fds,
                                                     File "/data/user/0/org.xbmc.kodi/cache/apk/assets/python3.8/lib/python3.8/subprocess.py", line 1702, in _execute_child
                                                       raise child_exception_type(errno_num, err_msg, err_filename)
                                                   FileNotFoundError: [Errno 2] No such file or directory: '/mnt/local/tmp/geckodriver'
                                                   
                                                   During handling of the above exception, another exception occurred:
                                                   
                                                   Traceback (most recent call last):
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.cine/addon.py", line 2213, in <module>
                                                       plugin.run()
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.xbmcswift2/lib/xbmcswift2/plugin.py", line 338, in run
                                                       items = self._dispatch(self.request.path)
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.xbmcswift2/lib/xbmcswift2/plugin.py", line 312, in _dispatch
                                                       listitems = view_func(**items)
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.cine/addon.py", line 1005, in home
                                                       categories = get_categories_mode(mode)
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.cine/addon.py", line 265, in get_categories_mode
                                                       item = eval('get_' + mode + '_categories')()
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.cine/addon.py", line 335, in get_ku2000_categories
                                                       log(openURLWebDriverContent('https://www.iqiyi.com/v_19rrok4nt0.html'))
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.cine/addon.py", line 859, in openURLWebDriverContent
                                                       driver = webdriver.Firefox(executable_path = driverPath, log_path=rpath, options=options,  desired_capabilities= capabilities2)
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.selenium/lib/selenium/webdriver/firefox/webdriver.py", line 160, in __init__
                                                       self.service.start()
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.selenium/lib/selenium/webdriver/common/service.py", line 89, in start
                                                       raise WebDriverException(
                                                   selenium.common.exceptions.WebDriverException: Message: 'geckodriver' executable needs to be in PATH. 
                                                   
                                                   -->End of Python script error report<--
`
This is my code:
`
driverPath = get_driver_path('geckodriver')
        log('Driver path: ' + driverPath)
        options = webdriver.FirefoxOptions()
        #options.enable_mobile()
        capabilities2 = DesiredCapabilities.FIREFOX.copy()
        capabilities2['platform'] = ''
        capabilities2['androidPackage'] = 'org.mozilla.fennec_aurora'
        capabilities2["moz:firefoxOptions"] = {
            "androidPackage": "org.mozilla.fennec_aurora",
        }
        capabilities2["alwaysMatch"] = {
            "firstMatch": [
                {"platformName": ""},

            ],
            "moz:firefoxOptions": {
                "androidPackage": "org.mozilla.fennec_aurora",

            }
        }
        if VisibleBrowser == 'false':
            options.add_argument('headless')
        s = Service(driverPath)
        rpath = xbmcaddon.Addon('script.module.selenium').getAddonInfo(
            'path') + 'tmp' + os.path.sep + 'geckodriver.log'
        binlibry = '/data/app/org.mozilla.fennec_aurora-1'
        driver = webdriver.Firefox(executable_path = driverPath, log_path=rpath, options=options,  desired_capabilities= capabilities2)
`
How can I get the Path of the App?

**Comment by whimboo** [comment]
Well, this is not a geckodriver issue. Please consult the Selenium documentation in how correctly setting the geckodriver path if it hasn't been put into a folder which is part of the `PATH` environment variable. Also note that geckodriver needs to run on the host machine and not the Android device itself.

Also is there a reason why you are using Fennec (68.0) and not a more recent Firefox (Fenix) that is based on GeckoView. Fennec is no longer supported.
