### ISSUE TITLE
webdriver: Request failed with status 500 due to session not created

### ISSUE THREAD

**Issue by akash-basavaraju** [mozilla/geckodriver#2076]
## System

* Version: 3.141.59
* Platform: MacOS, M1 pro chiset
* Firefox: latest firefox
* Selenium: using selenium gecko driver for webdriver.io

## Testcase

Repo is enterprise level cant share. But, having this issue for all the wdio test running in MacBooks pro with M1 processor.

## Stacktrace

[0-0] 2023-01-09T08:16:10.706Z ERROR webdriver: Request failed with status 500 due to session not created: Unable to create session from {
[0-0]   "desiredCapabilities": {
[0-0]     "browserName": "firefox",
[0-0]     "moz:firefoxOptions": {
[0-0]       "args": [
[0-0]         "-remote-debugging-port",
[0-0]         "61398"
[0-0]       ]
[0-0]     },
[0-0]     "acceptInsecureCerts": true
[0-0]   },
[0-0]   "capabilities": {
[0-0]     "firstMatch": [
[0-0]       {
[0-0]         "acceptInsecureCerts": true,
[0-0]         "browserName": "firefox",
[0-0]         "moz:firefoxOptions": {
[0-0]           "args": [
[0-0]             "-remote-debugging-port",
[0-0]             "61398"
[0-0]           ]
[0-0]         }
[0-0]       }
[0-0]     ]
[0-0]   }
[0-0] }
[0-0] Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:53'
[0-0] System info: host: 'macos-CQVM0WHC0F', ip: '192.168.50.34', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '12.6', java.version: '1.8.0_351'
[0-0] Driver info: driver.version: unknown
[0-0] 2023-01-09T08:16:10.707Z ERROR webdriver: org.openqa.selenium.SessionNotCreatedException: Unable to create session from {
[0-0]   "desiredCapabilities": {
[0-0]     "browserName": "firefox",
[0-0]     "moz:firefoxOptions": {
[0-0]       "args": [
[0-0]         "-remote-debugging-port",
[0-0]         "61398"
[0-0]       ]
[0-0]     },
[0-0]     "acceptInsecureCerts": true
[0-0]   },
[0-0]   "capabilities": {
[0-0]     "firstMatch": [
[0-0]       {
[0-0]         "acceptInsecureCerts": true,
[0-0]         "browserName": "firefox",
[0-0]         "moz:firefoxOptions": {
[0-0]           "args": [
[0-0]             "-remote-debugging-port",
[0-0]             "61398"
[0-0]           ]
[0-0]         }
[0-0]       }
[0-0]     ]
[0-0]   }
[0-0] }
[0-0] Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:53'
[0-0] System info: host: 'macos-CQVM0WHC0F', ip: '192.168.50.34', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '12.6', java.version: '1.8.0_351'
[0-0] Driver info: driver.version: unknown
[0-0] 	at org.openqa.selenium.remote.server.NewSessionPipeline.lambda$null$4(NewSessionPipeline.java:76)
[0-0] 	at java.util.Optional.orElseThrow(Optional.java:290)
[0-0] 	at org.openqa.selenium.remote.server.NewSessionPipeline.lambda$createNewSession$5(NewSessionPipeline.java:75)
[0-0] 	at java.util.Optional.orElseGet(Optional.java:267)
[0-0] 	at org.openqa.selenium.remote.server.NewSessionPipeline.createNewSession(NewSessionPipeline.java:73)
[0-0] 	at org.openqa.selenium.remote.server.commandhandler.BeginSession.execute(BeginSession.java:65)
[0-0] 	at org.openqa.selenium.remote.server.WebDriverServlet.lambda$handle$0(WebDriverServlet.java:235)
[0-0] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[0-0] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[0-0] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[0-0] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[0-0] 	at java.lang.Thread.run(Thread.java:750)
[0-0] 
[0-0] 2023-01-09T08:16:10.707Z ERROR @wdio/runner: Error: Failed to create session.
[0-0] Unable to create session from {
[0-0]   "desiredCapabilities": {
[0-0]     "browserName": "firefox",
[0-0]     "moz:firefoxOptions": {
[0-0]       "args": [
[0-0]         "-remote-debugging-port",
[0-0]         "61398"
[0-0]       ]
[0-0]     },
[0-0]     "acceptInsecureCerts": true
[0-0]   },
[0-0]   "capabilities": {
[0-0]     "firstMatch": [
[0-0]       {
[0-0]         "acceptInsecureCerts": true,
[0-0]         "browserName": "firefox",
[0-0]         "moz:firefoxOptions": {
[0-0]           "args": [
[0-0]             "-remote-debugging-port",
[0-0]             "61398"
[0-0]           ]
[0-0]         }
[0-0]       }
[0-0]     ]
[0-0]   }
[0-0] }
[0-0] Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:53'
[0-0] System info: host: 'macos-CQVM0WHC0F', ip: '192.168.50.34', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '12.6', java.version: '1.8.0_351'
[0-0] Driver info: driver.version: unknown
[0-0]     at startWebDriverSession (/Users/ajohnson/replay-e2e-tests/node_modules/webdriver/build/utils.js:72:15)
[0-0]     at processTicksAndRejections (internal/process/task_queues.js:97:5)
[0-0] FAILED in firefox - /.replay-testsjL3ls8/TY22-E2E-JumpToPaths-AZI_new.js
Cleaning temporary test folders

Spec Files:	 0 passed, 1 failed, 1 total (100% completed) in 00:06:45 

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by whimboo** [comment]
Could you please attach a [trace-level log] from geckodriver? Read more about reporting actionable bugs in our [contribution guidelines].

[trace-level log]: https://firefox-source-docs.mozilla.org/testing/geckodriver/TraceLogs.html
[contribution guidelines]: https://firefox-source-docs.mozilla.org/testing/geckodriver/Bugs.html

**Comment by whimboo** [comment]
No further feedback from reporter.
