### ISSUE TITLE
webdriver: Request failed with status 500 due to session not created

### ISSUE THREAD

**Issue by akash-basavaraju** [mozilla/geckodriver#2081]
## System

Version: 3.141.59
Platform: MacOS, M1 pro chiset
Firefox: latest firefox
Selenium: using selenium gecko driver for webdriver.io

## Testcase

Repo is enterprise level cant share. But, having this issue for all the wdio test running in MacBooks pro with M1 processor.

## Stacktrace
[0-0] 2023-02-06T07:10:18.044Z ERROR webdriver: Request failed with status 500 due to session not created: Unable to find a matching set of capabilities
[0-0] Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:53'
[0-0] System info: host: 'macos-CQVM0WHC0F', ip: '192.168.50.34', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '12.6', java.version: '1.8.0_351'
[0-0] Driver info: driver.version: unknown
[0-0] remote stacktrace:
[0-0] 2023-02-06T07:10:18.044Z ERROR webdriver: org.openqa.selenium.SessionNotCreatedException: Unable to find a matching set of capabilities
[0-0] Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:53'
[0-0] System info: host: 'macos-CQVM0WHC0F', ip: '192.168.50.34', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '12.6', java.version: '1.8.0_351'
[0-0] Driver info: driver.version: unknown
[0-0] remote stacktrace:
[0-0] 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[0-0] 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[0-0] 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[0-0] 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[0-0] 	at org.openqa.selenium.remote.W3CHandshakeResponse.lambda$errorHandler$0(W3CHandshakeResponse.java:62)
[0-0] 	at org.openqa.selenium.remote.HandshakeResponse.lambda$getResponseFunction$0(HandshakeResponse.java:30)
[0-0] 	at org.openqa.selenium.remote.ProtocolHandshake.lambda$createSession$0(ProtocolHandshake.java:126)
[0-0] 	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
[0-0] 	at java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:958)
[0-0] 	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
[0-0] 	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:499)
[0-0] 	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:486)
[0-0] 	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
[0-0] 	at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152)
[0-0] 	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
[0-0] 	at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:464)
[0-0] 	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:128)
[0-0] 	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:74)
[0-0] 	at org.openqa.selenium.grid.session.remote.RemoteSession$Factory.performHandshake(RemoteSession.java:147)
[0-0] 	at org.openqa.selenium.grid.session.remote.ServicedSession$Factory.apply(ServicedSession.java:161)
[0-0] 	at org.openqa.selenium.remote.server.ActiveSessionFactory.lambda$apply$12(ActiveSessionFactory.java:180)
[0-0] 	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
[0-0] 	at java.util.stream.ReferencePipeline$11$1.accept(ReferencePipeline.java:373)
[0-0] 	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
[0-0] 	at java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:958)
[0-0] 	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
[0-0] 	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:499)
[0-0] 	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:486)
[0-0] 	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
[0-0] 	at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152)
[0-0] 	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
[0-0] 	at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:464)
[0-0] 	at org.openqa.selenium.remote.server.ActiveSessionFactory.apply(ActiveSessionFactory.java:183)
[0-0] 	at org.openqa.selenium.remote.server.NewSessionPipeline.lambda$null$2(NewSessionPipeline.java:66)
[0-0] 	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
[0-0] 	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
[0-0] 	at java.util.Collections$2.tryAdvance(Collections.java:4719)
[0-0] 	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
[0-0] 	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:499)
[0-0] 	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:486)
[0-0] 	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
[0-0] 	at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152)
[0-0] 	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
[0-0] 	at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:464)
[0-0] 	at org.openqa.selenium.remote.server.NewSessionPipeline.lambda$createNewSession$3(NewSessionPipeline.java:69)
[0-0] 	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
[0-0] 	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
[0-0] 	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
[0-0] 	at java.util.stream.DistinctOps$1$2.accept(DistinctOps.java:175)
[0-0] 	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
[0-0] 	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
[0-0] 	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
[0-0] 	at java.util.stream.Streams$StreamBuilderImpl.tryAdvance(Streams.java:405)
[0-0] 	at java.util.stream.Streams$ConcatSpliterator.tryAdvance(Streams.java:728)
[0-0] 	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
[0-0] 	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:499)
[0-0] 	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:486)
[0-0] 	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
[0-0] 	at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152)
[0-0] 	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
[0-0] 	at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:464)
[0-0] 	at org.openqa.selenium.remote.server.NewSessionPipeline.createNewSession(NewSessionPipeline.java:72)
[0-0] 	at org.openqa.selenium.remote.server.commandhandler.BeginSession.execute(BeginSession.java:65)
[0-0] 	at org.openqa.selenium.remote.server.WebDriverServlet.lambda$handle$0(WebDriverServlet.java:235)
[0-0] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[0-0] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[0-0] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[0-0] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[0-0] 	at java.lang.Thread.run(Thread.java:750)
[0-0]
[0-0] 2023-02-06T07:10:18.044Z ERROR @wdio/runner: Error: Failed to create session.
[0-0] Unable to find a matching set of capabilities
[0-0] Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:53'
[0-0] System info: host: 'macos-CQVM0WHC0F', ip: '192.168.50.34', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '12.6', java.version: '1.8.0_351'
[0-0] Driver info: driver.version: unknown
[0-0] remote stacktrace:
[0-0]   at startWebDriverSession (/Users/ajohnson/replay-e2e-tests/node_modules/webdriver/build/utils.js:72:15)
[0-0]   at processTicksAndRejections (internal/process/task_queues.js:95:5)
[0-0]   at async Function.newSession (/Users/ajohnson/replay-e2e-tests/node_modules/webdriver/build/index.js:42:45)
[0-0]   at async remote (/Users/ajohnson/replay-e2e-tests/node_modules/webdriverio/build/index.js:73:22)
[0-0]   at async Runner._startSession (/Users/ajohnson/replay-e2e-tests/node_modules/@wdio/runner/build/index.js:223:56)
[0-0]   at async Runner._initSession (/Users/ajohnson/replay-e2e-tests/node_modules/@wdio/runner/build/index.js:176:25)
[0-0]   at async Runner.run (/Users/ajohnson/replay-e2e-tests/node_modules/@wdio/runner/build/index.js:88:19)

**Comment by whimboo** [comment]
Could you please attach a [trace-level log] from geckodriver? Read more about reporting actionable bugs in our [contribution guidelines].

[trace-level log]: https://firefox-source-docs.mozilla.org/testing/geckodriver/TraceLogs.html
[contribution guidelines]: https://firefox-source-docs.mozilla.org/testing/geckodriver/Bugs.html

**Comment by akash-basavaraju** [comment]
Hi whimboo,
I tried with `{"moz:firefoxOptions": {"log": {"level": "trace"}}}`. But this is the log I got.

**Comment by whimboo** [comment]
Did you check if there is an eg. `geckodriver.log` file in the folder?

**Comment by akash-basavaraju** [comment]
No, its not there.

**Comment by whimboo** [comment]
Does [something like that](https://github.com/webdriverio/webdriverio/blob/a1a3c37f031dbd1728a548a34ebfb916a12cad5a/website/docs/SetupTypes.md#standalone-mode) help?
