### ISSUE TITLE
Firefox browser failing to launch

### ISSUE THREAD

**Issue by rahulkundu01** [mozilla/geckodriver#2118]
## System

* Version: <0.33.0>
* Platform: <windows 11->
* Firefox: <113.0.2>
* Selenium: <4.9.1>

## Testcase

Tried to launch the Firefox driver for running Test Script:
public static WebDriver wd;

	public static void main(String[] args) {
		// TODO Auto-generated method stub
		FirefoxOptions options = new FirefoxOptions();
		options.setLogLevel(FirefoxDriverLogLevel.TRACE);
		//System.setProperty("webdriver.chrome.driver",System.getProperty("user.dir")+"\\src\\test\\java\\drivers\\chromedriver1.exe");
		System.setProperty("webdriver.gecko.driver",System.getProperty("user.dir")+"\\src\\test\\java\\drivers\\geckodriver.exe");
		wd = new FirefoxDriver(options);
		//wd = new ChromeDriver();
		String baseUrl = "http://demo.guru99.com/test/newtours/";
        String expectedTitle = "Welcome: Mercury Tours";
        String actualTitle = "";
        
        // launch Chrome and direct it to the Base URL
        wd.get(baseUrl);

****** 

but its failing to launch on running.

## Stacktrace

Exception in thread "main" org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure. 
Host info: host: 'RK', ip: '192.168.0.109'
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:561)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:229)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:157)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:150)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:146)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:131)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:127)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:112)
	at practice_play.Mercury_Nav.main(Mercury_Nav.java:18)
Caused by: org.openqa.selenium.WebDriverException: Timed out waiting for driver process to start.
Build info: version: '4.9.1', revision: 'eb2032df7f'
System info: os.name: 'Windows 11', os.arch: 'amd64', os.version: '10.0', java.version: '19'
Driver info: driver.version: FirefoxDriver
	at org.openqa.selenium.remote.service.DriverService.start(DriverService.java:216)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:114)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:543)
	... 8 more

**Comment by whimboo** [comment]
Hi. The attached stack is sadly not a trace log from geckodriver. Please check again [our documentation in how get those logs](https://firefox-source-docs.mozilla.org/testing/geckodriver/TraceLogs.html). Thanks.

**Comment by whimboo** [comment]
No further reply from reporter.
