### ISSUE TITLE
gecko driver is throwing error python API

### ISSUE THREAD

**Issue by mjaafa** [mozilla/geckodriver#2125]
## System

Last firefox version 102.13.0esr

## Testcase

from selenium import webdriver
#browser = webdriver.Firefox(executable_path='/usr/bin/geckodriver')
browser = webdriver.Firefox()
browser.get('http://www.ubuntu.com/')

## Stacktrace

Traceback (most recent call last):
  File "/home/momo/test.py", line 3, in <module>
    browser = webdriver.Firefox()
              ^^^^^^^^^^^^^^^^^^^
  File "/home/momo/anaconda3/lib/python3.11/site-packages/selenium/webdriver/firefox/webdriver.py", line 61, in __init__
    self.service.start()
  File "/home/momo/anaconda3/lib/python3.11/site-packages/selenium/webdriver/common/service.py", line 97, in start
    self.assert_process_still_running()
  File "/home/momo/anaconda3/lib/python3.11/site-packages/selenium/webdriver/common/service.py", line 110, in assert_process_still_running
    raise WebDriverException(f"Service {self._path} unexpectedly exited. Status code was: {return_code}")
selenium.common.exceptions.WebDriverException: Message: Service /usr/bin/geckodriver unexpectedly exited. Status code was: 64

**Comment by whimboo** [comment]
Could you please attach a [trace-level log] from geckodriver? Read more about reporting actionable bugs in our [contribution guidelines]. Also which version of geckodriver is in use?

[trace-level log]: https://firefox-source-docs.mozilla.org/testing/geckodriver/TraceLogs.html
[contribution guidelines]: https://firefox-source-docs.mozilla.org/testing/geckodriver/Bugs.html

**Comment by whimboo** [comment]
No response from reporter. Closing for now but happy to reopen if the requested information can be provided.
