### ISSUE TITLE
org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Response code 400. Message: Unrecognised option moz:debuggerAddress

### ISSUE THREAD

**Issue by Argano-GQE** [mozilla/geckodriver#2132]
## System
When trying to launch the Firefox Browser from the selenoid hub in docker then I am getting the below error 
**_"org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Response code 400. Message: Unrecognised option moz:debuggerAddress"_**

* Version: 
* Platform: Windows/Linux
* Firefox: Any Browser Version
* Selenium: 4.11.0 and 4.12.0

## Testcase

When trying to launch the Firefox Browser from the selenoid hub in docker then I am getting the error .

**Comment by whimboo** [comment]
Could you please attach a [trace-level log] from geckodriver? Read more about reporting actionable bugs in our [contribution guidelines].

[trace-level log]: https://firefox-source-docs.mozilla.org/testing/geckodriver/TraceLogs.html
[contribution guidelines]: https://firefox-source-docs.mozilla.org/testing/geckodriver/Bugs.html

**Comment by Argano-GQE** [comment]
I am using selenoid grid 


**org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Response code 400. Message: Unrecognised option moz:debuggerAddress** 
Host info: host: 'ARGANO-BT4J1J3', ip: '192.168.1.14'
Build info: version: '4.12.1', revision: '8e34639b11'
System info: os.name: 'Windows 11', os.arch: 'amd64', os.version: '10.0', java.version: '17.0.8'
Driver info: org.openqa.selenium.remote.RemoteWebDriver
Command: [null, newSession {capabilities=[Capabilities {acceptInsecureCerts: true, browserName: firefox, browserVersion: 83, moz:debuggerAddress: true, moz:firefoxOptions: {}, selenoid:options: {enableVNC: true, name: LoginPageTest, screenResolution: 1280x1024x24}}]}]
Capabilities {acceptInsecureCerts: true, browserName: firefox, browserVersion: 83, moz:debuggerAddress: true, moz:firefoxOptions: {}, selenoid:options: {enableVNC: true, name: LoginPageTest, screenResolution: 1280x1024x24}}
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:140)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:96)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:68)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:163)
	at org.openqa.selenium.remote.TracedCommandExecutor.execute(TracedCommandExecutor.java:51)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:602)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:236)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:163)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:143)
	at com.qa.opencart.factory.DriverFactory.init_remoteDriver(DriverFactory.java:112)
	at com.qa.opencart.factory.DriverFactory.initDriver(DriverFactory.java:77)
	at com.qa.opencart.base.BaseTest.setup(BaseTest.java:48)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
	at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:62)
	at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:385)
	at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:321)
	at org.testng.TestRunner.invokeTestConfigurations(TestRunner.java:637)
	at org.testng.TestRunner.beforeRun(TestRunner.java:627)
	at org.testng.TestRunner.run(TestRunner.java:589)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:28)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:418)
	at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by whimboo** [comment]
Why is that using such an old release of Firefox? See the `browserVersion: 83` in the capabilities output. Please update to a recent version of Firefox, which is 117, and it will work.

**Comment by Argano-GQE** [comment]
Working fine . Thx
