### ISSUE TITLE
Unable to launch Firefox with geckodriver 0.34.0 on Windows 11

### ISSUE THREAD

**Issue by elhaddajiOtmane** [mozilla/geckodriver#2175]
## System
_Version:_ 0.34.0
_Platform:_ Windows 11
_Firefox:_ Firefox Developer Edition 110.0b7 (64-bit)
_Selenium:_ Python 3.10.6 + Selenium

## Testcase
The provided HTML code is for the MEGA login page:

```html
<div class="main-left-block">
    <form id="login_form" class="account login-form">
        <div class="account top-header login">Log&nbsp;in</div>
        <div class="mega-input title-ontop">
            <div class="mega-input-title">Your email address</div>
            <input type="text" class="underlinedText megaInputs" name="login-name2" id="login-name2" value="" placeholder="Your email address" maxlength="190">
            <div class="message-container mega-banner"></div>
        </div>
        <div class="mega-input title-ontop">
            <div class="mega-input-title">Password</div>
            <input type="password" class="underlinedText megaInputs" name="login-password2" id="login-password2" placeholder="Password">
            <div class="message-container mega-banner"></div>
            <i class="sprite-fm-mono icon-eye-reveal pass-visible"></i>
        </div>
        <div class="login-page-forgot-bl">
            <a class="top-login-forgot-pass" tabindex="-1"> <span>Forgot your password?</span> </a>
            <div class="clear"></div>
        </div>
        <div class="account checkbox-block left">
            <div class="login-check checkboxOn checkbox">
                <input class="checkboxOn megaInputs" type="checkbox" name="login-check2" id="login-check2" checked="">
            </div>
            <label class="radio-txt">Remember me</label>
        </div>
        <button class="mega-button positive login-button large right" tabindex="0" type="button"> <span>Log&nbsp;in</span> </button>
        <div class="clear"></div>
        <div class="account dialog-dark-bottom register"> Don't have an account? <a class="clickurl" href="/register" data-eventid="99797">Create one now</a> </div>
    </form>
</div>
```

## Stacktrace
```
Traceback (most recent call last):
  File "c:\Program Files\Firefox Developer Edition\scripts\mega.py", line 37, in <module>
    auto_login('usernname@examle.me', 'RV345P*345*b4nk')
  File "c:\Program Files\Firefox Developer Edition\scripts\mega.py", line 16, in auto_login
    driver = webdriver.Firefox(service=service, options=options)
  File "C:\Users\elhad\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\selenium\webdriver\firefox\webdriver.py", line 60, in __init__
    self.service.start()
  File "C:\Users\elhad\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\selenium\webdriver\common\service.py", line 98, in start
    self._start_process(self._path)
  File "C:\Users\elhad\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\selenium\webdriver\common\service.py", line 208, in _start_process
    self.process = subprocess.Popen(
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\subprocess.py", line 1538, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
OSError: [WinError 216] This version of %1 is not compatible with the version of Windows you're running. Check your computer's system information and then contact the software publisher
```

## Trace-level log
A trace-level log is not created on C:\geckodriver
![wwww](https://github.com/mozilla/geckodriver/assets/39245156/842ac228-160b-4ddd-b4c1-2f82f9a49d63)

**Comment by whimboo** [comment]
Did you download the correct version of geckodriver? Note that there is a difference between 64bit and 32bit. Please check and make sure that you run the 64bit version.

If you do does the same happen for the 0.33.0 release as well? Or with which version of geckodriver did this crash start to happen?

**Comment by whimboo** [comment]
No response from reporter. Closing issue as incomplete.
