### ISSUE TITLE
Cannot find firefox binary in PATH. Make sure firefox is installed. OS appears to be: MAC

### ISSUE THREAD

**Issue by ngoraii** [mozilla/geckodriver#2208]
## System

* Version: v0.35.0
* Platform: Mac M1
* Firefox: 132.0.2 (aarch64)
* Selenium: selenium-server-standalone-3.141.59

## Testcase
package demo;

import org.openqa.selenium.firefox.FirefoxDriver;

public class Sample {
	public static void main(String[] args) throws InterruptedException {
		String key="webdriver.gecko.driver";
		String value="/Users/ngorai/eclipse-workspace/Selenium/softwares/geckodriver";
		System.setProperty(key, value);
		FirefoxDriver driver = new FirefoxDriver();
		driver.navigate().to("https://opensea.io/collection/onchain-gaias/activity");
		
	}

}

## Stacktrace

Exception in thread "main" org.openqa.selenium.WebDriverException: Cannot find firefox binary in PATH. Make sure firefox is installed. OS appears to be: MAC
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:53'
System info: host: 'Nayans-MacBook-Air.local', ip: '2401:4900:1c01:a365:9d82:6074:1f61:95ae%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '15.0.1', java.version: '22.0.2'
Driver info: driver.version: FirefoxDriver
	at org.openqa.selenium.firefox.FirefoxBinary.<init>(FirefoxBinary.java:100)
	at java.base/java.util.Optional.orElseGet(Optional.java:364)
	at org.openqa.selenium.firefox.FirefoxOptions.getBinary(FirefoxOptions.java:216)
	at org.openqa.selenium.firefox.FirefoxDriver.toExecutor(FirefoxDriver.java:187)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:147)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:125)
	at demo.Sample.main(Sample.java:10)

**Comment by whimboo** [comment]
Could you please attach a [trace-level log] from geckodriver?

[trace-level log]: https://firefox-source-docs.mozilla.org/testing/geckodriver/TraceLogs.html
[contribution guidelines]: https://firefox-source-docs.mozilla.org/testing/geckodriver/Bugs.html

**Comment by whimboo** [comment]
No further reply from reporter. Closing issue as incomplete.
