### ISSUE TITLE
Error - org.openqa.selenium.remote.ProtocolHandshake createSession

### ISSUE THREAD

**Issue by jayaKirti** [mozilla/geckodriver#229]
Getting below error - 
Sep 13, 2016 6:36:26 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Attempting bi-dialect session, assuming Postel's Law holds true on the remote end
using -
Window10, Java JDK 8 , Fire fox  48 and selenium3.0.0-beta3 | Selenium Automation

code : 
System.setProperty("webdriver.gecko.driver","C:\\Selenium-java-3.0.0\\geckodriver\\geckodriver.exe");
WebDriver driver = new FirefoxDriver();

**Comment by andreastt** [comment]
You need to provide more information for this to be an actionable issue report. Please provide us with the full stacktrace and verbose logs from the geckodriver binary. You can get these by starting it with the `-vv` flag.

I’m happy to re-open this issue when sufficient information is provided.

**Comment by andreastt** [comment]
@kiran3090 It’s impossible to say why unless you include a verbose log from geckodriver.

**Comment by sarank87** [comment]
@andreastt 
Hi I am also getting the same error message as Kiran. 
I am using gecko driver 0.10 anf FF v49 with Selenium v3.beta
Can you please advise and the steps to get the verbose log for geckodriver ?

**Comment by andreastt** [comment]
@sarank87 Append `-vv` to the command line flags passed to the geckodriver binary.

**Comment by priyanka-chaubey** [comment]
I face bit similar error , if can identify while writing script on Ecllipse for Appium

Sep 29, 2016 4:57:36 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Attempting bi-dialect session, assuming Postel's Law holds true on the remote end
Exception in thread "main" org.openqa.selenium.remote.UnreachableBrowserException: Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure.
Build info: version: 'unknown', revision: 'c7b525d', time: '2016-09-01 14:52:30 -0700'
System info: host: 'T530-THINK', ip: '10.1.1.80', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_102'
Driver info: driver.version: AndroidDriver
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:618)
	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:180)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:242)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:129)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:156)
	at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:109)
	at io.appium.java_client.android.AndroidDriver.<init>(AndroidDriver.java:39)
	at test.StartApplication.main(StartApplication.java:37)
Caused by: org.apache.http.conn.HttpHostConnectException: Connect to 127.0.0.1:4727 [/127.0.0.1] failed: Connection refused: connect
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:158)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:353)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:380)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:71)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:55)
	at org.openqa.selenium.remote.internal.ApacheHttpClient.fallBackExecute(ApacheHttpClient.java:142)
	at org.openqa.selenium.remote.internal.ApacheHttpClient.execute(ApacheHttpClient.java:88)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:97)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:55)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:141)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:597)
	... 7 more
Caused by: java.net.ConnectException: Connection refused: connect
	at java.net.DualStackPlainSocketImpl.waitForConnect(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(Unknown Source)
	at java.net.AbstractPlainSocketImpl.doConnect(Unknown Source)
	at java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source)
	at java.net.AbstractPlainSocketImpl.connect(Unknown Source)
	at java.net.PlainSocketImpl.connect(Unknown Source)
	at java.net.SocksSocketImpl.connect(Unknown Source)
	at java.net.Socket.connect(Unknown Source)
	at org.apache.http.conn.socket.PlainConnectionSocketFactory.connectSocket(PlainConnectionSocketFactory.java:74)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:141)
	... 22 more

**Comment by priyanka-chaubey** [comment]
I have followed below mentioned steps for appium set up : 
1)jdk installed
2)Ecllipse 
3) Appium Installed.
4) Set paths for android home , Java home , other path variables .
5) I have copied sdk folder and added path for platform tools and tools
6) Added jars for Gson, Selenium , Client etc.

Please let me what else needed to get started . 
I am sharing screenshot for the appium config [
!img_20160929_172210540 1](https://cloud.githubusercontent.com/assets/22496134/18952886/6408d540-8669-11e6-8cc6-5c8820bc2992.jpg)
(url)

**Comment by bhupendrarautela** [comment]
I am also facing this issue.


[XmlSuite] [WARN] 'parallel' value 'false' is deprecated, default value will be used instead: 'none'.
[TestNG] Running:
  C:\Users\Bhupendra\AppData\Local\Temp\testng-eclipse--1349211820\testng-customsuite.xml

here
Usage:
    C:\selenium\geckodriver.exe [OPTIONS]
C:\selenium\geckodriver.exe: Unknown option --port=14157
Oct 26, 2016 11:44:57 AM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Attempting bi-dialect session, assuming Postel's Law holds true on the remote end
[Utils] Attempting to create C:\Users\Bhupendra\workspace\Glaucus_oms_test\test-output\Default suite\Default test.xml
[Utils]   Directory C:\Users\Bhupendra\workspace\Glaucus_oms_test\test-output\Default suite exists: true
FAILED CONFIGURATION: @BeforeClass setUp
org.openqa.selenium.WebDriverException: org.apache.http.conn.HttpHostConnectException: Connect to localhost:14157 [localhost/127.0.0.1, localhost/0:0:0:0:0:0:0:1] failed: Connection refused: connect
Build info: version: '3.0.1', revision: '1969d75', time: '2016-10-18 09:48:19 -0700'
System info: host: 'LAPTOP-VQQSI8R2', ip: '192.168.1.7', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_111'
Driver info: driver.version: FirefoxDriver
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:91)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:601)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:241)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:128)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:259)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:247)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:242)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:238)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:127)
	at com.glaucus.HomeTest.setUp(HomeTest.java:27)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:100)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:515)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:216)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:143)
	at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:169)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:753)
	at org.testng.TestRunner.run(TestRunner.java:607)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:368)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:363)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:321)
	at org.testng.SuiteRunner.run(SuiteRunner.java:270)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1284)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1209)
	at org.testng.TestNG.runSuites(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1096)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
Caused by: org.apache.http.conn.HttpHostConnectException: Connect to localhost:14157 [localhost/127.0.0.1, localhost/0:0:0:0:0:0:0:1] failed: Connection refused: connect
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:158)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:353)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:380)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:71)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:55)
	at org.openqa.selenium.remote.internal.ApacheHttpClient.fallBackExecute(ApacheHttpClient.java:142)
	at org.openqa.selenium.remote.internal.ApacheHttpClient.execute(ApacheHttpClient.java:88)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:108)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:64)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:141)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:82)
	... 34 more
Caused by: java.net.ConnectException: Connection refused: connect
	at java.net.DualStackPlainSocketImpl.waitForConnect(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(Unknown Source)
	at java.net.AbstractPlainSocketImpl.doConnect(Unknown Source)
	at java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source)
	at java.net.AbstractPlainSocketImpl.connect(Unknown Source)
	at java.net.PlainSocketImpl.connect(Unknown Source)
	at java.net.SocksSocketImpl.connect(Unknown Source)
	at java.net.Socket.connect(Unknown Source)
	at org.apache.http.conn.socket.PlainConnectionSocketFactory.connectSocket(PlainConnectionSocketFactory.java:74)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:141)
	... 49 more

FAILED CONFIGURATION: @AfterClass tearDown
java.lang.NullPointerException
	at com.glaucus.HomeTest.tearDown(HomeTest.java:67)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:100)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:515)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:216)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:143)
	at org.testng.internal.TestMethodWorker.invokeAfterClassMethods(TestMethodWorker.java:217)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:115)
	at org.testng.TestRunner.privateRun(TestRunner.java:753)
	at org.testng.TestRunner.run(TestRunner.java:607)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:368)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:363)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:321)
	at org.testng.SuiteRunner.run(SuiteRunner.java:270)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1284)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1209)
	at org.testng.TestNG.runSuites(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1096)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)

SKIPPED: testChat
SKIPPED: testLogin

===============================================
    Default test
    Tests run: 2, Failures: 0, Skips: 2
    Configuration Failures: 2, Skips: 0
===============================================


===============================================
Default suite
Total tests run: 2, Failures: 0, Skips: 2
Configuration Failures: 2, Skips: 0
===============================================

[TestNG] Time taken by org.testng.reporters.XMLReporter@2752f6e2: 17 ms
[Utils] Attempting to create C:\Users\Bhupendra\workspace\Glaucus_oms_test\test-output\junitreports\TEST-com.glaucus.HomeTest.xml
[Utils]   Directory C:\Users\Bhupendra\workspace\Glaucus_oms_test\test-output\junitreports exists: true
[TestNG] Time taken by org.testng.reporters.JUnitReportReporter@48140564: 26 ms
[TestNG] Time taken by org.testng.reporters.EmailableReporter2@4c203ea1: 28 ms
[Utils] Attempting to create C:\Users\Bhupendra\workspace\Glaucus_oms_test\test-output\old\Default suite\toc.html
[Utils]   Directory C:\Users\Bhupendra\workspace\Glaucus_oms_test\test-output\old\Default suite exists: true
[Utils] Attempting to create C:\Users\Bhupendra\workspace\Glaucus_oms_test\test-output\old\Default suite\Default test.properties
[Utils]   Directory C:\Users\Bhupendra\workspace\Glaucus_oms_test\test-output\old\Default suite exists: true
[Utils] Attempting to create C:\Users\Bhupendra\workspace\Glaucus_oms_test\test-output\old\Default suite\index.html
[Utils]   Directory C:\Users\Bhupendra\workspace\Glaucus_oms_test\test-output\old\Default suite exists: true
[Utils] Attempting to create C:\Users\Bhupendra\workspace\Glaucus_oms_test\test-output\old\Default suite\main.html
[Utils]   Directory C:\Users\Bhupendra\workspace\Glaucus_oms_test\test-output\old\Default suite exists: true
[Utils] Attempting to create C:\Users\Bhupendra\workspace\Glaucus_oms_test\test-output\old\Default suite\groups.html
[Utils]   Directory C:\Users\Bhupendra\workspace\Glaucus_oms_test\test-output\old\Default suite exists: true
[Utils] Attempting to create C:\Users\Bhupendra\workspace\Glaucus_oms_test\test-output\old\Default suite\classes.html
[Utils]   Directory C:\Users\Bhupendra\workspace\Glaucus_oms_test\test-output\old\Default suite exists: true
[Utils] Attempting to create C:\Users\Bhupendra\workspace\Glaucus_oms_test\test-output\old\Default suite\reporter-output.html
[Utils]   Directory C:\Users\Bhupendra\workspace\Glaucus_oms_test\test-output\old\Default suite exists: true
[Utils] Attempting to create C:\Users\Bhupendra\workspace\Glaucus_oms_test\test-output\old\Default suite\methods-not-run.html
[Utils]   Directory C:\Users\Bhupendra\workspace\Glaucus_oms_test\test-output\old\Default suite exists: true
[Utils] Attempting to create C:\Users\Bhupendra\workspace\Glaucus_oms_test\test-output\old\Default suite\testng.xml.html
[Utils]   Directory C:\Users\Bhupendra\workspace\Glaucus_oms_test\test-output\old\Default suite exists: true
[Utils] Attempting to create C:\Users\Bhupendra\workspace\Glaucus_oms_test\test-output\old\index.html
[Utils]   Directory C:\Users\Bhupendra\workspace\Glaucus_oms_test\test-output\old exists: true
[TestNG] Time taken by org.testng.reporters.SuiteHTMLReporter@7d417077: 100 ms
[TestNG] Time taken by org.testng.reporters.jq.Main@2c8d66b2: 47 ms
[Utils] Attempting to create C:\Users\Bhupendra\workspace\Glaucus_oms_test\test-output\testng-failed.xml
[Utils]   Directory C:\Users\Bhupendra\workspace\Glaucus_oms_test\test-output exists: true
[Utils] Attempting to create C:\Users\Bhupendra\workspace\Glaucus_oms_test\test-output\Default suite\testng-failed.xml
[Utils]   Directory C:\Users\Bhupendra\workspace\Glaucus_oms_test\test-output\Default suite exists: true
[TestNG] Time taken by [FailedReporter passed=0 failed=0 skipped=0]: 12 ms

**Comment by andreastt** [comment]
I’m going to lock this as no one has been able to say what steps to take to reproduce this. It doesn’t help to just add more of what is already here to the conversation.

**Comment by andreastt** [comment]
There appears to be further discussion about this in https://github.com/SeleniumHQ/selenium/issues/3087.
