### ISSUE TITLE
 FF 49.0, GeckoDriver v0.9.0, Selenium 2.53.1 doesn't work 

### ISSUE THREAD

**Issue by FlorianSchaetz** [mozilla/geckodriver#239]
Probably the latest Firefox Update on Ubuntu killed the Selenium driver somehow (because before it worked nicely)... Test starts, FF opens to blank page, nothing happens, then timeout.

If I can get a better log via Java, please tell me, how, currently I'm using...

```
DesiredCapabilities capabilities = DesiredCapabilities.firefox();
LoggingPreferences logs = new LoggingPreferences();
logs.enable(LogType.DRIVER, Level.ALL);
capabilities.setCapability(CapabilityType.LOGGING_PREFS, logs);
```

```
> Build info: version: '2.53.1', revision: 'a36b8b1cd5757287168e54b817830adce9b0158d', time: '2016-06-30 19:26:09'
> System info: host: 'wsn062', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '4.4.0-38-generic', java.version: '1.8.0_65'
> Driver info: driver.version: FirefoxDriver
> 	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:154)
> 	at com.example.test.selenium.SeleniumTestExecutionListener.prepareTestInstance(SeleniumTestExecutionListener.java:76)
> 	at org.springframework.test.context.TestContextManager.prepareTestInstance(TestContextManager.java:230)
> 	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.createTest(SpringJUnit4ClassRunner.java:228)
> 	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner$1.runReflectiveCall(SpringJUnit4ClassRunner.java:287)
> 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
> 	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.methodBlock(SpringJUnit4ClassRunner.java:289)
> 	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:247)
> 	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:94)
> 	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
> 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
> 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
> 	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
> 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
> 	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
> 	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:70)
> 	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
> 	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:191)
> 	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
> 	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
> 	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
> 	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678)
> 	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
> 	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
> Caused by: org.openqa.selenium.WebDriverException: Failed to connect to binary FirefoxBinary(/usr/bin/firefox) on port 7055; process output follows: 
> ritve za Firefox.","creator":"Canonical Ltd.","homepageURL":null},{"locales":["sv-SE"],"name":"Ubuntu Modifications","description":"Ubuntu-paket för Firefox.","creator":"Canonical Ltd.","homepageURL":null},{"locales":["uk"],"name":"Ubuntu Modifications","description":"Убунтівські доповнення до Firefox.","creator":"Canonical Ltd.","homepageURL":null},{"locales":["zh-CN"],"name":"Ubuntu Modifications","description":"Ubuntu 火狐扩展包.","creator":"Canonical Ltd.","homepageURL":null},{"locales":["zh-TW"],"name":"Ubuntu Modifications","description":"Ubuntu Firefox 擴充包。","creator":"Canonical Ltd.","homepageURL":null}],"targetApplications":[{"id":"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","minVersion":"9.0","maxVersion":"37.0a1"}],"targetPlatforms":[],"multiprocessCompatible":false,"seen":true}
> 1475052587830	DeferredSave.extensions.json	DEBUG	Save changes
> 1475052587830	addons.xpi	DEBUG	Updating database with changes to installed add-ons
> 1475052587830	addons.xpi-utils	DEBUG	Updating add-on states
> 1475052587831	addons.xpi-utils	DEBUG	Writing add-ons list
> 1475052587832	addons.xpi	DEBUG	Registering manifest for /usr/lib/firefox/browser/features/e10srollout@mozilla.org.xpi
> 1475052587833	addons.xpi	DEBUG	Calling bootstrap method startup on e10srollout@mozilla.org version 1.2
> 1475052587833	addons.xpi	DEBUG	Registering manifest for /usr/lib/firefox/browser/features/firefox@getpocket.com.xpi
> 1475052587834	addons.xpi	DEBUG	Calling bootstrap method startup on firefox@getpocket.com version 1.0.4
> 1475052587835	addons.xpi	DEBUG	Registering manifest for /usr/lib/firefox/browser/features/webcompat@mozilla.org.xpi
> 1475052587835	addons.xpi	DEBUG	Calling bootstrap method startup on webcompat@mozilla.org version 1.0
> 1475052587836	addons.xpi	DEBUG	Registering manifest for /usr/lib/firefox/browser/extensions/langpack-en-ZA@firefox.mozilla.org.xpi
> 1475052587837	addons.xpi	DEBUG	Registering manifest for /usr/lib/firefox/browser/extensions/langpack-en-GB@firefox.mozilla.org.xpi
> 1475052587838	addons.xpi	DEBUG	Registering manifest for /usr/lib/firefox/browser/extensions/langpack-de@firefox.mozilla.org.xpi
> 1475052587840	addons.manager	DEBUG	Registering shutdown blocker for XPIProvider
> 1475052587841	addons.manager	DEBUG	Provider finished startup: XPIProvider
> 1475052587841	addons.manager	DEBUG	Starting provider: LightweightThemeManager
> 1475052587841	addons.manager	DEBUG	Registering shutdown blocker for LightweightThemeManager
> 1475052587841	addons.manager	DEBUG	Provider finished startup: LightweightThemeManager
> 1475052587841	addons.manager	DEBUG	Starting provider: GMPProvider
> 1475052587846	addons.manager	DEBUG	Registering shutdown blocker for GMPProvider
> 1475052587847	addons.manager	DEBUG	Provider finished startup: GMPProvider
> 1475052587847	addons.manager	DEBUG	Starting provider: PluginProvider
> 1475052587847	addons.manager	DEBUG	Registering shutdown blocker for PluginProvider
> 1475052587847	addons.manager	DEBUG	Provider finished startup: PluginProvider
> 1475052587848	addons.manager	DEBUG	Completed startup sequence
> 1475052588185	addons.manager	DEBUG	Starting provider: <unnamed-provider>
> 1475052588185	addons.manager	DEBUG	Registering shutdown blocker for <unnamed-provider>
> 1475052588186	addons.manager	DEBUG	Provider finished startup: <unnamed-provider>
> 1475052588189	DeferredSave.extensions.json	DEBUG	Starting write
> 1475052588271	addons.repository	DEBUG	No addons.json found.
> 1475052588271	DeferredSave.addons.json	DEBUG	Save changes
> 1475052588274	DeferredSave.addons.json	DEBUG	Starting timer
> 1475052588292	addons.manager	DEBUG	Starting provider: PreviousExperimentProvider
> 1475052588292	addons.manager	DEBUG	Registering shutdown blocker for PreviousExperimentProvider
> 1475052588292	addons.manager	DEBUG	Provider finished startup: PreviousExperimentProvider
> 1475052588294	DeferredSave.extensions.json	DEBUG	Write succeeded
> 1475052588294	addons.xpi-utils	DEBUG	XPI Database saved, setting schema version preference to 17
> 1475052588374	DeferredSave.addons.json	DEBUG	Starting write
> 1475052588384	DeferredSave.addons.json	DEBUG	Write succeeded
> 
> Build info: version: '2.53.1', revision: 'a36b8b1cd5757287168e54b817830adce9b0158d', time: '2016-06-30 19:26:09'
> System info: host: 'wsn062', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '4.4.0-38-generic', java.version: '1.8.0_65'
> Driver info: driver.version: FirefoxDriver
> 	at org.openqa.selenium.firefox.internal.NewProfileExtensionConnection.start(NewProfileExtensionConnection.java:125)
> 	at org.openqa.selenium.firefox.FirefoxDriver.startClient(FirefoxDriver.java:271)
> 	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:119)
> 	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:216)
> 	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:211)
> 	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:128)
> 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
> 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
> 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
> 	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
> 	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:142)
> 	... 23 common frames omitted
> Caused by: org.openqa.selenium.firefox.NotConnectedException: Unable to connect to host 127.0.0.1 on port 7055 after 45000 ms. Firefox console output:
> ritve za Firefox.","creator":"Canonical Ltd.","homepageURL":null},{"locales":["sv-SE"],"name":"Ubuntu Modifications","description":"Ubuntu-paket för Firefox.","creator":"Canonical Ltd.","homepageURL":null},{"locales":["uk"],"name":"Ubuntu Modifications","description":"Убунтівські доповнення до Firefox.","creator":"Canonical Ltd.","homepageURL":null},{"locales":["zh-CN"],"name":"Ubuntu Modifications","description":"Ubuntu 火狐扩展包.","creator":"Canonical Ltd.","homepageURL":null},{"locales":["zh-TW"],"name":"Ubuntu Modifications","description":"Ubuntu Firefox 擴充包。","creator":"Canonical Ltd.","homepageURL":null}],"targetApplications":[{"id":"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","minVersion":"9.0","maxVersion":"37.0a1"}],"targetPlatforms":[],"multiprocessCompatible":false,"seen":true}
> 1475052587830	DeferredSave.extensions.json	DEBUG	Save changes
> 1475052587830	addons.xpi	DEBUG	Updating database with changes to installed add-ons
> 1475052587830	addons.xpi-utils	DEBUG	Updating add-on states
> 1475052587831	addons.xpi-utils	DEBUG	Writing add-ons list
> 1475052587832	addons.xpi	DEBUG	Registering manifest for /usr/lib/firefox/browser/features/e10srollout@mozilla.org.xpi
> 1475052587833	addons.xpi	DEBUG	Calling bootstrap method startup on e10srollout@mozilla.org version 1.2
> 1475052587833	addons.xpi	DEBUG	Registering manifest for /usr/lib/firefox/browser/features/firefox@getpocket.com.xpi
> 1475052587834	addons.xpi	DEBUG	Calling bootstrap method startup on firefox@getpocket.com version 1.0.4
> 1475052587835	addons.xpi	DEBUG	Registering manifest for /usr/lib/firefox/browser/features/webcompat@mozilla.org.xpi
> 1475052587835	addons.xpi	DEBUG	Calling bootstrap method startup on webcompat@mozilla.org version 1.0
> 1475052587836	addons.xpi	DEBUG	Registering manifest for /usr/lib/firefox/browser/extensions/langpack-en-ZA@firefox.mozilla.org.xpi
> 1475052587837	addons.xpi	DEBUG	Registering manifest for /usr/lib/firefox/browser/extensions/langpack-en-GB@firefox.mozilla.org.xpi
> 1475052587838	addons.xpi	DEBUG	Registering manifest for /usr/lib/firefox/browser/extensions/langpack-de@firefox.mozilla.org.xpi
> 1475052587840	addons.manager	DEBUG	Registering shutdown blocker for XPIProvider
> 1475052587841	addons.manager	DEBUG	Provider finished startup: XPIProvider
> 1475052587841	addons.manager	DEBUG	Starting provider: LightweightThemeManager
> 1475052587841	addons.manager	DEBUG	Registering shutdown blocker for LightweightThemeManager
> 1475052587841	addons.manager	DEBUG	Provider finished startup: LightweightThemeManager
> 1475052587841	addons.manager	DEBUG	Starting provider: GMPProvider
> 1475052587846	addons.manager	DEBUG	Registering shutdown blocker for GMPProvider
> 1475052587847	addons.manager	DEBUG	Provider finished startup: GMPProvider
> 1475052587847	addons.manager	DEBUG	Starting provider: PluginProvider
> 1475052587847	addons.manager	DEBUG	Registering shutdown blocker for PluginProvider
> 1475052587847	addons.manager	DEBUG	Provider finished startup: PluginProvider
> 1475052587848	addons.manager	DEBUG	Completed startup sequence
> 1475052588185	addons.manager	DEBUG	Starting provider: <unnamed-provider>
> 1475052588185	addons.manager	DEBUG	Registering shutdown blocker for <unnamed-provider>
> 1475052588186	addons.manager	DEBUG	Provider finished startup: <unnamed-provider>
> 1475052588189	DeferredSave.extensions.json	DEBUG	Starting write
> 1475052588271	addons.repository	DEBUG	No addons.json found.
> 1475052588271	DeferredSave.addons.json	DEBUG	Save changes
> 1475052588274	DeferredSave.addons.json	DEBUG	Starting timer
> 1475052588292	addons.manager	DEBUG	Starting provider: PreviousExperimentProvider
> 1475052588292	addons.manager	DEBUG	Registering shutdown blocker for PreviousExperimentProvider
> 1475052588292	addons.manager	DEBUG	Provider finished startup: PreviousExperimentProvider
> 1475052588294	DeferredSave.extensions.json	DEBUG	Write succeeded
> 1475052588294	addons.xpi-utils	DEBUG	XPI Database saved, setting schema version preference to 17
> 1475052588374	DeferredSave.addons.json	DEBUG	Starting write
> 1475052588384	DeferredSave.addons.json	DEBUG	Write succeeded
> 
> 	at org.openqa.selenium.firefox.internal.NewProfileExtensionConnection.start(NewProfileExtensionConnection.java:113)
> 	... 33 common frames omitted
```

**Comment by fhoeben** [comment]
Same problem here on OSX (with FF 49.0.1 and Selenium 2.53.1)

Creating the driver with or without setting desired capability `marionette` to `true` does not seem to make a difference

```
org.openqa.selenium.WebDriverException: Failed to connect to binary FirefoxBinary(/Applications/Firefox.app/Contents/MacOS/firefox-bin) on port 7055; process output follows: 
08198ce6fd}","syncGUID":"0QDmxqABmJ3c","location":"app-global","version":"49.0.1","type":"theme","internalName":"classic/1.0","updateURL":null,"updateKey":null,"optionsURL":null,"optionsType":null,"aboutURL":null,"icons":{"32":"icon.png","48":"icon.png"},"iconURL":null,"icon64URL":null,"defaultLocale":{"name":"Default","description":"The default theme.","creator":"Mozilla","homepageURL":null,"contributors":["Mozilla Contributors"]},"visible":true,"active":true,"userDisabled":false,"appDisabled":false,"descriptor":"/Applications/Firefox.app/Contents/Resources/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}.xpi","installDate":1475265561000,"updateDate":1475265561000,"applyBackgroundUpdates":1,"skinnable":true,"size":7140,"sourceURI":null,"releaseNotesURI":null,"softDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"strictCompatibility":true,"locales":[],"targetApplications":[{"id":"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","minVersion":"49.0.1","maxVersion":"49.0.1"}],"targetPlatforms":[],"seen":true}
1475269566778	addons.xpi	DEBUG	getModTime: Recursive scan of {972ce4c6-7e08-4474-a285-3208198ce6fd}
1475269566779	DeferredSave.extensions.json	DEBUG	Save changes
1475269566779	addons.xpi	DEBUG	Updating database with changes to installed add-ons
1475269566779	addons.xpi-utils	DEBUG	Updating add-on states
1475269566780	addons.xpi-utils	DEBUG	Writing add-ons list
1475269566781	addons.xpi	DEBUG	Registering manifest for /Applications/Firefox.app/Contents/Resources/browser/features/e10srollout@mozilla.org.xpi
1475269566782	addons.xpi	DEBUG	Calling bootstrap method startup on e10srollout@mozilla.org version 1.2
1475269566782	addons.xpi	DEBUG	Registering manifest for /Applications/Firefox.app/Contents/Resources/browser/features/firefox@getpocket.com.xpi
1475269566782	addons.xpi	DEBUG	Calling bootstrap method startup on firefox@getpocket.com version 1.0.4
1475269566783	addons.xpi	DEBUG	Registering manifest for /Applications/Firefox.app/Contents/Resources/browser/features/webcompat@mozilla.org.xpi
1475269566783	addons.xpi	DEBUG	Calling bootstrap method startup on webcompat@mozilla.org version 1.0
1475269566785	addons.manager	DEBUG	Registering shutdown blocker for XPIProvider
1475269566786	addons.manager	DEBUG	Provider finished startup: XPIProvider
1475269566786	addons.manager	DEBUG	Starting provider: LightweightThemeManager
1475269566786	addons.manager	DEBUG	Registering shutdown blocker for LightweightThemeManager
1475269566786	addons.manager	DEBUG	Provider finished startup: LightweightThemeManager
1475269566787	addons.manager	DEBUG	Starting provider: GMPProvider
1475269566795	addons.manager	DEBUG	Registering shutdown blocker for GMPProvider
1475269566795	addons.manager	DEBUG	Provider finished startup: GMPProvider
1475269566795	addons.manager	DEBUG	Starting provider: PluginProvider
1475269566795	addons.manager	DEBUG	Registering shutdown blocker for PluginProvider
1475269566796	addons.manager	DEBUG	Provider finished startup: PluginProvider
1475269566796	addons.manager	DEBUG	Completed startup sequence
1475269567141	addons.manager	DEBUG	Starting provider: <unnamed-provider>
1475269567141	addons.manager	DEBUG	Registering shutdown blocker for <unnamed-provider>
1475269567142	addons.manager	DEBUG	Provider finished startup: <unnamed-provider>
1475269567150	DeferredSave.extensions.json	DEBUG	Starting write
1475269567257	addons.repository	DEBUG	No addons.json found.
1475269567258	DeferredSave.addons.json	DEBUG	Save changes
1475269567266	DeferredSave.addons.json	DEBUG	Starting timer
1475269567323	addons.manager	DEBUG	Starting provider: PreviousExperimentProvider
1475269567323	addons.manager	DEBUG	Registering shutdown blocker for PreviousExperimentProvider
1475269567325	addons.manager	DEBUG	Provider finished startup: PreviousExperimentProvider
1475269567341	DeferredSave.extensions.json	DEBUG	Write succeeded
1475269567341	addons.xpi-utils	DEBUG	XPI Database saved, setting schema version preference to 17
1475269567344	DeferredSave.addons.json	DEBUG	Starting write
1475269567381	DeferredSave.addons.json	DEBUG	Write succeeded

Build info: version: '2.53.1', revision: 'a36b8b1cd5757287168e54b817830adce9b0158d', time: '2016-06-30 19:26:09'
System info: host: 'Frieds-MacBook-Pro.local', ip: '192.168.0.101', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.11.6', java.version: '1.7.0_45'
Driver info: driver.version: FirefoxDriver

	at org.openqa.selenium.firefox.internal.NewProfileExtensionConnection.start(NewProfileExtensionConnection.java:125)
	at org.openqa.selenium.firefox.FirefoxDriver.startClient(FirefoxDriver.java:271)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:119)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:216)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:211)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:128)

```

**Comment by rameshp286** [comment]
Firefox 49 won't support Selenium 2.53. You have to use selenium 3.0 beta for that
