### ISSUE TITLE
Can not disable the firefox untrusted connection warning

### ISSUE THREAD

**Issue by gvasanka** [mozilla/geckodriver#300]
OS:  Ubuntu 14.04
Selenium Version:   3.0.1
Browser:  Firefox 49.0

I was trying to disable the Insecure connection warning with following code block.
`   System.setProperty("webdriver.gecko.driver", "src/main/resources/drivers/gecko/geckodriver");
            ProfilesIni profile = new ProfilesIni();
            FirefoxProfile myprofile = profile.getProfile("myprofile");
            myprofile.setAcceptUntrustedCertificates(true);
            myprofile.setAssumeUntrustedCertificateIssuer(false);
            driver = new FirefoxDriver(myprofile);`

Issue:
Though many online resources suggest above code to disable Firefox insecure connection browser warning, I am getting following error and Web-driver fails to skip the insecure warning.

`V4dGVuc2lvbnMuanNvblBLAQIUABQACAgIAOaBWUmzLG4CYjYAAKlDAAASAAAAAAAAAAAAAAAAAOnSAABzZWFyY2guanNvbi5tb3psejRQSwECFAAUAAgICADmgVlJx1reZptWAAAAAKAADQAAAAAAAAAAAAAAAACLCQEAcGxhY2VzLnNxbGl0ZVBLAQIUABQACAgIAOaBWUnEW4Y/6AEAAABAAAAJAAAAAAAAAAAAAAAAAGFgAQBzZWNtb2QuZGJQSwECFAAUAAgICADmgVlJYPc+xLEEAAAAAAgADgAAAAAAAAAAAAAAAACAYgEAY29va2llcy5zcWxpdGVQSwUGAAAAACEAIQCxCAAAbWcBAAAA}, appBuildId=20160919213721, version=, platform=LINUX, proxy={}, command_id=1, specificationLevel=0, acceptSslCerts=false, processId=22141, browserVersion=49.0, platformVersion=4.4.0-45-generic, XULappId={ec8030f7-c20a-464f-9b0e-13a3a9e97384}, browserName=firefox, takesScreenshot=true, takesElementScreenshot=true, platformName=linux, device=desktop}]
Session ID: c04150fa-a3cc-4228-b191-9a947f46d9f4
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:127)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:93)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:42)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:163)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:82)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:601)
	at org.openqa.selenium.remote.RemoteWebDriver.get(RemoteWebDriver.java:322)
	at org.asanka.automation.ui.pages.BasePage.loadApplication(BasePage.java:41)
	at org.asanka.automation.ui.test.LW.ApplicationLoginTestCase.testApplicationLoad(ApplicationLoginTestCase.java:33)`

**Comment by jgraham** [comment]
https://github.com/mozilla/geckodriver/issues/93
