### ISSUE TITLE
Error: Permission denied to access property "length"

### ISSUE THREAD

**Issue by FranciszekMalcher** [mozilla/geckodriver#302]
Firefox: 47.0.1
geckodriver v0.11.1

When I need to wait for element to be clickable I use explicit wait: 

new WebDriverWait(getDriver(), 2).until(ExpectedConditions.elementToBeClickable(element));

On firefox exception is thrown:

`org.openqa.selenium.JavascriptException: Error: Permission denied to access property "length"
Build info: version: '3.0.0', revision: '350cf60', time: '2016-10-13 10:48:57 -0700'
System info: host: 'LTTW0362', ip: '10.40.131.140', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_101'
Driver info: com.avira.abs.support.FirefoxDriver
Capabilities: Not needed.
Session ID: 204d85f0-e300-4ca4-a9d7-c97dc5443edc
  at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
  at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
  at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
  at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
  at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:127)
  at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:93)
  at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:42)
  at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:163)
  at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:82)
  at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:601)
  at com.avira.abs.support.FirefoxDriver.execute(FirefoxDriver.java:32)
  at org.openqa.selenium.remote.RemoteWebElement.execute(RemoteWebElement.java:274)
  at org.openqa.selenium.remote.RemoteWebElement.isDisplayed(RemoteWebElement.java:315)
  at org.openqa.selenium.support.ui.ExpectedConditions.elementIfVisible(ExpectedConditions.java:302)
  at org.openqa.selenium.support.ui.ExpectedConditions.access$100(ExpectedConditions.java:41)
  at org.openqa.selenium.support.ui.ExpectedConditions$7.apply(ExpectedConditions.java:205)
  at org.openqa.selenium.support.ui.ExpectedConditions$7.apply(ExpectedConditions.java:201)
  at org.openqa.selenium.support.ui.ExpectedConditions$22.apply(ExpectedConditions.java:651)
  at org.openqa.selenium.support.ui.ExpectedConditions$22.apply(ExpectedConditions.java:644)
  at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:238)
  at com.avira.abs.pageObjects.BaseObject.clickElement(BaseObject.java:21)
  at com.avira.abs.pageObjects.PopupObject.openMenu(PopupObject.java:83)
  at com.avira.abs.stepDefinitions.Menu_Steps.theUserClicksTheHelpIcon(Menu_Steps.java:21)
  at ✽.And the user clicks the menu settings

**Comment by andreastt** [comment]
This isn’t reproducible. Closing.
