### ISSUE TITLE
Help i am getting this error when i am trying to run instabrute.py

### ISSUE THREAD

**Issue by damageddomain** [mozilla/geckodriver#303]
Using 1 seconds of delay
Traceback (most recent call last):
  File "instaBrute.py", line 142, in <module>
    main()
  File "instaBrute.py", line 132, in main
    driver = webdriver.Firefox(profile)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/webdriver.py", line 135, in __init__
    self.service.start()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/common/service.py", line 71, in start
    os.path.basename(self.path), self.start_error_message)
selenium.common.exceptions.WebDriverException: Message: 'geckodriver' executable needs to be in PATH. 

Exception AttributeError: "'Service' object has no attribute 'process'" in <bound method Service.__del__ of <selenium.webdriver.firefox.service.Service object at 0x7f6ffe234150>> ignored

**Comment by jgraham** [comment]
I don't know what instrbrute.py is, but if you do indeed have geckodriver on the path, this seems like a selenium issue.
