### ISSUE TITLE
UnknownCommandError for Logs

### ISSUE THREAD

**Issue by gauntface** [mozilla/geckodriver#370]
In selenium-webdriver JavaScript SDK, accessing the logs like so:

    seleniumDriver.manage().logs().get(webdriver.logging.Type.BROWSER);

Results in the following error:

```
UnknownCommandError: POST /session/17726311-462f-4d1e-935b-583fe421090a/log did not match a known command
      at Object.throwDecodedError (node_modules/selenium-webdriver/lib/error.js:477:11)
      at parseHttpResponse (node_modules/selenium-webdriver/lib/http.js:499:15)
      at doSend.then.response (node_modules/selenium-webdriver/lib/http.js:440:13)
      at process._tickCallback (internal/process/next_tick.js:103:7)
  From: Task: WebDriver.manage().logs().get(browser)
      at Driver.schedule (node_modules/selenium-webdriver/lib/webdriver.js:816:17)
      at Logs.get (node_modules/selenium-webdriver/lib/webdriver.js:1642:25)
```

**Comment by jgraham** [comment]
https://github.com/mozilla/geckodriver/issues/284
