### ISSUE TITLE
Error with Selenium + Scrapy+ Pyvirtualdisplay + geckodriver:  connection refused

### ISSUE THREAD

**Issue by lhg912** [mozilla/geckodriver#376]
If you are having an issue with GeckoDriver starting up, please make sure that your client bindings support using it.

* OS: Ubuntu 14.04 (on Cloud9, headless Ubuntu)
* Browser Version:  Firefox 50.0 (headless)
* installed xvfb, PyVirtualDisplay, Selenium(python), Scrapy, geckodriver.
* Selenium version: 3.0.1
* Scrapy versoin: 1.2.1
* geckodriver version: 0.11.1

Hi, I am doing some scraping works, with selenium, scrapy, etc., on Cloud9 environment (Ubuntu 14.04)

```python
import time
import scrapy
from selenium import webdriver

class NTRYSpider(scrapy.Spider):
    name = "ntryspider"
    allowed_domains = ["ntry.com"]
    start_urls = [
        "http://ntry.com/#/scores/named_ladder/main.php"
        ]
                  
    def __init__(self):
        scrapy.Spider.__init__(self)
        self.driver = webdriver.Firefox()
   
    def parse(self, response):
        self.driver.get(response.url)
        time.sleep(5)        
        html = self.browser.find_element_by_xpath('//*').get_attribute('outerHTML')
```

`$scrapy crawl ntryspider`

I expect this code works with my environment, but it raises error.
```
Traceback (most recent call last):
  File "/home/ubuntu/ntry_virtualenv/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1299, in _inlineCallbacks
    result = g.send(result)
  File "/home/ubuntu/ntry_virtualenv/local/lib/python2.7/site-packages/scrapy/crawler.py", line 90, in crawl
    six.reraise(*exc_info)
  File "/home/ubuntu/ntry_virtualenv/local/lib/python2.7/site-packages/scrapy/crawler.py", line 71, in crawl
    self.spider = self._create_spider(*args, **kwargs)
  File "/home/ubuntu/ntry_virtualenv/local/lib/python2.7/site-packages/scrapy/crawler.py", line 94, in _create_spider
    return self.spidercls.from_crawler(self, *args, **kwargs)
  File "/home/ubuntu/ntry_virtualenv/local/lib/python2.7/site-packages/scrapy/spiders/__init__.py", line 50, in from_crawler
    spider = cls(*args, **kwargs)
  File "/home/ubuntu/ntry_virtualenv/ntry_crawler/ntry_crawler/spiders/ntry_spider.py", line 18, in __init__
    self.browser = webdriver.Firefox()
  File "/home/ubuntu/ntry_virtualenv/local/lib/python2.7/site-packages/selenium/webdriver/firefox/webdriver.py", line 145, in __init__
    keep_alive=True)
  File "/home/ubuntu/ntry_virtualenv/local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 92, in __init__
    self.start_session(desired_capabilities, browser_profile)
  File "/home/ubuntu/ntry_virtualenv/local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 179, in start_session
    response = self.execute(Command.NEW_SESSION, capabilities)
  File "/home/ubuntu/ntry_virtualenv/local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/ntry_virtualenv/local/lib/python2.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
**WebDriverException: Message: connection refused**
```

and I suspect this problem is related to geckodriver and firfox webdriver, so checked geckodriver.log.
```
1480838994116	geckodriver	INFO	Listening on 127.0.0.1:46526
1480838995071	mozprofile::profile	INFO	Using profile path /tmp/rust_mozprofile.CY06Hvkcdmcg
1480838995072	geckodriver::marionette	INFO	Starting browser /usr/bin/firefox
1480838995079	geckodriver::marionette	INFO	Connecting to Marionette on localhost:42981
**Error: GDK_BACKEND does not match available displays**
```
I added geckodriver installed path to PATH variable, and
I looked lots of stackoverflow and github issued stuffs, but still this error pops up. 
for next, I am thinking that providing firefox installed binary location to my code may help.

Can Anybody help me?? :pizza:

**Comment by cgoldberg** [comment]
Your code snippet is incomplete... it doesn't show you are using PyVirtualDisplay at all.  This error sounds like you are trying to run headless without invoking xvfb.   You need to either invoke your tests using `xvfb-run` or use the PyVirtualDisplay module to run under xvfb.

btw, this issue has nothing to do with firefox, geckodriver, or selenium, whatsoever.

**Comment by andreastt** [comment]
I think @cgoldberg is correct. Not starting Xvfb(1) would explain why it isn’t connecting to geckodriver.

It would also be useful if you in the future included verbose logging information from geckodriver. You can learn how to enable this from reading the README.
