### ISSUE TITLE
movetoElement action is not working

### ISSUE THREAD

**Issue by pankajgupta007** [mozilla/geckodriver#407]
In order to help us efficiently investigate your issue, please provide the following information:

Windows 10
Firefox 50.1.0
GeckoDriver 0.11.1
Selenium 3.0.1

## Steps to reproduce -
Launch Firefox and try to Mouse hover on the specific link .

**Comment by andreastt** [comment]
The actions API isn’t implemented in geckodriver/Marionette yet. See https://github.com/mozilla/geckodriver/issues/233.

**Comment by vantruongt2** [comment]
Please tell me know that when it will be implemented?

**Comment by andreastt** [comment]
There’s no ETA, but the tracking bug is https://bugzilla.mozilla.org/show_bug.cgi?id=1292178.

**Comment by prasanna532** [comment]
from also same exception

INFO: Detected dialect: W3C
Exception in thread "main" org.openqa.selenium.UnsupportedCommandException: mouseMoveTo
Build info: version: '3.3.1', revision: '5234b32', time: '2017-03-10 09:04:52 -0800'
System info: host: 'DESKTOP-9ISPGDN', ip: '192.168.1.101', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_121'
Driver info: driver.version: RemoteWebDriver
at org.openqa.selenium.remote.http.AbstractHttpCommandCodec.encode(AbstractHttpCommandCodec.java:220)
at org.openqa.selenium.remote.http.AbstractHttpCommandCodec.encode(AbstractHttpCommandCodec.java:118)
at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:157)
at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:82)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:604)
at org.openqa.selenium.remote.RemoteExecuteMethod.execute(RemoteExecuteMethod.java:35)
at org.openqa.selenium.remote.RemoteMouse.mouseMove(RemoteMouse.java:89)
at org.openqa.selenium.interactions.MoveMouseAction.perform(MoveMouseAction.java:43)
at org.openqa.selenium.interactions.CompositeAction.perform(CompositeAction.java:36)
at org.openqa.selenium.interactions.Actions$BuiltAction.perform(Actions.java:637)
