### ISSUE TITLE
Geckodriver not working on Mac OS

### ISSUE THREAD

**Issue by dsb84** [mozilla/geckodriver#419]
Firefox version: 50.1.0
Geckodriver version: 0.12.0
Selenium version: 3.0.1
Mac OS El Capitan version: 10.11.4

I have also tried the previous versions of geckodriver but nothing worked for me.

I am getting the following exception:

```
1483481781959   geckodriver INFO    Listening on 127.0.0.1:10068
Jan 03, 2017 5:16:22 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Attempting bi-dialect session, assuming Postel's Law holds true on the remote end
Jan 03, 2017 5:16:22 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Falling back to original OSS JSON Wire Protocol.
Jan 03, 2017 5:16:22 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Falling back to straight W3C remote end connection
Exception in thread "main" org.openqa.selenium.SessionNotCreatedException: Unable to create new remote session. desired capabilities = Capabilities [{firefoxOptions=org.openqa.selenium.firefox.FirefoxOptions@4f638935, browserName=firefox, moz:firefoxOptions=org.openqa.selenium.firefox.FirefoxOptions@4f638935, version=, platform=ANY}], required capabilities = Capabilities [{}]
Build info: version: '2.42.2', revision: '6a6995d31c7c56c340d6f45a76976d43506cd6cc', time: '2014-06-03 10:52:47'
System info: host: 'xxxxxxx', ip: 'xxxxxxxx', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.11.4', java.version: '1.8.0_102'
Driver info: driver.version: FirefoxDriver
    at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:91)
    at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:141)
    at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:82)
    at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:601)
    at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:241)
    at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:128)
    at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:259)
    at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:247)
    at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:242)
    at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:238)
    at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:127)
    at com.test.extras.GeckoTest.main(GeckoTest.java:22)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
```

**Comment by andreastt** [comment]
“Not working” is a relative term. In the issue template, you were asked to submit a trace-level geckodriver log. Without this, it’s impossible to tell what is wrong. You can enable verbose logging by starting geckodriver with the `-vv` flag, or by passing it the `{"moz:firefoxOptions": {"log": {"level": "trace"}}}` capability. This is also documented in the README.

**Comment by andreastt** [comment]
Happy to re-open this when it is reproducible. (-:

**Comment by denslinsunitha** [comment]
we are using Firefox 53 and selenium 3.3.1 with geckodriver 0.15
In Mac when i run my code the firefox browser is getting launched but after that i am getting below error:
2017-05-26 11:08:36.716 plugin-container[2615:38932] *** CFMessagePort: bootstrap_register(): failed 1100 (0x44c) 'Permission denied', port = 0x8d3f, name = 'com.apple.tsm.portname'
See /usr/include/servers/bootstrap_defs.h for the error codes.
2017-05-26 11:08:36.718 plugin-container[2615:38932] *** CFMessagePort: bootstrap_register(): failed 1100 (0x44c) 'Permission denied', port = 0x451f, name = 'com.apple.CFPasteboardClient'
See /usr/include/servers/bootstrap_defs.h for the error codes.
2017-05-26 11:08:36.718 plugin-container[2615:38932] void __CFPasteboardSetup() : Failed to allocate communication port for com.apple.CFPasteboardClient; this is likely due to sandbox restrictions

Can you please help me in resolving this issue ?

**Comment by andreastt** [comment]
@denslinsunitha You’re using old versions of Firefox, Selenium, _and_ geckodriver. I suggest you upgrade all of them to the latest.

The errors you are seeing are also not something to worry about.
