### ISSUE TITLE
.findElement not working and hence breaks every other script 

### ISSUE THREAD

**Issue by john77eipe** [mozilla/geckodriver#426]
Webdriver.findElement breaks when I try to find any element on the page.

The code works fine in other browsers with the corresponding drivers.
I tried ```dr = new FirefoxDriver()``` but it doesn't even launch the page.

## Firefox Version
50.0.1

## Platform
OSx 

## Steps to reproduce -
This was reproducible using a simple script. 

 - Code used:
```
    WebDriver dr = null;
    System.setProperty(FIREFOX_DRIVER_PROPERTY, context.getFirefoxDriverFilePath());
    dr = new MarionetteDriver();
    dr.manage().deleteAllCookies();
    //followed by
    dr.get("http://www.google.com");
    WebElement element = dr.findElement(By.id(htmlValue));
```

 - Trace logs:
```
1483811686551	geckodriver	INFO	Listening on 127.0.0.1:37550
1483811687279	mozprofile::profile	INFO	Using profile path /var/folders/pb/bg383jf90b5dmndzwlp3mcq0sddwd0/T/rust_mozprofile.v87VpqW7cD21
1483811687281	geckodriver::marionette	INFO	Starting browser /Applications/Firefox.app/Contents/MacOS/firefox-bin
1483811687284	geckodriver::marionette	INFO	Connecting to Marionette on localhost:64919
1483811687819	Marionette	INFO	Listening on port 64919
Jan 07, 2017 11:25:32 PM org.openqa.selenium.support.ui.ExpectedConditions findElement
WARNING: WebDriverException thrown by findElement(By.cssSelector: .gsfi)
org.openqa.selenium.WebDriverException: Returned value cannot be converted to WebElement: {element-6066-11e4-a52e-4f735466cecf=8066f37b-7b52-f84d-b1fa-22d306c38a38}
Build info: version: '2.45.0', revision: '5017cb8', time: '2015-02-27 00:00:10'
System info: host: 'JohnEmacbookpro.local', ip: '192.168.137.1', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.11.6', java.version: '1.8.0_60'
Driver info: driver.version: RemoteWebDriver
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:359)
	at org.openqa.selenium.remote.RemoteWebDriver.findElementByCssSelector(RemoteWebDriver.java:441)
	at org.openqa.selenium.By$ByCssSelector.findElement(By.java:426)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:344)
	at org.openqa.selenium.support.ui.ExpectedConditions.findElement(ExpectedConditions.java:730)
	at org.openqa.selenium.support.ui.ExpectedConditions.access$0(ExpectedConditions.java:728)
	at org.openqa.selenium.support.ui.ExpectedConditions$3.apply(ExpectedConditions.java:106)
	at org.openqa.selenium.support.ui.ExpectedConditions$3.apply(ExpectedConditions.java:1)
	at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:208)
	at .........
Caused by: java.lang.ClassCastException: com.google.common.collect.Maps$TransformedEntriesMap cannot be cast to org.openqa.selenium.WebElement
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:357)
	... 19 more
```

If I use the FirefoxDriver() class then firefox launches but nothing happens after that.

- Trace logs:
```
org.openqa.selenium.firefox.NotConnectedException: Unable to connect to host 127.0.0.1 on port 7055 after 45000 ms. Firefox console output:
xpi","e":true,"v":"1.5","st":1483810103000},"firefox@getpocket.com":{"d":"/Applications/Firefox.app/Contents/Resources/browser/features/firefox@getpocket.com.xpi","e":true,"v":"1.0.5","st":1483810103000},"webcompat@mozilla.org":{"d":"/Applications/Firefox.app/Contents/Resources/browser/features/webcompat@mozilla.org.xpi","e":true,"v":"1.0","st":1483810103000}},"app-global":{"{972ce4c6-7e08-4474-a285-3208198ce6fd}":{"d":"/Applications/Firefox.app/Contents/Resources/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}.xpi","e":true,"v":"50.1.0","st":1483810103000}}}
1483813272601	addons.xpi	DEBUG	No changes found
1483813272607	addons.xpi	DEBUG	Registering manifest for /Applications/Firefox.app/Contents/Resources/browser/features/aushelper@mozilla.org.xpi
1483813272608	addons.xpi	DEBUG	Loading bootstrap scope from /Applications/Firefox.app/Contents/Resources/browser/features/aushelper@mozilla.org.xpi
1483813272612	addons.xpi	DEBUG	Calling bootstrap method startup on aushelper@mozilla.org version 1.0
1483813272612	addons.xpi	DEBUG	Registering manifest for /Applications/Firefox.app/Contents/Resources/browser/features/e10srollout@mozilla.org.xpi
1483813272612	addons.xpi	DEBUG	Loading bootstrap scope from /Applications/Firefox.app/Contents/Resources/browser/features/e10srollout@mozilla.org.xpi
1483813272621	addons.xpi	DEBUG	Calling bootstrap method startup on e10srollout@mozilla.org version 1.5
1483813272622	addons.xpi	DEBUG	Registering manifest for /Applications/Firefox.app/Contents/Resources/browser/features/firefox@getpocket.com.xpi
1483813272622	addons.xpi	DEBUG	Loading bootstrap scope from /Applications/Firefox.app/Contents/Resources/browser/features/firefox@getpocket.com.xpi
1483813272625	addons.xpi	DEBUG	Calling bootstrap method startup on firefox@getpocket.com version 1.0.5
1483813272631	addons.xpi-utils	DEBUG	Starting async load of XPI database /var/folders/pb/bg383jf90b5dmndzwlp3mcq0sddwd0/T/anonymous670020922414797208webdriver-profile/extensions.json
1483813272632	addons.xpi	DEBUG	Registering manifest for /Applications/Firefox.app/Contents/Resources/browser/features/webcompat@mozilla.org.xpi
1483813272632	addons.xpi	DEBUG	Loading bootstrap scope from /Applications/Firefox.app/Contents/Resources/browser/features/webcompat@mozilla.org.xpi
1483813272634	addons.xpi	DEBUG	Calling bootstrap method startup on webcompat@mozilla.org version 1.0
1483813272635	addons.manager	DEBUG	Registering shutdown blocker for XPIProvider
1483813272636	addons.manager	DEBUG	Provider finished startup: XPIProvider
1483813272636	addons.manager	DEBUG	Starting provider: LightweightThemeManager
1483813272636	addons.manager	DEBUG	Registering shutdown blocker for LightweightThemeManager
1483813272636	addons.manager	DEBUG	Provider finished startup: LightweightThemeManager
1483813272636	addons.manager	DEBUG	Starting provider: GMPProvider
1483813272644	addons.manager	DEBUG	Registering shutdown blocker for GMPProvider
1483813272644	addons.manager	DEBUG	Provider finished startup: GMPProvider
1483813272644	addons.manager	DEBUG	Starting provider: PluginProvider
1483813272644	addons.manager	DEBUG	Registering shutdown blocker for PluginProvider
1483813272645	addons.manager	DEBUG	Provider finished startup: PluginProvider
1483813272645	addons.manager	DEBUG	Completed startup sequence
1483813272887	addons.xpi-utils	DEBUG	Async JSON file read took 0 MS
1483813272887	addons.xpi-utils	DEBUG	Finished async read of XPI database, parsing...
1483813272889	addons.xpi-utils	DEBUG	Successfully read XPI database
1483813272901	addons.manager	DEBUG	Starting provider: <unnamed-provider>
1483813272901	addons.manager	DEBUG	Registering shutdown blocker for <unnamed-provider>
1483813272901	addons.manager	DEBUG	Provider finished startup: <unnamed-provider>
*** Blocklist::_loadBlocklistFromFile: blocklist is disabled
1483813273038	addons.manager	DEBUG	Starting provider: PreviousExperimentProvider
1483813273038	addons.manager	DEBUG	Registering shutdown blocker for PreviousExperimentProvider
1483813273038	addons.manager	DEBUG	Provider finished startup: PreviousExperimentProvider

	at org.openqa.selenium.firefox.internal.NewProfileExtensionConnection.start(NewProfileExtensionConnection.java:118)
	at org.openqa.selenium.firefox.FirefoxDriver.startClient(FirefoxDriver.java:246)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:114)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:193)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:186)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:182)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:99)

```

**Comment by andreastt** [comment]
Without a more detailed geckodriver log, I would say this looks like a Selenium issue. If you could attach the trace-level verbosity log from geckodriver, I could tell for certain.

**Comment by AutomatedTester** [comment]
Closing as no more detail has been added since the request
