### ISSUE TITLE
Getting error when going to logical url (Selenium::WebDriver::Error::TimeOutError)

### ISSUE THREAD

**Issue by vveliev** [mozilla/geckodriver#439]
Getting timeout error when trying to go by URL 

## Firefox Version
49.0.1

## Platform
Linux

## Steps to reproduce 
Try to navigate to the logical page
Ex.
https://test.com - > https://test.com/product

## Log
```
15:18:30.182 INFO - Executing: [find element: By.id: user_account])
15:18:31.520 INFO - Done: [find element: By.id: user_account]
15:18:31.531 INFO - Executing: [execute script: return UCP.active(), []])
15:18:31.539 INFO - Done: [execute script: return UCP.active(), []]
15:18:31.553 INFO - Executing: [get: https://ucp-web01.qas.internal.company.com/#!/product])
JavaScript error: https://ucp-web01.qas.internal.company.com/#!, line 436: TypeError: this.element is null

(firefox:29082): GLib-GObject-CRITICAL **: g_type_add_interface_static: assertion 'g_type_parent (interface_type) == G_TYPE_INTERFACE' failed

(firefox:29082): GLib-GObject-CRITICAL **: g_type_add_interface_static: assertion 'g_type_parent (interface_type) == G_TYPE_INTERFACE' failed
JavaScript error: chrome://marionette/content/proxy.js, line 187: NS_ERROR_ILLEGAL_VALUE: Component returned failure code: 0x80070057 (NS_ERROR_ILLEGAL_VALUE) [nsIMessageSender.sendAsyncMessage]
15:19:02.144 WARN - Exception thrown
org.openqa.selenium.TimeoutException: Error loading page, timed out (onDOMContentLoaded)
Build info: version: '3.0.1', revision: '1969d75', time: '2016-10-18 09:48:19 -0700'
System info: host: 'vagif-SYS-5038A-IL', ip: '127.0.0.1', os.name: 'Linux', os.arch: 'amd64', os.version: '3.13.0-37-generic', java.version: '1.8.0_101'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{raisesAccessibilityExceptions=false, AcceptSslCertificates=true, appBuildId=20160922113459, platform=LINUX, accept_ssl_certs=true, specificationLevel=0, acceptSslCerts=false, processId=29082, browserVersion=49.0.1, platformVersion=3.13.0-37-generic, XULappId={ec8030f7-c20a-464f-9b0e-13a3a9e97384}, browserName=firefox, takesScreenshot=true, javascriptEnabled=true, platformName=linux, rotatable=false, profile={zip=UEsDBBQAAAAIAEiiM0qaJT3SlAMAADgNAAAHAAAAdXNlci5qc6VWTW/cNhC991cEPiVATayd5tKeXMcFCgRxkYWRI0GRoxW9FMmQw5X333corWI1lqh1c1tq3+N8v2GKELgPUL+9qILr6MSUa1mnrXIdU6n1DKyoDKiLX99gSPDuj1/SS44RCCEkOwHXwsQFtIUORcVSMIS7EJVL+HtlhN1flPBe7OC8+yOKgMmzzCDkpoxqXAsn5Bm+/Mji7kCRawWsjehsf4veWRdg4QL6pO7t1z7B8WrDtMXgHr58KpvPRWnFE5dNIMM8yqA9cso4R91mo+8384TzkAG8C8iFMfwxcniS4FE7G2eL/igOYriWuQHGYuO6v+0t/XQGZkkv8taBkTmU1S4oMZlQSmcXxMolHVQqaCoVFzIHxxOlPUUExSUEnA90QooxZYvfSZo+QCjOhCcqjUV/1HZHc2WRIK4l685ysPjKC0RC1ydjliW8Z8krIvTA+QmZgM6aJKWjN+II6u5qs/3sUMtc3d8WwK6zxglFfWepTqHviq8N2G12miIo27p7+HTDxmkqJqZHvmdDJdeUSds9tSlQwp8o4UOjXK9hSXEGCVwGu7omPJRjCiBUzgwgSPL0Lx0i3lAu5MKUfFcZUT/X/TzNmzJaYToRzlVLEEE2p7ZYg5o6Jp+1YlTvJZmEGLMyIAkhZaGfnpp6n8sgYrNipQFjmGxA7j9CLZLBP4d/yjRaEZFR2Pbe3hoXV0KZoO+p4vNgyogYpDFntQFhsBnOFGA40DSUU1zgJ59H5e5/skfrdW6oL+n17hu32+WPcpDsV/jhndHyyPLHbapa3df5Z/n/9B9vngd67ho4oHMmMlIIF06OF18nebORgmUA78dapUAu8Jz5eRtZI2zfuL2IfhzIW0nsvCKuNovwyji5NzpiuSMmjL7Bb2kdCNSVNhqPzOpdg+a4Sh2rVwp+Aj9H8V/CLcl9fXxYnLvJM6DkhwXsXNiflsLlSTYvaZFhivM3j5QGkR5xjY7N8TL/7WkNXxqwO8wKcv3hw39p49W05Kh8xriOV0euBgmZ9W3YxjGLAW+dEqacowiSGojqJOP4LF4B1toA/WIuaCoYH3o/v8FW8BGDlvRM+IE2Zyo/Ni1JbAttBWHbHxfymsdnr5Gd8juu6dOIzGZopCAYsoDhyIac9Sm6XsMWs/kSHuCxX5Oznjx5TeuEyspyyNQ8tFWI8S3psGThmdI1mszk6Swznl98g+ucDNGRw4Gea9Os/gtQSwECNAMUAAAACABIojNKmiU90pQDAAA4DQAABwAAAAAAAAABAAAApIEAAAAAdXNlci5qc1BLBQYAAAAAAQABADUAAAC5AwAAAAA=}, firefoxOptions={args=[], profile=UEsDBBQACAgIAEh6M0oAAAAAAAAAAAAAAAAHAAAAdXNlci5qc51WTW/bMAy971cMOW3AKqTretlOXdcBA4Z1aFDsKMgSbauRJU0fcfPvR/mjSRNHbndKbJMS+fj4yOjBUeugfLconGnxiXhWQvdf6oo0TLXMAQHNCgVi8eFtyZSH91/exJ2nYAFtrHEhudTAVKj7Z4JGG8ln/DWE1rg1qUOwxNbS19uz9Nky788U6CrU6Pjx8vK52xiwAybwR0AAHkB8l86HK4yFK0C34OJhuKbBvB4pr51pgHrupA3URU2DbJLLxXL6osAKTxAOfauvlfEwnc1oLUyrlWEC79KsSsDWpv1Tg14hWgmpaXeLQdng02W0MYKpGexhE4xRnoBzxnGjvVH7cB+n72WljUbUGmgKcKvu0edz8eC9RKtgkAsOfETcSgyUcsd8nfdVUq+JsaApPAZwmqlUzFczqExlvYt6+rIWCuHkBp8Z54DljBoz90gHysEFP4nEU6Wkt4ptQdycL1e/DDInlfbTtDG+Erf6j9RYX3++JBIvMvd3P9FjwQoTw+dCMb1eHHOuT4gypeiDRzBSnLKH/ji2RysRbrQlbS0DKOkDHvA3SneKCYkGaxnI0E0j6zC5xIUsAIphYbAB8lTzibfRkhq7xuLZtAXFUwdFl0q6OEg5VVt3rCHRYoGBaIS23N6jyat1JNrUSjfZ8IBHJ8MWmaIA/xEfnOSBGicrqak1SvJtnqoaWmw7MuSTqeazQPuTSXq5ikUju1b53b286sj4Mt2cPCab8VN3DoVJRUHLE+q160NMs+34e9yIpizRDs6YtZ4g+0xLiy0VULKowrScjLBzbwf+TEd7zIcs20Y6I/dRqYLbkl4ZO/uPc7bZo0dEbu5/XpELwnZFOk7vgW1YPyGyonpYirFH8jw6jtvBQzfEspf0NE3H5/PcQ5zFYL71SrDiSIIkOufLUxran0o1C/hIYQN6RkH3JuMtMmw2nEIZvu407UWF8sAcrwfazE3dhvTkJiI2Nls0JPmLqPiMLwYBclJMC+qRBh2Kz8X05tOL9dnYfciiEGdG8mB7QlmGFWd+t9kbnL4b67vBiQoUO6nOIpeYNR3EXuuYftJ1K9APfd1vKSeXs2Fk0U6sBMKoK5rkf4YkNeC05DXw9bder772X14/zQgTQqaI2cwgmNyZ/3dXVqaq0sthictK/14vdRlfozRitxZSJfZpWdVBnRh2e67jjf+jbHRsBNLgWtgRcZFWSQcHGO02mbR5IrFxf5xZZXZ9r0ofbb8B7JaMf1BLBwh1hce1pQMAALUMAABQSwECFAAUAAgICABIejNKdYXHtaUDAAC1DAAABwAAAAAAAAAAAAAAAAAAAAAAdXNlci5qc1BLBQYAAAAAAQABADUAAADaAwAAAAA=}, version=, proxy={}, command_id=1, nativeEvents=true, elementScrollBehavior=1, takesElementScreenshot=true, device=desktop, cssSelectorsEnabled=true}]
Session ID: ede8d52b-6fdd-461e-8fda-47b5ed68e309
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:127)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:93)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:42)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:163)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:82)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:601)
	at org.openqa.selenium.remote.RemoteWebDriver.get(RemoteWebDriver.java:322)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.openqa.selenium.support.events.EventFiringWebDriver$2.invoke(EventFiringWebDriver.java:103)
	at com.sun.proxy.$Proxy6.get(Unknown Source)
	at org.openqa.selenium.support.events.EventFiringWebDriver.get(EventFiringWebDriver.java:162)
	at org.openqa.selenium.remote.server.handler.ChangeUrl.call(ChangeUrl.java:40)
	at org.openqa.selenium.remote.server.handler.ChangeUrl.call(ChangeUrl.java:25)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at org.openqa.selenium.remote.server.DefaultSession$1.run(DefaultSession.java:176)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
15:19:02.146 WARN - Exception: Error loading page, timed out (onDOMContentLoaded)
Build info: version: '3.0.1', revision: '1969d75', time: '2016-10-18 09:48:19 -0700'
System info: host: 'vagif-SYS-5038A-IL', ip: '127.0.0.1', os.name: 'Linux', os.arch: 'amd64', os.version: '3.13.0-37-generic', java.version: '1.8.0_101'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{raisesAccessibilityExceptions=false, AcceptSslCertificates=true, appBuildId=20160922113459, platform=LINUX, accept_ssl_certs=true, specificationLevel=0, acceptSslCerts=false, processId=29082, browserVersion=49.0.1, platformVersion=3.13.0-37-generic, XULappId={ec8030f7-c20a-464f-9b0e-13a3a9e97384}, browserName=firefox, takesScreenshot=true, javascriptEnabled=true, platformName=linux, rotatable=false, profile={zip=UEsDBBQAAAAIAEiiM0qaJT3SlAMAADgNAAAHAAAAdXNlci5qc6VWTW/cNhC991cEPiVATayd5tKeXMcFCgRxkYWRI0GRoxW9FMmQw5X333corWI1lqh1c1tq3+N8v2GKELgPUL+9qILr6MSUa1mnrXIdU6n1DKyoDKiLX99gSPDuj1/SS44RCCEkOwHXwsQFtIUORcVSMIS7EJVL+HtlhN1flPBe7OC8+yOKgMmzzCDkpoxqXAsn5Bm+/Mji7kCRawWsjehsf4veWRdg4QL6pO7t1z7B8WrDtMXgHr58KpvPRWnFE5dNIMM8yqA9cso4R91mo+8384TzkAG8C8iFMfwxcniS4FE7G2eL/igOYriWuQHGYuO6v+0t/XQGZkkv8taBkTmU1S4oMZlQSmcXxMolHVQqaCoVFzIHxxOlPUUExSUEnA90QooxZYvfSZo+QCjOhCcqjUV/1HZHc2WRIK4l685ysPjKC0RC1ydjliW8Z8krIvTA+QmZgM6aJKWjN+II6u5qs/3sUMtc3d8WwK6zxglFfWepTqHviq8N2G12miIo27p7+HTDxmkqJqZHvmdDJdeUSds9tSlQwp8o4UOjXK9hSXEGCVwGu7omPJRjCiBUzgwgSPL0Lx0i3lAu5MKUfFcZUT/X/TzNmzJaYToRzlVLEEE2p7ZYg5o6Jp+1YlTvJZmEGLMyIAkhZaGfnpp6n8sgYrNipQFjmGxA7j9CLZLBP4d/yjRaEZFR2Pbe3hoXV0KZoO+p4vNgyogYpDFntQFhsBnOFGA40DSUU1zgJ59H5e5/skfrdW6oL+n17hu32+WPcpDsV/jhndHyyPLHbapa3df5Z/n/9B9vngd67ho4oHMmMlIIF06OF18nebORgmUA78dapUAu8Jz5eRtZI2zfuL2IfhzIW0nsvCKuNovwyji5NzpiuSMmjL7Bb2kdCNSVNhqPzOpdg+a4Sh2rVwp+Aj9H8V/CLcl9fXxYnLvJM6DkhwXsXNiflsLlSTYvaZFhivM3j5QGkR5xjY7N8TL/7WkNXxqwO8wKcv3hw39p49W05Kh8xriOV0euBgmZ9W3YxjGLAW+dEqacowiSGojqJOP4LF4B1toA/WIuaCoYH3o/v8FW8BGDlvRM+IE2Zyo/Ni1JbAttBWHbHxfymsdnr5Gd8juu6dOIzGZopCAYsoDhyIac9Sm6XsMWs/kSHuCxX5Oznjx5TeuEyspyyNQ8tFWI8S3psGThmdI1mszk6Swznl98g+ucDNGRw4Gea9Os/gtQSwECNAMUAAAACABIojNKmiU90pQDAAA4DQAABwAAAAAAAAABAAAApIEAAAAAdXNlci5qc1BLBQYAAAAAAQABADUAAAC5AwAAAAA=}, firefoxOptions={args=[], profile=UEsDBBQACAgIAEh6M0oAAAAAAAAAAAAAAAAHAAAAdXNlci5qc51WTW/bMAy971cMOW3AKqTretlOXdcBA4Z1aFDsKMgSbauRJU0fcfPvR/mjSRNHbndKbJMS+fj4yOjBUeugfLconGnxiXhWQvdf6oo0TLXMAQHNCgVi8eFtyZSH91/exJ2nYAFtrHEhudTAVKj7Z4JGG8ln/DWE1rg1qUOwxNbS19uz9Nky788U6CrU6Pjx8vK52xiwAybwR0AAHkB8l86HK4yFK0C34OJhuKbBvB4pr51pgHrupA3URU2DbJLLxXL6osAKTxAOfauvlfEwnc1oLUyrlWEC79KsSsDWpv1Tg14hWgmpaXeLQdng02W0MYKpGexhE4xRnoBzxnGjvVH7cB+n72WljUbUGmgKcKvu0edz8eC9RKtgkAsOfETcSgyUcsd8nfdVUq+JsaApPAZwmqlUzFczqExlvYt6+rIWCuHkBp8Z54DljBoz90gHysEFP4nEU6Wkt4ptQdycL1e/DDInlfbTtDG+Erf6j9RYX3++JBIvMvd3P9FjwQoTw+dCMb1eHHOuT4gypeiDRzBSnLKH/ji2RysRbrQlbS0DKOkDHvA3SneKCYkGaxnI0E0j6zC5xIUsAIphYbAB8lTzibfRkhq7xuLZtAXFUwdFl0q6OEg5VVt3rCHRYoGBaIS23N6jyat1JNrUSjfZ8IBHJ8MWmaIA/xEfnOSBGicrqak1SvJtnqoaWmw7MuSTqeazQPuTSXq5ikUju1b53b286sj4Mt2cPCab8VN3DoVJRUHLE+q160NMs+34e9yIpizRDs6YtZ4g+0xLiy0VULKowrScjLBzbwf+TEd7zIcs20Y6I/dRqYLbkl4ZO/uPc7bZo0dEbu5/XpELwnZFOk7vgW1YPyGyonpYirFH8jw6jtvBQzfEspf0NE3H5/PcQ5zFYL71SrDiSIIkOufLUxran0o1C/hIYQN6RkH3JuMtMmw2nEIZvu407UWF8sAcrwfazE3dhvTkJiI2Nls0JPmLqPiMLwYBclJMC+qRBh2Kz8X05tOL9dnYfciiEGdG8mB7QlmGFWd+t9kbnL4b67vBiQoUO6nOIpeYNR3EXuuYftJ1K9APfd1vKSeXs2Fk0U6sBMKoK5rkf4YkNeC05DXw9bder772X14/zQgTQqaI2cwgmNyZ/3dXVqaq0sthictK/14vdRlfozRitxZSJfZpWdVBnRh2e67jjf+jbHRsBNLgWtgRcZFWSQcHGO02mbR5IrFxf5xZZXZ9r0ofbb8B7JaMf1BLBwh1hce1pQMAALUMAABQSwECFAAUAAgICABIejNKdYXHtaUDAAC1DAAABwAAAAAAAAAAAAAAAAAAAAAAdXNlci5qc1BLBQYAAAAAAQABADUAAADaAwAAAAA=}, version=, proxy={}, command_id=1, nativeEvents=true, elementScrollBehavior=1, takesElementScreenshot=true, device=desktop, cssSelectorsEnabled=true}]
Session ID: ede8d52b-6fdd-461e-8fda-47b5ed68e309
1484857158834	addons.productaddons	INFO	sending request to: https://aus5.mozilla.org/update/3/GMP/49.0.1/20160922113459/Linux_x86_64-gcc3/en-US/release/Linux%203.13.0-37-generic%20(GTK%203.10.8%2Clibpulse%204.0.0)/default/default/update.xml
1484857164131	addons.productaddons	INFO	Completed downloading document
1484857164521	addons.productaddons	INFO	downloadXHR File download. status=200
1484857164527	addons.productaddons	INFO	Downloaded file will be saved to /tmp/tmpaddon
1484857698099	addons.manager	INFO	Skipping background update check

```

**Comment by andreastt** [comment]
It’s usually not a good idea to report bugs on old software. When making an issue report, you as an issue-filer should make an effort to not waste the author’s time by making sure you’re reporting a genuine bug.

Is http://test.com/ the actual URL you’re navigating to? Your stack trace contains traces of other unrelated commands. You’re using an outdated Firefox. You haven’t included a Gecko trace-level log which you were asked for in the issue template.

**Comment by vveliev** [comment]
Thanks for the feedback,  it's me first bug report,  for geckodriver will check with latest stable version of Firefox. 

And no test.com is not the actual domain,  but I don't see how it makes any difference if you cannot access it regardless 

Thank again
