### ISSUE TITLE
pageLoadTimeout not supporting negative values throws InvalidArgumentException

### ISSUE THREAD

**Issue by phystem** [mozilla/geckodriver#467]
As per [WebDriver pageLoadTimeout](https://seleniumhq.github.io/selenium/docs/api/java/org/openqa/selenium/WebDriver.Timeouts.html#pageLoadTimeout-long-java.util.concurrent.TimeUnit-)

> If the timeout is negative, page loads can be indefinite.

` driver.manage().timeouts().pageLoadTimeout(-1, TimeUnit.SECONDS);`

The above code is working fine in **ChromeDriver** and **InternetExplorerDriver**, where as in GeckoDriver it is throwing InvalidArgumentException

## Firefox Version
52.0b5 32bit

## GeckoDriver Version
0.14

## Platform
Windows 7

## Steps to reproduce -
Please provide a description of how to reproduce the problem, including the following essential elements:

 - [x] Create WebDriver. Set **pageLoadTimeout** to any **negative** value
        ` driver.manage().timeouts().pageLoadTimeout(-1, TimeUnit.SECONDS);`

 - [x] Log Trace
```
1486970585481	Marionette	WARN	Using deprecated data structure for setting timeouts
2017-02-13 12:53:05:02S +0530 [SEVERE] com.x.TestCaseRunner onError:org.openqa.selenium.InvalidArgumentException: Expected [object Number] -1000 to be >= 0
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: host: 'PC339515', ip: '10.219.69.176', os.name: 'Windows 7', os.arch: 'x86', os.version: '6.1', java.version: '1.8.0_121'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{moz:profile=C:\Users\525372\AppData\Local\Temp\rust_mozprofile.4kZrBdwbkESh, rotatable=false, timeouts={implicit=0, page load=300000, script=30000}, pageLoadStrategy=normal, platform=ANY, specificationLevel=0, moz:accessibilityChecks=false, acceptInsecureCerts=true, browserVersion=52.0, platformVersion=6.1, moz:processID=8296, browserName=firefox, platformName=windows_nt}]
Session ID: 30ad5c42-cd42-4949-9828-95cd7deef3f3
org.openqa.selenium.InvalidArgumentException: Expected [object Number] -1000 to be >= 0
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: host: 'PC339515', ip: '10.219.69.176', os.name: 'Windows 7', os.arch: 'x86', os.version: '6.1', java.version: '1.8.0_121'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{moz:profile=C:\Users\525372\AppData\Local\Temp\rust_mozprofile.4kZrBdwbkESh, rotatable=false, timeouts={implicit=0, page load=300000, script=30000}, pageLoadStrategy=normal, platform=ANY, specificationLevel=0, moz:accessibilityChecks=false, acceptInsecureCerts=true, browserVersion=52.0, platformVersion=6.1, moz:processID=8296, browserName=firefox, platformName=windows_nt}]
Session ID: 30ad5c42-cd42-4949-9828-95cd7deef3f3
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:127)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:93)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:42)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:163)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:82)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:601)
	at org.openqa.selenium.remote.RemoteWebDriver$RemoteWebDriverOptions$RemoteTimeouts.pageLoadTimeout(RemoteWebDriver.java:836)
```

**Comment by Elmue** [comment]
Why should Selenium allow to set a negative timeout? What a nonsense!

**Comment by jgraham** [comment]
The behaviour we have is per-spec. I was under the impression that `timeout=0` was supposed to mean "infintite timeout" but I can't see that in the spec right now. I'll raise a spec issue.

**Comment by andreastt** [comment]
A negative timeout doesn’t make any sense. The number provided should be an unsigned 64-bit integer.
