### ISSUE TITLE
[GFX1]: Unknown image format 16

### ISSUE THREAD

**Issue by ArmandsBruns** [mozilla/geckodriver#477]
Hi,

I'm running my tests via Jenkins on Ubunt server 16.04 without GUI only CLI.
Google chrome tests successfully executed but on firefox I got the following error '[GFX1]: Unknown image format 16':

### Firefox Version
51.0.1+build2-0ubuntu0.16.04.2 500
### Platform
Linux
### Selenium Version: 
3.0.1
### geckodriver:
v0.14.0-linux64
### Jenkins ver:
 2.45

## Log:
```
Test case = ApplicationTableTempl
browserName = firefox
Excel path - /usr/share/GlobalStagingERP/global.staging.erp/ApplicationTestData/GLOBAL_Test_Data.xlsx
Browser - firefox
1487255036037	geckodriver	INFO	Listening on 127.0.0.1:7437
Feb 16, 2017 4:23:56 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Attempting bi-dialect session, assuming Postel's Law holds true on the remote end
1487255036229	mozprofile::profile	INFO	Using profile path /tmp/rust_mozprofile.QNATBgYwq02N
1487255036243	geckodriver::marionette	INFO	Starting browser /opt/firefox/firefox-bin
1487255036254	geckodriver::marionette	INFO	Connecting to Marionette on localhost:45271
1487255036538	addons.manager	DEBUG	Application has been upgraded
1487255036559	addons.manager	DEBUG	Loaded provider scope for resource://gre/modules/addons/XPIProvider.jsm: ["XPIProvider"]
1487255036562	addons.manager	DEBUG	Loaded provider scope for resource://gre/modules/LightweightThemeManager.jsm: ["LightweightThemeManager"]
1487255036568	addons.manager	DEBUG	Loaded provider scope for resource://gre/modules/addons/GMPProvider.jsm
1487255036571	addons.manager	DEBUG	Loaded provider scope for resource://gre/modules/addons/PluginProvider.jsm
1487255036573	addons.manager	DEBUG	Starting provider: XPIProvider
1487255036573	addons.xpi	DEBUG	startup
1487255036574	addons.xpi	INFO	SystemAddonInstallLocation directory is missing
1487255036575	addons.xpi	INFO	Mapping firefox@getpocket.com to /opt/firefox/browser/features/firefox@getpocket.com.xpi
1487255036576	addons.xpi	INFO	Mapping aushelper@mozilla.org to /opt/firefox/browser/features/aushelper@mozilla.org.xpi
1487255036576	addons.xpi	INFO	Mapping webcompat@mozilla.org to /opt/firefox/browser/features/webcompat@mozilla.org.xpi
1487255036577	addons.xpi	INFO	Mapping e10srollout@mozilla.org to /opt/firefox/browser/features/e10srollout@mozilla.org.xpi
1487255036578	addons.xpi	INFO	Mapping {972ce4c6-7e08-4474-a285-3208198ce6fd} to /opt/firefox/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}.xpi
1487255036578	addons.xpi	DEBUG	checkForChanges
1487255036579	addons.xpi	DEBUG	Loaded add-on state from prefs: {}
1487255036580	addons.xpi	DEBUG	New add-on firefox@getpocket.com in app-system-defaults
1487255036582	addons.xpi	DEBUG	getModTime: Recursive scan of firefox@getpocket.com
1487255036583	addons.xpi	DEBUG	New add-on aushelper@mozilla.org in app-system-defaults
1487255036584	addons.xpi	DEBUG	getModTime: Recursive scan of aushelper@mozilla.org
1487255036584	addons.xpi	DEBUG	New add-on webcompat@mozilla.org in app-system-defaults
1487255036585	addons.xpi	DEBUG	getModTime: Recursive scan of webcompat@mozilla.org
1487255036586	addons.xpi	DEBUG	New add-on e10srollout@mozilla.org in app-system-defaults
1487255036589	addons.xpi	DEBUG	getModTime: Recursive scan of e10srollout@mozilla.org
1487255036595	addons.xpi	DEBUG	New add-on {972ce4c6-7e08-4474-a285-3208198ce6fd} in app-global
1487255036596	addons.xpi	DEBUG	getModTime: Recursive scan of {972ce4c6-7e08-4474-a285-3208198ce6fd}
1487255036598	addons.xpi	DEBUG	getInstallState changed: true, state: {"app-system-defaults":{"firefox@getpocket.com":{"d":"/opt/firefox/browser/features/firefox@getpocket.com.xpi","st":1478328701000},"aushelper@mozilla.org":{"d":"/opt/firefox/browser/features/aushelper@mozilla.org.xpi","st":1478328701000},"webcompat@mozilla.org":{"d":"/opt/firefox/browser/features/webcompat@mozilla.org.xpi","st":1478328701000},"e10srollout@mozilla.org":{"d":"/opt/firefox/browser/features/e10srollout@mozilla.org.xpi","st":1478328701000}},"app-global":{"{972ce4c6-7e08-4474-a285-3208198ce6fd}":{"d":"/opt/firefox/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}.xpi","st":1478328701000}}}
1487255036617	addons.xpi-utils	DEBUG	Opening XPI database /tmp/rust_mozprofile.QNATBgYwq02N/extensions.json
1487255036619	addons.xpi-utils	DEBUG	New add-on firefox@getpocket.com installed in app-system-defaults
*** Blocklist::_loadBlocklistFromFile: blocklist is disabled
1487255036632	DeferredSave.extensions.json	DEBUG	Save changes
1487255036632	addons.xpi-utils	DEBUG	New add-on aushelper@mozilla.org installed in app-system-defaults
1487255036635	DeferredSave.extensions.json	DEBUG	Starting timer
1487255036637	DeferredSave.extensions.json	DEBUG	Save changes
1487255036637	addons.xpi-utils	DEBUG	New add-on webcompat@mozilla.org installed in app-system-defaults
1487255036645	DeferredSave.extensions.json	DEBUG	Save changes
1487255036645	addons.xpi-utils	DEBUG	New add-on e10srollout@mozilla.org installed in app-system-defaults
1487255036650	DeferredSave.extensions.json	DEBUG	Save changes
1487255036652	addons.xpi-utils	DEBUG	New add-on {972ce4c6-7e08-4474-a285-3208198ce6fd} installed in app-global
1487255036660	DeferredSave.extensions.json	DEBUG	Save changes
1487255036661	addons.manager	DEBUG	Registering startup change 'installed' for firefox@getpocket.com
1487255036672	addons.xpi	DEBUG	Loading bootstrap scope from /opt/firefox/browser/features/firefox@getpocket.com.xpi
1487255036695	addons.xpi	DEBUG	Calling bootstrap method install on firefox@getpocket.com version 1.0.5
1487255036695	addons.xpi-utils	DEBUG	Make addon app-system-defaults:firefox@getpocket.com visible
1487255036696	DeferredSave.extensions.json	DEBUG	Save changes
1487255036698	addons.manager	DEBUG	Registering startup change 'installed' for aushelper@mozilla.org
1487255036699	addons.xpi	DEBUG	Loading bootstrap scope from /opt/firefox/browser/features/aushelper@mozilla.org.xpi
1487255036705	addons.xpi	DEBUG	Calling bootstrap method install on aushelper@mozilla.org version 1.0
1487255036711	addons.xpi-utils	DEBUG	Make addon app-system-defaults:aushelper@mozilla.org visible
1487255036721	DeferredSave.extensions.json	DEBUG	Save changes
1487255036721	addons.manager	DEBUG	Registering startup change 'installed' for webcompat@mozilla.org
1487255036723	addons.xpi	DEBUG	Loading bootstrap scope from /opt/firefox/browser/features/webcompat@mozilla.org.xpi
1487255036727	addons.xpi	DEBUG	Calling bootstrap method install on webcompat@mozilla.org version 1.0
1487255036728	addons.xpi-utils	DEBUG	Make addon app-system-defaults:webcompat@mozilla.org visible
1487255036728	DeferredSave.extensions.json	DEBUG	Save changes
1487255036729	addons.manager	DEBUG	Registering startup change 'installed' for e10srollout@mozilla.org
1487255036730	addons.xpi	DEBUG	Loading bootstrap scope from /opt/firefox/browser/features/e10srollout@mozilla.org.xpi
1487255036741	addons.xpi	DEBUG	Calling bootstrap method install on e10srollout@mozilla.org version 1.5
1487255036743	addons.xpi-utils	DEBUG	Make addon app-system-defaults:e10srollout@mozilla.org visible
1487255036743	DeferredSave.extensions.json	DEBUG	Save changes
1487255036744	addons.xpi-utils	DEBUG	Make addon app-global:{972ce4c6-7e08-4474-a285-3208198ce6fd} visible
1487255036744	DeferredSave.extensions.json	DEBUG	Save changes
1487255036745	addons.xpi	DEBUG	Updating XPIState for {"id":"firefox@getpocket.com","syncGUID":"{ca6fb4fc-8e28-4ac5-9ae3-b598a1136db0}","location":"app-system-defaults","version":"1.0.5","type":"extension","internalName":null,"updateURL":null,"updateKey":null,"optionsURL":null,"optionsType":null,"aboutURL":null,"icons":{},"iconURL":null,"icon64URL":null,"defaultLocale":{"name":"Pocket","description":"When you find something you want to view later, put it in Pocket.","creator":null,"homepageURL":null},"visible":true,"active":true,"userDisabled":false,"appDisabled":false,"descriptor":"/opt/firefox/browser/features/firefox@getpocket.com.xpi","installDate":1478328701000,"updateDate":1478328701000,"applyBackgroundUpdates":1,"bootstrap":true,"skinnable":false,"size":916880,"sourceURI":null,"releaseNotesURI":null,"softDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"strictCompatibility":false,"locales":[],"targetApplications":[{"id":"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","minVersion":"50.0","maxVersion":"50.*"}],"targetPlatforms":[],"multiprocessCompatible":false,"seen":true}
1487255036746	addons.xpi	DEBUG	getModTime: Recursive scan of firefox@getpocket.com
1487255036747	addons.xpi	DEBUG	Updating XPIState for {"id":"aushelper@mozilla.org","syncGUID":"{e9f94f2f-7e9f-48ea-82dd-9ab394e4b7d6}","location":"app-system-defaults","version":"1.0","type":"extension","internalName":null,"updateURL":null,"updateKey":null,"optionsURL":null,"optionsType":null,"aboutURL":null,"icons":{},"iconURL":null,"icon64URL":null,"defaultLocale":{"name":"Application Update Service Helper","description":"Sets value(s) in the update url based on custom checks.","creator":null,"homepageURL":null},"visible":true,"active":true,"userDisabled":false,"appDisabled":false,"descriptor":"/opt/firefox/browser/features/aushelper@mozilla.org.xpi","installDate":1478328701000,"updateDate":1478328701000,"applyBackgroundUpdates":1,"bootstrap":true,"skinnable":false,"size":5973,"sourceURI":null,"releaseNotesURI":null,"softDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"strictCompatibility":false,"locales":[],"targetApplications":[{"id":"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","minVersion":"50.0","maxVersion":"50.*"}],"targetPlatforms":[],"multiprocessCompatible":true,"seen":true}
1487255036748	addons.xpi	DEBUG	getModTime: Recursive scan of aushelper@mozilla.org
1487255036750	addons.xpi	DEBUG	Updating XPIState for {"id":"webcompat@mozilla.org","syncGUID":"{2530c06e-ba76-4d38-ba0b-916589028eb3}","location":"app-system-defaults","version":"1.0","type":"extension","internalName":null,"updateURL":null,"updateKey":null,"optionsURL":null,"optionsType":null,"aboutURL":null,"icons":{},"iconURL":null,"icon64URL":null,"defaultLocale":{"name":"Web Compat","description":"Urgent post-release fixes for web compatibility.","creator":null,"homepageURL":null},"visible":true,"active":true,"userDisabled":false,"appDisabled":false,"descriptor":"/opt/firefox/browser/features/webcompat@mozilla.org.xpi","installDate":1478328701000,"updateDate":1478328701000,"applyBackgroundUpdates":1,"bootstrap":true,"skinnable":false,"size":1500,"sourceURI":null,"releaseNotesURI":null,"softDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"strictCompatibility":false,"locales":[],"targetApplications":[{"id":"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","minVersion":"50.0","maxVersion":"50.*"}],"targetPlatforms":[],"multiprocessCompatible":false,"seen":true}
1487255036751	addons.xpi	DEBUG	getModTime: Recursive scan of webcompat@mozilla.org
1487255036752	addons.xpi	DEBUG	Updating XPIState for {"id":"e10srollout@mozilla.org","syncGUID":"{41a2a430-fc6d-4940-a806-a1e6f4686a9e}","location":"app-system-defaults","version":"1.5","type":"extension","internalName":null,"updateURL":null,"updateKey":null,"optionsURL":null,"optionsType":null,"aboutURL":null,"icons":{},"iconURL":null,"icon64URL":null,"defaultLocale":{"name":"Multi-process staged rollout","description":"Staged rollout of Firefox multi-process feature.","creator":null,"homepageURL":null},"visible":true,"active":true,"userDisabled":false,"appDisabled":false,"descriptor":"/opt/firefox/browser/features/e10srollout@mozilla.org.xpi","installDate":1478328701000,"updateDate":1478328701000,"applyBackgroundUpdates":1,"bootstrap":true,"skinnable":false,"size":7208,"sourceURI":null,"releaseNotesURI":null,"softDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"strictCompatibility":false,"locales":[],"targetApplications":[{"id":"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","minVersion":"50.0","maxVersion":"50.*"}],"targetPlatforms":[],"multiprocessCompatible":false,"seen":true}
1487255036753	addons.xpi	DEBUG	getModTime: Recursive scan of e10srollout@mozilla.org
1487255036754	addons.xpi	DEBUG	Updating XPIState for {"id":"{972ce4c6-7e08-4474-a285-3208198ce6fd}","syncGUID":"{6bbe545d-edf5-48ad-83ce-6e25db99172b}","location":"app-global","version":"50.0","type":"theme","internalName":"classic/1.0","updateURL":null,"updateKey":null,"optionsURL":null,"optionsType":null,"aboutURL":null,"icons":{"32":"icon.png","48":"icon.png"},"iconURL":null,"icon64URL":null,"defaultLocale":{"name":"Default","description":"The default theme.","creator":"Mozilla","homepageURL":null,"contributors":["Mozilla Contributors"]},"visible":true,"active":true,"userDisabled":false,"appDisabled":false,"descriptor":"/opt/firefox/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}.xpi","installDate":1478328701000,"updateDate":1478328701000,"applyBackgroundUpdates":1,"skinnable":true,"size":4926,"sourceURI":null,"releaseNotesURI":null,"softDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"strictCompatibility":true,"locales":[],"targetApplications":[{"id":"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","minVersion":"50.0","maxVersion":"50.0"}],"targetPlatforms":[],"seen":true}
1487255036755	addons.xpi	DEBUG	getModTime: Recursive scan of {972ce4c6-7e08-4474-a285-3208198ce6fd}
1487255036757	DeferredSave.extensions.json	DEBUG	Save changes
1487255036757	addons.xpi	DEBUG	Updating database with changes to installed add-ons
1487255036757	addons.xpi-utils	DEBUG	Updating add-on states
1487255036758	addons.xpi-utils	DEBUG	Writing add-ons list
1487255036759	addons.xpi	DEBUG	Registering manifest for /opt/firefox/browser/features/firefox@getpocket.com.xpi
1487255036760	addons.xpi	DEBUG	Calling bootstrap method startup on firefox@getpocket.com version 1.0.5
1487255036762	addons.xpi	DEBUG	Registering manifest for /opt/firefox/browser/features/aushelper@mozilla.org.xpi
1487255036763	addons.xpi	DEBUG	Calling bootstrap method startup on aushelper@mozilla.org version 1.0
1487255036763	addons.xpi	DEBUG	Registering manifest for /opt/firefox/browser/features/webcompat@mozilla.org.xpi
1487255036764	addons.xpi	DEBUG	Calling bootstrap method startup on webcompat@mozilla.org version 1.0
1487255036764	addons.xpi	DEBUG	Registering manifest for /opt/firefox/browser/features/e10srollout@mozilla.org.xpi
1487255036765	addons.xpi	DEBUG	Calling bootstrap method startup on e10srollout@mozilla.org version 1.5
1487255036767	addons.manager	DEBUG	Registering shutdown blocker for XPIProvider
1487255036768	addons.manager	DEBUG	Provider finished startup: XPIProvider
1487255036768	addons.manager	DEBUG	Starting provider: LightweightThemeManager
1487255036768	addons.manager	DEBUG	Registering shutdown blocker for LightweightThemeManager
1487255036768	addons.manager	DEBUG	Provider finished startup: LightweightThemeManager
1487255036769	addons.manager	DEBUG	Starting provider: GMPProvider
1487255036784	addons.manager	DEBUG	Registering shutdown blocker for GMPProvider
1487255036785	addons.manager	DEBUG	Provider finished startup: GMPProvider
1487255036786	addons.manager	DEBUG	Starting provider: PluginProvider
1487255036787	addons.manager	DEBUG	Registering shutdown blocker for PluginProvider
1487255036788	addons.manager	DEBUG	Provider finished startup: PluginProvider
1487255036789	addons.manager	DEBUG	Completed startup sequence
1487255037277	Marionette	INFO	Listening on port 45271
1487255037585	addons.manager	DEBUG	Starting provider: <unnamed-provider>
1487255037586	addons.manager	DEBUG	Registering shutdown blocker for <unnamed-provider>
1487255037587	addons.manager	DEBUG	Provider finished startup: <unnamed-provider>
1487255037621	addons.manager	DEBUG	Starting provider: PreviousExperimentProvider
1487255037621	addons.manager	DEBUG	Registering shutdown blocker for PreviousExperimentProvider
1487255037627	addons.manager	DEBUG	Provider finished startup: PreviousExperimentProvider
1487255037632	DeferredSave.extensions.json	DEBUG	Starting write
1487255037871	DeferredSave.extensions.json	DEBUG	Write succeeded
1487255037872	addons.xpi-utils	DEBUG	XPI Database saved, setting schema version preference to 17

[GFX1]: Unknown image format 16

[GFX1]: Unknown image format 16
[GFX1]: Unknown image format 16
[GFX1]: Unknown image format 16
[GFX1]: Unknown image format 16
[GFX1]: Unknown image format 16
[GFX1]: Unknown image format 16
[GFX1]: Unknown image format 16
[GFX1]: Unknown image format 16
[GFX1]: Unknown image format 16
[GFX1]: Unknown image format 16
[GFX1]: Unknown image format 16
[GFX1]: Unknown image format 16
Feb 16, 2017 4:23:59 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: W3C
OS = linux, Browser = firefox 
[GFX1]: Unknown image format 16
[GFX1]: Unknown image format 16
[GFX1]: Unknown image format 16
[GFX1]: Unknown image format 16
[GFX1]: Unknown image format 16
[GFX1]: Unknown image format 16
url = http://mango-erp.example.lv
[GFX1]: Unknown image format 16

[GFX1]: Unknown image format 16
[GFX1]: Unknown image format 16
[GFX1]: Unknown image format 16
[GFX1]: Unknown image format 16
[GFX1]: Unknown image format 16
[GFX1]: Unknown image format 16
[GFX1]: Unknown image format 16
[GFX1]: Unknown image format 16
[GFX1]: Unknown image format 16
Tests run: 5, Failures: 1, Errors: 0, Skipped: 2, Time elapsed: 22.227 sec <<< FAILURE! - in TestSuite
runBrowser(testCases.ApplicationTableTempl)  Time elapsed: 17.5 sec  <<< FAILURE!
org.openqa.selenium.NoAlertPresentException: No tab modal was open when attempting to get the dialog text
Build info: version: '3.0.1', revision: '1969d75', time: '2016-10-18 09:49:13 -0700'
System info: host: 'jenkins', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '4.4.0-62-generic', java.version: '1.8.0_121'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{rotatable=false, raisesAccessibilityExceptions=false, marionette=true, firefoxOptions={args=[], profile=UEsDBBQACAgIAPyCUEoAAAAAAAAAAAAAAAAHAAAAdXNlci5qc51WTW/bMAy971cMOW3AKqTretlOXdcBA4Z1aFDsKMgSbauRJU0fcfPvR/mjSRNHbndKbJMS+fj4yOjBUeugfLconGnxiXhWQvdf6oo0TLXMAQHNCgVi8eFtyZSH91/exJ2nYAFtrHEhudTAVKj7Z4JGG8ln/DWE1rg1qUOwxNbS19uz9Nky788U6CrU6Pjx8vK52xiwAybwR0AAHkB8l86HK4yFK0C34OJhuKbBvB4pr51pgHrupA3URU2DbJLLxXL6osAKTxAOfauvlfEwnc1oLUyrlWEC79KsSsDWpv1Tg14hWgmpaXeLQdng02W0MYKpGexhE4xRnoBzxnGjvVH7cB+n72WljUbUGmgKcKvu0edz8eC9RKtgkAsOfETcSgyUcsd8nfdVUq+JsaApPAZwmqlUzFczqExlvYt6+rIWCuHkBp8Z54DljBoz90gHysEFP4nEU6Wkt4ptQdycL1e/DDInlfbTtDG+Erf6j9RYX3++JBIvMvd3P9FjwQoTw+dCMb1eHHOuT4gypeiDRzBSnLKH/ji2RysRbrQlbS0DKOkDHvA3SneKCYkGaxnI0E0j6zC5xIUsAIphYbAB8lTzibfRkhq7xuLZtAXFUwdFl0q6OEg5VVt3rCHRYoGBaIS23N6jyat1JNrUSjfZ8IBHJ8MWmaIA/xEfnOSBGicrqak1SvJtnqoaWmw7MuSTqeazQPuTSXq5ikUju1b53b286sj4Mt2cPCab8VN3DoVJRUHLE+q160NMs+34e9yIpizRDs6YtZ4g+0xLiy0VULKowrScjLBzbwf+TEd7zIcs20Y6I/dRqYLbkl4ZO/uPc7bZo0dEbu5/XpELwnZFOk7vgW1YPyGyonpYirFH8jw6jtvBQzfEspf0NE3H5/PcQ5zFYL71SrDiSIIkOufLUxran0o1C/hIYQM6zAyIvdF4ixSbjadQhq87UXtRpTwwx+uBN3NjtyE9u4mIjc1WDVn+Ii4+I4xBhJwU04p6JEKH6nMxvfr0an02th/SKMQZyAfbE9Iy7Djzy83e5PTdXN9NTpSg2Gl1FrlErekg9nrH9KOu24F+6Ot+TTm5nQ0zi3ZqJRBGXdGk/zMkqQHHJa+Br7/1gvW1//L6cUaYEDJFzGYmweTS/L/LsjJVlV4OW1xW+/d6qcv4GrUR27WQKrFPy6oO6sS023Mdb/wfaaNjI5AG98KOiIu0Szo4wGi3yqTVE4mNC+TMLrPre1X6aPsVYLdl/ANQSwcIy87bUaYDAAC2DAAAUEsBAhQAFAAICAgA/IJQSsvO21GmAwAAtgwAAAcAAAAAAAAAAAAAAAAAAAAAAHVzZXIuanNQSwUGAAAAAAEAAQA1AAAA2wMAAAAA}, appBuildId=20161104212021, version=, platform=LINUX, proxy={}, command_id=1, specificationLevel=0, acceptSslCerts=false, processId=25511, browserVersion=50.0, platformVersion=4.4.0-62-generic, XULappId={ec8030f7-c20a-464f-9b0e-13a3a9e97384}, browserName=firefox, takesScreenshot=true, takesElementScreenshot=true, platformName=linux}]
Session ID: cd766365-1072-4f2d-acbe-87f23589d100
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:127)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:93)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:42)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:163)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:82)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:601)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:658)
	at org.openqa.selenium.remote.RemoteWebDriver$RemoteTargetLocator.alert(RemoteWebDriver.java:977)
	at factory.BrowserFactory.browserAuthentication(BrowserFactory.java:182)
	at testCases.ApplicationTableTempl.runBrowser(ApplicationTableTempl.java:48)

Results :

Failed tests: 
  ApplicationTableTempl.runBrowser:48 » NoAlertPresent No tab modal was open whe...
```

In order to help us efficiently investigate your issue, please provide the following information:

**Comment by andreastt** [comment]
It seems your test is failing on an assertion you make in `ApplicationTableTempl.runBrowser:48`: `NoAlertPresent No tab modal was open whe...`.

`[GFX1]: Unknown image format 16` is probably being printed due to something being rendered in the viewport and shouldn’t indicate anything fatal. I don’t think the issue is that you are running Firefox in an virtual framebuffer.

If you think this is still a real issue, you would have to provide a trace-level geckodriver log. Please see the README for how to bump up the logging verbosity to trace level.

**Comment by ArmandsBruns** [comment]
My code in ApplicationTableTempl.java class :
On chrome browser everything works fine.

`@Parameters({"browser", "system_OS", "testCase"})
@BeforeTest
public void runBrowser(String browser, String system_OS, String testCase) throws Exception{

		//CHeck TestCase RunMode
		BrowserFactory.checkRunMode(testCase, browser);
		
		//Start Screen Video recording
		Utility.startRecording(testCase + "_" + browser);
		
		//Open browser
		driver = BrowserFactory.getBrowser(browser, system_OS);
		
		//Run browser
		BrowserFactory.runBrowser(browser);
		
	}

	public static void runBrowser(String browser) throws IOException, InterruptedException{
		
		String url = DataProviderFactory.getExcel().getData(1, 1, 2);
		String username = DataProviderFactory.getExcel().getData(2, 6, 1);
		String password = DataProviderFactory.getExcel().getData(2, 6, 2);
		String http = DataProviderFactory.getExcel().getData(1, 2, 2);
		
		System.out.println("url = " + http + url);
		
		//Run URL and Authentication
		if(browser.equalsIgnoreCase("iexplore")){
			BrowserFactory.browserAuthentication(browser, http + url);
		}else{
			BrowserFactory.browserAuthentication(browser, http + username + ":" + password + "@" + url);
		}
		
	}`

**Comment by andreastt** [comment]
@ArmandsBruns Please provide a _reproducible_ test case. As you have provided neither such a test case or a trace-level log, there is really nothing I can do to help you.

**Comment by ArmandsBruns** [comment]
@andreastt  yes, I'm trying to switch on Trace-level log.

I defined the path to my geckodriver in server, export PATH=$PATH:/usr/share/GlobalStagingERP/global.staging.erp/BrowserDrivers/geckodriver

With Selenium 3.0 and later, you shouldn't need to do anything to use Marionette, as it's enabled by default.

`// =================== Initialize and SetUp the WebDriver ======================
		if(browserName.equalsIgnoreCase("firefox")){
			
			if(CheckOS.equalsIgnoreCase("Linux")){
				
				System.setProperty("webdriver.gecko.driver", ConstantsLinux.FIREFOX_DRIVER_PATH);
				FirefoxBinary ffbinary = new FirefoxBinary(new File("/opt/firefox/firefox-bin"));
				FirefoxProfile ffprofile = new FirefoxProfile();
				driver = new FirefoxDriver(ffbinary, ffprofile);

public static final String FIREFOX_DRIVER_PATH="/usr/share/GlobalStagingERP/global.staging.erp/BrowserDrivers/geckodriver";`

**Comment by ArmandsBruns** [comment]
@andreastt 
[https://github.com/laurentj/slimerjs/issues/566](it seems it is firefox bug)
I will try the latest version of firefox.
