### ISSUE TITLE
Selenium issue

### ISSUE THREAD

**Issue by logesh123** [mozilla/geckodriver#489]
Hi, I'm getting this issue. 

Feb 21, 2017 12:01:05 PM org.openqa.selenium.remote.ProtocolHandshake createSession

INFO: Attempting bi-dialect session, assuming Postel's Law holds true on the remote end

Exception in thread "main" org.openqa.selenium.SessionNotCreatedException: A new session could not be created. (Original error: Bad app: D:\Android\startupApp\FirstTest1\app\SarathiAppFinalWave2.apk. App paths need to be absolute, or relative to the appium server install dir, or a URL to compressed file, or a special app name. cause: Error: Error locating the app: ENOENT, stat 'D:\Android\startupApp\FirstTest1\app\SarathiAppFinalWave2.apk') (WARNING: The server did not provide any stacktrace information)

Command duration or timeout: 0 milliseconds

Build info: version: 'unknown', revision: '1969d75', time: '2016-10-18 09:43:45 -0700'

System info: host: 'admin-PC', ip: '192.168.1.229', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_11'

Driver info: driver.version: AndroidDriver

    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)

    at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)

    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)

    at java.lang.reflect.Constructor.newInstance(Unknown Source)

    at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:216)

    at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:168)

    at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:161)

    at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:64)

    at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:141)

    at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:601)

    at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:180)

    at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:241)

    at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:128)

    at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:155)

    at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:109)

    at io.appium.java_client.android.AndroidDriver.<init>(AndroidDriver.java:39)

    at com.tas.MyFirst1test.main(MyFirst1test.java:51)

**Comment by jgraham** [comment]
This isn't an issue tracker for Selenium or Appium. Based on the log output it appears that you are not passing the correct path to your apk file.
