### ISSUE TITLE
geckodriver 0.15.0 does not work in Ubuntu 64bits

### ISSUE THREAD

**Issue by bonigarcia** [mozilla/geckodriver#518]
- Firefox version: 52.0
- geckodriver version: 0.15.0
- Platform: Linux (Ubuntu 16.04 64bits)
- Steps to reproduce: run this [test](https://github.com/bonigarcia/webdrivermanager-examples/blob/master/src/test/java/io/github/bonigarcia/wdm/test/FirefoxTest.java) (based on JUnit and Selenium WebDriver)
- Trace logs:

JUnit
```
org.openqa.selenium.SessionNotCreatedException: Unable to create new remote session. desired capabilities = Capabilities [{marionette=true, browserName=firefox, moz:firefoxOptions=org.openqa.selenium.firefox.FirefoxOptions@7a675056, version=, platform=ANY, firefox_profile=org.openqa.selenium.firefox.FirefoxProfile@d21a74c}], required capabilities = Capabilities [{}]
Build info: version: '3.2.0', revision: '8c03df6b79', time: '2017-02-23 10:51:31 +0000'
System info: host: 'ubuntu', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '4.4.0-64-generic', java.version: '1.8.0_121'
Driver info: driver.version: FirefoxDriver
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:91)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:141)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:82)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:604)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:244)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:131)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:293)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:272)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:267)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:263)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:122)
	at io.github.bonigarcia.wdm.test.FirefoxTest.setupTest(FirefoxTest.java:49)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
```

geckodriver
```
1488987991322	geckodriver	INFO	Listening on 127.0.0.1:16895
1488987991493	mozprofile::profile	INFO	Using profile path /tmp/rust_mozprofile.gSofohCZFIYJ
1488987991495	geckodriver::marionette	INFO	Starting browser /usr/lib/firefox/firefox with args []
1488987991502	geckodriver::marionette	INFO	Connecting to Marionette on localhost:36986
1488987991729	addons.manager	DEBUG	Application has been upgraded
1488987991747	addons.manager	DEBUG	Loaded provider scope for resource://gre/modules/addons/XPIProvider.jsm: ["XPIProvider"]
1488987991749	addons.manager	DEBUG	Loaded provider scope for resource://gre/modules/LightweightThemeManager.jsm: ["LightweightThemeManager"]
1488987991753	addons.manager	DEBUG	Loaded provider scope for resource://gre/modules/addons/GMPProvider.jsm
1488987991756	addons.manager	DEBUG	Loaded provider scope for resource://gre/modules/addons/PluginProvider.jsm
1488987991757	addons.manager	DEBUG	Starting provider: XPIProvider
1488987991757	addons.xpi	DEBUG	startup
1488987991757	addons.xpi	INFO	SystemAddonInstallLocation directory is missing
1488987991758	addons.xpi	INFO	Mapping aushelper@mozilla.org to /usr/lib/firefox/browser/features/aushelper@mozilla.org.xpi
1488987991758	addons.xpi	INFO	Mapping e10srollout@mozilla.org to /usr/lib/firefox/browser/features/e10srollout@mozilla.org.xpi
1488987991759	addons.xpi	INFO	Mapping webcompat@mozilla.org to /usr/lib/firefox/browser/features/webcompat@mozilla.org.xpi
1488987991759	addons.xpi	INFO	Mapping firefox@getpocket.com to /usr/lib/firefox/browser/features/firefox@getpocket.com.xpi
1488987991760	addons.xpi	INFO	Mapping {972ce4c6-7e08-4474-a285-3208198ce6fd} to /usr/lib/firefox/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}.xpi
1488987991761	addons.xpi	INFO	Mapping langpack-en-ZA@firefox.mozilla.org to /usr/lib/firefox/browser/extensions/langpack-en-ZA@firefox.mozilla.org.xpi
1488987991761	addons.xpi	INFO	Mapping langpack-en-GB@firefox.mozilla.org to /usr/lib/firefox/browser/extensions/langpack-en-GB@firefox.mozilla.org.xpi
1488987991762	addons.xpi	DEBUG	checkForChanges
1488987991762	addons.xpi	INFO	SystemAddonInstallLocation directory is missing
1488987991762	addons.xpi	DEBUG	Loaded add-on state from prefs: {}
1488987991763	addons.xpi	DEBUG	New add-on aushelper@mozilla.org in app-system-defaults
1488987991764	addons.xpi	DEBUG	getModTime: Recursive scan of aushelper@mozilla.org
1488987991765	addons.xpi	DEBUG	New add-on e10srollout@mozilla.org in app-system-defaults
1488987991766	addons.xpi	DEBUG	getModTime: Recursive scan of e10srollout@mozilla.org
1488987991766	addons.xpi	DEBUG	New add-on webcompat@mozilla.org in app-system-defaults
1488987991766	addons.xpi	DEBUG	getModTime: Recursive scan of webcompat@mozilla.org
1488987991767	addons.xpi	DEBUG	New add-on firefox@getpocket.com in app-system-defaults
1488987991767	addons.xpi	DEBUG	getModTime: Recursive scan of firefox@getpocket.com
1488987991768	addons.xpi	DEBUG	New add-on {972ce4c6-7e08-4474-a285-3208198ce6fd} in app-global
1488987991769	addons.xpi	DEBUG	getModTime: Recursive scan of {972ce4c6-7e08-4474-a285-3208198ce6fd}
1488987991769	addons.xpi	DEBUG	New add-on langpack-en-ZA@firefox.mozilla.org in app-global
1488987991770	addons.xpi	DEBUG	getModTime: Recursive scan of langpack-en-ZA@firefox.mozilla.org
1488987991770	addons.xpi	DEBUG	New add-on langpack-en-GB@firefox.mozilla.org in app-global
1488987991771	addons.xpi	DEBUG	getModTime: Recursive scan of langpack-en-GB@firefox.mozilla.org
1488987991771	addons.xpi	DEBUG	getInstallState changed: true, state: {"app-system-defaults":{"aushelper@mozilla.org":{"d":"/usr/lib/firefox/browser/features/aushelper@mozilla.org.xpi","st":1488507822000},"e10srollout@mozilla.org":{"d":"/usr/lib/firefox/browser/features/e10srollout@mozilla.org.xpi","st":1488507822000},"webcompat@mozilla.org":{"d":"/usr/lib/firefox/browser/features/webcompat@mozilla.org.xpi","st":1488507822000},"firefox@getpocket.com":{"d":"/usr/lib/firefox/browser/features/firefox@getpocket.com.xpi","st":1488507822000}},"app-global":{"{972ce4c6-7e08-4474-a285-3208198ce6fd}":{"d":"/usr/lib/firefox/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}.xpi","st":1488507822000},"langpack-en-ZA@firefox.mozilla.org":{"d":"/usr/lib/firefox/browser/extensions/langpack-en-ZA@firefox.mozilla.org.xpi","st":1488508135000},"langpack-en-GB@firefox.mozilla.org":{"d":"/usr/lib/firefox/browser/extensions/langpack-en-GB@firefox.mozilla.org.xpi","st":1488508135000}}}
1488987991778	addons.xpi-utils	DEBUG	Opening XPI database /tmp/rust_mozprofile.gSofohCZFIYJ/extensions.json
1488987991779	addons.xpi-utils	DEBUG	New add-on aushelper@mozilla.org installed in app-system-defaults
*** Blocklist::_loadBlocklistFromFile: blocklist is disabled
1488987991789	DeferredSave.extensions.json	DEBUG	Save changes
1488987991790	addons.xpi-utils	DEBUG	New add-on e10srollout@mozilla.org installed in app-system-defaults
1488987991792	DeferredSave.extensions.json	DEBUG	Starting timer
1488987991794	DeferredSave.extensions.json	DEBUG	Save changes
1488987991794	addons.xpi-utils	DEBUG	New add-on webcompat@mozilla.org installed in app-system-defaults
1488987991800	DeferredSave.extensions.json	DEBUG	Save changes
1488987991800	addons.xpi-utils	DEBUG	New add-on firefox@getpocket.com installed in app-system-defaults
1488987991807	DeferredSave.extensions.json	DEBUG	Save changes
1488987991808	addons.xpi-utils	DEBUG	New add-on {972ce4c6-7e08-4474-a285-3208198ce6fd} installed in app-global
1488987991813	DeferredSave.extensions.json	DEBUG	Save changes
1488987991813	addons.xpi-utils	DEBUG	New add-on langpack-en-ZA@firefox.mozilla.org installed in app-global
1488987991827	DeferredSave.extensions.json	DEBUG	Save changes
1488987991827	addons.xpi-utils	DEBUG	New add-on langpack-en-GB@firefox.mozilla.org installed in app-global
1488987991836	DeferredSave.extensions.json	DEBUG	Save changes
1488987991837	addons.manager	DEBUG	Registering startup change 'installed' for aushelper@mozilla.org
1488987991845	addons.xpi	DEBUG	Loading bootstrap scope from /usr/lib/firefox/browser/features/aushelper@mozilla.org.xpi
1488987991850	addons.xpi	DEBUG	Calling bootstrap method install on aushelper@mozilla.org version 2.0
1488987991850	addons.xpi-utils	DEBUG	Make addon app-system-defaults:aushelper@mozilla.org visible
1488987991851	DeferredSave.extensions.json	DEBUG	Save changes
1488987991851	addons.manager	DEBUG	Registering startup change 'installed' for e10srollout@mozilla.org
1488987991852	addons.xpi	DEBUG	Loading bootstrap scope from /usr/lib/firefox/browser/features/e10srollout@mozilla.org.xpi
1488987991854	addons.xpi	DEBUG	Calling bootstrap method install on e10srollout@mozilla.org version 1.9
1488987991855	addons.xpi-utils	DEBUG	Make addon app-system-defaults:e10srollout@mozilla.org visible
1488987991855	DeferredSave.extensions.json	DEBUG	Save changes
1488987991855	addons.manager	DEBUG	Registering startup change 'installed' for webcompat@mozilla.org
1488987991855	addons.xpi	DEBUG	Loading bootstrap scope from /usr/lib/firefox/browser/features/webcompat@mozilla.org.xpi
1488987991857	addons.xpi	DEBUG	Calling bootstrap method install on webcompat@mozilla.org version 1.0
1488987991857	addons.xpi-utils	DEBUG	Make addon app-system-defaults:webcompat@mozilla.org visible
1488987991857	DeferredSave.extensions.json	DEBUG	Save changes
1488987991857	addons.manager	DEBUG	Registering startup change 'installed' for firefox@getpocket.com
1488987991858	addons.xpi	DEBUG	Loading bootstrap scope from /usr/lib/firefox/browser/features/firefox@getpocket.com.xpi
1488987991861	addons.xpi	DEBUG	Calling bootstrap method install on firefox@getpocket.com version 1.0.5
1488987991861	addons.xpi-utils	DEBUG	Make addon app-system-defaults:firefox@getpocket.com visible
1488987991862	DeferredSave.extensions.json	DEBUG	Save changes
1488987991862	addons.xpi-utils	DEBUG	Make addon app-global:{972ce4c6-7e08-4474-a285-3208198ce6fd} visible
1488987991862	DeferredSave.extensions.json	DEBUG	Save changes
1488987991863	addons.manager	DEBUG	Registering startup change 'installed' for langpack-en-ZA@firefox.mozilla.org
1488987991863	addons.manager	DEBUG	Registering startup change 'installed' for langpack-en-ZA@firefox.mozilla.org
1488987991863	addons.xpi-utils	DEBUG	Make addon app-global:langpack-en-ZA@firefox.mozilla.org visible
1488987991863	DeferredSave.extensions.json	DEBUG	Save changes
1488987991863	addons.manager	DEBUG	Registering startup change 'installed' for langpack-en-GB@firefox.mozilla.org
1488987991864	addons.manager	DEBUG	Registering startup change 'installed' for langpack-en-GB@firefox.mozilla.org
1488987991864	addons.xpi-utils	DEBUG	Make addon app-global:langpack-en-GB@firefox.mozilla.org visible
1488987991864	DeferredSave.extensions.json	DEBUG	Save changes
1488987991865	addons.xpi	DEBUG	Updating XPIState for {"id":"aushelper@mozilla.org","syncGUID":"{deb7eec4-f011-4984-a31c-c0a76c58ab2c}","location":"app-system-defaults","version":"2.0","type":"extension","internalName":null,"updateURL":null,"updateKey":null,"optionsURL":null,"optionsType":null,"aboutURL":null,"icons":{},"iconURL":null,"icon64URL":null,"defaultLocale":{"name":"Application Update Service Helper","description":"Sets value(s) in the update url based on custom checks.","creator":null,"homepageURL":null},"visible":true,"active":true,"userDisabled":false,"appDisabled":false,"descriptor":"/usr/lib/firefox/browser/features/aushelper@mozilla.org.xpi","installDate":1488507822000,"updateDate":1488507822000,"applyBackgroundUpdates":1,"bootstrap":true,"skinnable":false,"size":8486,"sourceURI":null,"releaseNotesURI":null,"softDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"strictCompatibility":false,"locales":[],"targetApplications":[{"id":"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","minVersion":"52.0","maxVersion":"52.*"}],"targetPlatforms":[],"multiprocessCompatible":true,"seen":true,"dependencies":[],"hasEmbeddedWebExtension":false,"mpcOptedOut":false}
1488987991865	addons.xpi	DEBUG	getModTime: Recursive scan of aushelper@mozilla.org
1488987991865	addons.xpi	DEBUG	Updating XPIState for {"id":"e10srollout@mozilla.org","syncGUID":"{266f6003-8aa0-4bd0-8bce-84b37bb0fcbd}","location":"app-system-defaults","version":"1.9","type":"extension","internalName":null,"updateURL":null,"updateKey":null,"optionsURL":null,"optionsType":null,"aboutURL":null,"icons":{},"iconURL":null,"icon64URL":null,"defaultLocale":{"name":"Multi-process staged rollout","description":"Staged rollout of Firefox multi-process feature.","creator":null,"homepageURL":null},"visible":true,"active":true,"userDisabled":false,"appDisabled":false,"descriptor":"/usr/lib/firefox/browser/features/e10srollout@mozilla.org.xpi","installDate":1488507822000,"updateDate":1488507822000,"applyBackgroundUpdates":1,"bootstrap":true,"skinnable":false,"size":7181,"sourceURI":null,"releaseNotesURI":null,"softDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"strictCompatibility":false,"locales":[],"targetApplications":[{"id":"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","minVersion":"52.0","maxVersion":"52.*"}],"targetPlatforms":[],"multiprocessCompatible":true,"seen":true,"dependencies":[],"hasEmbeddedWebExtension":false,"mpcOptedOut":false}
1488987991865	addons.xpi	DEBUG	getModTime: Recursive scan of e10srollout@mozilla.org
1488987991866	addons.xpi	DEBUG	Updating XPIState for {"id":"webcompat@mozilla.org","syncGUID":"{7f88abcb-241f-4286-a339-c2f6ceb9af67}","location":"app-system-defaults","version":"1.0","type":"extension","internalName":null,"updateURL":null,"updateKey":null,"optionsURL":null,"optionsType":null,"aboutURL":null,"icons":{},"iconURL":null,"icon64URL":null,"defaultLocale":{"name":"Web Compat","description":"Urgent post-release fixes for web compatibility.","creator":null,"homepageURL":null},"visible":true,"active":true,"userDisabled":false,"appDisabled":false,"descriptor":"/usr/lib/firefox/browser/features/webcompat@mozilla.org.xpi","installDate":1488507822000,"updateDate":1488507822000,"applyBackgroundUpdates":1,"bootstrap":true,"skinnable":false,"size":1454,"sourceURI":null,"releaseNotesURI":null,"softDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"strictCompatibility":false,"locales":[],"targetApplications":[{"id":"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","minVersion":"52.0","maxVersion":"52.*"}],"targetPlatforms":[],"multiprocessCompatible":true,"seen":true,"dependencies":[],"hasEmbeddedWebExtension":false,"mpcOptedOut":false}
1488987991866	addons.xpi	DEBUG	getModTime: Recursive scan of webcompat@mozilla.org
1488987991866	addons.xpi	DEBUG	Updating XPIState for {"id":"firefox@getpocket.com","syncGUID":"{6718a3f0-ee0d-42e4-88fc-420cef4fd47c}","location":"app-system-defaults","version":"1.0.5","type":"extension","internalName":null,"updateURL":null,"updateKey":null,"optionsURL":null,"optionsType":null,"aboutURL":null,"icons":{},"iconURL":null,"icon64URL":null,"defaultLocale":{"name":"Pocket","description":"When you find something you want to view later, put it in Pocket.","creator":null,"homepageURL":null},"visible":true,"active":true,"userDisabled":false,"appDisabled":false,"descriptor":"/usr/lib/firefox/browser/features/firefox@getpocket.com.xpi","installDate":1488507822000,"updateDate":1488507822000,"applyBackgroundUpdates":1,"bootstrap":true,"skinnable":false,"size":920279,"sourceURI":null,"releaseNotesURI":null,"softDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"strictCompatibility":false,"locales":[],"targetApplications":[{"id":"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","minVersion":"52.0","maxVersion":"52.*"}],"targetPlatforms":[],"multiprocessCompatible":true,"seen":true,"dependencies":[],"hasEmbeddedWebExtension":false,"mpcOptedOut":false}
1488987991866	addons.xpi	DEBUG	getModTime: Recursive scan of firefox@getpocket.com
1488987991867	addons.xpi	DEBUG	Updating XPIState for {"id":"{972ce4c6-7e08-4474-a285-3208198ce6fd}","syncGUID":"{eb967de6-9b99-4c81-b706-444a9ee8eb7f}","location":"app-global","version":"52.0","type":"theme","internalName":"classic/1.0","updateURL":null,"updateKey":null,"optionsURL":null,"optionsType":null,"aboutURL":null,"icons":{"32":"icon.png","48":"icon.png"},"iconURL":null,"icon64URL":null,"defaultLocale":{"name":"Default","description":"The default theme.","creator":"Mozilla","homepageURL":null,"contributors":["Mozilla Contributors"]},"visible":true,"active":true,"userDisabled":false,"appDisabled":false,"descriptor":"/usr/lib/firefox/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}.xpi","installDate":1488507822000,"updateDate":1488507822000,"applyBackgroundUpdates":1,"skinnable":true,"size":4926,"sourceURI":null,"releaseNotesURI":null,"softDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"strictCompatibility":true,"locales":[],"targetApplications":[{"id":"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","minVersion":"52.0","maxVersion":"52.0"}],"targetPlatforms":[],"seen":true,"dependencies":[],"hasEmbeddedWebExtension":false}
1488987991867	addons.xpi	DEBUG	getModTime: Recursive scan of {972ce4c6-7e08-4474-a285-3208198ce6fd}
1488987991868	addons.xpi	DEBUG	Updating XPIState for {"id":"langpack-en-ZA@firefox.mozilla.org","syncGUID":"{6284a2bd-a3d7-425d-8241-0ca87e974bc9}","location":"app-global","version":"52.0","type":"locale","internalName":null,"updateURL":null,"updateKey":null,"optionsURL":null,"optionsType":null,"aboutURL":null,"icons":{},"iconURL":null,"icon64URL":null,"defaultLocale":{"name":"English (South Africa) Language Pack","description":null,"creator":"Translate.org.za","homepageURL":null,"contributors":["Translate.org.za","Dwayne Bailey"]},"visible":true,"active":true,"userDisabled":false,"appDisabled":false,"descriptor":"/usr/lib/firefox/browser/extensions/langpack-en-ZA@firefox.mozilla.org.xpi","installDate":1488508135000,"updateDate":1488508135000,"applyBackgroundUpdates":1,"bootstrap":true,"skinnable":false,"size":1197389,"sourceURI":null,"releaseNotesURI":null,"softDisabled":false,"foreignInstall":true,"hasBinaryComponents":false,"strictCompatibility":true,"locales":[],"targetApplications":[{"id":"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","minVersion":"52.0","maxVersion":"52.*"}],"targetPlatforms":[],"seen":true,"dependencies":[],"hasEmbeddedWebExtension":false}
1488987991868	addons.xpi	DEBUG	getModTime: Recursive scan of langpack-en-ZA@firefox.mozilla.org
1488987991868	addons.xpi	DEBUG	Updating XPIState for {"id":"langpack-en-GB@firefox.mozilla.org","syncGUID":"{82a7666e-baf7-4aef-b73e-52f3507c6e6b}","location":"app-global","version":"52.0","type":"locale","internalName":null,"updateURL":null,"updateKey":null,"optionsURL":null,"optionsType":null,"aboutURL":null,"icons":{},"iconURL":null,"icon64URL":null,"defaultLocale":{"name":"English (GB) Language Pack","description":null,"creator":"Mark Tyndall","homepageURL":null,"contributors":["David Bartlett","Constantine Murenin","Ian Neal"]},"visible":true,"active":true,"userDisabled":false,"appDisabled":false,"descriptor":"/usr/lib/firefox/browser/extensions/langpack-en-GB@firefox.mozilla.org.xpi","installDate":1488508135000,"updateDate":1488508135000,"applyBackgroundUpdates":1,"bootstrap":true,"skinnable":false,"size":1155231,"sourceURI":null,"releaseNotesURI":null,"softDisabled":false,"foreignInstall":true,"hasBinaryComponents":false,"strictCompatibility":true,"locales":[],"targetApplications":[{"id":"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","minVersion":"52.0","maxVersion":"52.*"}],"targetPlatforms":[],"seen":true,"dependencies":[],"hasEmbeddedWebExtension":false}
1488987991869	addons.xpi	DEBUG	getModTime: Recursive scan of langpack-en-GB@firefox.mozilla.org
1488987991870	DeferredSave.extensions.json	DEBUG	Save changes
1488987991870	addons.xpi	DEBUG	Updating database with changes to installed add-ons
1488987991870	addons.xpi-utils	DEBUG	Updating add-on states
1488987991871	addons.xpi-utils	DEBUG	Writing add-ons list
1488987991873	addons.xpi	DEBUG	Registering manifest for /usr/lib/firefox/browser/features/aushelper@mozilla.org.xpi
1488987991873	addons.xpi	DEBUG	Calling bootstrap method startup on aushelper@mozilla.org version 2.0
1488987991875	addons.xpi	DEBUG	Registering manifest for /usr/lib/firefox/browser/features/e10srollout@mozilla.org.xpi
1488987991876	addons.xpi	DEBUG	Calling bootstrap method startup on e10srollout@mozilla.org version 1.9
1488987991877	addons.xpi	DEBUG	Registering manifest for /usr/lib/firefox/browser/features/firefox@getpocket.com.xpi
1488987991878	addons.xpi	DEBUG	Calling bootstrap method startup on firefox@getpocket.com version 1.0.5
1488987991880	addons.xpi	DEBUG	Registering manifest for /usr/lib/firefox/browser/extensions/langpack-en-GB@firefox.mozilla.org.xpi
1488987991881	addons.xpi	DEBUG	Registering manifest for /usr/lib/firefox/browser/extensions/langpack-en-ZA@firefox.mozilla.org.xpi
1488987991883	addons.xpi	DEBUG	Registering manifest for /usr/lib/firefox/browser/features/webcompat@mozilla.org.xpi
1488987991883	addons.xpi	DEBUG	Calling bootstrap method startup on webcompat@mozilla.org version 1.0
1488987991888	addons.manager	DEBUG	Registering shutdown blocker for XPIProvider
1488987991889	addons.manager	DEBUG	Provider finished startup: XPIProvider
1488987991889	addons.manager	DEBUG	Starting provider: LightweightThemeManager
1488987991889	addons.manager	DEBUG	Registering shutdown blocker for LightweightThemeManager
1488987991889	addons.manager	DEBUG	Provider finished startup: LightweightThemeManager
1488987991890	addons.manager	DEBUG	Starting provider: GMPProvider
1488987991896	addons.manager	DEBUG	Registering shutdown blocker for GMPProvider
1488987991897	addons.manager	DEBUG	Provider finished startup: GMPProvider
1488987991897	addons.manager	DEBUG	Starting provider: PluginProvider
1488987991897	addons.manager	DEBUG	Registering shutdown blocker for PluginProvider
1488987991897	addons.manager	DEBUG	Provider finished startup: PluginProvider
1488987991897	addons.manager	DEBUG	Completed startup sequence
1488987992095	Marionette	INFO	Listening on port 36986
1488987992383	addons.manager	DEBUG	Starting provider: <unnamed-provider>
1488987992383	addons.manager	DEBUG	Registering shutdown blocker for <unnamed-provider>
1488987992383	addons.manager	DEBUG	Provider finished startup: <unnamed-provider>
1488987992397	addons.manager	DEBUG	Starting provider: PreviousExperimentProvider
1488987992397	addons.manager	DEBUG	Registering shutdown blocker for PreviousExperimentProvider
1488987992398	addons.manager	DEBUG	Provider finished startup: PreviousExperimentProvider
1488987992401	DeferredSave.extensions.json	DEBUG	Starting write
1488987992534	DeferredSave.extensions.json	DEBUG	Write succeeded
1488987992535	addons.xpi-utils	DEBUG	XPI Database saved, setting schema version preference to 19
```

**Comment by twalpole** [comment]
Update to selenium 3.3

**Comment by bonigarcia** [comment]
Indeed, with that update it works again. Thank you.

**Comment by andreastt** [comment]
Duplicate of https://github.com/mozilla/geckodriver/issues/523.
