### ISSUE TITLE
geckodriver and Firefox dont' work together

### ISSUE THREAD

**Issue by zniff** [mozilla/geckodriver#523]
In order to help us efficiently investigate your issue, please provide the following information:

## Firefox Version
52.0 (23-bit)

## Platform
Windows 10

java 1.8.0_121
tested with both geckodriver 0.15.0 32/64 bit
selenium 3.3.0

## Steps to reproduce -
I encounter crashes which are obvioulsy caused somewhere deep in the geckodriver.
This happens e.g. if the "drag & drop" functionality is used -- but happens anywhere else too (quite randomly IMHO). I.e. let a test run and wait until it crashes. it will. sooner or later.

Example Java code for drag & drop:
```
		Actions act = new Actions(driver);
		act.clickAndHold(dragHandle).perform();
		act.moveToElement(moveTo, moveTo.getLocation().getX(), moveTo.getLocation().getY()).perform();
		act.release(moveTo).perform();

```

The error reported from geckodriver.exe is:

```
Mär 09, 2017 9:28:59 AM org.openqa.selenium.remote.ErrorCodes toStatus
INFO: HTTP Status: '400' -> incorrect JSON status mapping for 'unknown error' (500 expected)
[Child 1732] ###!!! ABORT: Aborting on channel error.: file c:/builds/moz2_slave/m-rel-w32-00000000000000000000/build/src/ipc/glue/MessageChannel.cpp, line 2143
Mär 09, 2017 9:29:00 AM org.openqa.selenium.os.UnixProcess destroy
SEVERE: Unable to kill process with PID 1336
```

and the stacktrace in Java:

```
org.openqa.selenium.WebDriverException: An unknown error has occurred
Build info: version: '3.3.0', revision: 'b526bd5b41', time: '2017-03-07 19:26:04 +0000'
System info: host: 'z001-07-I7', ip: '192.168.50.63', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_121'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{moz:profile=C:\Users\ESiffert\AppData\Local\Temp\rust_mozprofile.sw0pqFyuK7w3, rotatable=false, timeouts={implicit=0, page load=300000, script=30000}, pageLoadStrategy=normal, platform=ANY, specificationLevel=0, moz:accessibilityChecks=false, acceptInsecureCerts=true, browserVersion=52.0, platformVersion=10.0, moz:processID=7896, browserName=firefox, platformName=windows_nt}]
Session ID: c0fe73ad-c57d-4ebf-8d12-62f64bd7439b
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:127)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:93)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:42)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:163)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:82)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:604)
	at org.openqa.selenium.remote.RemoteWebDriver.perform(RemoteWebDriver.java:670)
	at org.openqa.selenium.interactions.Actions$BuiltAction.perform(Actions.java:634)
	at org.openqa.selenium.interactions.Actions.perform(Actions.java:596)

```

or another error:

```
Mär 09, 2017 7:40:59 AM org.openqa.selenium.remote.ErrorCodes toStatus
INFO: HTTP Status: '400' -> incorrect JSON status mapping for 'unknown error' (500 expected)
[Child 6696] ###!!! ABORT: Aborting on channel error.: file c:/builds/moz2_slave/m-rel-w32-00000000000000000000/build/src/ipc/glue/MessageChannel.cpp, line 2143
Mär 09, 2017 7:41:01 AM org.openqa.selenium.os.UnixProcess destroy
SEVERE: Unable to kill process with PID 12004

```
and the stacktrace to this error:
```

org.openqa.selenium.WebDriverException: An unknown error has occurred
Build info: version: '3.3.0', revision: 'b526bd5b41', time: '2017-03-07 19:26:04 +0000'
System info: host: 'dx78909-I7', ip: '192.168.50.63', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_121'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{moz:profile=C:\Users\ESiffert\AppData\Local\Temp\rust_mozprofile.S57qk21HjErV, rotatable=false, timeouts={implicit=0, page load=300000, script=30000}, pageLoadStrategy=normal, platform=ANY, specificationLevel=0, moz:accessibilityChecks=false, acceptInsecureCerts=true, browserVersion=52.0, platformVersion=10.0, moz:processID=10384, browserName=firefox, platformName=windows_nt}]
Session ID: 1b9cee1f-60d4-4685-99b0-df84995899f3
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:127)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:93)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:42)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:163)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:82)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:604)
	at org.openqa.selenium.remote.RemoteWebElement.execute(RemoteWebElement.java:274)
	at org.openqa.selenium.remote.RemoteWebElement.click(RemoteWebElement.java:84)
```

and the json profile:
```

{
  "desiredCapabilities": {
    "firefox_binary": "/Program Files (x86)/Mozilla Firefox/firefox.exe",
    "acceptSslCerts": true,
    "marionette": true,
    "acceptInsecureCerts": true,
    "browserName": "firefox",
    "moz:firefoxOptions": {
      "binary": "/Program Files (x86)/Mozilla Firefox/firefox.exe",
      "profile": ".......",
      "log": {
        "level": "fatal"
      },
      "args": []
    },
    "version": "",
    "platform": "ANY",
    "firefox_profile": "......."
  },
  "requiredCapabilities": {},
  "capabilities": {
    "desiredCapabilities": {
      "firefox_binary": "/Program Files (x86)/Mozilla Firefox/firefox.exe",
      "acceptSslCerts": true,
      "marionette": true,
      "acceptInsecureCerts": true,
      "browserName": "firefox",
      "moz:firefoxOptions": {
        "binary": "/Program Files (x86)/Mozilla Firefox/firefox.exe",
        "profile": ".......",
        "log": {
          "level": "fatal"
        },
        "args": []
      },
      "version": "",
      "platform": "ANY",
      "firefox_profile": "......."
    },
    "requiredCapabilities": {}
  },
  "alwaysMatch": {
    "acceptSslCerts": true,
    "acceptInsecureCerts": true,
    "version": "",
    "platform": "ANY"
  },
  "firstMatch": [
    {
      "browserName": "firefox",
      "moz:firefoxOptions": {
        "binary": "/Program Files (x86)/Mozilla Firefox/firefox.exe",
        "profile": ".......",
        "log": {
          "level": "fatal"
        },
        "args": []
      }
    }
  ]
}
```

**Comment by snpanigrahi9** [comment]
Hii Zniff

How did you get selenium 3.3.0 ?
even it is not released.

**Comment by Rohit12590More** [comment]
Even I want to know this.

**Comment by zniff** [comment]
Hi everybody
quite easy: through Maven...
I tested first with 3.2.0 -- then I saw a 3.3.0 version was already announced, and i fetched it as mentioned through maven (to my surprise it was already there):

```
    <dependency>
    	<groupId>org.seleniumhq.selenium</groupId>
    	<artifactId>selenium-java</artifactId>
    	<version>3.3.0</version>
    </dependency>

```

**Comment by JoeStoner** [comment]
I've the same problem:

http://stackoverflow.com/questions/42672643/selenium-3-2-0-crashes-firefox-52-during-driver-quit-win-7-home-premium-ge/42699027#42699027

**Comment by andreastt** [comment]
As I note in the [release notes](https://groups.google.com/forum/#!topic/mozilla.tools.marionette/yfOmVgYMDbQ), because the 0.15.0 release makes a backwards incompatible change to stay aligned with the [WebDriver standard](http://w3c.github.io/webdriver/webdriver-spec.html), you must make sure to use the latest Selenium 3.3 release: this has support for unmarshalling the way geckodriver now returns HTTP payloads.

I am very sorry for making this change, but geckodriver is leading the painful march towards specification conformance here. I hope you understand that these rough edges are being ironed out.

**Comment by jvg1426** [comment]
zniff The MoveToElement() was failing for me.  I fixed it by removing the .Preform(). I'm using C#.

snpanigrahi9 I was able to get Selenium 3.3.0 from NuGet Packages through Visual Studio.

**Comment by pshivapr** [comment]
new Actions(driver).sendKeys(Keys.ARROW_DOWN).perform();

also does not work (tested on firefox 52.0 64-bit)

JavaScript warning: https://armsapqa2.erpvpc1.arm.com:447/sap/public/bc/ur/Design2002/js/sapUrMapi_nn7.js?6.0.17.0.0, line 5696: unreachable code after return statement
JavaScript error: https://armsapqa2.erpvpc1.arm.com:447/sap/public/bc/ur/Design2002/js/sapUrMapi_nn7.js?6.0.17.0.0, line 1315: ReferenceError: ur_setEditCellColor is not defined
JavaScript error: https://armsapqa2.erpvpc1.arm.com:447/sap/public/bc/ur/Design2002/js/sapUrMapi_nn7.js?6.0.17.0.0, line 1710: ReferenceError: ur_removeEditCellColor is not defined
JavaScript error: https://armsapqa2.erpvpc1.arm.com:447/sap/public/bc/ur/Design2002/js/sapUrMapi_nn7.js?6.0.17.0.0, line 1315: ReferenceError: ur_setEditCellColor is not defined
JavaScript error: https://armsapqa2.erpvpc1.arm.com:447/sap/public/bc/ur/Design2002/js/sapUrMapi_nn7.js?6.0.17.0.0, line 1710: ReferenceError: ur_removeEditCellColor is not defined
JavaScript warning: https://armsapqa2.erpvpc1.arm.com:447/sap/bc/ui5_ui5/ui2/ushell/resources/sap/fiori/core-min-3.js, line 7: unreachable code after return statement
JavaScript warning: https://armsapqa2.erpvpc1.arm.com:447/sap/bc/ui5_ui5/ui2/ushell/resources/sap/fiori/core-min-3.js, line 7: unreachable code after return statement

**Comment by bladyk1** [comment]
Hi, i have the same with:
Firefox Version: 52.0 (23-bit)
geckodriver 0.15.0
selenium 3.3.1
For me test is working but I had to comment out line:
restartBrowserBetweenTests: true,
Even without it I have same error as you have. Do you know any resolution for this ?
