### ISSUE TITLE
error attempting to accesss webelement location

### ISSUE THREAD

**Issue by hjwp** [mozilla/geckodriver#531]
Attempt to access a webelement .location gives an error (in python):

This happens since selenium 3.3.0, does not occur in previous release 3.0.2

```python
Traceback (most recent call last):
  File "thing.py", line 6, in <module>
    print(thing.location)
  File "/home/harry/.virtualenvs/tmp-d064a1e63ffc8e96/lib/python3.6/site-packages/selenium/webdriver/remote/webelement.py", line 403, in location
    new_loc = {"x": round(old_loc['x']),
TypeError: 'NoneType' object is not subscriptable
```

presumably `old_loc` is None, so this code assumed the object had moved, or something like that?

## Firefox Version
51.0.1 (64-bit)

## Platform
Ubuntu 16.10

## Steps to reproduce -

https://gist.github.com/hjwp/493ab977618d6a28f46ed681a0438739

elements:

 - [x] A *minimal* HTML file 
 - [x] A [trace level log](https://github.com/mozilla/geckodriver#firefox-capabilities)

**Comment by hjwp** [comment]
Just saw the mailing list announcement, this is fixed by upgrading to geckodriver v15.0, my apologies everyone.
