### ISSUE TITLE
Selenium 3.3.1 and Gecko 0.15 cant start Firefox

### ISSUE THREAD

**Issue by lvlmd** [mozilla/geckodriver#548]
## Firefox Version
55.0a1 (2017-03-15) (64-bit)

## Platform
OSX

## Steps to reproduce -

Run this code:
```
public class TestSelenium3JavaGeckoDriver {

    public static void main(String[] args) {
        System.setProperty("webdriver.gecko.driver", "/Users/lvlmd/SeleniumTestTrainign/geckodriver");
        DesiredCapabilities capabilities = DesiredCapabilities.firefox();
        WebDriver driver = new FirefoxDriver(capabilities);
        driver.get("http://seleniumhq.org");
        driver.quit();
    }
}
```

pom file:
```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>WebDriverBasics</groupId>
    <artifactId>WebDriverBasics</artifactId>
    <packaging>pom</packaging>
    <version>1.0-SNAPSHOT</version>
    <dependencies>
        <dependency>
            <groupId>org.seleniumhq.selenium</groupId>
            <artifactId>selenium-java</artifactId>
            <version>3.3.1</version>
        </dependency>
        <dependency>
            <groupId>org.testng</groupId>
            <artifactId>testng</artifactId>
            <version>6.8</version>
            <scope>test</scope>
        </dependency>
    </dependencies>
</project>
```

Result log:
```
/Library/Java/JavaVirtualMachines/jdk1.8.0_31.jdk/Contents/Home/bin/java -Didea.launcher.port=7533 "-Didea.launcher.bin.path=/Applications/IntelliJ IDEA CE.app/Contents/bin" -Dfile.encoding=UTF-8 -classpath "/Library/Java/JavaVirtualMachines/jdk1.8.0_31.jdk/Contents/Home/jre/lib/charsets.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_31.jdk/Contents/Home/jre/lib/deploy.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_31.jdk/Contents/Home/jre/lib/ext/cldrdata.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_31.jdk/Contents/Home/jre/lib/ext/dnsns.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_31.jdk/Contents/Home/jre/lib/ext/jfxrt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_31.jdk/Contents/Home/jre/lib/ext/localedata.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_31.jdk/Contents/Home/jre/lib/ext/nashorn.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_31.jdk/Contents/Home/jre/lib/ext/sunec.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_31.jdk/Contents/Home/jre/lib/ext/sunjce_provider.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_31.jdk/Contents/Home/jre/lib/ext/sunpkcs11.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_31.jdk/Contents/Home/jre/lib/ext/zipfs.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_31.jdk/Contents/Home/jre/lib/javaws.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_31.jdk/Contents/Home/jre/lib/jce.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_31.jdk/Contents/Home/jre/lib/jfr.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_31.jdk/Contents/Home/jre/lib/jfxswt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_31.jdk/Contents/Home/jre/lib/jsse.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_31.jdk/Contents/Home/jre/lib/management-agent.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_31.jdk/Contents/Home/jre/lib/plugin.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_31.jdk/Contents/Home/jre/lib/resources.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_31.jdk/Contents/Home/jre/lib/rt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_31.jdk/Contents/Home/lib/ant-javafx.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_31.jdk/Contents/Home/lib/dt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_31.jdk/Contents/Home/lib/javafx-mx.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_31.jdk/Contents/Home/lib/jconsole.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_31.jdk/Contents/Home/lib/sa-jdi.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_31.jdk/Contents/Home/lib/tools.jar:/Users/lvlmd/SeleniumTestTrainign/Selenium3JavaGeckoDriver/target/test-classes:/Users/lvlmd/.m2/repository/org/seleniumhq/selenium/selenium-java/3.3.1/selenium-java-3.3.1.jar:/Users/lvlmd/.m2/repository/org/seleniumhq/selenium/selenium-chrome-driver/3.3.1/selenium-chrome-driver-3.3.1.jar:/Users/lvlmd/.m2/repository/org/seleniumhq/selenium/selenium-remote-driver/3.3.1/selenium-remote-driver-3.3.1.jar:/Users/lvlmd/.m2/repository/org/seleniumhq/selenium/selenium-api/3.3.1/selenium-api-3.3.1.jar:/Users/lvlmd/.m2/repository/cglib/cglib-nodep/3.2.4/cglib-nodep-3.2.4.jar:/Users/lvlmd/.m2/repository/org/apache/commons/commons-exec/1.3/commons-exec-1.3.jar:/Users/lvlmd/.m2/repository/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar:/Users/lvlmd/.m2/repository/com/google/guava/guava/21.0/guava-21.0.jar:/Users/lvlmd/.m2/repository/org/apache/httpcomponents/httpclient/4.5.2/httpclient-4.5.2.jar:/Users/lvlmd/.m2/repository/org/apache/httpcomponents/httpcore/4.4.4/httpcore-4.4.4.jar:/Users/lvlmd/.m2/repository/net/java/dev/jna/jna-platform/4.1.0/jna-platform-4.1.0.jar:/Users/lvlmd/.m2/repository/net/java/dev/jna/jna/4.1.0/jna-4.1.0.jar:/Users/lvlmd/.m2/repository/org/seleniumhq/selenium/selenium-edge-driver/3.3.1/selenium-edge-driver-3.3.1.jar:/Users/lvlmd/.m2/repository/org/seleniumhq/selenium/selenium-firefox-driver/3.3.1/selenium-firefox-driver-3.3.1.jar:/Users/lvlmd/.m2/repository/org/seleniumhq/selenium/selenium-ie-driver/3.3.1/selenium-ie-driver-3.3.1.jar:/Users/lvlmd/.m2/repository/org/seleniumhq/selenium/selenium-opera-driver/3.3.1/selenium-opera-driver-3.3.1.jar:/Users/lvlmd/.m2/repository/org/seleniumhq/selenium/selenium-safari-driver/3.3.1/selenium-safari-driver-3.3.1.jar:/Users/lvlmd/.m2/repository/com/codeborne/phantomjsdriver/1.4.0/phantomjsdriver-1.4.0.jar:/Users/lvlmd/.m2/repository/org/seleniumhq/selenium/htmlunit-driver/2.24/htmlunit-driver-2.24.jar:/Users/lvlmd/.m2/repository/org/seleniumhq/selenium/selenium-support/3.3.1/selenium-support-3.3.1.jar:/Users/lvlmd/.m2/repository/org/hamcrest/hamcrest-library/1.3/hamcrest-library-1.3.jar:/Users/lvlmd/.m2/repository/net/sourceforge/htmlunit/htmlunit/2.24/htmlunit-2.24.jar:/Users/lvlmd/.m2/repository/xalan/xalan/2.7.2/xalan-2.7.2.jar:/Users/lvlmd/.m2/repository/xalan/serializer/2.7.2/serializer-2.7.2.jar:/Users/lvlmd/.m2/repository/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar:/Users/lvlmd/.m2/repository/org/apache/httpcomponents/httpmime/4.5.2/httpmime-4.5.2.jar:/Users/lvlmd/.m2/repository/commons-codec/commons-codec/1.10/commons-codec-1.10.jar:/Users/lvlmd/.m2/repository/net/sourceforge/htmlunit/htmlunit-core-js/2.23/htmlunit-core-js-2.23.jar:/Users/lvlmd/.m2/repository/net/sourceforge/htmlunit/neko-htmlunit/2.24/neko-htmlunit-2.24.jar:/Users/lvlmd/.m2/repository/xerces/xercesImpl/2.11.0/xercesImpl-2.11.0.jar:/Users/lvlmd/.m2/repository/xml-apis/xml-apis/1.4.01/xml-apis-1.4.01.jar:/Users/lvlmd/.m2/repository/net/sourceforge/cssparser/cssparser/0.9.21/cssparser-0.9.21.jar:/Users/lvlmd/.m2/repository/org/w3c/css/sac/1.3/sac-1.3.jar:/Users/lvlmd/.m2/repository/commons-io/commons-io/2.5/commons-io-2.5.jar:/Users/lvlmd/.m2/repository/commons-logging/commons-logging/1.2/commons-logging-1.2.jar:/Users/lvlmd/.m2/repository/org/eclipse/jetty/websocket/websocket-client/9.2.20.v20161216/websocket-client-9.2.20.v20161216.jar:/Users/lvlmd/.m2/repository/org/eclipse/jetty/jetty-util/9.2.20.v20161216/jetty-util-9.2.20.v20161216.jar:/Users/lvlmd/.m2/repository/org/eclipse/jetty/jetty-io/9.2.20.v20161216/jetty-io-9.2.20.v20161216.jar:/Users/lvlmd/.m2/repository/org/eclipse/jetty/websocket/websocket-common/9.2.20.v20161216/websocket-common-9.2.20.v20161216.jar:/Users/lvlmd/.m2/repository/org/eclipse/jetty/websocket/websocket-api/9.2.20.v20161216/websocket-api-9.2.20.v20161216.jar:/Users/lvlmd/.m2/repository/org/testng/testng/6.8/testng-6.8.jar:/Users/lvlmd/.m2/repository/junit/junit/4.10/junit-4.10.jar:/Users/lvlmd/.m2/repository/org/hamcrest/hamcrest-core/1.1/hamcrest-core-1.1.jar:/Users/lvlmd/.m2/repository/org/beanshell/bsh/2.0b4/bsh-2.0b4.jar:/Users/lvlmd/.m2/repository/com/beust/jcommander/1.27/jcommander-1.27.jar:/Users/lvlmd/.m2/repository/org/yaml/snakeyaml/1.6/snakeyaml-1.6.jar:/Applications/IntelliJ IDEA CE.app/Contents/lib/idea_rt.jar" com.intellij.rt.execution.application.AppMain TestSelenium3JavaGeckoDriver
1489599669136	geckodriver	INFO	Listening on 127.0.0.1:12920
1489599669485	mozprofile::profile	INFO	Using profile path /var/folders/0m/kmxmf5vn1y741ld9wvpgmhvh0000gn/T/rust_mozprofile.yHOzBB4sdPEN
1489599669486	geckodriver::marionette	INFO	Starting browser /Applications/Firefox.app/Contents/MacOS/firefox-bin with args []
1489599669508	geckodriver::marionette	INFO	Connecting to Marionette on localhost:51365
1489599671817	Marionette	INFO	Listening on port 51365
Mar 15, 2017 1:41:12 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: W3C
2017-03-15 13:41:12.293 plugin-container[67734:7956054] *** CFMessagePort: bootstrap_register(): failed 1100 (0x44c) 'Permission denied', port = 0x983b, name = 'com.apple.tsm.portname'
See /usr/include/servers/bootstrap_defs.h for the error codes.
2017-03-15 13:41:12.294 plugin-container[67734:7956054] *** CFMessagePort: bootstrap_register(): failed 1100 (0x44c) 'Permission denied', port = 0x9b03, name = 'com.apple.CFPasteboardClient'
See /usr/include/servers/bootstrap_defs.h for the error codes.
1489599673245	Marionette	INFO	New connections will no longer be accepted
** Unknown exception behavior: -2147483647

Process finished with exit code 0
```

**Comment by andreastt** [comment]
It’s difficult to tell what is wrong here since you didn’t include the error you are seeing, but my guess from looking at the timestamps in the geckodriver log is that Selenium times out trying to connect and that Java then throws an exception.

Unfortunately I can’t be more specific and I’m afraid you need to debug this issue more closely.

**Comment by ggl-pratiksha** [comment]
I am facing the same issue. Did you find any solution?

**Comment by vaishgithub** [comment]
I am getting following error when tried to open url in firebox through selenium on Mac machine.

The firefox browser gets launched but doesn't open the url. I am able to launch chrome and open the url. The code is :
System.setProperty("webdriver.gecko.driver", "/Users/QA/Documents/Selennium_Classes/BrowserExes/geckodriver/");         
WebDriver driver = new FirefoxDriver();
driver.get("http://www.facebook.com");
======================
The selenium console shows following error:

2017-03-29 13:51:07.977 plugin-container[795:54793] * CFMessagePort: bootstrap_register(): failed 1100 (0x44c) 'Permission denied', port = 0x8f3f, name = 'com.apple.tsm.portname' See /usr/include/servers/bootstrap_defs.h for the error codes. 2017-03-29 13:51:07.980 plugin-container[795:54793] * CFMessagePort: bootstrap_register(): failed 1100 (0x44c) 'Permission denied', port = 0x4b1b, name = 'com.apple.CFPasteboardClient' See /usr/include/servers/bootstrap_defs.h for the error codes. 2017-03-29 13:51:07.980 plugin-container[795:54793] void __CFPasteboardSetup() : Failed to allocate communication port for com.apple.CFPasteboardClient; this is likely due to sandbox restrictions Exception in thread "main" org.openqa.selenium.SessionNotCreatedException: Unable to create new remote session. desired capabilities = Capabilities [{marionette=true, browserName=firefox, moz:firefoxOptions=org.openqa.selenium.firefox.FirefoxOptions@6b9651f3, version=, platform=ANY, firefox_profile=org.openqa.selenium.firefox.FirefoxProfile@38bc8ab5}], required capabilities = Capabilities [{}] Build info: version: '3.2.0', revision: '8c03df6b79', time: '2017-02-23 10:51:31 +0000' System info: host: 'MacBook-Pro.local', ip: ‘xxx.xxx.x.x’, os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.11.6', java.version: '1.8.0_111' Driver info: driver.version: FirefoxDriver at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:91) at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:141) at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:82) at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:604) at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:244) at org.openqa.selenium.remote.RemoteWebDriver.(RemoteWebDriver.java:131) at org.openqa.selenium.firefox.FirefoxDriver.(FirefoxDriver.java:293) at org.openqa.selenium.firefox.FirefoxDriver.(FirefoxDriver.java:272) at org.openqa.selenium.firefox.FirefoxDriver.(FirefoxDriver.java:267) at org.openqa.selenium.firefox.FirefoxDriver.(FirefoxDriver.java:263) at org.openqa.selenium.firefox.FirefoxDriver.(FirefoxDriver.java:122) at TestCase.resources.main(resources.java:37)

**Comment by DeveshDobriyal** [comment]
i have the same issue.. thanks for putting up this issue.
