### ISSUE TITLE
HTTP Status: '404' -> incorrect JSON status mapping for 'unknown error' (500 expected)

### ISSUE THREAD

**Issue by tmbenhura** [mozilla/geckodriver#551]
In order to help us efficiently investigate your issue, please provide the following information:

## Firefox Version
FF52

## Platform
Windows 10 64bit, Core i7 

## Steps to reproduce -
```
			driver.findElement(By.id("password")).sendKeys(password);
			driver.findElement(By.cssSelector("li > form > .btn-primary")).click();
			System.out.print("Logging In");
```

The password is entered, but the button is never clicked.

FF52
Selenium Java 3.3.0
Geckodriver 0.15

Trace:
```
1489680942359	hyper::header	TRACE	Headers.set( "Connection", Connection([Close]) )
1489680942359	hyper::http::h1	TRACE	Sized read, remaining=72
1489680942359	hyper::http::h1	TRACE	Sized read: 32
1489680942359	hyper::http::h1	TRACE	Sized read, remaining=40
1489680942359	hyper::http::h1	TRACE	Sized read: 40
1489680942359	hyper::http::h1	TRACE	Sized read, remaining=0
1489680942359	webdriver::server	DEBUG	Got request POST AbsolutePath("/session/0c5f908c-e268-42f5-80eb-88fca47fbeac/element")
1489680942359	webdriver::command	DEBUG	Got request body {"value":"li > form > .btn-primary","using":"css selector"}
1489680942359	geckodriver::marionette	DEBUG	→ 93:[0,12,"findElement",{"using":"css selector","value":"li > form > .btn-primary"}]
1489680942360	Marionette	TRACE	conn0 -> [0,12,"findElement",{"using":"css selector","value":"li > form > .btn-primary"}]
1489680972375	Marionette	TRACE	conn0 <- [1,12,{"error":"no such element","message":"Unable to locate element: li > form > .btn-primary","stacktrace":"WebDriverError@chrome://marionette/content/error.js:160:5\nNoSuchElementError@chrome://marionette/content/error.js:313:5\nelement.find/</<@chrome://marionette/content/element.js:267:16\n"},null]
1489680972375	geckodriver::marionette	DEBUG	← [1,12,{"error":"no such element","message":"Unable to locate element: li > form > .btn-primary","stacktrace":"WebDriverError@chrome://marionette/content/error.js:160:5\nNoSuchElementError@chrome://marionette/content/error.js:313:5\nelement.find/</<@chrome://marionette/content/element.js:267:16\n"},null]
1489680972376	webdriver::server	DEBUG	Returning status NotFound
1489680972376	webdriver::server	DEBUG	Returning body {"value":{"error":"no such element","message":"Unable to locate element: li > form > .btn-primary","stacktrace":"stack backtrace:\n   0:           0x61f07f - <no info>\n   1:           0x61fe59 - <no info>\n   2:           0x43b0b5 - <no info>\n   3:           0x420313 - <no info>\n   4:           0x408307 - <no info>\n   5:           0x6750f9 - <no info>\n   6:           0x416877 - <no info>\n   7:           0x66ed53 - <no info>\n   8:     0x7ffe9f578102 - BaseThreadInitThunk"}}
1489680972376	hyper::header	TRACE	Headers.set( "Content-Type", ContentType(Mime(Application, Json, [(Charset, Utf8)])) )
1489680972376	hyper::header	TRACE	Headers.set( "Cache-Control", CacheControl([NoCache]) )
1489680972376	hyper::header	TRACE	Headers.set( "Content-Length", ContentLength(497) )
1489680972376	hyper::server::response	DEBUG	writing head: Http11 NotFound
1489680972376	hyper::header	TRACE	Headers.set( "Date", Date(HttpDate(Tm { tm_sec: 12, tm_min: 16, tm_hour: 16, tm_mday: 16, tm_mon: 2, tm_year: 117, tm_wday: 4, tm_yday: 74, tm_isdst: 0, tm_utcoff: 0, tm_nsec: 376135900 })) )
1489680972376	hyper::server::response	DEBUG	headers [
Headers { Connection: close
, Content-Type: application/json; charset=utf-8
, Cache-Control: no-cache
, Content-Length: 497
, Date: Thu, 16 Mar 2017 16:16:12 GMT
, }]
1489680972376	hyper::server::response	DEBUG	write 497 bytes
1489680972376	hyper::server::response	TRACE	ending
1489680972376	hyper::server	DEBUG	keep_alive = false for 127.0.0.1:51730
1489680972376	hyper::server	DEBUG	keep_alive loop ending for 127.0.0.1:51730
Mar 16, 2017 6:16:12 PM org.openqa.selenium.remote.ErrorCodes toStatus
INFO: HTTP Status: '404' -> incorrect JSON status mapping for 'unknown error' (500 expected)

```
The test was working properly in Eclipse Luna, the error started when I moved to IntellJ Community Edition. Production build still works fine.

FYI - Changing to Selenium 3.3.1 gives

```
org.openqa.selenium.SessionNotCreatedException: Expected browser binary location, but unable to find binary in default location, no 'moz:firefoxOptions.binary' capability provided, and no binary flag set on the command line (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 0 milliseconds
Build info: version: 'unknown', revision: '5234b32', time: '2017-03-10 09:00:17 -0800'
System info: host: 'MY-PC', ip: '196.19.4.10', os.name: 'Windows 8.1', os.arch: 'amd64', os.version: '6.3', java.version: '1.8.0_40'
Driver info: driver.version: FirefoxDriver
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:216)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:168)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:367)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:113)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:141)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:82)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:604)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:244)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:131)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:218)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:125)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:150)
	at MyApp.test(MyApp.java:57)
```

The ip, os.name, os.arch reported by the sytem info are also incorrect. I use Windows 10 with and Intel i7 64 bit processor.

I had already specified the binary via System.setProperty("webdriver.firefox.bin", path to FF);

**Comment by jgraham** [comment]
As far as I can tell this is a selenium issue; either you are not using the API correctly or there is a bug in the way way API sets geckodriver capabilities. Please file a bug on the selenium issue tracker.
