### ISSUE TITLE
org.openqa.selenium.WebDriverException: Not a Number exception is thrown when setting implicitlyWait or pageLoadTimeout

### ISSUE THREAD

**Issue by cief0325** [mozilla/geckodriver#572]
## Firefox Version
47.0.1
geckodriver-v0.15.0-win64

## Platform
Windows

## Steps to reproduce -
Continue from #564.
1. Instantiate new local driver:WebDriver driver= new FirefoxDriver();
2. Execute command: driver.manage().timeouts().implicitlyWait(15, TimeUnit.SECONDS);

Exception is thrown.
The same exception is thrown for timeouts().pageLoadTimeout(15, TimeUnit.SECONDS);

Exception trace:

org.openqa.selenium.WebDriverException: Not a Number
Build info: version: '3.3.1', revision: '5234b325d5', time: '2017-03-10 09:10:29 +0000'
System info: host: 'LIVEDB', ip: '192.168.0.31', os.name: 'Windows Server 2008 R2', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_111'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{rotatable=false, raisesAccessibilityExceptions=false, appBuildId=20160623154057, version=47.0.1, platform=XP, proxy={}, command_id=1, specificationLevel=0, acceptSslCerts=false, browserVersion=47.0.1, platformVersion=6.1, XULappId={ec8030f7-c20a-464f-9b0e-13a3a9e97384}, browserName=Firefox, takesScreenshot=true, takesElementScreenshot=true, platformName=Windows_NT, device=desktop}]
Session ID: e803e998-9fe5-4f4c-9e1e-acdfd3733954
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:133)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:99)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:43)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:163)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:82)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:604)
	at org.openqa.selenium.firefox.FirefoxDriver.access$100(FirefoxDriver.java:67)
	at org.openqa.selenium.firefox.FirefoxDriver$1$1.implicitlyWait(FirefoxDriver.java:288)

**Comment by cief0325** [comment]
UPD.
The same setup works fine with geckodriver-v0.14.0-win64.

**Comment by andreastt** [comment]
Firefox 47 isn’t supported by geckodriver and you need to use the very latest Selenium bindings for this to work.
