### ISSUE TITLE
Getting exception with Gechodriver win64 Selenium 3.3.1

### ISSUE THREAD

**Issue by dramer** [mozilla/geckodriver#629]
DesiredCapabilities capabillities = DesiredCapabilities.firefox();
		capabillities.setCapability("platform", osInfo.getOSName());
		capabillities.setCapability("name", "some text");

driver = new FirefoxDriver(capabillities)

Exception in thread "main" org.openqa.selenium.WebDriverException: Not a Number
Build info: version: '3.3.1', revision: '5234b325d5', time: '2017-03-10 09:10:29 +0000'
System info: host: '', ip: '10.100.26.75', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_91'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{rotatable=false, raisesAccessibilityExceptions=false, marionette=true, appBuildId=20160502172042, version=, platform=XP, proxy={}, specificationLevel=1, acceptSslCerts=false, browserVersion=46.0.1, platformVersion=6.1, name=sTest Self Test - local Chrome web driver, XULappId={ec8030f7-c20a-464f-9b0e-13a3a9e97384}, browserName=Firefox, takesScreenshot=true, javascriptEnabled=true, takesElementScreenshot=true, platformName=Windows_NT, device=desktop}]
Session ID: 67cf3a73-09e9-4921-921a-e00f1cef95c6
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:133)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:99)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:43)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:163)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:82)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:604)
	at org.openqa.selenium.firefox.FirefoxDriver.access$100(FirefoxDriver.java:67)
	at org.openqa.selenium.firefox.FirefoxDriver$1$1.implicitlyWait(FirefoxDriver.java:288)
	at bichromate.core.sTestWebDriverFactory.createWebDriver(sTestWebDriverFactory.java:1090)
	at bichromate.core.sTestScreenCaptureFactory$Test.main(sTestScreenCaptureFactory.java:324)

**Comment by andreastt** [comment]
Firefox 46 is not supported, you should consider using [Firefox Nightly](https://nightly.mozilla.org/).

I believe this particular issue to do with setting timeout durations has been solved with Selenium 3.3.1, geckodriver 0.15.0, and Firefox Nightly.
