### ISSUE TITLE
Sendkeys unable to send text  in text field and got exception  

### ISSUE THREAD

**Issue by Ahemd-ali** [mozilla/geckodriver#680]
In order to help us efficiently investigate your issue, please provide the following information:

## Firefox Version 54.0b1 (32-bit)
From the "About" dialog.

## Platform Window
e.g. Windows

## Steps to reproduce -
               driver.manage().timeouts().implicitlyWait(30, TimeUnit.SECONDS);
	       driver.get("https://ad:vpYrUzx8AT@www-stage.elabelz.com/en_ae/");
	       driver.switchTo().alert().accept();
	       driver.findElement(By.xpath(".//*[@id='site_header']/div[1]/div/ul[1]/li[3]/a")).click();
	       Thread.sleep(4000);
	        driver.findElement(By.xpath(".//*[@id='email']")).sendKeys("Test");
	    driver.close();

 - [ ] A *Exception*Apr 24, 2017 11:30:03 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: W3C
JavaScript warning: https://dkd7fojk2ukc9.cloudfront.net/skin/frontend/apptha/superstore/js/lib/jquery-1.10.2.min.js, line 1: Using //@ to indicate sourceMappingURL pragmas is deprecated. Use //# instead
JavaScript error: https://s3-eu-west-1.amazonaws.com/shoptimally-ire/dist/special/elabelz/nwa.js, line 3: TypeError: this._storage is undefined
JavaScript warning: https://dkd7fojk2ukc9.cloudfront.net/skin/frontend/apptha/superstore/js/lib/jquery-1.10.2.min.js, line 1: Using //@ to indicate sourceMappingURL pragmas is deprecated. Use //# instead
JavaScript error: https://dkd7fojk2ukc9.cloudfront.net/skin/frontend/apptha/superstore/js/neowize_widget.js, line 48: TypeError: dataLayer[0] is undefined
Exception in thread "main" org.openqa.selenium.InvalidArgumentException: Expected [object Undefined] undefined to be a string
Build info: version: '3.3.1', revision: '5234b325d5', time: '2017-03-10 09:10:29 +0000'
System info: host: 'DESKTOP-QBEO8F3', ip: '192.168.100.145', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_131'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{moz:profile=C:\Users\PROGOS~1\AppData\Local\Temp\rust_mozprofile.M9X2UxAKvvqs, rotatable=false, timeouts={implicit=0, pageLoad=300000, script=30000}, pageLoadStrategy=normal, platform=ANY, specificationLevel=0, moz:accessibilityChecks=false, acceptInsecureCerts=false, browserVersion=54.0, platformVersion=10.0, moz:processID=8016, browserName=firefox, platformName=windows_nt}]
Session ID: 04a6079b-c77b-4e6e-bd0c-918e2fe307c7
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:133)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:99)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:43)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:163)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:82)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:604)
	at org.openqa.selenium.remote.RemoteWebElement.execute(RemoteWebElement.java:274)
	at org.openqa.selenium.remote.RemoteWebElement.sendKeys(RemoteWebElement.java:98)
	at Testcalss.main(Testcalss.java:23)).

 - [ ] A [trace level log](https://github.com/mozilla/geckodriver#firefox-capabilities) from a geckodriver session that demonstrates the problem using the minimal example file. Note: this is *not* the same as a selenium log.

** If any of the above are missing we will have to unfortunately close your issue. We will gladly reopen the issue once all the information requested has been added **

**Comment by andreastt** [comment]
I suspect you will need Selenium 3.4 or newer.

**Comment by Ahemd-ali** [comment]
Ok let me download this 3.4 and will let you know thanks for your inspection.

**Comment by andreastt** [comment]
@Ahemd-ali Please file a new bug and include a trace-level geckodriver log. See the README on how to crank up the geckodriver logging verbosity.

**Comment by Quilmont** [comment]
Any update?
