### ISSUE TITLE
Element.Sendkeys with new security policy of firefox 53!?

### ISSUE THREAD

**Issue by gnh1201** [mozilla/geckodriver#692]
In order to help us efficiently investigate your issue, please provide the following information:

## Firefox Version
Firefox 53.0

## Platform
Windows

## Steps to reproduce

Hello.

Since a few days ago, I can not use Element.Sendkeys method in Firefox 53.
Mozilla Firefox notified to me about "new security policy" in their browser. so I was add it.
> fxProfile.SetPreference("browser.tabs.remote.force-enable",` true);

Related policy: [Accessibility not available during multi-process support - Firefox Help](https://support.mozilla.org/en-US/kb/accessibility-and-ppt)

but, I can not access element. What happened?

> Element.SendKeys(username);`

```
System.InvalidOperationException
  HResult=-2146233079
  Message=Expected [object Undefined] undefined to be a string (IndexOutOfBounds)
  Source=WebDriver
  StackTrace:
       OpenQA.Selenium.Remote.RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse)
       OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
       OpenQA.Selenium.Remote.RemoteWebElement.SendKeys(String text)
       AwesomeConsole.Awesome.loginAsUser(String username, String password) File C:\Users\Administrator\Documents\Visual Studio 2015\Projects\AwesomeConsole\AwesomeConsole\Awesome.cs:Line 76
       AwesomeConsole.Program.Main(String[] args) File C:\Users\Administrator\Documents\Visual Studio 2015\Projects\BackcardConsole\BackcardConsole\Program.cs:Line 27
       System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
       System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
       Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
       System.Threading.ThreadHelper.ThreadStart_Context(Object state)
       System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
       System.Threading.ThreadHelper.ThreadStart()
  InnerException: 
```

Related issue: #608 #659 #668

**Comment by gnh1201** [comment]
I was downgraded to Firefox 52.0. Old version is works fine.

**Comment by andreastt** [comment]
You need to upgrade to Selenium 3.4 or greater and geckodriver 0.16.1 or greater. The issues you are describing have been resolved.

**Comment by lukasQuatro** [comment]
well, I have Selenium 3.4, geckodriver 0.16.1 and I'm having the same issues =S

this is the error I get:

```
System.InvalidOperationException occurred
  HResult=0x80131509
  Message=Missing 'text' parameter (IndexOutOfBounds)
  Source=WebDriver
  StackTrace:
   at OpenQA.Selenium.Remote.RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse)
   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Remote.RemoteWebElement.SendKeys(String text)
```

**Comment by andreastt** [comment]
@lukasQuatro That is probably because you’re using a Firefox version earlier than 53.

**Comment by lukasQuatro** [comment]
@andreastt I have FF v53.0, 32bits

**Comment by andreastt** [comment]
@lukasQuatro And did you test with Firefox Nightly? In any case, the error you’re describing is not related to this issue. Please open a new one.
