### ISSUE TITLE
'Permission denied' when using Firefox 52, Selenium 3.3.1 and geckodriver 0.16.1 on macOS

### ISSUE THREAD

**Issue by kvalev** [mozilla/geckodriver#706]
## Firefox Version
52.0.1 (64-bit)

## Platform
OSX

## Steps to reproduce -
When using Selenium 3.3.1, geckodriver 0.16.1 and Firefox 52.0.1 in a maven project, I get the same error as #526 (which has been closed). The previously created issue contains a script to reproduce the error. geckodriver session log is:
```
1493543472691	webdriver::httpapi	DEBUG	Creating routes
1493543472695	geckodriver	INFO	Listening on 127.0.0.1:46590
1493543472778	webdriver::server	DEBUG	→ POST /session {
  "desiredCapabilities": {
    "phantomjs.binary.version": "2.1.1",
    "marionette": true,
    "ieDriverBinary": "path to IEDriverServer_Win32_2.52.0.exe",
    "browserName": "firefox",
    "moz:firefoxOptions": {
      "prefs": {},
      "log": {
        "level": "trace"
      },
      "args": []
    },
    "version": "",
    "platform": "ANY"
  },
  "requiredCapabilities": {},
  "capabilities": {
    "desiredCapabilities": {
      "phantomjs.binary.version": "2.1.1",
      "marionette": true,
      "ieDriverBinary": "path to IEDriverServer_Win32_2.52.0.exe",
      "browserName": "firefox",
      "moz:firefoxOptions": {
        "prefs": {},
        "log": {
          "level": "trace"
        },
        "args": []
      },
      "version": "",
      "platform": "ANY"
    },
    "requiredCapabilities": {}
  },
  "alwaysMatch": {
    "phantomjs.binary.version": "2.1.1",
    "ieDriverBinary": "path to IEDriverServer_Win32_2.52.0.exe",
    "version": "",
    "platform": "ANY"
  },
  "firstMatch": [
    {
      "browserName": "firefox",
      "moz:firefoxOptions": {
        "prefs": {},
        "log": {
          "level": "trace"
        },
        "args": []
      }
    }
  ]
}
1493543472807	geckodriver::marionette	INFO	Starting browser /Applications/Firefox.app/Contents/MacOS/firefox-bin with args ["-marionette"]
1493543472810	geckodriver::marionette	TRACE	  connection attempt 0/600
1493543472914	geckodriver::marionette	TRACE	  connection attempt 1/600
1493543473018	geckodriver::marionette	TRACE	  connection attempt 2/600
1493543473123	geckodriver::marionette	TRACE	  connection attempt 3/600
1493543473227	geckodriver::marionette	TRACE	  connection attempt 4/600
1493543473330	geckodriver::marionette	TRACE	  connection attempt 5/600
1493543473432	geckodriver::marionette	TRACE	  connection attempt 6/600
1493543473499	Marionette	DEBUG	Marionette enabled via command-line flag
1493543473537	geckodriver::marionette	TRACE	  connection attempt 7/600
1493543473568	Marionette	INFO	Listening on port 55086
1493543473641	geckodriver::marionette	DEBUG	Connected to Marionette on localhost:55086
1493543473662	Marionette	DEBUG	Accepted connection conn0 from 127.0.0.1:55105
1493543473679	geckodriver::marionette	TRACE	← {"applicationType":"gecko","marionetteProtocol":3}
1493543473679	geckodriver::marionette	TRACE	→ 62:[0,1,"newSession",{"capabilities":{"desiredCapabilities":{}}}]
1493543473683	Marionette	TRACE	conn0 -> [0,1,"newSession",{"capabilities":{"desiredCapabilities":{}}}]
1493543473686	Marionette	CONFIG	Matched capabilities: {"browserName":"firefox","browserVersion":"52.0.1","platformName":"darwin","platformVersion":"16.5.0","pageLoadStrategy":"normal","acceptInsecureCerts":false,"timeouts":{"implicit":0,"page load":300000,"script":30000},"rotatable":false,"specificationLevel":0,"moz:processID":92165,"moz:profile":"/var/folders/rp/7lwtlxfs11g5v1k_9vxph_md2rygl_/T/rust_mozprofile.K3uW2OI88OAO","moz:accessibilityChecks":false}
1493543474692	Marionette	TRACE	conn0 <- [1,1,null,{"sessionId":"9bb18d55-69e0-cb4c-9ce9-c008dfb86bb1","capabilities":{"browserName":"firefox","browserVersion":"52.0.1","platformName":"darwin","platformVersion":"16.5.0","pageLoadStrategy":"normal","acceptInsecureCerts":false,"timeouts":{"implicit":0,"page load":300014935040,"s3474692	cgeckriptodr":30000},"riveor::tmariatable":false,"specificationLevelo":n0ett,e"moz:processID	"T:92RACE	← [1,1,165,n"ulmoz:l,{"sepssionIrofile":"/d"v:"9bb1a8d55-69er0-/folcb4c-9dceer9s-c008dfb86bb1","capabilities":{"browserName":"firefox","browserVersion":"52.0.1","platformName":"darwin","p/latfrormVeprsion":"1/6.75.lw0tlxfs",11g"pageLoadStrategy":"normal","acceptInsecureCerts":false,"timeouts":{"implicit":0,"page load":300000,"script":30000},"rotatable":false,"5sv1k_9vxph_mdp2ryegl_cificationLevel":0,"m/T/rust_oz:pmroocezpsrofile.K3uW2OI88OAO","moz:accessibilityChsecks":falIse}D"}]
:92165,"moz:profile":"/var/folders/rp/7lwtlxfs11g5v1k_9vxph_md2rygl_/T/rust_mozprofile.K3uW2OI88OAO","moz:accessibilityChecks":false}}]
1493543474692	webdriver::server	DEBUG	← 200 OK {"value": {"sessionId":"9bb18d55-69e0-cb4c-9ce9-c008dfb86bb1","capabilities":{"acceptInsecureCerts":false,"browserName":"firefox","browserVersion":"52.0.1","moz:accessibilityChecks":false,"moz:processID":92165,"moz:profile":"/var/folders/rp/7lwtlxfs11g5v1k_9vxph_md2rygl_/T/rust_mozprofile.K3uW2OI88OAO","pageLoadStrategy":"normal","platformName":"darwin","platformVersion":"16.5.0","rotatable":false,"specificationLevel":0,"timeouts":{"implicit":0,"page load":300000,"script":30000}}}}
2017-04-30 11:11:14.762 plugin-container[92166:2841982] *** CFMessagePort: bootstrap_register(): failed 1100 (0x44c) 'Permission denied', port = 0x9d3b, name = 'com.apple.tsm.portname'
See /usr/include/servers/bootstrap_defs.h for the error codes.
2017-04-30 11:11:14.763 plugin-container[92166:2841982] *** CFMessagePort: bootstrap_register(): failed 1100 (0x44c) 'Permission denied', port = 0xa103, name = 'com.apple.CFPasteboardClient'
See /usr/include/servers/bootstrap_defs.h for the error codes.

```

**Comment by wswebcreation** [comment]
Hi @kvalev , 

Have you tried using selenium 3.4 or higher, according to the [chances](https://github.com/mozilla/geckodriver/blob/master/CHANGES.md#0160-2016-04-21) this is needed.

I currently work with Angular 2+, Firefox 53, Geckdriver 0.16.1 and Selenium 3.4 and it works without any warnings

Grtz

Wim

**Comment by andreastt** [comment]
The line

    2017-04-30 11:11:14.762 plugin-container[92166:2841982] *** CFMessagePort: bootstrap_register(): failed 1100 (0x44c) 'Permission denied', port = 0x9d3b, name = 'com.apple.tsm.portname'

that you see in the log is unrelated to geckodriver or Marionette. You shouldn’t have to worry about it.

**Comment by cherry0228** [comment]
have you fixed the problem, i am facing same issue

**Comment by andreastt** [comment]
@cherry0228 As I said, this isn’t a problem with geckodriver.

**Comment by kvalev** [comment]
@cherry0228 The problem was that selenium 3.3.1 is not compatible with geckodriver 0.16.1 - you will have to use selenium 3.4.

**Comment by cherry0228** [comment]
thanks @kvalev, i tried with selenium 3.3.1 and geckdriver 0.16.1 and FF 52.1.1 (64-bit), still got the issue

Build info: version: '3.3.1', revision: '5234b32', time: '2017-03-10 09:04:52 -0800'
System info: host: '9801a79d82b5.ant.amazon.com', ip: '192.168.31.8', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.11.6', java.version: '1.8.0_131'
Driver info: driver.version: unknown
	at org.openqa.selenium.remote.server.FirefoxDriverProvider.callConstructor(FirefoxDriverProvider.java:89)
	at org.openqa.selenium.remote.server.FirefoxDriverProvider.newInstance(FirefoxDriverProvider.java:63)
	at org.openqa.selenium.remote.server.DefaultDriverFactory.newInstance(DefaultDriverFactory.java:60)
	at org.openqa.selenium.remote.server.DefaultSession$BrowserCreator.call(DefaultSession.java:222)
	at org.openqa.selenium.remote.server.DefaultSession$BrowserCreator.call(DefaultSession.java:209)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at org.openqa.selenium.remote.server.DefaultSession$1.run(DefaultSession.java:176)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	... 1 more
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.server.FirefoxDriverProvider.callConstructor(FirefoxDriverProvider.java:81)
	... 9 more
Caused by: org.openqa.selenium.SessionNotCreatedException: Unable to create new remote session. desired capabilities = Capabilities [{proxy={"proxyAutoconfigUrl":null,"autodetect":false,"socksUsername":null,"socksPassword":null,"httpProxy":null,"proxyType":"DIRECT","noProxy":null,"ftpProxy":null,"socksProxy":null,"hCode":198086692,"class":"org.openqa.selenium.Proxy","sslProxy":null}, browserName=firefox, javascriptEnabled=true, moz:firefoxOptions={binary=Optional.empty, args=[], legacy=null, logLevel=null, prefs={}, profile=org.openqa.selenium.firefox.FirefoxProfile@323a80b0}, version=, platform=ANY, firefox_profile=org.openqa.selenium.firefox.FirefoxProfile@323a80b0}], required capabilities = Capabilities [{moz:firefoxOptions={binary=Optional.empty, args=[], legacy=null, logLevel=null, prefs={}, profile=org.openqa.selenium.firefox.FirefoxProfile@323a80b0}, firefox_profile=org.openqa.selenium.firefox.FirefoxProfile@323a80b0}]
Build info: version: '3.3.1', revision: '5234b32', time: '2017-03-10 09:04:52 -0800'
System info: host: '9801a79d82b5.ant.amazon.com', ip: '192.168.31.8', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.11.6', java.version: '1.8.0_131'
Driver info: driver.version: FirefoxDriver
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:126)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:141)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:82)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:604)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:244)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:131)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:218)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:125)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:150)
	... 14 more
06:35:46.641 WARN - Exception: Unable to create new remote session. desired capabilities = Capabilities [{proxy={"proxyAutoconfigUrl":null,"autodetect":false,"socksUsername":null,"socksPassword":null,"httpProxy":null,"proxyType":"DIRECT","noProxy":null,"ftpProxy":null,"socksProxy":null,"hCode":198086692,"class":"org.openqa.selenium.Proxy","sslProxy":null}, browserName=firefox, javascriptEnabled=true, moz:firefoxOptions={binary=Optional.empty, args=[], legacy=null, logLevel=null, prefs={}, profile=org.openqa.selenium.firefox.FirefoxProfile@323a80b0}, version=, platform=ANY, firefox_profile=org.openqa.selenium.firefox.FirefoxProfile@323a80b0}], required capabilities = Capabilities [{moz:firefoxOptions={binary=Optional.empty, args=[], legacy=null, logLevel=null, prefs={}, profile=org.openqa.selenium.firefox.FirefoxProfile@323a80b0}, firefox_profile=org.openqa.selenium.firefox.FirefoxProfile@323a80b0}]
Build info: version: '3.3.1', revision: '5234b32', time: '2017-03-10 09:04:52 -0800'
System info: host: '9801a79d82b5.ant.amazon.com', ip: '192.168.31.8', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.11.6', java.version: '1.8.0_131'
Driver info: driver.version: FirefoxDriver
2017-06-07 06:35:46.653 plugin-container[95822:2419924] *** CFMessagePort: bootstrap_register(): failed 1100 (0x44c) 'Permission denied', port = 0x8b3f, name = 'com.apple.tsm.portname'
See /usr/include/servers/bootstrap_defs.h for the error codes.
2017-06-07 06:35:46.654 plugin-container[95822:2419924] *** CFMessagePort: bootstrap_register(): failed 1100 (0x44c) 'Permission denied', port = 0x8d0b, name = 'com.apple.CFPasteboardClient'
See /usr/include/servers/bootstrap_defs.h for the error codes.
2017-06-07 06:35:46.654 plugin-container[95822:2419924] void __CFPasteboardSetup() : Failed to allocate communication port for com.apple.CFPasteboardClient; this is likely due to sandbox restrictions

**Comment by kvalev** [comment]
@cherry0228 You need selenium __3.4__, not 3.3.1

**Comment by phoebusliang** [comment]
ff 53.0.3 
selenium 3.4.0
os: macOS 10.12.5

System.setProperty("webdriver.gecko.driver", "/usr/local/bin/geckodriver");
DesiredCapabilities capabilities = DesiredCapabilities.firefox();
DRIVER = new FirefoxDriver(capabilities);

error:
2017-06-08 15:15:04.241 plugin-container[18396:1336924] *** CFMessagePort: bootstrap_register(): failed 1100 (0x44c) 'Permission denied', port = 0x993b, name = 'com.apple.tsm.portname'
See /usr/include/servers/bootstrap_defs.h for the error codes.
2017-06-08 15:15:04.242 plugin-container[18396:1336924] *** CFMessagePort: bootstrap_register(): failed 1100 (0x44c) 'Permission denied', port = 0x9d03, name = 'com.apple.CFPasteboardClient'
See /usr/include/servers/bootstrap_defs.h for the error codes.

**Comment by whimboo** [comment]
@phoebusliang there is no error displayed. All this is just normal log output.

**Comment by iBasit** [comment]
I have 
selenium 3.4.0
firefox: 54.0
mac: 10.12.5 

```
1497568614711	geckodriver	INFO	Listening on 127.0.0.1:4444
1497568618948	geckodriver::marionette	INFO	Starting browser /Applications/Firefox.app/Contents/MacOS/firefox-bin with args ["-marionette"]
1497568621275	Marionette	INFO	Listening on port 50959
1497568621570	Marionette	DEBUG	loaded listener.js
2017-06-16 00:17:01.669 plugin-container[1369:17819] *** CFMessagePort: bootstrap_register(): failed 1100 (0x44c) 'Permission denied', port = 0x913b, name = 'com.apple.tsm.portname'
See /usr/include/servers/bootstrap_defs.h for the error codes.
2017-06-16 00:17:01.669 plugin-container[1369:17819] *** CFMessagePort: bootstrap_register(): failed 1100 (0x44c) 'Permission denied', port = 0x9503, name = 'com.apple.CFPasteboardClient'
See /usr/include/servers/bootstrap_defs.h for the error codes.
1497568649248	Marionette	DEBUG	loaded listener.js

```

**Comment by alxliken** [comment]
How could it work fine the first time I run it and then returning 'Permission denied' error message after?

**Comment by whimboo** [comment]
We said it multiple times that this is not a problem with geckodriver or marionette, but just some log output. I'm going to lock down this issue now.
