### ISSUE TITLE
Selenium Firefox driver doesn't work with Firefox ESR 45.9.0 under Debian Jessie

### ISSUE THREAD

**Issue by gouessej** [mozilla/geckodriver#726]
OS:  Debian Jessie
Architecture: ARM 7 (armhf v7)
Selenium Version: 3.4.0
Browser:  Firefox
Browser Version: 45.9.0
Gecko driver version: 0.16.1

## Expected Behavior -
new FirefoxDriver() doesn't throw any exception.

## Actual Behavior -

```
org.openqa.selenium.SessionNotCreatedException: Unable to find a matching set of capabilities
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: host: 'A20-OLinuXino', ip: '127.0.0.1', os.name: 'Linux', os.arch: 'arm', os.version: '3.4.103-00033-g9a1cd03-dirty', java.version: '1.8.0_111'
Driver info: driver.version: FirefoxDriver
remote stacktrace: stack backtrace:
   0: 0xb6de95b3 - backtrace::backtrace::trace::h8166ac046b01de0f
   1: 0xb6de9acb - backtrace::capture::Backtrace::new::hb5a725a088a2a2fc
   2: 0xb6dab093 - geckodriver::marionette::MarionetteHandler::create_connection::h826627e00cb80122
   3: 0xb6db30fb - >::handle_command::hea45c68e72b3846e
   4: 0xb6da784f - webdriver::server::start::{{closure}}::h3085395b806d111c
   5: 0xb6d79be3 - std::panicking::try::do_call::h86a6e0cb77ef092f
   6: 0xb6f06157 - panic_unwind::__rust_maybe_catch_panic
                at /buildslave/rust-buildbot/slave/stable-dist-rustc-cross-host-linux/build/src/libpanic_unwind/lib.rs:98
   7: 0xb6d8bc1f - >::call_box::h995a340dc6da2f87
   8: 0xb6efff53 - alloc::boxed::{{impl}}::call_once<(),()>
                at /buildslave/rust-buildbot/slave/stable-dist-rustc-cross-host-linux/build/src/liballoc/boxed.rs:624
                 - std::sys_common::thread::start_thread
                at /buildslave/rust-buildbot/slave/stable-dist-rustc-cross-host-linux/build/src/libstd/sys_common/thread.rs:21
                 - std::sys::imp::thread::{{impl}}::new::thread_start
                at /buildslave/rust-buildbot/slave/stable-dist-rustc-cross-host-linux/build/src/libstd/sys/unix/thread.rs:84
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
    at org.openqa.selenium.remote.W3CHandshakeResponse.lambda$new$0(W3CHandshakeResponse.java:57)
    at org.openqa.selenium.remote.W3CHandshakeResponse.lambda$getResponseFunction$2(W3CHandshakeResponse.java:104)
    at org.openqa.selenium.remote.ProtocolHandshake.lambda$createSession$22(ProtocolHandshake.java:365)
    at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
    at java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:958)
    at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
    at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498)
    at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
    at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
    at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152)
    at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
    at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:464)
    at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:368)
    at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:159)
    at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:142)
    at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:82)
    at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:637)
    at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:250)
    at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:236)
    at org.openqa.selenium.remote.RemoteWebDriver.(RemoteWebDriver.java:137)
    at org.openqa.selenium.firefox.FirefoxDriver.(FirefoxDriver.java:191)
    at org.openqa.selenium.firefox.FirefoxDriver.(FirefoxDriver.java:108)
    at org.openqa.selenium.firefox.FirefoxDriver.(FirefoxDriver.java:137)
```

## Steps to reproduce -
```
import org.openqa.selenium.firefox.FirefoxDriver;
public class Main {
    public static void main(String[] args) {
           new FirefoxDriver();
    }
}
```

**Comment by andreastt** [comment]
Please attach a trace-level log from geckodriver.

**Comment by jgraham** [comment]
I don't think we expect to support ESR45, do we? I certainly wouldn't be surprised if the capabilities handling on the marionette side chnaged enough that this doesn't work.

In any case it will certainly not work if `acceptInsecureCerts` isn't set to `false`.

**Comment by andreastt** [comment]
You’re right; I didn’t spot the Firefox version number above. Please retry with Firefox Nightly or one of the official release channel versions, and if that still doesn’t work, please feel free to report back.

**Comment by gouessej** [comment]
I use Selenium on an ARM single board computer and Firefox ESR 52.1.0 provided by the Mozilla Debian Team doesn't support ARM yet, that's why I'm stuck with Firefox ESR 45.9.0, which is the latest version in Debian Jessie even when I add the official backports.

How can I get the trace-level logs from geckodriver?

**Comment by andreastt** [comment]
Unfortunately we don’t support Firefox 45.9.0 ESR with geckodriver.

**Comment by andreastt** [comment]
See the README for further details on which Firefox release channels are: https://github.com/mozilla/geckodriver#supported-firefoxen

**Comment by gouessej** [comment]
Thank you. I'll be forced to use another web driver whereas I really wanted to mimic Firefox behaviour. Firefox ESR 52.1.0 is currently experimental in Debian Jessie.

**Comment by jgraham** [comment]
I would expect 52 to work reasonably well if you can update to that. Unfortunately the architecture of geckodriver makes it hard to retain full compatibility with older releases as we move through this transition cycle to the W3C protocol, and outdated ESR builds on a Tier 3 port aren't something we can easily justify spending time on.

**Comment by gouessej** [comment]
I understand your position, it's not a priority as most users can use a more up-to-date version of Firefox, that's why I tried to get Firefox 52 from the Debian Mozilla Team which is unfortunately available only for amd64 and i386 but not for ARM. I'll try the chrome driver with chromium in the meantime.

**Comment by bluejamesbond** [comment]
@gouessej @jgraham I am Debian Jessie with Firefox 52 which still produces the same issue for me.

**Comment by whimboo** [comment]
@bluejamesbond you provided basically no information. Please file a new issue and make sure to attach a trace level log.

**Comment by gouessej** [comment]
@bluejamesbond Maybe try with Firefox ESR 52 under Debian Stretch.

**Comment by andreastt** [comment]
FWIW with the latest geckodriver 0.17.0 release, we recommend using Firefox 53 or newer.

**Comment by danger89** [comment]
I still see a lot of problems:
https://github.com/SeleniumHQ/selenium/issues/3884
