### ISSUE TITLE
gecko driver issue with selenium java 3.4.0 in launching web browser

### ISSUE THREAD

**Issue by varshasahu** [mozilla/geckodriver#734]
In order to help us efficiently investigate your issue, please provide the following information:

## Firefox Version
firefox latest version.

## Platform
e.g. Windows 10

## Steps to reproduce -
Please provide a description of how to reproduce the problem, including the following essential elements:

package simple;
import org.openqa.selenium.WebDriver;

public class simple
{
	
	public static void main (String args[]){
	
	System.setProperty("webdriver.gecko.driver", "C:/Users/hp/Downloads");
	WebDriver driver = new WebDriver();

	
    driver.get("www.makemytrip.com");
    
    System.out.println("Successfully launched");
    
    driver.quit();
    
}
}
 Error showing -
Exception in thread "main" java.lang.IllegalStateException: The driver executable is a directory: C:\Users\hp\Downloads
	at com.google.common.base.Preconditions.checkState(Preconditions.java:518)
	at org.openqa.selenium.remote.service.DriverService.checkExecutable(DriverService.java:138)
	at org.openqa.selenium.remote.service.DriverService.findExecutable(DriverService.java:131)
	at org.openqa.selenium.firefox.GeckoDriverService.access$100(GeckoDriverService.java:41)
	at org.openqa.selenium.firefox.GeckoDriverService$Builder.findDefaultExecutable(GeckoDriverService.java:115)
	at org.openqa.selenium.remote.service.DriverService$Builder.build(DriverService.java:330)
	at org.openqa.selenium.firefox.FirefoxDriver.toExecutor(FirefoxDriver.java:207)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:108)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:104)
	at simple.simple.main(simple.java:11)
![java_error2](https://cloud.githubusercontent.com/assets/27557083/26033472/ceea7ecc-38ca-11e7-8e62-be882482bf28.png)

 - [ ] A *minimal* HTML file (or files) that can be used to reproduce the issue (this should not be your production site, unless you are unable to isolate the problem, but a page containing only the elements required to observe the problem).

 - [ ] A [trace level log](https://github.com/mozilla/geckodriver#firefox-capabilities) from a geckodriver session that demonstrates the problem using the minimal example file. Note: this is *not* the same as a selenium log.

** If any of the above are missing we will have to unfortunately close your issue. We will gladly reopen the issue once all the information requested has been added **

**Comment by AutomatedTester** [comment]
As the exception shows, you are giving a directory and it would appear that you need to pass the path to the executable for the Java bindings. if that isnt the case you will need to raise a Selenium issue.
