### ISSUE TITLE
Actions not yet working in chrome context

### ISSUE THREAD

**Issue by ChaseWPDEV** [mozilla/geckodriver#740]
## Firefox Version
53.0.2
## Selenium Version
3.4.1
## Geckodriver Version
0.16.1

## Platform
Linux, Ubuntu 16.04

## Steps to reproduce -
Attempting to execute an action chain in chrome context:
>>> d=webdriver.Firefox()
>>> d.set_context('chrome')
>>> urlbar=d.find_element('id','urlbar')
>>> gobtn=d.find_element('id','urlbar-go-button')
>>> actions=ActionChains(d)
>>> actions.send_keys_to_element(urlbar, "http://google.com")
>>> actions.click(gobtn)
>>> actions.perform()

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/common/action_chains.py", line 77, in perform
    self.w3c_actions.perform()
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/common/actions/action_builder.py", line 76, in perform
    self.driver.execute(Command.W3C_ACTIONS, enc)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 252, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: Command 'performActions' is not yet available in chrome context

geckodriver.log (not much here):
1494908339887	geckodriver	INFO	Listening on 127.0.0.1:54578
1494908340990	geckodriver::marionette	INFO	Starting browser /usr/lib/firefox/firefox.sh with args ["-marionette"]
1494908344749	Marionette	INFO	Listening on port 35144
1494908344832	Marionette	WARN	TLS certificate errors will be ignored for this session

Note: The above is, of course a trivial example of the problem--the use case is for testing a site requiring security device login, certificates etc. I'm just trying to get off the ground...

Thanks,

**Comment by ChaseWPDEV** [comment]
I'm an idiot--just noticed this was 100% selenium, not gecko...
