### ISSUE TITLE
browser.html is giving Permission denied to access property "__raven_wrapper__" exception

### ISSUE THREAD

**Issue by nitimagulati** [mozilla/geckodriver#747]
In order to help us efficiently investigate your issue, please provide the following information:

## Firefox Version
FF- 53.0.2 (32- bit)

## Platform
Windows 7, 64 bit
Selenium Version:
selenium-webdriver (3.4.0)
webdriver-user-agent (7.3)
Gecko driver version: 0.16.1 32 bit

## Steps to reproduce -
we recently upgraded to latest Gecko driver 0.16.1.
I need to look for certain assertion from html of page like browser.html.include? "xyz"
when I run browser.html it gives me following exception
This works fine for other pages but certain pages has this issue.

Here is the web page example
https://www.wegotravel.co.uk/hotels/united-states/new-york/20170603/20170607/99602217
Exception:
@backtrace = Array (40 elements)
 [0] = "C:/Ruby22/lib/ruby/gems/2.2.0/gems/selenium-webdriver-3.4.0/lib/selenium/webdriver/remote/response.rb:69:in `assert_ok'"
 [1] = "C:/Ruby22/lib/ruby/gems/2.2.0/gems/selenium-webdriver-3.4.0/lib/selenium/webdriver/remote/response.rb:32:in `initialize'"
 [2] = "C:/Ruby22/lib/ruby/gems/2.2.0/gems/selenium-webdriver-3.4.0/lib/selenium/webdriver/remote/http/common.rb:83:in `new'"
 [3] = "C:/Ruby22/lib/ruby/gems/2.2.0/gems/selenium-webdriver-3.4.0/lib/selenium/webdriver/remote/http/common.rb:83:in `create_response'"
 [4] = "C:/Ruby22/lib/ruby/gems/2.2.0/gems/selenium-webdriver-3.4.0/lib/selenium/webdriver/remote/http/default.rb:107:in `request'"
 [5] = "C:/Ruby22/lib/ruby/gems/2.2.0/gems/selenium-webdriver-3.4.0/lib/selenium/webdriver/remote/http/common.rb:61:in `call'"
 [6] = "C:/Ruby22/lib/ruby/gems/2.2.0/gems/selenium-webdriver-3.4.0/lib/selenium/webdriver/remote/w3c_bridge.rb:640:in `execute'"
 [7] = "C:/Ruby22/lib/ruby/gems/2.2.0/gems/selenium-webdriver-3.4.0/lib/selenium/webdriver/remote/w3c_bridge.rb:359:in `execute_script'"
 [8] = "C/Ruby22/lib/ruby/gems/2.2.0/gems/selenium-webdriver-3.4.0/lib/selenium/webdriver/remote/w3c_bridge.rb:183:in `page_source'"
 [9] = "C:/Ruby22/lib/ruby/gems/2.2.0/gems/selenium-webdriver-3.4.0/lib/selenium/webdriver/common/driver.rb:179:in `page_source'"
 [10] = "C:/Ruby22/lib/ruby/gems/2.2.0/gems/watir-webdriver-0.8.0/lib/watir-webdriver/browser.rb:183:in `html'"

**Comment by andreastt** [comment]
Did you try to run this against Firefox Nightly before reporting a bug?

**Comment by nitimagulati** [comment]
Thanks Andreas for responding, I tried it on firefox beta version. It is working fine.
I expect this will get fix with latest release version 54.
Thanks
