### ISSUE TITLE
org.openqa.selenium.SessionNotCreatedException: Unable to create new remote session...

### ISSUE THREAD

**Issue by hennayakaCM** [mozilla/geckodriver#749]
Getting started with selenium-webdriver with maven using below versions.
### Gecko `0.16.1`

Here is the code I made;

> src/main/java

`
                    import org.openqa.selenium.WebDriver;
		    import org.openqa.selenium.firefox.FirefoxDriver;

		public class Base {		

			public WebDriver driver = null;		
			public WebDriver getDriver() {				
				System.setProperty("webdriver.gecko.driver", "/home/henna/Programming/geckodriver");
				driver = new FirefoxDriver();
				return driver;
			}
		}
`

> src/test/java

> com.business

`		import org.openqa.selenium.WebDriver;
		
		public class Home extends com.qksell.page.Home_{
		
			public Home(WebDriver driver) {
				super(driver);
			}
			
			public void login( String email) {
				getEmail().clear();
				getEmail().sendKeys(email);
			}
			
		}`

> com.page

`	import org.openqa.selenium.By;
		import org.openqa.selenium.WebDriver;
		import org.openqa.selenium.WebElement;		
		import com.qksell.Base;
		
		public class Home_ extends Base{
			
			public WebDriver driver;
		
			public Home_(WebDriver driver) {
				super();
				this.driver = driver;
			}
			
			//Email
			public By email = By.xpath("/html/body/div[1]/div[1]/div[2]/div[2]/form/div[2]/div/div[1]/div[1]/div/div[1]/div/div[1]/input");
			public WebElement getEmail() {
				return driver.findElement(email);
			}`

> com.regression

`		import org.junit.Test;
		import org.openqa.selenium.WebDriver;
		import org.openqa.selenium.support.PageFactory;		
		import com.qksell.Base;
		import com.qksell.business.Home;
		
		public class MainTest {
		
			@Test
			public void test01() {
				Base b = new Base();
				WebDriver driver = b.getDriver();
				Home home = PageFactory.initElements(driver, Home.class);
				String url = "https://www.gmail.com";
				driver.get(url);
				driver.manage().window().maximize();
				home.login("hello@gmail.com");
				driver.close();
			}
		}`
After run Junit test I got this error;

> org.openqa.selenium.SessionNotCreatedException: Unable to create new remote session. desired capabilities = Capabilities [{moz:firefoxOptions={binary=Optional.empty, args=[], legacy=null, logLevel=null, prefs={}, profile=null}}], required capabilities = Capabilities [{moz:firefoxOptions={binary=Optional.empty, args=[], legacy=null, logLevel=null, prefs={}, profile=null}}]
Build info: version: '3.3.1', revision: '5234b325d5', time: '2017-03-10 09:10:29 +0000'
System info: host: 'Unknown', ip: 'Unknown', os.name: 'Linux', os.arch: 'amd64', os.version: '4.4.0-75-generic', java.version: '1.8.0_131'
Driver info: driver.version: FirefoxDriver
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:126)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:141)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:82)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:604)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:244)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:131)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:218)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:125)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:121)
	at com.qksell.Base.getDriver(Base.java:18)
	at com.qksell.regression.MainTest.test01(MainTest.java:15)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)

Here is the screenshot;
![screenshot from 2017-05-21 18-01-12](https://cloud.githubusercontent.com/assets/12958089/26285370/03eadf30-3e6c-11e7-837b-27cfab861d30.png)
How to fix this issue. Thanks in advance.!

**Comment by AutomatedTester** [comment]
Please upgrade to Selenium Java bindings 3.4+ and try again.

**Comment by hennayakaCM** [comment]
It's working.! Thanks a lot.

**Comment by srivasavi123** [comment]
Hi i m also getting the same error tried with server standalone 3.5.2 still the issue persists please help the same

**Comment by whimboo** [comment]
@srivasavi123 without a trace log or any other details about your test we cannot help. Also please make sure that you file a new issue given that you are using a version of Selenium which should be fine.

**Comment by srivasavi123** [comment]
Thanks whimboo how to get the tracelog i m not sure can you please help me with that

**Comment by whimboo** [comment]
Se the following link in how to attach a [trace-level log] from geckodriver. Thanks.

**Comment by Divyapabba16** [comment]
Selenium : 3.8

google chrome Version 63.0.3239.84 (Official Build) (64-bit)

Chromedriver : 2.34

written a small script
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;


public class Main {

	
	public static void main(String[] args) {
		
		  System.setProperty("webdriver.chrome.driver","/home/gamooga/Downloads/geckodriver");
		
		WebDriver driver = new ChromeDriver();
		
		driver.get("https://login.yahoo.com/");
	}

}

error : Exception in thread "main" org.openqa.selenium.SessionNotCreatedException: Unable to find a matching set of capabilities
Build info: version: '3.8.1', revision: '6e95a6684b', time: '2017-12-01T19:05:14.666Z'
System info: host: 'gamooga-Latitude-3460', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '4.10.0-28-generic', java.version: '1.8.0_151'
Driver info: driver.version: ChromeDriver
remote stacktrace: stack backtrace:

**Comment by cgoldberg** [comment]
@Divyapabba16 
Geckodriver is for controlling Firefox... Chromedriver is for controlling Chrome.
