### ISSUE TITLE
 java.lang.IllegalAccessError: tried to access class org.openqa.selenium.os.ExecutableFinder from class org.openqa.selenium.firefox.FirefoxBinary

### ISSUE THREAD

**Issue by Moshik177** [mozilla/geckodriver#754]
In order to help us efficiently investigate your issue, please provide the following information:
## Firefox Version
53.0.3

## Platform
Windows

## Steps to reproduce -
i am using the latest selenium version 3.4.0 , latest firefox version and the latest firefox driver 0.16.1 try to use 64bit or 32bit and i am getting the error  java.lang.IllegalAccessError: tried to access class org.openqa.selenium.os.ExecutableFinder from class org.openqa.selenium.firefox.FirefoxBinary
this is my code : 
```java
		DesiredCapabilities  capability = DesiredCapabilities.firefox();
		capability.setCapability("marionette", true);
		System.setProperty("webdriver.gecko.driver","C:\geckodriver.exe");
		WebDriver driver =  new FirefoxDriver(capability);
		return driver;

```

```
java.lang.IllegalAccessError: tried to access class org.openqa.selenium.os.ExecutableFinder from class org.openqa.selenium.firefox.FirefoxBinary
at org.openqa.selenium.firefox.FirefoxBinary.locateFirefoxBinariesFromPlatform(FirefoxBinary.java:418)
at org.openqa.selenium.firefox.FirefoxBinary.(FirefoxBinary.java:108)
at java.util.Optional.orElseGet(Optional.java:267)
at org.openqa.selenium.firefox.FirefoxDriver.toExecutor(FirefoxDriver.java:204)
at org.openqa.selenium.firefox.FirefoxDriver.(FirefoxDriver.java:108)
at org.openqa.selenium.firefox.FirefoxDriver.(FirefoxDriver.java:137)
at com.cellebrite.automation.generators.FirefoxWebDriverGenerator.getWebDriver(FirefoxWebDriverGenerator.java:37)
at com.cellebrite.automation.WebDriverSystemObject.webDriverFactory(WebDriverSystemObject.java:308)
at com.cellebrite.automation.WebDriverSystemObject.getBrowserInstance(WebDriverSystemObject.java:427)
at com.cellebrite.automation.WebDriverSystemObject.openBrowser(WebDriverSystemObject.java:330)
at com.cellebrite.automation.WebDriverSystemObject.init(WebDriverSystemObject.java:166)
at jsystem.framework.system.SystemManagerImpl.getSystemObject(SystemManagerImpl.java:185)
at jsystem.framework.system.SystemManagerImpl.getSystemObject(SystemManagerImpl.java:96)
at com.cellebrite.automation.tests.jsystem.AbstractWebDriverTest.setUp(AbstractWebDriverTest.java:20)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.junit.internal.runners.MethodRoadie.runBefores(MethodRoadie.java:129)
at org.junit.internal.runners.MethodRoadie.runBeforesThenTestThenAfters(MethodRoadie.java:93)
at org.junit.internal.runners.MethodRoadie.runTest(MethodRoadie.java:84)
at org.junit.internal.runners.MethodRoadie.run(MethodRoadie.java:49)
at org.junit.internal.runners.JUnit4ClassRunner.invokeTestMethod(JUnit4ClassRunner.java:98)
at org.junit.internal.runners.JUnit4ClassRunner.runMethods(JUnit4ClassRunner.java:61)
at org.junit.internal.runners.JUnit4ClassRunner$1.run(JUnit4ClassRunner.java:54)
at org.junit.internal.runners.ClassRoadie.runUnprotected(ClassRoadie.java:34)
at org.junit.internal.runners.ClassRoadie.runProtected(ClassRoadie.java:44)
at org.junit.internal.runners.JUnit4ClassRunner.run(JUnit4ClassRunner.java:52)
at junit.framework.JSystemJUnit4ClassRunner.run(JSystemJUnit4ClassRunner.java:250)
at junit.framework.JUnit4TestAdapterForJSystem.run(JUnit4TestAdapterForJSystem.java:86)
at com.aqua.anttask.jsystem.JUnitTestRunner.run(JUnitTestRunner.java:461)
at com.aqua.anttask.jsystem.JSystemTask.executeInVM(JSystemTask.java:1388)
at com.aqua.anttask.jsystem.JSystemTask.execute(JSystemTask.java:957)
at com.aqua.anttask.jsystem.JSystemTask.executeOrQueue(JSystemTask.java:1806)
at com.aqua.anttask.jsystem.JSystemTask.execute(JSystemTask.java:897)
at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:288)
at sun.reflect.GeneratedMethodAccessor5.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:105)
at org.apache.tools.ant.Task.perform(Task.java:348)
at org.apache.tools.ant.Target.execute(Target.java:357)
at org.apache.tools.ant.Target.performTasks(Target.java:385)
at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1329)
at org.apache.tools.ant.helper.SingleCheckExecutor.executeTargets(SingleCheckExecutor.java:38)
at org.apache.tools.ant.Project.executeTargets(Project.java:1181)
at org.apache.tools.ant.taskdefs.Ant.execute(Ant.java:416)
at net.sf.antcontrib.logic.AntCallBack.execute(AntCallBack.java:54)
at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:288)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:105)
at org.apache.tools.ant.Task.perform(Task.java:348)
at org.apache.tools.ant.Target.execute(Target.java:357)
at org.apache.tools.ant.Target.performTasks(Target.java:385)
at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1329)
at org.apache.tools.ant.Project.executeTarget(Project.java:1298)
at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
at org.apache.tools.ant.Project.executeTargets(Project.java:1181)
at org.apache.tools.ant.Main.runBuild(Main.java:698)
at org.apache.tools.ant.Main.startAnt(Main.java:199)
at org.apache.tools.ant.launch.Launcher.run(Launcher.java:257)
at org.apache.tools.ant.launch.Launcher.main(Launcher.java:104)

```

**Comment by Moshik177** [comment]
System.setProperty("webdriver.gecko.driver","C:\\geckodriver.exe");  :)

**Comment by andreastt** [comment]
This seems like a Selenium issue judging by the stacktrace. Please report your bug there.
