### ISSUE TITLE
Firefox Extension fails to install

### ISSUE THREAD

**Issue by mosaadm** [mozilla/geckodriver#759]
## Firefox Version
Firefox Version 53 using  0.16.1 geckodriver and selenium 3.4.0

## Platform
Windows 10 64bit

## Steps to reproduce -
We are trying to install a new extension that we developed and it does not contain an install.rdf because this technique is now legacy as mentioned [here ](https://developer.mozilla.org/en-US/Add-ons/Install_Manifests). 
The problem is that using the 0.16.1 geckodriver with selenium 3.4 does not seem to support this new kind of extensions and throws a : java.io.FileNotFoundException C:\Users\(username)\AppData\Local\Temp\unzip3999903548710354720stream\install.rdf (The system cannot find the file specified)

Of course manually the extension installs. You can get it from [here](https://addons.mozilla.org/en-US/firefox/addon/mooltipass-extension/)

**Comment by andreastt** [comment]
A `java.io.FileNotFoundException` would originate from your client or intermediary node, most likely Selenium. It would have nothing to do with geckodriver.

**Comment by whimboo** [comment]
Issue #702 could have an effect also here. @mosaadm how did you try to install the addon? We would need a testcase AND a trace level log as requested in the issue template when you created this issue. If there is something wrong with installing a webextension we will have to reopen this issue.

**Comment by mosaadm** [comment]
Steps to reproduce:
1. Download xpi from here (https://addons.mozilla.org/en-US/firefox/addon/mooltipass-extension/) right click and save as.
2. Use it in code

```

		FirefoxProfile profile = new FirefoxProfile();

		profile.addExtension(new File("path/to/mooltipass_extension-1.1.81-an+fx-windows.xpi"));

		driver = new FirefoxDriver(profile);
```
3. Run the project

**Expected Result:** addon is intalled 

**Actual Results:** the exception below:
```
[31morg.openqa.selenium.WebDriverException: Unable to convert: Capabilities [{moz:firefoxOptions={binary=Optional.empty, args=[], legacy=false, logLevel=null, prefs={}, profile=org.openqa.selenium.firefox.FirefoxProfile@7a67e3c6}, firefox_profile=org.openqa.selenium.firefox.FirefoxProfile@7a67e3c6}]
      	at org.openqa.selenium.remote.BeanToJsonConverter.convertObject(BeanToJsonConverter.java:87)
      	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:128)
      	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:142)
      	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:82)
      	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:637)
      	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:250)
      	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:236)
      	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:137)
      	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:191)
      	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:108)
      	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:121)
      	at mooltipass.automatedTest.config.WebDriverFactory.firefox(WebDriverFactory.java:74)
      	at mooltipass.automatedTest.config.WebDriverFactory.createDriver(WebDriverFactory.java:173)
      	at mooltipass.automatedTest.config.WebDriverFactory.get(WebDriverFactory.java:58)
      	at mooltipass.automatedTest.config.BeforeAfter.getNewBrowser(BeforeAfter.java:44)
      	at mooltipass.automatedTest.config.BeforeAfter.beforeScenario(BeforeAfter.java:22)
      	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
      	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
      	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
      	at java.lang.reflect.Method.invoke(Method.java:498)
      	at cucumber.runtime.Utils$1.call(Utils.java:37)
      	at cucumber.runtime.Timeout.timeout(Timeout.java:13)
      	at cucumber.runtime.Utils.invoke(Utils.java:31)
      	at cucumber.runtime.java.JavaHookDefinition.execute(JavaHookDefinition.java:60)
      	at cucumber.runtime.Runtime.runHookIfTagsMatch(Runtime.java:223)
      	at cucumber.runtime.Runtime.runHooks(Runtime.java:211)
      	at cucumber.runtime.Runtime.runBeforeHooks(Runtime.java:201)
      	at cucumber.runtime.model.CucumberScenario.run(CucumberScenario.java:40)
      	at cucumber.runtime.junit.ExecutionUnitRunner.run(ExecutionUnitRunner.java:91)
      	at cucumber.runtime.junit.FeatureRunner.runChild(FeatureRunner.java:63)
      	at cucumber.runtime.junit.FeatureRunner.runChild(FeatureRunner.java:18)
      	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
      	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
      	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
      	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
      	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
      	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
      	at cucumber.runtime.junit.FeatureRunner.run(FeatureRunner.java:70)
      	at cucumber.api.junit.Cucumber.runChild(Cucumber.java:93)
      	at cucumber.api.junit.Cucumber.runChild(Cucumber.java:37)
      	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
      	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
      	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
      	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
      	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
      	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
      	at cucumber.api.junit.Cucumber.run(Cucumber.java:98)
      	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
      	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
      	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
      	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678)
      	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
      	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
      Caused by: org.openqa.selenium.WebDriverException: java.lang.reflect.InvocationTargetException
      Build info: version: '3.4.0', revision: 'unknown', time: 'unknown'
      System info: host: 'DESKTOP-308IKTK', ip: '10.0.0.83', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_131'
      Driver info: driver.version: FirefoxDriver
      	at org.openqa.selenium.remote.BeanToJsonConverter.convertObject(BeanToJsonConverter.java:214)
      	at org.openqa.selenium.remote.BeanToJsonConverter.convertObject(BeanToJsonConverter.java:142)
      	at org.openqa.selenium.remote.BeanToJsonConverter.convertObject(BeanToJsonConverter.java:188)
      	at org.openqa.selenium.remote.BeanToJsonConverter.convertObject(BeanToJsonConverter.java:85)
      	... 52 more
      Caused by: java.lang.reflect.InvocationTargetException
      	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
      	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
      	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
      	at java.lang.reflect.Method.invoke(Method.java:498)
      	at org.openqa.selenium.remote.BeanToJsonConverter.convertObject(BeanToJsonConverter.java:197)
      	... 55 more
      Caused by: org.openqa.selenium.WebDriverException: java.io.FileNotFoundException: C:\Users\mohamed\AppData\Local\Temp\unzip4496712249998374393stream\install.rdf (The system cannot find the file specified)
      Build info: version: '3.4.0', revision: 'unknown', time: 'unknown'
      System info: host: 'DESKTOP-308IKTK', ip: '10.0.0.83', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_131'
      Driver info: driver.version: FirefoxDriver
      	at org.openqa.selenium.firefox.internal.FileExtension.readIdFromInstallRdf(FileExtension.java:142)
      	at org.openqa.selenium.firefox.internal.FileExtension.writeTo(FileExtension.java:61)
      	at org.openqa.selenium.firefox.FirefoxProfile.installExtensions(FirefoxProfile.java:424)
      	at org.openqa.selenium.firefox.FirefoxProfile.layoutOnDisk(FirefoxProfile.java:402)
      	at org.openqa.selenium.firefox.FirefoxProfile.toJson(FirefoxProfile.java:374)
      	at org.openqa.selenium.firefox.FirefoxOptions.toJson(FirefoxOptions.java:557)
      	... 60 more
      Caused by: java.io.FileNotFoundException: C:\Users\mohamed\AppData\Local\Temp\unzip4496712249998374393stream\install.rdf (The system cannot find the file specified)
      	at java.io.FileInputStream.open0(Native Method)
      	at java.io.FileInputStream.open(FileInputStream.java:195)
      	at java.io.FileInputStream.<init>(FileInputStream.java:138)
      	at java.io.FileInputStream.<init>(FileInputStream.java:93)
      	at sun.net.www.protocol.file.FileURLConnection.connect(FileURLConnection.java:90)
      	at sun.net.www.protocol.file.FileURLConnection.getInputStream(FileURLConnection.java:188)
      	at org.apache.xerces.impl.XMLEntityManager.setupCurrentEntity(Unknown Source)
      	at org.apache.xerces.impl.XMLVersionDetector.determineDocVersion(Unknown Source)
      	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
      	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
      	at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
      	at org.apache.xerces.parsers.DOMParser.parse(Unknown Source)
      	at org.apache.xerces.jaxp.DocumentBuilderImpl.parse(Unknown Source)
      	at javax.xml.parsers.DocumentBuilder.parse(DocumentBuilder.java:205)
      	at org.openqa.selenium.firefox.internal.FileExtension.readIdFromInstallRdf(FileExtension.java:98)
      	... 65 more
      [0m
```

**Comment by whimboo** [comment]
Ok, so it's done when preparing the profile. That said, and given that you are on Windows, this problem should be caused by #702. Lets wait for the next release of geckodriver which will happen soon. Then please report back. Thanks.

**Comment by phystem** [comment]
@whimboo  Happening in Geckodriver 0.17.0 as well.

I'm using 
Selenium 3.4
Firefox 54.0b6 (32-bit)
Geckodriver 0.17.0 32-bit
Windows 7 32 bit

Created a github project for the same

https://github.com/phystem/GekoDriverIssue

**Comment by whimboo** [comment]
Please provide a trace log and attach it to this issue. I would like to have a look at this first.

**Comment by phystem** [comment]
@whimboo updated with stacktrace. Please Check

**Comment by whimboo** [comment]
I do not need the Java bindings stacktrace, but the geckodriver one. Please see the the readme on this repository how to get it.

**Comment by phystem** [comment]
Though I set the log level, the log didn't generate
But I got the issue. The issue is happening if the extension is built using [**web-extensions**](https://developer.mozilla.org/en-US/Add-ons/WebExtensions). If the extension is built using **jpm** then there is no issue.

Because as per log

`Caused by: java.io.FileNotFoundException: C:\Users\394173\AppData\Local\Temp\unzip5806772282736173501stream\install.rdf (The system cannot find the file specified)`

The reason is install.rdf is not present in **web-extensions** type extensions, where as it is available in **jpm** type extensions.

Could not upload the extension due to firewall. But the extension which is used is present [here](https://github.com/CognizantQAHub/Cognizant-Intelligent-Test-Scripter-Firefox-Addon/releases)

### Java Code I used

```
 public void initDriverWithExtension() {
        FirefoxProfile profile = new FirefoxProfile();
        File extension = new File(DriverTest.class.getResource("/cognizantits.xpi").getFile());
        profile.addExtension(extension);
        FirefoxOptions fOptions = new FirefoxOptions();
        fOptions.setLogLevel(Level.ALL);
        fOptions.setProfile(profile);
        WebDriver driver = new FirefoxDriver(fOptions);
        driver.get("http://www.bing.com");
        driver.quit();
    }
```

### StackTrace

```
org.openqa.selenium.WebDriverException: Unable to convert: Capabilities [{moz:firefoxOptions={binary=Optional.empty, args=[], legacy=false, logLevel=ALL, prefs={}, profile=org.openqa.selenium.firefox.FirefoxProfile@1d48005}, firefox_profile=org.openqa.selenium.firefox.FirefoxProfile@1d48005}]
	at org.openqa.selenium.remote.BeanToJsonConverter.convertObject(BeanToJsonConverter.java:87)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:128)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:142)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:82)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:637)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:250)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:236)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:137)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:191)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:108)
	at drivertest.DriverTest.initDriverWithExtension(DriverTest.java:55)
Caused by: org.openqa.selenium.WebDriverException: java.lang.reflect.InvocationTargetException
Build info: version: '3.4.0', revision: 'unknown', time: 'unknown'
System info: host: 'PC327135', ip: '10.219.69.109', os.name: 'Windows 7', os.arch: 'x86', os.version: '6.1', java.version: '1.8.0_131'
Driver info: driver.version: FirefoxDriver
	at org.openqa.selenium.remote.BeanToJsonConverter.convertObject(BeanToJsonConverter.java:214)
	at org.openqa.selenium.remote.BeanToJsonConverter.convertObject(BeanToJsonConverter.java:142)
	at org.openqa.selenium.remote.BeanToJsonConverter.convertObject(BeanToJsonConverter.java:188)
	at org.openqa.selenium.remote.BeanToJsonConverter.convertObject(BeanToJsonConverter.java:85)
	... 44 more
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.openqa.selenium.remote.BeanToJsonConverter.convertObject(BeanToJsonConverter.java:197)
	... 47 more
Caused by: org.openqa.selenium.WebDriverException: java.io.FileNotFoundException: C:\Users\394173\AppData\Local\Temp\unzip5806772282736173501stream\install.rdf (The system cannot find the file specified)
Build info: version: '3.4.0', revision: 'unknown', time: 'unknown'
System info: host: 'PC327135', ip: '10.219.69.109', os.name: 'Windows 7', os.arch: 'x86', os.version: '6.1', java.version: '1.8.0_131'
Driver info: driver.version: FirefoxDriver
	at org.openqa.selenium.firefox.internal.FileExtension.readIdFromInstallRdf(FileExtension.java:142)
	at org.openqa.selenium.firefox.internal.FileExtension.writeTo(FileExtension.java:61)
	at org.openqa.selenium.firefox.FirefoxProfile.installExtensions(FirefoxProfile.java:424)
	at org.openqa.selenium.firefox.FirefoxProfile.layoutOnDisk(FirefoxProfile.java:402)
	at org.openqa.selenium.firefox.FirefoxProfile.toJson(FirefoxProfile.java:374)
	at org.openqa.selenium.firefox.FirefoxOptions.toJson(FirefoxOptions.java:557)
	... 52 more
Caused by: java.io.FileNotFoundException: C:\Users\394173\AppData\Local\Temp\unzip5806772282736173501stream\install.rdf (The system cannot find the file specified)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileInputStream.<init>(FileInputStream.java:93)
	at sun.net.www.protocol.file.FileURLConnection.connect(FileURLConnection.java:90)
	at sun.net.www.protocol.file.FileURLConnection.getInputStream(FileURLConnection.java:188)
	at org.apache.xerces.impl.XMLEntityManager.setupCurrentEntity(Unknown Source)
	at org.apache.xerces.impl.XMLVersionDetector.determineDocVersion(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
	at org.apache.xerces.parsers.DOMParser.parse(Unknown Source)
	at org.apache.xerces.jaxp.DocumentBuilderImpl.parse(Unknown Source)
	at javax.xml.parsers.DocumentBuilder.parse(DocumentBuilder.java:205)
	at org.openqa.selenium.firefox.internal.FileExtension.readIdFromInstallRdf(FileExtension.java:98)
	... 57 more


Results :

Failed tests:   initDriverWithExtension(drivertest.DriverTest): Unable to convert: Capabilities [{moz:firefoxOptions={binary=Optional.empty, args=[], legacy=false, logLevel=ALL, prefs={}, profile=org.openqa.selenium.firefox.FirefoxProfile@1d48005}, firefox_profile=org.openqa.selenium.firefox.FirefoxProfile@1d48005}]
```

**Comment by mosaadm** [comment]
I tried with the new release v0.17.0 and  I can confirm it is still not working.
Here is the stacktrace
`org.openqa.selenium.WebDriverException: Unable to convert: Capabilities [{moz:firefoxOptions={binary=Optional.empty, args=[], legacy=false, logLevel=null, prefs={}, profile=org.openqa.selenium.firefox.FirefoxProfile@662706a7}, firefox_profile=org.openqa.selenium.firefox.FirefoxProfile@662706a7}]
	at org.openqa.selenium.remote.BeanToJsonConverter.convertObject(BeanToJsonConverter.java:87)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:128)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:142)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:82)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:637)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:250)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:236)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:137)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:191)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:108)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:121)
	at mooltipass.automatedTest.config.WebDriverFactory.firefox(WebDriverFactory.java:73)
	at mooltipass.automatedTest.config.WebDriverFactory.createDriver(WebDriverFactory.java:184)
	at mooltipass.automatedTest.config.WebDriverFactory.get(WebDriverFactory.java:57)
	at mooltipass.automatedTest.RunCukesTest.getNewBrowser(RunCukesTest.java:31)
	at mooltipass.automatedTest.RunCukesTest.setUp(RunCukesTest.java:22)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at cucumber.api.junit.Cucumber.run(Cucumber.java:98)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
Caused by: org.openqa.selenium.WebDriverException: java.lang.reflect.InvocationTargetException
Build info: version: '3.4.0', revision: 'unknown', time: 'unknown'
System info: host: 'DESKTOP-308IKTK', ip: '10.0.0.124', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_131'
Driver info: driver.version: FirefoxDriver
	at org.openqa.selenium.remote.BeanToJsonConverter.convertObject(BeanToJsonConverter.java:214)
	at org.openqa.selenium.remote.BeanToJsonConverter.convertObject(BeanToJsonConverter.java:142)
	at org.openqa.selenium.remote.BeanToJsonConverter.convertObject(BeanToJsonConverter.java:188)
	at org.openqa.selenium.remote.BeanToJsonConverter.convertObject(BeanToJsonConverter.java:85)
	... 32 more
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.openqa.selenium.remote.BeanToJsonConverter.convertObject(BeanToJsonConverter.java:197)
	... 35 more
Caused by: org.openqa.selenium.WebDriverException: java.io.FileNotFoundException: C:\Users\user\AppData\Local\Temp\unzip5006317497018973935stream\install.rdf (The system cannot find the file specified)
Build info: version: '3.4.0', revision: 'unknown', time: 'unknown'
System info: host: 'DESKTOP-308IKTK', ip: '10.0.0.124', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_131'
Driver info: driver.version: FirefoxDriver
	at org.openqa.selenium.firefox.internal.FileExtension.readIdFromInstallRdf(FileExtension.java:142)
	at org.openqa.selenium.firefox.internal.FileExtension.writeTo(FileExtension.java:61)
	at org.openqa.selenium.firefox.FirefoxProfile.installExtensions(FirefoxProfile.java:424)
	at org.openqa.selenium.firefox.FirefoxProfile.layoutOnDisk(FirefoxProfile.java:402)
	at org.openqa.selenium.firefox.FirefoxProfile.toJson(FirefoxProfile.java:374)
	at org.openqa.selenium.firefox.FirefoxOptions.toJson(FirefoxOptions.java:557)
	... 40 more
Caused by: java.io.FileNotFoundException: C:\Users\user\AppData\Local\Temp\unzip5006317497018973935stream\install.rdf (The system cannot find the file specified)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileInputStream.<init>(FileInputStream.java:93)
	at sun.net.www.protocol.file.FileURLConnection.connect(FileURLConnection.java:90)
	at sun.net.www.protocol.file.FileURLConnection.getInputStream(FileURLConnection.java:188)
	at org.apache.xerces.impl.XMLEntityManager.setupCurrentEntity(Unknown Source)
	at org.apache.xerces.impl.XMLVersionDetector.determineDocVersion(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
	at org.apache.xerces.parsers.DOMParser.parse(Unknown Source)
	at org.apache.xerces.jaxp.DocumentBuilderImpl.parse(Unknown Source)
	at javax.xml.parsers.DocumentBuilder.parse(DocumentBuilder.java:205)
	at org.openqa.selenium.firefox.internal.FileExtension.readIdFromInstallRdf(FileExtension.java:98)
	... 45 more

java.lang.NullPointerException
	at mooltipass.automatedTest.RunCukesTest.closeBrowser(RunCukesTest.java:36)
	at mooltipass.automatedTest.RunCukesTest.tearDown(RunCukesTest.java:27)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:33)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at cucumber.api.junit.Cucumber.run(Cucumber.java:98)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)

`

**Comment by andreastt** [comment]
@mosaadm As always, a stacktrace from the Java client is not very useful to diagnose a problem with geckodriver because they don’t propagate. Please include a trace-level log from geckodriver.

**Comment by whimboo** [comment]
So it's the code in the Java bindings which allow you to install a webextension via the profile:

```
        FirefoxProfile profile = new FirefoxProfile();
        File extension = new File(DriverTest.class.getResource("/cognizantits.xpi").getFile());
        profile.addExtension(extension);
```

The `FirefoxProfile` is nothing which is related to GeckoDriver. So if you want to get support for installing webextensions you have to file a bug for Selenium.

Here the method in detail which would need to be enhanced:

https://seleniumhq.github.io/selenium/docs/api/java/org/openqa/selenium/firefox/FirefoxProfile.html#addExtension-java.io.File-

**Comment by whimboo** [comment]
A workaround for the time being would be to use the add-on endpoints geckodriver 0.17.0 provides to get an extension installed from the local disk. 

https://github.com/mozilla/geckodriver/blob/release/src/marionette.rs#L66
