### ISSUE TITLE
Seleium 3.4 can't be invoked under the firefox driver

### ISSUE THREAD

**Issue by cnhome** [mozilla/geckodriver#765]
Seleium 3.4 can't be invoked under the firefox driver.

## Firefox Version
54.0b9

## Platform
Windows 10 (201703)

## Steps to reproduce
Running the following codes:
        
        System.setProperty("webdriver.firefox.marionette","C:/Program Files (x86)/Mozilla 
        Firefox/geckodriver.exe");      
        FirefoxDriver driver = new FirefoxDriver();      
        driver.get("https://www.baidu.com");
        driver.close();

Browser can be opened. But it can't get the web page. Some logs and error information are generated in the Idea:

        1496546956935	DeferredSave.extensions.json	DEBUG	Starting write
        1496546956963	DeferredSave.addons.json	DEBUG	Starting write
        1496546956966	DeferredSave.extensions.json	DEBUG	Write succeeded
        1496546956980	DeferredSave.addons.json	DEBUG	Write succeeded
        Crash Annotation GraphicsCriticalError: |[C0][GFX1]: Potential driver version mismatch ignored due to missing DLLs igd10umd64 v= and igd10iumd64.dll v=0.0.0.0 (t=0.617838) [GFX1]: Potential driver version mismatch ignored due to missing DLLs igd10umd64 v= and igd10iumd64.dll v=0.0.0.0
        [GPU 36060] WARNING: pipe error: 109: file c:/builds/moz2_slave/m-beta-w64-0000000000000000000/build/src/ipc/chromium/src/chrome/common/ipc_channel_win.cc, line 346
        Exception in thread "main" org.openqa.selenium.remote.UnreachableBrowserException: Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure.
        Build info: version: '3.4.0', revision: 'unknown', time: 'unknown'
        System info: host: 'DESKTOP-EERRBKB', ip: '172.17.68.93', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_121'
        Driver info: driver.version: FirefoxDriver
	        at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:658)
	        at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:250)
	        at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:236)
	        at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:137)
	        at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:191)
	        at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:108)
	        at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:104)
	        at App.main(App.java:14)
        Caused by: java.lang.NullPointerException
	        at org.openqa.selenium.remote.service.DriverService.waitUntilAvailable(DriverService.java:192)
	        at org.openqa.selenium.firefox.XpiDriverService.start(XpiDriverService.java:94)
	        at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:78)
	        at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:637)
	        ... 7 more
        Disconnected from the target VM, address: '127.0.0.1:54903', transport: 'socket'
        Process finished with exit code 1

**Comment by andreastt** [comment]
And did you put geckodriver on your system path or set `webdriver.firefox.driver` to its path?

As I can’t really reproduce this from the information available, I’m going to close the bug. If you think this is wrong, please let me know.

**Comment by cnhome** [comment]
很感谢上边的朋友 @andreastt 。
我之前按照网上的例子，这样设置的：
~~~~
System.setProperty("webdriver.firefox.marionette",
"C:\\web_driver\\geckodriver-v0.17.0-win64\\geckodriver.exe");
~~~~
后来看到了你的提醒，又查了一下geckodriver的官方wiki，我调整程这样：
~~~~
System.setProperty("webdriver.gecko.driver",
"C:\\web_driver\\geckodriver-v0.17.0-win64\\geckodriver.exe");
~~~~
一切都可以了。

----------------
Thank you to the above friends @andreastt.
I followed the online example, so set:
~~~~
System.setProperty("webdriver.firefox.marionette",
"C:\\web_driver\\geckodriver-v0.17.0-win64\\geckodriver.exe");
~~~~
And later saw your reminder, and check the geckodriver official wiki, I adjust this way:
~~~~
System.setProperty("webdriver.gecko.driver",
"C:\\web_driver\\geckodriver-v0.17.0-win64\\geckodriver.exe");
~~~~
Everything is fine.
