### ISSUE TITLE
Fullscreen operation is not working

### ISSUE THREAD

**Issue by mrunalgosar** [mozilla/geckodriver#766]
In order to help us efficiently investigate your issue, please provide the following information:

## Firefox Version: 52.0.2 (32-bit)
From the "About" dialog.

## Steps to reproduce -
While trying to perform full screen operation in firefox browser then it throws UnsupportedCommandException
## Test code:
```
public class GeckoTest {
    public static void main(String[] args) throws IOException {
        System.setProperty("webdriver.gecko.driver","I:\\jetbrainsworkspace\\src\\test\\resources\\geckodriver.exe");
        FirefoxBinary binary = new FirefoxBinary(new File("D:\\installations\\browsers\\ff\\52.0.2_32\\firefox.exe"));
        FirefoxOptions options = new FirefoxOptions();
        options.setBinary(binary);
        options.setLogLevel(Level.ALL);
        WebDriver browser = new FirefoxDriver(options);
        browser.manage().timeouts().pageLoadTimeout(10, TimeUnit.SECONDS);
        browser.manage().timeouts().implicitlyWait(10,TimeUnit.SECONDS);
        browser.get("http://examples.sencha.com/extjs/6.5.0/examples/kitchensink/?classic#form-fieldtypes");
        browser.manage().window().fullscreen();
        WebDriverWait wait = new WebDriverWait(browser,20,3000);
        wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//div[contains(@class,'x-form-spinner x-form-spinner-default x-form-spinner-down x-form-spinner-down-default')]")));
        Actions builder = new Actions(browser);
        builder.doubleClick(browser.findElement(By.xpath(".//div[contains(@class,'x-form-spinner x-form-spinner-default x-form-spinner-down x-form-spinner-down-default')]"))).perform();
        browser.close();
    }
}
```

## Log:
```
"C:\Program Files\Java\jdk1.8.0_131\bin\java" -javaagent:D:\installations\jetbrains\IntelliJ\lib\idea_rt.jar=50367:D:\installations\jetbrains\IntelliJ\bin -Dfile.encoding=UTF-8 -classpath "C:\Program Files\Java\jdk1.8.0_131\jre\lib\charsets.jar;C:\Program Files\Java\jdk1.8.0_131\jre\lib\deploy.jar;C:\Program Files\Java\jdk1.8.0_131\jre\lib\ext\access-bridge-64.jar;C:\Program Files\Java\jdk1.8.0_131\jre\lib\ext\cldrdata.jar;C:\Program Files\Java\jdk1.8.0_131\jre\lib\ext\dnsns.jar;C:\Program Files\Java\jdk1.8.0_131\jre\lib\ext\jaccess.jar;C:\Program Files\Java\jdk1.8.0_131\jre\lib\ext\jfxrt.jar;C:\Program Files\Java\jdk1.8.0_131\jre\lib\ext\localedata.jar;C:\Program Files\Java\jdk1.8.0_131\jre\lib\ext\nashorn.jar;C:\Program Files\Java\jdk1.8.0_131\jre\lib\ext\sunec.jar;C:\Program Files\Java\jdk1.8.0_131\jre\lib\ext\sunjce_provider.jar;C:\Program Files\Java\jdk1.8.0_131\jre\lib\ext\sunmscapi.jar;C:\Program Files\Java\jdk1.8.0_131\jre\lib\ext\sunpkcs11.jar;C:\Program Files\Java\jdk1.8.0_131\jre\lib\ext\zipfs.jar;C:\Program Files\Java\jdk1.8.0_131\jre\lib\javaws.jar;C:\Program Files\Java\jdk1.8.0_131\jre\lib\jce.jar;C:\Program Files\Java\jdk1.8.0_131\jre\lib\jfr.jar;C:\Program Files\Java\jdk1.8.0_131\jre\lib\jfxswt.jar;C:\Program Files\Java\jdk1.8.0_131\jre\lib\jsse.jar;C:\Program Files\Java\jdk1.8.0_131\jre\lib\management-agent.jar;C:\Program Files\Java\jdk1.8.0_131\jre\lib\plugin.jar;C:\Program Files\Java\jdk1.8.0_131\jre\lib\resources.jar;C:\Program Files\Java\jdk1.8.0_131\jre\lib\rt.jar;I:\jetbrainsworkspace\target\test-classes;C:\Users\mrunal\.m2\repository\org\seleniumhq\selenium\selenium-java\3.4.0\selenium-java-3.4.0.jar;C:\Users\mrunal\.m2\repository\org\seleniumhq\selenium\selenium-api\3.4.0\selenium-api-3.4.0.jar;C:\Users\mrunal\.m2\repository\org\seleniumhq\selenium\selenium-chrome-driver\3.4.0\selenium-chrome-driver-3.4.0.jar;C:\Users\mrunal\.m2\repository\org\seleniumhq\selenium\selenium-edge-driver\3.4.0\selenium-edge-driver-3.4.0.jar;C:\Users\mrunal\.m2\repository\org\seleniumhq\selenium\selenium-firefox-driver\3.4.0\selenium-firefox-driver-3.4.0.jar;C:\Users\mrunal\.m2\repository\org\seleniumhq\selenium\selenium-ie-driver\3.4.0\selenium-ie-driver-3.4.0.jar;C:\Users\mrunal\.m2\repository\org\seleniumhq\selenium\selenium-opera-driver\3.4.0\selenium-opera-driver-3.4.0.jar;C:\Users\mrunal\.m2\repository\org\seleniumhq\selenium\selenium-remote-driver\3.4.0\selenium-remote-driver-3.4.0.jar;C:\Users\mrunal\.m2\repository\org\seleniumhq\selenium\selenium-safari-driver\3.4.0\selenium-safari-driver-3.4.0.jar;C:\Users\mrunal\.m2\repository\org\seleniumhq\selenium\selenium-support\3.4.0\selenium-support-3.4.0.jar;C:\Users\mrunal\.m2\repository\cglib\cglib-nodep\3.2.4\cglib-nodep-3.2.4.jar;C:\Users\mrunal\.m2\repository\org\apache\commons\commons-exec\1.3\commons-exec-1.3.jar;C:\Users\mrunal\.m2\repository\org\apache\commons\commons-lang3\3.5\commons-lang3-3.5.jar;C:\Users\mrunal\.m2\repository\commons-codec\commons-codec\1.10\commons-codec-1.10.jar;C:\Users\mrunal\.m2\repository\commons-io\commons-io\2.5\commons-io-2.5.jar;C:\Users\mrunal\.m2\repository\commons-logging\commons-logging\1.2\commons-logging-1.2.jar;C:\Users\mrunal\.m2\repository\org\w3c\css\sac\1.3\sac-1.3.jar;C:\Users\mrunal\.m2\repository\net\sourceforge\cssparser\cssparser\0.9.22\cssparser-0.9.22.jar;C:\Users\mrunal\.m2\repository\com\google\code\gson\gson\2.8.0\gson-2.8.0.jar;C:\Users\mrunal\.m2\repository\com\google\guava\guava\21.0\guava-21.0.jar;C:\Users\mrunal\.m2\repository\org\hamcrest\hamcrest-core\1.3\hamcrest-core-1.3.jar;C:\Users\mrunal\.m2\repository\net\sourceforge\htmlunit\htmlunit\2.26\htmlunit-2.26.jar;C:\Users\mrunal\.m2\repository\net\sourceforge\htmlunit\htmlunit-core-js\2.26\htmlunit-core-js-2.26.jar;C:\Users\mrunal\.m2\repository\net\sourceforge\htmlunit\neko-htmlunit\2.25\neko-htmlunit-2.25.jar;C:\Users\mrunal\.m2\repository\org\apache\httpcomponents\httpclient\4.5.3\httpclient-4.5.3.jar;C:\Users\mrunal\.m2\repository\org\apache\httpcomponents\httpcore\4.4.6\httpcore-4.4.6.jar;C:\Users\mrunal\.m2\repository\org\apache\httpcomponents\httpmime\4.5.3\httpmime-4.5.3.jar;C:\Users\mrunal\.m2\repository\org\eclipse\jetty\jetty-io\9.4.1.v20170120\jetty-io-9.4.1.v20170120.jar;C:\Users\mrunal\.m2\repository\org\eclipse\jetty\jetty-util\9.4.1.v20170120\jetty-util-9.4.1.v20170120.jar;C:\Users\mrunal\.m2\repository\net\java\dev\jna\jna\4.1.0\jna-4.1.0.jar;C:\Users\mrunal\.m2\repository\net\java\dev\jna\jna-platform\4.1.0\jna-platform-4.1.0.jar;C:\Users\mrunal\.m2\repository\com\codeborne\phantomjsdriver\1.4.0\phantomjsdriver-1.4.0.jar;C:\Users\mrunal\.m2\repository\org\seleniumhq\selenium\htmlunit-driver\2.26\htmlunit-driver-2.26.jar;C:\Users\mrunal\.m2\repository\javax\servlet\javax.servlet-api\3.1.0\javax.servlet-api-3.1.0.jar;C:\Users\mrunal\.m2\repository\org\eclipse\jetty\websocket\websocket-api\9.4.3.v20170317\websocket-api-9.4.3.v20170317.jar;C:\Users\mrunal\.m2\repository\org\eclipse\jetty\websocket\websocket-client\9.4.3.v20170317\websocket-client-9.4.3.v20170317.jar;C:\Users\mrunal\.m2\repository\org\eclipse\jetty\jetty-client\9.4.3.v20170317\jetty-client-9.4.3.v20170317.jar;C:\Users\mrunal\.m2\repository\org\eclipse\jetty\jetty-http\9.4.3.v20170317\jetty-http-9.4.3.v20170317.jar;C:\Users\mrunal\.m2\repository\org\eclipse\jetty\websocket\websocket-common\9.4.3.v20170317\websocket-common-9.4.3.v20170317.jar;C:\Users\mrunal\.m2\repository\xalan\serializer\2.7.2\serializer-2.7.2.jar;C:\Users\mrunal\.m2\repository\xalan\xalan\2.7.2\xalan-2.7.2.jar;C:\Users\mrunal\.m2\repository\xerces\xercesImpl\2.11.0\xercesImpl-2.11.0.jar;C:\Users\mrunal\.m2\repository\xml-apis\xml-apis\1.4.01\xml-apis-1.4.01.jar;C:\Users\mrunal\.m2\repository\junit\junit\4.12\junit-4.12.jar" GeckoTest
Jun 04, 2017 8:44:00 PM org.openqa.selenium.firefox.FirefoxOptions toCapabilities
INFO: Preferring the firefox binary in these options (D:\installations\browsers\ff\52.0.2_32\firefox.exe rather than D:/installations/browsers/ff/52.0.2_32/firefox.exe)
Jun 04, 2017 8:44:00 PM org.openqa.selenium.firefox.FirefoxOptions toCapabilities
INFO: Preferring the firefox binary in these options (D:\installations\browsers\ff\52.0.2_32\firefox.exe rather than D:/installations/browsers/ff/52.0.2_32/firefox.exe)
1496589240766	geckodriver	INFO	Listening on 127.0.0.1:3805
1496589241593	geckodriver::marionette	INFO	Starting browser \\?\D:\installations\browsers\ff\52.0.2_32\firefox.exe with args ["-marionette"]
2
 < AddonManagerInternal.validateBlocklist()@resource://gre/modules/AddonManager.jsm:700 < AddonManagerInternal.startup()@resource://gre/modules/AddonManager.jsm:870 < this.AddonManagerPrivate.startup()@resource://gre/modules/AddonManager.jsm:3033 < amManager.prototype.observe()@resource://gre/components/addonManager.js:65
1496589243615	geckodriver::marionette	TRACE	  connection attempt 0/600
1496589245223	Marionette	DEBUG	Marionette enabled via command-line flag
1496589245301	Marionette	INFO	Listening on port 50374
1496589245777	geckodriver::marionette	DEBUG	Connected to Marionette on localhost:50374
1496589245857	Marionette	DEBUG	Accepted connection conn0 from 127.0.0.1:50380
1496589245855	geckodriver::marionette	TRACE	← {"applicationType":"gecko","marionetteProtocol":3}
1496589245855	geckodriver::marionette	TRACE	→ 62:[0,1,"newSession",{"capabilities":{"desiredCapabilities":{}}}]
1496589245870	Marionette	TRACE	conn0 -> [0,1,"newSession",{"capabilities":{"desiredCapabilities":{}}}]
1496589245875	Marionette	CONFIG	Matched capabilities: {"browserName":"firefox","browserVersion":"52.0.2","platformName":"windows_nt","platformVersion":"6.1","pageLoadStrategy":"normal","acceptInsecureCerts":false,"timeouts":{"implicit":0,"page load":300000,"script":30000},"rotatable":false,"specificationLevel":0,"moz:processID":5332,"moz:profile":"C:\\Users\\mrunal\\AppData\\Local\\Temp\\rust_mozprofile.V7WcU0bOtQOP","moz:accessibilityChecks":false}
1496589247165	Marionette	DEBUG	loaded listener.js
JavaScript error: resource://gre/modules/AddonManager.jsm, line 2585: NS_ERROR_NOT_INITIALIZED: AddonManager is not initialized
1496589248144	Marionette	TRACE	conn0 <- [1,1,null,{"sessionId":"bbd5d0b1-05ec-4494-8f73-48f3ea6ba95b","capabilities":{"browserName":"firefox","browserVersion":"52.0.2","platformName":"windows_nt","platformVersion":"6.1","pageLoadStrategy":"normal","acceptInsecureCerts":false,"timeouts":{"implicit":0,"page load":300000,"script":30000},"rotatable":false,"specificationLevel":0,"moz:processID":5332,"moz:profile":"C:\\Users\\mrunal\\AppData\\Local\\Temp\\rust_mozprofile.V7WcU0bOtQOP","moz:accessibilityChecks":false}}]
1496589248154	geckodriver::marionette	TRACE	← [1,1,null,{"sessionId":"bbd5d0b1-05ec-4494-8f73-48f3ea6ba95b","capabilities":{"browserName":"firefox","browserVersion":"52.0.2","platformName":"windows_nt","platformVersion":"6.1","pageLoadStrategy":"normal","acceptInsecureCerts":false,"timeouts":{"implicit":0,"page load":300000,"script":30000},"rotatable":false,"specificationLevel":0,"moz:processID":5332,"moz:profile":"C:\\Users\\mrunal\\AppData\\Local\\Temp\\rust_mozprofile.V7WcU0bOtQOP","moz:accessibilityChecks":false}}]
1496589248155	webdriver::server	DEBUG	← 200 OK {"value": {"sessionId":"bbd5d0b1-05ec-4494-8f73-48f3ea6ba95b","capabilities":{"acceptInsecureCerts":false,"browserName":"firefox","browserVersion":"52.0.2","moz:accessibilityChecks":false,"moz:processID":5332,"moz:profile":"C:\\Users\\mrunal\\AppData\\Local\\Temp\\rust_mozprofile.V7WcU0bOtQOP","pageLoadStrategy":"normal","platformName":"windows_nt","platformVersion":"6.1","rotatable":false,"specificationLevel":0,"timeouts":{"implicit":0,"page load":300000,"script":30000}}}}
Jun 04, 2017 8:44:08 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: W3C
1496589248233	webdriver::server	DEBUG	→ POST /session/bbd5d0b1-05ec-4494-8f73-48f3ea6ba95b/timeouts {"page load":10000}
1496589248234	geckodriver::marionette	TRACE	→ 19:[0,2,"timeouts",{}]
1496589248234	Marionette	TRACE	conn0 -> [0,2,"timeouts",{}]
1496589248236	Marionette	TRACE	conn0 <- [1,2,null,{}]
1496589248237	geckodriver::marionette	TRACE	← [1,2,null,{}]
1496589248237	webdriver::server	DEBUG	← 200 OK {"value": {}}
1496589248242	webdriver::server	DEBUG	→ POST /session/bbd5d0b1-05ec-4494-8f73-48f3ea6ba95b/timeouts {"implicit":10000}
1496589248243	geckodriver::marionette	TRACE	→ 35:[0,3,"timeouts",{"implicit":10000}]
1496589248245	Marionette	TRACE	conn0 -> [0,3,"timeouts",{"implicit":10000}]
1496589248246	Marionette	TRACE	conn0 <- [1,3,null,{}]
1496589248247	geckodriver::marionette	TRACE	← [1,3,null,{}]
1496589248247	webdriver::server	DEBUG	← 200 OK {"value": {}}
1496589248250	webdriver::server	DEBUG	→ POST /session/bbd5d0b1-05ec-4494-8f73-48f3ea6ba95b/url {"url":"http://examples.sencha.com/extjs/6.5.0/examples/kitchensink/?classic#form-fieldtypes"}
1496589248250	geckodriver::marionette	TRACE	→ 106:[0,4,"get",{"url":"http://examples.sencha.com/extjs/6.5.0/examples/kitchensink/?classic#form-fieldtypes"}]
1496589248251	Marionette	TRACE	conn0 -> [0,4,"get",{"url":"http://examples.sencha.com/extjs/6.5.0/examples/kitchensink/?classic#form-fieldtypes"}]
1496589248799	Marionette	TRACE	conn0 <- [1,4,null,{}]
1496589248800	geckodriver::marionette	TRACE	← [1,4,null,{}]
1496589248800	webdriver::server	DEBUG	← 200 OK {"value": {}}
1496589248805	webdriver::server	DEBUG	→ POST /session/bbd5d0b1-05ec-4494-8f73-48f3ea6ba95b/window/fullscreen {}
1496589248809	webdriver::server	DEBUG	← 404 Not Found {"value":{"error":"unknown command","message":"POST /session/bbd5d0b1-05ec-4494-8f73-48f3ea6ba95b/window/fullscreen did not match a known command","stacktrace":"stack backtrace:\n   0:           0x489f6f - <no info>\n   1:           0x48ad59 - <no info>\n   2:           0x43a15d - <no info>\n   3:           0x42ec0f - <no info>\n   4:           0x423c30 - <no info>\n   5:           0x4078fa - <no info>\n   6:           0x6bc939 - <no info>\n   7:           0x415d0d - <no info>\n   8:           0x6b6e43 - <no info>\n   9:         0x76cf59cd - BaseThreadInitThunk"}}
Exception in thread "main" org.openqa.selenium.UnsupportedCommandException: POST /session/bbd5d0b1-05ec-4494-8f73-48f3ea6ba95b/window/fullscreen did not match a known command
Build info: version: '3.4.0', revision: 'unknown', time: 'unknown'
System info: host: 'MRUNAL-LAPTOP', ip: '192.168.56.1', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_131'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{moz:profile=C:\Users\mrunal\AppData\Local\Temp\rust_mozprofile.V7WcU0bOtQOP, rotatable=false, timeouts={implicit=0.0, page load=300000.0, script=30000.0}, pageLoadStrategy=normal, platform=ANY, specificationLevel=0.0, moz:accessibilityChecks=false, acceptInsecureCerts=false, browserVersion=52.0.2, platformVersion=6.1, moz:processID=5332.0, browserName=firefox, javascriptEnabled=true, platformName=windows_nt}]
Session ID: bbd5d0b1-05ec-4494-8f73-48f3ea6ba95b
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:150)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:115)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:45)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:164)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:82)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:637)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:694)
	at org.openqa.selenium.remote.RemoteWebDriver$RemoteWebDriverOptions$RemoteWindow.fullscreen(RemoteWebDriver.java:929)
	at GeckoTest.main(GeckoTest.java:32)

Process finished with exit code 1

```

**Comment by andreastt** [comment]
Support for fullscreen was added in https://bugzilla.mozilla.org/show_bug.cgi?id=1189749, and is only available in Firefox 55 or greater.
