### ISSUE TITLE
implicitly wait command is not working

### ISSUE THREAD

**Issue by gauri-evs** [mozilla/geckodriver#774]
I am running simple test that initiates firefox using TestNG @BeforeTest annotation. 
Class name is Base and method name is init(). Issue is:
There is no error when i declare implicitly wait statement , but when i run it i get error : 

FAILED CONFIGURATION:

```
@BeforeTest init
org.openqa.selenium.WebDriverException: An unknown error has occurred
Build info: version: '3.3.0', revision: 'b526bd5b41', time: '2017-03-07 19:26:04 +0000'
System info: host: 'EVS08AURA332', ip: '192.168.56.1', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_131'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{rotatable=false, raisesAccessibilityExceptions=false, appBuildId=20161031133903, version=47.0.2, platform=XP, proxy={}, command_id=1, specificationLevel=0, firefox_binary={extraEnv={DISPLAY=:1}, hCode=1170727939, class=org.openqa.selenium.firefox.FirefoxBinary, timeout=45000}, acceptSslCerts=false, browserVersion=47.0.2, platformVersion=6.1, XULappId={ec8030f7-c20a-464f-9b0e-13a3a9e97384}, browserName=Firefox, takesScreenshot=true, takesElementScreenshot=true, platformName=Windows_NT, device=desktop}]
Session ID: 0bdeb532-dfac-4fd1-8c88-ad0f1e32e771
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:127)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:93)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:42)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:163)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:82)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:604)
	at org.openqa.selenium.firefox.FirefoxDriver.access$100(FirefoxDriver.java:67)
	at org.openqa.selenium.firefox.FirefoxDriver$1$1.implicitlyWait(FirefoxDriver.java:272)
	at Base.init(Base.java:59)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:523)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:224)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:146)
	at org.testng.TestRunner.beforeRun(TestRunner.java:626)
	at org.testng.TestRunner.run(TestRunner.java:594)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
```

Also, i tried same without testNG. Creating object of base class and running as JAVA application, it ran successfully. Is there a problem with TestNG. I never faced this issue before. manage().window().maximixe() is also working. Only, wait is not working.

**Comment by andreastt** [comment]
You appear to be using Firefox 47 and Selenium 3.3 which are both not supported. You need to use a much more recent Firefox version to get page load strategies working.

**Comment by gauri-evs** [comment]
I am using firefox 53.0.3 version and selenium version 3.3. In my folder structure there is one folder resources that has 2 subfolders : browsers and drivers. Drivers contain .exe for geko driverand browser contain firefox-51.0.1.tar.bz2. 
  I am trying to open firefox using following code : 
     final String osName = System.getProperty("os.name");
			final String driverBase = Paths.get("resources", "drivers", "geckodriver").toString();
			final String driverExtn = osName.toLowerCase().contains("windows") ? ".exe" : "";
			System.setProperty("webdriver.gecko.driver", driverBase + driverExtn);

			final String xPort = System.getProperty("xvfb.id", ":1");
			final String firefoxPath;
			final FirefoxBinary firefoxBinary;

			
			if(driver==null)
			{
			if (osName.toLowerCase().contains("windows")) {
				// for now, find the default executable automatically
				// ensure windows firefox version is standard or as expected
				firefoxBinary = new FirefoxBinary();
			} else {
				firefoxPath = Paths.get("resources", "browsers", "firefox", "firefox-bin").toString();
				firefoxBinary = new FirefoxBinary(new File(firefoxPath));
			}

			firefoxBinary.setEnvironmentProperty("DISPLAY", xPort);
			driver = new FirefoxDriver(firefoxBinary);
						}
           driver.manage().timeouts().implicitlyWait(60, TimeUnit.SECONDS);
			driver.manage().window().maximize();
} 

I tried opening chrome using testng , it worked fine and there is no error on implicitly wait line.

**Comment by whimboo** [comment]
@gauri-evs, Firefox 51.0 is no longer supported. You should consider using 53.0, or a beta release for the upcoming 54.0 version.
