### ISSUE TITLE
WebDriverException: Message: connection refused

### ISSUE THREAD

**Issue by chrisspen** [mozilla/geckodriver#775]
I'm unable to use Selenium to control Firefox using Geckodriver.

## Platform and application details
* Platform: Ubuntu 16.04
* Firefox: 52.1.0
* Selenium: 3.4.3
* Geckodriver: 0.16.1

My code:

    from selenium import webdriver
    driver = webdriver.Firefox(capabilities={'marionette': True})

which throws the exception:

    Traceback (most recent call last):
      File "/usr/local/myproject/tests.py", line 393, in setUp
        driver = webdriver.Firefox(capabilities={'marionette': True})
      File "/usr/local/myproject/.env/local/lib/python2.7/site-packages/selenium/webdriver/firefox/webdriver.py", line 152, in __init__
        keep_alive=True)
      File "/usr/local/myproject/.env/local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 98, in __init__
        self.start_session(desired_capabilities, browser_profile)
      File "/usr/local/myproject/.env/local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 188, in start_session
        response = self.execute(Command.NEW_SESSION, parameters)
      File "/usr/local/myproject/.env/local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 256, in execute
        self.error_handler.check_response(response)
      File "/usr/local/myproject/.env/local/lib/python2.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
        raise exception_class(message, screen, stacktrace)
    WebDriverException: Message: connection refused

The contents of my geckodriver.log are:

    1496858900767	geckodriver	INFO	Listening on 127.0.0.1:51811
    1496858900821	geckodriver::marionette	INFO	Starting browser /usr/bin/firefox with args ["-marionette"]
    ExceptionHandler::GenerateDump cloned child 26504
    ExceptionHandler::SendContinueSignalToChild sent continue signal to child
    ExceptionHandler::WaitForContinueSignal waiting for continue signal...

**Comment by andreastt** [comment]
It’s really hard to tell what is going wrong just from the information you’ve added. Could you do some more investigation? In particular, it would be useful with a trace-level log from geckodriver. See the README for how to configure this.

**Comment by andreastt** [comment]
Closing due to inactivity.

**Comment by sharatkanthi** [comment]
Check out the following resolution

[https://stackoverflow.com/questions/39547598/selenium-common-exceptions-webdriverexception-message-connection-refused/52748355#52748355](url)

**Comment by sharatkanthi** [comment]
-This could be for various reasons.

-Most probably because the "latest" version of your geckodriver is not able to communicate with your "slightly older" firefox.

-The easiest way to fix this would be to try out different older versions of geckodriver. Run the following command to find the current version of your geckodriver

geckodriver --version

-If it shows the version as 19 or above, execute following steps to use geckodriver version 17(Works 90% of times)

-Step 1: Your existing geckodriver most typically may be placed in /usr/local/bin when u installed it earlier. First delete this by running sudo rm -r /usr/local/bin/geckodriver

-Step 2: Download version 17 of geckodriver from following link

https://github.com/mozilla/geckodriver/releases/tag/v0.17.0

Move the download file(geckodriver-v0.17.0-arm7hf.tar.gz) from your "Downloads" folder into your "home" directory

-Step 3: Unpack the file

tar -xzvf geckodriver-v0.17.0-arm7hf.tar.gz `

This will create a folder called "geckodriver" in your home directory

-Step 4: Move/Copy this extracted "geckodriver" into /usr/local/bin/

sudo cp geckodriver /usr/local/bin/

-Step 5: Run sudo reboot

rerun your program now... It should work
