### ISSUE TITLE
Invalid Argument Error SELENIUM findElement(...).sendKeys()

### ISSUE THREAD

**Issue by akgargo** [mozilla/geckodriver#788]
there is a problem when I tried to run the example of selenium with the latest geckodriver version (0.17.0).

on:
    driver.findElement(By.name('q')).sendKeys('webdriver');
throw:
    InvalidArgumentError: Expected [object Undefined] undefined to be a string

**Comment by andreastt** [comment]
You have not provided any of the information requested in the issue template, most importantly a geckodriver trace-level log. For us to be able to diagnose the issue, you need to provide sufficient information regarding the issue. This is not a good issue report.

I’m more than happy to re-open it once you add an error, stacktrace, trace-level log from geckodriver.

**Comment by akgargo** [comment]
Sorry about that.

Here is the trace log:

`...\node_modules\selenium-webdriver\lib\error.js:489:11)
    at parseHttpResponse (C:\Users\Gargo\OneDrive\Programacion_2017\NodeJS\automation\node_modules\selenium-webdriver\lib\http.js:519:13)
    at doSend.then.response (C:\Users\Gargo\OneDrive\Programacion_2017\NodeJS\automation\node_modules\selenium-webdriver\lib\http.js:441:30)
    at process._tickCallback (internal/process/next_tick.js:109:7)
From: Task: WebElement.sendKeys()
    at thenableWebDriverProxy.schedule (C:\Users\Gargo\OneDrive\Programacion_2017\NodeJS\automation\node_modules\selenium-webdriver\lib\webdriver.js:816:17)
    at WebElementPromise.schedule_ (C:\Users\Gargo\OneDrive\Programacion_2017\NodeJS\automation\node_modules\selenium-webdriver\lib\webdriver.js:2024:25)
    at WebElementPromise.sendKeys (C:\Users\Gargo\OneDrive\Programacion_2017\NodeJS\automation\node_modules\selenium-webdriver\lib\webdriver.js:2187:19)
    at Timeout._onTimeout (C:\Users\Gargo\OneDrive\Programacion_2017\NodeJS\automation\tsts.js:38:37)
    at ontimeout (timers.js:386:14)
    at tryOnTimeout (timers.js:250:5)
    at Timer.listOnTimeout (timers.js:214:5)`

And here is my code:
`/var webdriver = require('selenium-webdriver'),
    By = webdriver.By,
    until = webdriver.until;


	try {
		var driver = new webdriver.Builder()
	    .forBrowser('firefox')
	    .build();
		var dr = driver.get('http://www.google.com/');
	  setTimeout(function() {
			console.log('driver loaded');
			driver.sleep(3000);
			driver.findElement(By.name('q')).sendKeys('webdriver');
			driver.sleep(1000);
			driver.findElement(By.name('btnG')).click();
			driver.sleep(10000);
			//driver.wait(until.titleIs('webdriver - Buscar con Google'), 10000);
			driver.quit();

	  }, 5000);
	} catch(e) {
		console.log(e)
		driver.quit();
	}`

please re-open this issue

**Comment by andreastt** [comment]
@akgargo That’s a stacktrace, and not the trace-level log from geckodriver. Please see the README on how to crank up the log level, either via the `-vv` flag or through the `moz:firefoxOptions` configuration object capability.
