### ISSUE TITLE
Fails to navigate to the same URL with hash parameters

### ISSUE THREAD

**Issue by p0deje** [mozilla/geckodriver#790]
It seems that GeckoDriver (or Marionette) does not respond to request to navigate to the same URL that is currently loaded when the URL contains hash parameters. In this case, request to navigate simply fails with timeout.

## Platform and application details

* Platform: macOS 10.12.5
* Firefox: Firefox 53.0 (64-bit)
* Selenium: Ruby bindings 3.4.3

## Steps to reproduce

Run the following Ruby script:

```ruby
require 'selenium-webdriver'

Selenium::WebDriver.logger.level = :debug # print geckodriver output to stdout
options = Selenium::WebDriver::Firefox::Options.new
options.log_level = 'trace'
driver = Selenium::WebDriver.for(:firefox, options: options)

driver.navigate.to 'http://www.ford.com/#here' # this one works good
driver.navigate.to 'http://www.ford.com/#here' # this one hangs
```

## Log

```
017-06-20 18:02:31 DEBUG Selenium Executing Process ["/usr/local/bin/geckodriver", "--binary=/Applications/Firefox.app/Contents/MacOS/firefox-bin", "--port=4444"]
2017-06-20 18:02:31 DEBUG Selenium polling for socket on ["127.0.0.1", 4444]
1497960152074	geckodriver	INFO	Listening on 127.0.0.1:4444
2017-06-20 18:02:32 INFO Selenium Skipping handshake as we know it is W3C.
2017-06-20 18:02:32 INFO Selenium -> POST session
2017-06-20 18:02:32 INFO Selenium    >>> http://127.0.0.1:4444/session | {"desiredCapabilities":{"browserName":"firefox","marionette":true,"timeouts":{},"moz:firefoxOptions":{"log":{"level":"trace"}}},"capabilities":{"firstMatch":[{"browserName":"firefox","timeouts":{},"moz:firefoxOptions":{"log":{"level":"trace"}}}]}}
2017-06-20 18:02:32 DEBUG Selenium      > {"Accept"=>"application/json", "Content-Type"=>"application/json; charset=utf-8", "Content-Length"=>"247"}
1497960152402	geckodriver::marionette	INFO	Starting browser /Applications/Firefox.app/Contents/MacOS/firefox-bin with args ["-marionette"]
1497960152409	geckodriver::marionette	TRACE	  connection attempt 0/600
1497960152513	geckodriver::marionette	TRACE	  connection attempt 1/600
1497960152616	geckodriver::marionette	TRACE	  connection attempt 2/600
1497960152720	geckodriver::marionette	TRACE	  connection attempt 3/600
1497960152822	geckodriver::marionette	TRACE	  connection attempt 4/600
1497960152928	geckodriver::marionette	TRACE	  connection attempt 5/600
1497960153030	geckodriver::marionette	TRACE	  connection attempt 6/600
1497960153131	geckodriver::marionette	TRACE	  connection attempt 7/600
1497960153233	geckodriver::marionette	TRACE	  connection attempt 8/600
1497960153336	geckodriver::marionette	TRACE	  connection attempt 9/600
1497960153438	geckodriver::marionette	TRACE	  connection attempt 10/600
1497960153538	Marionette	DEBUG	Marionette enabled via command-line flag
1497960153545	geckodriver::marionette	TRACE	  connection attempt 11/600
1497960153649	geckodriver::marionette	TRACE	  connection attempt 12/600
1497960153753	geckodriver::marionette	TRACE	  connection attempt 13/600
1497960153856	geckodriver::marionette	TRACE	  connection attempt 14/600
1497960153959	geckodriver::marionette	TRACE	  connection attempt 15/600
1497960154063	geckodriver::marionette	TRACE	  connection attempt 16/600
1497960154165	geckodriver::marionette	TRACE	  connection attempt 17/600
1497960154269	geckodriver::marionette	TRACE	  connection attempt 18/600
1497960154370	geckodriver::marionette	TRACE	  connection attempt 19/600
1497960154474	geckodriver::marionette	TRACE	  connection attempt 20/600
1497960154580	geckodriver::marionette	TRACE	  connection attempt 21/600
1497960154682	geckodriver::marionette	TRACE	  connection attempt 22/600
1497960154783	geckodriver::marionette	TRACE	  connection attempt 23/600
1497960154887	geckodriver::marionette	TRACE	  connection attempt 24/600
1497960154990	geckodriver::marionette	TRACE	  connection attempt 25/600
1497960155093	geckodriver::marionette	TRACE	  connection attempt 26/600
1497960155169	Marionette	INFO	Listening on port 55951
1497960155196	geckodriver::marionette	DEBUG	Connected to Marionette on localhost:55951
1497960155213	Marionette	DEBUG	Accepted connection conn0 from 127.0.0.1:56040
1497960155235	geckodriver::marionette	TRACE	<- {"applicationType":"gecko","marionetteProtocol":3}
1497960155235	geckodriver::marionette	TRACE	-> 137:[0,1,"newSession",{"browserName":"firefox","capabilities":{"desiredCapabilities":{"browserName":"firefox","timeouts":{}}},"timeouts":{}}]
1497960155245	Marionette	TRACE	conn0 -> [0,1,"newSession",{"browserName":"firefox","capabilities":{"desiredCapabilities":{"browserName":"firefox","timeouts":{}}},"timeouts":{}}]
1497960155251	Marionette	CONFIG	Matched capabilities: {"browserName":"firefox","browserVersion":"53.0","platformName":"darwin","platformVersion":"16.6.0","pageLoadStrategy":"normal","acceptInsecureCerts":false,"timeouts":{"implicit":0,"pageLoad":300000,"script":30000},"rotatable":false,"specificationLevel":0,"moz:processID":88669,"moz:profile":"/var/folders/3s/yybq9c5n4pd0z9t4phtp6ml00000gn/T/rust_mozprofile.r9oCoocVmwze","moz:accessibilityChecks":false}
1497960155653	Marionette	TRACE	conn0 <- [1,1,null,{"sessionId":"ec4d374b-53af-9845-a1e1-de00d0b83efa","capabilities":{"browserName":"firefox","browserVersion":"53.0","platformName":"darwin","platformVersion":"16.6.0","pageLoadStrategy":"normal","acceptInsecureCerts":false,"timeouts":{"implicit":0,"pageLoad":300000,"script":30000},"rotatable":false,"specificationLevel":0,"moz:processID":88669,"moz:profile":"/var/folders/3s/yybq9c5n4pd0z9t4phtp6ml00000gn/T/rust_mozprofile.r9oCoocVmwze","moz:accessibilityChecks":false}}]
1497960155655	geckodriver::marionette	TRACE	<- [1,1,null,{"sessionId":"ec4d374b-53af-9845-a1e1-de00d0b83efa","capabilities":{"browserName":"firefox","browserVersion":"53.0","platformName":"darwin","platformVersion":"16.6.0","pageLoadStrategy":"normal","acceptInsecureCerts":false,"timeouts":{"implicit":0,"pageLoad":300000,"script":30000},"rotatable":false,"specificationLevel":0,"moz:processID":88669,"moz:profile":"/var/folders/3s/yybq9c5n4pd0z9t4phtp6ml00000gn/T/rust_mozprofile.r9oCoocVmwze","moz:accessibilityChecks":false}}]
1497960155656	webdriver::server	DEBUG	<- 200 OK {"value": {"sessionId":"ec4d374b-53af-9845-a1e1-de00d0b83efa","capabilities":{"acceptInsecureCerts":false,"browserName":"firefox","browserVersion":"53.0","moz:accessibilityChecks":false,"moz:processID":88669,"moz:profile":"/var/folders/3s/yybq9c5n4pd0z9t4phtp6ml00000gn/T/rust_mozprofile.r9oCoocVmwze","pageLoadStrategy":"normal","platformName":"darwin","platformVersion":"16.6.0","rotatable":false,"specificationLevel":0,"timeouts":{"implicit":0,"pageLoad":300000,"script":30000}}}}
2017-06-20 18:02:35 INFO Selenium <- {"value": {"sessionId":"ec4d374b-53af-9845-a1e1-de00d0b83efa","capabilities":{"acceptInsecureCerts":false,"browserName":"firefox","browserVersion":"53.0","moz:accessibilityChecks":false,"moz:processID":88669,"moz:profile":"/var/folders/3s/yybq9c5n4pd0z9t4phtp6ml00000gn/T/rust_mozprofile.r9oCoocVmwze","pageLoadStrategy":"normal","platformName":"darwin","platformVersion":"16.6.0","rotatable":false,"specificationLevel":0,"timeouts":{"implicit":0,"pageLoad":300000,"script":30000}}}}
2017-06-20 18:02:35 INFO Selenium Detected W3C dialect.
2017-06-20 18:02:35 INFO Selenium -> POST session/ec4d374b-53af-9845-a1e1-de00d0b83efa/url
2017-06-20 18:02:35 INFO Selenium    >>> http://127.0.0.1:4444/session/ec4d374b-53af-9845-a1e1-de00d0b83efa/url | {"url":"http://www.ford.com/#here"}
2017-06-20 18:02:35 DEBUG Selenium      > {"Accept"=>"application/json", "Content-Type"=>"application/json; charset=utf-8", "Content-Length"=>"35"}
1497960155659	webdriver::server	DEBUG	-> POST /session/ec4d374b-53af-9845-a1e1-de00d0b83efa/url {"url":"http://www.ford.com/#here"}
1497960155660	geckodriver::marionette	TRACE	-> 47:[0,2,"get",{"url":"http://www.ford.com/#here"}]
1497960155661	Marionette	TRACE	conn0 -> [0,2,"get",{"url":"http://www.ford.com/#here"}]
2017-06-20 18:02:35.739 plugin-container[88671:13876341] *** CFMessagePort: bootstrap_register(): failed 1100 (0x44c) 'Permission denied', port = 0x9c3b, name = 'com.apple.tsm.portname'
See /usr/include/servers/bootstrap_defs.h for the error codes.
2017-06-20 18:02:35.746 plugin-container[88671:13876341] *** CFMessagePort: bootstrap_register(): failed 1100 (0x44c) 'Permission denied', port = 0x9f03, name = 'com.apple.CFPasteboardClient'
See /usr/include/servers/bootstrap_defs.h for the error codes.
1497960159247	Marionette	TRACE	conn0 <- [1,2,null,{}]
1497960159250	geckodriver::marionette	TRACE	<- [1,2,null,{}]
1497960159250	webdriver::server	DEBUG	<- 200 OK {"value": {}}
2017-06-20 18:02:39 INFO Selenium <- {"value": {}}
2017-06-20 18:02:39 INFO Selenium -> POST session/ec4d374b-53af-9845-a1e1-de00d0b83efa/url
2017-06-20 18:02:39 INFO Selenium    >>> http://127.0.0.1:4444/session/ec4d374b-53af-9845-a1e1-de00d0b83efa/url | {"url":"http://www.ford.com/#here"}
2017-06-20 18:02:39 DEBUG Selenium      > {"Accept"=>"application/json", "Content-Type"=>"application/json; charset=utf-8", "Content-Length"=>"35"}
1497960159251	webdriver::server	DEBUG	-> POST /session/ec4d374b-53af-9845-a1e1-de00d0b83efa/url {"url":"http://www.ford.com/#here"}
1497960159253	geckodriver::marionette	TRACE	-> 47:[0,3,"get",{"url":"http://www.ford.com/#here"}]
1497960159255	Marionette	TRACE	conn0 -> [0,3,"get",{"url":"http://www.ford.com/#here"}]
1497960219294	Marionette	DEBUG	Closed connection conn0
/Users/p0deje/.rbenv/versions/2.4.1/lib/ruby/2.4.0/net/protocol.rb:176:in `rbuf_fill': Net::ReadTimeout (Net::ReadTimeout)
	from /Users/p0deje/.rbenv/versions/2.4.1/lib/ruby/2.4.0/net/protocol.rb:154:in `readuntil'
	from /Users/p0deje/.rbenv/versions/2.4.1/lib/ruby/2.4.0/net/protocol.rb:164:in `readline'
	from /Users/p0deje/.rbenv/versions/2.4.1/lib/ruby/2.4.0/net/http/response.rb:40:in `read_status_line'
	from /Users/p0deje/.rbenv/versions/2.4.1/lib/ruby/2.4.0/net/http/response.rb:29:in `read_new'
	from /Users/p0deje/.rbenv/versions/2.4.1/lib/ruby/2.4.0/net/http.rb:1446:in `block in transport_request'
	from /Users/p0deje/.rbenv/versions/2.4.1/lib/ruby/2.4.0/net/http.rb:1443:in `catch'
	from /Users/p0deje/.rbenv/versions/2.4.1/lib/ruby/2.4.0/net/http.rb:1443:in `transport_request'
	from /Users/p0deje/.rbenv/versions/2.4.1/lib/ruby/2.4.0/net/http.rb:1416:in `request'
	from /Users/p0deje/.rbenv/versions/2.4.1/lib/ruby/2.4.0/net/http.rb:1409:in `block in request'
	from /Users/p0deje/.rbenv/versions/2.4.1/lib/ruby/2.4.0/net/http.rb:877:in `start'
	from /Users/p0deje/.rbenv/versions/2.4.1/lib/ruby/2.4.0/net/http.rb:1407:in `request'
	from /Users/p0deje/Development/selenium/rb/lib/selenium/webdriver/remote/http/default.rb:124:in `response_for'
	from /Users/p0deje/Development/selenium/rb/lib/selenium/webdriver/remote/http/default.rb:78:in `request'
	from /Users/p0deje/Development/selenium/rb/lib/selenium/webdriver/remote/http/common.rb:61:in `call'
	from /Users/p0deje/Development/selenium/rb/lib/selenium/webdriver/remote/bridge.rb:170:in `execute'
	from /Users/p0deje/Development/selenium/rb/lib/selenium/webdriver/remote/w3c/bridge.rb:535:in `execute'
	from /Users/p0deje/Development/selenium/rb/lib/selenium/webdriver/remote/w3c/bridge.rb:59:in `get'
	from /Users/p0deje/Development/selenium/rb/lib/selenium/webdriver/common/navigation.rb:32:in `to'
	from test.rb:9:in `<main>'
```

**Comment by andreastt** [comment]
I suspect this is fixed in a more recent Firefox. Can you please test again with Firefox Nightly, and if it still does not work, please attach a trace-level geckodriver log?

**Comment by p0deje** [comment]
I have just ran this on 56.0a1 (2017-06-20) (64-bit) and still see the same issue. Here is the log (though it's mixed with Selenium logs):

```
2017-06-20 19:31:02 DEBUG Selenium Executing Process ["/usr/local/bin/geckodriver", "--binary=/Applications/Firefox.app/Contents/MacOS/firefox-bin", "--port=4444"]
2017-06-20 19:31:02 DEBUG Selenium polling for socket on ["127.0.0.1", 4444]
1497965462760	geckodriver	INFO	Listening on 127.0.0.1:4444
2017-06-20 19:31:02 INFO Selenium Skipping handshake as we know it is W3C.
2017-06-20 19:31:02 INFO Selenium -> POST session
2017-06-20 19:31:02 INFO Selenium    >>> http://127.0.0.1:4444/session | {"desiredCapabilities":{"browserName":"firefox","marionette":true,"timeouts":{},"moz:firefoxOptions":{"binary":"/Applications/FirefoxNightly.app/Contents/MacOS/firefox-bin","log":{"level":"trace"}}},"capabilities":{"firstMatch":[{"browserName":"firefox","timeouts":{},"moz:firefoxOptions":{"binary":"/Applications/FirefoxNightly.app/Contents/MacOS/firefox-bin","log":{"level":"trace"}}}]}}
2017-06-20 19:31:02 DEBUG Selenium      > {"Accept"=>"application/json", "Content-Type"=>"application/json; charset=utf-8", "Content-Length"=>"389"}
1497965463655	geckodriver::marionette	INFO	Starting browser /Applications/FirefoxNightly.app/Contents/MacOS/firefox-bin with args ["-marionette"]
1497965463682	geckodriver::marionette	TRACE	  connection attempt 0/600
1497965463785	geckodriver::marionette	TRACE	  connection attempt 1/600
1497965463891	geckodriver::marionette	TRACE	  connection attempt 2/600
1497965463992	geckodriver::marionette	TRACE	  connection attempt 3/600
1497965464095	geckodriver::marionette	TRACE	  connection attempt 4/600
1497965464198	geckodriver::marionette	TRACE	  connection attempt 5/600
1497965464303	geckodriver::marionette	TRACE	  connection attempt 6/600
1497965464407	geckodriver::marionette	TRACE	  connection attempt 7/600
1497965464511	geckodriver::marionette	TRACE	  connection attempt 8/600
1497965464617	geckodriver::marionette	TRACE	  connection attempt 9/600
1497965464720	geckodriver::marionette	TRACE	  connection attempt 10/600
1497965464824	geckodriver::marionette	TRACE	  connection attempt 11/600
1497965464930	geckodriver::marionette	TRACE	  connection attempt 12/600
1497965465031	geckodriver::marionette	TRACE	  connection attempt 13/600
1497965465136	geckodriver::marionette	TRACE	  connection attempt 14/600
1497965465240	geckodriver::marionette	TRACE	  connection attempt 15/600
1497965465345	geckodriver::marionette	TRACE	  connection attempt 16/600
1497965465450	geckodriver::marionette	TRACE	  connection attempt 17/600
1497965465553	geckodriver::marionette	TRACE	  connection attempt 18/600
1497965465657	geckodriver::marionette	TRACE	  connection attempt 19/600
1497965465773	geckodriver::marionette	TRACE	  connection attempt 20/600
1497965465878	geckodriver::marionette	TRACE	  connection attempt 21/600
1497965465983	geckodriver::marionette	TRACE	  connection attempt 22/600
1497965466087	geckodriver::marionette	TRACE	  connection attempt 23/600
1497965466192	geckodriver::marionette	TRACE	  connection attempt 24/600
1497965466296	geckodriver::marionette	TRACE	  connection attempt 25/600
1497965466401	geckodriver::marionette	TRACE	  connection attempt 26/600
1497965466506	geckodriver::marionette	TRACE	  connection attempt 27/600
1497965466610	geckodriver::marionette	TRACE	  connection attempt 28/600
1497965466714	geckodriver::marionette	TRACE	  connection attempt 29/600
1497965466819	geckodriver::marionette	TRACE	  connection attempt 30/600
1497965466924	geckodriver::marionette	TRACE	  connection attempt 31/600
1497965467031	geckodriver::marionette	TRACE	  connection attempt 32/600
1497965467134	geckodriver::marionette	TRACE	  connection attempt 33/600
1497965467239	geckodriver::marionette	TRACE	  connection attempt 34/600
1497965467345	geckodriver::marionette	TRACE	  connection attempt 35/600
1497965467450	geckodriver::marionette	TRACE	  connection attempt 36/600
1497965467552	geckodriver::marionette	TRACE	  connection attempt 37/600
2017-06-20 19:31:07.558 plugin-container[91001:13938361] *** CFMessagePort: bootstrap_register(): failed 1100 (0x44c) 'Permission denied', port = 0xb33b, name = 'com.apple.tsm.portname'
See /usr/include/servers/bootstrap_defs.h for the error codes.
2017-06-20 19:31:07.560 plugin-container[91001:13938361] *** CFMessagePort: bootstrap_register(): failed 1100 (0x44c) 'Permission denied', port = 0xb603, name = 'com.apple.CFPasteboardClient'
See /usr/include/servers/bootstrap_defs.h for the error codes.
1497965467657	geckodriver::marionette	TRACE	  connection attempt 38/600
1497965467763	geckodriver::marionette	TRACE	  connection attempt 39/600
1497965467868	geckodriver::marionette	TRACE	  connection attempt 40/600
1497965467972	geckodriver::marionette	TRACE	  connection attempt 41/600
1497965468078	geckodriver::marionette	TRACE	  connection attempt 42/600
1497965468183	geckodriver::marionette	TRACE	  connection attempt 43/600
1497965468287	geckodriver::marionette	TRACE	  connection attempt 44/600
2017-06-20 19:31:08.340 plugin-container[91002:13938489] *** CFMessagePort: bootstrap_register(): failed 1100 (0x44c) 'Permission denied', port = 0xb13b, name = 'com.apple.tsm.portname'
See /usr/include/servers/bootstrap_defs.h for the error codes.
2017-06-20 19:31:08.345 plugin-container[91002:13938489] *** CFMessagePort: bootstrap_register(): failed 1100 (0x44c) 'Permission denied', port = 0xb403, name = 'com.apple.CFPasteboardClient'
See /usr/include/servers/bootstrap_defs.h for the error codes.
1497965468367	Marionette	DEBUG	Setting recommended pref toolkit.cosmeticAnimations.enabled to false
1497965468367	Marionette	DEBUG	Setting recommended pref datareporting.policy.dataSubmissionPolicyAccepted to false
1497965468368	Marionette	INFO	Listening on port 60679
1497965468392	geckodriver::marionette	DEBUG	Connected to Marionette on localhost:60679
1497965468401	Marionette	DEBUG	Accepted connection 0 from 127.0.0.1:60824
1497965468406	geckodriver::marionette	TRACE	<- {"applicationType":"gecko","marionetteProtocol":3}
1497965468407	geckodriver::marionette	TRACE	-> 137:[0,1,"newSession",{"browserName":"firefox","capabilities":{"desiredCapabilities":{"browserName":"firefox","timeouts":{}}},"timeouts":{}}]
1497965468430	Marionette	TRACE	0 -> [0,1,"newSession",{"browserName":"firefox","capabilities":{"desiredCapabilities":{"browserName":"firefox","timeouts":{}}},"timeouts":{}}]
1497965468435	Marionette	CONFIG	Matched capabilities: {"browserName":"firefox","browserVersion":"56.0a1","platformName":"darwin","platformVersion":"16.6.0","pageLoadStrategy":"normal","acceptInsecureCerts":false,"timeouts":{"implicit":0,"pageLoad":300000,"script":30000},"rotatable":false,"specificationLevel":0,"moz:processID":91000,"moz:profile":"/var/folders/3s/yybq9c5n4pd0z9t4phtp6ml00000gn/T/rust_mozprofile.lBELk4VJk2WQ","moz:accessibilityChecks":false}
1497965468479	Marionette	DEBUG	loaded listener.js
1497965468495	Marionette	TRACE	0 <- [1,1,null,{"sessionId":"4e533241-14fd-2149-ba25-c78f83456c4c","capabilities":{"browserName":"firefox","browserVersion":"56.0a1","platformName":"darwin","platformVersion":"16.6.0","pageLoadStrategy":"normal","acceptInsecureCerts":false,"timeouts":{"implicit":0,"pageLoad":300000,"script":30000},"rotatable":false,"specificationLevel":0,"moz:processID":91000,"moz:profile":"/var/folders/3s/yybq9c5n4pd0z9t4phtp6ml00000gn/T/rust_mozprofile.lBELk4VJk2WQ","moz:accessibilityChecks":false}}]
1497965468503	geckodriver::marionette	TRACE	<- [1,1,null,{"sessionId":"4e533241-14fd-2149-ba25-c78f83456c4c","capabilities":{"browserName":"firefox","browserVersion":"56.0a1","platformName":"darwin","platformVersion":"16.6.0","pageLoadStrategy":"normal","acceptInsecureCerts":false,"timeouts":{"implicit":0,"pageLoad":300000,"script":30000},"rotatable":false,"specificationLevel":0,"moz:processID":91000,"moz:profile":"/var/folders/3s/yybq9c5n4pd0z9t4phtp6ml00000gn/T/rust_mozprofile.lBELk4VJk2WQ","moz:accessibilityChecks":false}}]
1497965468504	webdriver::server	DEBUG	<- 200 OK {"value": {"sessionId":"4e533241-14fd-2149-ba25-c78f83456c4c","capabilities":{"acceptInsecureCerts":false,"browserName":"firefox","browserVersion":"56.0a1","moz:accessibilityChecks":false,"moz:processID":91000,"moz:profile":"/var/folders/3s/yybq9c5n4pd0z9t4phtp6ml00000gn/T/rust_mozprofile.lBELk4VJk2WQ","pageLoadStrategy":"normal","platformName":"darwin","platformVersion":"16.6.0","rotatable":false,"specificationLevel":0,"timeouts":{"implicit":0,"pageLoad":300000,"script":30000}}}}
2017-06-20 19:31:08 INFO Selenium <- {"value": {"sessionId":"4e533241-14fd-2149-ba25-c78f83456c4c","capabilities":{"acceptInsecureCerts":false,"browserName":"firefox","browserVersion":"56.0a1","moz:accessibilityChecks":false,"moz:processID":91000,"moz:profile":"/var/folders/3s/yybq9c5n4pd0z9t4phtp6ml00000gn/T/rust_mozprofile.lBELk4VJk2WQ","pageLoadStrategy":"normal","platformName":"darwin","platformVersion":"16.6.0","rotatable":false,"specificationLevel":0,"timeouts":{"implicit":0,"pageLoad":300000,"script":30000}}}}
2017-06-20 19:31:08 INFO Selenium Detected W3C dialect.
2017-06-20 19:31:08 INFO Selenium -> POST session/4e533241-14fd-2149-ba25-c78f83456c4c/url
2017-06-20 19:31:08 INFO Selenium    >>> http://127.0.0.1:4444/session/4e533241-14fd-2149-ba25-c78f83456c4c/url | {"url":"http://www.ford.com/#here"}
2017-06-20 19:31:08 DEBUG Selenium      > {"Accept"=>"application/json", "Content-Type"=>"application/json; charset=utf-8", "Content-Length"=>"35"}
1497965468515	webdriver::server	DEBUG	-> POST /session/4e533241-14fd-2149-ba25-c78f83456c4c/url {"url":"http://www.ford.com/#here"}
1497965468517	geckodriver::marionette	TRACE	-> 47:[0,2,"get",{"url":"http://www.ford.com/#here"}]
1497965468519	Marionette	TRACE	0 -> [0,2,"get",{"url":"http://www.ford.com/#here"}]
1497965468523	Marionette	DEBUG	Received DOM event "beforeunload" for "about:blank"
1497965469413	Marionette	DEBUG	Received DOM event "pagehide" for "about:blank"
1497965469414	Marionette	DEBUG	Received DOM event "unload" for "about:blank"
1497965472215	Marionette	DEBUG	Received DOM event "DOMContentLoaded" for "http://www.ford.com/#here"
1497965473316	Marionette	DEBUG	Received observer notification "outer-window-destroyed" for "2147483653"
1497965473898	Marionette	DEBUG	Received DOM event "pageshow" for "http://www.ford.com/#here"
1497965473912	Marionette	TRACE	0 <- [1,2,null,{}]
1497965473917	geckodriver::marionette	TRACE	<- [1,2,null,{}]
1497965473917	webdriver::server	DEBUG	<- 200 OK {"value": {}}
2017-06-20 19:31:13 INFO Selenium <- {"value": {}}
2017-06-20 19:31:13 INFO Selenium -> POST session/4e533241-14fd-2149-ba25-c78f83456c4c/url
2017-06-20 19:31:13 INFO Selenium    >>> http://127.0.0.1:4444/session/4e533241-14fd-2149-ba25-c78f83456c4c/url | {"url":"http://www.ford.com/#here"}
2017-06-20 19:31:13 DEBUG Selenium      > {"Accept"=>"application/json", "Content-Type"=>"application/json; charset=utf-8", "Content-Length"=>"35"}
1497965473921	webdriver::server	DEBUG	-> POST /session/4e533241-14fd-2149-ba25-c78f83456c4c/url {"url":"http://www.ford.com/#here"}
1497965473923	geckodriver::marionette	TRACE	-> 47:[0,3,"get",{"url":"http://www.ford.com/#here"}]
1497965473925	Marionette	TRACE	0 -> [0,3,"get",{"url":"http://www.ford.com/#here"}]
1497965474089	Marionette	DEBUG	Received DOM event "pagehide" for "http://www.ford.com/#here"
1497965474094	Marionette	DEBUG	Received DOM event "pagehide" for "http://www.ford.com/#here"
1497965474117	Marionette	DEBUG	Received DOM event "pagehide" for "http://www.ford.com/#here"
1497965474391	Marionette	DEBUG	Received DOM event "pagehide" for "http://www.ford.com/#here"
1497965474704	Marionette	DEBUG	Received DOM event "pagehide" for "http://assets.adobedtm.com/a07333cf048521a77d8805932555ede8eefdb471/scripts/satellite-587e8e0164746d47d300ae2b.html?dart-u1-nameplate=na&dart-u12-cks-lead-id=na&dart-u14-fdaf-code=na&dart-u15-user-language-rad-ui=eng%3Aui%3Arad%3Apc&dart-u17-site=na&dart-u19-page-name-no-vehicle=fv%3Ahome&dart-u20-url=http%3A//www.ford.com/%23here&dart-u9-model-year-nameplate=na"
1497965475007	Marionette	DEBUG	Received DOM event "pagehide" for "https://690327.fls.doubleclick.net/activityi;src=690327;type=fvflup;cat=bhp;u1=na;u9=na;u12=na;u14=na;u15=eng:ui:rad:pc;u17=na;u19=fv:home;u20=http://www.ford.com/#here;ord=6081882218266.968?"
1497965475101	Marionette	DEBUG	Received DOM event "pagehide" for "https://690327.fls.doubleclick.net/activityi;src=690327;type=fvflup;cat=bhp;u1=na;u9=na;u12=na;u14=na;u15=eng:ui:rad:pc;u17=na;u19=fv:home;u20=http://www.ford.com/#here;ord=6081882218266.968?"
1497965475140	Marionette	DEBUG	Received DOM event "pagehide" for "http://690327.fls.doubleclick.net/activityi;src=690327;type=fvflup;cat=bhp;u1=na;u9=na;u12=na;u14=na;u15=eng:ui:rad:pc;u17=na;u19=fv:home;u20=http://www.ford.com/#here;ord=8026608294830.753?"
1497965533935	Marionette	DEBUG	Closed connection 0
/Users/p0deje/.rbenv/versions/2.4.1/lib/ruby/2.4.0/net/protocol.rb:176:in `rbuf_fill': Net::ReadTimeout (Net::ReadTimeout)
	from /Users/p0deje/.rbenv/versions/2.4.1/lib/ruby/2.4.0/net/protocol.rb:154:in `readuntil'
	from /Users/p0deje/.rbenv/versions/2.4.1/lib/ruby/2.4.0/net/protocol.rb:164:in `readline'
	from /Users/p0deje/.rbenv/versions/2.4.1/lib/ruby/2.4.0/net/http/response.rb:40:in `read_status_line'
	from /Users/p0deje/.rbenv/versions/2.4.1/lib/ruby/2.4.0/net/http/response.rb:29:in `read_new'
	from /Users/p0deje/.rbenv/versions/2.4.1/lib/ruby/2.4.0/net/http.rb:1446:in `block in transport_request'
	from /Users/p0deje/.rbenv/versions/2.4.1/lib/ruby/2.4.0/net/http.rb:1443:in `catch'
	from /Users/p0deje/.rbenv/versions/2.4.1/lib/ruby/2.4.0/net/http.rb:1443:in `transport_request'
	from /Users/p0deje/.rbenv/versions/2.4.1/lib/ruby/2.4.0/net/http.rb:1416:in `request'
	from /Users/p0deje/.rbenv/versions/2.4.1/lib/ruby/2.4.0/net/http.rb:1409:in `block in request'
	from /Users/p0deje/.rbenv/versions/2.4.1/lib/ruby/2.4.0/net/http.rb:877:in `start'
	from /Users/p0deje/.rbenv/versions/2.4.1/lib/ruby/2.4.0/net/http.rb:1407:in `request'
	from /Users/p0deje/Development/selenium/rb/lib/selenium/webdriver/remote/http/default.rb:124:in `response_for'
	from /Users/p0deje/Development/selenium/rb/lib/selenium/webdriver/remote/http/default.rb:78:in `request'
	from /Users/p0deje/Development/selenium/rb/lib/selenium/webdriver/remote/http/common.rb:61:in `call'
	from /Users/p0deje/Development/selenium/rb/lib/selenium/webdriver/remote/bridge.rb:170:in `execute'
	from /Users/p0deje/Development/selenium/rb/lib/selenium/webdriver/remote/w3c/bridge.rb:535:in `execute'
	from /Users/p0deje/Development/selenium/rb/lib/selenium/webdriver/remote/w3c/bridge.rb:59:in `get'
	from /Users/p0deje/Development/selenium/rb/lib/selenium/webdriver/common/navigation.rb:32:in `to'
	from test.rb:10:in `<main>'
```

**Comment by andreastt** [comment]
Thanks for the log, that’s helpful.

Immediately, it looks to me that the checks I added for this in https://hg.mozilla.org/mozilla-central/rev/39a2655e787d are gone, but have not been replaced by equivalent functionality in the web progress listener. We do have a test for navigation by hash in https://searchfox.org/mozilla-central/rev/2bcd258281da848311769281daf735601685de2d/testing/marionette/harness/marionette_harness/tests/unit/test_navigation.py#186, but I can’t spot any tests for navigation to the _same_ hash.

@whimboo has made changes in this area, so I’ll let him comment further.

**Comment by whimboo** [comment]
This is not a page load with a hash change, but loading the same page again. It's interesting that we get `pagehide` events fired, but it could mean that the page was put into `bfcache`. I can reproduce this with Marionette, so I will file a bug for that.

**Comment by whimboo** [comment]
The bug to handle that is https://bugzilla.mozilla.org/show_bug.cgi?id=1374672. Thank you for the report!

**Comment by whimboo** [comment]
This is now fixed and will be available starting with the Firefox Nightly build by tomorrow.
