### ISSUE TITLE
Too much recursion error when serialising recursive objects

### ISSUE THREAD

**Issue by borishinzer** [mozilla/geckodriver#792]
## Platform and application details
* Platform: OSX
* Firefox: 54.0 (64-Bit)
* Selenium: 3.4.0

## Steps to reproduce
Codeception Acceptance Test
```
$I = new AcceptanceTester($scenario);
$I->wantTo('Check datalayer');
$I->amOnUrl('https://www.web-vision.de/');
$dataLayer = $I->executeJS('return dataLayer;');
```

- [ ] A trace level log:
I don't know where the log will be saved. So if someone could help me with this I will provide the trace level log.

My node.json looks like this:
```
{
    "capabilities":
    [
        {
            "browserName": "firefox",
            "maxInstances": 5,
            "seleniumProtocol": "WebDriver",
            "platform": "MAC",
            "moz:firefoxOptions": {
                "log": {
                    "level": "trace"
                }
            }
        }
    ],
    "proxy": "org.openqa.grid.selenium.proxy.DefaultRemoteProxy",
    "maxSession": 5,
    "port": 5558,
    "register": true,
    "registerCycle": 5000,
    "hub": "http://localhost:4444",
    "nodeStatusCheckTimeout": 5000,
    "nodePolling": 5000,
    "role": "node",
    "unregisterIfStillDownAfter": 60000,
    "downPollingLimit": 2,
    "debug": false,
    "servlets" : [],
    "withoutServlets": [],
    "custom": {}
}
```

The trace from selenium looks like this:
```
11:43:10.069 INFO - Executing: [execute script: return dataLayer, []])
11:43:11.188 WARN - Exception thrown
org.openqa.selenium.WebDriverException: InternalError: too much recursion
Build info: version: '3.4.0', revision: 'unknown', time: 'unknown'
System info: host: 'MacbookPro', ip: 'fe80:0:0:0:c6b:1c02:695d:c13b%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.12.4', java.version: '1.8.0_121'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{moz:profile=/var/folders/kp/xndg6w6112q2cxt_6rj5m_jm0000gp/T/rust_mozprofile.VkvHQvsuJ0cA, rotatable=false, timeouts={implicit=0.0, pageLoad=300000.0, script=30000.0}, pageLoadStrategy=normal, platform=ANY, specificationLevel=0.0, moz:accessibilityChecks=false, acceptInsecureCerts=false, browserVersion=54.0, platformVersion=16.5.0, moz:processID=98550.0, browserName=firefox, javascriptEnabled=true, platformName=darwin}]
Session ID: 8c2d3079-2c87-404e-b031-6e1a6e23f292
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:150)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:115)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:45)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:164)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:82)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:637)
	at org.openqa.selenium.remote.RemoteWebDriver.executeScript(RemoteWebDriver.java:573)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.openqa.selenium.support.events.EventFiringWebDriver$2.invoke(EventFiringWebDriver.java:104)
	at com.sun.proxy.$Proxy6.executeScript(Unknown Source)
	at org.openqa.selenium.support.events.EventFiringWebDriver.executeScript(EventFiringWebDriver.java:217)
	at org.openqa.selenium.remote.server.handler.ExecuteScript.call(ExecuteScript.java:56)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at org.openqa.selenium.remote.server.DefaultSession$1.run(DefaultSession.java:176)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by florentbr** [comment]
This error usually occurs when an object returned with `execute script` contains a circular reference.

For instance, the driver will fail to return object `a` :

    var a = {};
    a.b = {parent: a};
    return a;

It's not possible to serialize an object with a circular reference, so make sure that there are none in the returned object.

**Comment by andreastt** [comment]
I think the ‘internal JSON clone algorithm’ in the specification caters for this, but we’re implementing an old version of the specification for evaluating scripts.

**Comment by borishinzer** [comment]
The same test runs fine in chrome and as far as I'm aware of the google dataLayer doesn't contain circular references, at least I can't see any

**Comment by andreastt** [comment]
If it contains a `WindowProxy` object, that causes recursion because it references itself.

**Comment by whimboo** [comment]
@borishinzer would you mind attaching a trace level log for this test? It would show us what might go wrong here. Also I don't see what `$I->wantTo('Check datalayer');` is actually doing.

**Comment by borishinzer** [comment]
@whimboo I would like too if someone tells me where the trace level log is saved or displayed.
I added the json I use to load the selenium node where I added the moz:firefoxOptions. If something is wrong with the config please tell me what is wrong.

**Comment by whimboo** [comment]
I don't know the node.js binding and how it has been implemented there. Maybe ask someone from this project. Otherwise please explain what this `dataLayer` is, because I cannot find it in the page after just loading it. Maybe something else sets it?

**Comment by borishinzer** [comment]
dataLayer is a javascript array used by google tag manager. You can find more information here: https://developers.google.com/tag-manager/devguide

**Comment by whimboo** [comment]
Would it be possible for you to tell us what the content of `dataLayer` is in your failing case?

**Comment by andreastt** [comment]
`dataLayer` appears to be a non-serialisable JSON type:

![screenshot-2017-08-22-111244](https://user-images.githubusercontent.com/399120/29560720-dd18fc18-872a-11e7-96df-6790ccbf2fae.png)

**Comment by whimboo** [comment]
This is actually a dupe of issue #328.
