### ISSUE TITLE
Maximize Window errors with "Failed to find width field"

### ISSUE THREAD

**Issue by evgeny1** [mozilla/geckodriver#820]
gecko v 0.18
FF v 54.0.1
Windows 10
WebDriver v 3.4.0

Steps:
`FirefoxDriver driver = new FirefoxDriver(capabilities);`
`driver.manage().window().maximize();` <- this is where the exception is getting thrown:

`org.openqa.selenium.WebDriverException: Failed to find width field
Build info: version: '3.4.0', revision: 'unknown', time: 'unknown'
System info: host: 'WINX0046', ip: '10.90.4.69', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_131'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{moz:profile=C:\Users\a955q\AppData\Local\Temp\1\rust_mozprofile.ynsZrL2A7MOT, rotatable=false, timeouts={implicit=0.0, pageLoad=300000.0, script=30000.0}, pageLoadStrategy=normal, platform=ANY, specificationLevel=0.0, moz:accessibilityChecks=false, acceptInsecureCerts=true, browserVersion=54.0.1, platformVersion=10.0, moz:processID=3412.0, browserName=firefox, javascriptEnabled=true, platformName=windows_nt}]
Session ID: 9c9c6a26-aef0-4d18-8299-43ada4cf0d5e`

The command being sent:
`[520ae916-5f9f-4227-8a5f-2d6d8aa0b318, maximizeCurrentWindow {}]`
The response:
`(Response: SessionID: null, Status: 13, Value: org.openqa.selenium.WebDriverException: Failed to find width field
Build info: version: '3.4.0', revision: 'unknown', time: 'unknown'
System info: host: 'WINX0046', ip: '10.90.4.69', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_131'
Driver info: driver.version: RemoteWebDriver)`

This issue makes the above code return null for the driver.

**Comment by andreastt** [comment]
Can you include the full trace-level log, please?

**Comment by evgeny1** [comment]
Full error log:
```org.openqa.selenium.WebDriverException: Failed to find width field
Build info: version: '3.4.0', revision: 'unknown', time: 'unknown'
System info: host: 'WINX0046', ip: '10.90.4.69', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_131'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{moz:profile=C:\Users\a955q\AppData\Local\Temp\1\rust_mozprofile.uD0R20gSokXG, rotatable=false, timeouts={implicit=0.0, pageLoad=300000.0, script=30000.0}, pageLoadStrategy=normal, platform=ANY, specificationLevel=0.0, moz:accessibilityChecks=false, acceptInsecureCerts=true, browserVersion=54.0.1, platformVersion=10.0, moz:processID=10396.0, browserName=firefox, javascriptEnabled=true, platformName=windows_nt}]
Session ID: 520ae916-5f9f-4227-8a5f-2d6d8aa0b318
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:150)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:115)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:45)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:164)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:82)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:637)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:694)
	at org.openqa.selenium.remote.RemoteWebDriver$RemoteWebDriverOptions$RemoteWindow.maximize(RemoteWebDriver.java:925)
	at com.infarmbureau.qa.providers.FirefoxDriverProvider.newWebDriver(FirefoxDriverProvider.java:20)
	at com.infarmbureau.qa.providers.FirefoxDriverProvider.newWebDriver(FirefoxDriverProvider.java:34)
	at com.infarmbureau.qa.providers.FirefoxDriverProvider.newWebDriver(FirefoxDriverProvider.java:1)
	at com.infarmbureau.qa.templates.WebDriverTemplate.beforeSetUp(WebDriverTemplate.java:70)
	at com.infarmbureau.qa.templates.TestTemplate$1.starting(TestTemplate.java:65)
	at org.junit.rules.TestWatcher.startingQuietly(TestWatcher.java:108)
	at org.junit.rules.TestWatcher.access$000(TestWatcher.java:46)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:53)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)`

java.lang.NullPointerException
	at com.infarmbureau.crm.qa.IfbCrmTest.setUp(IfbCrmTest.java:52)
	at com.infarmbureau.crm.qa.test_steps.TestSteps.setUp(TestSteps.java:38)
	at com.infarmbureau.crm.qa.ClientAddTest.setUp(ClientAddTest.java:29)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)```

**Comment by evgeny1** [comment]
The NPE is expected here, so I did not include it in the error log.

**Comment by SankySyS** [comment]
I have the same error. 

org.openqa.selenium.WebDriverException: Failed to find width field
Build info: version: '3.4.0', revision: 'unknown', time: 'unknown'
System info: host: 'DL', ip: '192.168.0.1', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_131'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{moz:profile=C:\Users\LEONTI~1\AppData\Local\Temp\rust_mozprofile.u6NdiZaKwdq7, rotatable=false, timeouts={implicit=0.0, pageLoad=300000.0, script=30000.0}, pageLoadStrategy=normal, platform=ANY, specificationLevel=0.0, moz:accessibilityChecks=false, acceptInsecureCerts=true, browserVersion=54.0.1, platformVersion=6.1, moz:processID=15704.0, browserName=firefox, javascriptEnabled=true, platformName=windows_nt}]
Session ID: 8584de4f-7eab-4855-b78d-9e400b1d9d6c
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:150)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:115)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:45)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:164)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:82)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:637)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:694)
	at org.openqa.selenium.remote.RemoteWebDriver$RemoteWebDriverOptions$RemoteWindow.maximize(RemoteWebDriver.java:925)
	at core.libs.SeleniumCore$seleniumHelper.start(SeleniumCore.java:286)
	at core.libs.SeleniumCore$seleniumHelper.start(SeleniumCore.java:240)
	at core.libs.SeleniumCore$seleniumHelper.startBrowser(SeleniumCore.java:300)
	at core.libs.Browser.start(Browser.java:44)
	at core.libs.Browser.start(Browser.java:32)
	at google.scripts.googletests.GoogleAbout.setUp(GoogleAbout.java:37)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)

**Comment by andreastt** [comment]
The Java stacktrace isn’t very helpful because it doesn’t say what your client sent to geckodriver, nor what geckodriver sent to and received from Marionette. I suspect that it fails to decode the response from Marionette, and that this could be the result of a programming error or that we accidentally broke backwards compatibility in Firefox. In that vein, it would be useful to also test with Firefox Nightly.

(I am still looking for a geckodriver trace-level log to diagnose this correctly.)

**Comment by SankySyS** [comment]
```
1499892954066	webdriver::server	DEBUG	-> POST /session/97029af2-6655-4fe4-bd87-032fd31515e7/window/maximize {}
1499892954067	geckodriver::marionette	TRACE	-> 25:[0,2,"maximizeWindow",{}]
1499892954083	Marionette	TRACE	0 -> [0,2,"maximizeWindow",{}]
1499892954367	Marionette	TRACE	0 <- [1,2,null,{}]
1499892954422	geckodriver::marionette	TRACE	<- [1,2,null,{}]
1499892954423	webdriver::server	DEBUG	<- 500 Internal Server Error {"value":{"error":"unknown error","message":"Failed to find width field","stacktrace":"stack backtrace:\n   0:           0x4bb74f - <no info>\n   1:           0x4bbea9 - <no info>\n   2:           0x44d60e - <no info>\n   3:           0x44944a - <no info>\n   4:           0x4203e1 - <no info>\n   5:           0x407dc7 - <no info>\n   6:           0x6d95b9 - <no info>\n   7:           0x4173a7 - <no info>\n   8:           0x6d38b3 - <no info>\n   9:         0x77b059cd - BaseThreadInitThunk"}}
```

**Comment by SankySyS** [comment]
With Firefox Nightly works as expected

**Comment by andreastt** [comment]
@SankySyS Thanks, that’s very helpful!

This means that the remote protocol in modern Firefoxen returns a window rect in the response from maximising the window. geckodriver looks for this, but since earlier Firefoxen doesn’t include it, it fails decoding the response.

It looks like this change (made in https://bugzilla.mozilla.org/show_bug.cgi?id=1357878) is only available in Firefox 55 (currently beta) and greater. Because 54 is stable, there is no chance of uplifting it there. The next uplift happens 2 August, which is only two weeks off from the time of writing this, which makes me think we’re better off waiting for the patch to ride the trains: when 55 reaches stable we can bump the recommended Firefox version to use with geckodriver to 55 (or I guess we could do that already?).

**Comment by abhishek-infi** [comment]
Jul 13, 2017 4:52:50 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: W3C
FAILED CONFIGURATION: @BeforeClass setupApplication
org.openqa.selenium.WebDriverException: Failed to find width field
Build info: version: '3.4.0', revision: 'unknown', time: 'unknown'
System info: host: 'LAPTOP-D69B8C99', ip: '192.168.2.115', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_131'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{moz:profile=C:\Users\HP\AppData\Local\Temp\rust_mozprofile.wQHpvIvpS6iZ, rotatable=false, timeouts={implicit=0.0, pageLoad=300000.0, script=30000.0}, pageLoadStrategy=normal, platform=ANY, specificationLevel=0.0, moz:accessibilityChecks=false, acceptInsecureCerts=false, browserVersion=54.0.1, platformVersion=10.0, moz:processID=13992.0, browserName=firefox, javascriptEnabled=true, platformName=windows_nt}]
Session ID: 254c346a-b31c-415d-9ba9-5c2768af51cf
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)




Firefox Version: 54.0
Web Driver 3.4.0
Gecko Driver v0.18
Eclipse Luna
Given all Dependecies but, I could see the same Error as Above

**Comment by andreastt** [comment]
I’m going to keep this issue open for tracking until Firefox 55 is released. My recommendation is to upgrade to Firefox 55, which is the new recommended Firefox version to use with geckodriver.

It’s a shame we didn’t discover this before releasing 0.18.0, but Firefox 55 will be out 2017-08-08 (see https://wiki.mozilla.org/RapidRelease/Calendar), which is not too far off.

**Comment by SchulteMarkus** [comment]
**Workaround** by setting size yourself 

    // driver.manage().window().maximize();
    driver.manage().window().setSize(new Dimension(1920, 1080));

**Comment by ToreyStapleton** [comment]
I'm using Protractor/Node so I use javascript promises, but this is also a nice workaround for dynamic width (local vs remote machine etc).:

`browser.driver.executeScript(function() {
	return {
		width: window.screen.availWidth,
		height: window.screen.availHeight
	};
}).then(function(result) {
	browser.driver.manage().window().setSize(result.width, result.height);
});`

**Comment by ToreyStapleton** [comment]
I'm using Protractor so I use javascript promises, but here's another workaround for dynamic screen width (local vs remote machine etc).

```
browser.driver.executeScript(function() {
	return {
		width: window.screen.availWidth,
		height: window.screen.availHeight
	};
}).then(function(result) {
	browser.driver.manage().window().setSize(result.width, result.height);
});
```

**Comment by romanbarabash** [comment]
win 10 ; gecko 0.018 ; FireFox 55.0beta ; selenium 3.4.0 -
driver.manage().window().maximize(); works for me.

**Comment by abhishekjain118** [comment]
Hi All, 
I too see this issue - 
what is the equivalent workaround for this issue in Python.. ?
i.e. 
driver.manage().window().setSize(new Dimension(1920, 1080)); ## java code
how do I write this in Python ?

**Comment by ohadperry** [comment]
@abhishekjain118  +1. also encountered this issue. updated firefox to 0.54

**Comment by asrafiq** [comment]
var screenWidth = Screen.PrimaryScreen.Bounds.Width;
            var screenHeight = Screen.PrimaryScreen.Bounds.Height;
            CurrentDriver.Manage().Window.Size = new Size(screenWidth, screenHeight);

**Comment by mseele** [comment]
Issue is still alive with firefox 55. 

This is my log with the `driver.manage().window().maximize();` line:

```1502114955655	geckodriver	INFO	geckodriver 0.18.0
1502114955666	geckodriver	INFO	Listening on 127.0.0.1:44513
1502114956405	geckodriver::marionette	INFO	Starting browser C:\Program Files\Mozilla Firefox\firefox.exe with args ["-marionette"]
1502114958063	Marionette	DEBUG	Setting recommended pref datareporting.policy.dataSubmissionPolicyAccepted to false
1502114958063	Marionette	INFO	Listening on port 63520
1502114958428	geckodriver::marionette	DEBUG	Connected to Marionette on localhost:63520
1502114958434	Marionette	DEBUG	Accepted connection 0 from 127.0.0.1:63524
1502114958435	geckodriver::marionette	TRACE	<- {"applicationType":"gecko","marionetteProtocol":3}
1502114958435	geckodriver::marionette	TRACE	-> 163:[0,1,"newSession",{"acceptInsecureCerts":true,"browserName":"firefox","capabilities":{"desiredCapabilities":{"acceptInsecureCerts":true,"browserName":"firefox"}}}]
1502114958439	Marionette	TRACE	0 -> [0,1,"newSession",{"acceptInsecureCerts":true,"browserName":"firefox","capabilities":{"desiredCapabilities":{"acceptInsecureCerts":true,"browserName":"firefox"}}}]
1502114958445	Marionette	CONFIG	Matched capabilities: {"browserName":"firefox","browserVersion":"54.0.1","platformName":"windows_nt","platformVersion":"10.0","pageLoadStrategy":"normal","acceptInsecureCerts":true,"timeouts":{"implicit":0,"pageLoad":300000,"script":30000},"rotatable":false,"specificationLevel":0,"moz:processID":6972,"moz:profile":"C:\\Users\\mseele\\AppData\\Local\\Temp\\rust_mozprofile.wVNcVyaLtCgf","moz:accessibilityChecks":false}
1502114958445	Marionette	WARN	TLS certificate errors will be ignored for this session
1502114958465	Marionette	DEBUG	loaded listener.js
1502114958475	Marionette	TRACE	0 <- [1,1,null,{"sessionId":"47bdfef8-e3af-4ec4-85ff-3f51551fd623","capabilities":{"browserName":"firefox","browserVersion":"54.0.1","platformName":"windows_nt","platformVersion":"10.0","pageLoadStrategy":"normal","acceptInsecureCerts":true,"timeouts":{"implicit":0,"pageLoad":300000,"script":30000},"rotatable":false,"specificationLevel":0,"moz:processID":6972,"moz:profile":"C:\\Users\\mseele\\AppData\\Local\\Temp\\rust_mozprofile.wVNcVyaLtCgf","moz:accessibilityChecks":false}}]
1502114958475	geckodriver::marionette	TRACE	<- [1,1,null,{"sessionId":"47bdfef8-e3af-4ec4-85ff-3f51551fd623","capabilities":{"browserName":"firefox","browserVersion":"54.0.1","platformName":"windows_nt","platformVersion":"10.0","pageLoadStrategy":"normal","acceptInsecureCerts":true,"timeouts":{"implicit":0,"pageLoad":300000,"script":30000},"rotatable":false,"specificationLevel":0,"moz:processID":6972,"moz:profile":"C:\\Users\\mseele\\AppData\\Local\\Temp\\rust_mozprofile.wVNcVyaLtCgf","moz:accessibilityChecks":false}}]
1502114958475	webdriver::server	DEBUG	<- 200 OK {"value": {"sessionId":"47bdfef8-e3af-4ec4-85ff-3f51551fd623","capabilities":{"acceptInsecureCerts":true,"browserName":"firefox","browserVersion":"54.0.1","moz:accessibilityChecks":false,"moz:processID":6972,"moz:profile":"C:\\Users\\mseele\\AppData\\Local\\Temp\\rust_mozprofile.wVNcVyaLtCgf","pageLoadStrategy":"normal","platformName":"windows_nt","platformVersion":"10.0","rotatable":false,"specificationLevel":0,"timeouts":{"implicit":0,"pageLoad":300000,"script":30000}}}}
1502114958554	webdriver::server	DEBUG	-> POST /session/47bdfef8-e3af-4ec4-85ff-3f51551fd623/window/maximize {}
1502114958555	geckodriver::marionette	TRACE	-> 25:[0,2,"maximizeWindow",{}]
1502114958558	Marionette	TRACE	0 -> [0,2,"maximizeWindow",{}]
1502114958565	Marionette	TRACE	0 <- [1,2,null,{}]
1502114958571	geckodriver::marionette	TRACE	<- [1,2,null,{}]
1502114958573	webdriver::server	DEBUG	<- 500 Internal Server Error {"value":{"error":"unknown error","message":"Failed to find width field","stacktrace":"stack backtrace:\n   0:           0x4bb74f - <no info>\n   1:           0x4bbea9 - <no info>\n   2:           0x44d60e - <no info>\n   3:           0x44944a - <no info>\n   4:           0x4203e1 - <no info>\n   5:           0x407dc7 - <no info>\n   6:           0x6d95b9 - <no info>\n   7:           0x4173a7 - <no info>\n   8:           0x6d38b3 - <no info>\n   9:     0x7ff9fbce2774 - BaseThreadInitThunk"}}
```

Here is my log without this line:

```1502115273865	geckodriver	INFO	geckodriver 0.18.0
1502115273875	geckodriver	INFO	Listening on 127.0.0.1:15054
1502115274546	geckodriver::marionette	INFO	Starting browser C:\Program Files\Mozilla Firefox\firefox.exe with args ["-marionette"]
1502115276179	Marionette	DEBUG	Setting recommended pref datareporting.policy.dataSubmissionPolicyAccepted to false
1502115276180	Marionette	INFO	Listening on port 63699
1502115276565	geckodriver::marionette	DEBUG	Connected to Marionette on localhost:63699
1502115276571	Marionette	DEBUG	Accepted connection 0 from 127.0.0.1:63704
1502115276574	geckodriver::marionette	TRACE	<- {"applicationType":"gecko","marionetteProtocol":3}
1502115276574	geckodriver::marionette	TRACE	-> 163:[0,1,"newSession",{"acceptInsecureCerts":true,"browserName":"firefox","capabilities":{"desiredCapabilities":{"acceptInsecureCerts":true,"browserName":"firefox"}}}]
1502115276594	Marionette	TRACE	0 -> [0,1,"newSession",{"acceptInsecureCerts":true,"browserName":"firefox","capabilities":{"desiredCapabilities":{"acceptInsecureCerts":true,"browserName":"firefox"}}}]
1502115276600	Marionette	CONFIG	Matched capabilities: {"browserName":"firefox","browserVersion":"54.0.1","platformName":"windows_nt","platformVersion":"10.0","pageLoadStrategy":"normal","acceptInsecureCerts":true,"timeouts":{"implicit":0,"pageLoad":300000,"script":30000},"rotatable":false,"specificationLevel":0,"moz:processID":1072,"moz:profile":"C:\\Users\\mseele\\AppData\\Local\\Temp\\rust_mozprofile.qdrMaXON22JI","moz:accessibilityChecks":false}
1502115276600	Marionette	WARN	TLS certificate errors will be ignored for this session
1502115276618	Marionette	DEBUG	loaded listener.js
1502115276627	Marionette	TRACE	0 <- [1,1,null,{"sessionId":"27873c02-8864-47a8-aedc-707bfcab4f35","capabilities":{"browserName":"firefox","browserVersion":"54.0.1","platformName":"windows_nt","platformVersion":"10.0","pageLoadStrategy":"normal","acceptInsecureCerts":true,"timeouts":{"implicit":0,"pageLoad":300000,"script":30000},"rotatable":false,"specificationLevel":0,"moz:processID":1072,"moz:profile":"C:\\Users\\mseele\\AppData\\Local\\Temp\\rust_mozprofile.qdrMaXON22JI","moz:accessibilityChecks":false}}]
1502115276627	geckodriver::marionette	TRACE	<- [1,1,null,{"sessionId":"27873c02-8864-47a8-aedc-707bfcab4f35","capabilities":{"browserName":"firefox","browserVersion":"54.0.1","platformName":"windows_nt","platformVersion":"10.0","pageLoadStrategy":"normal","acceptInsecureCerts":true,"timeouts":{"implicit":0,"pageLoad":300000,"script":30000},"rotatable":false,"specificationLevel":0,"moz:processID":1072,"moz:profile":"C:\\Users\\mseele\\AppData\\Local\\Temp\\rust_mozprofile.qdrMaXON22JI","moz:accessibilityChecks":false}}]
1502115276627	webdriver::server	DEBUG	<- 200 OK {"value": {"sessionId":"27873c02-8864-47a8-aedc-707bfcab4f35","capabilities":{"acceptInsecureCerts":true,"browserName":"firefox","browserVersion":"54.0.1","moz:accessibilityChecks":false,"moz:processID":1072,"moz:profile":"C:\\Users\\mseele\\AppData\\Local\\Temp\\rust_mozprofile.qdrMaXON22JI","pageLoadStrategy":"normal","platformName":"windows_nt","platformVersion":"10.0","rotatable":false,"specificationLevel":0,"timeouts":{"implicit":0,"pageLoad":300000,"script":30000}}}}
1502115276702	webdriver::server	DEBUG	-> POST /session/27873c02-8864-47a8-aedc-707bfcab4f35/timeouts {"implicit":30000}
1502115276703	geckodriver::marionette	TRACE	-> 38:[0,2,"setTimeouts",{"implicit":30000}]
1502115276723	Marionette	TRACE	0 -> [0,2,"setTimeouts",{"implicit":30000}]
1502115276726	Marionette	TRACE	0 <- [1,2,null,{}]
1502115276730	geckodriver::marionette	TRACE	<- [1,2,null,{}]
1502115276730	webdriver::server	DEBUG	<- 200 OK {"value": {}}
1502115276743	webdriver::server	DEBUG	-> POST /session/27873c02-8864-47a8-aedc-707bfcab4f35/url {"url":"http://localhost:8080/eDHTReporter/index"}
1502115276743	geckodriver::marionette	TRACE	-> 62:[0,3,"get",{"url":"http://localhost:8080/eDHTReporter/index"}]
1502115276747	Marionette	TRACE	0 -> [0,3,"get",{"url":"http://localhost:8080/eDHTReporter/index"}]
1502115276750	Marionette	DEBUG	Received DOM event "beforeunload" for "chrome://browser/content/browser.xul"
1502115276820	Marionette	DEBUG	Received DOM event "pagehide" for "chrome://browser/content/browser.xul"
1502115276820	Marionette	DEBUG	Received DOM event "unload" for "chrome://browser/content/browser.xul"
1502115276907	Marionette	DEBUG	Received DOM event "DOMContentLoaded" for "http://localhost:8080/eDHTReporter/index"
1502115276917	Marionette	DEBUG	Received DOM event "DOMContentLoaded" for "http://localhost:8080/eDHTReporter/index"
1502115276923	Marionette	DEBUG	Received DOM event "pageshow" for "http://localhost:8080/eDHTReporter/index"
1502115276943	Marionette	DEBUG	Received DOM event "pageshow" for "http://localhost:8080/eDHTReporter/index"
1502115276955	Marionette	TRACE	0 <- [1,3,null,{}]
1502115276956	geckodriver::marionette	TRACE	<- [1,3,null,{}]
1502115276956	webdriver::server	DEBUG	<- 200 OK {"value": {}}
1502115276970	webdriver::server	DEBUG	-> GET /session/27873c02-8864-47a8-aedc-707bfcab4f35/title 
1502115276970	geckodriver::marionette	TRACE	-> 19:[0,4,"getTitle",{}]
1502115276972	Marionette	TRACE	0 -> [0,4,"getTitle",{}]
1502115276974	Marionette	TRACE	0 <- [1,4,null,{"value":"eDHTReporter"}]
1502115276974	geckodriver::marionette	TRACE	<- [1,4,null,{"value":"eDHTReporter"}]
1502115276974	webdriver::server	DEBUG	<- 200 OK {"value":"eDHTReporter"}
1502115276979	webdriver::server	DEBUG	-> GET /session/27873c02-8864-47a8-aedc-707bfcab4f35/url 
1502115276979	geckodriver::marionette	TRACE	-> 24:[0,5,"getCurrentUrl",{}]
...
```

**Comment by evgeny1** [comment]
@mseele check your browser version, in the logs, it's 54

**Comment by whimboo** [comment]
Just a heads-up for all of you who are affected by this issue. Firefox 55 will be released today, so once it is out, upgrade to it and the issue will be fixed.

**Comment by realfaisalk** [comment]
Hi,

Can confirm now working with the following setup:

FF v55 (32bit)
GeckoDriver v0.18.0
Selenium v3.4.0
Windows 10 v1703, Build 15063.138

**Comment by rameshnatesan** [comment]
I could not upgrade to Firefox 55 due to some reasons.

is there any other workaround like downgrading GEcko driver to 17, 16 or 15 versions?

any one had luck on this?

**Comment by whimboo** [comment]
@rameshnatesan yes you can always use an older version if you cannot upgrade Firefox to the latest release. Just keep in mind that not all features will be available, and bugs will not be fixed for those old releases.

**Comment by minnujp** [comment]
hello....anybody can help me???? why mousehovering is not working in geckodriver 18,firefox 52 and selenium webdriver 3.5.2???

**Comment by whimboo** [comment]
@minnujp, your problem has absolutely nothing to do with this issue. So please do not hijack some random issues but file your own one. Second you cannot use geckodriver 0.18 with Firefox 52. Upgrade Firefox to latest release.

**Comment by Garimatyagi209** [comment]
did we get solution to above mentioned problem or just need to go with work arround

**Comment by gundsanthu** [comment]
@Garimatyagi209 Below worked for me. Please note that I am using Firefox 54

Instead of driver.manage().window().maximize use the below

driver.manage().window().setSize(new Dimension(1920, 1080));
