### ISSUE TITLE
Error message when New Session failed lacks information

### ISSUE THREAD

**Issue by shs96c** [mozilla/geckodriver#832]
In order to help us efficiently investigate your issue, please provide the following information:

## Platform and application details
* Platform: OSX
* Firefox: 56.0a1 (2017-07-19) (64-bit)
* Selenium: 036b87c80b2f31808c628f21d07dbec965f2df70

## Steps to reproduce
- [X] Reproducable testcase:
```
Capabilities caps = new FirefoxOptions().setBinary("I like cheese").addTo(DesiredCapabilities.firefox());
    WebDriver driver = new RemoteWebDriver(
        new URL("http://localhost:4444/"),
        caps);
```

A `SessionNotCreatedException` is thrown (as expected), but the error message is simply:

```Unable to find a matching set of capabilities```

The only thing wrong with the payload is that the binary does not exist. This is detected by geckodriver, but not reported, which makes debugging hard. 

In general, it would be useful if there was some indication of which parts of the New Session payload caused the match to fail, even if it's just the first failed match or failure of validation.

- [X] A trace level log:
```
1500592410938	geckodriver	INFO	geckodriver 0.18.0 ( '5f44d10bacca'  '2017-07-16 09:18 -0700')
1500592410939	webdriver::httpapi	DEBUG	Creating routes
1500592410946	geckodriver	INFO	Listening on 127.0.0.1:4444
1500592417240	webdriver::server	DEBUG	-> POST /session {
  "desiredCapabilities": {
    "firefox_binary": "I like cheese",
    "acceptInsecureCerts": true,
    "browserName": "firefox",
    "moz:firefoxOptions": {
      "binary": "I like cheese",
      "prefs": {},
      "args": []
    },
    "version": "",
    "platform": "ANY"
  },
  "requiredCapabilities": {},
  "capabilities": {
    "desiredCapabilities": {
      "firefox_binary": "I like cheese",
      "acceptInsecureCerts": true,
      "browserName": "firefox",
      "moz:firefoxOptions": {
        "binary": "I like cheese",
        "prefs": {},
        "args": []
      },
      "version": "",
      "platform": "ANY"
    },
    "requiredCapabilities": {},
    "alwaysMatch": {
      "acceptInsecureCerts": true
    },
    "firstMatch": [
      {
        "browserName": "firefox",
        "moz:firefoxOptions": {
          "binary": "I like cheese",
          "prefs": {},
          "args": []
        }
      }
    ]
  }
}
1500592417399	geckodriver::capabilities	DEBUG	Trying to read firefox version from ini files
1500592417400	geckodriver::capabilities	DEBUG	Trying to read firefox version from binary
1500592417402	geckodriver::capabilities	DEBUG	Failed to get binary version
1500592417406	webdriver::server	DEBUG	<- 500 Internal Server Error {"value":{"error":"session not created","message":"Unable to find a matching set of capabilities","stacktrace":"stack backtrace:\n   0:        0x10f32d81e - backtrace::backtrace::trace<closure>\n                        at /Users/shs/src/mozilla-central/third_party/rust/backtrace/src/backtrace/mod.rs:42\n   1:        0x10f32d9bc - backtrace::capture::Backtrace::new::h23089c033eded8f0\n                        at /Users/shs/src/mozilla-central/third_party/rust/backtrace/src/capture.rs:64\n   2:        0x10f2c42cf - geckodriver::marionette::{{impl}}::create_connection\n                        at /Users/shs/src/mozilla-central/third_party/rust/webdriver/src/error.rs:232\n   3:        0x10f2cc0c5 - geckodriver::marionette::{{impl}}::handle_command\n                        at /Users/shs/src/mozilla-central/testing/geckodriver/src/marionette.rs:520\n   4:        0x10f2c020c - webdriver::server::start::{{closure}}<geckodriver::marionette::MarionetteHandler,geckodriver::marionette::GeckoExtensionRoute>\n                        at /Users/shs/src/mozilla-central/third_party/rust/webdriver/src/server.rs:65\n   5:        0x10f286e9d - std::panicking::try::do_call<std::panic::AssertUnwindSafe<closure>,()>\n                        at /private/tmp/rust-20170612-28767-g1b3at/rustc-1.18.0-src/src/libstd/panicking.rs:454\n   6:        0x10f44a9ba - __rust_maybe_catch_panic\n                        at /private/tmp/rust-20170612-28767-g1b3at/rustc-1.18.0-src/src/libpanic_unwind/lib.rs:98\n   7:        0x10f296f1c - alloc::boxed::{{impl}}::call_box<(),closure>\n                        at /private/tmp/rust-20170612-28767-g1b3at/rustc-1.18.0-src/src/libstd/panicking.rs:433\n   8:        0x10f446b84 - std::sys::imp::thread::{{impl}}::new::thread_start\n                        at /private/tmp/rust-20170612-28767-g1b3at/rustc-1.18.0-src/src/libstd/sys_common/thread.rs:21\n   9:     0x7fffb899f93a - _pthread_body\n  10:     0x7fffb899f886 - _pthread_start"}}
```

As can be seen, this returns when the trace indicates that the binary cannot be found --- invaluable information when debugging.

**Comment by jgraham** [comment]
Yeah, this is a known problem. I've discussed it before with @andreastt and I think we know what to do, but it's not trivial to fix.

The problem is that because there are multiple possible matching capabilities sets, we need to collect the errors that stopped each one matching. That means changing some of the traits for handling capabilities matching to return something like a `Result<(), Vec[String]>` (or some kind of error enum) rather than an `Option<()>` (or whatever the current return type is). Then when we finally fail to match anything, we need to turn the list of error strings into a useful message. So it's not really hard, but there's a little plumbing that makes it not quite trivial to fix.

If anyone wants to have a go at this, I would be happy to mentor.

**Comment by shs96c** [comment]
My reading of the algorithm in the spec is that you can stop the moment there's something that doesn't match --- as a temporary first step, it would be useful to just return that first error.

**Comment by whimboo** [comment]
Btw I filed [bug 1410838](https://bugzilla.mozilla.org/show_bug.cgi?id=1410838) a couple days ago. Nearly missed this existent issue.

**Comment by nischt** [comment]
Issue 
selenium.common.exceptions.SessionNotCreatedException: Message: Unable to find a matching set of capabilities when running "driver= webdriver.Firefox"

selenium-3.141.0
Firefox - 63.0.1
geckodriver-v0.23.0-win32

Firefox is properly installed and manually I am able to open firefox from path "C:\Program Files\Mozilla Firefox\firefox.exe"

I even tried to use desired capabilities as below:

firefox_capabilities = DesiredCapabilities.FIREFOX
firefox_capabilities['binary'] = 'C:\Program Files\Mozilla Firefox\firefox.exe'

driver= webdriver.Firefox(capabilities=firefox_capabilities)

Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\New folder\test.py", line 9, in <module>
    driver= webdriver.Firefox(capabilities=firefox_capabilities)
  File "C:\Users\Administrator\Desktop\New folder\selenium\webdriver\firefox\webdriver.py", line 174, in __init__
    keep_alive=True)
  File "C:\Users\Administrator\Desktop\New folder\selenium\webdriver\remote\webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "C:\Users\Administrator\Desktop\New folder\selenium\webdriver\remote\webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "C:\Users\Administrator\Desktop\New folder\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Administrator\Desktop\New folder\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: Unable to find a matching set of capabilities

**Comment by whimboo** [comment]
@nischt please note that backslashes are escape characters. You will have to use two of them to actually let it interpret a backslash. So the line has to look like:

> firefox_capabilities['binary'] = 'C:\\Program Files\\Mozilla Firefox\\firefox.exe'

Also which exact version of Windows do you have, and are you trying to run the 32bit or 64bit Firefox?

**Comment by nischt** [comment]
@whimboo

I had tried "firefox_capabilities['binary'] = 'C:\\Program Files\\Mozilla Firefox\\firefox.exe'" also nothing worked.
OS version is Win 10 64 bit version 1803(OS build 17134.137). 
Also I think the issue is same for all OS versions using firefox version 63.0.1.I remember seeing this issue with Win 2012 as well.

**Comment by whimboo** [comment]
Can you please attach a new trace log with the update code? See https://firefox-source-docs.mozilla.org/testing/geckodriver/geckodriver/TraceLogs.html. Thanks.

**Comment by nischt** [comment]
I used the below code to generate  trace logs as per link  https://firefox-source-docs.mozilla.org/testing/geckodriver/geckodriver/TraceLogs.html.

from selenium import webdriver
from selenium.webdriver import Firefox
from selenium.webdriver.firefox.options import Options

opts = Options()
opts.log.level = "trace"
driver = Firefox(firefox_options=opts)

"geckodriver.log" file is generated in the current working directory but its empty.

**Comment by whimboo** [comment]
I would suggest that you file your own issue regarding that problem. It doesn't seem to be related to this one, and is offtopic here.

**Comment by nischt** [comment]
> I would suggest that you file your own issue regarding that problem. It doesn't seem to be related to this one, and is offtopic here.

Sure I will that.Since tracelogs are not generated what is the alternat


> Can you please attach a new trace log with the update code? See https://firefox-source-docs.mozilla.org/testing/geckodriver/geckodriver/TraceLogs.html. Thanks.

Due to issues in generating trace logs ,is there any other alternative. 

The issue "selenium.common.exceptions.SessionNotCreatedException: Message: Unable to find a matching set of capabilities " is easily reproducible with just these 2 lines of python code:

from selenium import webdriver
driver= webdriver.Firefox()

Are you aware of anyone facing similar kind of issue with latest firefox browsers(63.0.1)?

**Comment by andreastt** [comment]
> The issue "selenium.common.exceptions.SessionNotCreatedException:
> Message: Unable to find a matching set of capabilities " is easily
> reproducible with just these 2 lines of python code:

> from selenium import webdriver
> driver= webdriver.Firefox()
> 
> Are you aware of anyone facing similar kind of issue with latest
> firefox browsers(63.0.1)?

This is the first we hear of this.  Are you sure you’re using all
the latest versions, especially of the Selenium Python client?

There is a table of supported platforms and versions in
https://firefox-source-docs.mozilla.org/testing/geckodriver/geckodriver/Support.html.
