### ISSUE TITLE
Firefox 54.0.1 not able to connect with gecko driver (v 0.17.0) in jenkins

### ISSUE THREAD

**Issue by cbaquero-ar** [mozilla/geckodriver#837]
Hello, 
I'm having issues using geckodriver v0.17.0 with Firefox 54.0.1 on a Jenkins build. This actually doesn't happen running the tests locally from Visual Studio, which confuses me a lot.

## Platform and application details

* Platform: Windows Server 2008 R2 Standard
* Firefox: 54.0.1 32 bit/64bit (tried different versions and architectures)
* geckodriver: 0.17.0 (18 doesn't work for FF 54.0.1 on my local or the CI server - tested with lower versions as well)
* Selenium: WebDriver 3.4.0 for .Net (C#)

## Steps to reproduce
I configured a job on Jenkins to run a set of tests that I can actually run on my local with this geckodriver-Firefox configuration just fine. I put the job to run and get the following error:

"Class Initialization method MyApp.FunctionalTests.Tests.MVC.Automation.CreateProgrammedTaskTest.SetupTest threw exception. OpenQA.Selenium.WebDriverException: OpenQA.Selenium.WebDriverException: The HTTP request to the remote WebDriver server for URL http://localhost:33318/session timed out after 60 seconds. ---> System.Net.WebException: The operation has timed out.

When logging to the remote machine as a normal user and run the geckodriver manually, it connects and runs normally, but this is not how I want it to run... it should be unnatended.

- [ ] Reproducable testcase:
The failure is independant fromt he test I run, I tried a minimal example on goolge and the same thing happens.

- [ ] A trace level log: I can't find thegeckodriver trace, could you please indicate where to find it or how to set for C#?

Trace
    at System.Net.HttpWebRequest.GetResponse()
   at OpenQA.Selenium.Remote.HttpCommandExecutor.CreateResponse(WebRequest request)
 --- End of inner exception stack trace ---
    at OpenQA.Selenium.Remote.HttpCommandExecutor.CreateResponse(WebRequest request)
   at OpenQA.Selenium.Remote.HttpCommandExecutor.Execute(Command commandToExecute)
   at OpenQA.Selenium.Remote.DriverServiceCommandExecutor.Execute(Command commandToExecute)
   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Remote.RemoteWebDriver.StartSession(ICapabilities desiredCapabilities)
   at OpenQA.Selenium.Remote.RemoteWebDriver..ctor(ICommandExecutor commandExecutor, ICapabilities desiredCapabilities)
   at OpenQA.Selenium.Firefox.FirefoxDriver..ctor(FirefoxOptions options)
   at MyApp.FunctionalTests.Util.DriverFactory.GetBrowserDriver(Int32 browser) in c:\Program Files (x86)\Jenkins\jobs\Fixes_DPLR_Functional\workspace\MyApp.FunctionalTests\Util\DriverFactory.cs:line 37
   at MyApp.FunctionalTests.Util.DriverFactory.GetBrowserDriver() in c:\Program Files (x86)\Jenkins\jobs\Fixes_DPLR_Functional\workspace\MyApp.FunctionalTests\Util\DriverFactory.cs:line 16
   at MyApp.FunctionalTests.Pages.Page..ctor(String url) in c:\Program Files (x86)\Jenkins\jobs\Fixes_DPLR_Functional\workspace\MyApp.FunctionalTests\Pages\Page.cs:line 28
   at MyApp.FunctionalTests.Tests.MVC.Automation.CreateProgrammedTaskTest.SetupTest(TestContext context) in c:\Program Files (x86)\Jenkins\jobs\Fixes_DPLR_Functional\workspace\MyApp.FunctionalTests\Tests\MVC\Automation\CreateProgrammedTaskTest.cs:line 24"

Could you please help? I don't know what else to do and we need to run this tests with the latest Selenium version on CI.

Thanks in advance,
Carolina

**Comment by andreastt** [comment]
Can you provide a geckodriver trace-level log, as you were requested to in the issue template?

**Comment by andreastt** [comment]
You also need to test with Firefox Nightly, as we don’t develop against Firefox 54 any more.

**Comment by cbaquero-ar** [comment]
Hi Andreas,

I don't really find a way to see the geckodriver log, neither how to setup
the trace level. Could youplease guide me on where to find geckodriver's
logs?

My code runs the geckodriver automatically, I don't have any service or the
process running previously on the CI server. Should I do something like
that?

I tried with Nightly now, and I'm getting the same result. :(

Thanks,



Carolina .-

**Comment by andreastt** [comment]
See the README for how to enable trace-level logging. The log is normally sent to stdout.

**Comment by cbaquero-ar** [comment]
I added log level and instantiated FirefoxDriver as follows:

FirefoxOptions options = new FirefoxOptions();
options.SetLoggingPreference(LogType.Driver,LogLevel.All);
options.LogLevel = FirefoxDriverLogLevel.Trace;

FirefoxProfile profile = new FirefoxProfile();
string folder = AppDomain.CurrentDomain.BaseDirectory;
profile.SetPreference("browser.download.folderList", 2);
profile.SetPreference("browser.download.dir", folder);
profile.SetPreference("browser.helperApps.neverAsk.saveToDisk",
"application/msword, application/csv, application/ris, text/csv, image/png,
application/pdf, text/html, text/plain, application/zip, application/x-zip,
application/x-zip-compressed,
application/download, application/octet-stream");
profile.SetPreference("browser.download.manager.alertOnEXEOpen", false);
profile.SetPreference("browser.download.manager.focusWhenStarting", false);
profile.SetPreference("browser.download.manager.useWindow", false);
profile.SetPreference("browser.download.manager.showAlertOnComplete",
false);
profile.SetPreference("browser.download.manager.closeWhenDone", false);
profile.SetPreference("services.sync.prefs.sync.browser.download.manager.showWhenStarting",
false);
profile.SetPreference("pdfjs.disabled", true);

options.Profile = profile;
FirefoxDriverService service =
FirefoxDriverService.CreateDefaultService(GetDriverPath());
service.Port = 4444;
TimeSpan t = TimeSpan.FromSeconds(ConfigUtil.GetInt("timeout_seconds") * 2);
return new FirefoxDriver(service, options, t);

But, anyways, the only output I see on jenkins is this:

https://www.screencast.com/t/AWlJ76on0c

I really don't know how to access geckodriver on jenkins if it's not there.
That's the only output I get. I tried starting the geckodrver as a Jenkins
step and redirecting that to a text file, but didn't work either.

If I run the driver manually on the remote machine (then I CAN see the
logs) and launch the tests, then  it works, so I cannot see the error
happening when running via Jenkins job :( I'm frustrated,

The geckodriver.exe is on the Nightly folder on my CI server, and the
 folder is on Path's environment variable.


Carolina .-

**Comment by andreastt** [comment]
As I said, the driver’s output goes to stdout so you will have to capture that. In the screenshot you linked to, Jenkins only reproduces the stacktrace.

**Comment by whimboo** [comment]
@cbaquero-ar I would suggest that you talk to the maintainers who work on the c# binding and specifically for remote webdriver. They should be able to give you a hint in how to start geckodriver with a path argument, so that the output will end-up in a log file for inspection. I could assume that your problem here is that geckodriver runs in another process and as such the output cannot be caught by Jenkins.

Further can you see on those machines, that Firefox is getting started? Does it run as normal user or in headless mode? The latter might fail, and as such Marionette isn't started and geckodriver cannot connect.

**Comment by andreastt** [comment]
Closing due to inactivity. Happy to reopen if you think this is still an issue, but I request that you include trace-level logs.
