### ISSUE TITLE
Firefox is launching, but not loading the URL instead it showing the message "Accessibility Support is partially disabled due to Compatibility issues in new Firefox features"

### ISSUE THREAD

**Issue by RoupRanjan0308** [mozilla/geckodriver#848]
In order to help us efficiently investigate your issue, please provide the following information:

## Platform and application details
* Platform: Windows 7,64-bit
* Firefox: 52.0.1,32-bit
* Selenium: tried with all version of selenium starting from 2.48.2 to 3.4.0

## Steps to reproduce

		public class Sample{
	          public static void main(String[] args) {		
		  System.setProperty("webdriver.gecko.driver", "./drivers/geckodriver.exe");			
		  WebDriver driver = new FirefoxDriver();	
		  driver.manage().deleteAllCookies();
		 driver.manage().window().maximize();
		 driver.manage().timeouts().implicitlyWait(30, TimeUnit.SECONDS);
 		 driver.manage().timeouts().pageLoadTimeout(30, TimeUnit.SECONDS);		
		driver.get(URL);}}

- [ ] A trace level log:
1501225320127	geckodriver	INFO	geckodriver 0.18.0
1501225320144	geckodriver	INFO	Listening on 127.0.0.1:31142
Jul 28, 2017 12:32:00 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Attempting bi-dialect session, assuming Postel's Law holds true on the remote end
1501225321253	geckodriver::marionette	INFO	Starting browser C:\Program Files (x86)\Mozilla Firefox\firefox.exe with args ["-marionette"]
[ODEBUG] [Explorer Probe] [disableSPDY]#In disableSPDY()[ODEBUG] [Explorer Probe] [disableSPDY]#Trying to get profile path from command line if exists1501225325922	Marionette	INFO	Listening on port 65193
[ODEBUG] [Explorer Probe] [disableSPDY]#In disableSPDY()[ODEBUG] [Explorer Probe] [disableSPDY]#Trying to get profile path from command line if exists[ODEBUG] [Explorer Probe] [disableSPDY]#Didn't get any profile from command line, get all FireFox profiles from AppDataJul 28, 2017 12:32:18 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Falling back to original OSS JSON Wire Protocol.
Jul 28, 2017 12:32:18 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Falling back to straight W3C remote end connection
Exception in thread "main" org.openqa.selenium.SessionNotCreatedException: Unable to create new remote session. desired capabilities = Capabilities [{marionette=true, firefoxOptions=org.openqa.selenium.firefox.FirefoxOptions@9660f4e, browserName=firefox, moz:firefoxOptions=org.openqa.selenium.firefox.FirefoxOptions@9660f4e, version=, platform=ANY}], required capabilities = Capabilities [{}]
Build info: version: '3.0.1', revision: '1969d75', time: '2016-10-18 09:48:19 -0700'
System info: host: 'PW7AM1XDH004670', ip: '10.189.46.163', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_131'
Driver info: driver.version: FirefoxDriver
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:91)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:141)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:82)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:601)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:241)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:128)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:259)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:247)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:242)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:238)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:127)
	at aig.workday.pages.Sample.main(Sample.java:25)

**Comment by andreastt** [comment]
Firefox 52 is not supported and you haven’t included a trace-level log from geckodriver.

**Comment by pawarsam** [comment]
I am also facing same issue in mozilla 54.0.1

**Comment by whimboo** [comment]
In some cases the accessibility support is not yet enabled if e10s is turned on in Firefox. If you are facing this situation you will whether have to disable accessibility, or e10s.

Also try the upcoming Firefox 55.0 or even a recent Firefox Nightly build, which might (should) have this combination already enabled.
