### ISSUE TITLE
Switching domains in a JavaScript call results in acceptInsecureCerts being overridden (Mocha/Selenium)

### ISSUE THREAD

**Issue by christopherliu** [mozilla/geckodriver#877]
Not sure if this is best placed in webdriver-selenium or here so feel free to relocate.

## System
* Version: 0.18.0
* Platform: Windows 7
* Firefox: 54.0.1
* Selenium: selenium-webdriver (node) 3.5.0

## Testcase
```
describe('Minimum browser test', function() {
    it('Firefox should load a page without SSL properly', function() {
        var driver = new webdriver.Builder().withCapabilities(Capabilities.firefox().set("acceptInsecureCerts", true)).build();

        driver.get('https://badssl.com/');
        driver.findElement(by.xpath('//a[@href="https://self-signed.badssl.com/"]')).click();
        driver.wait(until.elementLocated(by.id('content')), 5000, "Insecure SSL cert site (from click) should load.");
        
        driver.get('http://untrusted-root.badssl.com/');
        driver.wait(until.elementLocated(by.id('content')), 5000, "Insecure SSL cert site (from redirect) should load.");
        
        driver.get('https://expired.badssl.com/');
        driver.wait(until.elementLocated(by.id('content')), 5000, "Insecure SSL cert site should load.");
        
        driver.get('https://google.com/');
        driver.executeScript('window.location.href="http://revoked.badssl.com/";');
        driver.wait(until.elementLocated(by.id('content')), 5000, "Insecure SSL cert site (domain switching from script) should load.");
        
        driver.quit();
    });
});
```

## Stacktrace
```

  1) Minimum browser test Firefox should load a page without SSL properly:
     WebDriverError: Failed to decode response from marionette
      at WebDriverError (node_modules\selenium-webdriver\lib\error.js:27:5)
      at Object.throwDecodedError (node_modules\selenium-webdriver\lib\error.js:
497:15)
      at parseHttpResponse (node_modules\selenium-webdriver\lib\http.js:519:13)
      at doSend.then.response (node_modules\selenium-webdriver\lib\http.js:441:3
0)
      at process._tickCallback (internal/process/next_tick.js:109:7)
  From: Task: WebDriver.findElements(By(css selector, *[id="content"]))
      at thenableWebDriverProxy.schedule (node_modules\selenium-webdriver\lib\we
bdriver.js:807:17)
      at thenableWebDriverProxy.findElements (node_modules\selenium-webdriver\li
b\webdriver.js:1048:22)
      at node_modules\selenium-webdriver\lib\until.js:243:23
      at node_modules\selenium-webdriver\lib\webdriver.js:938:14
      at TaskQueue.execute_ (node_modules\selenium-webdriver\lib\promise.js:3092
:14)
      at TaskQueue.executeNext_ (node_modules\selenium-webdriver\lib\promise.js:
3075:27)
      at asyncRun (node_modules\selenium-webdriver\lib\promise.js:2982:25)
      at node_modules\selenium-webdriver\lib\promise.js:676:7
  From: Task: <anonymous>
      at Timeout.pollCondition [as _onTimeout] (node_modules\selenium-webdriver\
lib\promise.js:2203:19)
  From: Task: Insecure SSL cert site (domain switching from script) should load.

      at scheduleWait (node_modules\selenium-webdriver\lib\promise.js:2196:20)
      at ControlFlow.wait (node_modules\selenium-webdriver\lib\promise.js:2525:1
2)
      at thenableWebDriverProxy.wait (node_modules\selenium-webdriver\lib\webdri
ver.js:934:29)
      at Context.<anonymous> (test\MinimumBrowser.js:70:16)
      at runTest (node_modules\selenium-webdriver\testing\index.js:164:22)
      at node_modules\selenium-webdriver\testing\index.js:185:16
      at new ManagedPromise (node_modules\selenium-webdriver\lib\promise.js:1085
:7)
      at controlFlowExecute (node_modules\selenium-webdriver\testing\index.js:18
4:14)
      at TaskQueue.execute_ (node_modules\selenium-webdriver\lib\promise.js:3092
:14)
      at TaskQueue.executeNext_ (node_modules\selenium-webdriver\lib\promise.js:
3075:27)
      at asyncRun (node_modules\selenium-webdriver\lib\promise.js:2982:25)
      at node_modules\selenium-webdriver\lib\promise.js:676:7
  From: Task: Minimum browser test Firefox should load a page without SSL proper
ly
      at Context.ret (node_modules\selenium-webdriver\testing\index.js:183:10)

```

**Comment by andreastt** [comment]
That is somewhat surprising, seeing we install the [cert override service](https://searchfox.org/mozilla-central/source/testing/marionette/cert.js) when the session is started in https://searchfox.org/mozilla-central/rev/5ce320a16f6998dc2b36e30458131d029d107077/testing/marionette/driver.js#782-786.

I don’t have any immediate ideas what could be wrong here. Maybe it has something to do with sandboxes.

**Comment by whimboo** [comment]
The problem here is that `http://revoked.badssl.com/` is causing an `about:neterror` failure but not a `about:certerror`. Which means that this has nothing to do with running this through `executeScript`, and not with `acceptInsecureCerts=True`.

```
1503418609613	Marionette	DEBUG	Received DOM event "DOMContentLoaded" for "about:neterror?e=nssFailure2&u=https%3A//revoked.badssl.com/&c=UTF-8&f=regular&d=An%20error%20occurred%20during%20a%20connection%20to%20revoked.badssl.com.%0A%0APeer%E2%80%99s%20Certificate%20has%20been%20revoked.%0A%0AError%20code%3A%20%3Ca%20id%3D%22errorCode%22%20title%3D%22SEC_ERROR_REVOKED_CERTIFICATE%22%3ESEC_ERROR_REVOKED_CERTIFICATE%3C/a%3E%0A"
```

The reason might be that we don't want to allow users to override the error as explained for another example on [bug 1218732](https://bugzilla.mozilla.org/show_bug.cgi?id=1218732).

So this is not a geckodriver issue.

**Comment by whimboo** [comment]
If you think it's something which would need a fix in Firefox please file a bug on Bugzilla, similar to the one above and let us know here. Thanks.
