### ISSUE TITLE
[Selenium 3.4.0][Geckodriver v 0.18.0][Firefox] 55[Mac]Not able to open url in firefox browser v55

### ISSUE THREAD

**Issue by anupamdas24** [mozilla/geckodriver#891]
## CONFIGURATION
* geckodriver version  : 0.18.0
* Platform: os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.12.6', java.version: '1.8.0_112'
* Firefox: 55
* Selenium: 3.4.0

## Console Log Output

Running TestSuite

```
1503408547593	geckodriver	INFO	geckodriver 0.18.0
1503408547598	geckodriver	INFO	Listening on 127.0.0.1:21585
1503408547998	geckodriver::marionette	INFO	Starting browser /Applications/Firefox.app/Contents/MacOS/firefox-bin with args ["-marionette"]
1503408548910	Marionette	INFO	Enabled via --marionette
1503408550576	Marionette	INFO	Listening on port 57584
JavaScript error: chrome://marionette/content/server.js, line 337: NS_ERROR_SOCKET_ADDRESS_IN_USE: Component returned failure code: 0x804b0036 (NS_ERROR_SOCKET_ADDRESS_IN_USE) [nsIServerSocket.initSpecialConnection]
JavaScript error: , line 0: TypeError: NetworkError when attempting to fetch resource.
1503408553426	addons.productaddons	WARN	Failed downloading XML, status: 0, reason: error
1503408554310	addons.productaddons	WARN	Failed downloading via XHR, status: 0, reason: error
WARNING: At least one completion condition is taking too long to complete. Conditions: [{"name":"SessionStore: flushing all windows","state":{"total":1,"current":0},"filename":"resource:///modules/sessionstore/SessionStore.jsm","lineNumber":1585,"stack":["resource:///modules/sessionstore/SessionStore.jsm:ssi_onQuitApplicationGranted:1585","resource:///modules/sessionstore/SessionStore.jsm:ssi_observe:768"]}] Barrier: quit-application-granted
Tests run: 5, Failures: 1, Errors: 0, Skipped: 4, Time elapsed: 80.478 sec <<< FAILURE! - in TestSuite
launhOS(com.ge.DAP.UItestscipts.ConfigAssetModelTest)  Time elapsed: 79.448 sec  <<< FAILURE!
org.openqa.selenium.WebDriverException: Failed to decode response from marionette
Build info: version: '3.4.0', revision: 'unknown', time: 'unknown'
System info: host: '1734021-C02SNGB4G8WN', ip: '10.177.53.254', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.12.6', java.version: '1.8.0_112'
Driver info: driver.version: FirefoxDriver
remote stacktrace: stack backtrace:
   0:        0x1019bd54e - backtrace::backtrace::trace::hc694823f3e7463c0
   1:        0x1019bd6ec - backtrace::capture::Backtrace::new::h23089c033eded8f0
   2:        0x10197150e - geckodriver::marionette::MarionetteConnection::send_command::hb3631625b1e960bc
   3:        0x101930d88 - _$LT$webdriver..server..Dispatcher$LT$T$C$$u20$U$GT$$GT$::run::h03bbbfe904a992bd
   4:        0x101916c97 - std::panicking::try::do_call::he6fd7abc59b6b346
   5:        0x101ada4ba - __rust_maybe_catch_panic
   6:        0x10192700c - _$LT$F$u20$as$u20$alloc..boxed..FnBox$LT$A$GT$$GT$::call_box::h8e002f7c448fbabb
   7:        0x101ad6684 - std::sys::imp::thread::Thread::new::thread_start::hba7593f2e1f1beb1
   8:     0x7fffa8cc593a - _pthread_body
   9:     0x7fffa8cc5886 - _pthread_start
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.W3CHandshakeResponse.lambda$new$0(W3CHandshakeResponse.java:57)
	at org.openqa.selenium.remote.W3CHandshakeResponse.lambda$getResponseFunction$2(W3CHandshakeResponse.java:104)
	at org.openqa.selenium.remote.ProtocolHandshake.lambda$createSession$22(ProtocolHandshake.java:365)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:958)
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:464)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:368)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:159)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:142)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:82)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:637)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:250)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:236)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:137)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:191)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:108)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:104)
	at com.ge.DAP.actionEngines.DAPBaseTest.launhOS(DAPBaseTest.java:86)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:564)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:213)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:138)
	at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:175)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:107)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:295)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:90)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray2(ReflectionUtils.java:208)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:155)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:81)
	at org.apache.maven.plugin.surefire.InPluginVMSurefireStarter.runSuitesInProcess(InPluginVMSurefireStarter.java:82)
	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeProvider(AbstractSurefireMojo.java:974)
	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked(AbstractSurefireMojo.java:824)
	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute(AbstractSurefireMojo.java:722)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)


Results :

Failed tests: 
  ConfigAssetModelTest>DAPBaseTest.launhOS:86 » WebDriver Failed to decode respo...

Tests run: 4, Failures: 1, Errors: 0, Skipped: 3

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:23 min
[INFO] Finished at: 2017-08-22T19:00:26+05:30
[INFO] Final Memory: 40M/591M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.18.1:test (default-test) on project QAUiAutomation: There are test failures.
[ERROR] 
[ERROR] Please refer to /Users/anupamdas/Documents/GIT_CODE/DAPAUTOMATION/dap-qa-ui-automation/target/surefire-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
****
```

## Details:

While launching the Firefox browser using TestNG framework from a Maven Selenium Project.

**Comment by andreastt** [comment]
`NS_ERROR_SOCKET_ADDRESS_IN_USE` indicates you already have some other process on your system that is bound to the port geckodriver is trying to use. geckodriver by default uses port 4444, but you should check that this is available or let the system atomically allocate a port through 0.

**Comment by anupamdas24** [comment]
Simply closing the issue, without having the proper solution won't help at all. @andreastt 

Even after making the different port selection, the same error is present.

![image](https://user-images.githubusercontent.com/10444769/29583782-303e6c7e-879f-11e7-8599-eee5de69d566.png)

**Comment by andreastt** [comment]
Ensure you’re using the latest version of Firefox (57 or greater) and verify that your client is not attempting to start two geckodrivers at the same time.

**Comment by anupamdas24** [comment]
In the APPSTORE, the latest version of Firefox available for MAC os X is version 55.*.*

![image](https://user-images.githubusercontent.com/10444769/29584735-4caa024e-87a2-11e7-83b9-8ee9d1272110.png)

Is there any way to download and set Firefox version 57 in mac ??

Also when I use the geckodriver 16.*.* and more, it always launches 2 Firefox instances.

**Comment by andreastt** [comment]
See https://www.mozilla.org/en-US/firefox/channel/desktop/#nightly. If two Firefox instances are always launched, that would explain why one instance is failing to bind to the port.

**Comment by anupamdas24** [comment]
@andreastt : Firefox Nightly is not stable version it seems. It it having so many crashes and sending them to Firefox.

Also it is not able to launch any URL manually . It shows white screen.

**Comment by andreastt** [comment]
Please file crash reports to Bugzilla and submit the crash report.

**Comment by anupamdas24** [comment]
@andreastt  I dont think we are trying to solve this issue..Just moving round and round..Anyways..ignore..you can not resolve this..

**Comment by whimboo** [comment]
Please open an instance of Firefox which works for you, go to `about:crashes` and make sure that the recent ones, which you have seen when running geckodriver, have been submitted. It would be good if you give at least one URL.

Otherwise please enable trace logs and attach one example here. Otherwise we indeed will only cycle in rounds...
