### ISSUE TITLE
Attribute wildcard (substring matching) selector not  supported

### ISSUE THREAD

**Issue by Spijkerj** [mozilla/geckodriver#896]
## System
* Version: v0.18.0 
* Platform: Windows Vista
* Selenium: 3.5.1
*Firefox: 55.0

## Testcase
I use attribute wildcard selector to select dynamic ID's on my page with a fixed postfix. In my case the id Always ends with: Amount.
So my selector looks like this: By.CssSelector("[id*=Amount]");

This works fine with Chrome and IE, but isn't working with Firefox and the GeckoDriver.
It's keep saying unable to locate element.

HTML 
`<span id="g_1823d804_181e_4505_b4d7_aa90d4feda0f__Amount">€ `71,51</span>`

## Stacktrace
Unable to locate element: [id*=Amount]
OpenQA.Selenium.NoSuchElementException: Unable to locate element: [id*=Amount]
   at OpenQA.Selenium.Remote.RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse)
   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Remote.RemoteWebElement.FindElement(String mechanism, String value)
   at OpenQA.Selenium.Remote.RemoteWebElement.FindElementByCssSelector(String cssSelector)
   at OpenQA.Selenium.By.<>c__DisplayClass1e.<CssSelector>b__1c(ISearchContext context)
   at OpenQA.Selenium.By.FindElement(ISearchContext context)
   at OpenQA.Selenium.Remote.RemoteWebElement.FindElement(By by)

**Comment by whimboo** [comment]
Please supply a trace log as requested when filing the issue. Thanks.

**Comment by Spijkerj** [comment]
1503668337248   webdriver::server       DEBUG   -> DELETE /session/a0f89dc6-5644-424a-a01e-6118f6baae27
1503668337248   geckodriver::marionette TRACE   -> 39:[0,122,"quit",{"flags":["eForceQuit"]}]
1503668337412   geckodriver::marionette TRACE   <- [1,122,null,{"cause":"shutdown"}]
1503668337419   webdriver::server       DEBUG   Deleting session

Is this enough tracing.?

**Comment by whimboo** [comment]
It should be but we need the output of the full run. Best save it to a file and attach this here.

**Comment by Spijkerj** [comment]
Leave a comment
