### ISSUE TITLE
OSError: [Errno 8] Exec format error

### ISSUE THREAD

**Issue by chrisclarkson** [mozilla/geckodriver#917]
## System
* Version: 
* Platform: 

I am inexperienced and must apologise in advance. I am using a MacBook and I downloaded geckodriver "geckodriver-v0.13.0-arm7hf". I have the binary geckodriver in my Downloads folder now and I  copied it to usr/local/bin and then "chmod +x usr/local/bin/geckodriver" and yet when I try to use it in python:

>>> from selenium import webdriver
>>> browser = webdriver.Firefox()

But I get this error:
_Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/Deirdreclarkson/anaconda/lib/python2.7/site-packages/selenium/webdriver/firefox/webdriver.py", line 144, in __init__
    self.service.start()
  File "/Users/Deirdreclarkson/anaconda/lib/python2.7/site-packages/selenium/webdriver/common/service.py", line 74, in start
    stdout=self.log_file, stderr=self.log_file)
  File "/Users/Deirdreclarkson/anaconda/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/Users/Deirdreclarkson/anaconda/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 8] Exec format error_

I have tried a host of things from S/O but to no avail. Can you help me? setting gecko driver is not immediately obvious.....

**Comment by andreastt** [comment]
First of all, 0.13.0 is a very old version.  ARMv7 HF is not the macOS platform, so you will want to download the macOS specific package.

**Comment by senorfoggy** [comment]
Thank you @andreastt your answer helped solved the problem. I didn't download the right version for MAC. Everything is working for me now.
