### ISSUE TITLE
When alert is open, elements on the page should not be found

### ISSUE THREAD

**Issue by rshanley-micro-focus** [mozilla/geckodriver#920]
## System
* Version: 0.18.0
* Platform: Windows 10
* Firefox: 55.0.2
* Selenium: Java binding, 3.5.2

### pagewithalert.html

```
<html>
    <head></head>
    <body>
        <p id="para1">hello, welcome to page to test alert</p>
        
        <button id="jsDialogsAlert" onclick="showMyAlert()">Show Alert</button>
        
        <script>
        function showMyAlert() {
            alert("This is an alert box!");
        }
        </script>
    </body>
</html>
```

### TestAlertAndFind.java
```
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.junit.Before;
import org.openqa.selenium.firefox.FirefoxDriver;

import java.util.List;
import java.util.concurrent.TimeUnit;
import org.junit.Test;
import org.openqa.selenium.Alert;
import org.openqa.selenium.By;
import org.junit.After;

public class TestAlertAndFind {

	private WebDriver driver;

	@Before
	public void setup() {
		//TODO: Replace property with path to your geckodriver.exe
		System.setProperty("webdriver.gecko.driver", "....");
		driver = new FirefoxDriver();
		driver.manage().timeouts().implicitlyWait(5, TimeUnit.SECONDS);
	}

	@Test
	public void findElementsWhenAlertOpen() {
		//given
		driver.get("http://localhost:8000/pagewithalert.html");
		WebElement dialogLink = driver.findElement(By.id("jsDialogsAlert"));
		dialogLink.click();
		driver.switchTo().alert();

		//when
		List<WebElement> paragraphElements = driver.findElements(By.tagName("p"));

		//then
        org.junit.Assert.assertEquals("should be no paragraph elements found when alert open", 0, paragraphElements.size());
	}
}
```

## Stacktrace

```
java.lang.AssertionError: expected:<0> but was:<1>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at TestAlertAndFind.findElementsWhenAlertOpen(TestAlertAndFind.java:37)
```

## Trace-level log

```
Sep 01, 2017 6:09:15 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: W3C
1504282155636	webdriver::server	DEBUG	-> POST /session/d992be5c-30cb-4caa-99b8-a3388babfb26/timeouts {"implicit":5000}
1504282155637	geckodriver::marionette	TRACE	-> 37:[0,2,"setTimeouts",{"implicit":5000}]
1504282155641	Marionette	TRACE	0 -> [0,2,"setTimeouts",{"implicit":5000}]
1504282155642	Marionette	TRACE	0 <- [1,2,null,{}]
1504282155642	geckodriver::marionette	TRACE	<- [1,2,null,{}]
1504282155642	webdriver::server	DEBUG	<- 200 OK {"value": {}}
1504282155646	webdriver::server	DEBUG	-> POST /session/d992be5c-30cb-4caa-99b8-a3388babfb26/url {"url":"http://localhost:8000/pagewithalert.html"}
1504282155646	geckodriver::marionette	TRACE	-> 62:[0,3,"get",{"url":"http://localhost:8000/pagewithalert.html"}]
1504282155648	Marionette	TRACE	0 -> [0,3,"get",{"url":"http://localhost:8000/pagewithalert.html"}]
1504282155650	Marionette	DEBUG	Received DOM event "beforeunload" for "about:blank"
1504282155914	Marionette	DEBUG	Received DOM event "pagehide" for "about:blank"
1504282155914	Marionette	DEBUG	Received DOM event "unload" for "about:blank"
1504282155920	Marionette	DEBUG	Received DOM event "DOMContentLoaded" for "http://localhost:8000/pagewithalert.html"
1504282155933	Marionette	DEBUG	Received DOM event "pageshow" for "http://localhost:8000/pagewithalert.html"
1504282155938	Marionette	TRACE	0 <- [1,3,null,{}]
1504282155948	geckodriver::marionette	TRACE	<- [1,3,null,{}]
1504282155948	webdriver::server	DEBUG	<- 200 OK {"value": {}}
1504282155957	webdriver::server	DEBUG	-> POST /session/d992be5c-30cb-4caa-99b8-a3388babfb26/element {"value":"#jsDialogsAlert","using":"css selector"}
1504282155958	geckodriver::marionette	TRACE	-> 70:[0,4,"findElement",{"using":"css selector","value":"#jsDialogsAlert"}]
1504282155961	Marionette	TRACE	0 -> [0,4,"findElement",{"using":"css selector","value":"#jsDialogsAlert"}]
1504282155966	Marionette	TRACE	0 <- [1,4,null,{"value":{"element-6066-11e4-a52e-4f735466cecf":"fb3b390c-838a-4575-a731-1df5c0d126fd","ELEMENT":"fb3b390c-838a-4575-a731-1df5c0d126fd"}}]
1504282155968	geckodriver::marionette	TRACE	<- [1,4,null,{"value":{"element-6066-11e4-a52e-4f735466cecf":"fb3b390c-838a-4575-a731-1df5c0d126fd","ELEMENT":"fb3b390c-838a-4575-a731-1df5c0d126fd"}}]
1504282155968	webdriver::server	DEBUG	<- 200 OK {"value":{"element-6066-11e4-a52e-4f735466cecf":"fb3b390c-838a-4575-a731-1df5c0d126fd"}}
1504282155975	webdriver::server	DEBUG	-> POST /session/d992be5c-30cb-4caa-99b8-a3388babfb26/element/fb3b390c-838a-4575-a731-1df5c0d126fd/click {"id":"fb3b390c-838a-4575-a731-1df5c0d126fd"}
1504282155976	geckodriver::marionette	TRACE	-> 66:[0,5,"clickElement",{"id":"fb3b390c-838a-4575-a731-1df5c0d126fd"}]
1504282155977	Marionette	TRACE	0 -> [0,5,"clickElement",{"id":"fb3b390c-838a-4575-a731-1df5c0d126fd"}]
1504282156028	Marionette	TRACE	0 <- [1,5,null,{}]
1504282156033	geckodriver::marionette	TRACE	<- [1,5,null,{}]
1504282156033	webdriver::server	DEBUG	<- 200 OK {"value": {}}
1504282156039	webdriver::server	DEBUG	-> GET /session/d992be5c-30cb-4caa-99b8-a3388babfb26/alert/text 
1504282156041	geckodriver::marionette	TRACE	-> 28:[0,6,"getTextFromDialog",{}]
1504282156044	Marionette	TRACE	0 -> [0,6,"getTextFromDialog",{}]
1504282156045	Marionette	TRACE	0 <- [1,6,null,{"value":"This is an alert box!"}]
1504282156059	geckodriver::marionette	TRACE	<- [1,6,null,{"value":"This is an alert box!"}]
1504282156059	webdriver::server	DEBUG	<- 200 OK {"value":"This is an alert box!"}
1504282156062	webdriver::server	DEBUG	-> POST /session/d992be5c-30cb-4caa-99b8-a3388babfb26/elements {"value":"p","using":"css selector"}
1504282156063	geckodriver::marionette	TRACE	-> 57:[0,7,"findElements",{"using":"css selector","value":"p"}]
1504282156064	Marionette	TRACE	0 -> [0,7,"findElements",{"using":"css selector","value":"p"}]
1504282156067	Marionette	TRACE	0 <- [1,7,null,[{"element-6066-11e4-a52e-4f735466cecf":"fec4fdae-bff9-4acf-9d54-df6543d4eb75","ELEMENT":"fec4fdae-bff9-4acf-9d54-df6543d4eb75"}]]
1504282156068	geckodriver::marionette	TRACE	<- [1,7,null,[{"element-6066-11e4-a52e-4f735466cecf":"fec4fdae-bff9-4acf-9d54-df6543d4eb75","ELEMENT":"fec4fdae-bff9-4acf-9d54-df6543d4eb75"}]]
1504282156068	webdriver::server	DEBUG	<- 200 OK {"value":[{"element-6066-11e4-a52e-4f735466cecf":"fec4fdae-bff9-4acf-9d54-df6543d4eb75"}]}
1504282156074	webdriver::server	DEBUG	-> DELETE /session/d992be5c-30cb-4caa-99b8-a3388babfb26 
1504282156074	geckodriver::marionette	TRACE	-> 37:[0,8,"quit",{"flags":["eForceQuit"]}]
1504282156075	Marionette	TRACE	0 -> [0,8,"quit",{"flags":["eForceQuit"]}]
1504282156076	Marionette	INFO	New connections will no longer be accepted
1504282156144	Marionette	TRACE	0 <- [1,8,null,{"cause":"shutdown"}]
1504282156163	geckodriver::marionette	TRACE	<- [1,8,null,{"cause":"shutdown"}]
1504282156163	webdriver::server	DEBUG	Deleting session
1504282156163	geckodriver::marionette	DEBUG	Stopping browser process
1504282156245	webdriver::server	DEBUG	<- 200 OK {"value": {}}
1504282156256	webdriver::server	DEBUG	-> GET /shutdown 
1504282156258	webdriver::server	DEBUG	<- 404 Not Found {"value":{"error":"unknown command","message":"GET /shutdown did not match a known command","stacktrace":"stack backtrace:\n   0:   0x4e6bd4 - <no info>\n   1:   0x43e83c - <no info>\n   2:   0x438a45 - <no info>\n   3:   0x404310 - <no info>\n   4:   0x40bf30 - <no info>\n   5:   0x69d92b - <no info>\n   6:   0x42061e - <no info>\n   7:   0x6989e1 - <no info>\n   8: 0x745462c4 - BaseThreadInitThunk\n   9: 0x77670fd9 - RtlSubscribeWnfStateChangeNotification"}}
```

**Comment by andreastt** [comment]
[According to the specification](https://w3c.github.io/webdriver/webdriver-spec.html#dfn-find-element) it should be possible to find elements even when a user prompt is open.

**Comment by rshanley-micro-focus** [comment]
Hi Andreas,

Thanks for your comment _"According to the specification it should be possible to find elements even when a user prompt is open"_. However, I cannot find that in the specification. What I do read in the specification in [18. User Prompts](https://w3c.github.io/webdriver/webdriver-spec.html#user-prompts) seems to pretty clearly say the opposite:

> When a user prompt appears, it is the task of the subsequent command to handle it. If the subsequent requested command is not one listed in this chapter, an unexpected alert open error will be returned.

I have also checked the behaviour of the _ChromeDriver_ and it throws an exception when you call `findElements` while the alert is open, which complies with the above in the specification and it seems to me to make more sense to do that anyway. _ChromeDriver_ exception:

`org.openqa.selenium.UnhandledAlertException: unexpected alert open`

In my test the next "command" after showing the alert is `findElements()`. The only reason I could think of not to handle it there would be if `findElements `is not considered a _command_ (e.g. it is categorised as a _query_ and not a command). However, this would then not be consistent with the ChromeDriver implementation.

Do you not think it should be changed in _GeckoDriver_?

Regards,

Ray

**Comment by andreastt** [comment]
By that I mean that the [Find Element](https://w3c.github.io/webdriver/webdriver-spec.html#dfn-find-element) command doesn’t have an invocation of the user prompt handler. For that spec prose you quote to come into effect, the command would need to have a step like this:

> Handle any user prompts and return its value if it is an error.

That chromedriver returns an error for this only means it is not conforming on the specification, and you should file a bug with them.

**Comment by whimboo** [comment]
Lets reopen for now until https://github.com/w3c/webdriver/issues/1086 has been clarified.

**Comment by bhabanipattanayak** [comment]
You can ass this if you want to do some action for all the alerts
DesiredCapabilities browser = DesiredCapabilities.firefox(); 
browser.setCapability(CapabilityType.UNEXPECTED_ALERT_BEHAVIOUR, UnexpectedAlertBehaviour.IGNORE);
You can use UnexpectedAlertBehaviour.ACCEPT or UnexpectedAlertBehaviour.DISMISS
Same can be done for other drivers.

**Comment by whimboo** [comment]
This was actually fixed in https://bugzilla.mozilla.org/show_bug.cgi?id=1503015 for Firefox 65. We can consider an uplift to beta.
