### ISSUE TITLE
geckodriver fails to start Firefox due to "other os error"

### ISSUE THREAD

**Issue by wenJanus** [mozilla/geckodriver#940]
## System
* Version: geckodriver 0.18.0
* Platform: Windows 7
* Firefox: 55.0.3 (64-bit)
* Selenium: client-combined-3.5.3-nodeps

## Testcase
package ssm;

import org.testng.annotations.Test;
import org.testng.annotations.BeforeMethod;
import org.testng.annotations.AfterMethod;
import org.testng.annotations.DataProvider;
import org.testng.annotations.BeforeClass;

import java.io.File;

import org.openqa.selenium.Alert;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.firefox.FirefoxOptions;
import org.openqa.selenium.firefox.FirefoxProfile;
import org.openqa.selenium.firefox.internal.ProfilesIni;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.testng.Assert;
import org.testng.annotations.AfterClass;
import org.testng.annotations.BeforeTest;
import org.testng.annotations.AfterTest;
import org.testng.annotations.BeforeSuite;
import org.testng.annotations.AfterSuite;

public class LoginSSM {
	WebDriver driver;
	String BrowerType = commonFunc.BrowersType.FIREFOX.toString();

	@Test(dataProvider = "dp")
	public void login(Integer n, String s) {
		driver.get("https://10.175.192.123/");
		if (driver.getTitle().indexOf("Insecure Connection") != -1) {
			driver.findElement(By.id("advancedButton")).click();
			driver.findElement(By.id("exceptionDialogButton")).click();
			driver.findElement(By.id("exceptionDialogButton")).click();
			Alert alt = driver.switchTo().alert();
			alt.accept();
		}

		WebElement username = driver.findElement(By.name("username"));
		username.sendKeys("admin");
		WebElement pw = driver.findElement(By.name("password"));
		pw.sendKeys("Wapwap12");
		WebElement login = driver.findElement(By.xpath("//*[@id=\"loginPage\"]/form/div/div[1]/button"));
		login.click();
		String title = driver.getTitle();
		Assert.assertEquals("SES Systems Manager", title);
	}
	
	public void viewRole(Integer n, String s) {
		WebElement userandroles = driver.findElement(By.linkText("Users and Roles"));
		userandroles.click();
		WebElement pathtitle = driver.findElement(By.xpath("/html/body/div[1]/div/div/div/h1"));
		Assert.assertEquals(pathtitle, "User Management");
	}

	@BeforeMethod
	public void beforeMethod() {
	}

	@AfterMethod
	public void afterMethod() {
	}

	@DataProvider
	public Object[][] dp() {
		return new Object[][] { new Object[] { 1, "a" }, };
	}

	@BeforeClass
	public void beforeClass() {
	}

	@AfterClass
	public void afterClass() {
	}

	@BeforeTest
	public void beforeTest() {
		//find profile by path
		File profileDir = new File("C:/wenzhanye/Selenium/FirefoxProfile");
		FirefoxProfile profile = new FirefoxProfile(profileDir);
//		//find profile by name
//		ProfilesIni pi = new ProfilesIni();
//        FirefoxProfile profile = pi.getProfile("Selenium");
		profile.setAcceptUntrustedCertificates(true);
		profile.setAssumeUntrustedCertificateIssuer(true);
		DesiredCapabilities caps = new FirefoxOptions().setProfile(profile)
				.addTo(DesiredCapabilities.firefox());
		driver = new FirefoxDriver(caps);
	}

	@AfterTest
	public void afterTest() {
		driver.close();
	}

	@BeforeSuite
	public void beforeSuite() {
	}

	@AfterSuite
	public void afterSuite() {
		driver.quit();
	}

}

## Trace-level log
org.openqa.selenium.SessionNotCreatedException: Failed to start browser C:\Program Files\Mozilla Firefox\firefox.exe: other os error
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: host: 'CN00207480', ip: '147.128.121.22', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_111'
Driver info: driver.version: FirefoxDriver
remote stacktrace: stack backtrace:
   0:           0x4bb74f - <no info>
   1:           0x4bbea9 - <no info>
   2:           0x43ce8d - <no info>
   3:           0x4430dd - <no info>
   4:           0x447acf - <no info>
   5:           0x4203e1 - <no info>
   6:           0x407dc7 - <no info>
   7:           0x6d95b9 - <no info>
   8:           0x4173a7 - <no info>
   9:           0x6d38b3 - <no info>
  10:         0x76b959cd - BaseThreadInitThunk
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.W3CHandshakeResponse.lambda$new$0(W3CHandshakeResponse.java:57)
	at org.openqa.selenium.remote.W3CHandshakeResponse.lambda$getResponseFunction$2(W3CHandshakeResponse.java:104)
	at org.openqa.selenium.remote.ProtocolHandshake.lambda$createSession$24(ProtocolHandshake.java:359)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:958)
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:464)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:362)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:136)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:142)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:82)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:646)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:255)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:237)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:138)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:191)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:103)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:137)
	at ssm.LoginSSM.beforeTest(LoginSSM.java:92)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:523)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:224)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:146)
	at org.testng.TestRunner.beforeRun(TestRunner.java:626)
	at org.testng.TestRunner.run(TestRunner.java:594)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)

**Comment by wenJanus** [comment]
Add another Issue, this case run last Friday start up the browser need 1min

**Comment by andreastt** [comment]
I’m not sure what `Failed to start browser C:\Program Files\Mozilla Firefox\firefox.exe: other os error` means, but are you sure you have the correct geckodriver binary for your platform architecture?

**Comment by whimboo** [comment]
This is Windows, so it shouldn't matter if its the 32bit or 64bit version of geckodriver. But what I miss is a real trace log. Can you please check that again?

`other os error` here simply means that it doesn't fit into any of the known error codes.

**Comment by resmiar** [comment]
Go this error with the same set up:
1505458528251	geckodriver	INFO	geckodriver 0.18.0
1505458528273	geckodriver	INFO	Listening on 127.0.0.1:4015
1505458529407	geckodriver::marionette	INFO	Starting browser C:\Program Files\Mozilla Firefox\firefox.exe with args ["-marionette"]
1505458530316	addons.xpi	WARN	Error parsing extensions state: [Exception... "Component returned failure code: 0x80520012 (NS_ERROR_FILE_NOT_FOUND) [amIAddonManagerStartup.readStartupData]"  nsresult: "0x80520012 (NS_ERROR_FILE_NOT_FOUND)"  location: "JS frame :: resource://gre/modules/addons/XPIProvider.jsm :: loadExtensionState :: line 1596"  data: no] Stack trace: loadExtensionState()@resource://gre/modules/addons/XPIProvider.jsm:1596 < getInstallState()@resource://gre/modules/addons/XPIProvider.jsm:1631 < checkForChanges()@resource://gre/modules/addons/XPIProvider.jsm:3152 < startup()@resource://gre/modules/addons/XPIProvider.jsm:2246 < callProvider()@resource://gre/modules/AddonManager.jsm:271 < _startProvider()@resource://gre/modules/AddonManager.jsm:741 < startup()@resource://gre/modules/AddonManager.jsm:908 < startup()@resource://gre/modules/AddonManager.jsm:3122 < observe()@jar:file:///C:/Program%20Files/Mozilla%20Firefox/omni.ja!/components/addonManager.js:65
1505458532271	Marionette	INFO	Enabled via --marionette
Unable to read VR Path Registry from C:\Users\rresmi\AppData\Local\openvr\openvrpaths.vrpath
[GPU 12712] WARNING: pipe error: 109: file c:/builds/moz2_slave/m-rel-w64-00000000000000000000/build/src/ipc/chromium/src/chrome/common/ipc_channel_win.cc, line 346
1505458540557	Marionette	INFO	Listening on port 10182
1505458540608	Marionette	INFO	Listening on port 10182
1505458541108	Marionette	DEBUG	loaded listener.js
Sep 15, 2017 12:25:41 PM org.openqa.selenium.remote.ProtocolHandshake createSession

**Comment by AutomatedTester** [comment]
Closing as information was not added.

**Comment by whimboo** [comment]
This error could be visible if the executable of Firefox as specified can not be found. In case you are on a 64-bit Windows, make sure that you also have installed the 64-bit version of Firefox. Otherwise the installation folder will be found at: "C:/Program Files (x86)/Mozilla Firefox/".

**Comment by viteshk92** [comment]
ohk.. but it's downloaded in "C:/Program Files/Mozilla Firefox/".
firstly it was working fine..after few days i run the program so it showed me "**Other OS Error**"..
so what do you suggest?

**Comment by whimboo** [comment]
@viteshk92 please open a command shell on Windows and run the following command: `C:/Program Files/Mozilla Firefox/firefox.exe -console`. Then please attach all the log output of Firefox as new attachment to this issue. Thanks.

**Comment by viteshk92** [comment]
![image](https://user-images.githubusercontent.com/35993751/35675748-408af84a-076f-11e8-836a-86ed0fbe83f5.png)

**Comment by viteshk92** [comment]
showing blank in Firefox console

**Comment by whimboo** [comment]
Does `-attach-console` change something? Does Firefox correctly start up?

**Comment by viteshk92** [comment]
i tried once more it shows this in the screenshot below
![image](https://user-images.githubusercontent.com/35993751/35679777-436fb0f0-077e-11e8-88a0-1f3a4a83ee8e.png)

**Comment by viteshk92** [comment]
When i use -attach-console command firefox was able to start properly.. and doesn't show "unable to read VR path resigtry as shown in the screenshot as shown in the above comment..

**Comment by viteshk92** [comment]
now it's showing **"pipe error"** when i close the firefox and also its showing **"unable to read VR path resigtry"**.

![image](https://user-images.githubusercontent.com/35993751/35680224-bc7f4c16-077f-11e8-8323-4ee69821ca22.png)

**Comment by whimboo** [comment]
Ok, that looks fine. You don't have to worry about those warnings. Mind running the same, and with the additional `-marionette` option, and maybe also with `-profile %path%`. Maybe the %path% of the profile still exists, which was `C:\Users\vitesh\AppData\Local\Temp\rust_mozprofile.Ql337kYY5ATK` in your trace log on the other issue.

I wonder what's causing this I/O error.

**Comment by viteshk92** [comment]
i tried and got no issue and firefox is working opening properly

**Comment by viteshk92** [comment]
it working now.. What i did is that i re-installed my fire-fox in Program files(x86) file path.

**Comment by whimboo** [comment]
Ok, so given that you didn't specify the Firefox binary via the `moz:firefoxOptions` capability, the system default installation will be looked up. But as it looks like we fail here, because we do not care about `C:/Program Files/Mozilla Firefox/` bug only `C:/Program Files/Mozilla Firefox (x86)/`.

A better failure message should be available once https://bugzilla.mozilla.org/show_bug.cgi?id=1410838 has been fixed.

For finding the right path, I dupe this issue against #1045.
