### ISSUE TITLE
Exception in thread "main" org.openqa.selenium.WebDriverException: Error loading page

### ISSUE THREAD

**Issue by UjjawalSaini** [mozilla/geckodriver#942]
## System
 Version:  geckodriver v0.14.0 
 Platform: macOS 
 Firefox: 46.0.1 
 Selenium:  3.0.1

I am getting following exception when I am trying to access a url in firefox. After browser gets launched, it asks for certificates and then exception comes.

```
505150853418	geckodriver	INFO	Listening on 127.0.0.1:42963
Sep 11, 2017 10:57:33 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Attempting bi-dialect session, assuming Postel's Law holds true on the remote end
log4j:WARN No appenders could be found for logger (org.apache.http.client.protocol.RequestAddCookies).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
1505150853559	mozprofile::profile	INFO	Using profile path /var/folders/nl/95x6x38j2gx001lcz0phgkhmpd4qmv/T/rust_mozprofile.YH4aoSr5YKAA
1505150853560	geckodriver::marionette	INFO	Starting browser /Applications/Firefox.app/Contents/MacOS/firefox-bin
1505150853568	geckodriver::marionette	INFO	Connecting to Marionette on localhost:57037
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
1505150853964	Marionette	INFO	Listening on port 57037
Sep 11, 2017 10:57:34 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: W3C
Exception in thread "main" org.openqa.selenium.WebDriverException: Error loading page
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: host: '784f439ca45d', ip: '10.92.249.129', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.12.5', java.version: '1.8.0_131'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{rotatable=false, raisesAccessibilityExceptions=false, marionette=true, firefoxOptions={args=[], prefs={}}, appBuildId=20160502172042, version=, platform=MAC, proxy={}, specificationLevel=1, acceptSslCerts=false, browserVersion=46.0.1, platformVersion=16.6.0, XULappId={ec8030f7-c20a-464f-9b0e-13a3a9e97384}, browserName=Firefox, takesScreenshot=true, takesElementScreenshot=true, platformName=Darwin, device=desktop}]
Session ID: 9af066d1-f1c4-4849-a322-5bffafe1e8d2
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:127)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:93)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:42)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:163)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:82)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:601)
	at org.openqa.selenium.remote.RemoteWebDriver.get(RemoteWebDriver.java:322)
	at com.tgt.cyborg.npb.utils.LaunchBrowser.launchingBrowser(LaunchBrowser.java:17)
	at com.tgt.cyborg.npb.workflow.Workflow.init(Workflow.java:38)
	at com.tgt.cyborg.npb.core.BotInitializer.main(BotInitializer.java:13)
```

**Comment by andreastt** [comment]
I think `Exception in thread "main" org.openqa.selenium.WebDriverException: Error loading page` originates from `com.tgt.cyborg.pb.core.BotInitializer.main`, not geckodriver.

In any case it looks like Selenium is failing to connect to geckodriver. Firefox is being started and the Marionette server is listening.

geckodriver doesn’t support Firefox 46, so this isn’t surprising. I recommend using Firefox Nightly.
