### ISSUE TITLE
keyDown(Keys.SHIFT) not considered for sendKeys()

### ISSUE THREAD

**Issue by codingphil** [mozilla/geckodriver#944]
## System
* Version: 0.18
* Platform: Windows 10 Creators Update
* Firefox: 57.0a1 (2017-09-12) (64-Bit)
* Selenium: 3.5.3 (Java)

## Testcase
After calling `Actions.keyDown(Keys.SHIFT)` it is expected that the following `sendKeys()` call considers the pressed SHIFT key and uppercases all lower case characters passed to `sendKeys()` but actually the pressed SHIFT key is just ignored. See the Selenium JUnit test below.

```java
  @Test
  public void testKeyDownShift_sendKeys_keyUpShift_textIsUppercase() {
    // given
    webDriver.navigate().to("http://localhost/SimpleTextField.html");
    WebElement textFieldElem = webDriver.findElementByName("textfield");
    assertEquals("", textFieldElem.getAttribute("value"));
    textFieldElem.click();
    
    // when
    new Actions(webDriver).keyDown(Keys.SHIFT).sendKeys("abc").keyUp(Keys.SHIFT).perform();
    
    // then
    assertEquals("ABC", textFieldElem.getAttribute("value")); // <<=== FAILS
  }
```

## Stacktrace

```java
org.junit.ComparisonFailure: expected:<[ABC]> but was:<[abc]>
	at org.junit.Assert.assertEquals(Assert.java:115)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at SendKeysTests.testKeyDownShift_sendKeys_keyUpShift_textIsUppercase(SendKeysTests.java:439)
```

## Trace-level log

[geckodriver-log.txt](https://github.com/mozilla/geckodriver/files/1295045/geckodriver-log.txt)

**Comment by codingphil** [comment]
The used HTML page:
[SimpleTextField.html.zip](https://github.com/mozilla/geckodriver/files/1344653/SimpleTextField.html.zip)

**Comment by mjzffr** [comment]
I was able to reproduce this. 

Strangely enough, Marionette _does_ synthesize events that look right (i.e. the shift property on the event object is true when we expect it to be true) but that doesn't actually cause the browser to produce capitalized letters in the input field, apparently. =/

Details at: https://bugzilla.mozilla.org/show_bug.cgi?id=1405370

**Comment by Trucnt** [comment]
We have faced the same issue.

**Comment by altus34** [comment]
Same issue here

**Comment by TylerJackDurden** [comment]
With newer versions (0.21.0 gecko 3.13.0 selenium) still do not work on ff. Chrome, Edge work fine.

**Comment by whimboo** [comment]
As long as the before-mentioned bug is not fixed, it doesn't help us when you add `me too` comments. Thanks.
