### ISSUE TITLE
FirefoxDeveloperEdition not discovered

### ISSUE THREAD

**Issue by xmo-odoo** [mozilla/geckodriver#948]
## System
* Version: 0.18.0
* Platform: macOS 10.11.6
* Firefox: Developer Edition 56.0b10 (64-bit)
* Selenium: python 3.4.3

## Testcase
Don't have regular Firefox installed, have FirefoxDeveloperEdition installed
```
>>> from selenium import webdriver
>>> f = webdriver.Firefox()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "lib/python3.6/site-packages/selenium/webdriver/firefox/webdriver.py", line 154, in __init__
    keep_alive=True)
  File "lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 140, in __init__
    self.start_session(desired_capabilities, browser_profile)
  File "lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 229, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 297, in execute
    self.error_handler.check_response(response)
  File "lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: Unable to find a matching set of capabilities
```

symlink "Firefox.app" to "FirefoxDevelopmentEdition.app" and everything works fine.

## Trace-level log
```
> geckodriver -vvvvvv
1505288834027	geckodriver	INFO	geckodriver 0.18.0
1505288834028	webdriver::httpapi	DEBUG	Creating routes
1505288834035	geckodriver	INFO	Listening on 127.0.0.1:4444
```

**Comment by andreastt** [comment]
It is not meant to discover Firefox dev edition. In this case you’ll need to provide a path to the binary, either using the `binary` field in the [`moz:firefoxOptions`](https://github.com/mozilla/geckodriver#firefox-capabilities) object or with the `--binary PATH` flag to geckodriver.
