### ISSUE TITLE
Empty Firefox new session opened and then fialed to load URL

### ISSUE THREAD

**Issue by AmaranathaM** [mozilla/geckodriver#952]
## System
* Version: geckodriver-v0.18.0-win64
* Platform: Windows 7 64-bit
* Firefox: 55.0.3 (64-bit)
* Selenium: Selenium 3.4.0
* Java 1.8v

## Testcase
```java
                        DesiredCapabilities capabilities=DesiredCapabilities.firefox();
			capabilities.setCapability("marionette", true);
			driver = new FirefoxDriver(capabilities);
			
			System.out.println("Hello Test !!!!!!!");
			driver.manage().timeouts().implicitlyWait(60, TimeUnit.SECONDS);

			System.out.println("Hello Test !!!!!!!");
			driver.get("http://cdi-ag-pilot.sl.cloud9.ibm.com");
```

## Log
```
### 505716342250	geckodriver	INFO	Listening on 127.0.0.1:48065
1505716342911	mozprofile::profile	INFO	Using profile path C:\Users\IBM_AD~1\AppData\Local\Temp\rust_mozprofile.cwiZoutOuqAw
1505716342915	geckodriver::marionette	INFO	Starting browser C:\Program Files\Mozilla Firefox\firefox.exe
1505716342925	geckodriver::marionette	INFO	Connecting to Marionette on localhost:62354
1505716344524	addons.xpi	WARN	Error parsing extensions state: [Exception... "Component returned failure code: 0x80520012 (NS_ERROR_FILE_NOT_FOUND) [amIAddonManagerStartup.readStartupData]"  nsresult: "0x80520012 (NS_ERROR_FILE_NOT_FOUND)"  location: "JS frame :: resource://gre/modules/addons/XPIProvider.jsm :: loadExtensionState :: line 1596"  data: no] Stack trace: loadExtensionState()@resource://gre/modules/addons/XPIProvider.jsm:1596 < getInstallState()@resource://gre/modules/addons/XPIProvider.jsm:1631 < checkForChanges()@resource://gre/modules/addons/XPIProvider.jsm:3152 < startup()@resource://gre/modules/addons/XPIProvider.jsm:2246 < callProvider()@resource://gre/modules/AddonManager.jsm:271 < _startProvider()@resource://gre/modules/AddonManager.jsm:741 < startup()@resource://gre/modules/AddonManager.jsm:908 < startup()@resource://gre/modules/AddonManager.jsm:3122 < observe()@jar:file:///C:/Program%20Files/Mozilla%20Firefox/omni.ja!/components/addonManager.js:65
Unable to read VR Path Registry from C:\Users\IBM_ADMIN\AppData\Local\openvr\openvrpaths.vrpath
[GPU 12220] WARNING: pipe error: 109: file c:/builds/moz2_slave/m-rel-w64-00000000000000000000/build/src/ipc/chromium/src/chrome/common/ipc_channel_win.cc, line 346
Unable to read VR Path Registry from C:\Users\IBM_ADMIN\AppData\Local\openvr\openvrpaths.vrpath
[Child 11340] WARNING: pipe error: 109: file c:/builds/moz2_slave/m-rel-w64-00000000000000000000/build/src/ipc/chromium/src/chrome/common/ipc_channel_win.cc, line 346
[Child 11340] WARNING: pipe error: 109: file c:/builds/moz2_slave/m-rel-w64-00000000000000000000/build/src/ipc/chromium/src/chrome/common/ipc_channel_win.cc, line 346
org.testng.TestNGException: 
Cannot instantiate class com.ibm.cdi.automation.BaseTest
	at org.testng.internal.ObjectFactoryImpl.newInstance(ObjectFactoryImpl.java:31)
	at org.testng.internal.ClassHelper.createInstance1(ClassHelper.java:410)
	at org.testng.internal.ClassHelper.createInstance(ClassHelper.java:323)
	at org.testng.internal.ClassImpl.getDefaultInstance(ClassImpl.java:126)
	at org.testng.internal.ClassImpl.getInstances(ClassImpl.java:191)
	at org.testng.TestClass.getInstances(TestClass.java:99)
	at org.testng.TestClass.initTestClassesAndInstances(TestClass.java:85)
	at org.testng.TestClass.init(TestClass.java:77)
	at org.testng.TestClass.<init>(TestClass.java:42)
	at org.testng.TestRunner.initMethods(TestRunner.java:423)
	at org.testng.TestRunner.init(TestRunner.java:250)
	at org.testng.TestRunner.init(TestRunner.java:220)
	at org.testng.TestRunner.<init>(TestRunner.java:169)
	at org.testng.remote.support.RemoteTestNG6_10$1.newTestRunner(RemoteTestNG6_10.java:28)
	at org.testng.remote.support.RemoteTestNG6_10$DelegatingTestRunnerFactory.newTestRunner(RemoteTestNG6_10.java:61)
	at org.testng.SuiteRunner$ProxyTestRunnerFactory.newTestRunner(SuiteRunner.java:616)
	at org.testng.SuiteRunner.init(SuiteRunner.java:185)
	at org.testng.SuiteRunner.<init>(SuiteRunner.java:131)
	at org.testng.TestNG.createSuiteRunner(TestNG.java:1383)
	at org.testng.TestNG.createSuiteRunners(TestNG.java:1363)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1217)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.testng.internal.ObjectFactoryImpl.newInstance(ObjectFactoryImpl.java:23)
	... 25 more
Caused by: org.openqa.selenium.WebDriverException: connection refused
Command duration or timeout: 663.77 seconds
Build info: version: '3.4.0', revision: 'unknown', time: 'unknown'
System info: host: 'IBM662-PC0GXS9T', ip: '9.204.15.65', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_144'
Driver info: driver.version: FirefoxDriver
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:215)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:167)
	at org.openqa.selenium.remote.Gecko013ProtocolResponse.lambda$new$0(Gecko013ProtocolResponse.java:39)
	at org.openqa.selenium.remote.Gecko013ProtocolResponse.lambda$getResponseFunction$2(Gecko013ProtocolResponse.java:90)
	at org.openqa.selenium.remote.ProtocolHandshake.lambda$createSession$22(ProtocolHandshake.java:365)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:958)
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:464)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:368)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:159)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:142)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:82)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:637)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:250)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:236)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:137)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:191)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:108)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:104)
	at com.ibm.cdi.automation.BrowserInstance.getInstance(BrowserInstance.java:15)
	at com.ibm.cdi.automation.BaseTest.<init>(BaseTest.java:68)
	... 30 more
```

**Comment by AutomatedTester** [comment]
Do you have any Firewalls that are blocking the connection. Everything is starting up but the connection is being blocked.

**Comment by whimboo** [comment]
This is not geckodriver 0.18 which is in use here given that this would print its version to the log. So please check that, and as best upgrade to 0.19.0. Also please attach a trace log, which would contain more information. Thanks.

**Comment by AutomatedTester** [comment]
Closing as details have not been added
