### ISSUE TITLE
DELETE `/session/{session id}` no longer working

### ISSUE THREAD

**Issue by elgalu** [mozilla/geckodriver#957]
DELETE `/session/{session id}` no longer working since version 0.16.0

## System
* Version: 0.16.0 until 0.19.0 (inclusive) - Works ok with 0.15.0
* Platform: Linux - Ubuntu 16.04
* Firefox: 55.0.3 (latest)
* Selenium: 3.5.3 (latest) and Python bindings 3.5.0 (latest)

## Testcase
Complete test case at:
https://github.com/elgalu/docker-selenium/blob/3.5.3-p0/test/python_test.py#L229

Since version 0.16.0 we have to catch the error during `driver.quit()`

## Stacktrace
Python:
```
2017-09-18 15:32:20.946660 dosel - test-adwords - firefox - (13/14) Test done - will driver.quit()
Traceback (most recent call last):
  File "/usr/bin/python_test", line 225, in <module>
    driver.quit()
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 592, in quit
    self.execute(Command.QUIT)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 297, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: Tried to run command without establishing a connection
```

This has also been reported by JS nightwish users (not just python)
```
16:39:15.268 INFO - Handler thread for session ce860aff-e17b-44c3-9a75-ef85897abfc7 (firefox): Executing DELETE on /session/ce860aff-e17b-44c3-9a75-ef85897abfc7 (handler: ServicedSession)
```

## Trace-level log
```
/var/log/cont/firefox_driver.log:1505748737001  geckodriver INFO    Listening on 127.0.0.1:6805
/var/log/cont/firefox_driver.log:1505748737064  geckodriver::marionette INFO    Starting browser /home/seluser/firefox-for-sel-3/firefox with args ["-marionette"]
/var/log/cont/firefox_driver.log:1505748737260  addons.xpi  WARN    Error parsing extensions state: [Exception... "Component returned failure code: 0x80520012 (NS_ERROR_FILE_NOT_FOUND) [amIAddonManagerStartup.readStartupData]"  nsresult: "0x80520012 (NS_ERROR_FILE_NOT_FOUND)"  location: "JS frame :: resource://gre/modules/addons/XPIProvider.jsm :: loadExtensionState :: line 1596"  data: no] Stack trace: loadExtensionState()@resource://gre/modules/addons/XPIProvider.jsm:1596 < getInstallState()@resource://gre/modules/addons/XPIProvider.jsm:1631 < checkForChanges()@resource://gre/modules/addons/XPIProvider.jsm:3152 < startup()@resource://gre/modules/addons/XPIProvider.jsm:2246 < callProvider()@resource://gre/modules/AddonManager.jsm:271 < _startProvider()@resource://gre/modules/AddonManager.jsm:741 < startup()@resource://gre/modules/AddonManager.jsm:908 < startup()@resource://gre/modules/AddonManager.jsm:3122 < observe()@jar:file:///home/seluser/firefox-for-sel-3/omni.ja!/components/addonManager.js:65
/var/log/cont/firefox_driver.log:1505748737595  Marionette  INFO    Enabled via --marionette
/var/log/cont/firefox_driver.log:1505748738776  Marionette  INFO    Listening on port 32911
/var/log/cont/firefox_driver.log:JavaScript error: chrome://marionette/content/server.js, line 337: NS_ERROR_SOCKET_ADDRESS_IN_USE: Component returned failure code: 0x804b0036 (NS_ERROR_SOCKET_ADDRESS_IN_USE) [nsIServerSocket.initSpecialConnection]
/var/log/cont/firefox_driver.log:1505748738901  Marionette  DEBUG   loaded listener.js
/var/log/cont/firefox_driver.log:1505748739171  Marionette  DEBUG   Received DOM event "beforeunload" for "about:blank"
/var/log/cont/firefox_driver.log:1505748739192  Marionette  DEBUG   Received DOM event "pagehide" for "about:blank"
/var/log/cont/firefox_driver.log:1505748739192  Marionette  DEBUG   Received DOM event "unload" for "about:blank"
/var/log/cont/firefox_driver.log:1505748739332  Marionette  DEBUG   Received DOM event "DOMContentLoaded" for "http://172.17.0.2:8280/adwords/"
/var/log/cont/firefox_driver.log:1505748739337  Marionette  DEBUG   Received DOM event "DOMContentLoaded" for "http://172.17.0.2:8280/adwords/"
/var/log/cont/firefox_driver.log:1505748739339  Marionette  DEBUG   Received DOM event "pageshow" for "http://172.17.0.2:8280/adwords/"
```

**Comment by andreastt** [comment]
`selenium.common.exceptions.WebDriverException: Message: Tried to run command without establishing a connection` would kind of suggest you haven’t actually created a WebDriver session, which means your client is disconnecting at some point.

Without a trace-level log it is hard to say what happens.

**Comment by elgalu** [comment]
I think I found where the problem is; I was doing `driver.close()` plus `driver.quit()` and it simply worked.

From 0.16.0 doing both seems redundant.

Not sure why it worked before and why it works with Chrome but it looks like we can close this one.

**Comment by andreastt** [comment]
A difference in behaviour is something that should be investigated. Without a trace-level log I can’t actually tell what’s going on.

**Comment by elgalu** [comment]
I enabled the log level trace, as you say it tries to execute a DELETE on an already terminated session:

```
1505753594523	webdriver::server	DEBUG	-> DELETE /session/a8312282-af00-4931-94d4-0d401abf01c9 
1505753594524	webdriver::server	DEBUG	<- 500 Internal Server Error {"value":{"error":"session not created","message":"Tried to run command without establishing a connection","stacktrace":"stack backtrace:\n   0:           0x4f388c - backtrace::backtrace::trace::h736111741fa0878e\n   1:           0x4f38c2 - backtrace::capture::Backtrace::new::h63b8a5c0787510c9\n   2:           0x442c61 - webdriver::error::WebDriverError::new::hc4fe6a1ced4e57dd\n   3:           0x42a926 - <webdriver::server::Dispatcher<T, U>>::run::hba9181b5aacf8f04\n   4:           0x402c59 - std::sys_common::backtrace::__rust_begin_short_backtrace::h19de262639927233\n   5:           0x40c065 - std::panicking::try::do_call::h6c1659fc4d01af51\n   6:           0x5e38ec - panic_unwind::__rust_maybe_catch_panic\n                        at /checkout/src/libpanic_unwind/lib.rs:98\n   7:           0x420d32 - <F as alloc::boxed::FnBox<A>>::call_box::h953e5f59694972c5\n   8:           0x5dc00b - alloc::boxed::{{impl}}::call_once<(),()>\n                        at /checkout/src/liballoc/boxed.rs:661\n                         - std::sys_common::thread::start_thread\n                        at /checkout/src/libstd/sys_common/thread.rs:21\n                         - std::sys::imp::thread::{{impl}}::new::thread_start\n                        at /checkout/src/libstd/sys/unix/thread.rs:84"}}
```

Full trace [in this gist](https://gist.github.com/elgalu/6cc1da0c78bebfb2cf826d817e96243c)

**Comment by andreastt** [comment]
The relevant part to that log is this:

```
1505753594119	geckodriver::marionette	TRACE	-> 17:[0,21,"close",{}]
1505753594120	Marionette	TRACE	0 -> [0,21,"close",{}]
1505753594121	Marionette	TRACE	0 <- [1,21,null,[]]
1505753594121	geckodriver::marionette	TRACE	<- [1,21,null,[]]
1505753594121	webdriver::server	DEBUG	Last window was closed, deleting session
1505753594121	webdriver::server	DEBUG	Deleting session
1505753594121	geckodriver::marionette	DEBUG	Stopping browser process
1505753594364	webdriver::server	DEBUG	<- 200 OK {"value": []}
1505753594523	webdriver::server	DEBUG	-> DELETE /session/a8312282-af00-4931-94d4-0d401abf01c9 
1505753594524	webdriver::server	DEBUG	<- 500 Internal Server Error {"value":{"error":"session not created","message":"Tried to run command without establishing a connection","stacktrace":"stack backtrace:\n   0:           0x4f388c - backtrace::backtrace::trace::h736111741fa0878e\n   1:           0x4f38c2 - backtrace::capture::Backtrace::new::h63b8a5c0787510c9\n   2:           0x442c61 - webdriver::error::WebDriverError::new::hc4fe6a1ced4e57dd\n   3:           0x42a926 - <webdriver::server::Dispatcher<T, U>>::run::hba9181b5aacf8f04\n   4:           0x402c59 - std::sys_common::backtrace::__rust_begin_short_backtrace::h19de262639927233\n   5:           0x40c065 - std::panicking::try::do_call::h6c1659fc4d01af51\n   6:           0x5e38ec - panic_unwind::__rust_maybe_catch_panic\n                        at /checkout/src/libpanic_unwind/lib.rs:98\n   7:           0x420d32 - <F as alloc::boxed::FnBox<A>>::call_box::h953e5f59694972c5\n   8:           0x5dc00b - alloc::boxed::{{impl}}::call_once<(),()>\n                        at /checkout/src/liballoc/boxed.rs:661\n                         - std::sys_common::thread::start_thread\n                        at /checkout/src/libstd/sys_common/thread.rs:21\n                         - std::sys::imp::thread::{{impl}}::new::thread_start\n                        at /checkout/src/libstd/sys/unix/thread.rs:84"}}
1505753594533	webdriver::server	DEBUG	-> DELETE /session/a8312282-af00-4931-94d4-0d401abf01c9 
1505753594542	webdriver::server	DEBUG	<- 500 Internal Server Error {"value":{"error":"session not created","message":"Tried to run command without establishing a connection","stacktrace":"stack backtrace:\n   0:           0x4f388c - backtrace::backtrace::trace::h736111741fa0878e\n   1:           0x4f38c2 - backtrace::capture::Backtrace::new::h63b8a5c0787510c9\n   2:           0x442c61 - webdriver::error::WebDriverError::new::hc4fe6a1ced4e57dd\n   3:           0x42a926 - <webdriver::server::Dispatcher<T, U>>::run::hba9181b5aacf8f04\n   4:           0x402c59 - std::sys_common::backtrace::__rust_begin_short_backtrace::h19de262639927233\n   5:           0x40c065 - std::panicking::try::do_call::h6c1659fc4d01af51\n   6:           0x5e38ec - panic_unwind::__rust_maybe_catch_panic\n                        at /checkout/src/libpanic_unwind/lib.rs:98\n   7:           0x420d32 - <F as alloc::boxed::FnBox<A>>::call_box::h953e5f59694972c5\n   8:           0x5dc00b - alloc::boxed::{{impl}}::call_once<(),()>\n                        at /checkout/src/liballoc/boxed.rs:661\n                         - std::sys_common::thread::start_thread\n                        at /checkout/src/libstd/sys_common/thread.rs:21\n                         - std::sys::imp::thread::{{impl}}::new::thread_start\n                        at /checkout/src/libstd/sys/unix/thread.rs:84"}}
1505753594549	webdriver::server	DEBUG	-> GET /shutdown 
1505753594551 webdriver::server DEBUG <- 404 Not Found {"value":{"error":"unknown command","message":"GET /shutdown did not match a known command","stacktrace":"stack backtrace:\n 0: 0x4f388c - backtrace::backtrace::trace::h736111741fa0878e\n 1: 0x4f38c2 - backtrace::capture::Backtrace::new::h63b8a5c0787510c9\n 2: 0x442d88 - webdriver::error::WebDriverError::new::hea6d4dbf778b2b24\n 3: 0x43c65f - <webdriver::server::HttpHandler<U> as hyper::server::Handler>::handle::hd03629bd67672697\n 4: 0x403a04 - std::sys_common::backtrace::__rust_begin_short_backtrace::h32e6ff325c0d7f46\n 5: 0x40c036 - std::panicking::try::do_call::h5f902dc1eea01ffe\n 6: 0x5e38ec - panic_unwind::__rust_maybe_catch_panic\n at /checkout/src/libpanic_unwind/lib.rs:98\n 7: 0x4209a2 - <F as alloc::boxed::FnBox<A>>::call_box::h032bafb4b576d1cd\n 8: 0x5dc00b - alloc::boxed::{{impl}}::call_once<(),()>\n 
```

geckodriver is implicitly ending the session when the last window closes on the first line. When `driver.quit()` is called as the subsequent command it will fail because the session has already been implicitly deleted.

I would encourage you to file a bug on this with the client you’re using. It should detect that the session has been closed implicitly after `driver.close()` or ignore the response from `driver.quit()` in case the session has already been closed.
