### ISSUE TITLE
UnknownCommandError: POST /session/foo/moveto did not match a known command

### ISSUE THREAD

**Issue by kaiyoma** [mozilla/geckodriver#958]
## System
* Version: 0.19.0
* Platform: Windows 10
* Firefox: 55.0.3
* Selenium: 3.5.0

I have a test written in JS that is attempting to move the mouse over a `<div>`, like so:

```
driver.actions().mouseMove(wrappers[0]).perform(); // `wrappers` is an array of <div> elements
```

This test works perfectly in Chrome and Chrome Headless, but fails in Firefox:

```
     UnknownCommandError: POST /session/ff91f250-8eb1-44ba-94ae-1c55b5a96629/moveto did not match a known command
      at WebDriverError (node_modules\selenium-webdriver\lib\error.js:27:5)
      at UnknownCommandError (node_modules\selenium-webdriver\lib\error.js:304:5)
      at Object.throwDecodedError (node_modules\selenium-webdriver\lib\error.js:497:15)
      at parseHttpResponse (node_modules\selenium-webdriver\lib\http.js:519:13)
      at doSend.then.response (node_modules\selenium-webdriver\lib\http.js:441:30)
      at process._tickCallback (internal/process/next_tick.js:109:7)
  From: Task: mouseMove
      at thenableWebDriverProxy.schedule (node_modules\selenium-webdriver\lib\webdriver.js:807:17)
      at actions.map.action (node_modules\selenium-webdriver\lib\actions.js:124:23)
      at Array.map (native)
      at node_modules\selenium-webdriver\lib\actions.js:123:29
      at TaskQueue.execute_ (node_modules\selenium-webdriver\lib\promise.js:3092:14)
      at TaskQueue.executeNext_ (node_modules\selenium-webdriver\lib\promise.js:3075:27)
      at asyncRun (node_modules\selenium-webdriver\lib\promise.js:2982:25)
      at node_modules\selenium-webdriver\lib\promise.js:676:7
      at process._tickCallback (internal/process/next_tick.js:109:7)
  From: Task: ActionSequence.perform
      at ActionSequence.perform (node_modules\selenium-webdriver\lib\actions.js:122:33)
      at modal.js:55:51
      at ManagedPromise.invokeCallback_ (node_modules\selenium-webdriver\lib\promise.js:1384:14)
      at TaskQueue.execute_ (node_modules\selenium-webdriver\lib\promise.js:3092:14)
      at TaskQueue.executeNext_ (node_modules\selenium-webdriver\lib\promise.js:3075:27)
      at asyncRun (node_modules\selenium-webdriver\lib\promise.js:2935:27)
      at node_modules\selenium-webdriver\lib\promise.js:676:7
      at process._tickCallback (internal/process/next_tick.js:109:7)
```

**Comment by andreastt** [comment]
Your Selenium client appears not to support the W3C WebDriver protocol. The `/{session id}/moveto` endpoint isn’t supported by geckodriver. Could you file a bug against the client?

**Comment by kaiyoma** [comment]
Thanks for the fast response! Looks like a report was already filed against Selenium: https://github.com/SeleniumHQ/selenium/issues/4564

**Comment by andreastt** [comment]
Thanks for filing!
