### ISSUE TITLE
Legacy Firefox waits for visibility as well when the implicit wait is set but geckodriver doesn't

### ISSUE THREAD

**Issue by Rajagopalan-M** [mozilla/geckodriver#960]
Legacy Firefox driver not only waits for element to exist,it is also waiting for visibility as well. 

When I write 

**driver.manage.timeouts.implicit_wait=10**

This implicit wait is for both :exist and :visible in legacy Firefox driver but gecko driver only waits for exist not for visibility.

**Comment by AutomatedTester** [comment]
I have updated the comment but now wondering if this is for Find Elements only? If so then Marionette is doing the right thing here. What commands are you expecting it to wait on?

**Comment by Rajagopalan-M** [comment]
Actually `find_element` does wait until element exist in both legacy firefox driver and geckodriver but while I click the element, legacy firefox driver waits until element gets visible for the time which i set in implicit wait but geckodriver is not waiting 

For an example, consider the code
```
var=driver.find_element(:xpath, "//span[normalize-space()='usage details']")

var.click
```
Line 1 passes in both the cases, but when it comes to var.click, Legacy firefox is waiting until the element gets visible but geckodriver is not waiting for visibility and it immediately throws the error.

**Comment by AutomatedTester** [comment]
@Rajagopalan-M element click doesnt say that we should so can you please raise an issue about this. the other element interaction commands do have it so we need to implement it

**Comment by AutomatedTester** [comment]
Raised https://bugzilla.mozilla.org/show_bug.cgi?id=1401163

**Comment by Rajagopalan-M** [comment]
Hi, I am new to this github, You seem to be asking to raise a bug and then in your second comment, you seem to be raised the bug. What should I do now?

**Comment by AutomatedTester** [comment]
@Rajagopalan-M sorry, please can you raise a bug against https://github.com/w3c/webdriver for interactable checks on `Element Click`.

**Comment by Rajagopalan-M** [comment]
Can I create this same question there? will that help? Or should I need justify my opinion as to why this has to be wait for visibility?

**Comment by AutomatedTester** [comment]
I have raised https://github.com/w3c/webdriver/issues/1097

**Comment by Rajagopalan-M** [comment]
@AutomatedTester  Thank you.

**Comment by Rajagopalan-M** [comment]
@AutomatedTester 

I realized this issue still persist with different error

```
WebDriverError@chrome://marionette/content/error.js:178:5: Element <a href="#"> could not be scrolled into view (Selenium::WebDriver::Error::ElementNotInteractableError)
	from ElementNotInteractableError@chrome://marionette/content/error.js:286:5
	from webdriverClickElement@chrome://marionette/content/interaction.js:158:11
	from interaction.clickElement@chrome://marionette/content/interaction.js:129:11
	from clickElement/<@chrome://marionette/content/listener.js:1221:14
	from navigate/<@chrome://marionette/content/listener.js:415:13
	from navigate@chrome://marionette/content/listener.js:414:13
	from clickElement@chrome://marionette/content/listener.js:1220:5
	from C:/Ruby231/lib/ruby/gems/2.3.0/gems/selenium-webdriver-3.8.0/lib/selenium/webdriver/remote/response.rb:69:in `assert_ok'
	from C:/Ruby231/lib/ruby/gems/2.3.0/gems/selenium-webdriver-3.8.0/lib/selenium/webdriver/remote/response.rb:32:in `initialize'
	from C:/Ruby231/lib/ruby/gems/2.3.0/gems/selenium-webdriver-3.8.0/lib/selenium/webdriver/remote/http/common.rb:81:in `new'
	from C:/Ruby231/lib/ruby/gems/2.3.0/gems/selenium-webdriver-3.8.0/lib/selenium/webdriver/remote/http/common.rb:81:in `create_response'
	from C:/Ruby231/lib/ruby/gems/2.3.0/gems/selenium-webdriver-3.8.0/lib/selenium/webdriver/remote/http/default.rb:104:in `request'
	from C:/Ruby231/lib/ruby/gems/2.3.0/gems/selenium-webdriver-3.8.0/lib/selenium/webdriver/remote/http/common.rb:59:in `call'
	from C:/Ruby231/lib/ruby/gems/2.3.0/gems/selenium-webdriver-3.8.0/lib/selenium/webdriver/remote/bridge.rb:164:in `execute'
	from C:/Ruby231/lib/ruby/gems/2.3.0/gems/selenium-webdriver-3.8.0/lib/selenium/webdriver/remote/w3c/bridge.rb:535:in `execute'
	from C:/Ruby231/lib/ruby/gems/2.3.0/gems/selenium-webdriver-3.8.0/lib/selenium/webdriver/remote/w3c/bridge.rb:358:in `click_element'
	from C:/Ruby231/lib/ruby/gems/2.3.0/gems/selenium-webdriver-3.8.0/lib/selenium/webdriver/common/element.rb:72:in `click'
	from C:/Users/rajagopalan.m/RubymineProjects/Rajagopalan/Example.rb:9:in `<top (required)>'
	from -e:1:in `load'
	from -e:1:in `<main>'

```
