### ISSUE TITLE
AddExtension for E10s extension throws exception

### ISSUE THREAD

**Issue by furqanmlk** [mozilla/geckodriver#963]
## System
* Version: v0.19.0
* Platform: Win 10x64
* Firefox: FF 55
* Selenium: 3.5.1

## Expected Behavior 
FirefoxProfile profile = new FirefoxProfile();
profile.AddExtension(@"..\\e10ssaffplg.xpi")
Should be able to add extension to Firefox

## Actual Behavior
"Error installing extension"
![image](https://user-images.githubusercontent.com/6909890/30652124-8d120e76-9df5-11e7-98ff-f50d42ca8d8b.png)

## Stacktrace

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
   at System.Xml.XmlDownloadManager.GetStream(Uri uri, ICredentials credentials, IWebProxy proxy, RequestCachePolicy cachePolicy)
   at System.Xml.XmlUrlResolver.GetEntity(Uri absoluteUri, String role, Type ofObjectToReturn)
   at System.Xml.XmlTextReaderImpl.OpenUrlDelegate(Object xmlResolver)
   at System.Threading.CompressedStack.runTryCode(Object userData)
   at System.Runtime.CompilerServices.RuntimeHelpers.ExecuteCodeWithGuaranteedCleanup(TryCode code, CleanupCode backoutCode, Object userData)
   at System.Threading.CompressedStack.Run(CompressedStack compressedStack, ContextCallback callback, Object state)
   at System.Xml.XmlTextReaderImpl.OpenUrl()
   at System.Xml.XmlTextReaderImpl.Read()
   at System.Xml.XmlLoader.Load(XmlDocument doc, XmlReader reader, Boolean preserveWhitespace)
   at System.Xml.XmlDocument.Load(XmlReader reader)
   at System.Xml.XmlDocument.Load(String filename)
   at OpenQA.Selenium.Firefox.FirefoxExtension.ReadIdFromInstallRdf(String root)

**Comment by andreastt** [comment]
That looks like an error originating from your system/client, but did you try with Firefox 57?

**Comment by whimboo** [comment]
@furqanmlk is that an extension which is based on the WebExtensions API? If yes, your client doesn't support using such kind of extension yet. It is looking for an `install.rdf` file which doesn't exist in that XPI package.

**Comment by andreastt** [comment]
Closing for inactivity.
